migrate SourceHubspot to cdk
airbytehq/airbyte pull request #10177
Opened 2022-02-08 11:39 UTC by augan-rymkhan

## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

2022-02-11 09:50 UTC, augan-rymkhan commented
/test connector=connectors/source-hubspot

2022-02-11 11:51 UTC, augan-rymkhan commented
/test connector=connectors/source-hubspot

2022-02-11 13:00 UTC, augan-rymkhan commented on airbyte-integrations/connectors/source-hubspot/source_hubspot/api.py
> +    _name: str = None
This property is added to define stream name when use CRMSearchStream, CRMObjectIncrementalStream general (template) stream. So self._name = "companies"  matches to  `schema/companies.json`

2022-02-11 13:04 UTC, augan-rymkhan commented on airbyte-integrations/connectors/source-hubspot/source_hubspot/api.py
> +            json_schema["properties"]["properties"] = {"type": "object", "properties": self.properties}
Some entities has dynamic set of properties, so we trying to resolve those at runtime

2022-02-11 13:06 UTC, augan-rymkhan commented on airbyte-integrations/connectors/source-hubspot/source_hubspot/api.py
> +            self.state = stream_state
Set initial `state` which is got from `connector_state` mapping, passed from `AbstractSource` `_read_incremental` method.

2022-02-11 13:11 UTC, augan-rymkhan commented on airbyte-integrations/connectors/source-hubspot/source_hubspot/api.py
> +class Campaigns(Stream):
Refactored stream names so its snake case version matches to `schemas/campaigns.json`

2022-02-11 13:12 UTC, augan-rymkhan commented on airbyte-integrations/connectors/source-hubspot/source_hubspot/source.py
> +                    continue
This method is overridden to check whether the stream `quotes` exists in the source, if not skip reading that stream.

2022-02-11 23:19 UTC, keu commented on airbyte-integrations/connectors/source-hubspot/source_hubspot/source.py
> +            CRMSearchStream(
@augan-rymkhan I propose to follow here the practice we have in many other connectors:
make these attribute of class and create explicit classes for each stream, i.e.
```python
class Contacts(HubspotCRMSearchStream):
   entity = "contact"
   cursor_field = "lastmodifieddate"
   associations=["contacts"]
```

2022-02-11 23:22 UTC, keu commented on airbyte-integrations/connectors/source-hubspot/source_hubspot/api.py
> +        return self.updated_at_field
unnecessary indirection, lets just rename it to cursor_field

2022-02-11 23:51 UTC, keu requested changes
nice job! but the current PR feels more like a wrapper/adapter around the legacy codebase to fit cdk interface,
not sure if that matches the description of the ticket - i.e. the code doesn't look like following our best practice and utilize CDK classes (slices, HTTPStream, etc)
just a sidenote

2022-02-14 18:54 UTC, keu approved these changes
lgtm

2022-02-16 07:11 UTC, sergei-solonitcyn approved these changes

2022-02-17 16:32 UTC, augan-rymkhan commented
/test connector=connectors/source-hubspot

2022-02-18 11:29 UTC, augan-rymkhan commented
/test connector=connectors/source-hubspot

2022-02-18 12:10 UTC, augan-rymkhan commented
/test connector=connectors/source-hubspot

2022-02-18 18:28 UTC, keu commented on airbyte-integrations/connectors/source-hubspot/acceptance-test-config.yml
> +        email_events: ["created"]
if it matches the cursor_field in a stream (catalog) then you don't need cusor_paths for this stream (and any of them)
the purpose of `cursor_paths` is to handle cases when the path in the STATE file is nested
```json
"some_field": {
   "cursor_field": "value"
}
```

2022-02-18 18:31 UTC, keu approved these changes

2022-02-21 05:39 UTC, sergei-solonitcyn approved these changes

2022-02-21 07:50 UTC, augan-rymkhan commented
/test connector=connectors/source-hubspot

2022-02-21 13:09 UTC, augan-rymkhan commented
/test connector=connectors/source-hubspot

2022-02-21 15:13 UTC, augan-rymkhan commented
/test connector=connectors/source-hubspot

2022-02-21 15:43 UTC, augan-rymkhan commented
/publish connector=connectors/source-hubspot

2022-02-21 16:03 UTC, merged