Add banner when there is a problem with credits
airbytehq/airbyte pull request #10430
Opened 2022-02-17 22:01 UTC by juliachvyrova

## What
Add red banner at top of page when there is a problem with credits

<img width="1431" alt="Снимок экрана 2022-02-18 в 16 14 38" src="https://user-images.githubusercontent.com/9026944/154689444-c98db61a-7178-40f9-90b9-f5557a811ce9.png">

Closes #9755

2022-02-17 22:51 UTC, jrhizor approved these changes

2022-02-18 10:44 UTC, timroes requested changes
Some contrast ratio issue and some typing correction. Besides that looks good.

2022-02-18 10:44 UTC, timroes commented on airbyte-webapp/src/packages/cloud/views/layout/MainView/components/CreditsProblemBanner.tsx
> +  color: ${({ theme }) => theme.whiteColor};
We need to use black text on that background color to achieve the proper (see https://color.review/check/FFFFFF-FF6A4D).

2022-02-18 10:44 UTC, timroes commented on airbyte-webapp/src/packages/cloud/views/layout/MainView/components/CreditsProblemBanner.tsx
> +  color: ${({ theme }) => theme.whiteColor};
Same here, should use black text.

2022-02-18 13:24 UTC, timroes approved these changes
Code LGTM, haven't tested locally.

2022-02-20 18:53 UTC, merged