Added support for Amazon DocumentDB to the mongodb source connector
airbytehq/airbyte pull request #10995
Opened 2022-03-09 19:47 UTC by awill1

## What
This PR adds support to the MongoDB source connector for Amazon DocumentDB when TLS is enabled. Prior to this PR, the connection could not be made because of a certificate validation error.

A new MongoDb Instance Type was added called *Amazon DocumentDB*. 
Here is a screenshot of the new *Amazon DocumentDB* MongoDb Instance Type in the MongoDB source UI.
![Screen Shot 2022-03-09 at 2 31 19 PM](https://user-images.githubusercontent.com/1019585/157517489-9e8576dc-8c28-4462-b9a2-08c5bd4fba4f.png)

## How
Installs Amazon DocumentDB CA certs on the MongoDB source docker image in the default Java keystore. Having these certs installed in the docker image allows support for Amazon DocumentDB sources with TLS enabled.

A new MongoDb Instance Type was added called *Amazon DocumentDB*. This type was added because the jdbc connection string is slightly different as recommended by Amazon. Specifically it is connecting to a replica set and should use the cluster host.

## Recommended reading order
1. `airbyte-db/lib/src/main/java/io/airbyte/db/mongodb/MongoUtils.java`
2. `airbyte-integrations/connectors/source-mongodb-v2/src/main/resources/spec.json`
3. `airbyte-integrations/connectors/source-mongodb-v2/src/main/java/io.airbyte.integrations.source.mongodb/MongoDbSource.java`
4. `airbyte-integrations/connectors/source-mongodb-v2/Dockerfile`

## User Impact

There should be no breaking changes. This solution extends the existing MongoDb Instance Types and adds certs to the default keystore. No changes to existing code, only addition of code.

A new MongoDb Instance Type was added called *Amazon DocumentDB* in the MongoDB source UI..

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

2022-03-09 19:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=10995) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=10995) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=10995) it.</sub>

2022-03-10 15:30 UTC, awill1 commented
I an having a problem creating integration tests for Amazon DocumentDB. I tried to add integration tests for connecting to Amazon DocumentDB,  just like we have for the other MongoDB instance types (Standalone, Replica Set, and MongoDB Atlas). Amazon DocumentDB is a hosted MongoDB solution similar to MongoDB Atlas. The Atlas integration tests require the contributor to sign up for a free Atlas account and database to allow the tests to connect to the hosted database. Amazon Document DB does not have a forever free option, so I do not think it is reasonable to make contributors sign up for AWS and create a DocumentDB. Connecting to the DocumentDB with TLS is the core functionality I added in this PR. I would like to test it with an integration test, but I don't know how to test it without a hosted DB to connect to. What should I do about the Amazon DocumentDB integration test?

2022-03-11 00:09 UTC, marcosmarxm requested changes
some comments

2022-03-11 00:09 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-mongodb-v2/src/main/resources/import-rds-cert.sh
> +storepassword=changeit
you need to change this to generate the certificate?

2022-03-11 00:09 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-mongodb-v2/src/main/resources/import-rds-cert.sh
> +storepassword=changeit
this is going to generate a static certificate when publishing the connector.

2022-03-11 00:10 UTC, marcosmarxm commented
>I would like to test it with an integration test, but I don't know how to test it without a hosted DB to connect to. What should I do about the Amazon DocumentDB integration test?
If there is a testcontainer you can setup it, if doesn't you need to use the hosted connection.

2022-03-11 00:56 UTC, kodeine commented
Would it be possible to test with Digital Ocean managed mongodb cluster? It provided TLS cert as well.

2022-03-11 20:06 UTC, awill1 commented
@kodeine I will need to rework this PR to get broader support for Digital Ocean's hosted mongodb instances. I looked at other connectors to find a model and the Oracle Database connector also has a way to include TLS certificates. I am going to try to port that pattern over to the mongodb connector which will simplify the UI changes.

2022-03-11 20:35 UTC, kodeine commented
@awill1 would really appreciate your help and it will be a great addition for the community! thank you

2022-03-17 14:32 UTC, marcosmarxm commented
@awill1 do you want to continue working on this contribution?

2022-03-23 20:03 UTC, kodeine commented
@marcosmarxm this PR will fix other related tickets as well, just mentioning them here so the authors get to know once this PR is merged.
#7379 
#9843

2022-03-24 16:16 UTC, kodeine commented
@awill1 I think TLS should be checked as default just for better security but if someone wants they can uncheck it. As long its not mandatory its good.

2022-04-19 21:27 UTC, marcosmarxm commented
@awill1 are you planning to continue the work here? Maybe break between TLS and DocumentDB?

2022-05-02 14:11 UTC, closed without merging

2022-10-26 03:32 UTC, kodeine commented
@awill1 
were you able to get this pushed? Kindly let us know. Thanks

2022-11-24 12:17 UTC, ecylmz commented
@awill1 hi,

We look forward to good news from you :cry: