Source Mailchimp: update documentation
airbytehq/airbyte pull request #11352
Opened 2022-03-23 12:13 UTC by annalvova05

## What
Close #11347 

## How
Update documentation

## Recommended reading order
1. `spec.json`
2. `mailchimp.md`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

2022-03-29 18:01 UTC, lazebnyi approved these changes

2022-04-18 20:46 UTC, misteryeo requested changes
Added a few comments and feedback.

FYI @andyjih

2022-04-18 20:46 UTC, misteryeo commented on docs/integrations/sources/mailchimp.md
> +For Apikey authorization:
```suggestion
For API Key authorization:
```

2022-04-18 20:46 UTC, misteryeo commented on docs/integrations/sources/mailchimp.md
> +* Mailchimp client_id
```suggestion
* Mailchimp `client_id`
```

2022-04-18 20:46 UTC, misteryeo commented on docs/integrations/sources/mailchimp.md
> +* Mailchimp client_secret
```suggestion
* Mailchimp `client_secret`
```

2022-04-18 20:46 UTC, misteryeo commented on docs/integrations/sources/mailchimp.md
> +4. On the Set up the source page, enter the name for the Mailchimp connector and select **Mailchimp** from the Source type dropdown.
```suggestion
4. On the source setup page, elect **Mailchimp** from the Source type dropdown and enter a name for this connector.
```

2022-04-18 20:46 UTC, misteryeo commented on docs/integrations/sources/mailchimp.md
> +4. On the Set up the source page, enter the name for the Mailchimp connector and select **Mailchimp** from the Source type dropdown.
We no longer require the name to be filled before the dropdown in our UI.

2022-04-18 20:46 UTC, misteryeo commented on docs/integrations/sources/mailchimp.md
> +1. For using an API key [create account](https://mailchimp.com/developer/marketing/guides/quick-start/#create-an-account)
```suggestion
1. For using an API key, [create an account](https://mailchimp.com/developer/marketing/guides/quick-start/#create-an-account) 
```

2022-04-18 20:46 UTC, misteryeo commented on docs/integrations/sources/mailchimp.md
> +The Mailchimp source connector supports the following [sync modes](https://docs.airbyte.com/getting-started-with-airbyte-cloud/core-concepts#connection-sync-modes):
Looks like this link is broken?

cc: @Amruta-Ranade are all of these links broken due to the migration?

2022-04-18 20:46 UTC, misteryeo commented on docs/integrations/sources/mailchimp.md
> +We don't support Incremental Deletes for `Campaigns`, `Lists`, and `Email Activity` streams.
```suggestion
We don't support Incremental Deletes for `Campaigns`, `Lists`, and `Email Activity` streams because
```

2022-04-18 20:46 UTC, misteryeo commented on docs/integrations/sources/mailchimp.md
> +Mailchimp doesn't give any information about deleted data in these streams.
Make sure this sentence continues from the prior sentence.

2022-04-20 16:54 UTC, misteryeo approved these changes

2022-04-21 10:53 UTC, annalvova05 commented
/test connector=connectors/source-mailchimp

2022-04-21 11:17 UTC, annalvova05 commented
/publish connector=connectors/source-mailchimp

2022-04-21 11:31 UTC, annalvova05 commented
/publish connector=connectors/source-mailchimp

2022-04-21 11:56 UTC, merged