Upgrade MySQL to dbt 1.0.0
airbytehq/airbyte pull request #11470
Opened 2022-03-28 13:38 UTC by alafanechere

## What
`dbt-mysql` now supports DBT 1.0.0
Closes https://github.com/airbytehq/airbyte/issues/9484

## How
* Edit `mysql.Dockerfile`
* Use `event-buffer-size` in test for `normalization-mysql`
* Bump normalization version

2022-03-28 13:47 UTC, alafanechere commented
/test connector=bases/base-normalization

2022-03-28 14:21 UTC, ChristopheDuong commented
You might need to tweak the `dbt_project.yml` files as it was done here for this upgrade: https://github.com/airbytehq/airbyte/pull/11051

2022-03-28 14:23 UTC, ChristopheDuong requested changes
To upgrade to dbt 1.0.0, you might need to tweak the dbt_project.yml files as it was done in the PR https://github.com/airbytehq/airbyte/pull/11051

2022-03-29 21:42 UTC, alafanechere commented
/test connector=bases/base-normalization

2022-03-30 11:07 UTC, ChristopheDuong commented
It seems the failing tests may be related to https://github.com/airbytehq/airbyte/pull/11267#discussion_r838403965  maybe?

2022-03-30 11:13 UTC, ChristopheDuong approved these changes
Could you check the event-buffer-size option issue from https://github.com/airbytehq/airbyte/pull/11578 while you are publishing this please?

2022-03-30 11:27 UTC, alafanechere commented
/test connector=bases/base-normalization

2022-03-30 12:15 UTC, alafanechere commented
/test connector=bases/base-normalization

2022-03-31 09:30 UTC, alafanechere commented
/test connector=bases/base-normalization

2022-03-31 13:17 UTC, alafanechere commented
/test connector=bases/base-normalization

2022-03-31 17:23 UTC, alafanechere commented
/test connector=bases/base-normalization

2022-03-31 17:54 UTC, alafanechere commented
@ChristopheDuong the test ^ failed because the build of `destination-mssql` image failed:
```
#8 [build 4/4] RUN tar xf destination-mssql.tar --strip-components=1 && rm -rf destination-mssql.tar
#8 sha256:6aef1e7c3a165e325a1e5265e05c5ece72ce34711b89d8743a4a14875268dc37
#8 0.408 tar: destination-mssql.tar: Cannot open: No such file or directory
#8 0.408 tar: Error is not recoverable: exiting now
#8 ERROR: executor failed running [/bin/sh -c tar xf $***APPLICATION***.tar --strip-components=1 && rm -rf $***APPLICATION***.tar]: exit code: 2
```

Do you have an idea for the root cause?

2022-04-01 07:49 UTC, alafanechere commented
/test connector=bases/base-normalization

2022-04-01 09:41 UTC, alafanechere commented
@ChristopheDuong now tests are failing for a more intelligible reason:
```
 AssertionError: docker run --rm --init -v /actions-runner/_work/airbyte/airbyte/airbyte-integrations/bases/base-normalization/integration_tests/normalization_test_output/mysql/test_simple_streams:/workspace -v /actions-runner/_work/airbyte/airbyte/airbyte-integrations/bases/base-normalization/integration_tests/normalization_test_output/mysql/test_simple_streams/build:/build -v /actions-runner/_work/airbyte/airbyte/airbyte-integrations/bases/base-normalization/integration_tests/normalization_test_output/mysql/test_simple_streams/logs:/logs -v /tmp:/tmp --network host --entrypoint /usr/local/bin/dbt -i airbyte/normalization-mysql:dev --event-buffer-size=10000 run --profiles-dir=/workspace --project-dir=/workspace --full-refresh
	 E         	terminated with return code 1 with 5 'Error/Warning/Fail' mention(s).
	 E       assert 5 == 0
	 E         +5
	 E         -0
```

2022-04-01 09:48 UTC, ChristopheDuong commented
the useful eror in the log would be
```
 	 08:24:58  Finished running 6 view models, 14 table models in 1.23s.
	 08:24:58  
	 08:24:58  Completed with 5 errors and 0 warnings:
	 08:24:58  
	 08:24:58  Database Error in model 1_prefix_startwith_number_scd (models/generated/airbyte_incremental/scd/test_normalization_ci_txjrr/1_prefix_startwith_number_scd.sql)
	 08:24:58    1292 (22007): Truncated incorrect DOUBLE value: '-'
	 08:24:58    compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_incremental/scd/test_normalization_ci_txjrr/1_prefix_startwith_number_scd.sql
	 08:24:58  
	 08:24:58  Database Error in model dedup_cdc_excluded_scd (models/generated/airbyte_incremental/scd/test_normalization_ci_txjrr/dedup_cdc_excluded_scd.sql)
	 08:24:58    1292 (22007): Truncated incorrect DOUBLE value: '-'
	 08:24:58    compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_incremental/scd/test_normalization_ci_txjrr/dedup_cdc_excluded_scd.sql
	 08:24:58  
	 08:24:58  Database Error in model dedup_exchange_rate_scd (models/generated/airbyte_incremental/scd/test_normalization_ci_txjrr/dedup_exchange_rate_scd.sql)
	 08:24:58    1292 (22007): Truncated incorrect DOUBLE value: '-'
	 08:24:58    compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_incremental/scd/test_normalization_ci_txjrr/dedup_exchange_rate_scd.sql
	 08:24:58  
	 08:24:58  Database Error in model multiple_column_names_conflicts_scd (models/generated/airbyte_incremental/scd/test_normalization_ci_txjrr/multiple_column_names_conflicts_scd.sql)
	 08:24:58    1292 (22007): Truncated incorrect DOUBLE value: '-'
	 08:24:58    compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_incremental/scd/test_normalization_ci_txjrr/multiple_column_names_conflicts_scd.sql
	 08:24:58  
	 08:24:58  Database Error in model pos_dedup_cdcx_scd (models/generated/airbyte_incremental/scd/test_normalization_ci_txjrr/pos_dedup_cdcx_scd.sql)
	 08:24:58    1292 (22007): Truncated incorrect DOUBLE value: '-'
	 08:24:58    compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_incremental/scd/test_normalization_ci_txjrr/pos_dedup_cdcx_scd.sql
	 08:24:58  
	 08:24:58  Done. PASS=9 WARN=0 ERROR=5 SKIP=6 TOTAL=20
```

2022-04-07 21:47 UTC, edgao commented
for posterity: https://github.com/dbt-labs/dbt-utils/pull/373 broke mysql output; latest commit on this branch adds an override for mysql's concat logic.

test output has some odd capitalization diffs, which is weird but probably fine? (since mysql tablenames are case-insensitive)

2022-04-07 21:48 UTC, edgao commented
/test connector=bases/base-normalization

2022-04-07 22:14 UTC, edgao commented on airbyte-integrations/bases/base-normalization/integration_tests/normalization_test_output/mysql/test_nested_streams/first_output/airbyte_incremental/test_normalization/nested_stream_with_co___names_partition_data.sql
> +    p0.generated_number * power(2, 0)
`pow` and `power` are apparently equivalent https://stackoverflow.com/a/51615601

2022-04-08 00:03 UTC, edgao commented
tests failed due to https://github.com/airbytehq/airbyte/pull/9610 again (not sure why the comment didn't get edited though). Waiting for the test run on _that_ pr to finish, and will rerun tests here afterward. Realistically, I probably won't do that until tomorrow though.

2022-04-08 05:50 UTC, grubberr commented
> @ChristopheDuong the test ^ failed because the build of `destination-mssql` image failed:
> 
> ```
> #8 [build 4/4] RUN tar xf destination-mssql.tar --strip-components=1 && rm -rf destination-mssql.tar
> #8 sha256:6aef1e7c3a165e325a1e5265e05c5ece72ce34711b89d8743a4a14875268dc37
> #8 0.408 tar: destination-mssql.tar: Cannot open: No such file or directory
> #8 0.408 tar: Error is not recoverable: exiting now
> #8 ERROR: executor failed running [/bin/sh -c tar xf $***APPLICATION***.tar --strip-components=1 && rm -rf $***APPLICATION***.tar]: exit code: 2
> ```
> 
> Do you have an idea for the root cause?

I saw this problem a lot of time in past 
I suspect that it's some concurrency side effect when multiple gradle tasks running in parrallel 
( but to be honest I don't have 100% proves for this)

yesterday to work-around this problem in this PR https://github.com/airbytehq/airbyte/pull/9610
I have done this temp commit 
https://github.com/airbytehq/airbyte/pull/9610/commits/1c48d6e3e1de8b59958a275d8006a86dc7a1e37d

and it helped

2022-04-11 13:31 UTC, alafanechere commented
/test connector=bases/base-normalization

2022-04-11 13:31 UTC, alafanechere commented
Thanks @grubberr, let's give this a try 😄

2022-04-11 15:10 UTC, alafanechere commented
/test connector=bases/base-normalization

2022-04-11 16:17 UTC, alafanechere commented
@edgao does it mean we need wait for https://github.com/airbytehq/airbyte/pull/9610 to be merged?

2022-04-11 17:22 UTC, edgao commented
/test connector=bases/base-normalization

2022-04-11 17:23 UTC, edgao commented
sort of. Every time that PR gets `/test`-ed, it'll break tests everywhere else. I cleaned up our cluster again, so tests should be fixed here, hopefully

2022-04-11 18:39 UTC, grubberr commented
@alafanechere I see that our `base-normalization` tests are not good isolated, please do before running tests:

```
psql -h redshift-cluster-2.c5lzdndklo9c.us-east-2.redshift.amazonaws.com -p 5439 -d integrationtests --user awsuser

grubberr_test=# drop database integrationtests;
DROP DATABASE
grubberr_test=# create database integrationtests;
CREATE DATABASE
```

2022-04-11 21:58 UTC, edgao commented
hm, the last run still failed with the `tar: destination-mssql.tar: Cannot open: No such file or directory` error. gonna just retry it

2022-04-12 21:41 UTC, edgao commented
/publish connector=bases/base-normalization

2022-04-12 21:42 UTC, edgao commented
rebumped version to 0.1.77 and reattempting the publish

2022-04-13 14:19 UTC, alafanechere commented
@edgao is now failing with Snowflake 🤦 : 
`Operation failed because soft limit on objects of type 'Column' per table was exceeded. Please reduce number of 'Column's or contact Snowflake support about raising the limit.`
Do you think this is transient?

2022-04-13 23:04 UTC, edgao commented
that's just the logs being misleading. The real error is even higher:
```
	 Unable to find image 'airbyte/destination-bigquery:dev' locally
	 docker: Error response from daemon: manifest for airbyte/destination-bigquery:dev not found: manifest unknown: manifest unknown.
```
this is definitely transient; retrying.

I should put this in the readme later, but the way to find the "actual" error message:
1. Find the test summary (it's a red line of text, e.g. `============= 1 failed, 23 passed, 9 skipped in 2233.36s (0:37:13) =============`)
2. Above it, there are some lines that start with `FAILED`, e.g. `AILED integration_tests/test_ephemeral.py::test_destination_supported_limits[DestinationType.BIGQUERY-1000]`
3. Search the logs for the first occurrence of the text inside the brackets (e.g. `DestinationType.BIGQUERY-1000`)
4. Scroll down until you find the error. (in this specific example, it's kind of weird because it somehow got interleaved with a bunch of gradle messages so you have to scroll quite a long distance, but normally it's pretty close)

2022-04-20 15:43 UTC, alafanechere commented
@edgao I re-ran the test and found the following errors:
**MSSQL**
```ERROR i.a.i.b.FailureTrackingAirbyteMessageConsumer(start):39 - Exception while starting consumer
	 java.sql.SQLException: Cannot create PoolableConnectionFactory (Cannot open database "test_ephemeral" requested by the login. The login failed. ClientConnectionId:f0df6262-7a8b-4d03-9688-c1eacbf22507)
```

Do you think this is transient? Is the `test_ephemeral` DB created on test run?


**REDSHIFT** 
```
Error during updateVarcharDataColumnToSuperDataColumn() appears: 
	 java.sql.SQLException: [Amazon](500310) Invalid operation: cannot drop table _airbyte_raw_stream_with_1000_columnsckjyv column _airbyte_data because other objects depend on it 
	 Hint: Use DROP ... CASCADE to drop the dependent objects too.
```

Do you think this is because we need to clean some other test-related table from other test runs?


PS: thank you for explaining the process of spotting the right error message 🙏

2022-04-20 16:11 UTC, grubberr commented
@alafanechere about REDSHIFT I see that base-normalization test are not isolated
to make them PASS tyou need to re-create `integrationtests ` database 

```
psql -h redshift-cluster-2.c5lzdndklo9c.us-east-2.redshift.amazonaws.com -p 5439 -d integrationtests --user awsuser

drop database integrationtests;
create database integrationtests;
```

2022-04-20 16:57 UTC, edgao commented
how does this PR keep running into different errors :joy:

that _could_ be transient? The MSSQL test creates its own database, so it should just work.... retrying the test run.

Also, merged in master to get the changes from https://github.com/airbytehq/airbyte/pull/12064, which should fix the redshift normalization test.

2022-04-20 16:57 UTC, edgao commented
/test connector=bases/base-normalization

2022-04-20 17:03 UTC, grubberr commented
@edgao when you run 
`/test connector=bases/base-normalization`
you run normalization tests over all possible destinations we have

2022-04-21 09:07 UTC, alafanechere commented
> @edgao when you run `/test connector=bases/base-normalization` you run normalization tests over all possible destinations we have

Do we have a way to only run tests for Mysql normalization?

2022-04-21 14:36 UTC, edgao commented
@alafanechere fyi re: current test failure: discussion here https://airbytehq-team.slack.com/archives/C02U9R3AF37/p1650550398654509?thread_ts=1650534020.615949&cid=C02U9R3AF37 (apparently our formatter is forcing uppercase `REF`, but dbt requires lowercase `ref`)

2022-04-22 06:35 UTC, alafanechere commented
/publish connector=bases/base-normalization

2022-04-22 07:32 UTC, alafanechere commented
`docker: Error response from daemon: manifest for airbyte/destination-bigquery:dev not found: manifest unknown: manifest unknown.`

2022-04-22 16:07 UTC, edgao commented
I think we are still running into the REF error, also.

But that's pretty weird; I suspect there's a race condition in the build somewhere, but haven't been able to track it down. That error has been transient the other couple times I've seen it.

2022-04-22 22:16 UTC, edgao commented
/publish connector=bases/base-normalization

2022-04-22 22:54 UTC, edgao commented
/publish connector=bases/base-normalization

2022-04-23 15:58 UTC, grubberr commented
I see that problem with `REF` still not fixed
https://github.com/airbytehq/airbyte/runs/6136132925?check_suite_focus=true#step:17:20010

2022-04-23 19:59 UTC, edgao commented
nice, that means the CI script hack is working (or is at least not breaking anything) :P

but yeah, I think the `REF` thing is going to block publishing base-normalization until it's fixed

2022-04-25 13:17 UTC, alafanechere commented
@grubberr / @edgao do we have an issue for the `REF` thing?

2022-04-27 02:46 UTC, droxer commented
I encountered the basic normalization issue for mysql 8 destination.  And the issue can be fixed by upgrading dbt mysql 1.0.0 . do you mind I create another PR for the issue, or you will be keep working this https://github.com/airbytehq/airbyte/pull/11470 in next few days?

2022-04-27 06:19 UTC, grubberr commented
> @grubberr / @edgao do we have an issue for the `REF` thing?

I have created one https://github.com/airbytehq/airbyte/issues/12384

2022-04-27 11:18 UTC, alafanechere commented
Hi @droxer, we are currently trying to upgrade the MySQL adapter to 1.0.0. We are currently blocked by #12384 but it's on it's way.

2022-05-01 00:10 UTC, tuliren commented
/test connector=connectors/destination-mysql

2022-05-01 00:11 UTC, tuliren commented
The MySQL destination acceptance test has been broken for at least the last five days due to normalization. It's unclear how long it had been failing. So I triggered one to see if the new dbt version fixes this problem.

2022-05-05 13:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=11470) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=11470) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: edgao<br/>:x: alafanechere<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=11470) it.</sub>

2022-05-19 13:11 UTC, DoNotPanicUA commented
Hi @tuliren ,
Just want to let you know that MySql DAT is now fixed. There was an issue with the normalization but now it's fixed by #12924

2022-05-19 14:41 UTC, alafanechere commented
/test connector=bases/base-normalization

2022-06-15 21:22 UTC, edgao commented
going to publish skipping tests. I ran the mysql normalization tests locally and they passed.

2022-06-15 22:05 UTC, merged