#10938 fix docs and spec
airbytehq/airbyte pull request #11803
Opened 2022-04-07 14:45 UTC by davydov-d

## Source GA to Beta: fix specs and doc

2022-04-11 16:49 UTC, grubberr approved these changes

2022-04-11 16:51 UTC, grubberr requested changes
Please update `source_definitions.yaml`

2022-04-11 16:59 UTC, annalvova05 requested changes

2022-04-11 16:59 UTC, annalvova05 commented on airbyte-integrations/connectors/source-google-analytics-v4/source_google_analytics_v4/source.py
> +        auth_params = config["credentials"]
`credentials` is not a required field. We should leave `config.get("credentials")` for supporting old config version. We haven't the `credentials` field before OAuth implementation.
Same for other fields below.

2022-04-12 07:13 UTC, annalvova05 approved these changes

2022-04-12 07:59 UTC, davydov-d commented
> Please update `source_definitions.yaml`

after publishing a connector, the seed definitions yaml is version bumped & gradle processResources gets run automatically in CI

2022-04-12 08:04 UTC, grubberr approved these changes

2022-04-13 09:50 UTC, midavadim commented
This update can be released without Airbyte review

2022-04-13 10:03 UTC, davydov-d commented
/publish connector=connectors/source-google-analytics-v4

2022-04-13 10:31 UTC, merged