Multiple Template Sources: DRY acceptance test templates
airbytehq/airbyte pull request #12067
Opened 2022-04-15 10:07 UTC by daniel-cortez-stevenson

## What
- fixes #11836
- This change deduplicates common code between the source connector templates.

## How
I copied the `acceptance-test-config.yml.hbs` and
`acceptance-test-docker.sh` files from `source-python` into
a new directory called `source_acceptance_test_files` in
`connector-templates`.

`plopfile.js` now declares `sourceAcceptanceTestFilesInputRoot` and all
source templates, which use the common acceptance tests, perform an
additional `addMany` action to copy the common files into their
respective output root directories.

The affected connector templates are:
- `source-generic`
- `source-python`
- `source-python-http-api`
- `source-singer`

## Recommended reading order
1. `source_acceptance_test_files/*`
2. `plopfile.js`

## 🚨 User Impact 🚨
I expect no user impact, if things were done right.

## Pre-merge Checklist
<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

I believe the tests should be handled by CI, using the checked-in 'blank' connectors.

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

2022-04-15 10:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=12067) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=12067) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=12067) it.</sub>

2022-04-15 13:03 UTC, daniel-cortez-stevenson commented
@sherifnada Is this done as specified? Are we ready to approve running the additional workflows? 😃

2022-04-18 15:49 UTC, daniel-cortez-stevenson commented
We're getting an error in CI `Error: google-github-actions/setup-gcloud failed with: no credentials provided to export` - is this a known issue? @sherifnada who should be brought in to support here?

2022-04-18 22:13 UTC, sherifnada commented
@daniel-cortez-stevenson thanks for the contribution! I believe this is a known issue. Someone from the team will review shortly.

2022-04-22 17:59 UTC, alafanechere approved these changes
Thank you @daniel-cortez-stevenson for the contribution! 
I successfully generated the 4 types of connectors you mentioned.

2022-04-22 17:59 UTC, alafanechere commented
@pedroslopez do you want to go over a final review?

2022-04-22 19:01 UTC, pedroslopez reviewed
Thanks for contributing! I only have one comment on some differences between some of the generated ``acceptance-test-config.yml` files. Not a huge deal since this is just a template that people are likely to tweak anyway, but I think we should at least point it out as a comment.

2022-04-25 13:25 UTC, alafanechere commented
> Thanks for contributing! I only have one comment on some differences between some of the generated `acceptance-test-config.yml` files. Not a huge deal since this is just a template that people are likely to tweak anyway, but I think we should at least point it out as a comment.

@pedroslopez / @sherifnada do you think its a concern if new singer connectors lose their `-singer` suffix?

2022-04-25 17:43 UTC, sherifnada commented
@alafanechere we should keep that suffix as it helps with issues around singer. I think it's very easy to add the `-singer` suffix programmatically in `plopfile.js` -- I would recommend we do that instead of removing the suffix. see the plopfile.js docs to edit the `answers` config to change the user's answer to include `-singer` by default

2022-04-25 17:58 UTC, sherifnada commented
@alafanechere I think I misunderstood -- as long as the directory is suffixed with `-singer` that's what matters. The dockerfile/setup.py etc.. don't need to have it strictly speaking

2022-04-26 10:29 UTC, alafanechere commented
@daniel-cortez-stevenson / @pedroslopez / @sherifnada 
I implement some changes in https://github.com/airbytehq/airbyte/pull/12067/commits/83fd1dc1dbac8ddba8b74ece6f83948ea032cba3 to match extactly the existing generated acceptance test file for Generic and Singer connectors.
I added custom helpers to build `spec_path` and `connector_image` strings. Behavior of these helpers can change according to some variable passed in the `data` object of the related `actions`. This allows custom behavior for `singer` (mixed case suffix) and `generic` (the `spec.json` is not in at the root of the connector folder, not in a subfolder).

Let me know what you think.

2022-04-26 15:03 UTC, pedroslopez requested changes
Nice @alafanechere! There may be some potential for cleanup if we can add some expectations or do a bit of formatting on the `name` input for the singer generator, but the only blocking comment from me is the switch to `spec.yaml` files on the python CDK sources introduced in #12245

2022-04-26 15:53 UTC, alafanechere commented on airbyte-integrations/connector-templates/generator/plopfile.js
> +const changeCase = require('change-case')
It's a plopfile dependency, do you think we shall also explicitly declare it in `package.json`?

2022-04-26 23:11 UTC, pedroslopez commented on airbyte-integrations/connector-templates/generator/plopfile.js
> +const changeCase = require('change-case')
Yeah, if we're using it directly then it should be listed as a dependency. This way we don't run into issues later if decides to do some refactoring and strip out the dependency or upgrade it to an incompatible version.

2022-04-27 11:08 UTC, alafanechere commented on airbyte-integrations/connector-templates/generator/plopfile.js
> +  });
I checked Inquirer a bit, the `suffix`  is meant to be added to prompt message. I could build `connector_image` and `spec_path` in the filter function and make it return an object with `name`, `connector_image` and `spec_path` properties. But this does not look like a "for free" implementation to me. 
I prefer to defer the logic of building `name` related values downstream, in the plop helpers logic as it looks to me like the proper place of handling this kind of things.

2022-04-27 12:54 UTC, alafanechere commented on airbyte-integrations/connector-templates/generator/plopfile.js
> +const changeCase = require('change-case')
I added it to `package.json`: https://github.com/airbytehq/airbyte/pull/12067/commits/6d98a9f7ccd3a8c9365e144483e73656c55caf63

2022-04-27 12:55 UTC, alafanechere commented on airbyte-integrations/connector-templates/generator/plopfile.js
> +  const specFileName = 'spec.json'
✅ I changed it to `spec.yaml` in https://github.com/airbytehq/airbyte/pull/12067/commits/7496a7d4048362ba1a6b3b9e30b01f29bfa868cf

2022-04-28 23:24 UTC, sherifnada approved these changes
LGTM once pedro's comments are addressed

2022-04-29 15:05 UTC, pedroslopez approved these changes

2022-05-02 07:08 UTC, merged