2655 Clean up kafka source connector docs
airbytehq/airbyte pull request #12343
Opened 2022-04-26 11:10 UTC by alexandr-shegeda

## What
Clean up docs

## 🚨 User Impact 🚨
No user impact.

2022-05-05 13:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=12343) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=12343) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=12343) it.</sub>

2022-05-12 13:01 UTC, etsybaev requested changes

2022-05-12 13:40 UTC, alexandr-shegeda commented on docs/integrations/sources/kafka.md
> +You'll need the following information to configure the Postgres destination:
thanks, fixed

2022-05-12 13:43 UTC, etsybaev approved these changes

2022-05-12 14:07 UTC, merged