🎉 New Source: Firebolt (#1)
airbytehq/airbyte pull request #12536
Opened 2022-05-03 15:03 UTC by ptiurin

## What
Add new source [Firebolt](https://firebolt.io/)

## Recommended reading order
1. docs/integrations/sources/firebolt.md
2. airbyte-integrations/connectors/source-firebolt/bootstrap.md
3. airbyte-integrations/connectors/source-firebolt/source_firebolt/source.py
4. airbyte-integrations/connectors/source-firebolt/source_firebolt/utils.py

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

![image](https://user-images.githubusercontent.com/93913847/166479469-809f3b51-b0d1-4225-be08-f1381fa2d0a4.png)

</details>

<details><summary><strong>Integration</strong></summary>

![image](https://user-images.githubusercontent.com/93913847/166479637-15681493-6698-4b04-b74d-29f0e9595e56.png)

</details>

<details><summary><strong>Acceptance</strong></summary>

![image](https://user-images.githubusercontent.com/93913847/166479673-5ad22b7c-5efc-4def-98cc-8d5401b79388.png)
![image](https://user-images.githubusercontent.com/93913847/166479714-a7efd4ff-dd91-4b8d-a969-c329473cd410.png)

</details>

2022-05-03 15:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=12536) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=12536) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=12536) it.</sub>

2022-05-03 21:58 UTC, marcosmarxm commented
Can you sign the CLA @ptiurin ?

2022-05-04 06:14 UTC, ptiurin commented
> Can you sign the CLA @ptiurin ?

Done. Had to consult if I'm authorised to sign it.

2022-05-18 11:32 UTC, ptiurin commented
Could you have a look at this PR please, @jerri-airbyte ?

2022-05-18 15:20 UTC, jerri-airbyte approved these changes

2022-05-23 16:15 UTC, ptiurin commented
What would be the next steps here?

2022-06-02 15:57 UTC, harshithmullapudi requested changes
Also inside the wrapper could we link to your documentation where ever needed/possible

2022-06-02 15:57 UTC, harshithmullapudi commented on airbyte-integrations/connectors/source-firebolt/source_firebolt/utils.py
> +        logger.info("Engine parameter was not provided. Connecting to the default engine.")
this can go inside the firebolt wrapper

2022-06-06 11:26 UTC, ptiurin commented on airbyte-integrations/connectors/source-firebolt/source_firebolt/utils.py
> +    """
Added examples and cleaned up the docstring/types.

2022-06-06 12:08 UTC, ptiurin commented on airbyte-integrations/connectors/source-firebolt/source_firebolt/source.py
> +    return connection
I created database.py instead, since having both `firebolt` external module and local would be confusing and problematic.

2022-06-06 12:11 UTC, ptiurin commented
> Also inside the wrapper could we link to your documentation where ever needed/possible

Please indicate where you feel like documentation is needed.
Overall, Firebolt documentation is linked in both readme and bootstrap docs.

2022-06-06 12:20 UTC, harshithmullapudi commented
> > Also inside the wrapper could we link to your documentation where ever needed/possible
> 
> Please indicate where you feel like documentation is needed. Overall, Firebolt documentation is linked in both readme and bootstrap docs.

I felt we can link documentation for what data types firebolt support in the convert type function also the data conversion we can link the documentation if available.

Otherwise LGTM

2022-06-10 06:09 UTC, harshithmullapudi approved these changes

2022-06-10 06:12 UTC, harshithmullapudi commented
@ptiurin we are waiting to figure out the firebolt account credentials once it is done I will run the tests

2022-06-10 11:52 UTC, igrankova commented
@harshithmullapudi, the account is available in LastPass: Firebolt.
Be informed, that it is a paid account (0.01$ per item). I'll try to find out how to make it a sandbox, or maybe switch to the paid subscription.

2022-06-16 15:58 UTC, harshithmullapudi commented
/test connector=connectors/source-firebolt

2022-06-17 12:16 UTC, harshithmullapudi commented
closing in favor of #13874

2022-06-17 12:17 UTC, closed without merging