New Source: Kyriba
airbytehq/airbyte pull request #12748
Opened 2022-05-10 18:15 UTC by wjwatkinson

## What
Add a new source for Kyriba

## How
Use the python cdk

## 🚨 User Impact 🚨
None

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

New Connector

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] `docs/SUMMARY.md`
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

2022-05-11 00:03 UTC, octavia-squidington-iii commented
A new comment

2022-05-13 16:43 UTC, marcosmarxm requested changes
a few comments! but loved your implementation @wjwatkinson !!!

2022-05-13 16:43 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-kyriba/Pipfile
> +python_version = "3.9"
can you remove this file @wjwatkinson ?

2022-05-13 16:43 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-kyriba/integration_tests/catalog.json
> +          "column1": {
Please remove this file.

2022-05-13 16:43 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-kyriba/source_kyriba/schemas/.json
> +    "value": {
what this schema about?

2022-05-13 16:43 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-kyriba/source_kyriba/source.py
> +        self.version = version
can you rename it to `api_version`?

2022-05-13 16:43 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-kyriba/source_kyriba/source.py
> +        return iter(response.json().get("results"))
usually connectors use `yield from response.json().get("results")`

2022-05-13 16:43 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-kyriba/source_kyriba/spec.json
> +      "version": {
api_version

2022-05-13 16:43 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-kyriba/source_kyriba/spec.json
> +        "description": "The date the sync should end.",
If set to empty will sync data to most recent date. (maybe adding this to become clear to users)

2022-05-13 16:43 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-kyriba/source_kyriba/source.py
> +        self.end_date = date.fromisoformat(end_date) if end_date else None
why for end date you convert `fromisoformat` and didn't apply for start date?

2022-05-13 16:43 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-kyriba/source_kyriba/source.py
> +        start_date = date.fromisoformat(self.start_date)
you're doing the isoformat here, maybe apply when creating the object.

2022-05-13 16:43 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-kyriba/source_kyriba/source.py
> +        end_date = self.end_date or date.today()
what happens if you don't inform start and end date? will get any data at all?

2022-05-14 01:40 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-kyriba/source_kyriba/source.py
> +
please enable cache to not run full refresh two times.

2022-05-17 13:45 UTC, wjwatkinson commented
@marcosmarxm Thanks for the review. This is the first source I have contributed and the Kyriba API is not at all standard, so the second set of eyes is really helpful.

2022-05-17 14:02 UTC, marcosmarxm commented
> @marcosmarxm Thanks for the review. This is the first source I have contributed and the Kyriba API is not at all standard, so the second set of eyes is really helpful.

Sure!

2022-05-25 11:29 UTC, wjwatkinson commented
@marcosmarxm all your comments should have been addressed with updates. Let me know if I missed anything, or you see further room for improvement.

2022-05-27 01:25 UTC, marcosmarxm commented
@wjwatkinson do you mind sharing the integration test output again?

2022-05-27 01:25 UTC, marcosmarxm commented
and solve the conflict with SUMMARY.md looks this file was deleted

2022-06-22 16:21 UTC, marcosmarxm commented
@wjwatkinson do you think is ready to be merged? Can you solve conflict with `docs/SUMMARY.md`? Please ping me in Slack if possible.

2022-06-30 19:40 UTC, marcosmarxm commented
/publish connector=connectors/source-kyriba run_tests=false

2022-06-30 19:48 UTC, marcosmarxm commented
/publish connector=connectors/source-kyriba run-tests=false

2022-07-13 13:55 UTC, marcosmarxm commented
/publish connector=connectors/source-kyriba run-tests=false

2022-07-13 14:10 UTC, marcosmarxm approved these changes
thanks @wjwatkinson

2022-07-13 14:11 UTC, merged

2022-07-29 16:29 UTC, grubberr commented
/test connector=connectors/source-kyriba

2022-08-01 12:16 UTC, marcosmarxm commented
@grubberr this was merged as alpha connector without credentials.