Destination Redshift: fixed array contents verification for SUPER
airbytehq/airbyte pull request #13069
Opened 2022-05-20 21:46 UTC by adam-bloom

## What
Follow up to #12940. That solution relies on `Jsons.flatten`, which previously did not actually flatten arrays, but rather just converted them to strings. Redshift can store arrays within a SUPER.

## How
Added a case to `flatten` to handle arrays. This function is only used one other location: https://github.com/airbytehq/airbyte/blob/a1b1c1cb8cefbb04e3721cba564b6707a12f66c2/airbyte-scheduler/persistence/src/main/java/io/airbyte/scheduler/persistence/job_tracker/JobTracker.java#L218

As far as I can tell, that case (enum/const) should never encounter an array, so I do not believe adding this handling will result in any other negative consequences. Someone with more knowledge of the codebase than me, feel free to disagree! I can always add a switch to enable this behavior.

When flatten encounters an array, it will now flatten it into a map with keys `[<index>]` and the corresponding values. This should allow flatten to truly flatten arbitrary data.

As an example:
```
{"foo": [{"blue": "apple"}]}
```
would have previously been flattened to: `{"foo": "[{\"blue\": \"apple\"}]"}`
It will now flatten to: `{"foo.[0].blue": "apple"}`

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.
<summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

2022-05-20 21:51 UTC, adam-bloom commented
@marcosmarxm @alexandertsukanov FYI - not a regression in the last PR, but one more edge case that I missed.

2022-05-23 12:41 UTC, marcosmarxm requested changes

2022-05-23 12:41 UTC, marcosmarxm commented on airbyte-commons/src/main/java/io/airbyte/commons/json/Jsons.java
> +      return output;
thanks @adam-bloom but can you add a unit test for this? I'll request the team to review it becsause the change can impact more than just Redshift.

2022-05-27 08:46 UTC, alexandertsukanov commented
@adam-bloom looks like some conflicts with the master, could you fix them after I will run the tests? Thanks.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-05-27 14:23 UTC, adam-bloom commented
@alexandertsukanov resolved

2022-05-27 14:30 UTC, alexandertsukanov commented
/test connector=connectors/destination-redshift

2022-05-27 15:21 UTC, adam-bloom commented
@alexandertsukanov looks like the failure was in dbt/normalization. Is that test currently passing on master? Or do you think that there's a side-effect of the other use of `flatten` showing up here?

2022-06-02 11:11 UTC, alexandertsukanov commented
@adam-bloom  I see normalization tests are failing, let me ask somebody from Python team to take a look

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-06-02 11:27 UTC, grubberr commented
@adam-bloom please merge latest `master` branch to your branch and re-run
`/test connector=connectors/destination-redshift`
again

2022-06-02 14:22 UTC, alexandertsukanov commented
/test connector=connectors/destination-redshift

2022-06-03 17:38 UTC, marcosmarxm commented
/publish connector=connectors/destination-redshift

2022-06-03 18:46 UTC, merged