🎉 New Source: Orbit.love
airbytehq/airbyte pull request #13390
Opened 2022-06-01 19:35 UTC by avaidyanatha

## Main Changes
- Adds a connector for the [Orbit.love API](https://docs.orbit.love/reference/about-the-orbit-api)
- Supports the `members` and `workspace` streams, will add more once everything is working
- Initial support for pagination

2022-06-03 12:22 UTC, marcosmarxm commented
Thanks for the contribution @avaidyanatha :) can you share unit test and acceptance test output?

2022-06-06 06:49 UTC, avaidyanatha reviewed
Hey @marcosmarxm!

Everything seems to be in order now (I pasted all my test results in the main PR text)

One question though - it seems like acceptance tests won't let me pass my schema through unless I add an extra "data" object underneath the main response body. 

This prevents me from setting primary key = "id" in my streams as well. 

Everything works, but not setting the primary key is not optimal..

2022-06-06 06:49 UTC, avaidyanatha commented on airbyte-integrations/connectors/source-orbit/source_orbit/schemas/members.json
> +    "data": {
@marcosmarxm The orbit API returns an extra "data" here, is there a way to bypass this?

2022-06-09 12:56 UTC, alafanechere commented
@avaidyanatha thank you for this PR. We'll review it early next week in pair with @natalyjazzviolin for onboarding!

2022-06-13 14:29 UTC, natalyjazzviolin requested changes
I'm still reviewing the rest of the PR, will have some more comments soon!

2022-06-13 14:29 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-orbit/source_orbit/spec.yaml
> +      description: Authorizes you to work with Orbit workspaces associated with the token.
```suggestion
      description: Authorizes you to work with Orbit workspaces associated with the token.
      order: 0
```

2022-06-13 14:29 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-orbit/source_orbit/spec.yaml
> +      description: The unique name of the workspace that your API token is associated with.
```suggestion
      description: The unique name of the workspace that your API token is associated with.
      order: 1
```

2022-06-13 15:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=13390) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=13390) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: avaidyanatha<br/>:x: natalyjazzviolin<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=13390) it.</sub>

2022-06-13 20:54 UTC, natalyjazzviolin requested changes

2022-06-14 14:41 UTC, natalyjazzviolin requested changes

2022-06-14 14:41 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-orbit/source_orbit/source.py
> +            return False, e
Please add a more explanatory error message to accompany the error object.

2022-06-14 14:41 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-orbit/source_orbit/source.py
> +        stream_args = {
```suggestion
        stream_kwargs = {
```

2022-06-14 14:41 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-orbit/source_orbit/source.py
> +            "authenticator": TokenAuthenticator(token=config["api_token"]),
```suggestion
            "authenticator": TokenAuthenticator(config["api_token"]),
```

2022-06-14 14:41 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-orbit/source_orbit/streams.py
> +        return {}
```suggestion
```
This function is redundant, as it is already implemented in the HttpStream parent class.

2022-06-14 14:41 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-orbit/source_orbit/streams.py
> +        yield response.json()
```suggestion
    def parse_response(
        self,
        response: requests.Response,
        stream_state: Mapping[str, Any] = None,
        stream_slice: Mapping[str, Any] = None,
        next_page_token: Mapping[str, Any] = None,
    ) -> Iterable[Mapping]:
        data = response.json()
        records = data['data']
        yield records
```
Please alter the stream schemas to unnest the records from the data array.

2022-06-14 14:41 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-orbit/source_orbit/streams.py
> +            return
```suggestion
            return None
```

2022-06-14 14:41 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-orbit/source_orbit/streams.py
> +            return
```suggestion
            return None
```

2022-06-15 23:12 UTC, avaidyanatha reviewed
Made requested changes, thanks for the review!

2022-06-15 23:21 UTC, avaidyanatha commented
@natalyjazzviolin @alafanechere 

All the edits should be in and source acceptance tests are passing. Let me know what next steps are!

2022-06-16 13:25 UTC, alafanechere commented on airbyte-integrations/connectors/source-orbit/source_orbit/spec.yaml
> +    start_date:
@avaidyanatha we'd need the start date to only replicate a subset of our data, otherwise the test can't run in our CI as we exceed rate limits.

2022-06-16 14:05 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-orbit/source_orbit/spec.yaml
> +    start_date:
@avaidyanatha if you're open to it, I can make this change!

2022-06-21 17:00 UTC, natalyjazzviolin commented
/test connector=connectors/source-orbit

2022-06-24 13:15 UTC, natalyjazzviolin commented
@avaidyanatha I'm implementing the `start_date` parameter to bypass the API throttling in our CI tests, then we should be good to merge!

2022-06-27 15:04 UTC, alafanechere commented
/test connector=connectors/source-orbit

2022-06-27 16:37 UTC, alafanechere commented
/publish connector=connectors/source-orbit

2022-06-27 17:05 UTC, alafanechere commented
Thanks @avaidyanatha for this contribution and @natalyjazzviolin for the through review 👏

2022-06-27 17:05 UTC, merged

2023-01-08 16:49 UTC, PeerRich commented
following up here, https://github.com/airbytehq/airbyte/issues/11865#issuecomment-1374542522 i'm running into issues, not sure if its me or the source integration