Improved schema_generator tool
airbytehq/airbyte pull request #13518
Opened 2022-06-07 00:50 UTC by dougpm

## What
Improves the developer experience when using the schema generator tool.

## How
1. Created a package for the tool.
2. Added a command for generating a Configured Catalog.
3. Added documentation on how the tool works and how to use it.

## Recommended reading order

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

2022-06-07 00:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=13518) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=13518) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=13518) it.</sub>

2022-06-07 11:54 UTC, koconder requested changes
Good stuff, i think you need to add unit tests and re-instate the licence. I only did a quick eye-ball on the logic

2022-06-07 11:54 UTC, koconder commented on tools/schema_generator/schema_generator/infer_schemas.py
> -# MIT License
I dont think you can drop the licence

2022-06-07 11:54 UTC, koconder commented on tools/schema_generator/schema_generator/main.py
> +def main():
Any unit tests for the tool?

2022-06-07 17:13 UTC, alafanechere commented
Thank you @dougpm for this great contribution! Our team will review it soon.

2022-06-10 09:19 UTC, alafanechere commented
Hi @dougpm let me know if I'm wrong:
* Your tool is generating schemas files from running a `read` command
* The `read` command requires a catalog to run, hence the underlying stream schema

So I'm under the impression that this tool can't be used to initially create schema files while starting a new connector project. Am I right?

2022-06-14 17:34 UTC, dougpm commented
Hey @alafanechere 

You're right, to generate the catalog we need the schema files. These files can be empty json files, they just need to be there for the `discover` and `read` commands to succeed.
I could add instructions for the creation of empty schema files for each stream before the connector container is built. 
Should we go with that or are there any other options?

2022-06-14 18:08 UTC, alafanechere commented
Hey @dougpm I pinged our Developer Experience team to get their opinion about this addition 😄

2022-06-15 18:31 UTC, alafanechere commented
@dougpm it would help if you can add a bit more details in your documentation about the context in which this tool can be used in the connector development cycle.

2022-06-19 18:20 UTC, dougpm commented
@alafanechere Added a __Prerequisites__ section in the tool README file.

2022-06-21 22:11 UTC, sherifnada approved these changes
Generally looks good, thanks for adding docs! would also support having unit tests here but otherwise LGTM

2022-06-22 10:58 UTC, alafanechere requested changes
@dougpm how do you feel about adding unit tests?

2022-07-04 14:16 UTC, alafanechere commented
Hey @dougpm do you have the bandwidth to implement the unit tests soon?

2022-07-05 14:10 UTC, dougpm commented
Hey @alafanechere yes, I'll do it this week, sorry for the delay.

2022-07-12 01:38 UTC, dougpm commented
@alafanechere tests added!

2022-07-13 09:41 UTC, alafanechere approved these changes
Thank you for adding the tests. I played with the schema generator locally, I had to make minor changes to the installation process to make it work.

2022-07-13 17:00 UTC, merged