:tada: Source Amazon Seller Partner: Add new streams
airbytehq/airbyte pull request #13604
Opened 2022-06-08 13:15 UTC by vladimir-remar

## What
Add two new report types:
- GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA
- GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE
## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

```bash
============================================================================================ test session starts =============================================================================================
platform linux -- Python 3.9.13, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /home/vladimir/.virtualenvs/amzseller/bin/python
cachedir: .pytest_cache
rootdir: /home/vladimir/Work/Airbyte_projects/Fork/airbyte, configfile: pytest.ini
plugins: mock-3.7.0
collected 93 items                                                                                                                                                                                           

unit_tests/test_finance_streams.py::test_finance_stream_next_token PASSED
unit_tests/test_finance_streams.py::test_financial_event_groups_stream_request_params PASSED
unit_tests/test_finance_streams.py::test_financial_event_groups_stream_parse_response PASSED
unit_tests/test_finance_streams.py::test_financial_events_stream_request_params PASSED
unit_tests/test_finance_streams.py::test_financial_events_stream_parse_response PASSED
unit_tests/test_reports_streams_rate_limits.py::test_reports_stream_should_retry PASSED
unit_tests/test_reports_streams_rate_limits.py::test_reports_stream_send_request PASSED
unit_tests/test_reports_streams_rate_limits.py::test_reports_stream_send_request_backoff_exception {"type": "LOG", "log": {"level": "INFO", "message": "Backing off _send_request(...) for 5.0s (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException: Request URL: None, Response Code: 429, Response Text: )"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Caught retryable error 'Request URL: None, Response Code: 429, Response Text: ' after 1 tries. Waiting 5 seconds then retrying..."}}
{"type": "LOG", "log": {"level": "INFO", "message": "Backing off _send_request(...) for 10.0s (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException: Request URL: None, Response Code: 429, Response Text: )"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Caught retryable error 'Request URL: None, Response Code: 429, Response Text: ' after 2 tries. Waiting 10 seconds then retrying..."}}
{"type": "LOG", "log": {"level": "INFO", "message": "Backing off _send_request(...) for 20.0s (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException: Request URL: None, Response Code: 429, Response Text: )"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Caught retryable error 'Request URL: None, Response Code: 429, Response Text: ' after 3 tries. Waiting 20 seconds then retrying..."}}
{"type": "LOG", "log": {"level": "INFO", "message": "Backing off _send_request(...) for 40.0s (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException: Request URL: None, Response Code: 429, Response Text: )"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Caught retryable error 'Request URL: None, Response Code: 429, Response Text: ' after 4 tries. Waiting 40 seconds then retrying..."}}
{"type": "LOG", "log": {"level": "ERROR", "message": "Giving up _send_request(...) after 5 tries (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException: Request URL: None, Response Code: 429, Response Text: )"}}
PASSED
unit_tests/test_source.py::test_spec PASSED
unit_tests/test_source.py::test_streams PASSED
unit_tests/test_source.py::test_stream_with_good_iam_arn_value[arn:aws:iam::123456789098:user/some-user] PASSED
unit_tests/test_source.py::test_stream_with_good_iam_arn_value[arn:aws:iam::123456789098:role/some-role] PASSED
unit_tests/test_source.py::test_stream_with_bad_iam_arn_value PASSED
unit_tests/test_transform_function.py::test_transform_seller_feedback[A2VIGQ35RCS4UG-input_data0-expected_data0] PASSED
unit_tests/test_transform_function.py::test_transform_seller_feedback[A2VIGQ35RCS4UG-input_data1-expected_data1] PASSED
unit_tests/test_transform_function.py::test_transform_seller_feedback[A2VIGQ35RCS4UG-input_data2-expected_data2] PASSED
unit_tests/test_transform_function.py::test_transform_seller_feedback[A2VIGQ35RCS4UG-input_data3-expected_data3] PASSED
unit_tests/test_transform_function.py::test_transform_seller_feedback[A1PA6795UKMFR9-input_data4-expected_data4] PASSED
unit_tests/test_transform_function.py::test_transform_seller_feedback[A1PA6795UKMFR9-input_data5-expected_data5] PASSED
unit_tests/test_transform_function.py::test_transform_seller_feedback[A1PA6795UKMFR9-input_data6-expected_data6] PASSED
unit_tests/test_transform_function.py::test_transform_seller_feedback[A1PA6795UKMFR9-input_data7-expected_data7] PASSED
unit_tests/test_transform_function.py::test_transform_seller_feedback[A1C3SOZRARQ6R3-input_data8-expected_data8] PASSED
unit_tests/test_transform_function.py::test_transform_seller_feedback[A1C3SOZRARQ6R3-input_data9-expected_data9] PASSED
unit_tests/test_transform_function.py::test_transform_seller_feedback[A1C3SOZRARQ6R3-input_data10-expected_data10] PASSED
unit_tests/test_transform_function.py::test_transform_seller_feedback[A1C3SOZRARQ6R3-input_data11-expected_data11] PASSED
unit_tests/test_transform_function.py::test_transform_seller_feedback[ARBP9OOSHTCHU-input_data12-expected_data12] PASSED
unit_tests/test_transform_function.py::test_transform_seller_feedback[ARBP9OOSHTCHU-input_data13-exp [...]

2022-06-15 12:09 UTC, harshithmullapudi commented
@vladimir-remar thanks for the contribution. Could you help with these things
1.  Run `./gradlew format`
2. Follow these steps for updating connector https://docs.airbyte.com/connector-development/#updating-an-existing-connector

2022-06-15 12:10 UTC, harshithmullapudi commented
/test connector=connectors/source-amazon-seller-partner

2022-06-20 13:26 UTC, vladimir-remar commented
> @vladimir-remar thanks for the contribution. Could you help with these things
> 
> 1. Run `./gradlew format`
> 2. Follow these steps for updating connector https://docs.airbyte.com/connector-development/#updating-an-existing-connector

Hello @harshithmullapudi, this is my format output
```bash
vladimir@vremar:airbyte$ ./gradlew :airbyte-integrations:connectors:source-amazon-seller-partner:airbytePythonFormat
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
Building all of Airbyte.
/home/vladimir/Work/Airbyte_projects/Fork/airbyte/airbyte-integrations/connectors
Type-safe dependency accessors is an incubating feature.

> Task :airbyte-integrations:connectors:source-amazon-seller-partner:checkPython
Using python 3.9.13 from /home/vladimir/Work/Airbyte_projects/Fork/airbyte/airbyte-integrations/connectors/source-amazon-seller-partner/.venv (.venv/bin/python)
Using pip 21.3.1 from /home/vladimir/Work/Airbyte_projects/Fork/airbyte/airbyte-integrations/connectors/source-amazon-seller-partner/.venv/lib/python3.9/site-packages/pip (python 3.9)

> Task :airbyte-integrations:connectors:source-amazon-seller-partner:pipInstall
[python] .venv/bin/python -m pip install pip==21.3.1
         Requirement already satisfied: pip==21.3.1 in ./.venv/lib/python3.9/site-packages (21.3.1)
         WARNING: You are using pip version 21.3.1; however, version 22.1.2 is available.
         You should consider upgrading via the '/home/vladimir/Work/Airbyte_projects/Fork/airbyte/airbyte-integrations/connectors/source-amazon-seller-partner/.venv/bin/python -m pip install --upgrade pip' command.
[python] .venv/bin/python -m pip list --format=columns
         Package           Version
         ----------------- -------
         attrs             21.4.0
         black             22.3.0
         click             8.1.3
         coverage          6.3.1
         flake8            4.0.1
         iniconfig         1.1.1
         isort             5.6.4
         mccabe            0.6.1
         mypy              0.930
         mypy-extensions   0.4.3
         packaging         21.3
         pathspec          0.9.0
         pip               21.3.1
         platformdirs      2.5.2
         pluggy            0.13.1
         py                1.11.0
         pycodestyle       2.8.0
         pyflakes          2.4.0
         pyparsing         3.0.9
         pyproject-flake8  0.0.1a2
         pytest            6.1.2
         setuptools        62.1.0
         toml              0.10.2
         tomli             2.0.1
         typing_extensions 4.2.0
         wheel             0.37.1
         WARNING: You are using pip version 21.3.1; however, version 22.1.2 is available.
         You should consider upgrading via the '/home/vladimir/Work/Airbyte_projects/Fork/airbyte/airbyte-integrations/connectors/source-amazon-seller-partner/.venv/bin/python -m pip install --upgrade pip' command.

> Task :airbyte-integrations:connectors:source-amazon-seller-partner:isortFormat
[python] .venv/bin/python -m isort --settings-file=/home/vladimir/Work/Airbyte_projects/Fork/airbyte/pyproject.toml ./
         Skipped 6 files

> Task :airbyte-integrations:connectors:source-amazon-seller-partner:blackFormat
[python] .venv/bin/python -m black --config /home/vladimir/Work/Airbyte_projects/Fork/airbyte/pyproject.toml ./
         All done! ✨ 🍰 ✨
         14 files left unchanged.

> Task :airbyte-integrations:connectors:source-amazon-seller-partner:flakeCheck
[python] .venv/bin/python -m pflake8 --config /home/vladimir/Work/Airbyte_projects/Fork/airbyte/pyproject.toml ./

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 44s
16 actionable tasks: 9 executed, 7 up-to-date

```

2022-06-27 17:33 UTC, harshithmullapudi requested changes

2022-07-01 09:34 UTC, harshithmullapudi commented on airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
> +    def stream_slices(
@vladimir-remar I don't think it's right way to use the stream_slices here. @marcosmarxm do you have any suggestions here?

2022-07-05 12:56 UTC, marcosmarxm requested changes

2022-07-11 05:47 UTC, harshithmullapudi commented
Hey @vladimir-remar could you help on those changes Marcos requested?

2022-07-11 06:45 UTC, vladimir-remar commented
Thanks for your patience, I will check it ASAP.

2022-07-11 07:07 UTC, vladimir-remar commented on airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
> +        strict_start_date = pendulum.now("utc").subtract(days=90)
sure, That strict limit comes from documentation:
```
createdSince
The earliest report creation date and time for reports to include in the response, in ISO 8601 date time format. The default is 90 days ago. Reports are retained for a maximum of 90 days.
```
For testing porpuses if a date is less than 90 days ago the status from response is 400.

2022-07-15 07:36 UTC, harshithmullapudi commented
/test connector=connectors/source-amazon-seller-partner

2022-07-15 07:46 UTC, harshithmullapudi approved these changes

2022-07-15 07:46 UTC, harshithmullapudi commented
/publish connector=connectors/source-amazon-seller-partner

2022-07-15 09:33 UTC, merged