Update paypal transaction schema
airbytehq/airbyte pull request #13682
Opened 2022-06-10 14:22 UTC by mohamagdy

## What
Update PayPal Transactions schema

## How
Updated the `schemas/transaction.json` with couple of new fields and added the `maxLength` parameter for some fields based on PayPal's documentation https://developer.paypal.com/docs/api/transaction-search/v1/.

## 🚨 User Impact 🚨
Users might need to reset the connector to create the new fields in the database.

## Pre-merge Checklist

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

```shell
(3.9.11/envs/source-paypal-transactions) ➜  source-paypal-transaction git:(update-paypal-transaction-schema) ✗ python -m pytest unit_tests
Test session starts (platform: darwin, Python 3.9.11, pytest 6.2.5, pytest-sugar 0.9.4)
cachedir: .pytest_cache
rootdir: /Users/mohamedmagdy/projects/airbyte/airbyte, configfile: pytest.ini
plugins: sugar-0.9.4, mock-3.7.0, timeout-1.4.2
collecting ...
 airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py::test_get_field ✓    25% ██▌
 airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py::test_update_field ✓ 50% █████     {"type": "LOG", "log": {"level": "WARN", "message": "Stream transactions: start_date \"2022-06-10T15:55:52+02:00\" is too recent. Reset start_date to the maximum_allowed_start_date \"2022-06-10T15:53:52+02:00\""}}

 airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py::test_transactions_stream_slices ✓75% ███████▌
 airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py::test_balances_stream_slices ✓100% ██████████
================================================== warnings summary ==================================================
airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py::test_transactions_stream_slices
  /Users/mohamedmagdy/projects/airbyte/airbyte/airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py:75: DeprecationWarning: Call to deprecated class NoAuth. (Set `authenticator=None` instead) -- Deprecated since version 0.1.20.
    authenticator=NoAuth(),

airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py: 38 warnings
  /Users/mohamedmagdy/.pyenv/versions/3.9.11/envs/source-paypal-transactions/lib/python3.9/site-packages/deprecated/classic.py:173: DeprecationWarning: Call to deprecated class HttpAuthenticator. (Use requests.auth.AuthBase instead) -- Deprecated since version 0.1.20.
    return old_new1(cls, *args, **kwargs)

airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py: 19 warnings
  /Users/mohamedmagdy/.pyenv/versions/3.9.11/envs/source-paypal-transactions/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py:42: DeprecationWarning: Call to deprecated class NoAuth. (Set `authenticator=None` instead) -- Deprecated since version 0.1.20.
    self._authenticator: HttpAuthenticator = NoAuth()

airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py::test_transactions_stream_slices
  /Users/mohamedmagdy/projects/airbyte/airbyte/airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py:84: DeprecationWarning: Call to deprecated class NoAuth. (Set `authenticator=None` instead) -- Deprecated since version 0.1.20.
    authenticator=NoAuth(),

airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py::test_transactions_stream_slices
  /Users/mohamedmagdy/projects/airbyte/airbyte/airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py:92: DeprecationWarning: Call to deprecated class NoAuth. (Set `authenticator=None` instead) -- Deprecated since version 0.1.20.
    authenticator=NoAuth(),

airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py::test_transactions_stream_slices
  /Users/mohamedmagdy/projects/airbyte/airbyte/airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py:100: DeprecationWarning: Call to deprecated class NoAuth. (Set `authenticator=None` instead) -- Deprecated since version 0.1.20.
    authenticator=NoAuth(),

airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py::test_transactions_stream_slices
  /Users/mohamedmagdy/projects/airbyte/airbyte/airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py:108: DeprecationWarning: Call to deprecated class NoAuth. (Set `authenticator=None` instead) -- Deprecated since version 0.1.20.
    authenticator=NoAuth(),

airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py::test_transactions_stream_slices
  /Users/mohamedmagdy/projects/airbyte/airbyte/airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py:116: DeprecationWarning: Call to deprecated class NoAuth. (Set `authenticator=None` instead) -- Deprecated since version 0.1.20.
    authenticator=NoAuth(),

airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py::test_transactions_stream_slices
  /Users/mohamedmagdy/projects/airbyte/airbyte/airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py:124: DeprecationWarning: Call to deprecated class NoAuth. (Set `authenticator=None` instead) -- Deprecated since version 0.1.20.
    authenticator=NoAuth(),

airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py::test_transactions_stream_slices
  /Users/mohamedmagdy/projects/airbyte/airbyte/airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py:133: DeprecationWarning: Call to deprecated class NoAuth. (Set `authenticator=None` instead) -- Deprecated since version 0.1.20.
    authenticator=NoAuth(),

airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py::test_transactions_stream_slices
  /Users/mohamedmagdy/projects/airbyte/airbyte/airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py:148: DeprecationWarning: Call to deprecated class NoAuth. (Set `authenticator=None` instead) -- Deprecated since version 0.1.20.
    authenticator=NoAuth(),

airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py::test_transactions_stream_slices
  /Users/mohamedmagdy/projects/airbyte/airbyte/airbyte-integrations/connectors/source-paypal-transaction/unit_tests/unit_test.py:161: DeprecationWarning: Call to deprecated class NoAuth. (Set `authenticator=None` instead) -- Deprecated since version 0.1.20.
    authenticator=NoAuth(),

airbyte-integrations/connectors/source-paypal-transaction/uni [...]

2022-06-16 16:41 UTC, natalyjazzviolin requested changes

2022-06-16 16:41 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-paypal-transaction/source_paypal_transaction/schemas/transactions.json
> +              "maxLength": 256
```suggestion
              "type": ["null", "string"],
              "maxLength": 140
```

2022-06-16 16:41 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-paypal-transaction/source_paypal_transaction/schemas/transactions.json
> +              "maxLength": 256
```suggestion
              "maxLength": 140
```

2022-06-16 16:41 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-paypal-transaction/source_paypal_transaction/schemas/transactions.json
>              "alternate_full_name": {
```suggestion
```
Delete this property as it's been [deprecated](https://developer.paypal.com/docs/api/transaction-search/v1/#definition-name).

2022-06-16 16:41 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-paypal-transaction/source_paypal_transaction/schemas/transactions.json
> +          "maxLength": 3
```suggestion
          "maxLength": 2,
          "minLength": 2
```

2022-06-16 16:41 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-paypal-transaction/source_paypal_transaction/schemas/transactions.json
> +              "maxLength": 256
```suggestion
              "type": ["string"]
```

2022-06-16 16:41 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-paypal-transaction/source_paypal_transaction/schemas/transactions.json
> +              "maxLength": 3
```suggestion
              "type": ["string"],
              "maxLength": 2
```

2022-06-16 16:41 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-paypal-transaction/source_paypal_transaction/schemas/transactions.json
> +              "maxLength": 256
```suggestion
```

2022-06-16 16:41 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-paypal-transaction/source_paypal_transaction/schemas/transactions.json
> +                "maxLength": 256
```suggestion
                "maxLength": 200
```

2022-06-16 16:41 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-paypal-transaction/source_paypal_transaction/schemas/transactions.json
>                  "type": ["null", "string"]
```suggestion
                "type": ["null", "string"],
                "maxLength": 2000
```

2022-06-16 16:41 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-paypal-transaction/source_paypal_transaction/schemas/transactions.json
> +                "type": ["null", "number"]
```suggestion
                "type": ["null", "number"],
                "maxLength": 4000
```

2022-06-16 16:41 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-paypal-transaction/source_paypal_transaction/schemas/transactions.json
>                    "currency_code": {
Please update the currency code and value properties according to the [documentation](https://developer.paypal.com/docs/api/transaction-search/v1/#definition-money).

2022-06-16 16:41 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-paypal-transaction/source_paypal_transaction/schemas/transactions.json
>                    "currency_code": {
Please update the currency code and value properties according to the [documentation](https://developer.paypal.com/docs/api/transaction-search/v1/#definition-money).

2022-06-16 16:41 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-paypal-transaction/source_paypal_transaction/schemas/transactions.json
>                          "currency_code": {
Please update the currency code and value properties according to the [documentation](https://developer.paypal.com/docs/api/transaction-search/v1/#definition-money).

2022-06-16 16:41 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-paypal-transaction/source_paypal_transaction/schemas/transactions.json
>                    "currency_code": {
Please update the currency code and value properties according to the [documentation](https://developer.paypal.com/docs/api/transaction-search/v1/#definition-money).

2022-06-16 16:41 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-paypal-transaction/source_paypal_transaction/schemas/transactions.json
>                    "currency_code": {
Please update the currency code and value according to the [documentation.](https://developer.paypal.com/docs/api/transaction-search/v1/#definition-money)

2022-06-16 16:41 UTC, natalyjazzviolin commented on airbyte-config/init/src/main/resources/seed/source_definitions.yaml
> +  dockerImageTag: 0.1.6
We have a script that updates version numbers automatically. This works for now, but don't worry about these in the future - the same goes for the version numbers in source_spec.yaml and the Dockerfile.

2022-06-17 09:51 UTC, mohamagdy commented on airbyte-integrations/connectors/source-paypal-transaction/source_paypal_transaction/schemas/transactions.json
> +              "type": "number"
@natalyjazzviolin you're right, the documenation states it's a string but if you look at the `pattern` it is matches either integer or a number (decimal) `^((-?[0-9]+)|(-?([0-9]+)?[.][0-9]+))$.`. I would suggest keeping it as a number in the JSON schema.

2022-06-17 09:52 UTC, mohamagdy commented on airbyte-integrations/connectors/source-paypal-transaction/source_paypal_transaction/schemas/transactions.json
>            "type": ["null", "string"]
As far as I can see the `transaction_subject` is of length 256
<img width="527" alt="Screenshot 2022-06-17 at 11 48 32" src="https://user-images.githubusercontent.com/1228432/174274829-06c8b5a3-e9d5-44a3-954b-c28ba6871170.png">

2022-06-17 13:06 UTC, natalyjazzviolin commented on airbyte-integrations/connectors/source-paypal-transaction/source_paypal_transaction/schemas/transactions.json
>            "type": ["null", "string"]
You're right - sorry about that!

2022-06-17 18:43 UTC, natalyjazzviolin commented
@mohamagdy the basic read test in the acceptance test suite is failing due to the transaction stream being empty. 
To fix this please add `empty_streams: ["transactions"]` to the `acceptance-test-config.yml` file right under `configured_catalog_path` on line 17. 

Then we should be good to go!

2022-06-17 22:07 UTC, mohamagdy commented
@natalyjazzviolin added the `empty_stream: ["transactions"]` here https://github.com/airbytehq/airbyte/pull/13682/commits/40172fc02b8f8ad8c9b352738e935db719a5d9bf

```shell
(3.9.11/envs/source-paypal-transactions) ➜  source-paypal-transaction git:(update-paypal-transaction-schema) ✗ python -m pytest integration_tests -p integration_tests.acceptance
Test session starts (platform: darwin, Python 3.9.11, pytest 6.2.5, pytest-sugar 0.9.4)
cachedir: .pytest_cache
rootdir: /Users/mohamedmagdy/projects/airbyte/airbyte, configfile: pytest.ini
plugins: sugar-0.9.4, mock-3.7.0, timeout-1.4.2
collecting ...
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_config_match_spec[inputs0] ✓                             5% ▌
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_match_expected[inputs0] ✓                               10% █
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_docker_env[inputs0] ✓                                   15% █▌
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_oneof_usage[inputs0] ✓                                  20% ██
Add `transactions` to list of empty streams
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_required[inputs0] ✓                                     25% ██▌
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_optional[inputs0] ✓                                     30% ███
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_has_secret[inputs0] ✓                                   35% ███▌
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_secret_never_in_the_output[inputs0] ✓                   40% ████
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_defined_refs_exist_in_json_spec_file[inputs0] ✓         45% ████▌
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_oauth_flow_parameters[inputs0] ✓                        50% █████
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestConnection.test_check[inputs0] ✓                                  55% █████▌
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestConnection.test_check[inputs1] ✓                                  60% ██████
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_discover[inputs0] ✓                                65% ██████▌
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_defined_cursors_exist_in_schema[inputs0] ✓         70% ███████
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_defined_refs_exist_in_schema[inputs0] ✓            75% ███████▌
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_defined_keyword_exist_in_schema[inputs0-allOf] ✓   80% ████████
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_defined_keyword_exist_in_schema[inputs0-not] ✓     85% ████████▌
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_primary_keys_exist_in_schema[inputs0] ✓            90% █████████
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestBasicRead.test_read[inputs0] ✓                                    95% █████████▌{"type": "LOG", "log": {"level": "ERROR", "message": "Docker container was failed, code 1, error:\n{\"type\": \"TRACE\", \"trace\": {\"type\": \"ERROR\", \"emitted_at\": 1655502751889.146, \"error\": {\"message\": \"Something went wrong in the connector. See the logs for more details.\", \"internal_message\": \"2 validation errors for ConfiguredAirbyteCatalog\\nstreams -> 0 -> sync_mode\\n  value is not a valid enumeration member; permitted: 'full_refresh', 'incremental' (type=type_error.enum; enum_values=[<SyncMode.full_refresh: 'full_refresh'>, <SyncMode.incremental: 'incremental'>])\\nstreams -> 0 -> destination_sync_mode\\n  value is not a valid enumeration member; permitted: 'append', 'overwrite', 'append_dedup' (type=type_error.enum; enum_values=[<DestinationSyncMode.append: 'append'>, <DestinationSyncMode.overwrite: 'overwrite'>, <DestinationSyncMode.append_dedup: 'append_dedup'>])\", \"stack_trace\": \"Traceback (most recent call last):\\n  File \\\"/airbyte/integration_code/main.py\\\", line 13, in <module>\\n    launch(source, sys.argv[1:])\\n  File \\\"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\\\", line 129, in launch\\n    for message in source_entrypoint.run(parsed_args):\\n  File \\\"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\\\", line 117, in run\\n    config_catalog = self.source.read_catalog(parsed_args.catalog)\\n  File \\\"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/source.py\\\", line 28, in read_catalog\\n    return ConfiguredAirbyteCatalog.parse_obj(self.read_config(catalog_path))\\n  File \\\"pydantic/main.py\\\", line 521, in pydantic.main.BaseModel.parse_obj\\n  File \\\"pydantic/main.py\\\", line 341, in pydantic.main.BaseModel.__init__\\npydantic.error_wrappers.ValidationError: 2 validation errors for ConfiguredAirbyteCatalog\\nstreams -> 0 -> sync_mode\\n  value is not a valid enumeration member; permitted: 'full_refresh', 'incremental' (type=type_error.enum; enum_values=[<SyncMode.full_refresh: 'full_refresh'>, <SyncMode.incremental: 'incremental'>])\\nstreams -> 0 -> destination_sync_mode\\n  value is not a valid enumeration member; permitted: 'append', 'overwrite', 'append_dedup' (type=type_error.enum; enum_values=[<DestinationSyncMode.append: 'append'>, <DestinationSyncMode.overwrite: 'overwrite'>, <DestinationSyncMode.append_dedup: 'append_dedup'>])\\n\", \"failure_type\": \"system_error\"}}}\n"}}

 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestBasicRead.test_airbyte_trace_message_on_failure[inputs0] ✓       100% ██████████
{"type": "LOG", "log": {"level": "INFO", "message": "/Users/mohamedmagdy/projects/airbyte/airbyte/airbyte-integrations/connectors/source-paypal-transaction - SAT run - 13d82a9bd9605ddb152451ff58127cafef0fc7fa - PASSED"}}

============================================================================ short test summary info =============================================================================
SKIPPED [1] ../../bases/source-acceptance-test/source_acceptance_test/plugin.py:56: Skipping TestFullRefresh.test_sequential_reads because not found in the config
SKIPPED [1] ../../bases/source-acceptance-test/source_acceptance_test/plugin.py:56: Skipping TestIncremental.test_two_sequential_reads because not found in the config

Results (103.12s):
      20 passed
```

2022-06-20 17:22 UTC, alafanechere commented
/test connector=connectors/source-paypal-transaction

2022-06-21 18:51 UTC, natalyjazzviolin commented
/test connector=connectors/source-paypal-transaction

2022-06-22 15:30 UTC, natalyjazzviolin commented
/test connector=connectors/source-paypal-transaction

2022-06-22 21:28 UTC, natalyjazzviolin approved these changes

2022-06-24 05:22 UTC, alafanechere commented
/publish connector=connectors/source-paypal-transaction auto-bump-version=false

2022-06-24 09:50 UTC, alafanechere commented
/publish connector=connectors/source-paypal-transaction auto-bump-version=false

2022-06-24 13:43 UTC, merged