Add Glassfrog native connector
airbytehq/airbyte pull request #13868
Opened 2022-06-17 02:08 UTC by rparrapy

## What
Add new native source connector for Glassfrog

## How
Native connector using the Python CDK, pulls all resources available through the [Glassfrog API](https://documenter.getpostman.com/view/1014385/glassfrog-api-v3/2SJViY).

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
No breaking changes.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

## Tests

<details><summary><strong>Acceptance</strong></summary>

<img width="1262" alt="Screen Shot 2022-06-16 at 21 36 19" src="https://user-images.githubusercontent.com/742097/174205996-c21deccd-c36c-45c6-af03-1eb753fe529d.png">

</details>

2022-06-20 16:01 UTC, alafanechere commented
Thank you @rparrapy for this contribution. We need a sandbox account for Glassfrog to run the acceptance tests in our CI. I created an issue so that our team can create it. We'll review it once we have this account.

2022-07-15 08:18 UTC, harshithmullapudi requested changes

2022-07-15 08:18 UTC, harshithmullapudi commented on airbyte-integrations/connectors/source-glassfrog/source_glassfrog/source.py
> +        return {}
Can we remove this method?

2022-07-15 08:18 UTC, harshithmullapudi commented on airbyte-integrations/connectors/source-glassfrog/source_glassfrog/source.py
> +    data_field = "assignments"
Could you add a link to the documentation here? and same for other streams also

2022-07-21 19:00 UTC, harshithmullapudi commented
/test connector=connectors/source-glassfrog

2022-07-21 19:25 UTC, harshithmullapudi commented
/test connector=connectors/source-glassfrog

2022-07-21 19:45 UTC, harshithmullapudi commented
/publish connector=connectors/source-glassfrog

2022-07-21 20:45 UTC, harshithmullapudi commented
/publish connector=connectors/source-glassfrog

2022-07-22 04:35 UTC, harshithmullapudi commented
/publish connector=connectors/source-glassfrog

2022-07-25 10:40 UTC, harshithmullapudi commented
/publish connector=connectors/source-glassfrog

2022-07-25 14:40 UTC, marcosmarxm commented
/publish connector=connectors/source-glassfrog

2022-07-26 07:13 UTC, harshithmullapudi commented
/test connector=connectors/source-glassfrog

2022-07-26 07:48 UTC, harshithmullapudi commented
/publish connector=connectors/source-glassfrog

2022-07-26 14:48 UTC, harshithmullapudi commented
/publish connector=connectors/source-posthog

2022-07-27 03:53 UTC, merged