Resolving issue #1353: implement backoff in Google Sheets
airbytehq/airbyte pull request #1438
Opened 2020-12-23 17:27 UTC by yevhenii-ldv

## What
*Using a backoff in the Google Sheets source code when the request limit is reached.*

## How
*Using python library `backoff`*

## Pre-merge Checklist
- [ ] *Run integration tests*
- [ ] *Publish Docker images*

## Recommended reading order
1. `test.java`
1. `component.ts`
1. the rest

2020-12-23 18:07 UTC, sherifnada reviewed
@yevhenii-ldv This looks great so far, but we aren't backing off on every client call. For example in the `discovery` method we make a call using `client` but there is no backing off there as far as i can tell. Could we add this backoff to every call made with the client? It may make sense to put the client in a separate class if it helps.

2020-12-24 17:24 UTC, yevhenii-ldv commented
@sherifnada PR was updated with new client`s class for Google Sheets requests with backoff
Merry Christmas))

2020-12-25 02:43 UTC, sherifnada requested changes
Merry christmas @yevhenii-ldv! looking much better already. Two more things needed: 

1. Update the version of this connector in the Dockerfile, YAML, and generated JSON file. We generally want to do this whenever we make an update to a connector so we can release a new version. 
2. small structural change to the client

2020-12-25 02:43 UTC, sherifnada commented on airbyte-integrations/connectors/source-google-sheets/google_sheets_source/client.py
> +class GoogleSheetsClient:
@yevhenii-ldv last change: this should have a constructor which takes the credentials dict and calls to `Helpers.get_authenticated_google_credentials`, and these methods do not need to be static. But this is already looking much better ;)

2020-12-30 13:28 UTC, yevhenii-ldv commented
@sherifnada I have updated the code as per your comments.

2020-12-30 23:37 UTC, jrhizor approved these changes
Looks good! 

I'm going to build the image, run the tests, and then merge this.

2020-12-31 01:13 UTC, merged