In the case of building test-connector using Airbyte CDK
airbytehq/airbyte pull request #14442
Opened 2022-07-06 10:39 UTC by HALLOWe3n

dev:
test connector

2022-07-06 10:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=14442) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=14442) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=14442) it.</sub>

2022-07-11 07:44 UTC, davydov-d commented
/test connector=connectors/source-exchange-rates-tutorial

2022-07-11 07:45 UTC, davydov-d requested changes

2022-07-11 07:45 UTC, davydov-d commented on airbyte-integrations/connectors/source-exchange-rates-tutorial/acceptance-test-config.yml
> +      future_state_path: "integration_tests/abnormal_state.json"
have you tried running integration tests? it should probably fail with the current config

2022-07-11 07:45 UTC, davydov-d commented on airbyte-integrations/connectors/source-exchange-rates-tutorial/integration_tests/catalog.json
> +{
is this file used?

2022-07-11 07:45 UTC, davydov-d commented on airbyte-integrations/connectors/source-exchange-rates-tutorial/integration_tests/sample_state.json
> +{
I guess we can remove this file as well as all other sample files

2022-07-11 07:45 UTC, davydov-d commented on airbyte-integrations/connectors/source-exchange-rates-tutorial/sample_files/configured_catalog.json
> +{
what's the purpose of this file?

2022-07-11 07:45 UTC, davydov-d commented on airbyte-integrations/connectors/source-exchange-rates-tutorial/source_exchange_rates_tutorial/spec.yaml
> +      pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2}$
can we use `{"type": "string", "format": "date"}` instead?

2022-07-11 07:45 UTC, davydov-d commented on airbyte-integrations/connectors/source-exchange-rates-tutorial/source_exchange_rates_tutorial/schemas/customers.json
> +{
this is the schema for a non existent stream

2022-07-11 07:45 UTC, davydov-d commented on airbyte-integrations/connectors/source-exchange-rates-tutorial/source_exchange_rates_tutorial/schemas/employees.json
> +{
this is the schema for a non existent stream

2022-07-11 07:45 UTC, davydov-d commented on airbyte-integrations/connectors/source-exchange-rates-tutorial/integration_tests/configured_catalog.json
> +      "sync_mode": "incremental",
I guess we should provide a cursor field in both the stream and the configured_stream in case we set the incremental mode here

2022-07-11 07:45 UTC, davydov-d commented on airbyte-integrations/connectors/source-exchange-rates-tutorial/source_exchange_rates_tutorial/source.py
> +            base = config.get("base")
why `.get`? I see it is required in the spec

2022-07-11 07:45 UTC, davydov-d commented on airbyte-integrations/connectors/source-exchange-rates-tutorial/source_exchange_rates_tutorial/source.py
> +            resp = requests.get(f"{ExchangeRates.url_base}{config['start_date']}", params=params)
I suggest using libraries like urllib for constructing URLs

2022-07-11 07:45 UTC, davydov-d commented on airbyte-integrations/connectors/source-exchange-rates-tutorial/source_exchange_rates_tutorial/source.py
> +            error = resp.json().get("error")
what if response body is empty?

2022-07-11 07:45 UTC, davydov-d commented on airbyte-integrations/connectors/source-exchange-rates-tutorial/source_exchange_rates_tutorial/source.py
> +            code = error.get("code")
what if there's no `error` in the response json?

2022-07-11 07:45 UTC, davydov-d commented on airbyte-integrations/connectors/source-exchange-rates-tutorial/source_exchange_rates_tutorial/source.py
> +            if code == "base_currency_access_restricted":
do you have any information about other error codes? if yes, we should also process them as for me

2022-07-11 07:45 UTC, davydov-d commented on airbyte-integrations/connectors/source-exchange-rates-tutorial/source_exchange_rates_tutorial/source.py
> +        start_date = datetime.strptime(stream_state["date"], "%Y-%m-%d") if stream_state and "date" in stream_state else self.start_date
"%Y-%m-%d" repeats multiple times, I believe we should reuse it in a routine

2022-07-11 07:45 UTC, davydov-d commented on airbyte-integrations/connectors/source-exchange-rates-tutorial/source_exchange_rates_tutorial/source.py
> +    def next_page_token(self, response: requests.Response) -> Optional[Mapping[str, Any]]:
what's the purpose to override it?

2022-07-11 07:45 UTC, davydov-d commented on airbyte-integrations/connectors/source-exchange-rates-tutorial/source_exchange_rates_tutorial/source.py
> +    def state(self, value: Mapping[str, Any]):
where do you set the state?

2022-07-11 07:45 UTC, davydov-d commented on airbyte-integrations/connectors/source-exchange-rates-tutorial/unit_tests/test_incremental_streams.py
> +    assert stream.cursor_field == expected_cursor_field
how does it work?

that's opposite to what is implemented [here](https://github.com/airbytehq/airbyte/pull/14442/files#diff-b552061aa2b8e7c43d45df2a942450a1ca98515c69142f44a09414b377fb47fbR38)

2022-07-11 07:45 UTC, davydov-d commented on airbyte-integrations/connectors/source-exchange-rates-tutorial/unit_tests/test_incremental_streams.py
> +def test_stream_slices(patch_incremental_base_class):
can you please parametrize it with more meaningfull data?

2022-07-11 07:45 UTC, davydov-d commented on airbyte-integrations/connectors/source-exchange-rates-tutorial/unit_tests/test_incremental_streams.py
> +    mocker.patch.object(IncrementalExchangeRatesTutorialStream, "cursor_field", "dummy_field")
why do you need to mock it?

2022-07-11 07:45 UTC, davydov-d commented on airbyte-integrations/connectors/source-exchange-rates-tutorial/unit_tests/test_streams.py
> +    assert next(stream.parse_response(**inputs)) == expected_parsed_object
how does it work? shouldn't the `.json` method be called on that mock?

2022-07-11 07:45 UTC, davydov-d commented
I have also fired test runner, please make sure all the tests pass

2022-07-12 11:13 UTC, lazebnyi commented
Deprecated PR

2022-07-12 11:13 UTC, closed without merging