Remove `additionalProperties` from JDBC source connectors
airbytehq/airbyte pull request #14574
Opened 2022-07-11 13:05 UTC by VitaliiMaltsev

## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

2022-07-11 13:08 UTC, VitaliiMaltsev commented
/test connector=connectors/source-clickhouse

2022-07-11 13:09 UTC, VitaliiMaltsev commented
/test connector=connectors/source-clickhouse-strict-encrypt

2022-07-11 13:10 UTC, VitaliiMaltsev commented
/test connector=connectors/source-cockroachdb

2022-07-11 13:10 UTC, VitaliiMaltsev commented
/test connector=connectors/source-cockroachdb-strict-encrypt

2022-07-11 13:10 UTC, VitaliiMaltsev commented
/test connector=connectors/source-db2

2022-07-11 13:12 UTC, VitaliiMaltsev commented
/test connector=connectors/source-mysql-strict-encrypt

2022-07-11 13:12 UTC, VitaliiMaltsev commented
/test connector=connectors/source-mysql

2022-07-11 13:12 UTC, VitaliiMaltsev commented
/test connector=connectors/source-oracle-strict-encrypt

2022-07-11 13:12 UTC, VitaliiMaltsev commented
/test connector=connectors/source-oracle

2022-07-11 13:13 UTC, VitaliiMaltsev commented
/test connector=connectors/source-postgres-strict-encrypt

2022-07-11 13:14 UTC, VitaliiMaltsev commented
/test connector=connectors/source-redshift

2022-07-11 13:14 UTC, VitaliiMaltsev commented
/test connector=connectors/source-snowflake

2022-07-11 13:52 UTC, VitaliiMaltsev commented
/test connector=connectors/source-cockroachdb

2022-07-11 13:58 UTC, VitaliiMaltsev commented
/test connector=connectors/source-oracle-strict-encrypt

2022-07-11 13:59 UTC, VitaliiMaltsev commented
/test connector=connectors/source-db2

2022-07-11 14:00 UTC, VitaliiMaltsev commented
/test connector=connectors/source-redshift

2022-07-13 09:15 UTC, VitaliiMaltsev commented
/test connector=connectors/source-snowflake

2022-07-13 10:40 UTC, VitaliiMaltsev commented
/test connector=connectors/source-redshift

2022-07-13 17:44 UTC, VitaliiMaltsev commented
/test connector=connectors/source-snowflake

2022-07-13 18:59 UTC, VitaliiMaltsev commented
/test connector=connectors/source-oracle-strict-encrypt

2022-07-14 08:29 UTC, VitaliiMaltsev commented
/test connector=connectors/source-oracle-strict-encrypt

2022-07-14 10:11 UTC, VitaliiMaltsev commented
/test connector=connectors/source-oracle-strict-encrypt

2022-07-15 15:55 UTC, sashaNeshcheret approved these changes

2022-07-18 11:52 UTC, alexandr-shegeda approved these changes
LGTM

2022-07-18 22:56 UTC, grishick requested changes
looks like one rogue change snuck into this PR (final keyword removed) and the PR needs to be rebased. Otherwise - looks good.

2022-07-18 22:56 UTC, grishick commented on airbyte-integrations/connectors/source-snowflake/src/test-integration/java/io/airbyte/integrations/io/airbyte/integration_tests/sources/SnowflakeSourceAuthAcceptanceTest.java
> +    config = getStaticConfig();
why is `final` removed as part of this change?

2022-07-19 05:10 UTC, VitaliiMaltsev commented
> looks like one rogue change snuck into this PR (final keyword removed) and the PR needs to be rebased. Otherwise - looks good.

@grishick no, this change is necessary. The SnowflakeSourceAuthAcceptanceTest test is broken in the master branch and redefining the global variable _config_ instead of defining a new local variable is a fix for this issue

2022-07-19 10:13 UTC, VitaliiMaltsev commented
/test connector=connectors/source-cockroachdb

2022-07-19 15:57 UTC, grishick approved these changes

2022-07-19 16:41 UTC, VitaliiMaltsev commented
/test connector=connectors/source-cockroachdb

2022-07-20 02:21 UTC, tuliren approved these changes

2022-07-20 06:53 UTC, VitaliiMaltsev commented
/publish connector=connectors/source-bigquery

2022-07-20 06:54 UTC, VitaliiMaltsev commented
/publish connector=connectors/source-clickhouse

2022-07-20 06:55 UTC, VitaliiMaltsev commented
/publish connector=connectors/source-clickhouse-strict-encrypt auto-bump-version=false

2022-07-20 06:55 UTC, VitaliiMaltsev commented
/publish connector=connectors/source-cockroachdb

2022-07-20 06:56 UTC, VitaliiMaltsev commented
/publish connector=connectors/source-cockroachdb-strict-encrypt auto-bump-version=false

2022-07-20 06:57 UTC, VitaliiMaltsev commented
/publish connector=connectors/source-db2-strict-encrypt auto-bump-version=false

2022-07-20 06:57 UTC, VitaliiMaltsev commented
/publish connector=connectors/source-db2

2022-07-20 06:58 UTC, VitaliiMaltsev commented
/publish connector=connectors/source-mssql

2022-07-20 06:59 UTC, VitaliiMaltsev commented
/publish connector=connectors/source-mssql-strict-encrypt auto-bump-version=false

2022-07-20 06:59 UTC, VitaliiMaltsev commented
/publish connector=connectors/source-mysql-strict-encrypt auto-bump-version=false

2022-07-20 07:00 UTC, VitaliiMaltsev commented
/publish connector=connectors/source-mysql

2022-07-20 07:01 UTC, VitaliiMaltsev commented
/publish connector=connectors/source-oracle-strict-encrypt auto-bump-version=false

2022-07-20 07:02 UTC, VitaliiMaltsev commented
/publish connector=connectors/source-postgres

2022-07-20 07:03 UTC, VitaliiMaltsev commented
/publish connector=connectors/source-redshift

2022-07-20 07:03 UTC, VitaliiMaltsev commented
/publish connector=connectors/source-snowflake

2022-07-20 07:07 UTC, VitaliiMaltsev commented
/publish connector=connectors/source-clickhouse-strict-encrypt auto-bump-version=false

2022-07-20 07:41 UTC, VitaliiMaltsev commented
/publish connector=connectors/source-clickhouse

2022-07-20 07:42 UTC, VitaliiMaltsev commented
/publish connector=connectors/source-clickhouse-strict-encrypt auto-bump-version=false

2022-07-20 10:52 UTC, VitaliiMaltsev commented
/test connector=connectors/source-oracle

2022-07-20 16:35 UTC, grishick commented
This can be merged now.

2022-07-21 00:20 UTC, grishick commented
@VitaliiMaltsev please file separate issues for fixing the broke integration tests (the ones that are failing on this PR) and then you can merge this PR.

2022-07-21 07:58 UTC, VitaliiMaltsev commented
@grishick  I published all connectors except _clickhouse-source_ and _clickhouse-source-strict-encrypt_ because integration tests are broken there. The publishing of these connectors will be part of [this PR](https://github.com/airbytehq/airbyte/pull/14701)

2022-07-21 08:01 UTC, merged