🎉 Source Github: PullRequestCommentReactions - re-implemented using GraphQL
airbytehq/airbyte pull request #14795
Opened 2022-07-18 15:47 UTC by grubberr

Signed-off-by: Sergey Chvalyuk <grubberr@gmail.com>

## Performance for stream PullRequestCommentReactions

Type        | HTTP requests | Sync time           | Number of records  
--------- |---------------  |-----------------|-------------------
GraphQL | 2796                  | 674 seconds      | 2365
REST API | 28671                | 17068 seconds | 2365

Some notes:

- Traversing Graph algorithm produce UNSORTED records (not fully sorted)

## How
*Describe the solution*

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [x] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [x] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

2022-07-19 09:13 UTC, alexandertsukanov commented
/test connector=connectors/destination-s3

2022-07-22 06:41 UTC, grubberr commented
/test connector=connectors/source-github

2022-07-23 11:23 UTC, grubberr commented
/test connector=connectors/source-github

2022-07-24 06:33 UTC, grubberr commented
/test connector=connectors/source-github

2022-07-25 20:25 UTC, grubberr commented
/test connector=connectors/source-github

2022-07-26 14:50 UTC, lazebnyi requested changes

2022-07-26 14:50 UTC, lazebnyi commented on airbyte-integrations/connectors/source-github/source_github/graphql.py
> +        op = sgqlc.operation.Operation(_schema_root.query_type)
I see we use this line in a lot of methods. May be better shift it to class or instance attribute.

2022-07-27 09:50 UTC, grubberr commented
/test connector=connectors/source-github

2022-07-27 12:39 UTC, lazebnyi approved these changes

2022-08-01 12:10 UTC, Phlair approved these changes
Approving to not block but would appreciate adding docstrings & code comments to make the logic clear for any dev that works on this in the future.
Great move for optimisation though 👍

2022-08-01 12:10 UTC, Phlair commented on airbyte-integrations/connectors/source-github/source_github/graphql.py
> +    AVERAGE_REACTIONS = 2
Unclear what these numbers mean and where they come from... code comment would be good.

2022-08-01 12:10 UTC, Phlair commented on airbyte-integrations/connectors/source-github/source_github/graphql.py
> +    def get_query_root_repository(self, owner, name, first, after=None):
all these funcs could do with:

- type hints on params
- brief docstring explaining what they are achieving.

2022-08-02 11:18 UTC, grubberr commented on airbyte-integrations/connectors/source-github/source_github/graphql.py
> +    def get_query_root_repository(self, owner, name, first, after=None):
added

2022-08-02 11:18 UTC, grubberr commented
/test connector=connectors/source-github

2022-08-02 11:35 UTC, grubberr commented
/publish connector=connectors/source-github

2022-08-02 11:57 UTC, merged