Fix multiply log bindings
airbytehq/airbyte pull request #14801
Opened 2022-07-18 17:08 UTC by DoNotPanicUA

## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

2022-07-18 17:16 UTC, DoNotPanicUA commented
/test connector=connectors/source-mysql

2022-07-19 10:16 UTC, DoNotPanicUA commented
/test connector=connectors/destination-mysql

2022-07-19 10:28 UTC, DoNotPanicUA commented
/test connector=connectors/source-mysql

2022-07-19 10:57 UTC, DoNotPanicUA commented
Before:
![Screenshot from 2022-07-19 13-49-25](https://user-images.githubusercontent.com/30464745/179734274-e6c5a343-7cff-4cc0-a87b-96fe5c416a79.png)
After:
![Screenshot from 2022-07-19 13-49-39](https://user-images.githubusercontent.com/30464745/179734293-f71cdc70-4869-4a0d-ab5d-03cd6e2cb9ed.png)

2022-07-19 12:01 UTC, mkhokh-33 approved these changes

2022-07-22 07:56 UTC, subodh1810 requested changes
@DoNotPanicUA I upgraded mysql to use `airbyte-integrations/bases/debezium-v1-9-2` So you need to make this change there as well. 
Secondly to test this lets run a sync in CDC mode for mysql, postgres and mssql by deploying this change in in local Airbyte instance and see if the logs are as expected or not

2022-07-22 10:17 UTC, DoNotPanicUA commented
/test connector=connectors/source-mssql

2022-07-22 10:17 UTC, DoNotPanicUA commented
/test connector=connectors/source-postgres

2022-07-22 10:17 UTC, DoNotPanicUA commented
/test connector=connectors/destination-mssql

2022-07-22 10:17 UTC, DoNotPanicUA commented
/test connector=connectors/destination-postgres

2022-07-22 11:16 UTC, DoNotPanicUA commented
> @DoNotPanicUA I upgraded mysql to use `airbyte-integrations/bases/debezium-v1-9-2` So you need to make this change there as well. Secondly to test this lets run a sync in CDC mode for mysql, postgres and mssql by deploying this change in in local Airbyte instance and see if the logs are as expected or not

@subodh1810 I've checked `1-9-2` version during implementation. There are no conflicts inside.

MySql tests including CDC : [Error not found](https://github.com/airbytehq/airbyte/runs/7407306688?check_suite_focus=true#step:11:2672) :heavy_check_mark: 
MsSql tests including CDC : [Error not found](https://github.com/airbytehq/airbyte/runs/7466485830?check_suite_focus=true) :heavy_check_mark: 
Postgres tests including CDC : [Error not found](https://github.com/airbytehq/airbyte/runs/7466484424?check_suite_focus=true) :heavy_check_mark: 

I've checked MySql locally on the Airbyte instance and don't see any differences between logs inside destination tests and the connector's run.
Also, I'm going to push only MySql source and destination with this change, as it was requested only there.
Other fixed sources/destinations will be published with other changes.

2022-07-22 11:20 UTC, subodh1810 commented
@DoNotPanicUA I dont see this change in this file `airbyte-integrations/bases/debezium-v1-9-2/build.gradle`

2022-07-22 11:24 UTC, DoNotPanicUA commented
> @DoNotPanicUA I dont see this change in this file `airbyte-integrations/bases/debezium-v1-9-2/build.gradle`

They are not required there.
The `1.9.2` version doesn't have implicit bindings anymore.

2022-07-25 07:38 UTC, subodh1810 commented
/test connector=connectors/source-mysql

2022-07-25 07:39 UTC, subodh1810 commented
@DoNotPanicUA I pushed a commit to your branch to pull in latest changes from master (I noticed your branch didnt have changes from PR https://github.com/airbytehq/airbyte/pull/14542)

2022-07-25 09:31 UTC, DoNotPanicUA commented
@subodh1810 
thanks, I will check the latest state.

2022-07-25 10:28 UTC, DoNotPanicUA commented
@subodh1810 
checked mysql. there are no errors as expected.
[logs-26.txt](https://github.com/airbytehq/airbyte/files/9180277/logs-26.txt)

2022-07-25 11:39 UTC, alexandr-shegeda approved these changes

2022-07-26 18:00 UTC, subodh1810 commented
@DoNotPanicUA we need to run connectors in CDC mode, [here](https://github.com/airbytehq/airbyte/pull/14801#issuecomment-1193865677) the logs are from a non CDC mode sync

2022-07-27 03:03 UTC, grishick approved these changes

2022-07-27 10:14 UTC, DoNotPanicUA commented
@subodh1810 
[logs-30.txt](https://github.com/airbytehq/airbyte/files/9197366/logs-30.txt)

Maybe I'm missing something, but why do you expect another behavior of compiled version inside tests where we run it as docker container and inside docker compose where we execute it in the same way?
If there is a difference, shall we change our tests to cover it?

2022-08-02 09:45 UTC, DoNotPanicUA commented
/publish connector=connectors/source-postgres

2022-08-02 09:45 UTC, DoNotPanicUA commented
/publish connector=connectors/source-mysql

2022-08-02 09:46 UTC, DoNotPanicUA commented
/publish connector=connectors/source-mssql

2022-08-02 09:46 UTC, DoNotPanicUA commented
/publish connector=connectors/destination-bigquery

2022-08-02 09:46 UTC, DoNotPanicUA commented
/publish connector=connectors/destination-bigquery-denormalized

2022-08-02 09:46 UTC, DoNotPanicUA commented
/publish connector=connectors/destination-s3

2022-08-02 09:46 UTC, DoNotPanicUA commented
/publish connector=connectors/destination-gcs

2022-08-02 09:47 UTC, DoNotPanicUA commented
/publish connector=connectors/source-mysql-strict-encrypt

2022-08-02 09:47 UTC, DoNotPanicUA commented
/publish connector=connectors/source-mssql-strict-encrypt

2022-08-02 09:47 UTC, DoNotPanicUA commented
/publish connector=connectors/source-postgres-strict-encrypt

2022-08-02 16:38 UTC, evantahler commented
This PR closes https://github.com/airbytehq/airbyte/issues/13583

2022-08-03 00:31 UTC, edgao commented
Is this PR ready to merge? (so that I can publish source-postgres)

2022-08-03 15:09 UTC, edgao commented
I'm going to merge this into master as-is (after resolving the merge conflict) - will mark destinations s3 and gcs as unpublished.

2022-08-03 15:21 UTC, grishick commented
/test connector=connectors/destination-gcs

2022-08-03 15:35 UTC, edgao commented
/publish connector=connectors/destination-bigquery

2022-08-03 15:35 UTC, edgao commented
/publish connector=connectors/destination-bigquery-denormalized

2022-08-03 16:05 UTC, grishick approved these changes

2022-08-03 16:36 UTC, merged

2022-08-04 06:22 UTC, DoNotPanicUA commented
@edgao 
Followup issues:
#15285
#15286

2022-08-04 14:27 UTC, edgao commented
does destination-databricks need to be published? It has some changes to its build.gradle in this PR also

2022-08-05 08:56 UTC, DoNotPanicUA commented
> does destination-databricks need to be published? It has some changes to its build.gradle in this PR also

#15353
The Databricks destination is also broken. [Test run](https://github.com/airbytehq/airbyte/runs/7687769248?check_suite_focus=true)

2022-08-08 17:22 UTC, tuliren commented on docs/integrations/destinations/bigquery.md
> +| 1.1.12  | 2022-08-02 | [14801](https://github.com/airbytehq/airbyte/pull/14801) | Fix multiply log bindings |
This new version for this PR should be `1.1.13`. `1.1.12` is already allocated to `Fix standard loading mode`. This is fixed in https://github.com/airbytehq/airbyte/pull/15409.

2022-08-08 17:22 UTC, tuliren commented on docs/integrations/destinations/bigquery.md
> +| 1.1.13  | 2022-08-02 | [14801](https://github.com/airbytehq/airbyte/pull/14801) | Fix multiply log bindings |
Same here, the new version should be `1.1.14`.