New Source: Zenefits
airbytehq/airbyte pull request #14809
Opened 2022-07-18 19:32 UTC by makyash

## What
*Describe what the change is solving* 
Hello Team, <br>
We at Pliancy, have created this python custom connector, that interacts with the API and pulls the data from the source. This connector helps in time tracking and is used by many companies like ours. Everything is explained properly on how to work this connector locally as well in the readme.md file.

*It helps to add screenshots if it affects the frontend.*

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*
<img width="1163" alt="Screen Shot 2022-07-08 at 3 50 40 PM" src="https://user-images.githubusercontent.com/64660381/179601725-00368085-df93-4d4e-8987-77ce22076396.png">

<img width="1149" alt="Screen Shot 2022-07-08 at 3 51 05 PM" src="https://user-images.githubusercontent.com/64660381/179601752-893ac236-659f-4c5f-96d4-ab4fd880aeb6.png">

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*
![Screen Shot 2022-07-18 at 2 29 48 PM](https://user-images.githubusercontent.com/64660381/179602256-17877fca-315c-484a-a901-5c6913b56e90.png)

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*
![Screen Shot 2022-07-15 at 6 18 41 PM](https://user-images.githubusercontent.com/64660381/179601466-9c280b8f-cf4e-46af-933b-2298961dc703.png)

</details>

2022-07-19 14:28 UTC, makyash commented
here's my email:  yash.makwana@pliancy.com, do reach out to me for any questions.

2022-08-15 23:25 UTC, marcosmarxm commented
@harshithmullapudi could you review this and publish without the credentials for now?

2022-08-16 13:55 UTC, marcosmarxm requested changes
I made a few comments, sorry the long delay to review it.

2022-08-16 13:55 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-zenefits/source_zenefits/schemas/TODO.md
> +# TODO: Define your stream schemas
Remove this file.

2022-08-16 13:55 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-zenefits/source_zenefits/source.py
> +class people(ZenefitsStream):
Python Class are Capitalize.

2022-08-16 13:55 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-zenefits/source_zenefits/source.py
> +        return people_headers
```suggestion
    def request_headers(self, **kwargs) -> Mapping[str, Any]:
        return {"Authorization": f"Bearer {self.token}", "Content-Type": "application/json", "Accept": "application/json"}
```

2022-08-16 13:55 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-zenefits/source_zenefits/source.py
> +        return eresponse
Move this to parent stream as

```python
def parse_response(...):
    return response.json().get("data", {}).get("data")

2022-08-16 13:55 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-zenefits/source_zenefits/source.py
> +            return False, e
Check how other connectors made this implementation for `check_connection`.

2022-08-16 13:55 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-zenefits/source_zenefits/spec.json
> +        "description": "describe me"
update the `describe me`.

2022-08-18 15:34 UTC, makyash commented
@marcosmarxm  I have made the necessary changes you suggested, the only thing with check_connection is I have a Bearer Token and I have to work surround that. 
I ran source acceptance test again after making the changes to help speed up the process, you can find the test screenshot below

![Screen Shot 2022-08-18 at 10 31 00 AM](https://user-images.githubusercontent.com/64660381/185435478-a30918cf-56b9-4790-bb29-cee25732bbdc.png)

2022-08-24 07:47 UTC, harshithmullapudi commented
Hey @makyash is it possible to give me access to push a commit over this repo. I have some fixes to make and a documentation to add. If not do you mind doing these

1. Add a new record in source_definition file just after zendesk
```
- name: Zenefits
  sourceDefinitionId: 8baba53d-2fe3-4e33-bc85-210d0eb62884
  dockerRepository: airbyte/source-zenefits
  dockerImageTag: 0.1.0
  documentationUrl: https://docs.airbyte.io/integrations/sources/zenefits
  icon: zenefits.svg
  sourceType: api
  releaseStage: alpha
```
2. Create a new file in docs/integrations/sources and name it zenefits.md and contents attached below
3. Remove sample_files folder and then remove all TODO.md files
[zenefits.md](https://github.com/airbytehq/airbyte/files/9413978/zenefits.md)

4. Run `./gradlew format`

2022-08-24 18:52 UTC, makyash commented
@harshithmullapudi let me know, if the changes were accurate or else I will give you the access to push  a commit into this repo.

2022-09-12 07:09 UTC, harshithmullapudi commented
Sure checking

2022-09-14 05:39 UTC, harshithmullapudi commented
LGTM

2022-09-14 05:39 UTC, harshithmullapudi approved these changes

2022-09-22 04:16 UTC, harshithmullapudi commented
/publish connector=connectors/source-zenefits

2022-09-22 06:56 UTC, harshithmullapudi commented
/publish connector=connectors/source-zenefits run-tests=false

2022-09-22 16:55 UTC, merged