Destination S3 connector check ignores the s3_bucket_path
airbytehq/airbyte pull request #15207
Opened 2022-08-02 16:10 UTC by haithem-souala

Fix for #15195 & #11871

2022-08-02 16:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=15207) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=15207) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=15207) it.</sub>

2022-08-03 17:03 UTC, marcosmarxm commented
/test connector=connectors/destination-s3

2022-08-03 17:06 UTC, marcosmarxm commented
@sashaNeshcheret can you review this contribution?

2022-08-03 20:50 UTC, marcosmarxm commented
/test connector=connectors/destination-s3

2022-08-05 14:35 UTC, haithem-souala commented
/test connector=connectors/destination-s3

2022-08-08 10:13 UTC, haithem-souala commented
Hey @sashaNeshcheret, could you review this PR please?

2022-08-11 15:04 UTC, marcosmarxm commented
/test connector=connectors/destination-s3

2022-08-11 22:28 UTC, marcosmarxm commented
/test connector=connectors/destination-s3

2022-08-22 04:43 UTC, marcosmarxm commented
@sashaNeshcheret can you do the final approval here?

2022-08-22 16:37 UTC, sashaNeshcheret commented
Hi @haithem-souala, sorry i've not a chance to make review earlier. 
I've tested PR and it really covers case when user has just read permissions on s3 and in such case we are trying to create new object(with bucket name) instead of using path that specified in config. From my perspective it can be properly published and merged. Thanks for your work.
CC: @marcosmarxm

2022-08-22 16:38 UTC, sashaNeshcheret approved these changes
Looks good to me

2022-08-22 19:45 UTC, haithem-souala commented
Hey @marcosmarxm,
The PR is approved, how can i publish the connector ?

2022-08-24 04:41 UTC, marcosmarxm requested changes

2022-08-24 04:41 UTC, marcosmarxm commented on airbyte-integrations/connectors/destination-s3/Dockerfile
> +LABEL io.airbyte.name=airbyte/destination-s3
add eof here and allow maintaners edit your branch so I can run the publish command.

2022-08-24 08:44 UTC, marcosmarxm commented
/publish connector=connectors/destination-s3

2022-08-24 09:46 UTC, marcosmarxm approved these changes

2022-08-24 09:46 UTC, merged