🎉 New Source: `Wrike`
airbytehq/airbyte pull request #15638
Opened 2022-08-14 15:58 UTC by tfoldi

## What

This a new source connector for Wrike, which is a work management software used by small and large companies. The source connector works fairly well, but I need some unit tests and feedback from you guys. (So it is WIP)

## How
 * It uses Wrike's v4 API and Python CDK's HttpStream
 * Currently it support tasks, comments, contacts, folders and custom attributes

## Recommended reading order

It is a plan custom source, the most boring one ever. 

## 🚨 User Impact 🚨
No breaking changes.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

I need to work on unit tests, but as I checked the examples (Slack and Exchange API) they did not have any unit tests. 

</details>

<details><summary><strong>Integration</strong></summary>

```
> Task :airbyte-integrations:bases:base-normalization:checkPython
Using python 3.9.13 from /Users/tfoldi/Developer/airbyte/airbyte-integrations/bases/base-normalization/.venv (.venv/bin/python)
Using pip 21.3.1 from /Users/tfoldi/Developer/airbyte/airbyte-integrations/bases/base-normalization/.venv/lib/python3.9/site-packages/pip (python 3.9)

> Task :airbyte-integrations:bases:source-acceptance-test:checkPython
Using python 3.9.13 from /Users/tfoldi/Developer/airbyte/airbyte-integrations/bases/source-acceptance-test/.venv (.venv/bin/python)
Using pip 21.3.1 from /Users/tfoldi/Developer/airbyte/airbyte-integrations/bases/source-acceptance-test/.venv/lib/python3.9/site-packages/pip (python 3.9)

> Task :airbyte-integrations:connectors:source-wrike:checkPython
Using python 3.9.13 from /Users/tfoldi/Developer/airbyte/airbyte-integrations/connectors/source-wrike/.venv (.venv/bin/python)
Using pip 21.3.1 from /Users/tfoldi/Developer/airbyte/airbyte-integrations/connectors/source-wrike/.venv/lib/python3.9/site-packages/pip (python 3.9)

> Task :airbyte-integrations:bases:base-normalization:pipInstall
[python] .venv/bin/python -m pip install pip==21.3.1
         Requirement already satisfied: pip==21.3.1 in ./.venv/lib/python3.9/site-packages (21.3.1)
         WARNING: You are using pip version 21.3.1; however, version 22.2.2 is available.
         You should consider upgrading via the '/Users/tfoldi/Developer/airbyte/airbyte-integrations/bases/base-normalization/.venv/bin/python -m pip install --upgrade pip' command.
[python] .venv/bin/python -m pip list --format=columns
         Package                Version
         ---------------------- ---------
         airbyte-cdk            0.1.74
         attrs                  22.1.0
         backoff                2.1.2
         black                  22.3.0
         certifi                2022.6.15
         charset-normalizer     2.1.0
         click                  8.1.3
         coverage               6.3.1
         dataclasses-jsonschema 2.15.1
         Deprecated             1.2.13
         dpath                  2.0.6
         flake8                 4.0.1
         idna                   3.3
         iniconfig              1.1.1
         isort                  5.6.4
         Jinja2                 3.1.2
         jsonref                0.2
         jsonschema             3.2.0
         MarkupSafe             2.1.1
         mccabe                 0.6.1
         multidict              6.0.2
         mypy                   0.930
         mypy-extensions        0.4.3
         normalization          0.0.0
         packaging              21.3
         pathspec               0.9.0
         pendulum               2.1.2
         pip                    21.3.1
         platformdirs           2.5.2
         pluggy                 0.13.1
         py                     1.11.0
         pycodestyle            2.8.0
         pydantic               1.9.2
         pyflakes               2.4.0
         pyparsing              3.0.9
         pyproject-flake8       0.0.1a2
         pyrsistent             0.18.1
         pytest                 6.1.2
         python-dateutil        2.8.2
         pytzdata               2020.1
         PyYAML                 5.4.1
         requests               2.28.1
         setuptools             63.2.0
         six                    1.16.0
         toml                   0.10.2
         tomli                  2.0.1
         types-PyYAML           6.0.11
         typing_extensions      4.3.0
         urllib3                1.26.11
         vcrpy                  4.2.0
         wheel                  0.37.1
         wrapt                  1.14.1
         yarl                   1.8.1
         WARNING: You are using pip version 21.3.1; however, version 22.2.2 is available.
         You should consider upgrading via the '/Users/tfoldi/Developer/airbyte/airbyte-integrations/bases/base-normalization/.venv/bin/python -m pip install --upgrade pip' command.

> Task :airbyte-integrations:bases:source-acceptance-test:pipInstall
[python] .venv/bin/python -m pip install pip==21.3.1
         Requirement already satisfied: pip==21.3.1 in ./.venv/lib/python3.9/site-packages (21.3.1)
         WARNING: You are using pip version 21.3.1; however, version 22.2.2 is available.
         You should consider upgrading via the '/Users/tfoldi/Developer/airbyte/airbyte-integrations/bases/source-acceptance-test/.venv/bin/python -m pip install --upgrade pip' command.
[python] .venv/bin/python -m pip list --format=columns
         Package                Version
         ---------------- [...]

2022-08-14 15:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=15638) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=15638) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=15638) it.</sub>

2022-08-15 14:57 UTC, marcosmarxm commented
Thanks for the contribution @tfoldi please let us know when it's ready to review.

2022-08-16 21:40 UTC, tfoldi commented
@marcosmarxm it is ready from my end, thx!

2022-08-22 10:55 UTC, harshithmullapudi requested changes, later dismissed
Thanks for the contribution

Could you run `./gradlew format`.

2022-08-22 10:55 UTC, harshithmullapudi commented on airbyte-integrations/connectors/source-wrike/acceptance-test-config.yml
> +  #        extra_records: yes
you can remove this in case we are using this

2022-08-22 10:55 UTC, harshithmullapudi commented on airbyte-integrations/connectors/source-wrike/bootstrap.md
> +To generate a token:
can't we add this to README.md?

2022-08-22 10:55 UTC, harshithmullapudi commented on airbyte-integrations/connectors/source-wrike/sample_files/configured_catalog.json
> +        "json_schema": {
you can delete this incase you are already using the one in integration_tests folder

2022-08-22 10:55 UTC, harshithmullapudi commented on airbyte-integrations/connectors/source-wrike/source_wrike/source.py
> +class WrikeStream(HttpStream, ABC):
Could you add the link to documentation here?

2022-08-27 15:18 UTC, tfoldi commented
> Thanks for the contribution
> 
> Could you run `./gradlew format`.

Sure, I did. please let me know if you need any other changes

2022-09-08 17:37 UTC, sajarin commented
Assigned to @tuanchris as part of Airbyte's Community Maintainer program

2022-09-10 14:19 UTC, tuanchris requested changes
Hi @tfoldi, thank you for contributing. Your code looks good so far. I left some comments on things you can improve for readability.

2022-09-10 14:19 UTC, tuanchris commented on airbyte-integrations/connectors/source-wrike/unit_tests/test_streams.py
> +    # TODO: replace this with your expected http request method
can you remove this TODO comment

2022-09-11 11:40 UTC, tfoldi commented on airbyte-integrations/connectors/source-wrike/source_wrike/source.py
> +
I will certainly change it, but just FYI, I took the code from tutorial as implemented in https://github.com/airbytehq/airbyte/blob/6b4c5235ec066363321d9927a69092790d39f01c/airbyte-integrations/connectors/source-exchange-rates/source_exchange_rates/source.py#L96

Perhaps the docs and this sample connect should be changed too

2022-09-11 12:46 UTC, tfoldi commented
sure, just implemented the changes @tuanchris

2022-09-14 02:05 UTC, sajarin commented
@tfoldi can you post a screenshot of passing acceptance tests?

2022-09-14 08:26 UTC, tfoldi commented
Logs were attached in the original PR description, but if you prefer images:

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/82426/190101390-ab6f8a2d-cde3-4b9e-a15a-75e812380554.png">
<img width="2557" alt="image" src="https://user-images.githubusercontent.com/82426/190101931-0d0555ee-6ceb-4822-8265-31711fe56cd4.png">

2022-09-14 17:48 UTC, sajarin approved these changes

2022-09-14 17:49 UTC, sajarin commented
/publish connector=connectors/source-wrike

2022-09-14 18:54 UTC, sajarin commented
/publish connector=connectors/source-wrike run-tests=false

2022-09-15 17:57 UTC, merged

2022-09-15 17:58 UTC, sajarin commented
Thanks for the connector @tfoldi and thanks for the review @tuanchris!