hot fix mssql cdc data type: decimal, money
airbytehq/airbyte pull request #15782
Opened 2022-08-19 05:53 UTC by duytp

## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*

https://github.com/airbytehq/airbyte/issues/15780

## How
*Describe the solution*
Add Datatype: SMALLMONEY, DECIMAL, NUMERIC in MSSQLConverter.java

2022-08-19 05:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=15782) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=15782) before we can accept your contribution.<br/><hr/>**Tran Phuoc Duy** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=15782) it.</sub>

2022-08-19 05:56 UTC, duytp commented
@gsmith-schlesinger thank you for your contribution.

2022-08-22 06:49 UTC, marcosmarxm commented
/test connector=connectors/source-mssql

2022-08-25 02:45 UTC, marcosmarxm commented
Thanks @duytp team will review later today or next week your contribution! Sorry the delay

2022-08-29 21:48 UTC, marcosmarxm commented
@subodh1810 can you review this contribution?

2022-08-31 21:15 UTC, marcosmarxm commented
/test connector=connectors/source-mssql

2022-09-03 11:18 UTC, subodh1810 requested changes
The test is failing, we need to add new tests for this change as well

2022-09-03 11:18 UTC, subodh1810 commented on airbyte-integrations/bases/debezium-v1-4-2/src/main/java/io/airbyte/integrations/debezium/internals/MSSQLConverter.java
> +        return ((BigDecimal) input).doubleValue();
I dont understand why are we converting to the double value? Whats wrong with using BigDecimal as it is? Wouldnt it result in loss of precision and scale?

2022-09-13 17:49 UTC, marcosmarxm commented
@duytp did you check Subbodh's comments?

2022-09-20 13:58 UTC, marcosmarxm commented
Closing due inactivity @duytp let me know if you want to continue this contribution then I can reopen it.

2022-09-20 13:58 UTC, closed without merging