documentation (fix): Added boolean datatype in official docs
airbytehq/airbyte pull request #16048
Opened 2022-08-28 06:13 UTC by Jagrutiti

## What
Added Boolean datatype in the documentation page (https://docs.airbyte.com/understanding-airbyte/supported-data-types/#the-types)

## Closes
Boolean data type is missing from official docs #12739

2022-08-28 06:18 UTC, Jagrutiti commented on docs/understanding-airbyte/supported-data-types.md
> +#### Boolean
I am not sure how to describe the `Boolean` type here

2022-08-28 06:19 UTC, Jagrutiti commented on docs/understanding-airbyte/supported-data-types.md
> +| Boolean                              | `{"type": "boolean"}`                                                                                     |                                `True` or` False`
I did what I thought the boolean type would be. I did not have a reference to an API or anything that takes this data.

2022-08-31 01:27 UTC, marcosmarxm requested changes

2022-09-08 12:41 UTC, marcosmarxm commented
Close due inactivity.

2022-09-08 12:41 UTC, closed without merging