10730 Added custom JDBC parameters to Source Redshift
airbytehq/airbyte pull request #16058
Opened 2022-08-29 05:06 UTC by suhomud

## What
Add support for Redshift Source to take in a JDBC URL Params input to specify any additional JDBC parameters for the connection.

## Recommended reading order
1. `x.java`
2. `y.python`

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

2022-08-29 05:08 UTC, suhomud commented
/test connector=connectors/source-redshift

2022-08-29 06:16 UTC, suhomud commented
<img width="656" alt="Screenshot 2022-08-29 at 13 16 01" src="https://user-images.githubusercontent.com/5124694/187135134-0c6d42e7-c95c-4236-a4a1-e1bdfedc6720.png">

2022-08-29 08:33 UTC, DoNotPanicUA requested changes

2022-08-29 08:33 UTC, DoNotPanicUA commented on docs/integrations/sources/redshift.md
> +| 0.3.12  | 2022-05-25 |  | Added JDBC URL params                                                                                     |
Version is not increased

2022-08-29 08:33 UTC, DoNotPanicUA commented on airbyte-integrations/connectors/source-redshift/src/test/java/io/airbyte/integrations/source/redshift/RedshiftSpecTest.java
> +    final JsonNode config = Jsons.deserialize(CONFIGURATION);
It makes sense to have a get method for this operation and call it in the BeforeEach

2022-08-29 08:58 UTC, suhomud commented on docs/integrations/sources/redshift.md
> +| 0.3.12  | 2022-05-25 |  | Added JDBC URL params                                                                                     |
ouch, thanks

2022-08-29 09:33 UTC, DoNotPanicUA approved these changes

2022-08-29 19:53 UTC, grishick approved these changes

2022-08-30 04:28 UTC, suhomud commented
/publish connector=connectors/source-redshift

2022-08-30 04:44 UTC, merged