SATS: fix backwards compatibility
airbytehq/airbyte pull request #16429
Opened 2022-09-08 08:23 UTC by davydov-d

## What
SATs declare widening of a data type is ok but in reality tests do not pass in a `'integer'-> '[integer, string]'` type change. Fixing it here

2022-09-08 08:33 UTC, davydov-d commented
/test connector=bases/source-acceptance-test

2022-09-08 13:11 UTC, lazebnyi approved these changes

2022-09-08 23:00 UTC, sherifnada requested changes
@davydov-d could you add a unit test to verify this behavior?

2022-09-09 08:14 UTC, davydov-d commented
/test connector=bases/source-acceptance-test

2022-09-09 08:23 UTC, davydov-d commented
> @davydov-d could you add a unit test to verify this behavior?

@sherifnada sure, done. I've also separated spec validation from catalog validation because I believe the behavior should be different in these cases

2022-09-09 14:30 UTC, alafanechere requested changes
@davydov-d could you please explain your motivation for this change? Type widening sounds dangerous at first sight. Is it your approach to changing a spec type but still supporting the previous type?

2022-09-09 15:16 UTC, davydov-d commented
> @davydov-d could you please explain your motivation for this change? Type widening sounds dangerous at first sight. Is it your approach to changing a spec type but still supporting the previous type?

@alafanechere Yes. [here](https://github.com/airbytehq/airbyte/pull/16400) I need to change data type from integer to string but support legacy integer values as well. That's why here I'm letting `<old_type> -> [<old_type>, <new_type>]` change to be valid (only for spec, not for catalog). Besides, it is stated to be a valid use case [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/utils/backward_compatibility.py#L79), but is not at the moment

2022-09-09 16:46 UTC, alafanechere approved these changes
Thank you for the clarification. LGTM

2022-09-09 16:46 UTC, alafanechere commented on airbyte-integrations/bases/source-acceptance-test/CHANGELOG.md
> +Backward compatibility tests: improve `check_if_type_of_type_field_changed` to make it less radical when validating specs and allow `'str' -> ['str', 'another_str']` type changes.[#16429](https://git
nit
```suggestion
Backward compatibility tests: improve `check_if_type_of_type_field_changed` to make it less radical when validating specs and allow `'str' -> ['str', '<another_type>']` type changes.[#16429](https://github.com/airbytehq/airbyte/pull/16429/)
```

2022-09-09 17:24 UTC, sherifnada approved these changes

2022-09-09 21:02 UTC, pedroslopez approved these changes

2022-09-12 07:07 UTC, davydov-d commented
/publish connector=bases/source-acceptance-test auto-bump-version=false

2022-09-12 07:38 UTC, merged