Hiring lever
airbytehq/airbyte pull request #16572
Opened 2022-09-11 08:33 UTC by akashkmr27089

## What
*Describe what the change is solving*
Added Basic Auth authentication to the Lever Hiring connector
https://github.com/airbytehq/airbyte/issues/16358

https://hire.lever.co/developer/documentation

Impact: 
No impact in functionality

2022-09-11 08:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=16572) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=16572) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=16572) it.</sub>

2022-09-11 08:35 UTC, akashkmr27089 commented
hi @sajarin , i have created the pr for resolving issue https://github.com/airbytehq/airbyte/issues/16358
I have not tested the flow as i dont have credentials, but based on documentation it should work fine. 
Please review it

2022-09-12 18:05 UTC, misteryeo commented
**Issue was linked to Harvestr Discovery:**  [Source Lever Hiring: Support API Key authentication](https://app.harvestr.io/components/0/list/5xDGRstVm)

2022-09-13 15:27 UTC, sajarin commented
Hi @akashkmr27089, thanks for working on this feature. This PR is part of Airbyte's Community Maintainer program and someone from the community will be assigned to review your PR and get it merged. Thanks for being patient!

2022-09-15 23:24 UTC, YiyangLi commented on .vscode/settings.json
> +  "python.analysis.extraPaths": [
I understand it may improve your local vscode setup, is it okay to undo this change? Thanks.

2022-09-15 23:24 UTC, YiyangLi commented on airbyte-integrations/connectors/source-lever-hiring/source_lever_hiring/source.py
> +    if config and config["credemtials"] and 'api_key' in config["credentials"]:
is it a typo, `credemtials`?

2022-09-15 23:27 UTC, YiyangLi commented on airbyte-integrations/connectors/source-lever-hiring/source_lever_hiring/spec.json
> +                "enum": ["Api Key"],
I think an api key is dynamic for each develop application. is it a string enum? Essentially, the spec.json comes from JSON Schema, and [here](https://json-schema.org/understanding-json-schema/reference/generic.html#enumerated-values) is the doc for enum.

2022-09-15 23:29 UTC, YiyangLi commented on airbyte-integrations/connectors/source-lever-hiring/source_lever_hiring/spec.json
> +              "api_key": {
can you add an `order` of ` for the property `api_key`?

2022-09-15 23:30 UTC, YiyangLi commented on airbyte-integrations/connectors/source-lever-hiring/source_lever_hiring/source.py
> +    if config and config["credemtials"] and 'api_key' in config["credentials"]:
is it okay to add a check on config["credentials"]["auth_type"], when the auth_type is `Api Key`

2022-09-15 23:31 UTC, YiyangLi commented
can you help update the read me to reflect the additional authorization mode? https://github.com/airbytehq/airbyte/blob/master/docs/integrations/sources/lever-hiring.md#getting-started

2022-09-15 23:36 UTC, YiyangLi commented on airbyte-integrations/connectors/source-lever-hiring/source_lever_hiring/source.py
> +    else:
https://github.com/airbytehq/airbyte/blob/e1983114bcb3b524c64c6c1f3f74a52da14ba363/airbyte-integrations/connectors/source-lever-hiring/unit_tests/test_source.py#L11-L14

Similar to the unit test for `check_connection` above, can you add one for the basic auth? Thanks.

2022-09-17 14:49 UTC, YiyangLi requested changes
can you add some tests for the basic auth? Can you also update the readme to reflect the new authorization mode? Thanks.

2022-09-29 14:25 UTC, sajarin commented
@akashkmr27089, where are we with this PR? Can you provide an update? Thanks!

2022-10-12 13:29 UTC, alexchouraki commented
Hello!
Any news on this one? It would be pretty useful for me in my deployment of Airbyte...

2022-10-12 17:28 UTC, YiyangLi commented
@alexchouraki Hi, we didn't hear an update from @akashkmr27089, my last change request is to add unit tests for the basic auth, add sample config, and update the readme doc. You are encouraged to continue the work if you are interested.

2022-10-14 14:06 UTC, alexchouraki commented
@YiyangLi, just did so, please have a look! :)

2022-10-20 17:51 UTC, closed without merging