Airbyte amazon ads brands products filter
airbytehq/airbyte pull request #16829
Opened 2022-09-16 20:00 UTC by sage-watterworth

## What
This PR will allow Brand and Product campaigns to use the status (state) filter. This is an iteration of the following PR: 
https://github.com/airbytehq/airbyte/pull/15985

<img width="735" alt="Screen Shot 2022-08-25 at 2 39 48 PM" src="https://user-images.githubusercontent.com/83830720/186743245-3d1091fa-f3e2-4f9f-b4ee-7a02230dc1fe.png">

## How
Adding request params to Brand and Product campaigns. 

## Recommended reading order
1. `sponsored_brands.py`
2. `sponsored_product.py`
3. `test_report_streams.py`

## 🚨 User Impact 🚨
The parameter is optional and will not affect current functionality.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

> Task :airbyte-integrations:connectors:source-amazon-ads:unitTest
Name                                                              Stmts   Miss  Cover
-------------------------------------------------------------------------------------
source_amazon_ads/utils.py                                            9      0   100%
source_amazon_ads/streams/sponsored_products.py                      41      0   100%
source_amazon_ads/streams/sponsored_display.py                       31      0   100%
source_amazon_ads/streams/sponsored_brands.py                        26      0   100%
source_amazon_ads/streams/report_streams/products_report.py          18      0   100%
source_amazon_ads/streams/report_streams/display_report.py           16      0   100%
source_amazon_ads/streams/report_streams/brands_video_report.py      10      0   100%
source_amazon_ads/streams/report_streams/brands_report.py            10      0   100%
source_amazon_ads/streams/report_streams/__init__.py                  5      0   100%
source_amazon_ads/streams/profiles.py                                21      0   100%
source_amazon_ads/streams/__init__.py                                 6      0   100%
source_amazon_ads/schemas/sponsored_products.py                      37      0   100%
source_amazon_ads/schemas/sponsored_display.py                       31      0   100%
source_amazon_ads/schemas/sponsored_brands.py                        22      0   100%
source_amazon_ads/schemas/profile.py                                 16      0   100%
source_amazon_ads/schemas/__init__.py                                 6      0   100%
source_amazon_ads/constants.py                                        1      0   100%
source_amazon_ads/__init__.py                                         2      0   100%
source_amazon_ads/streams/common.py                                  76      1    99%
source_amazon_ads/schemas/common.py                                  51      1    98%
source_amazon_ads/streams/report_streams/report_streams.py          240     18    92%
source_amazon_ads/source.py                                          38      8    79%
-------------------------------------------------------------------------------------
TOTAL                                                               713     28    96%

> Task :airbyte-integrations:bases:source-acceptance-test:_unitTestCoverage
         collecting ... 
         
          test_asserts.py::test_verify_records_schema ✓                     0%           
          test_asserts.py::test_validate_records_format[record0-configured_catalog0-False] ✓1% ▏         
          test_asserts.py::test_validate_records_format[record1-configured_catalog1-False] ✓1% ▏         
          test_asserts.py::test_validate_records_format[record2-configured_catalog2-False] ✓1% ▎         
          test_asserts.py::test_validate_records_format[record3-configured_catalog3-False] ✓2% ▎         
          test_asserts.py::test_validate_records_format[record4-configured_catalog4-True] ✓2% ▎         
          test_asserts.py::test_validate_records_format[record5-configured_catalog5-False] ✓2% ▎         
          test_asserts.py::test_validate_records_format[record6-configured_catalog6-True] ✓3% ▍         
          test_asserts.py::test_validate_records_format[record7-configured_catalog7-False] ✓3% ▍         
          test_asserts.py::test_validate_records_format[record8-configured_catalog8-False] ✓3% ▍         
          test_asserts.py::test_validate_records_format[record9-configured_catalog9-True] ✓4% ▍         
          test_asserts.py::test_validate_records_format[record10-configured_catalog10-True] ✓4% ▍         
          test_asserts.py::test_validate_records_format[record11-configured_catalog11-True] ✓4% ▌         
          test_asserts.py::test_validate_records_format[record12-configured_catalog12-True] ✓5% ▌         
          test_asserts.py::test_validate_records_format[record13-configured_catalog13-False] ✓5% ▌         
          test_asserts.py::test_validate_records_format[record14-configured_catalog14-False] ✓5% ▌         
          test_asserts.py::test_validate_records_format[record15-configured_catalog15-False] ✓6% ▋         
          test_asserts.py::test_validate_records_format[record16-configured_catalog16-True] ✓6% ▋         
          test_asserts.py::test_validate_records_format[record17-configured_catalog17-False] ✓6% ▋         
          test_asserts.py::test_validate_records_format[record18-configured_catalog18-True] ✓7% ▋         
          test_asserts.py::test_validate_records_format[record19-configured_catalog19-True] ✓7% ▊         
          test_asserts.py::test_validate_records_format[record20-configured_catalog20-True] ✓7% ▊         
          test_asserts.py::test_validate_records_format[record21-configured_catalog21-False] ✓7% ▊         
          test_asserts.py::test_validate_records_format[record22-configured_catalog22-False] ✓8% ▊         
          test_asserts.py::test_validate_records_format[record23-configured_catalog23-True] ✓8% ▊         
          test_asserts.py::test_val [...]

2022-09-26 16:53 UTC, sajarin commented
Hey @sage-watterworth, thanks for the wait. I'm escalating this PR to our dev team. Thanks for being patient!

2022-09-26 21:09 UTC, sage-watterworth commented
[sajarin](https://github.com/sajarin) thank you for the update!

2022-11-03 15:52 UTC, monai requested changes

2022-11-03 15:52 UTC, monai commented on airbyte-integrations/connectors/source-amazon-ads/unit_tests/test_report_streams.py
> +@pytest.mark.parametrize("state_filter", [["enabled", "archived", "paused"], ["enabled"], None])
Now, these three tests are the same except for the class name. Use `itertools.product` to generate test cases for all state filter and stream class pairs.

```python
from itertools import product

@pytest.mark.parametrize("state_filter", "klass", product(
    [["enabled", "archived", "paused"], ["enabled"], None],
    [SponsoredDisplayCampaigns, SponsoredProductCampaigns, SponsoredBrandsCampaigns]
))
def test_campaign_state_filer(mocker, config, state_filter, klass):
    ...
    mocker.patch.object(klass, "state_filter", new_callable=mocker.PropertyMock, return_value=state_filter)
    ...
```

2022-11-03 15:52 UTC, monai commented on airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/streams/sponsored_display.py
> +    def path(self, **kwargs) -> str:
Fix `kwargs` naming in all the modified files.

2022-11-03 15:52 UTC, monai commented on airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/streams/sponsored_brands.py
> +    def __init__(self, *args, **kwargs):
The use of `state_filter` parameter is copy-pasted across all three streams. Refactor it to a mixin instead, e.g.

```python
class StateFilterMixin:
    state_filter = None

    def __init__(self, *args, **kwargs):
        self.state_filter = kwargs.get("config", {}).get("state_filter")
        super().__init__(*args, **kwargs)

    def request_params(self, *args, **kwargs):
        params = super().request_params(*args, **kwargs)
        if self.state_filter:
            params["stateFilter"] = ",".join(self.state_filter)
        return params

class SponsoredBrandsCampaigns(StateFilterMixin, SubProfilesStream):
    ...
```

Place `StateFilterMixin` in `common.py`.

2022-11-03 18:08 UTC, grubberr commented
@sage-watterworth @monai 
is this PR has to be close because of this https://github.com/airbytehq/airbyte/pull/17475
?

2022-11-04 07:46 UTC, monai commented
> @sage-watterworth @monai is this PR has to be close because of this #17475 ?

Oh, it looks like it duplicates #17475, indeed. I'm closing it, then.

2022-11-04 07:46 UTC, closed without merging