🐛 cron/workspace-cleaner: only run task for docker environments
airbytehq/airbyte pull request #17168
Opened 2022-09-26 19:57 UTC by pedroslopez

## What

Running cron on a kubernetes environment was causing an error when executing the WorkspaceCleaner:

```
2022-09-23 19:39:59 ERROR i.m.s.DefaultTaskExceptionHandler(handle):47 - Error invoking scheduled task for bean [io.airbyte.cron.selfhealing.WorkspaceCleaner@774358c5] /workspace
java.nio.file.NoSuchFileException: /workspace
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148) ~[?:?]
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[?:?]
	at java.nio.file.Files.readAttributes(Files.java:1849) ~[?:?]
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220) ~[?:?]
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277) ~[?:?]
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323) ~[?:?]
	at java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71) ~[?:?]
	at java.nio.file.Files.walk(Files.java:3917) ~[?:?]
	at java.nio.file.Files.walk(Files.java:3972) ~[?:?]
	at io.airbyte.cron.selfhealing.WorkspaceCleaner.deleteOldFiles(WorkspaceCleaner.java:51) ~[io.airbyte-airbyte-cron-0.40.6.jar:?]
	at io.airbyte.cron.selfhealing.$WorkspaceCleaner$Definition$Exec.dispatch(Unknown Source) ~[io.airbyte-airbyte-cron-0.40.6.jar:?]
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.inject.DelegatingExecutableMethod.invoke(DelegatingExecutableMethod.java:76) ~[micronaut-inject-3.6.3.jar:3.6.3]
	at io.micronaut.scheduling.processor.ScheduledMethodProcessor.lambda$process$5(ScheduledMethodProcessor.java:127) ~[micronaut-context-3.6.3.jar:3.6.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]

```

## How

Since this is only intended to run on docker contexts, use the existing `WORKER_ENVIRONMENT` env var to determine if the task should run.

2022-09-26 20:47 UTC, pedroslopez commented on airbyte-cron/src/main/resources/application.yml
> +    env: ${WORKER_ENVIRONMENT:DOCKER}
Using the same structure as in https://github.com/airbytehq/airbyte/blob/c4fb6b7f9eb9c371902e8c4bec484c2427954cf4/airbyte-workers/src/main/resources/application.yml#L87-L88

2022-09-27 18:44 UTC, gosusnp reviewed
The require part looks good to me. I am not sure about the config itself, we had some discussions about that.
@benmoriceau, what do you think?

2022-09-27 23:24 UTC, benmoriceau requested changes
LGTM but we need to add the new env variable to the file `kube/overlays/resources/cron.yml` .

And we will need to make sure that the helm chart have this value as well when they got created.

2022-09-29 18:21 UTC, pedroslopez commented
@benmoriceau  Added to kube/resources/cron.yml in [bbe301b](https://github.com/airbytehq/airbyte/pull/17168/commits/bbe301b636f60a5c2ba841310dc10e8201cb6a65)

2022-09-29 18:49 UTC, pedroslopez commented
Updated to use micronaut environments cc @jdpgrailsdev

2022-09-29 18:57 UTC, jdpgrailsdev approved these changes
:shipit:

2022-09-29 19:32 UTC, benmoriceau approved these changes

2022-09-29 19:53 UTC, merged