new connector source-clockify
airbytehq/airbyte pull request #17767
Opened 2022-10-09 12:14 UTC by RobLucchi

## What
New Source Connector For [Clockify](https://clockify.me/) 

## How
This is a new Source Connector for [Clockify](https://clockify.me/)  using [Python CDK](https://docs.airbyte.com/connector-development/cdk-python/)

## Recommended reading order
2. `y.python`

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

</details>

## Tests
<details><summary><strong>Unit</strong></summary>

airbyte-integrations/connectors/source-clockify/unit_tests/test_source.py::test_check_connection ✓                                                                                                            14% █▌        
 airbyte-integrations/connectors/source-clockify/unit_tests/test_source.py::test_streams ✓                                                                                                                     29% ██▉       
 airbyte-integrations/connectors/source-clockify/unit_tests/test_streams.py::test_request_params ✓                                                                                                             43% ████▍     
 airbyte-integrations/connectors/source-clockify/unit_tests/test_streams.py::test_next_page_token ✓                                                                                                            57% █████▊    
 airbyte-integrations/connectors/source-clockify/unit_tests/test_streams.py::test_read_records ✓                                                                                                               71% ███████▎  
 airbyte-integrations/connectors/source-clockify/unit_tests/test_streams.py::test_request_headers ✓                                                                                                            86% ████████▋ 
 airbyte-integrations/connectors/source-clockify/unit_tests/test_streams.py::test_http_method ✓                                                                                                               100% ██████████

Results (0.24s):
       7 passed

</details>

2022-10-09 12:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=17767) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=17767) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=17767) it.</sub>

2022-10-11 16:32 UTC, marcosmarxm commented
Can you provide the output of integration tests @RobLucchi ?

2022-10-11 16:36 UTC, marcosmarxm requested changes
Some comments, please run the formatter command.

2022-10-11 16:36 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-clockify/source_clockify/spec.json
> +            "X-Api-Key": {
```suggestion
            "api_key": {
```

2022-10-11 16:36 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-clockify/source_clockify/spec.json
> +            "workspaceId": {
```suggestion
            "workspace_id": {
```

2022-10-11 16:36 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-clockify/source_clockify/streams.py
> +        self.workspaceId = workspaceId
```suggestion
        self.workspace_id = workspaceId

```

Please check Python PEP-8 recommendations for variable naming.

2022-10-11 16:36 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-clockify/source_clockify/streams.py
> +        return f"workspaces/{self.workspaceId}/users"
Please enable cache for this stream, so when reading the `TimeEntrie`won't read a second time.

2022-10-11 16:36 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-clockify/source_clockify/streams.py
> +        return f"workspaces/{self.workspaceId}/projects"
Same here: enable cache.

2022-10-12 17:41 UTC, sajarin commented
@RobLucchi Thanks for the new source connector. This PR is part of AIrbyte community maintainer program and will be reviewed by a member of the community. Please be patient as you wait for a maintainer to be assigned to this PR. 

Thanks!

2022-10-16 11:35 UTC, RobLucchi commented
@sajarin Requested Changes Applied, waiting for any further reviews.

2022-10-18 16:26 UTC, natalyjazzviolin commented
Hey @RobLucchi ! I tested your connector locally and made a few changes to make sure the integration tests pass.

Could you please check over your schemas and either:
- Remove fields that are type `null`
- OR add a second type, so null is the fallback: `["null", "string"]` for example.

Looking through the API documentation, it looks like `costRate` (one of the null fields) can either be null, a string, or an object:
https://clockify.me/developers-api

2022-10-19 12:24 UTC, RobLucchi commented
@natalyjazzviolin Could you please check the last changes.

2022-10-19 13:30 UTC, natalyjazzviolin commented
@RobLucchi testing! Please note that the task duration field needs a fallback value of `null`! And another small detail - we would really appreciate it if you used a more descriptive branch name in the future :) something like `roblucchi/source-clockify` would work great!

What a cool source, thanks for the contribution!

2022-10-19 13:31 UTC, natalyjazzviolin commented
/test connector=connectors/source-clockify

2022-10-19 16:01 UTC, natalyjazzviolin commented
/test connector=connectors/source-clockify

2022-10-19 16:50 UTC, natalyjazzviolin commented
/test connector=connectors/source-clockify

2022-10-19 22:43 UTC, marcosmarxm commented
/test connector=connectors/source-clockify

2022-10-20 13:13 UTC, natalyjazzviolin commented
/test connector=connectors/source-clockify

2022-10-20 19:22 UTC, natalyjazzviolin commented
/test connector=connectors/source-clockify

2022-10-20 19:50 UTC, marcosmarxm commented
@natalyjazzviolin before publishing please:
- [ ] add seed uuid into airbyte-config/.../source_seed file
- [ ] format files there are some EOF missing in the review
- [ ] publish :)

2022-10-21 13:41 UTC, natalyjazzviolin commented
/publish connector=connectors/source-clockify

2022-10-21 16:26 UTC, marcosmarxm approved these changes

2022-10-21 16:26 UTC, marcosmarxm requested changes

2022-10-21 16:26 UTC, marcosmarxm commented on airbyte-config/init/src/main/resources/seed/source_definitions.yaml
> +  icon: cliskhouse.svg
@natalyjazzviolin please remove this.

2022-10-21 16:27 UTC, marcosmarxm requested changes

2022-10-25 18:07 UTC, marcosmarxm commented
Dockerhub has an issue with push command. I'll wait until this is solved.

2022-10-26 11:08 UTC, marcosmarxm commented
/publish connector=connectors/source-clockify

2022-10-26 12:09 UTC, marcosmarxm approved these changes

2022-10-26 12:09 UTC, merged