workflows: Update actions/checkout to v3
airbytehq/airbyte pull request #17764
Opened 2022-10-08 10:47 UTC by Sushrut1101

2022-10-08 10:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=17764) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=17764) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=17764) it.</sub>

2022-10-08 10:54 UTC, Sushrut1101 commented
Signed!

> [![CLA assistant check](https://camo.githubusercontent.com/777a078050c6b0e4f4af5f36272b0014312f4cafeea86f96c172ea30870fb940/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f7369676e6564)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=17764) All committers have signed the CLA.

2022-10-11 11:08 UTC, marcosmarxm commented
@supertopher can you review this community contribution?

2022-10-11 11:09 UTC, marcosmarxm commented
@Sushrut1101 do you want to merge this? Can you add a complete description of what of you're trying to achieve changing action v2 to v3?

2022-10-11 11:10 UTC, marcosmarxm requested changes

2022-10-11 11:10 UTC, marcosmarxm commented on .github/workflows/commands-for-testing-tool.yml
> +       AirbyteAirbyteAirbyteAirbyteAirbyteAirbyteAirbyteAirbyteAirbyteAirbyteAirbyteAirbyteAirbyteAirbyteAirbyteAirbyteAirbyteAirbyteAirbyteAirbyteAirbyteAirbyteAirbyteAirbyteAirbyteAirbyteAirbyteAir
what is this?

2022-10-11 11:10 UTC, marcosmarxm commented on .github/workflows/commands-for-testing-tool.yml
> +      - name: Checkout AirbyteAirbyte
?

2022-10-11 13:44 UTC, supertopher commented
Agree with the above comments.  Please articulate what you want to achieve with this change.  I'm not opposed to upgrading, but without a reason this feels like a risk without a reward.  Version bumps may have unintended effects especially considering the number of places this action runs.

Thank you for the contribution.  look forward to hearing from you

2022-10-12 17:42 UTC, supertopher requested changes
marking as requested changes to clear my notification

2022-10-14 01:01 UTC, davinchia requested changes
I agree with the other comments. Marking as request changes to clear my notifications too.

2022-10-14 17:29 UTC, Sushrut1101 commented on .github/workflows/commands-for-testing-tool.yml
> +      - name: Checkout AirbyteAirbyte
Uhh, looks like sth got messed up 😬

2022-10-14 17:29 UTC, Sushrut1101 commented
Will do a force push, looks like I messed up sth 😬

2022-10-17 13:50 UTC, marcosmarxm commented
> Will do a force push, looks like I messed up sth 😬

@Sushrut1101 please check commentns from Topher and Davin.

2022-11-22 20:23 UTC, marcosmarxm commented
Hello :wave:, first thank you for this amazing contribution. 

We really appreciate the effort you've made to improve the project.
We ask you patience for the code review. Last month our team was focused on Hacktoberfest event and that probably left some PR without the proper feedback. And this week, due to the Thanksgiving US Holiday, most our team is out of office with their families. Another important piece of information why code won't be merge this week is: as a safety measure the core team has decided to freeze merging code to main branch to keep the release stable. Next week we'll return to you with the proper code review and update the status of your contribution.

If you have any questions feel free to send me a message in Slack!
Thanks!

2022-12-02 18:51 UTC, closed without merging