Source facebook-marketing: remove `pixel` from custom conversions stream
airbytehq/airbyte pull request #18045
Opened 2022-10-17 10:22 UTC by davydov-d

## What
https://github.com/airbytehq/oncall/issues/744

## How
![image](https://user-images.githubusercontent.com/7703835/196153496-3a6b7687-5479-4ddd-8cb6-dd2358f2edeb.png)
There are two options here:
 - request additional permissions
 - remove `pixel` field from stream schema
 Since I can not find any mention of what permissions this field/endpoint requires, I'm removing `pixel` field

2022-10-17 10:31 UTC, davydov-d commented
/test connector=connectors/source-facebook-marketing

2022-10-17 11:20 UTC, arsenlosenko approved these changes

2022-10-17 14:56 UTC, alafanechere requested changes
Were you able to reproduce this problem locally? Could you please add the `custom_conversions` stream to `integration-tests/configured_catalog.json`?

2022-10-17 15:07 UTC, davydov-d commented
> Were you able to reproduce this problem locally? Could you please add the `custom_conversions` stream to `integration-tests/configured_catalog.json`?

@alafanechere I will certainly add this stream to the catalog, but we wont benefit much from it since I could reproduce the issue only using customer's config

2022-10-17 17:57 UTC, davydov-d commented
/test connector=connectors/source-facebook-marketing

2022-10-17 17:59 UTC, davydov-d commented
> It looks like this error is common to all syncs with this stream. I'm wondering what I could take to make sure that source acceptance tests can also reproduce this problem.

it makes me wonder the same..

2022-10-18 09:06 UTC, alafanechere approved these changes
Thanks for the addition to the configured catalog. I think we can't reproduce because the `custom_conversions` stream is not seeded on our sandbox account...

2022-10-18 09:11 UTC, davydov-d commented
/publish connector=connectors/source-facebook-marketing

2022-10-18 10:22 UTC, merged