Source: Alt Google Ads Low Cdk
airbytehq/airbyte pull request #18091
Opened 2022-10-18 04:57 UTC by mutt-santiago-stachuk

## What
 Trying to replicate conector developed with Python SDK in `low code sdk`

## Why
 If performance is similar, it may be more easy to update connector for future contributors/collaborators

## OG Source Google Ads
 [Airbyte Gads documentation](https://docs.airbyte.com/integrations/sources/google-ads/)

## How
- Using `low code cdk`
- Relying hard in original connector, awesome community and Airbyte team ❤️ 

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

2022-10-18 11:52 UTC, marcosmarxm commented
This is ready to review @mutt-santiago-stachuk ? If not please move to draft

2022-10-21 23:56 UTC, RealChrisSean commented
https://github.com/airbytehq/connector-contest/issues/156

2022-10-24 14:01 UTC, mutt-santiago-stachuk commented
![connection checked!](https://user-images.githubusercontent.com/106173005/197544069-763a9fef-e711-4bd6-a462-95e2ca70960b.png)
Connection check was a success!

2022-10-25 18:31 UTC, marcosmarxm commented
> ![connection checked!](https://user-images.githubusercontent.com/106173005/197544069-763a9fef-e711-4bd6-a462-95e2ca70960b.png) Connection check was a success!

Great, let us know if you need any assistance also ping us in our Slack in the channel `#hacktoberfest-2022`

2022-10-27 01:59 UTC, mutt-santiago-stachuk commented
@marcosmarxm somewhat ready for being reviewed

2022-10-28 10:19 UTC, marcosmarxm commented
> @marcosmarxm somewhat ready for being reviewed

I'll take a look today!

2022-11-01 00:38 UTC, marcosmarxm commented
Sorry the delay @mutt-santiago-stachuk I'll add your connector to my priority to-do list for tomorrow!

2022-11-02 16:36 UTC, marcosmarxm requested changes
Sorry I forget to submit the review!

2022-11-04 08:54 UTC, marcosmarxm commented
Hello! I'm going to be out of the office this Friday and won't be able to review your contribution again today, I return next Monday. So far, most contributions look solid and are almost done to be approved. As said in [Chris' comment](https://airbytehq.slack.com/archives/C0450PCSDB2/p1667430678866629) all contributions made before 2-November are eligible to receive the prize and have 2 weeks to merge the contributions. But I ensure next week we're going to have your contribution merged. If you have questions about the implementation you can send them in `#hacktoberfest-2022` in Airbyte's Slack.

Sorry the inconvenience and see you again next week, thank you so much for your contribution!

2022-11-07 16:12 UTC, mutt-santiago-stachuk commented on airbyte-integrations/connectors/source-alt-google-ads/source_alt_google_ads/alt_google_ads.yaml
> +      type: NoPagination
ok! im going to do it! I didn't add it cuz google ads' searchstream doesn't use pagination as opossed to serch, but i'll check it, maybe i'm missing something

2022-11-07 17:54 UTC, marcosmarxm requested changes
@mutt-santiago-stachuk do you need assistance to solve pending issues?

2022-11-07 18:33 UTC, mutt-santiago-stachuk commented
@marcosmarxm Yeah! I was finishing some things, but I have problems with the stream_slicer  for the incremental bit!

2022-11-08 18:00 UTC, marcosmarxm commented
> 

If you remove the cursor it works? Maybe you can use transformation to move the `segments.date` to higher level. https://docs.airbyte.com/connector-development/config-based/understanding-the-yaml-file/record-selector#transformations

2022-11-11 17:01 UTC, mutt-santiago-stachuk commented
> > 
> 
> If you remove the cursor it works? Maybe you can use transformation to move the `segments.date` to higher level. https://docs.airbyte.com/connector-development/config-based/understanding-the-yaml-file/record-selector#transformations

I'm trying to apply this, but had a hard week, so maybe the monday its more likely to be some progress.
I have a doubt: To reference the field in the Transformation AddField, I should include them to Stream Slice?


Still, with the problem of the stream slicer not showing dates, do  you have any Idea of why is that happening?
my definition of the stream slicer:
'''yaml
  stream_slicer:
    type: "DatetimeStreamSlicer"
    start_datetime:
      datetime: "{{config['start_date']}}"
      datetime_format: "%Y-%m-%d" 
    end_datetime:
      datetime: "{{ config.get('end_date') or now_utc().strftime('%Y-%m-%d') }}"
      datetime_format: "%Y-%m-%d"
    step: "1d"
    datetime_format: "%Y-%m-%d"
    cursor_field: "{{options['stream_cursor_field']}}"
'''

then it's defined like this:
'''yaml
  retriever:
    record_selector:
      $ref: "*ref(definitions.selector)"
    paginator:
      type: NoPagination
    requester:
      $ref: "*ref(definitions.requester)"
    stream_slicer:
      $ref: "*ref(definitions.stream_slicer)"
'''

but when I try to template it in tue queries, it doesn't find any values, I tried something like "{{ stream_slice.start_date}}" and it's rendered as an empty string. and when I try {{stream_slice}} alone, its rendered as "{}" (an empty dir)

2022-11-17 01:45 UTC, marcosmarxm commented
@mutt-santiago-stachuk sorry the delay here, I'll review the connector tomorrow and help you to get this merge ASAP :)

2022-11-17 07:51 UTC, mutt-santiago-stachuk commented
> @mutt-santiago-stachuk sorry the delay here, I'll review the connector tomorrow and help you to get this merge ASAP :)

ty! here is the output of the test:
```
pyenv exec python -m pytest integration_tests -p integration_tests.acceptance
Test session starts (platform: linux, Python 3.10.2, pytest 6.2.5, pytest-sugar 0.9.5)
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/santiago/contributions/airbyte/airbyte-integrations/connectors/source-alt-google-ads/.hypothesis/examples')
rootdir: /home/santiago/contributions/airbyte, configfile: pytest.ini
plugins: requests-mock-1.9.3, mock-3.6.1, timeout-1.4.2, sugar-0.9.5, cov-3.0.0, hypothesis-6.54.6
collecting ... {"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}
{"type": "LOG", "log": {"level": "WARN", "message": "The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format."}}

 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_config_match_spec[inputs0] ✓3% ▍         
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_match_expected[inputs0] ✓7% ▊         
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_docker_env[inputs0] ✓10% █         
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_oneof_usage[inputs0] ✓14% █▍        
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_required[inputs0] ✓ 17% █▊        
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_optional[inputs0] ✓ 21% ██▏       
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_has_secret[inputs0] ✓24% ██▌       
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_secret_never_in_the_output[inputs0] ✓28% ██▊       
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_defined_refs_exist_in_json_spec_file[inputs0] ✓31% ███▏      
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_oauth_flow_parameters[inputs0] ✓34% ███▌      Pulling docker image airbyte/source-alt-google-ads:latest
{"type": "LOG", "log": {"level": "WARN", "message": "\n We did not find the airbyte/source-alt-google-ads:latest image for this connector. This probably means this version has not yet been published to an accessible docker registry like DockerHub."}}

 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_backward_compatibility[inputs0] s38% ███▊      
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_additional_properties_is_true[inputs0] ✓41% ████▎     

――――――――――――――――――――――――――――――――――――――――――――――――――――― TestConnection.test_check[inputs0] ―――――――――――――――――――――――――――――――――――――――――――――――――――――

self = <source_acceptance_test.tests.test_core.TestConnection object at 0x7fabaa438b50>, connector_config = SecretDict(******)
inputs = ConnectionTestConfig(config_path='secrets/config.json', status=<Status.Succeed: 'succeed'>, timeout_seconds=None)
docker_runner = <source_acceptance_test.utils.connector_runner.ConnectorRunner object at 0x7fabaa43b8b0>

    def test_check(self, connector_config, inputs: ConnectionTestConfig, docker_runner: ConnectorRunner):
        if inputs.status == ConnectionTestConfig.Status.Succeed:
>           output = docker_runner.call_check(config=connector_config [...]

2022-11-17 19:11 UTC, marcosmarxm commented
/test connector=connectors/source-alt-google-ads

2022-11-17 19:13 UTC, marcosmarxm commented
@mutt-santiago-stachuk I think Google Ads is a complex source which in the current level of low-code CDK being in Alpha it won't be able to make it work without a lot of complex custom components to make pagination and incremental syncs to work. Not sure if adding this connector will benefit users which already are using the native python-CDK Google Ads connector. What are you thoughts?

2022-11-19 01:46 UTC, mutt-santiago-stachuk commented
> @mutt-santiago-stachuk I think Google Ads is a complex source which in the current level of low-code CDK being in Alpha it won't be able to make it work without a lot of complex custom components to make pagination and incremental syncs to work. Not sure if adding this connector will benefit users which already are using the native python-CDK Google Ads connector. What are you thoughts?

@marcosmarxm It seems like you're right... Well, I've tried at least

2022-11-22 14:32 UTC, closed without merging