🎉 New Source: ActiveCampaign
airbytehq/airbyte pull request #18335
Opened 2022-10-22 18:52 UTC by dainiussa

## What
The following PR adds the new Low Code CDK-based ActiveCampaign Connector. For more context, please refer to [this issue](https://github.com/airbytehq/connector-contest/issues/167).

## How
This PR uses the Low Code CDK to create a ActiveCampaign connector with the following streams:

* campaigns
* contacts
* lists
* deals
* segments
* forms

## Recommended reading order
1. `spec.yaml`
2. `activecampaign.yaml`
3. schemas

## 🚨 User Impact 🚨
No changes to existing code.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

## Tests

<details><summary><strong>Acceptance</strong></summary>

![image](https://user-images.githubusercontent.com/24483275/197357445-f957da25-67db-47bb-81c6-bd1f55bbdc04.png)

</details>

2022-10-22 18:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=18335) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=18335) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: rytismi<br/>:x: Dainius Salkauskas<br/><hr/>**Dainius Salkauskas** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=18335) it.</sub>

2022-10-24 20:36 UTC, marcosmarxm requested changes
A few comments but the implementation looks great! Thanks for the contribution.

2022-10-24 20:36 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-activecampaign/source_activecampaign/schemas/TODO.md
> +# TODO: Define your stream schemas
Remove this file.

2022-10-24 21:21 UTC, dainiussa commented on airbyte-integrations/connectors/source-activecampaign/integration_tests/catalog.json
> +        "$schema": "http://json-schema.org/draft-07/schema#",
Removed

2022-10-24 21:21 UTC, dainiussa commented on airbyte-integrations/connectors/source-activecampaign/source_activecampaign/schemas/TODO.md
> +# TODO: Define your stream schemas
Removed

2022-10-24 21:21 UTC, dainiussa commented on airbyte-integrations/connectors/source-activecampaign/test.py
> +    print(set(json_2.keys()).difference(json_1.keys()))
Removed

2022-10-24 21:21 UTC, dainiussa commented on docs/integrations/sources/activecampaign.md
> +* ActiveCampaign API Key
Added the changelog

2022-10-26 00:21 UTC, marcosmarxm requested changes
A few comments and it is almost ready to go! :)
Ask my review again when all comments are resolved.

2022-10-26 00:21 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-activecampaign/source_activecampaign/activecampaign.yaml
> +      path: "/api/3/campaigns"
@dainiussa why not move `/api/3/` to base url?

2022-10-26 00:21 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-activecampaign/integration_tests/sample_config.json
> +}
Please fix this file and give one example (remove secrets of course)

2022-10-27 16:29 UTC, marcosmarxm approved these changes
congrats @dainiussa I'll publish and merge later.

2022-10-27 16:55 UTC, marcosmarxm approved these changes

2022-10-27 16:56 UTC, marcosmarxm commented
/publish connector=connectors/source-activecampaign

2022-10-27 17:15 UTC, merged