New source - Mailjet SMS
airbytehq/airbyte pull request #18345
Opened 2022-10-23 20:47 UTC by haithem-souala

## What
https://dev.mailjet.com/sms

## How
New source connector for Mailjet SMS API

## Streams
1. SMS

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

2022-10-23 22:03 UTC, haithem-souala commented
![Capture d’écran 2022-10-24 à 00 02 57](https://user-images.githubusercontent.com/75131226/197420307-de3535fd-a5ed-4093-80f0-5c80a9950755.png)

2022-10-24 23:16 UTC, marcosmarxm commented
Thanks for the contribution! Someone will review it during this week. If you have any questions please create comments so the reviewer can focus on those points.

2022-10-25 11:55 UTC, marcosmarxm requested changes
Some comments! But looks great.

2022-10-25 11:55 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-mailjet-sms/integration_tests/catalog.json
> +        "properties": {
Remove this file.

2022-10-25 11:55 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-mailjet-sms/source_mailjet_sms/mailjet_sms.yaml
> +      page_size: 10
The limit is 100. Please use always the limit when possible. 
https://dev.mailjet.com/sms/guides/filtering-resources/#the-limit-filter

2022-10-25 11:55 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-mailjet-sms/source_mailjet_sms/mailjet_sms.yaml
> +      field_name: "offset"
The name is correct? Is it not `Offset`?

2022-10-25 11:55 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-mailjet-sms/source_mailjet_sms/spec.yaml
> +      airbyte_secret: true
The API allows you to use start date and end date, are you planning to add those parameters?

2022-10-25 12:48 UTC, haithem-souala commented
![Capture d’écran 2022-10-25 à 14 47 57](https://user-images.githubusercontent.com/75131226/197777132-5ba08cf0-0894-46d5-8f0b-b319f65f7fb8.png)

2022-10-26 00:26 UTC, marcosmarxm requested changes
Almost ready! A few comments. Ask my review again after comments are solved.

2022-10-26 00:26 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-mailjet-sms/integration_tests/sample_config.json
> +}
Please fix this file.

2022-10-26 00:26 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-mailjet-sms/source_mailjet_sms/spec.yaml
> +      airbyte_secret: true
```suggestion
    token:
      title: Access Token
      type: string
      description: >- 
        Your access token. See <a
        href="https://dev.mailjet.com/sms/reference/overview/authentication">here</a>.
      airbyte_secret: true
```
Please add title to all parameters.

2022-10-26 00:26 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-mailjet-sms/source_mailjet_sms/spec.yaml
> +documentationUrl: https://dev.mailjet.com/sms
update this to direct to Airbyte Source connector url

2022-10-26 00:26 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-mailjet-sms/source_mailjet_sms/spec.yaml
> +        - 1666261656
Can you add regex pattern to make sure people add the correct input?

2022-10-27 00:02 UTC, marcosmarxm approved these changes
I'll publish this tomorrow! Congrats @haithem-souala !

2022-10-28 22:13 UTC, marcosmarxm approved these changes

2022-10-28 22:14 UTC, merged