🎉 New Source: Zapier Supported Storage
airbytehq/airbyte pull request #18442
Opened 2022-10-25 19:24 UTC by albert-marrero

## What
Adding a Source Connector for Zapier

See issue here: https://github.com/airbytehq/connector-contest/issues/11

## How
Using the Storage by Zapier. 

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
No breaking change

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

2022-10-25 19:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=18442) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=18442) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=18442) it.</sub>

2022-10-25 21:36 UTC, albert-marrero commented
![test](https://user-images.githubusercontent.com/7494358/197886697-268eaeae-e6db-4b03-85bd-0c393a6dc069.png)

2022-10-26 19:05 UTC, marcosmarxm requested changes
A few comments.

2022-10-26 19:05 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-zapier-supported-storage/source_zapier_supported_storage/schemas/TODO.md
> +From the `zapier_supported_storage.yaml` configuration file, you read the `.json` files in the `schemas/` directory. You can refer to a schema in your configuration file using the `schema_loader` com
Remove this file.

2022-10-26 19:05 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-zapier-supported-storage/integration_tests/catalog.json
> +          },
Remove this file.

2022-10-26 19:05 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-zapier-supported-storage/source_zapier_supported_storage/spec.yaml
> +      type: string
add title to your property.

2022-10-26 19:05 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-zapier-supported-storage/source_zapier_supported_storage/spec.yaml
> +documentationUrl: https://docsurl.com
update the doc to `https://docs.airbyte.com/integrations/sources/zapier-supported-storage`

2022-10-26 19:05 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-zapier-supported-storage/source_zapier_supported_storage/zapier_supported_storage.yaml
> +#      api_token: "{{ config['api_key'] }}"
what that?

2022-10-26 19:05 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-zapier-supported-storage/source_zapier_supported_storage/zapier_supported_storage.yaml
> +      path: "/api/records"
please move the preview `/api` to the base_url

2022-10-26 19:05 UTC, marcosmarxm commented on docs/integrations/sources/zapier-supported-storage.md
> +| 0.1.0   | 2022-10-25 |  | Initial release for Zapier Supported Storage|
Add the Pr number.

2022-10-29 00:40 UTC, albert-marrero commented on airbyte-integrations/connectors/source-zapier-supported-storage/source_zapier_supported_storage/schemas/TODO.md
> +From the `zapier_supported_storage.yaml` configuration file, you read the `.json` files in the `schemas/` directory. You can refer to a schema in your configuration file using the `schema_loader` com
Done.

2022-10-29 00:53 UTC, albert-marrero commented
@marcosmarxm sorry for the delay, it was pretty crazy with work and getting a home ready for a baby. I hope I did everything correctly.

2022-10-31 23:02 UTC, marcosmarxm requested changes
Some comments @albert-marrero

2022-10-31 23:02 UTC, marcosmarxm commented on docs/integrations/README.md
> +| [Zapier Supported Storage](sources/zapier-supported-storage.md)                             | Beta                 | Yes                 |
```suggestion
| [Zapier Supported Storage](sources/zapier-supported-storage.md)                             | Alpha                 | No                 |
```

2022-10-31 23:02 UTC, marcosmarxm commented on docs/integrations/sources/zapier-supported-storage.md
> +# Typeform
Please update the documentation it is using the other connector, Typeform.

2022-10-31 23:02 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-zapier-supported-storage/integration_tests/sample_config.json
> +}
Please correct this file.

2022-10-31 23:02 UTC, marcosmarxm commented
@albert-marrero can you share the integration test results besides the read command?

2022-11-01 15:43 UTC, albert-marrero commented
@GreeneWoods , can you share the integration test results besides the read command?

2022-11-01 19:58 UTC, GreeneWoods commented
updated pending issues in md and configs.

all tests are being passed
![image](https://user-images.githubusercontent.com/35355162/199326684-a83f1e12-670f-4bb5-902c-00d99617a146.png)

2022-11-02 20:06 UTC, marcosmarxm requested changes
There are some requests not solved yet.

2022-11-02 20:06 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-zapier-supported-storage/source_zapier_supported_storage/schemas/TODO.md
> +```
Please remove this file...

2022-11-02 20:06 UTC, marcosmarxm commented on docs/integrations/sources/zapier-supported-storage.md
> +* Click Generate token.
Please update this document correctly.

2022-11-02 22:02 UTC, albert-marrero commented
@marcosmarxm sorry about that, my partner and I thought we did everything correctly.  Hopefully it is done correctly now.

2022-11-04 08:54 UTC, marcosmarxm commented
Hello! I'm going to be out of the office this Friday and won't be able to review your contribution again today, I return next Monday. So far, most contributions look solid and are almost done to be approved. As said in [Chris' comment](https://airbytehq.slack.com/archives/C0450PCSDB2/p1667430678866629) all contributions made before 2-November are eligible to receive the prize and have 2 weeks to merge the contributions. But I ensure next week we're going to have your contribution merged. If you have questions about the implementation you can send them in `#hacktoberfest-2022` in Airbyte's Slack.

Sorry the inconvenience and see you again next week, thank you so much for your contribution!

2022-11-07 20:56 UTC, marcosmarxm commented
/test connector=connectors/source-zapier-supported-storage

2022-11-07 21:25 UTC, marcosmarxm approved these changes

2022-11-07 21:31 UTC, marcosmarxm commented
/publish connector=connectors/source-zapier-supported-storage

2022-11-07 22:02 UTC, marcosmarxm approved these changes

2022-11-07 22:02 UTC, merged

2022-11-18 17:13 UTC, RealChrisSean commented
Hello @albert-marrero! Congrats on having this merged. Can you please provide an email for us to contact you about payouts?

2022-11-22 14:48 UTC, albert-marrero commented
Hello @RealChrisSean what is the best way to give you that info?