🎉 New Source: Visma e-conomic
airbytehq/airbyte pull request #18595
Opened 2022-10-28 08:23 UTC by sofiehellmark

## What
Adding Visma e-conomic as a source. 

## How
Using python cdk

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

2022-10-28 08:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=18595) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=18595) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=18595) it.</sub>

2022-10-28 10:49 UTC, marcosmarxm commented
Thanks for your contribution @sofiehellmark ! Please request my review when the code is ready to review. If you have any questions feel free to ask them in our Slack channel #hacktoberfest-2022. You can get a link to access Slack here: https://airbyte.com/connector-contest

2022-10-28 10:50 UTC, marcosmarxm commented
@sofiehellmark can you sign the CLA?

2022-10-30 16:23 UTC, sofiehellmark commented
Hi! Ready for review on my first PR here 😄 I have updated the documentation now, let me know if I missed something. About the tests - could you please guide me if there is more I need to implement/provide?

2022-10-31 11:26 UTC, marcosmarxm requested changes
Hello @sofiehellmark, Marcos from Airbyte here 👋 . We received more than 25 new contributions along the weekend. One is yours 🎉  thank so much for! Our team is limited and maybe the review process can take longer than expected. As described in the Airbyte's Hacktoberfest your contribution was submitted before November 2nd and it is eligible to win the prize. The review process will validate other requirements. I ask to you patience until someone from the team review it. 

Because I reviewed some contributions for Hacktoberfest so far I saw some common patterns you can check in advance:
* [ ] Make sure you have added connector documentation to `/docs/integrations/`
* [ ] Remove the file `catalog` from `/integration_tests`
* [ ] Edit the `sample_config.json` inside `/integration_tests`
* [ ] For the `configured_catalog` you can use only `json_schema: {}`
* [ ] Add title to all properties in the `spec.yaml`
* [ ] Make sure the `documentationUrl` in the `spec.yaml` redirect to Airbyte's future connector page, eg: connector Airtable the `documentationUrl: https://docs.airbyte.com/integrations/sources/airtable`
* [ ] Review now new line at EOF (end-of-file) for all files.

If possible send to me a DM in Slack with the tests credentials, this process will make easier to us run integration tests and publish your connector. If you only has production keys, make sure to create a bootstrap.md explaining how to get the keys.

2022-10-31 20:24 UTC, marcosmarxm requested changes
Some comments.

2022-10-31 20:24 UTC, marcosmarxm commented on airbyte-integrations/builds.md
> -| 3PL Central  | [![source-amazon-seller-partner](https://img.shields.io/endpoint?url=https%3A%2F%2Fdnsgjos7lj2fu.cloudfront.net%2Ftests%2Fsummary%2Fsource-tplcentral%2Fbadge.json)](https://dnsgjos7l
Can you check this file change?

2022-10-31 20:24 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-visma-economic/integration_tests/catalog.json
> +        "type": "object",
Remove this file.

2022-10-31 20:24 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-visma-economic/integration_tests/sample_config.json
> +  "fix-me": "TODO"
Please update this file.

2022-10-31 20:24 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-visma-economic/requirements.txt
> +-e .
```
# This file is autogenerated -- only edit if you know what you are doing. Use setup.py for declaring dependencies.
-e ../../bases/source-acceptance-test
-e .
```

2022-10-31 20:24 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-visma-economic/source_visma_economic/sample_files/demo_config.json
> +}
Replace this with `sample_config.json`

2022-10-31 20:24 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-visma-economic/source_visma_economic/schemas/accounts.json
> +      "enum": ["profitAndLoss", "status", "totalFrom", "heading", "headingStart", "sumInterval", "sumAlpha"],
you must specify the type: string

2022-10-31 20:24 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-visma-economic/source_visma_economic/schemas/accounts.json
> +      "enum": ["profitAndLoss", "status", "totalFrom", "heading", "headingStart", "sumInterval", "sumAlpha"],
check all enums.

2022-10-31 20:24 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-visma-economic/source_visma_economic/source.py
> +                return query_params
```suggestion
        if 'nextPage' in response_json.get('pagination').keys():
            parsed_url = urlparse(response_json['pagination']['nextPage'])
            query_params = parse_qs(parsed_url.query)
             return query_params
```

2022-10-31 20:24 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-visma-economic/source_visma_economic/source.py
> +                return query_params
You can simplify the code. Please add one unit test to make sure this is working.

2022-10-31 20:24 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-visma-economic/source_visma_economic/spec.yaml
> +documentationUrl: https://apis.e-conomic.com/
This is the Airbyte's connector page: `https://docs.airbyte.com/integrations/sources/visma-economic`

2022-10-31 20:24 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-visma-economic/source_visma_economic/spec.yaml
> +      type: string
add title to all parameters.

2022-10-31 20:24 UTC, marcosmarxm commented on docs/integrations/README.md
> +| [Visma e-conomic](sources/visma-economic.md)                                                | Alpha                | Yes                 |
```suggestion
| [Visma e-conomic](sources/visma-economic.md)                                                | Alpha                | No                 |
```

2022-11-01 18:50 UTC, sofiehellmark commented
Hi @marcosmarxm, I have pushed requested changes. Thanks!

2022-11-01 22:55 UTC, marcosmarxm requested changes
@sofiehellmark I read the Visma documentation (https://restdocs.e-conomic.com/#filtering) and found the API allows filtering. This allows to implement incremental syncs, which is much better to use the connector. What do you think about implementing this? I can help you whenever you need

2022-11-03 07:56 UTC, sofiehellmark commented
Sounds good! I'll have a go at it, will let you know if any questions

2022-11-04 08:52 UTC, marcosmarxm commented
Hello! I'm going to be out of the office this Friday and won't be able to review your contribution again today, I return next Monday. So far, most contributions look solid and are almost done to be approved. As said in [Chris' comment](https://airbytehq.slack.com/archives/C0450PCSDB2/p1667430678866629) all contributions made before 2-November are eligible to receive the prize and have 2 weeks to merge the contributions. But I ensure next week we're going to have your contribution merged. If you have questions about the implementation you can send them in `#hacktoberfest-2022` in Airbyte's Slack.

Sorry the inconvenience and see you again next week, thank you so much for your contribution!

2022-11-07 22:19 UTC, marcosmarxm commented
/test connector=connectors/source-visma-economic

2022-11-07 22:23 UTC, marcosmarxm commented
/test connector=connectors/source-visma-economic

2022-11-07 22:59 UTC, marcosmarxm commented
/publish connector=connectors/source-visma-economic

2022-11-07 23:44 UTC, marcosmarxm approved these changes
Thanks @sofiehellmark

2022-11-07 23:44 UTC, merged