Add new source Pagar.me
airbytehq/airbyte pull request #18622
Opened 2022-10-28 19:15 UTC by sarafonseca-123

## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

2022-10-31 17:50 UTC, sajarin commented
Hello @sarafonseca-123 Saj from Airbyte here 👋 . We received more than 25 new contributions along the weekend. One of which is yours 🎉  thank you so much! Our team is limited and the review process may take longer than expected. As described in the Airbyte's Hacktoberfest your contribution was submitted before November 2nd and it is eligible to win the prize. The review process will validate other requirements. I ask to you patience until someone from the team review it. 

Because we reviewed some contributions for Hacktoberfest so far we've seen some common errors/patterns you can double check in advance:
* [ ] Make sure you have added connector documentation to `/docs/integrations/`
* [ ] Remove the file `catalog` from `/integration_tests`
* [ ] Edit the `sample_config.json` inside `/integration_tests`
* [ ] For the `configured_catalog` you can use only `json_schema: {}`
* [ ] Add title to all properties in the `spec.yaml`
* [ ] Make sure the `documentationUrl` in the `spec.yaml` redirect to Airbyte's future connector page, eg: connector Airtable the `documentationUrl: https://docs.airbyte.com/integrations/sources/airtable`
* [ ] Review now new line at EOF (end-of-file) for all files.

If possible send to me a DM in Slack with the tests credentials, this process will make easier to us run integration tests and publish your connector. If you only has production keys, make sure to create a bootstrap.md explaining how to get the keys.

2022-10-31 20:32 UTC, marcosmarxm requested changes
@sarafonseca-123 some comments, do you have a test account? Also check Saj's comment.

2022-10-31 20:32 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-pagarme/source_pagarme/streams.py
> +        return body
Does it make sense this code block? the start date is a required parameter and else never will be executed.

2022-11-01 01:11 UTC, mmolimar commented
Hey @sajarin 
I'll be taking a look at this PR

2022-11-02 02:35 UTC, sarafonseca-123 commented
My company is still analyzing if it's ok to share the test key, so I won't be able to provide it for now. But I addressed all comments, and here are the test results after the code change 😄 : 

Unit:

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/56175551/199381136-c99788f0-914c-4ec5-8256-dbe11b0f76a0.png">


Acceptance:

<img width="146" alt="image" src="https://user-images.githubusercontent.com/56175551/199380966-92d4306a-11f4-44fb-a93e-f09e7d7532a5.png">


<details> <summary>Integration</summary> 

Building all of Airbyte.
/Users/sarasantos/git-jusbrasil/airbyte/airbyte-integrations/connectors
Type-safe dependency accessors is an incubating feature.

> Configure project :
configuring docker task for airbyte-bootloader
configuring docker task for airbyte-container-orchestrator
configuring docker task for airbyte-cron
configuring docker task for airbyte-proxy
configuring docker task for airbyte-server
configuring docker task for airbyte-temporal
configuring docker task for airbyte-webapp
configuring docker task for airbyte-workers
configuring docker task for init
configuring docker task for db-lib
configuring docker task for reporter

> Task :airbyte-integrations:bases:source-acceptance-test:checkPython
Using python 3.10.8 from /Users/sarasantos/git-jusbrasil/airbyte/airbyte-integrations/bases/source-acceptance-test/.venv (.venv/bin/python)
Using pip 21.3.1 from /Users/sarasantos/git-jusbrasil/airbyte/airbyte-integrations/bases/source-acceptance-test/.venv/lib/python3.10/site-packages/pip (python 3.10)

> Task :airbyte-integrations:bases:base-normalization:checkPython
Using python 3.10.8 from /Users/sarasantos/git-jusbrasil/airbyte/airbyte-integrations/bases/base-normalization/.venv (.venv/bin/python)
Using pip 21.3.1 from /Users/sarasantos/git-jusbrasil/airbyte/airbyte-integrations/bases/base-normalization/.venv/lib/python3.10/site-packages/pip (python 3.10)

> Task :airbyte-integrations:connectors:source-pagarme:checkPython
Using python 3.10.8 from /Users/sarasantos/git-jusbrasil/airbyte/airbyte-integrations/connectors/source-pagarme/.venv (.venv/bin/python)
Using pip 21.3.1 from /Users/sarasantos/git-jusbrasil/airbyte/airbyte-integrations/connectors/source-pagarme/.venv/lib/python3.10/site-packages/pip (python 3.10)

> Task :airbyte-integrations:bases:source-acceptance-test:pipInstall
[python] .venv/bin/python -m pip install pip==21.3.1
         Requirement already satisfied: pip==21.3.1 in ./.venv/lib/python3.10/site-packages (21.3.1)
         WARNING: You are using pip version 21.3.1; however, version 22.3 is available.
         You should consider upgrading via the '/Users/sarasantos/git-jusbrasil/airbyte/airbyte-integrations/bases/source-acceptance-test/.venv/bin/python -m pip install --upgrade pip' command.
[python] .venv/bin/python -m pip list --format=columns
         Package                     Version   Editable project location
         --------------------------- --------- ---------------------------------------------------------------------------------------------------
         airbyte-cdk                 0.4.2
         appdirs                     1.4.4
         attrs                       22.1.0
         backoff                     2.2.1
         black                       22.3.0
         cattrs                      22.2.0
         certifi                     2022.9.24
         charset-normalizer          2.1.1
         click                       8.1.3
         coverage                    6.3.1
         dataclasses-jsonschema      2.15.1
         deepdiff                    5.8.1
         Deprecated                  1.2.13
         docker                      5.0.3
         dpath                       2.0.6
         exceptiongroup              1.0.0rc9
         fancycompleter              0.9.1
         flake8                      4.0.1
         hypothesis                  6.54.6
         hypothesis-jsonschema       0.20.1
         icdiff                      1.9.1
         idna                        3.4
         inflection                  0.5.1
         iniconfig                   1.1.1
         isort                       5.6.4
         Jinja2                      3.1.2
         jsonref                     0.2
         jsonschema                  3.2.0
         MarkupSafe                  2.1.1
         mccabe                      0.6.1
         multidict                   6.0.2
         mypy                        0.930
         mypy-extensions             0.4.3
         ordered-set                 4.1.0
         packaging                   21.3
         pathspec                    0.10.1
         pdbpp                       0.10.3
         pendulum                    2.1.2
         pip                         21.3.1
         platformdirs                2.5.2
         pluggy                      0.13.1
         pprintpp                    0.4.0
         py                          1.11.0
         pycodestyle                 2.8.0
         pydantic                    1.9.2
         pyflakes                    2.4.0
         Pygments                    2.13.0
         pyparsing                   3.0.9
         pyproject-flake8            0.0.1a2
         pyrepl                      0.9.0
         pyrsistent                  0.18.1
         pytest                      6.1.2
         pytest-cov                  3.0.0
         pytest-mock                 3.6.1
         pytest-sugar                0.9.5
         pytest-timeout              1.4.2
         python-dateutil             2.8.2
         pytzdata                    2020.1
         PyYAML                      5.4.1
         requests                    2.28.1
         requests-cache              0.9.6
         requests-mock               1.9.3
         responses                   0.13.4
         setuptools                  63.4.3
         six                         1.16.0
         sortedcontainers            2.4.0
         source-acceptance-test      0.0.0
         source-rd-station           0.0.0
         source-rd-station-marketing 0.0.0     /Users/sarasantos/git-jusbrasil/airbyte/airbyte-integrations/connectors/source-rd-station-marketing
         termcolor                   2.0.1
         toml                        0.10.2
         tomli                       2.0.1
         typing_extensions           4.4.0
         url-normalize               1.4.3
         urllib3                     1.26.12
         vcrpy                       4.2.1
         websocket-client            1.4.1
         wmctrl                      0.4
         wrapt                       1.14.1
         yarl                        1.8.1
         WARNING: You are using pip version 21.3.1; however, version 22.3 is available.
         You should consider upgrading via the '/Users/sarasantos/git-jusbrasil/airbyte/airbyte-integrations/bases/source-acceptance-test/.venv/bin/python -m pip install --upgrade pip' command.

> Task :airbyte-integrations:bases:base-normalization:pipInstall
[python] .venv/bin/python -m pip install pip==21.3.1
         Requirement already satisfied: pip==21.3.1 in ./.venv/lib/python3.10/site-packages (21.3.1)
         WARNING: You are using pip version 21.3.1; however, version 22.3 is available.
         You should consider upgrading via the '/Users/sarasantos/git-jusbrasil/airbyte/airbyte-integrations/bases/base-normalization/.venv/bin/python -m pip install --upgrade pip' command.
[python] .venv/bin/python -m pip list --format=columns
         Package                     Version   Editable project location
         --------------------------- --------- ---------------------------------------------------------------------------------------------------
         airbyte-cdk                 0.2.3
         appdirs                     1.4.4
         attrs                       22.1.0
         backoff                     2.2.1
         black                       22.3.0
         cattrs                      22.2.0
         certifi                     2022.9 [...]

2022-11-03 03:28 UTC, mmolimar commented on airbyte-integrations/connectors/source-pagarme/README.md
> +#### Minimum Python version required `= 3.9.0`
Should this version required be `>=`?

2022-11-03 03:33 UTC, mmolimar commented on airbyte-integrations/connectors/source-pagarme/source_pagarme/spec.json
> +{
Could this be changed to a `spec.yaml` file instead of a JSON file?

2022-11-03 03:40 UTC, mmolimar commented on airbyte-integrations/connectors/source-pagarme/source_pagarme/streams.py
> +        return "bank_Accounts"
Should this be `bank_accounts` instead?

2022-11-03 03:41 UTC, mmolimar commented on airbyte-integrations/connectors/source-pagarme/source_pagarme/schemas/balance.json
> +                "null",
Primary key fields shouldn't be `null` (this applies for all entities)

2022-11-03 03:58 UTC, mmolimar commented on airbyte-integrations/connectors/source-pagarme/source_pagarme/streams.py
> +    page_size_limit = 1000
What do you think about adding a new config property to configure this `page_size_limit`?

2022-11-03 04:00 UTC, mmolimar commented on airbyte-integrations/connectors/source-pagarme/source_pagarme/streams.py
> +    url_base = "https://api.pagar.me/1/"
Out of curiosity, why using version `1` which looks a bit old?

2022-11-03 04:09 UTC, mmolimar requested changes
Left some comments.

Btw, did you run ` ./gradlew format`?

2022-11-03 04:11 UTC, mmolimar commented on airbyte-integrations/connectors/source-pagarme/bootstrap.md
> +Authentication is done through an `api_key`, that can be found in the Dashboard. For more informations, consult the [documentation](https://docs.pagar.me/v1/reference/principios-basicos#autentica%C3%
typo in `informations`

2022-11-14 13:51 UTC, marcosmarxm commented
@sarafonseca-123 are you still working on this>

2022-11-14 14:52 UTC, sarafonseca-123 commented
@marcosmarxm I got an access key for the latest Pagar.me API version, now I will update this code to use the V5 instead of V1

2022-11-18 16:28 UTC, marcosmarxm commented
Because this contribution didn't receive recent updates it won't be consider valid to hacktoberfest event. You can continue the work to get this merge in your own pace. Thank so much for your contribution!

2022-11-22 20:24 UTC, marcosmarxm commented
Hello :wave:, first thank you for this amazing contribution. 

We really appreciate the effort you've made to improve the project.
We ask you patience for the code review. Last month our team was focused on Hacktoberfest event and that probably left some PR without the proper feedback. And this week, due to the Thanksgiving US Holiday, most our team is out of office with their families. Another important piece of information why code won't be merge this week is: as a safety measure the core team has decided to freeze merging code to main branch to keep the release stable. Next week we'll return to you with the proper code review and update the status of your contribution.

If you have any questions feel free to send me a message in Slack!
Thanks!

2022-12-02 18:58 UTC, marcosmarxm commented
@sarafonseca-123 are you going to continue the work here?

2022-12-15 17:20 UTC, marcosmarxm commented
Close due inactivity.

2022-12-15 17:20 UTC, closed without merging

2022-12-26 15:47 UTC, guillaume-chech commented
I'm also interested in being able to sync Pagar data with airbyte . Is this connector not being developed as we speak ? 
Should I start over from scratch uising low code template or should I start from where you left off @sarafonseca-123 ?

2022-12-30 17:22 UTC, sarafonseca-123 commented
@guillaume-chech, the connector was made using an old version of the API. If you have a key for the newest version I advise you to begin from scratch, since the entities change a lot from v5 to v1. I can gladly help you to conclude this connector if you want to!