🎉 New Source: SAP
airbytehq/airbyte pull request #18656
Opened 2022-10-30 07:56 UTC by Sid-Lais

## What
Added source connector for SAP. [Issue](https://github.com/airbytehq/connector-contest/issues/6)

## How
Using `low code cdk`

## Recommended reading order
1. `docs/integrations/sources/sap-fieldglass.md`
2. `spec.yaml`
3. `sap.yaml`

## 🚨 User Impact 🚨
No change to base code

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

2022-10-30 07:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=18656) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=18656) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=18656) it.</sub>

2022-10-31 04:22 UTC, Sid-Lais commented
Tested the connector using sandbox url and works. Do I need to shift to production url ? Production needs login details.

2022-10-31 11:16 UTC, marcosmarxm requested changes
Hello @Sid-Lais, Marcos from Airbyte here 👋 . We received more than 25 new contributions along the weekend. One is yours 🎉  thank so much for! Our team is limited and maybe the review process can take longer than expected. As described in the Airbyte's Hacktoberfest your contribution was submitted before November 2nd and it is eligible to win the prize. The review process will validate other requirements. I ask to you patience until someone from the team review it. 

Because I reviewed some contributions for Hacktoberfest so far I saw some common patterns you can check in advance:
* [ ] Make sure you have added connector documentation to `/docs/integrations/`
* [ ] Remove the file `catalog` from `/integration_tests`
* [ ] Edit the `sample_config.json` inside `/integration_tests`
* [ ] For the `configured_catalog` you can use only `json_schema: {}`
* [ ] Add title to all properties in the `spec.yaml`
* [ ] Make sure the `documentationUrl` in the `spec.yaml` redirect to Airbyte's future connector page, eg: connector Airtable the `documentationUrl: https://docs.airbyte.com/integrations/sources/airtable`
* [ ] Review now new line at EOF (end-of-file) for all files.

If possible send to me a DM in Slack with the tests credentials, this process will make easier to us run integration tests and publish your connector. If you only has production keys, make sure to create a bootstrap.md explaining how to get the keys.

2022-10-31 11:16 UTC, marcosmarxm commented
> Tested the connector using sandbox url and works. Do I need to shift to production url ? Production needs login details.

It isn't necessary to use productions keys.

2022-10-31 19:39 UTC, Sid-Lais commented
> > Tested the connector using sandbox url and works. Do I need to shift to production url ? Production needs login details.
> 
> It isn't necessary to use productions keys.

So, I've tested using sandbox url and it works. Testing gives 2 errors for now. Can't test production as it needs login details I guess. Gives connection error.

`―――――――――――――――――――――――――――――――――――――――― TestDiscovery.test_primary_keys_exist_in_schema[inputs0] ―――――――――――――――――――――――――――――――――――――――――

self = <source_acceptance_test.tests.test_core.TestDiscovery object at 0x7fed07ed4490>
discovered_catalog = {'data': AirbyteStream(name='data', json_schema={'Data': {'type': 'array', 'items': {'type': 'object', 'properties': {...source_defined_cursor=None, default_cursor_field=None, source_defined_primary_key=[['Job Seeker ID']], namespace=None)}

    def test_primary_keys_exist_in_schema(self, discovered_catalog: Mapping[str, Any]):
        """Check that all primary keys are present in catalog."""
        for stream_name, stream in discovered_catalog.items():
            for pk in stream.source_defined_primary_key or []:
                schema = stream.json_schema
                pk_path = "/properties/".join(pk)
>               pk_field_location = dpath.util.search(schema["properties"], pk_path)
E               KeyError: 'properties'

../../bases/source-acceptance-test/source_acceptance_test/tests/test_core.py:288: KeyError`

`―――――――――――――――――――――――――――――――――――――――――――――――――――― TestBasicRead.test_read[inputs0] ―――――――――――――――――――――――――――――――――――――――――――――――――――――

self = <source_acceptance_test.tests.test_core.TestBasicRead object at 0x7fed07c3f1f0>, connector_config = SecretDict(******)
configured_catalog = ConfiguredAirbyteCatalog(streams=[ConfiguredAirbyteStream(stream=AirbyteStream(name='data', json_schema={'Data': {'typ...l_refresh'>, cursor_field=None, destination_sync_mode=<DestinationSyncMode.overwrite: 'overwrite'>, primary_key=None)])
inputs = BasicReadTestConfig(config_path='secrets/config.json', configured_catalog_path='integration_tests/configured_catalog.j...rds=None, validate_schema=True, validate_data_points=False, expect_trace_message_on_failure=True, timeout_seconds=None)
expected_records_by_stream = {}, docker_runner = <source_acceptance_test.utils.connector_runner.ConnectorRunner object at 0x7fed07c3ff70>
detailed_logger = <Logger detailed_logger acceptance_tests_logs/test_core.py__TestBasicRead__test_read[inputs0].txt (DEBUG)>

    def test_read(
        self,
        connector_config,
        configured_catalog,
        inputs: BasicReadTestConfig,
        expected_records_by_stream: MutableMapping[str, List[MutableMapping]],
        docker_runner: ConnectorRunner,
        detailed_logger,
    ):
        output = docker_runner.call_read(connector_config, configured_catalog)
        records = [message.record for message in filter_output(output, Type.RECORD)]
    
        assert records, "At least one record should be read using provided catalog"
    
        if inputs.validate_schema:
            self._validate_schema(records=records, configured_catalog=configured_catalog)
    
        self._validate_empty_streams(records=records, configured_catalog=configured_catalog, allowed_empty_streams=inputs.empty_streams)
        for pks, record in primary_keys_for_records(streams=configured_catalog.streams, records=records):
            for pk_path, pk_value in pks.items():
>               assert (
                    pk_value is not None
                ), f"Primary key subkeys {repr(pk_path)} have null values or not present in {record.stream} stream records."
E               AssertionError: Primary key subkeys ('Job Seeker ID',) have null values or not present in data stream records.
E               assert None is not None

../../bases/source-acceptance-test/source_acceptance_test/tests/test_core.py:485: AssertionError`


Second error says Primary key is null. I've used the right primary key given in documentation. The sandbox url does give some null primary keys.

2022-11-01 23:12 UTC, marcosmarxm commented
> > > Tested the connector using sandbox url and works. Do I need to shift to production url ? Production needs login details.
> > 
> > 
> > It isn't necessary to use productions keys.
> 
> So, I've tested using sandbox url and it works. Testing gives 2 errors for now. Can't test production as it needs login details I guess. Gives connection error.
> 
> ```
> ―――――――――――――――――――――――――――――――――――――――― TestDiscovery.test_primary_keys_exist_in_schema[inputs0] ―――――――――――――――――――――――――――――――――――――――――
> 
> self = <source_acceptance_test.tests.test_core.TestDiscovery object at 0x7fed07ed4490>
> discovered_catalog = {'data': AirbyteStream(name='data', json_schema={'Data': {'type': 'array', 'items': {'type': 'object', 'properties': {...source_defined_cursor=None, default_cursor_field=None, source_defined_primary_key=[['Job Seeker ID']], namespace=None)}
> 
>     def test_primary_keys_exist_in_schema(self, discovered_catalog: Mapping[str, Any]):
>         """Check that all primary keys are present in catalog."""
>         for stream_name, stream in discovered_catalog.items():
>             for pk in stream.source_defined_primary_key or []:
>                 schema = stream.json_schema
>                 pk_path = "/properties/".join(pk)
> >               pk_field_location = dpath.util.search(schema["properties"], pk_path)
> E               KeyError: 'properties'
> 
> ../../bases/source-acceptance-test/source_acceptance_test/tests/test_core.py:288: KeyError
> ```
> 
> ```
> ―――――――――――――――――――――――――――――――――――――――――――――――――――― TestBasicRead.test_read[inputs0] ―――――――――――――――――――――――――――――――――――――――――――――――――――――
> 
> self = <source_acceptance_test.tests.test_core.TestBasicRead object at 0x7fed07c3f1f0>, connector_config = SecretDict(******)
> configured_catalog = ConfiguredAirbyteCatalog(streams=[ConfiguredAirbyteStream(stream=AirbyteStream(name='data', json_schema={'Data': {'typ...l_refresh'>, cursor_field=None, destination_sync_mode=<DestinationSyncMode.overwrite: 'overwrite'>, primary_key=None)])
> inputs = BasicReadTestConfig(config_path='secrets/config.json', configured_catalog_path='integration_tests/configured_catalog.j...rds=None, validate_schema=True, validate_data_points=False, expect_trace_message_on_failure=True, timeout_seconds=None)
> expected_records_by_stream = {}, docker_runner = <source_acceptance_test.utils.connector_runner.ConnectorRunner object at 0x7fed07c3ff70>
> detailed_logger = <Logger detailed_logger acceptance_tests_logs/test_core.py__TestBasicRead__test_read[inputs0].txt (DEBUG)>
> 
>     def test_read(
>         self,
>         connector_config,
>         configured_catalog,
>         inputs: BasicReadTestConfig,
>         expected_records_by_stream: MutableMapping[str, List[MutableMapping]],
>         docker_runner: ConnectorRunner,
>         detailed_logger,
>     ):
>         output = docker_runner.call_read(connector_config, configured_catalog)
>         records = [message.record for message in filter_output(output, Type.RECORD)]
>     
>         assert records, "At least one record should be read using provided catalog"
>     
>         if inputs.validate_schema:
>             self._validate_schema(records=records, configured_catalog=configured_catalog)
>     
>         self._validate_empty_streams(records=records, configured_catalog=configured_catalog, allowed_empty_streams=inputs.empty_streams)
>         for pks, record in primary_keys_for_records(streams=configured_catalog.streams, records=records):
>             for pk_path, pk_value in pks.items():
> >               assert (
>                     pk_value is not None
>                 ), f"Primary key subkeys {repr(pk_path)} have null values or not present in {record.stream} stream records."
> E               AssertionError: Primary key subkeys ('Job Seeker ID',) have null values or not present in data stream records.
> E               assert None is not None
> 
> ../../bases/source-acceptance-test/source_acceptance_test/tests/test_core.py:485: AssertionError
> ```
> 
> Second error says Primary key is null. I've used the right primary key given in documentation. The sandbox url does give some null primary keys.

@girarda it is allow to use nullable primary keys?

2022-11-01 23:13 UTC, marcosmarxm commented
@Sid-Lais could you share the test account credentials with me?

2022-11-02 02:22 UTC, Sid-Lais commented
> @Sid-Lais could you share the test account credentials with me?

Shared the credentials on slack

2022-11-02 23:04 UTC, marcosmarxm commented
@Sid-Lais I'm having issue running `./gradlew airbyte-integrations:connectors:source-sap:integrationTest`, can you share the output of this command>?

2022-11-03 14:53 UTC, Sid-Lais commented
> @Sid-Lais I'm having issue running `./gradlew airbyte-integrations:connectors:source-sap:integrationTest`, can you share the output of this command>?

Build completed with 3 failures. It says old python used even though I have python3.10
```
Building all of Airbyte.
/home/sid/projects/airbyte/airbyte-integrations/connectors
Type-safe dependency accessors is an incubating feature.

> Configure project :
configuring docker task for airbyte-bootloader
configuring docker task for airbyte-container-orchestrator
configuring docker task for airbyte-cron
configuring docker task for airbyte-proxy
configuring docker task for airbyte-server
configuring docker task for airbyte-temporal
configuring docker task for airbyte-webapp
configuring docker task for airbyte-workers
configuring docker task for init
configuring docker task for db-lib
configuring docker task for reporter

> Task :airbyte-integrations:bases:base-normalization:checkPython FAILED
> Task :airbyte-integrations:bases:source-acceptance-test:checkPython FAILED
> Task :airbyte-commons:compileJava FAILED

> Task :airbyte-integrations:connectors:source-sap:checkPython
Using python 3.10.8 from /home/sid/projects/airbyte/airbyte-integrations/connectors/source-sap/.venv (.venv/bin/python)
Using pip 22.3 from /home/sid/projects/airbyte/airbyte-integrations/connectors/source-sap/.venv/lib/python3.10/site-packages/pip (python 3.10)

FAILURE: Build completed with 3 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':airbyte-integrations:bases:base-normalization:checkPython'.
> Python (/usr) verion 3.8.10 does not match minimal required version: 3.9

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':airbyte-integrations:bases:source-acceptance-test:checkPython'.
> Python (/usr) verion 3.8.10 does not match minimal required version: 3.9

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':airbyte-commons:compileJava'.
> error: invalid source release: 17

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7s
14 actionable tasks: 4 executed, 10 up-to-date
```

2022-11-04 00:35 UTC, girarda commented
@marcosmarxm @Sid-Lais - it's not possible to have a nullable primary key, but it's possible to not set a primary key

2022-11-04 01:00 UTC, Sid-Lais commented
> @marcosmarxm @Sid-Lais - it's not possible to have a nullable primary key, but it's possible to not set a primary key

It doesn't let me not set a primary key
```
―――――――――――――――――――――――――――――――――――――――― TestDiscovery.test_primary_keys_exist_in_schema[inputs0] ―――――――――――――――――――――――――――――――――――――――――

self = <source_acceptance_test.tests.test_core.TestDiscovery object at 0x7f9b31554ac0>
discovered_catalog = {'data': AirbyteStream(name='data', json_schema={'Data': {'type': 'array', 'items': {'type': 'object', 'properties': {...refresh'>], source_defined_cursor=None, default_cursor_field=None, source_defined_primary_key=[[' ']], namespace=None)}

    def test_primary_keys_exist_in_schema(self, discovered_catalog: Mapping[str, Any]):
        """Check that all primary keys are present in catalog."""
        for stream_name, stream in discovered_catalog.items():
            for pk in stream.source_defined_primary_key or []:
                schema = stream.json_schema
                pk_path = "/properties/".join(pk)
>               pk_field_location = dpath.util.search(schema["properties"], pk_path)
E               KeyError: 'properties'

../../bases/source-acceptance-test/source_acceptance_test/tests/test_core.py:288: KeyError

 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_primary_keys_exist_in_schema[inputs0] ⨯77% ███████▊  
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_streams_has_sync_modes[inputs0] ✓81% ████████▏ 
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_additional_properties_is_true[inputs0] ✓85% ████████▌ Pulling docker image airbyte/source-sap:latest
{"type": "LOG", "log": {"level": "WARN", "message": "\n We did not find the airbyte/source-sap:latest image for this connector. This probably means this version has not yet been published to an accessible docker registry like DockerHub."}}

 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_backward_compatibility[inputs0] s88% ████████▉ 

―――――――――――――――――――――――――――――――――――――――――――――――――――― TestBasicRead.test_read[inputs0] ―――――――――――――――――――――――――――――――――――――――――――――――――――――

self = <source_acceptance_test.tests.test_core.TestBasicRead object at 0x7f9b31462dd0>, connector_config = SecretDict(******)
configured_catalog = ConfiguredAirbyteCatalog(streams=[ConfiguredAirbyteStream(stream=AirbyteStream(name='data', json_schema={'Data': {'typ...l_refresh'>, cursor_field=None, destination_sync_mode=<DestinationSyncMode.overwrite: 'overwrite'>, primary_key=None)])
inputs = BasicReadTestConfig(config_path='secrets/config.json', configured_catalog_path='integration_tests/configured_catalog.j...rds=None, validate_schema=True, validate_data_points=False, expect_trace_message_on_failure=True, timeout_seconds=None)
expected_records_by_stream = {}, docker_runner = <source_acceptance_test.utils.connector_runner.ConnectorRunner object at 0x7f9b312b4820>
detailed_logger = <Logger detailed_logger acceptance_tests_logs/test_core.py__TestBasicRead__test_read[inputs0].txt (DEBUG)>

    def test_read(
        self,
        connector_config,
        configured_catalog,
        inputs: BasicReadTestConfig,
        expected_records_by_stream: MutableMapping[str, List[MutableMapping]],
        docker_runner: ConnectorRunner,
        detailed_logger,
    ):
        output = docker_runner.call_read(connector_config, configured_catalog)
        records = [message.record for message in filter_output(output, Type.RECORD)]
    
        assert records, "At least one record should be read using provided catalog"
    
        if inputs.validate_schema:
            self._validate_schema(records=records, configured_catalog=configured_catalog)
    
        self._validate_empty_streams(records=records, configured_catalog=configured_catalog, allowed_empty_streams=inputs.empty_streams)
        for pks, record in primary_keys_for_records(streams=configured_catalog.streams, records=records):
            for pk_path, pk_value in pks.items():
>               assert (
                    pk_value is not None
                ), f"Primary key subkeys {repr(pk_path)} have null values or not present in {record.stream} stream records."
E               AssertionError: Primary key subkeys (' ',) have null values or not present in data stream records.
E               assert None is not None

../../bases/source-acceptance-test/source_acceptance_test/tests/test_core.py:485: AssertionError

 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestBasicRead.test_read[inputs0] ⨯92% █████████▎{"type": "LOG", "log": {"level": "ERROR", "message": "Docker container failed, code 1, error:\n{\"type\": \"TRACE\", \"trace\": {\"type\": \"ERROR\", \"emitted_at\": 1667523563970.8928, \"error\": {\"message\": \"Something went wrong in the connector. See the logs for more details.\", \"internal_message\": \"2 validation errors for ConfiguredAirbyteCatalog\\nstreams -> 0 -> sync_mode\\n  value is not a valid enumeration member; permitted: 'full_refresh', 'incremental' (type=type_error.enum; enum_values=[<SyncMode.full_refresh: 'full_refresh'>, <SyncMode.incremental: 'incremental'>])\\nstreams -> 0 -> destination_sync_mode\\n  value is not a valid enumeration member; permitted: 'append', 'overwrite', 'append_dedup' (type=type_error.enum; enum_values=[<DestinationSyncMode.append: 'append'>, <DestinationSyncMode.overwrite: 'overwrite'>, <DestinationSyncMode.append_dedup: 'append_dedup'>])\", \"stack_trace\": \"Traceback (most recent call last):\\n  File \\\"/airbyte/integration_code/main.py\\\", line 13, in <module>\\n    launch(source, sys.argv[1:])\\n  File \\\"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\\\", line 131, in launch\\n    for message in source_entrypoint.run(parsed_args):\\n  File \\\"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\\\", line 119, in run\\n    config_catalog = self.source.read_catalog(parsed_args.catalog)\\n  File \\\"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/source.py\\\", line 90, in read_catalog\\n    return ConfiguredAirbyteCatalog.parse_obj(self.read_config(catalog_path))\\n  File \\\"pydantic/main.py\\\", line 521, in pydantic.main.BaseModel.parse_obj\\n  File \\\"pydantic/main.py\\\", line 341, in pydantic.main.BaseModel.__init__\\npydantic.error_wrappers.ValidationError: 2 validation errors for ConfiguredAirbyteCatalog\\nstreams -> 0 -> sync_mode\\n  value is not a valid enumeration member; permitted: 'full_refresh', 'incremental' (type=type_error.enum; enum_values=[<SyncMode.full_refresh: 'full_refresh'>, <SyncMode.incremental: 'incremental'>])\\nstreams -> 0 -> destination_sync_mode\\n  value is not a valid enumeration member; permitted: 'append', 'overwrite', 'append_dedup' (type=type_error.enum; enum_values=[<DestinationSyncMode.append: 'append'>, <DestinationSyncMode.overwrite: 'overwrite'>, <DestinationSyncMode.append_dedup: 'append_dedup'>])\\n\", \"failure_type\": \"system_error\"}}}\n"}}

 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestBasicRead.test_airbyte_trace_message_on_failure[inputs0] ✓96% █████████▋
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_full_refresh.py::TestFullRefresh.test_sequential_reads[inputs0] ✓100% ██████████
{"type": "LOG", "log": {"level": "INFO", "message": "/home/sid/projects/airbyte/airbyte-integrations/connectors/source-sap - SAT run - 520f662ba4a4df483f8f0e119941ac2d4ed84a24 - FAILED"}}

============================================================ warnings summary =============================================================
../../bases/source-acceptance-test/source_acceptance_test/config.py:246: 26 warnings
airbyte-integrations/bases/source-accepta [...]

2022-11-04 08:52 UTC, marcosmarxm commented
Hello! I'm going to be out of the office this Friday and won't be able to review your contribution again today, I return next Monday. So far, most contributions look solid and are almost done to be approved. As said in [Chris' comment](https://airbytehq.slack.com/archives/C0450PCSDB2/p1667430678866629) all contributions made before 2-November are eligible to receive the prize and have 2 weeks to merge the contributions. But I ensure next week we're going to have your contribution merged. If you have questions about the implementation you can send them in `#hacktoberfest-2022` in Airbyte's Slack.

Sorry the inconvenience and see you again next week, thank you so much for your contribution!

2022-11-04 13:26 UTC, Sid-Lais commented
> Hello! I'm going to be out of the office this Friday and won't be able to review your contribution again today, I return next Monday. So far, most contributions look solid and are almost done to be approved. As said in [Chris' comment](https://airbytehq.slack.com/archives/C0450PCSDB2/p1667430678866629) all contributions made before 2-November are eligible to receive the prize and have 2 weeks to merge the contributions. But I ensure next week we're going to have your contribution merged. If you have questions about the implementation you can send them in `#hacktoberfest-2022` in Airbyte's Slack.
> 
> Sorry the inconvenience and see you again next week, thank you so much for your contribution!

No worries. Enjoy your weekend. (⁠◍⁠•⁠ᴗ⁠•⁠◍⁠)

2022-11-08 17:04 UTC, marcosmarxm requested changes
@Sid-Lais I think this source must change the name to SAP Fieldgrass to make clear is only one specific module of SAP.

2022-11-08 17:11 UTC, marcosmarxm requested changes
Some comments, the error you pointed is related about your schema.

2022-11-08 17:11 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-sap/source_sap/schemas/TODO.md
> +
Remove this file.

2022-11-08 18:27 UTC, Sid-Lais commented
> @Sid-Lais I think this source must change the name to SAP Fieldgrass to make clear is only one specific module of SAP.

So all the files also has to be changed to sap_fieldglass from sap?

2022-11-09 07:23 UTC, Sid-Lais commented on airbyte-integrations/connectors/source-sap/source_sap/schemas/data.json
> +              "description" : "Custom fields found on the worker.\nIf there are many custom fields, there will be many\ncolumns.Column header format will be: \n\"[c]modulename_custom field name\" (i.
So I need to just add the schema link at top and fix the indexing?
Is this enough or are there more changes to be made?
I used JSON schema validator and it says its correct.
```
{
  "Data": {
    "type": "array",
    "items": {
      "type": "object",
      "required": [
        "Bill Rate",
        "Business Unit Code",
        "Business Unit Name",
        "Buyer Code",
        "Cost Center Code",
        "Currency",
        "End Date",
        "First Name",
        "Job Posting Title",
        "Job Seeker ID",
        "Last Name",
        "Pay Rate",
        "Rate Category /UOM",
        "Sequence",
        "Site Code",
        "Site Name",
        "Start Date",
        "Status",
        "Vendor Name",
        "Vendor Number",
        "Work Order ID",
        "Work Order/Work Order Revision Owner",
        "Worker Email",
        "Worker ID"
      ],
      "properties": {
        "[c]Worker Custom Fields": {
          "type": "string",
          "description": "Custom fields found on the worker.\nIf there are many custom fields, there will be many\ncolumns.Column header format will be: \n\"[c]modulename_custom field name\" (i.e. [c] followed by\nmodule custom text lowercase with no spaces, followed by\nunderscore, followed by the custom field name text as\ndefined by users in the SAP Fieldglass application.)",
          "maxLength": 4000
        },
        "Job Seeker ID": {
          "type": "string",
          "description": "14-character alphanumeric SAP Fieldglass Job Seeker ID.",
          "maxLength": 14
        },
        "[c]Buyer or Supplier custom fields": {
          "type": "string",
          "description": "Custom fields found on the supplier. (For supplier side\ndownload, only those fields required by buyer for supplier\nto be entered and viewed are downloaded.)If there are many\ncustom fields, there will be many columns.Column header\nformat will be: \n?[c]modulename_custom field name? (i.e. [c] followed by\nmodule custom text lowercase with no spaces, followed by\nunderscore, followed by the custom field name text as\ndefined by users in the SAP Fieldglass application.)",
          "maxLength": 4000
        },
        "Billable Per Diem": {
          "type": "integer",
          "format": "float",
          "description": ""
        },
        "First Name": {
          "type": "string",
          "description": "First name of the Worker as defined in SAP Fieldglass.",
          "maxLength": 100
        },
        "Remit To address Code": {
          "type": "string",
          "description": "Code as assigned to the Remit To Address by supplier.",
          "maxLength": 100
        },
        "Cost Center Name": {
          "type": "string",
          "description": "Cost Center Name in SAP Fieldglass.",
          "maxLength": 200
        },
        "Work Order/Work Order Revision Owner": {
          "type": "string",
          "description": "Work Order Owner?s name.",
          "maxLength": 100
        },
        "Vendor Name": {
          "type": "string",
          "description": "Supplier name.",
          "maxLength": 200
        },
        "Work Order ID": {
          "type": "string",
          "description": "Work Order ID.",
          "maxLength": 14
        },
        "Bill Rate": {
          "type": "integer",
          "format": "float",
          "description": "Worker?s Bill Rate that is associated to the Rate\nCategory/UOM listed in the previous field."
        },
        "Start Date": {
          "type": "string",
          "format": "date",
          "description": "Work order start date."
        },
        "Security ID": {
          "type": "string",
          "description": "This column will only appear in the file if the security ID\nfield functionality is activated in SAP Fieldglass for the\nbuyer. If the functionality is not activated, this column\nwill not be in the file.",
          "maxLength": 100
        },
        "Currency": {
          "type": "string",
          "description": "ISO currency designation (ex. USD).",
          "maxLength": 100
        },
        "[c]Work Order Custom Fields": {
          "type": "string",
          "description": "Custom fields found on the work order/work order revision. \nIf there are many custom fields, there will be many columns.\nColumn header format will be:\n?[c]modulename_custom field name? (i.e. [c] followed by\nmodule custom text lowercase with no spaces, followed by\nunderscore, followed by the custom field name text as\ndefined by users in the SAP Fieldglass application.)",
          "maxLength": 4000
        },
        "Job Posting Title": {
          "type": "string",
          "description": "Job Posting?s Title or SOW Name for SOW Workers.",
          "maxLength": 100
        },
        "Worker ID": {
          "type": "string",
          "description": "14-character alphanumeric SAP Fieldglass Worker ID.",
          "maxLength": 14
        },
        "Business Unit Name": {
          "type": "string",
          "description": "Business Unit Name.",
          "maxLength": 100
        },
        "Site Name": {
          "type": "string",
          "description": "Site Name.",
          "maxLength": 100
        },
        "Buyer Code": {
          "type": "string",
          "description": "Buyer Company Code.",
          "maxLength": 4
        },
        "Status": {
          "type": "string",
          "description": "Status of the worker.",
          "maxLength": 50
        },
        "Pay Rate": {
          "type": "integer",
          "format": "float",
          "description": "Worker?s Pay Rate that is associated to the Rate Category/UOM\nlisted in the previous field. \nIf Supplier did not enter a Pay Rate, 0.00 will be\ndisplayed."
        },
        "Vendor Number": {
          "type": "string",
          "description": "SAP Fieldglass Supplier code for buyer.",
          "maxLength": 4
        },
        "Sequence": {
          "type": "number",
          "description": "Work Order Revision Number."
        },
        "Person ID": {
          "type": "string",
          "description": "Unique identifier for the worker as a person.",
          "maxLength": 24
        },
        "Cost Center Code": {
          "type": "string",
          "description": "Cost Center Code in SAP Fieldglass.",
          "maxLength": 200
        },
        "[c]Worker User Person Custom Fields": {
          "type": "string",
          "description": "Custom fields found on the worker user person\nIf there are many custom fields, there will be many columns.\nColumn header format will be: \n?[c]modulename_custom field name? (i.e. [c] followed by\nmodule custom text lowercase with no spaces, followed by\nunderscore, followed by the custom field name text as\ndefined by users in the SAP Fieldglass application.)",
          "maxLength": 4000
        },
        "Rate Category /UOM": {
          "type": "string",
          "description": "Worker?s Rate Category/Unit Of Measure for which the\ncorresponding rate will be displayed. \nMore than one Rate Category/UOM may exist for a single\nWorker. If this is the case a new line will appear for each\nassociated Rate Category/UOM in this file.",
          "maxLength": 100
        },
        "Segmented Object Detail": {
          "type": "string",
          "description": "Segmented Object Detail string. Segments will be separated by\ndelimiter on the Segmented Object.\nValid delimiters are colon (:), semi-colon (;), pipe (|), and\ndash (-).\nRequired if ?Enable Segmented Object Detail? configuration is\nset.\nThis field is mutually exclusive with GL Account fields.\nMore than one string can appear for a cost center.",
          "maxLength": 2000
        },
        "End Date": {
          "type": "string",
          "format": "date",
          "description": "Work order end date."
        },
        "Worker Email": {
          "type": "string",
          "description": "Worker?s e-mail address.",
          "maxLength": 100
      [...]

2022-11-09 12:13 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-sap/source_sap/schemas/data.json
> +              "description" : "Custom fields found on the worker.\nIf there are many custom fields, there will be many\ncolumns.Column header format will be: \n\"[c]modulename_custom field name\" (i.
Probably you must use `data` to field record and only use the nest data inside.

2022-11-09 12:13 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-sap/source_sap/schemas/data.json
> +              "description" : "Custom fields found on the worker.\nIf there are many custom fields, there will be many\ncolumns.Column header format will be: \n\"[c]modulename_custom field name\" (i.
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
        "Last Name": {
          "type": "string",
          "description": "Last name of the Worker as defined in SAP Fieldglass.",
          "maxLength": 100
        },
        "Site Code": {
          "type": "string",
          "description": "Site Code.",
          "maxLength": 100
        },
        "Business Unit Code": {
          "type": "string",
          "description": "Business Unit Code.",
          "maxLength": 100
        }
   }
}
```

2022-11-09 18:28 UTC, Sid-Lais commented
@marcosmarxm Rebuilt the whole connector from ground and turns out I had somewhat used old generator. Everything works now and all test passed. Test result added to the PR in acceptance section. Re-added primary key too for future use and all test works.

2022-11-09 22:29 UTC, marcosmarxm requested changes
@Sid-Lais small comment about unrelated change and it is ready to publish.

2022-11-10 05:54 UTC, Sid-Lais commented
> @Sid-Lais small comment about unrelated change and it is ready to publish.

Done

2022-11-10 23:26 UTC, marcosmarxm commented
/test connector=connectors/source-sap-fieldglass

2022-11-10 23:41 UTC, marcosmarxm commented
/test connector=connectors/source-sap-fieldglass

2022-11-11 00:44 UTC, marcosmarxm commented
/publish connector=connectors/source-sap-fieldglass

2022-11-11 01:46 UTC, marcosmarxm approved these changes
Thanks @Sid-Lais

2022-11-11 01:46 UTC, merged

2022-11-11 01:50 UTC, Sid-Lais commented
> Thanks @Sid-Lais

Thank you so much for helping. It was my first contribution to open source.