🎉 New source: Breezometer Pollen [low-code SDK]
airbytehq/airbyte pull request #18650
Opened 2022-10-29 16:22 UTC by sarafonseca-123

## What
A new source, Breezometer Pollen.

## How
Using airbyte's low-code SDK.

## Recommended reading order
1. airbyte-integrations/connectors/source-breezometer-pollen/source_breezometer_pollen/breezometer_pollen.yaml
2. airbyte-integrations/connectors/source-breezometer-pollen/source_breezometer_pollen/spec.yaml

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [X] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [X] Secrets in the connector's spec are annotated with `airbyte_secret`
- [X] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [X] Documentation updated
    - [X] Connector's `README.md`
    - [X] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [X] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [X] `docs/integrations/README.md`
    - [X] `airbyte-integrations/builds.md`
- [X] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

## Tests

<details><summary><strong>Integration</strong></summary>

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/56175551/198842234-d5dd3ccd-f368-47d4-b85d-66d1f3672e1e.png">

</details>

<details><summary><strong>Acceptance</strong></summary>

Building all of Airbyte.
/Users/sarasantos/git-jusbrasil/airbyte/airbyte-integrations/connectors
Type-safe dependency accessors is an incubating feature.

> Configure project :
configuring docker task for airbyte-bootloader
configuring docker task for airbyte-cli
configuring docker task for airbyte-container-orchestrator
configuring docker task for airbyte-cron
configuring docker task for airbyte-server
configuring docker task for airbyte-temporal
configuring docker task for airbyte-webapp
configuring docker task for airbyte-workers
configuring docker task for init
configuring docker task for db-lib
configuring docker task for reporter

> Task :airbyte-integrations:bases:source-acceptance-test:checkPython
Using python 3.10.8 from /Users/sarasantos/git-jusbrasil/airbyte/airbyte-integrations/bases/source-acceptance-test/.venv (.venv/bin/python)
Using pip 21.3.1 from /Users/sarasantos/git-jusbrasil/airbyte/airbyte-integrations/bases/source-acceptance-test/.venv/lib/python3.10/site-packages/pip (python 3.10)

> Task :airbyte-integrations:connectors:source-breezometer-pollen:checkPython
Using python 3.10.8 from /Users/sarasantos/git-jusbrasil/airbyte/airbyte-integrations/connectors/source-breezometer-pollen/.venv (.venv/bin/python)
Using pip 21.3.1 from /Users/sarasantos/git-jusbrasil/airbyte/airbyte-integrations/connectors/source-breezometer-pollen/.venv/lib/python3.10/site-packages/pip (python 3.10)

> Task :airbyte-integrations:bases:base-normalization:checkPython
Using python 3.10.8 from /Users/sarasantos/git-jusbrasil/airbyte/airbyte-integrations/bases/base-normalization/.venv (.venv/bin/python)
Using pip 21.3.1 from /Users/sarasantos/git-jusbrasil/airbyte/airbyte-integrations/bases/base-normalization/.venv/lib/python3.10/site-packages/pip (python 3.10)

> Task :airbyte-integrations:connectors:source-breezometer-pollen:pipInstall
[python] .venv/bin/python -m pip install pip==21.3.1
         Requirement already satisfied: pip==21.3.1 in ./.venv/lib/python3.10/site-packages (21.3.1)
         WARNING: You are using pip version 21.3.1; however, version 22.3 is available.
         You should consider upgrading via the '/Users/sarasantos/git-jusbrasil/airbyte/airbyte-integrations/connectors/source-breezometer-pollen/.venv/bin/python -m pip install --upgrade pip' command.
[python] .venv/bin/python -m pip list --format=columns
         Package                   Version   Editable project location
         ------------------------- --------- -----------------------------------------------------------------------------------------
         airbyte-cdk               0.1.104
         attrs                     22.1.0
         backoff                   2.2.1
         black                     22.3.0
         certifi                   2022.9.24
         charset-normalizer        2.1.1
         click                     8.1.3
         coverage                  6.3.1
         dataclasses-jsonschema    2.15.1
         deepdiff                  5.8.1
         Deprecated                1.2.13
         docker                    5.0.3
         dpath                     2.0.6
         exceptiongroup            1.0.0
         fancycompleter            0.9.1
         flake8                    4.0.1
         hypothesis                6.54.6
         hypothesis-jsonschema     0.20.1
         icdiff                    1.9.1
         idna                      3.4
         inflection                0.5.1
         iniconfig                 1.1.1
         isort                     5.6.4
         Jinja2                    3.1.2
         jsonref                   0.2
         jsonschema                3.2.0
         MarkupSafe                2.1.1
         mccabe                    0.6.1
         multidict                 6.0.2
         mypy                      0.930
         mypy-extensions           0.4.3
         ordered-set               4.1.0
         packaging                 21.3
         pathspec                  0.10.1
         pdbpp                     0.10.3
         pendulum                  2.1.2
         pip                       21.3.1
         platformdirs              2.5.2
         pluggy                    0.13.1
         pprintpp                  0.4.0
         py                        1.11.0
         pycodestyle               2.8.0
         pydantic                  1.9.2
         pyflakes                  2.4.0
         Pygments                  2.13.0
         pyparsing                 3.0.9
         pyproject-flake8          0.0.1a2
         pyrepl                    0.9.0
         pyrsistent                0.18.1
         pytest                    6.1.2
         pytest-cov                3.0.0
         pytest-mock               3.6.1
         pytest-sugar              0.9.5
         pytest-timeout            1.4.2
      [...]

2022-10-29 16:22 UTC, sarafonseca-123 commented
I have a test account that I can share via Slack!

2022-10-31 11:10 UTC, marcosmarxm commented
Hello @sarafonseca-123 , Marcos from Airbyte here 👋 . We received more than 25 new contributions along the weekend. One is yours 🎉  thank so much for! Our team is limited and maybe the review process can take longer than expected. As described in the Airbyte's Hacktoberfest your contribution was submitted before November 2nd and it is eligible to win the prize. The review process will validate other requirements. I ask to you patience until someone from the team review it. 

Because I reviewed some contributions for Hacktoberfest so far I saw some common patterns you can check in advance:
* [ ] Make sure you have added connector documentation to `/docs/integrations/`
* [ ] Remove the file `catalog` from `/integration_tests`
* [ ] Edit the `sample_config.json` inside `/integration_tests`
* [ ] For the `configured_catalog` you can use only `json_schema: {}`
* [ ] Add title to all properties in the `spec.yaml`
* [ ] Make sure the `documentationUrl` in the `spec.yaml` redirect to Airbyte's future connector page, eg: connector Airtable the `documentationUrl: https://docs.airbyte.com/integrations/sources/airtable`
* [ ] Review now new line at EOF (end-of-file) for all files.

If possible send to me a DM in Slack with the tests credentials, this process will make easier to us run integration tests and publish your connector. If you only has production keys, make sure to create a bootstrap.md explaining how to get the keys.

2022-10-31 20:47 UTC, marcosmarxm requested changes
@sarafonseca-123 are you plannign to add other endpoints like air quality, wildfire and weather?

2022-10-31 20:51 UTC, sarafonseca-123 commented
@marcosmarxm yes, I'm gonna do this tonight! until then I will change this PR to draft

2022-11-04 08:50 UTC, marcosmarxm commented
Hello! I'm going to be out of the office this Friday and won't be able to review your contribution again today, I return next Monday. So far, most contributions look solid and are almost done to be approved. As said in [Chris' comment](https://airbytehq.slack.com/archives/C0450PCSDB2/p1667430678866629) all contributions made before 2-November are eligible to receive the prize and have 2 weeks to merge the contributions. But I ensure next week we're going to have your contribution merged. If you have questions about the implementation you can send them in `#hacktoberfest-2022` in Airbyte's Slack.

Sorry the inconvenience and see you again next week, thank you so much for your contribution!

2022-11-08 00:54 UTC, marcosmarxm commented
/test connector=connectors/source-breezometer

2022-11-08 01:11 UTC, marcosmarxm commented
/publish connector=connectors/source-breezometer

2022-11-08 01:12 UTC, marcosmarxm approved these changes
Thanks for the contribution @sarafonseca-123

2022-11-08 01:34 UTC, merged