New source: Ip2whois [low-code SDK]|
airbytehq/airbyte pull request #18661
Opened 2022-10-30 13:27 UTC by kaggrwal

## What
https://www.ip2whois.com/developers-api [issue](https://github.com/airbytehq/connector-contest/issues/229)

## How
A new source connector using low-code cdk.

## Streams
- Whois

## 🚨 User Impact 🚨
No user impact

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [✓ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ✓] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ✓] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ✓] Code reviews completed
- [ ✓] Documentation updated
    - [ ✓] Connector's `README.md`
    - [ ✓] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [✓ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ✓] `docs/integrations/README.md`
    - [ ✓] `airbyte-integrations/builds.md`
- [ ✓] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

![image](https://user-images.githubusercontent.com/11560407/198846383-2f3c70e1-829d-4855-a150-e940438dd908.png)

</details>

2022-10-31 11:18 UTC, marcosmarxm requested changes
Hello @kaggrwal, Marcos from Airbyte here 👋 . We received more than 25 new contributions along the weekend. One is yours 🎉  thank so much for! Our team is limited and maybe the review process can take longer than expected. As described in the Airbyte's Hacktoberfest your contribution was submitted before November 2nd and it is eligible to win the prize. The review process will validate other requirements. I ask to you patience until someone from the team review it. 

Because I reviewed some contributions for Hacktoberfest so far I saw some common patterns you can check in advance:
* [ ] Make sure you have added connector documentation to `/docs/integrations/`
* [ ] Remove the file `catalog` from `/integration_tests`
* [ ] Edit the `sample_config.json` inside `/integration_tests`
* [ ] For the `configured_catalog` you can use only `json_schema: {}`
* [ ] Add title to all properties in the `spec.yaml`
* [ ] Make sure the `documentationUrl` in the `spec.yaml` redirect to Airbyte's future connector page, eg: connector Airtable the `documentationUrl: https://docs.airbyte.com/integrations/sources/airtable`
* [ ] Review now new line at EOF (end-of-file) for all files.

If possible send to me a DM in Slack with the tests credentials, this process will make easier to us run integration tests and publish your connector. If you only has production keys, make sure to create a bootstrap.md explaining how to get the keys.

2022-10-31 21:44 UTC, marcosmarxm requested changes
Small comment additional to the previous one.

2022-10-31 21:44 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-ip2whois/source_ip2whois/spec.yaml
> +        - www.facebook.com
Why not use this as an array and use the ListStream feature to read records from multiple domains?

2022-11-01 23:24 UTC, marcosmarxm commented
@kaggrwal please check my first comment and check all tasks. Ask my review again when this is done.

2022-11-03 01:12 UTC, marcosmarxm approved these changes
Thanks @kaggrwal I'll publish later this week.

2022-11-03 12:21 UTC, marcosmarxm requested changes
I found some problems running tests, please fix them.

2022-11-03 12:21 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-ip2whois/source_ip2whois/schemas/TODO.md
> +## Static schemas
please remove this file.

2022-11-03 12:21 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-ip2whois/source_ip2whois/schemas/whois.json
> +    },
The schema is not compatible:
```
The whois stream has the following schema errors:
'' is not a 'email'

Failed validating 'format' in schema['properties']['registrant']['properties']['email']:
    {'format': 'email', 'type': 'string'}

On instance['registrant']['email']:
    ''
--------------------------------------------------------------------------------
'' is not a 'email'

Failed validating 'format' in schema['properties']['admin']['properties']['email']:
    {'format': 'email', 'type': 'string'}

On instance['admin']['email']:
    ''
--------------------------------------------------------------------------------
'' is not a 'email'

Failed validating 'format' in schema['properties']['tech']['properties']['email']:
    {'format': 'email', 'type': 'string'}

On instance['tech']['email']:
    ''
```

2022-11-03 12:21 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-ip2whois/source_ip2whois/spec.yaml
> +    - access_key
`access_key` doesn't exist.

2022-11-03 12:21 UTC, marcosmarxm commented on docs/integrations/README.md
> +| [Ip2whois](source/ip2whois.md)                                                              | Alpha                | Yes                 |
```suggestion
| [Ip2whois](source/ip2whois.md)                                                              | Alpha                | No                 |
```

2022-11-04 08:52 UTC, marcosmarxm commented
Hello! I'm going to be out of the office this Friday and won't be able to review your contribution again today, I return next Monday. So far, most contributions look solid and are almost done to be approved. As said in [Chris' comment](https://airbytehq.slack.com/archives/C0450PCSDB2/p1667430678866629) all contributions made before 2-November are eligible to receive the prize and have 2 weeks to merge the contributions. But I ensure next week we're going to have your contribution merged. If you have questions about the implementation you can send them in `#hacktoberfest-2022` in Airbyte's Slack.

Sorry the inconvenience and see you again next week, thank you so much for your contribution!

2022-11-08 00:27 UTC, marcosmarxm commented
@kaggrwal let me know when you solve the issues.

2022-11-08 16:46 UTC, kaggrwal commented
> @kaggrwal let me know when you solve the issues.

@marcosmarxm it's working fine i have tested it, to get API keys, you need to create an account https://www.ip2location.io/ or i can share my keys for the testing purposes.

2022-11-09 12:41 UTC, marcosmarxm commented
/test connector=connectors/source-ip2whois

2022-11-09 12:59 UTC, marcosmarxm commented
/publish connector=connectors/source-ip2whois

2022-11-09 13:00 UTC, marcosmarxm approved these changes
Thanks @kaggrwal

2022-11-09 13:17 UTC, merged