Destination S3: Add virtual-hosted-style option
airbytehq/airbyte pull request #19427
Opened 2022-11-15 14:14 UTC by Xingyuan-Chen

*I add a virtual-hosted-style option for S3 destination
*It helps to make both S3 destination support Non-Amazon S3 endpoint who only support virtual hosted style like Aliyun OSS.
This PR closes https://github.com/airbytehq/airbyte/issues/19426

2022-11-22 20:25 UTC, marcosmarxm commented
Hello :wave:, first thank you for this amazing contribution. 

We really appreciate the effort you've made to improve the project.
We ask you patience for the code review. Last month our team was focused on Hacktoberfest event and that probably left some PR without the proper feedback. And this week, due to the Thanksgiving US Holiday, most our team is out of office with their families. Another important piece of information why code won't be merge this week is: as a safety measure the core team has decided to freeze merging code to main branch to keep the release stable. Next week we'll return to you with the proper code review and update the status of your contribution.

If you have any questions feel free to send me a message in Slack!
Thanks!

2022-12-02 22:49 UTC, marcosmarxm requested changes

2022-12-02 22:49 UTC, marcosmarxm commented on airbyte-integrations/bases/base-java-s3/src/main/java/io/airbyte/integrations/destination/s3/S3DestinationConfig.java
> +389
Please update this

2022-12-03 08:07 UTC, Xingyuan-Chen commented on airbyte-integrations/bases/base-java-s3/src/main/java/io/airbyte/integrations/destination/s3/S3DestinationConfig.java
> +389
updated

2022-12-20 19:51 UTC, marcosmarxm commented
Hello :wave::skin-tone-2: and thank you for your contribution!

Airbyte has instituted a code freeze between 19 and 30 December, to make sure there are no disruptions during the holidays. 
Because of this, reviewing and merging your contribution may take longer than usual. 
We apologize for the delay, but we want everyone to have a quiet and happy holiday.

If you have any questions or need further clarification, please don't hesitate to ping via Slack.

2022-12-23 13:47 UTC, dtonda commented
Note that this may also solve issue #20860 as it would provide an alternative way to configure the S3 connection for non-AWS S3 buckets.

2023-01-27 15:09 UTC, ZengineChris commented
Any updates on this?

2023-03-07 20:11 UTC, sh4sh commented
/test connector=connectors/destination-s3

2023-03-08 00:23 UTC, grishick requested changes
Several comments on this PR:
1. This PR does not compile, because `PATH_STYLE_ACCESS_ENABLED` is not defined.
2. `isPathStyleAccessEnabled` getter method is not used anywhere
3. `S_3_PATH_STYLE_ACCESS_ENABLED` is defined but not used anywhere
4. In order for this feature to be usable, this PR should add a new field to `spec.json `to `destination-s3` connector

2023-04-20 11:28 UTC, marcosmarxm commented
Closed due inactivity @Xingyuan-Chen let us know if you want to return to this PR.

2023-04-20 11:28 UTC, closed without merging