Update availability of SALES_AND_TRAFFIC_REPORT SLA to 2 days
airbytehq/airbyte pull request #19480
Opened 2022-11-16 14:28 UTC by krisjan-oldekamp

## What
Data is not available in Amazon Seller API next day, so only fetch data now - 2 days (instead of now - 1 day)

## How
Adjusted the SLA parameter

## 🚨 User Impact 🚨
No breaking changes.

2022-11-17 07:44 UTC, krisjan-oldekamp commented
Related to this isssue: https://github.com/airbytehq/airbyte/issues/18958

2022-11-22 20:25 UTC, marcosmarxm commented
Hello :wave:, first thank you for this amazing contribution. 

We really appreciate the effort you've made to improve the project.
We ask you patience for the code review. Last month our team was focused on Hacktoberfest event and that probably left some PR without the proper feedback. And this week, due to the Thanksgiving US Holiday, most our team is out of office with their families. Another important piece of information why code won't be merge this week is: as a safety measure the core team has decided to freeze merging code to main branch to keep the release stable. Next week we'll return to you with the proper code review and update the status of your contribution.

If you have any questions feel free to send me a message in Slack!
Thanks!

2022-12-20 19:52 UTC, marcosmarxm commented
Hello :wave::skin-tone-2: and thank you for your contribution!

Airbyte has instituted a code freeze between 19 and 30 December, to make sure there are no disruptions during the holidays. 
Because of this, reviewing and merging your contribution may take longer than usual. 
We apologize for the delay, but we want everyone to have a quiet and happy holiday.

If you have any questions or need further clarification, please don't hesitate to ping via Slack.

2023-01-18 09:17 UTC, marcosmarxm requested changes

2023-01-18 09:17 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
> +    availability_sla_days = 2
I don't see the information about SLA availability to this report as others one. See example: https://developer-docs.amazon.com/sp-api/docs/report-type-values#vendor-retail-analytics-reports
<img width="372" alt="image" src="https://user-images.githubusercontent.com/5154322/213131687-002deac9-d8a0-45db-a59d-57dcc40f1083.png">

You have any link to Amazon docs?

2023-01-18 09:19 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
> +    availability_sla_days = 2
I read the discussion in #18958 looks there isn't anything in Amazon docs and it is more a practical issue encountered by users. Do you mind adding a comment about it in the code.

2023-01-24 20:55 UTC, YowanR commented
@krisjan-oldekamp is there any Amazon docs pointing to this? I couldn't find that SLA. The reason I'm asking is because we do not want connectors to be subjective in nature -- It's better to leave this decision to the person using the connector (and adding this to the docs instead).

2023-01-27 09:34 UTC, dandpz commented
> @krisjan-oldekamp is there any Amazon docs pointing to this? I couldn't find that SLA. The reason I'm asking is because we do not want connectors to be subjective in nature -- It's better to leave this decision to the person using the connector (and adding this to the docs instead). 

Hi, I created the issue, in the doc there is no SLA, but the update delay is a common issue. Can I suggest to add a parameter in source configuration instead of hardcoding it?

2023-03-17 00:05 UTC, marcosmarxm commented
Close due inactivity @krisjan-oldekamp let me know if you want to continue this work.

2023-03-17 00:05 UTC, closed without merging

2023-03-29 08:27 UTC, krisjan-oldekamp commented
@marcosmarxm @dandpz  Sorry, missed the thread. Indeed it's not in the Amazon documentation. However an Amazon dev is shing some light on this: https://github.com/amzn/selling-partner-api-docs/issues/2303 where he recommends to fetch the data after 3 days.

Problem is, some data is available after 24 hours and some data after 48-72 hours. Thing is, you're not getting any response from the API that (a part) of the data is not updated / there yet. So there will be some data in the reponse that is correct, and some data is missing.