🎉 Source Amazon Ads: add option to customize look back window value
airbytehq/airbyte pull request #19491
Opened 2022-11-16 17:07 UTC by dandpz

## What
1. Add "look_back_window" internal settings
2. Add "Look Back Window" to source settings in order to let the user customize this value

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
The User will find a new field to set inside the resource settings. No breaking change, default value is the old one.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

2022-11-22 20:25 UTC, marcosmarxm commented
Hello :wave:, first thank you for this amazing contribution. 

We really appreciate the effort you've made to improve the project.
We ask you patience for the code review. Last month our team was focused on Hacktoberfest event and that probably left some PR without the proper feedback. And this week, due to the Thanksgiving US Holiday, most our team is out of office with their families. Another important piece of information why code won't be merge this week is: as a safety measure the core team has decided to freeze merging code to main branch to keep the release stable. Next week we'll return to you with the proper code review and update the status of your contribution.

If you have any questions feel free to send me a message in Slack!
Thanks!

2022-12-20 19:52 UTC, marcosmarxm commented
Hello :wave::skin-tone-2: and thank you for your contribution!

Airbyte has instituted a code freeze between 19 and 30 December, to make sure there are no disruptions during the holidays. 
Because of this, reviewing and merging your contribution may take longer than usual. 
We apologize for the delay, but we want everyone to have a quiet and happy holiday.

If you have any questions or need further clarification, please don't hesitate to ping via Slack.

2023-01-18 09:04 UTC, marcosmarxm approved these changes
Thanks @dandpz I only need the final approval from the connector team.

2023-01-19 09:24 UTC, grubberr commented on airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/streams/report_streams/report_streams.py
> -        look_back_date = pendulum.today(tz=profile.timezone).date().subtract(days=self.LOOK_BACK_WINDOW - 1)
can you remove this constant from 
```
LOOK_BACK_WINDOW = 3
```

it seems we don't need it now

2023-01-19 09:36 UTC, grubberr commented
@dandpz can you please merge master branch and resolve conflicts?

2023-01-20 09:19 UTC, grubberr commented on airbyte-config/init/src/main/resources/seed/source_definitions.yaml
> +  dockerImageTag: 0.1.28
you don't need to bump version here, it's done automatically by publishing scripts

2023-01-20 09:20 UTC, grubberr commented on airbyte-config/init/src/main/resources/seed/source_specs.yaml
> +- dockerImage: "airbyte/source-amazon-ads:0.1.28"
you don't need to bump version here, it's done automatically by publishing scripts

2023-01-20 09:20 UTC, grubberr commented on airbyte-config/init/src/main/resources/seed/source_specs.yaml
> +        look_back_window:
you don't need to touch this file, it's done automatically by publishing scripts

2023-01-20 09:22 UTC, grubberr approved these changes

2023-01-20 09:23 UTC, grubberr commented
@dandpz I have approved
but revert changes on `source_specs.yaml` and `source_definitions.yaml`
this files updated automatically

2023-01-20 09:24 UTC, grubberr commented
/test connector=connectors/source-amazon-ads

2023-01-20 09:25 UTC, dandpz commented
> @dandpz I have approved but revert changes on `source_specs.yaml` and `source_definitions.yaml` this files updated automatically

Ok, I am reverting them, sorry I wasn't aware of the automatic update of the files

2023-01-20 09:27 UTC, grubberr commented
@YowanR @lazebnyi new config parameter was introduced to the source-amazon-ads GA connector can you please look?

2023-01-20 09:33 UTC, grubberr requested changes
sorry I missed this

can you please pre-load default value 
like did here for "region"

https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/source.py#L52

2023-01-20 09:34 UTC, grubberr commented
@dandpz please fully revert `source_specs.yaml` not only version.
it's updated automatically

2023-01-20 09:56 UTC, grubberr commented on airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/streams/report_streams/report_streams.py
> +        self._look_back_window: int = config.get("look_back_window")
because `look_back_window` not optional can you please 
change `config['look_back_window']`
?

2023-01-20 10:17 UTC, grubberr approved these changes

2023-01-20 10:17 UTC, grubberr commented
/test connector=connectors/source-amazon-ads

2023-01-20 11:03 UTC, grubberr commented
@dandpz it seems unit-tests failed

2023-01-20 11:03 UTC, grubberr requested changes
it seems unit-tests failed

2023-01-20 11:48 UTC, grubberr commented
/test connector=connectors/source-amazon-ads

2023-01-20 14:19 UTC, grubberr approved these changes

2023-01-26 16:36 UTC, marcosmarxm commented
/publish connector=connectors/source-amazon-ads

2023-01-27 09:03 UTC, merged