dbt Cloud integration doc
airbytehq/airbyte pull request #19619
Opened 2022-11-18 21:20 UTC by sophia-wiley

dbt Cloud integration doc

2022-11-18 22:42 UTC, mfsiega-airbyte approved these changes
LGTM!

2022-11-21 16:45 UTC, ambirdsall approved these changes

2022-11-21 20:45 UTC, Amruta-Ranade requested changes

2022-11-21 20:45 UTC, Amruta-Ranade commented on docs/cloud/dbt-cloud-integration.md
> +## Step 1: Prerequisites
Change "Step 1: Prerequisites" > "Step 1: Generate a service token"

2022-11-21 20:45 UTC, Amruta-Ranade commented on docs/cloud/dbt-cloud-integration.md
> +### Generate a service token
Delete "### Generate a service token"

2022-11-21 20:45 UTC, Amruta-Ranade commented on docs/cloud/dbt-cloud-integration.md
> +To generate a service token:
Do they have instructions on generating a service token? If yes, delete this step and add a prerequisite linking to their official instructions.

2022-11-21 20:45 UTC, Amruta-Ranade commented on docs/cloud/dbt-cloud-integration.md
> +1. On the Airbyte Cloud dashboard, click **Settings** in the navigation bar.
Add a new line between lead sentence and first step

2022-11-21 20:45 UTC, Amruta-Ranade commented on docs/cloud/dbt-cloud-integration.md
> +1. On the Airbyte Cloud dashboard, click **Settings** in the navigation bar.
Delete "in the navigation bar"

2022-11-21 20:45 UTC, Amruta-Ranade commented on docs/cloud/dbt-cloud-integration.md
> +2. In the **Settings** sidebar, click **dbt Cloud integration**.
Delete "In the Settings sidebar"

2022-11-21 20:45 UTC, Amruta-Ranade commented on docs/cloud/dbt-cloud-integration.md
> +4. Click **Connections** in the navigation bar and select the connection you want to add a dbt transformation to.
Delete "in the navigation bar"

2022-11-21 20:45 UTC, Amruta-Ranade commented on docs/cloud/dbt-cloud-integration.md
> +6. Select the transformation from the dropdown and save the changes. The transformation will run during the subsequent syncs until you remove it.
"save the changes" -- how? Click Save?

2022-11-21 20:45 UTC, Amruta-Ranade commented on docs/cloud/dbt-cloud-integration.md
> +8. To remove a transformation, click **X** on the transformation and save the changes.
Same comment as above

2022-11-21 21:51 UTC, Amruta-Ranade approved these changes

2022-11-21 21:52 UTC, merged