Stripe: expand tiers when syncing plans
airbytehq/airbyte pull request #19906
Opened 2022-11-29 23:30 UTC by visnup

## What
Fixes #19905 

## How
Includes the [tiers property](https://stripe.com/docs/api/prices/object#price_object-tiers) when syncing plans.

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

2022-11-29 23:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=19906) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=19906) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=19906) it.</sub>

2022-11-30 01:21 UTC, visnup commented
I'm a new contributor, so unsure what tests I can add and have left this so far as a draft PR.

I set this up to run on our Airbyte EC2 instance and it seems to work.

2022-12-08 20:03 UTC, marcosmarxm commented
Sorry the delay @visnup I'm going to review your contribution!

2022-12-08 20:03 UTC, marcosmarxm commented
/test connector=connectors/source-stripe

2022-12-20 19:52 UTC, marcosmarxm commented
Hello :wave::skin-tone-2: and thank you for your contribution!

Airbyte has instituted a code freeze between 19 and 30 December, to make sure there are no disruptions during the holidays. 
Because of this, reviewing and merging your contribution may take longer than usual. 
We apologize for the delay, but we want everyone to have a quiet and happy holiday.

If you have any questions or need further clarification, please don't hesitate to ping via Slack.

2023-01-19 01:24 UTC, visnup commented
Ping on this PR. I think it's decently simple? Let me know if I can move it along.

2023-02-06 20:03 UTC, sashei commented
Ping - would appreciate having this functionality as well. Cross-posting to Slack.

2023-02-07 10:37 UTC, marcosmarxm commented
Sorry the long-long-long delay to get this merge @visnup and @sashei. 
@sh4sh can you take a look here?

2023-02-07 10:37 UTC, marcosmarxm commented
/test connector=connectors/source-stripe

2023-02-07 10:44 UTC, marcosmarxm commented
/test connector=connectors/source-stripe

2023-02-07 10:47 UTC, marcosmarxm commented
@supertopher there was a change to run tests in community PRs? Seeing this error: https://github.com/airbytehq/airbyte/actions/runs/4113048675/jobs/7098711577

2023-02-08 00:23 UTC, sh4sh commented
The [failing check](https://github.com/airbytehq/airbyte/actions/runs/4119260873/jobs/7112719921) is due to some changes in how acceptance tests are configured. We've started implementing high-strictness acceptance testing for GA connectors: https://docs.airbyte.com/connector-development/testing-connectors/connector-acceptance-tests-reference/#strictness-level

We also need an approving review from @airbytehq/gl-python

2023-02-08 08:24 UTC, davydov-d requested changes
Also, please bump the connector version in the Dockerfile and add a record to the changelog. Thanks!

2023-02-08 08:24 UTC, davydov-d commented on airbyte-integrations/connectors/source-stripe/source_stripe/streams.py
> +        params["expand[]"] = ["data.tiers"]
Could you please reflect this change in the stream schema as well? As far as I understand, it does not correspond to the docs. (at least 2 fields missing)

2023-02-10 00:51 UTC, bazarnov approved these changes

2023-02-10 08:16 UTC, davydov-d approved these changes

2023-03-02 19:39 UTC, visnup commented
Is there anything else I should do here?

2023-03-03 08:02 UTC, davydov-d commented
@visnup the master branch has been updated, could you please merge it into your branch and resolve the conflicts?
afterwards, we'll fix the build and then we'll be able to proceed with your PR. Thanks!

2023-03-09 13:34 UTC, davydov-d commented
hey @marcosmarxm can you please proceed with this PR? it needs the changelog to be updated. The build should be fixed this week I believe, then it can be published and merged

2023-03-10 18:48 UTC, sh4sh commented
Everything is passing except changelog, @visnup could you add a new changelog entry for v3.1.0? I tried to add it but i don't have push access to your repo.

2023-03-13 20:40 UTC, sh4sh commented
/publish connector=connectors/source-stripe

2023-03-13 21:28 UTC, sh4sh commented
The connector is now published, but I needed to bump connector versions in https://github.com/airbytehq/airbyte/pull/23941. Once we get an approving review, it will be merged in that pr.

2023-04-07 14:14 UTC, marcosmarxm commented
This has been published one month ago. My recommentation is to delete the tag in Dockerhub and republish the connector again.

2023-04-11 20:26 UTC, marcosmarxm commented
/publish connector=connectors/source-stripe

2023-04-12 15:26 UTC, merged