Enable full SAT for the Snowflake source
airbytehq/airbyte pull request #20138
Opened 2022-12-06 15:01 UTC by DoNotPanicUA

## What
Enable SAT for the Snowflake source

## Configured test instances
- sat_test_dataset

## Found issues
SAT related issues:
- The source returns time data with milliseconds, but the SAT treats this as a type violation.
- The SAT fails when face non-typical values like `Nan`, `+inf` or `-inf`

2022-12-06 15:02 UTC, DoNotPanicUA commented
/test connector=connectors/source-snowflake

2022-12-06 16:34 UTC, alafanechere requested changes

2022-12-06 16:34 UTC, alafanechere commented on airbyte-integrations/connectors/source-snowflake/acceptance-test-config.yml
> +  connection:
Please use the latest acceptance-test-config format. [Example here.](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-zendesk-support/acceptance-test-config.yml#L1). I'd be curious to check the test output under `high` test strictness level, we might get this for free 😄

2022-12-07 14:40 UTC, DoNotPanicUA commented
/test connector=connectors/source-snowflake

2022-12-07 14:42 UTC, alafanechere commented on airbyte-integrations/connectors/source-snowflake/acceptance-test-config.yml
> +acceptance_tests:
```suggestion
test_strictness_level: high
acceptance_tests:
```
I'd be curious to check the test output under high test strictness level, we might get this for free.

2022-12-07 15:06 UTC, DoNotPanicUA commented
@alafanechere 
The CI run fails with the new format, but the local pass is fine.
![Screenshot from 2022-12-07 17-05-27](https://user-images.githubusercontent.com/30464745/206215030-b270f5d7-4220-4cd4-82d8-a0be035f3ad2.png)
any ideas on how to fix it?

2022-12-07 15:11 UTC, alafanechere commented
> any ideas on how to fix it? 
I think you spotted a bug in my latest PR: https://github.com/airbytehq/airbyte/pull/20076
I'm going to take a look.

2022-12-07 15:13 UTC, alafanechere commented
/test connector=connectors/source-snowflake

2022-12-07 15:21 UTC, DoNotPanicUA commented
@alafanechere 
Looks like we can't set the strictness level as High because it requires the future cursor check.
This check doesn't work for the java sources because they use the old State massage handler, and it requires more deep investigation with the significant refactoring of the JDBC sources.

2022-12-07 15:23 UTC, alafanechere commented
> Looks like we can't set the strictness level as High because it requires the future cursor check.
This check doesn't work for the java sources because they use the old State massage handler, and it requires more deep investigation with the significant refactoring of the JDBC sources.

It makes sense, thank you for trying!

2022-12-07 15:30 UTC, DoNotPanicUA commented
/test connector=connectors/source-snowflake

2022-12-07 16:18 UTC, alafanechere requested changes
Requesting changes for the reasons explained here: https://github.com/airbytehq/airbyte/pull/19915#discussion_r1042325573

2022-12-07 21:04 UTC, alafanechere approved these changes

2022-12-08 11:55 UTC, merged