Update keyword_report in Google ads source
airbytehq/airbyte pull request #20175
Opened 2022-12-07 01:06 UTC by LuliRib

adding segments.date field to keyword_report. 

Tests succedded + Google ads response in pr#20005

2022-12-07 08:57 UTC, LuliRib commented
@marcosmarxm Good morning! This is thenew branch with the google ads field added to keyword_report schema.
As it´s a new branch, the tests don´t appear here.. but in #20005

2022-12-07 14:12 UTC, LuliRib commented
@sh4sh, hi, maybe you can help me. I was asked to open this new branch. The google ads test passed ok in the other branch..

2022-12-07 16:30 UTC, marcosmarxm commented
/test connector=connectors/source-google-ads

2022-12-07 16:30 UTC, marcosmarxm commented
@grubberr can you validate this change removing one field from Google Ads to add other?

2022-12-08 13:08 UTC, marcosmarxm requested changes

2022-12-08 13:08 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-google-ads/source_google_ads/schemas/keyword_report.json
> +    }
@LuliRib it is missing a comman and breaking the tests.
```suggestion
    },
```

2022-12-08 13:21 UTC, LuliRib commented
Changed. Can you pls re-test?

2022-12-08 17:24 UTC, marcosmarxm commented
@grubberr can you check this change for Google Ads?

2022-12-09 13:27 UTC, LuliRib commented
@marcosmarxm hi, is there any way to move forward with it?

2022-12-12 15:55 UTC, LuliRib commented
@marcosmarxm Hi

2022-12-20 15:02 UTC, LuliRib commented
Hi, any way to move forward with it?

2022-12-20 19:52 UTC, marcosmarxm commented
Hello :wave::skin-tone-2: and thank you for your contribution!

Airbyte has instituted a code freeze between 19 and 30 December, to make sure there are no disruptions during the holidays. 
Because of this, reviewing and merging your contribution may take longer than usual. 
We apologize for the delay, but we want everyone to have a quiet and happy holiday.

If you have any questions or need further clarification, please don't hesitate to ping via Slack.

2023-03-07 20:58 UTC, sh4sh commented
/test connector=connectors/source-google-ads

2023-04-14 15:28 UTC, sajarin commented
/test connector=connectors/source-google-ads

2023-04-14 16:27 UTC, sajarin commented
@grubberr can you approve this PR, it's a schema update for the Google Ads connector.

2023-04-14 16:27 UTC, sajarin approved these changes

2023-04-25 13:55 UTC, marcosmarxm commented
/test connector=connectors/source-google-ads

2023-05-05 09:05 UTC, lazebnyi requested changes
@LuliRib @marcosmarxm I'm having trouble understanding why we need to replace `metrics.historical_quality_score` with `segments.device` and trigger a breacking changes. If we require additional fields that are incompatible with the fields already in the schema, we can use the` custom_queries` field in the configuration to obtain what we need.

2023-05-08 21:48 UTC, marcosmarxm commented
@lazebnyi overall I think segments.device is more valuable info than metric quality score. But @LuliRib probably has a better argument than mine.

2023-05-09 16:07 UTC, LuliRib commented
Hi all, the problem is that those 2 fields are not compatible (can check it in the query builder).
I think the metrics.device is more valuable.


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Marcos Marx ***@***.***>
Sent: Tuesday, May 9, 2023 11:08:20 AM
To: airbytehq/airbyte ***@***.***>
Cc: Laila R. ***@***.***>; Mention ***@***.***>
Subject: Re: [airbytehq/airbyte] Source Google Ads: add `segments.device` and remove `metrics.historical_quality_score` from `keyword_report` (PR #20175)


@lazebnyi<https://github.com/lazebnyi> overall I think segments.device is more valuable info than metric quality score. But @LuliRib<https://github.com/LuliRib> probably has a better argument than mine.

—
Reply to this email directly, view it on GitHub<https://github.com/airbytehq/airbyte/pull/20175#issuecomment-1539098177>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ARUVBWRSWGB2KSVDG4FI4H3XFICQJANCNFSM6AAAAAASWF5S3Y>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-05-30 13:31 UTC, closed without merging