New Source: Commcare
airbytehq/airbyte pull request #20220
Opened 2022-12-08 05:59 UTC by siddhant3030

## What

Commcare is a digital data collection platform for front-line workers working in offline settings. For organizations using Commcare having a native Airbyte connector to import data will allow for ingestion into their data warehouses and use of the data for analysis. Current processes involve ingestion with Python scripts, maintaining schemas ad-hoc in the scripts, and through Excel downloads.

## How

The current version of the connector provides for ingesting data through Airbyte from multiple forms in an organization's Commcare application. A typical use case of a Commcare system involves a root project space in which multiple applications can be hosted and can be defined for multiple program interventions. The current connector defines the ingestion of data at the application level as that is the most common entry point for Commcare Applications. The implemented version of the connector will allow for all sync modes - full refresh and incremental including de-duped mode. A best-guess normalization is also provided to ease the normalization process using a couple of python libraries to guess the schema from the data fetched back through the API.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

2022-12-08 18:22 UTC, geekwhocodes commented
@sajarin I can review this PR.

2022-12-12 06:36 UTC, siddhant3030 commented
<img width="1085" alt="Screenshot 2022-12-12 at 11 58 57 AM" src="https://user-images.githubusercontent.com/9019958/206977428-4cd0029b-c79a-47c7-ad60-5275906215ce.png">

Flake check

2022-12-13 10:10 UTC, geekwhocodes commented
Hi @siddhant3030, Thanks for your amazing contribution! 
Could you please delete unused files?
- source-commcare\source_commcare\schemas\TODO.md
- source-commcare\sample_files

Also, can you upload a screenshot of `integration tests`?

It would be good if you move custom classes to separate file/s.

2022-12-13 17:29 UTC, sajarin commented
@siddhant3030 can you respond to the requested changes ASAP? Thanks!

2022-12-14 11:18 UTC, geekwhocodes requested changes

2022-12-14 16:42 UTC, siddhant3030 commented
@geekwhocodes Thank you for the suggestions. I'll work on this. Also we are fixing the acceptance test. As soon as we're done we can let you know. I'll also add the screenshot.

2022-12-15 11:27 UTC, sajarin commented
@siddhant3030 any update here? We're trying to get this merged before the end of the week. Otherwise, the merging might be significantly delayed due to the holidays. We're fairly close to finishing the review here.

2022-12-15 12:31 UTC, siddhant3030 commented on airbyte-integrations/connectors/source-commcare/source_commcare/source.py
> +class Form(IncrementalStream):
what are doc strings ?

2022-12-15 12:31 UTC, siddhant3030 commented
@sajarin will try to push this today

2022-12-16 11:58 UTC, sajarin commented
@siddhant3030 any update here? Trying to get this merged by EOD today. Let me know if you need help with the requested changes.

2022-12-16 18:20 UTC, siddhant3030 commented
@sajarin We are working on some config changes and making it more general to use this connector. We will let you know latest by Monday. Thankyou for your replies.

2022-12-20 10:05 UTC, siddhant3030 commented on airbyte-integrations/connectors/source-commcare/source_commcare/source.py
> +            # print("Returning No")
done

2022-12-20 10:09 UTC, siddhant3030 commented on airbyte-integrations/connectors/source-commcare/source_commcare/source.py
> +        form_args = {**args, "app_id": config["app_id"], "start_date": config["start_date"]}
done

2022-12-20 10:09 UTC, siddhant3030 commented on airbyte-integrations/connectors/source-commcare/source_commcare/source.py
> +        stream = Case(**args, app_id=config["app_id"], start_date=config["start_date"], schema=self.empty_schema())
done

2022-12-20 10:21 UTC, siddhant3030 commented on airbyte-integrations/connectors/source-commcare/source_commcare/source.py
> +            stream = Form(**form_args, name=k, xmlns=key, schema=self.empty_schema())
done

2022-12-20 10:22 UTC, siddhant3030 commented on airbyte-integrations/connectors/source-commcare/source_commcare/source.py
> +                # print(frec)
done

2022-12-20 13:16 UTC, siddhant3030 commented on airbyte-integrations/connectors/source-commcare/source_commcare/source.py
> +class Application(CommcareStream):
done

2022-12-20 13:16 UTC, siddhant3030 commented on airbyte-integrations/connectors/source-commcare/source_commcare/source.py
> +class Case(IncrementalStream):
done

2022-12-20 13:17 UTC, siddhant3030 commented
@geekwhocodes @sajarin can you help me with this? This is the only test case which is failing in acceptance test

<img width="1085" alt="Screenshot 2022-12-12 at 11 58 57 AM" src="https://user-images.githubusercontent.com/9019958/208676189-9b5afc96-3582-4705-82af-1bfc0176ac03.png">

2022-12-20 19:52 UTC, marcosmarxm commented
Hello :wave::skin-tone-2: and thank you for your contribution!

Airbyte has instituted a code freeze between 19 and 30 December, to make sure there are no disruptions during the holidays. 
Because of this, reviewing and merging your contribution may take longer than usual. 
We apologize for the delay, but we want everyone to have a quiet and happy holiday.

If you have any questions or need further clarification, please don't hesitate to ping via Slack.

2023-01-05 04:16 UTC, siddhant3030 commented
@geekwhocodes @sajarin any updates on this? Needed your help the acceptance this. I have posted the query above

2023-01-05 18:55 UTC, sajarin approved these changes

2023-01-05 18:56 UTC, sajarin commented
/publish connector=connectors/source-commcare run-tests=false

2023-01-05 19:25 UTC, merged