fix(python-cdk): convert expires_in to int when refreshing oauth
airbytehq/airbyte pull request #20301
Opened 2022-12-09 13:28 UTC by joelluijmes

## What
Converts expires_in to int when refreshing during oauth refresh. Some oauth providers return the expires_in as a string in the returned json. 

```
{
    "access_token": "....",
    "refresh_token": "....",
    "expires_in": "600",
}
```

Currently this is silently ignored, but when the expire date is calculated a type error is raised.

```
File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 27, in get_auth_header
    return {"Authorization": f"Bearer {self.get_access_token()}"}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/oauth.py", line 195, in get_access_token
    self.set_token_expiry_date(t0.add(seconds=access_token_expires_in))
  File "/usr/local/lib/python3.9/site-packages/pendulum/datetime.py", line 632, in add
    dt = add_duration(
  File "/usr/local/lib/python3.9/site-packages/pendulum/helpers.py", line 113, in add_duration
    if abs(seconds) > 59:
TypeError: bad operand type for abs(): 'str'
```

## How
Always parse the value as int

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
No, it un-breaks 🤓 

## Pre-merge Checklist
Checklists seems redundant for this change

- [x] updated unit tests

2022-12-09 13:28 UTC, joelluijmes commented on airbyte-cdk/python/unit_tests/sources/streams/http/requests_native_auth/test_requests_native_auth.py
> +
Expanded the unit tests with another assertion. Not sure if this is conventional in Airbyte repo, or new test should be added. LMK.

2022-12-09 13:37 UTC, joelluijmes commented
Also, I only updated the `requests_native_auth` classes. As the [other version](airbyte-cdk/python/airbyte_cdk/sources/streams/http/auth/oauth.py) is already marked deprecated.

2022-12-09 18:02 UTC, marcosmarxm requested changes

2022-12-09 18:05 UTC, joelluijmes commented on airbyte-cdk/python/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py
> +            return response_json[self.get_access_token_name()], int(response_json[self.get_expires_in_name()])
`get_expires_in_name` only returns the name of the field in the response, which defaults to `expires_in`. It's not actually a function which parses the value.

Or are you suggesting to refactor the oauth classes to work in such way?

2022-12-09 18:14 UTC, marcosmarxm commented on airbyte-cdk/python/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py
> +            return response_json[self.get_access_token_name()], int(response_json[self.get_expires_in_name()])
Oh I missed that :ops:

2022-12-09 19:34 UTC, girarda approved these changes
lgtm! :shipit:

2022-12-09 23:29 UTC, brianjlai approved these changes

2022-12-12 19:00 UTC, marcosmarxm approved these changes

2022-12-20 19:52 UTC, marcosmarxm commented
Hello :wave::skin-tone-2: and thank you for your contribution!

Airbyte has instituted a code freeze between 19 and 30 December, to make sure there are no disruptions during the holidays. 
Because of this, reviewing and merging your contribution may take longer than usual. 
We apologize for the delay, but we want everyone to have a quiet and happy holiday.

If you have any questions or need further clarification, please don't hesitate to ping via Slack.

2023-02-06 13:15 UTC, joelluijmes commented
This PR has been approved, is there something else I need to do before we can get this merged? 😇

2023-03-08 14:38 UTC, joelluijmes commented
Updated with master again. Would be great if this can be merged 😇

2023-03-09 21:46 UTC, merged

2023-03-10 01:11 UTC, sherifnada commented
@joelluijmes i had to revert this PR due to unit test failures. It will be re-merged as part of https://github.com/airbytehq/airbyte/pull/20301