Utilize React-Lazy for Code Splitting
airbytehq/airbyte pull request #20605
Opened 2022-12-16 19:58 UTC by krishnaglick

## What
Resolves #20604

## How
Implements some top-level react-lazy usage, as well as a little deeper in the tree. Still room to improve.
Here's the lighthouse result.

![Screenshot 2022-12-16 at 2 57 29 PM](https://user-images.githubusercontent.com/4967694/208178834-8bbf33be-897e-4049-992e-412be86380c7.png)

2022-12-19 19:07 UTC, krishnaglick commented on airbyte-webapp/src/pages/routes.tsx
> +const ConnectionPage = React.lazy(() => import("./ConnectionPage"));
No! I've gone ahead and done a Cloud pass too :)

2023-01-04 09:35 UTC, josephkmh requested changes
The code changes look good, I just made a few small comments mostly about syntax.

I am wondering whether this change will have the desired impact. Code splitting strictly along routes means smaller JS bundle chunks at the cost of more network requests. This means route changes that currently load "instantly" (because the JS chunk was loaded on the initial page load) will now potentially show a loading spinner until all their JS dependencies are loaded over the network. This type of optimization is generally good when you want to optimize for quick individual page loads (e.g. for SEO/inbound traffic from search), but I'm not sure if this is what we really want to optimize for in Airbyte. I don't feel too strongly either way currently, but I wanted to call it out. Is this tradeoff something you considered?

Could you maybe add a comparison of the lighthouse scores before and after so we can understand the net change that code splitting is having on initial page loads? This is probably most relevant for both the login page and the first page load (`AllConnectionsPage.tsx`)

2023-01-04 09:35 UTC, josephkmh commented on airbyte-webapp/src/pages/destination/AllDestinationsPage/index.tsx
> +export default AllDestinationsPage;
Could we just do the default export here? I don't think we need the named one at all.

2023-01-04 09:35 UTC, josephkmh commented on airbyte-webapp/src/pages/destination/DestinationItemPage/index.tsx
> +export default DestinationItemPage;
Same here, I think we only need the default export

2023-01-04 09:35 UTC, josephkmh commented on airbyte-webapp/src/pages/destination/DestinationSettingsPage/index.ts
> +export default DestinationSettingsPage;
Same here, I think we only need the default export

2023-01-04 09:35 UTC, josephkmh commented on airbyte-webapp/src/packages/cloud/views/auth/LoginPage/index.tsx
> +export default LoginPage;
nitpick: these default exports could all be one-liners:

```ts
export { LoginPage as default } from "./LoginPage";
```

2023-01-04 09:35 UTC, josephkmh commented on airbyte-webapp/src/components/ui/DatePicker/index.ts
> +export default React.lazy(() => import("./DatePicker"));
Could we just export this normally here, and defer the lazy import to the consumer?

2023-01-04 20:39 UTC, krishnaglick commented
> The code changes look good, I just made a few small comments mostly about syntax.
> 
> I am wondering whether this change will have the desired impact. Code splitting strictly along routes means smaller JS bundle chunks at the cost of more network requests. This means route changes that currently load "instantly" (because the JS chunk was loaded on the initial page load) will now potentially show a loading spinner until all their JS dependencies are loaded over the network. This type of optimization is generally good when you want to optimize for quick individual page loads (e.g. for SEO/inbound traffic from search), but I'm not sure if this is what we really want to optimize for in Airbyte. I don't feel too strongly either way currently, but I wanted to call it out. Is this tradeoff something you considered?
> 
> Could you maybe add a comparison of the lighthouse scores before and after so we can understand the net change that code splitting is having on initial page loads? This is probably most relevant for both the login page and the first page load (`AllConnectionsPage.tsx`)

![Screenshot 2023-01-04 at 3 35 31 PM](https://user-images.githubusercontent.com/4967694/210645006-135e1f5f-a6d5-41d6-9d0d-b1c951ea0d49.png)

![Screenshot 2023-01-04 at 3 35 05 PM](https://user-images.githubusercontent.com/4967694/210644984-5a6cf32f-87a7-4baf-95bd-5c76675d1b1a.png)

Current master vs this branch. A 7 point increase is pretty nice imo.
I'm aware this will increase load times when navigating around but the goal of this batch of work is to improve first-load times. Splitting out the routing like this does accomplish that.

2023-01-04 22:16 UTC, josephkmh commented
Ok, I'm fine with these changes as long as we're aware of the tradeoffs 🙂 we can always look into preloading other chunks in the background or chunking some routes together later if that makes sense.

2023-01-04 22:17 UTC, josephkmh approved these changes

2023-01-05 14:54 UTC, merged