Update form field labels in connection form to match design
airbytehq/airbyte pull request #21036
Opened 2023-01-04 20:43 UTC by matter-q

## What
Closes [#19900](https://github.com/airbytehq/airbyte/issues/19900)

## How
Replaced ControlLabels message property with infoTooltipContent

_For test purposes, use the environment variable:_ REACT_APP_NEW_STREAMS_TABLE=true

[Figma design ](https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=874%3A35099&scaling=min-zoom&page-id=857%3A24319&starting-point-node-id=857%3A25233&show-proto-sidebar=1)

## Loom
https://www.loom.com/share/ea52bb672849427e91a2d72b603f40ce

2023-01-05 12:25 UTC, YatsukBogdan1 approved these changes
looks good to me

2023-01-05 14:45 UTC, edmundito commented
@matter-q from looking at the changes, the namespace/stream name prefix fields also need to be updated so that they are consistent with the current table.

2023-01-05 15:30 UTC, matter-q commented
> @matter-q from looking at the changes, the namespace/stream name prefix fields also need to be updated so that they are consistent with the current table.

I didn't quite understand what needed to be updated... 
Could you be more specific?

2023-01-05 17:56 UTC, edmundito commented
When the new streams table feature is disabled, there are more fields.

Also, while creating a new connection, there are extra name and data residency fields. Here's what it looks like from the new connection page:

![image](https://user-images.githubusercontent.com/168664/210847552-88bc9a07-bb51-4458-a321-3c54524b7e80.png)

Also, the vertical alignment of the items should be centered but it is not:
![image](https://user-images.githubusercontent.com/168664/210848008-5225a30a-c959-4bf9-be46-646c3c7bbdfa.png)

2023-01-09 15:37 UTC, edmundito reviewed
The changes look good, and tested locally. There is one more thing in terms of how the fields are presented in the new design. Required fields no longer need the `*` next to it and instead the optional fields are marked as `optional` (there is a prop in the ControlLabels to do this). Here's an example with the Destination Stream Prefix:

![Screen Shot 2023-01-09 at 10 36 10](https://user-images.githubusercontent.com/168664/211346732-e7afc1d3-c02d-455e-8155-4562db15cc99.png)

2023-01-10 19:28 UTC, edmundito requested changes
Tested locally, but noticed one small thing...

2023-01-10 19:28 UTC, edmundito commented on airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionFormFields.tsx
> +                        optional
Not optional

```suggestion
```

2023-01-10 21:27 UTC, edmundito commented
Sorry, just tested the cloud version and noticed a couple of things on the connection settings page:

![image](https://user-images.githubusercontent.com/168664/211665336-e809929b-118a-414b-8cf2-b2f094daf2e0.png)

1. The tooltip should now use the "learn more" link for tooltips: https://63053d1047904393cf8d8faa-hpmeogsbgz.chromatic.com/?path=/story/ui-tooltip--with-learn-more-url
2. The spacing between the label and the dropdown needs to be adjusted. The dropdown now takes whatever is left of the card, but it should be a specific size (300px) and looks like removing the description broke the layout

2023-01-11 13:48 UTC, edmundito approved these changes

2023-01-11 14:01 UTC, merged