Shady Faker (example of a connector which calls an untrusted URL)
airbytehq/airbyte pull request #21180
Opened 2023-01-10 00:41 UTC by evantahler

### This PR SHOULD NEVER BE MERGED

This PR demonstrates a connector being modified to call a remote URL at boot, demonstrating that it has access to the filesystem and contents of `secrets.json`.

This version of the connector is published as `source-faker#shady` via the command:
```
```

The URL which this connector sends information to is `echo.evantahler.com`, run by @evantahler.  The codebase for this server is here: https://github.com/evantahler/echo-server.

2023-01-10 00:43 UTC, evantahler commented
The echo server stores the last 1000 messages it receives in redis.  These messages can be viewed by visiting https://echo.evantahler.com

<img width="1719" alt="Screenshot 2023-01-09 at 4 37 26 PM" src="https://user-images.githubusercontent.com/303226/211436363-47ba4a09-1e6a-48dd-a448-1aba9765b6d2.png">

2023-01-10 01:19 UTC, evantahler commented
@davinchia in lieu of a PR review, can you comment if you think the test plan outlined here is sufficient?

2023-01-13 19:26 UTC, pedroslopez requested changes
👍🏻 ack - commenting to acknowledge the review request but definitely shouldn't merge 😄

2023-01-16 17:32 UTC, davinchia commented
@evantahler yes this is a decent sanity check. A sophisticated attacker can bypass this with DNS hijacking. The risk of that is low given we primary rely on Google's network (both for DNS servers and to route requests). Def good enough to check that request are routing to what 'we think' is the right endpoint.

2023-04-28 01:02 UTC, davinchia commented
I'm closing this to clean up PRs.

2023-04-28 01:02 UTC, closed without merging