Suggested Streams
airbytehq/airbyte pull request #21437
Opened 2023-01-13 23:55 UTC by evantahler

Closes https://github.com/airbytehq/airbyte/issues/10872 

This PR allows connectors to suggest which streams are selected for users creating a new connection.  

For many of our API sources, Airbyte provides *a lot* of streams, because Airbyte is great.  But, most users probably don't want to wait for / pay for all of that data.  In fact, sometimes the inclusion of a particular stream can dramatically slow down the sync for all steams.  Maybe this stream has a slower API or consumes more API "credits" or hurts the rate limit.   

This PR allows us to tune the default stream selections to provide a better first-time sync experience.  

> The Convenience Principle: People will do what's convenient, and they will avoid what's inconvenient. All else being equal, to increase how many people do something, make it more convenient, and to decrease, make it less convenient
> - @sherifnada

2023-01-14 00:04 UTC, evantahler commented on airbyte-integrations/connectors/source-github/source_github/streams.py
> +
This is all it takes to demote a CDK stream to un-suggested.

2023-01-14 00:04 UTC, evantahler commented on airbyte-server/src/main/java/io/airbyte/server/handlers/helpers/CatalogConverter.java
> +    }
There's probably a better ☕ way to do this... Also, the difference between protocol models and api models was confusing.

2023-01-16 00:50 UTC, sherifnada requested changes
exciting! LGTM minus one request about naming

2023-01-16 00:50 UTC, sherifnada commented on airbyte-protocol/protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml
> +      suggested:
naming nitpick: can we call it `sync_by_default` or `enabled_by_default`? makes the name more self explanatory

2023-01-19 02:31 UTC, evantahler commented
Closing in favor of https://github.com/airbytehq/airbyte/pull/21577, which moves the storage of SuggestedStreams to the Actor Definition

2023-01-19 02:31 UTC, closed without merging