Source Google Search Console: enable `high` test strictness level in SAT
airbytehq/airbyte pull request #21503
Opened 2023-01-17 22:46 UTC by lazebnyi

https://github.com/airbytehq/airbyte/issues/19044
SAT high strictness

2023-01-17 22:47 UTC, lazebnyi commented
/test connector=connectors/source-google-search-console

2023-01-17 23:59 UTC, evantahler commented
My review is pending the results of [this slack converstation](https://airbytehq-team.slack.com/archives/C04G4ST1ZB7/p1673999887742139).  These records look like real ad data for Airbyte, which may be sensitive information.

2023-01-18 16:40 UTC, evantahler requested changes
Rejecting as expected_records contains sensitive data.

I think the path forward here is, sadly, to bypass the stream's acceptance test.  It seems like too big of a lift at the moment to spin up a test website and run ads pointing at it...

cc @alafanechere

2023-01-18 21:24 UTC, lazebnyi commented
/test connector=connectors/source-google-search-console

2023-01-18 23:25 UTC, evantahler reviewed
```
{"stream": "search_analytics_by_page", "data": {"clicks": 22, "impressions": 760, "ctr": 0.02894736842105263, "position": 2.375, "site_url": "https://airbyte.io/", "search_type": "web", "date": "2021-09-14", "page": "https://airbyte.io/pricing"}, "emitted_at": 1673994671340}
```

Still might be protected business data - @Patsy-Airbyte and @YowanR to decide.

2023-01-19 13:52 UTC, lazebnyi commented
/test connector=connectors/source-google-search-console

2023-01-19 14:40 UTC, lazebnyi commented
/test connector=connectors/source-google-search-console

2023-01-19 21:41 UTC, evantahler commented
Swapping my review with @YowanR to decide on expected records being secret or not

2023-01-24 13:04 UTC, YowanR commented
@lazebnyi I just checked the expected_records. I would consider `"clicks": 22, "impressions": 760,` to be PIIs. Can we skip those? If not, I suggest that we skip enabling high test strictness for this one. I'm checking this with @Patsy-Airbyte and will get back to you on a final decision today.

2023-01-24 23:05 UTC, lazebnyi commented
/test connector=connectors/source-google-search-console

2023-01-24 23:23 UTC, lazebnyi commented
@YowanR From expected records deleted `clicks`, `impressions` and all fields connected with `country`, `website urls` or `type of devices`. Waiting your approve to merge PR.

2023-01-25 13:56 UTC, YowanR commented
Looking at `expected_records.jsonl`, the data now seems to be free of both PII and business sensitive information which is great! We should be able to proceed with the merge for now. In parallel, we should flag all these connectors to the Unblocker team so that we can look into creating richer samples without PIIs or Business sensitive info.
I'm curious --  what is the impact of reducing the records in `expected_records.jsonl`? Does it reduce our test coverage?
cc @evantahler

2023-01-25 13:56 UTC, YowanR approved these changes
LGTM!

2023-01-25 16:40 UTC, evantahler approved these changes

2023-01-25 16:40 UTC, evantahler commented on airbyte-integrations/connectors/source-google-search-console/acceptance-test-config.yml
>    incremental:
👍 no bypass reasons!

2023-01-25 16:40 UTC, evantahler commented on airbyte-integrations/connectors/source-google-search-console/integration_tests/expected_records.jsonl
> +{"stream": "search_analytics_by_date", "data": {"ctr": 0.07940251572327044, "position": 31.88456498951782, "search_type": "web", "date": "2021-09-14"}, "emitted_at": 1674600074364}
This data seems vague enough to be OK 👍.  Can you confirm that this is not data about www.airbute.com/www.airbute.io?

2023-01-25 16:43 UTC, merged