Source Jira: Small fix in the board stream
airbytehq/airbyte pull request #21524
Opened 2023-01-18 14:30 UTC by anamargaridarl

## What
Some boards don't have projects associated with them. Thus, some records don't have the fields inside the location dict. I created a fail-safe approach. 

## How
Use get instead. The project fields will be None if no project is available.

## Recommended reading order
1. streams.py

## 🚨 User Impact 🚨
Boards stream won't break

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

2023-01-25 17:49 UTC, marcosmarxm commented
/test connector=connectors/source-jira

2023-01-27 10:13 UTC, marcosmarxm commented
/test connector=connectors/source-jira

2023-01-27 10:17 UTC, marcosmarxm requested changes
Some comments. I started the tests to check if it will work.

2023-01-27 10:17 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-jira/source_jira/streams.py
> +            location = board["location"]
```suggestion
            location = board.get("location", {})
```
This at least won't break the code in any case.

2023-01-27 10:18 UTC, marcosmarxm requested changes
forget one suggestion

2023-01-27 10:18 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-jira/source_jira/streams.py
> +                record["projectKey"] = location.get("projectKey")
```suggestion
        location = record.get("location")
        if location:
            record["projectId"] = str(location.get("projectId"))
            record["projectKey"] = location.get("projectKey")
```

2023-01-27 15:25 UTC, anamargaridarl commented
Thank you for the review! I applied the changes requested @marcosmarxm

2023-02-27 21:54 UTC, Logicoeur commented
Bump. encountered this error too

2023-03-02 16:06 UTC, natalyjazzviolin commented
/test connector=connectors/source-jira

2023-03-02 21:13 UTC, natalyjazzviolin approved these changes
Looks good!

2023-03-02 21:23 UTC, marcosmarxm approved these changes

2023-03-02 22:32 UTC, merged

2023-04-03 06:18 UTC, quorak commented
Awesome fix. When can we expect a release?