Fixing bootloader not running migration on startup
airbytehq/airbyte pull request #21639
Opened 2023-01-20 09:52 UTC by lihan

RUN_DATABASE_MIGRATION_ON_STARTUP not passed to airbyte-bootloader Pod.

This caused the Airbyte upgrade not running at startup time

https://github.com/airbytehq/airbyte/issues/21638

2023-01-20 09:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=21639) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=21639) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=21639) it.</sub>

2023-01-20 14:46 UTC, xpuska513 approved these changes

2023-01-20 14:57 UTC, supertopher commented
![](https://media4.giphy.com/media/4vIfVmbQonId4YTpjI/giphy.gif?cid=ecf05e47nty39i4xpd75icslmxw1l0i3gn274wrqedijdn73&rid=giphy.gif&ct=g)

because secrets are secret we have to run integration tests on a branch of an employee.  

I'm running your test suite here.

Your changes look great to my eyes so far.  Thank you for taking the time to contribute back to airbyte.  

If the tests come back green, I'll approve/merge this.  If they don't we'll talk about what happened.

Thanks again @lihan :)

2023-03-21 15:07 UTC, xpuska513 requested changes

2023-03-21 15:07 UTC, xpuska513 commented on charts/airbyte-bootloader/templates/pod.yaml
> +              name: {{ .Values.global.configMapName | default (printf "%s-airbyte-env" .Release.Name) }}
Can you include this value to configmap?
Otherwise, the deployment will fail since this variable does not exist in the configmap itself.

2023-03-21 15:13 UTC, xpuska513 commented
Oh, wait the charts was moved to another repo, I'll copy the changes in that repo then and after it gets merged I'll notify you about it

2023-04-20 20:59 UTC, cgardens commented
Thanks @nightmareartist  and @xpuska513 . I'm going to close this PR since it was moved to the new repo.

2023-04-20 20:59 UTC, closed without merging