Low Code CDK: DpathExtractor extend
airbytehq/airbyte pull request #21690
Opened 2023-01-21 20:51 UTC by artem1205

## What
Parse responses with nested lists (see tests)

Complex response structure connectors:

1. [ChargeBee](https://github.com/airbytehq/airbyte/blob/96a2a18fb75bdd426aff265f253852fdf19a8e02/airbyte-integrations/connectors/source-chargebee/source_chargebee/components.py#L17-L57)
2. [Facebook Pages](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/components.py#L55-L97)
3. [Monday](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-monday/source_monday/dpath_string_extractor.py)

## How
Use dpath.util.values in DpathExtractor

## Recommended reading order
1. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

2023-01-24 05:40 UTC, sherifnada requested changes
Looks good! could you update the docs to describe how the `DpathExtractor` now works? specifically, we should tell users that `*` can be used to mean "for each element in the array"

2023-01-25 01:16 UTC, girarda approved these changes
🚢 🚢 🚢

2023-01-25 01:47 UTC, sherifnada approved these changes

2023-01-25 01:47 UTC, sherifnada commented on docs/connector-development/config-based/understanding-the-yaml-file/record-selector.md
> +### Selecting nested field
```suggestion
### Selecting fields nested in arrays 
```

2023-01-25 01:48 UTC, sherifnada approved these changes
Nice work!

2023-01-25 01:53 UTC, brianjlai approved these changes
@artem1205 changes look good to me. However, we've modified the release process of the `airbyte-cdk` package a little bit. 

We're starting the process a bit. Instead of writing the changelog and bumping the version, we use the "Publish CDK Manually" Github action point it towards your branch, your commit hash, and including the minor bump w/ the changelog message. If you don't have access, we can trigger the workflow once you remove your code on the `CHANGELOG.md` which will push a commit w/ the version bumps to your current branch

2023-01-25 10:57 UTC, artem1205 commented on docs/connector-development/config-based/understanding-the-yaml-file/record-selector.md
> +### Selecting nested field
updated

2023-01-25 11:23 UTC, artem1205 commented
@brianjlai , I've removed my code from the `CHANGELOG.md`.
As I understood, I need to merge this PR now, and then run the `Publish CDK Manually` Action?
![image](https://user-images.githubusercontent.com/36314070/214551051-a5353ee9-048c-4839-9cea-aded61b034c1.png)

2023-01-25 14:49 UTC, merged