Mark/long source and destination names make the connection list table scroll horizontally
airbytehq/airbyte pull request #21759
Opened 2023-01-23 23:55 UTC by matter-q

## What

Closes [#21274](https://github.com/airbytehq/airbyte/issues/21274)

## How

- Added responsive columns
- Created new cell components
- Removed styled-components
- Refactored Table component

_Note: This PR is a temporary solution that fixes some bugs for this moment before we can start using the new Table component_

## Loom
https://www.loom.com/share/a442f62c9dd1406691b7e4af19d89c40

2023-01-25 12:34 UTC, dizel852 commented on airbyte-webapp/src/components/ui/Table/Table.tsx
> +                    }}
The same question here

2023-01-25 12:44 UTC, dizel852 requested changes
Did a review: changes looks great 🔥 
Left some comments.
Also noticed some minor issues, would be great to fix them in scope o this PR:
1. `font-weight` is changed from `500` to `400`. By design - we need `500`. 
<img width="658" alt="Screenshot at Jan 25 14-37-31" src="https://user-images.githubusercontent.com/20929344/214566016-02a3b251-9008-4abd-944e-3aeee9e80c45.png">
<img width="671" alt="Screenshot at Jan 25 14-38-14" src="https://user-images.githubusercontent.com/20929344/214566059-cfdddd2a-5283-43b8-9961-bf9783b30f3d.png">

2. Status icon stretches:
<img width="274" alt="Screenshot at Jan 25 14-26-09" src="https://user-images.githubusercontent.com/20929344/214566449-98ba4763-8c83-4b13-9370-fe087a5b4095.png">
<img width="463" alt="Screenshot at Jan 25 14-25-52" src="https://user-images.githubusercontent.com/20929344/214566479-94e23543-6675-4c67-a70b-e4fd6cf77570.png">

2023-01-25 21:12 UTC, matter-q commented on airbyte-webapp/src/components/ui/Table/Table.tsx
> +                }}
Removed padding parameters since we do not use them at all

2023-01-26 15:14 UTC, matter-q commented
> Did a review: changes looks great 🔥 Left some comments. Also noticed some minor issues, would be great to fix them in scope o this PR:
> 
> 1. `font-weight` is changed from `500` to `400`. By design - we need `500`.
> 
> <img alt="Screenshot at Jan 25 14-37-31" width="658" src="https://user-images.githubusercontent.com/20929344/214566016-02a3b251-9008-4abd-944e-3aeee9e80c45.png">
> 
> <img alt="Screenshot at Jan 25 14-38-14" width="671" src="https://user-images.githubusercontent.com/20929344/214566059-cfdddd2a-5283-43b8-9961-bf9783b30f3d.png">
> 
> 2. Status icon stretches:
> 
> <img alt="Screenshot at Jan 25 14-26-09" width="274" src="https://user-images.githubusercontent.com/20929344/214566449-98ba4763-8c83-4b13-9370-fe087a5b4095.png">
> 
> <img alt="Screenshot at Jan 25 14-25-52" width="463" src="https://user-images.githubusercontent.com/20929344/214566479-94e23543-6675-4c67-a70b-e4fd6cf77570.png">

Thanks for the detailed review. Fixed with  font-weight 500 :wink:

2023-01-27 10:29 UTC, dizel852 approved these changes
LGTM 👍 

Passing to @edmundito and @tealjulia  for another review

@tealjulia I think you will be interested to look, since pretty close issue was created recently - https://github.com/airbytehq/airbyte/issues/21941

2023-01-27 15:34 UTC, edmundito approved these changes
Changes look good. Tested connections, sources, and destinations lists, and resized windows. Noted a couple of nits that may be nice to fix but no need for re-approval.

2023-01-27 15:34 UTC, edmundito commented on airbyte-webapp/src/components/EntityTable/components/ConnectionStatusCell.module.scss
> +$connector_icon_margin: 10px;
Nit: The convention is to use dash instead of underscore

2023-01-27 15:34 UTC, edmundito commented on airbyte-webapp/src/components/EntityTable/components/ConnectorNameCell.module.scss
> +$status_icon_width: 25px;
Same nit

2023-01-27 15:45 UTC, teallarson requested changes
Looks like there is a small visual regression on the Credits Page in the CreditConsumptionPerConnectionTable:

<img width="1392" alt="Screenshot 2023-01-27 at 10 44 15 AM" src="https://user-images.githubusercontent.com/63751206/215127471-2bd6c0d0-d269-40a3-916b-5f6c10c22e81.png">
(there is now a double card)

2023-01-27 15:45 UTC, tealjulia commented
> @tealjulia I think you will be interested to look, since pretty close issue was created recently - https://github.com/airbytehq/airbyte/issues/21941

This and the inconsistent header highlighting were the main two things I was getting at in that issue:
<img width="1398" alt="Screenshot 2023-01-27 at 10 42 52 AM" src="https://user-images.githubusercontent.com/63751206/215127118-be6cd17f-98b4-4894-a68a-b244336fbd8a.png">

2023-01-30 15:56 UTC, tealjulia approved these changes
Retested the credits and connections pages locally.  LGTM.

2023-01-30 17:27 UTC, merged