set new helm attribute
airbytehq/airbyte pull request #22114
Opened 2023-01-30 22:49 UTC by franviera92

I would like to set the following values with helm, I see that it can be set with kustomize but not with helm

2023-02-02 08:45 UTC, marcosmarxm commented
@xpuska513 can you review this contribution?

2023-02-02 08:46 UTC, marcosmarxm requested changes

2023-02-02 12:17 UTC, franviera92 commented on charts/airbyte/values.yaml
> +  activity_max_delay_between_attempts_seconds: ""
Ready man

2023-02-06 18:28 UTC, franviera92 commented on charts/airbyte/values.yaml
> +  activity_max_delay_between_attempts_seconds: ""
@xpuska513 can you review this contribution please?

2023-02-07 19:18 UTC, xpuska513 approved these changes
LGTM

2023-02-09 22:42 UTC, marcosmarxm approved these changes

2023-02-09 22:43 UTC, merged