🎉Source Gitlab: preserve data in records with flattened keys
airbytehq/airbyte pull request #22293
Opened 2023-02-02 03:25 UTC by BrentSouza

## What

Writing this to resolve #22124

## How

Certain ids for nested objects are being "flattened" into the parent object, but the function is using `pop` to access the nested object, which eliminates useful information from the record. Instead of using `pop`, I'm proposing to just use `get` which so we can keep the "flattened" ids in the parent object for backward compatibility while preserving the original structure of the record.

## Recommended reading order

This is a simple 3 char swap in a single file. I recommend you read left to right 😉 

## 🚨 User Impact 🚨
This should not break anything for existing consumers. The flattened_ids are still maintained, we're just adding data or perhaps keeping data is the better term.

## Pre-merge Checklist

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

2023-02-02 03:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=22293) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=22293) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=22293) it.</sub>

2023-02-02 09:44 UTC, juweins reviewed
From my perspective:

You already mentioned it in your issue statement. From a consumers point of view, I would expect to receive data as requested from the source. So changing to .get makes sense to me.

I share your thoughts on this:
> Was .pop a design decision?

However, since .get returns a None in some cases: Did you test this case? 
With only limited experience with Gitlab: How likely is that case? I see that there is no exception handling on _flatten_id so I would assume that there is no such case.

Thoughts please :)

2023-02-02 18:52 UTC, juweins commented
Thanks for pointing this out to me! 👍🏼

2023-05-17 18:55 UTC, marcosmarxm requested changes

2023-05-17 20:23 UTC, archangelic commented on airbyte-integrations/connectors/source-gitlab/source_gitlab/schemas/issues.json
> +      "additionalProperties": true
I was going to add all the properties into these, but many of them are only documented in examples outputs, or not at all.

2023-05-17 20:35 UTC, archangelic commented
/test connector=source-gitlab

2023-05-17 21:39 UTC, archangelic commented
/test connector=source-gitlab

2023-05-23 16:10 UTC, marcosmarxm commented
/test connector=source-gitlab

2023-05-23 17:06 UTC, marcosmarxm commented
The Oauth token got expired for today. Waiting instructions how to get this generated to make tests work again.

2023-05-25 16:16 UTC, marcosmarxm commented
/test connector=source-gitlab

2023-05-25 17:18 UTC, marcosmarxm approved these changes

2023-05-25 17:38 UTC, merged