🎉 Source Amazon Ads : add new stream for invoices
airbytehq/airbyte pull request #22319
Opened 2023-02-02 16:05 UTC by ganpatagarwal

## What
*Add capability to pull [invoices](https://advertising.amazon.com/API/docs/en-us/invoices/#/invoice) data

## How
*Add new stream `invoices` to pull the invoices based on `start_date` filter

## Recommended reading order
1. `source_amazon_ads/streams/invoices.py`

## 🚨 User Impact 🚨
No user impact as this is not a breaking change 

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

</details>

2023-02-02 16:07 UTC, ganpatagarwal commented on airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/streams/common.py
> +    def error_response(self, response: requests.Response):
creating a separate function for error response so that it can be re-used

2023-02-02 16:08 UTC, ganpatagarwal commented
# unit tests run

```
Results (4.97s):
      72 passed
Name                                                              Stmts   Miss  Cover   Missing
-----------------------------------------------------------------------------------------------
source_amazon_ads/__init__.py                                         2      0   100%
source_amazon_ads/constants.py                                        1      0   100%
source_amazon_ads/schemas/__init__.py                                 8      0   100%
source_amazon_ads/schemas/attribution_report.py                      21      0   100%
source_amazon_ads/schemas/common.py                                  51      1    98%   26
source_amazon_ads/schemas/invoices.py                               132      0   100%
source_amazon_ads/schemas/profile.py                                 16      0   100%
source_amazon_ads/schemas/sponsored_brands.py                        22      0   100%
source_amazon_ads/schemas/sponsored_display.py                       31      0   100%
source_amazon_ads/schemas/sponsored_products.py                      37      0   100%
source_amazon_ads/source.py                                          47      1    98%   134
source_amazon_ads/streams/__init__.py                                 8      0   100%
source_amazon_ads/streams/attribution_report.py                      81      0   100%
source_amazon_ads/streams/common.py                                  85      2    98%   96, 165
source_amazon_ads/streams/invoices.py                                87      4    95%   59-60, 117, 156
source_amazon_ads/streams/profiles.py                                21      0   100%
source_amazon_ads/streams/report_streams/__init__.py                  5      0   100%
source_amazon_ads/streams/report_streams/brands_report.py            10      0   100%
source_amazon_ads/streams/report_streams/brands_video_report.py      10      0   100%
source_amazon_ads/streams/report_streams/display_report.py           16      0   100%
source_amazon_ads/streams/report_streams/products_report.py          18      0   100%
source_amazon_ads/streams/report_streams/report_streams.py          240     19    92%   151, 204-205, 257-258, 377-378, 410-412, 417-418, 427-433
source_amazon_ads/streams/sponsored_brands.py                        26      0   100%
source_amazon_ads/streams/sponsored_display.py                       31      0   100%
source_amazon_ads/streams/sponsored_products.py                      41      0   100%
source_amazon_ads/utils.py                                           22      0   100%
unit_tests/__init__.py                                                0      0   100%
unit_tests/conftest.py                                               51      0   100%
unit_tests/test_attribution_report.py                                66      1    98%   47
unit_tests/test_invoices.py                                          54      1    98%   66
unit_tests/test_report_streams.py                                   297      0   100%
unit_tests/test_source.py                                            48      0   100%
unit_tests/test_streams.py                                          126      1    99%   77
unit_tests/test_utils.py                                             11      0   100%
unit_tests/utils.py                                                  32      0   100%
-----------------------------------------------------------------------------------------------
TOTAL                                                              1754     30    98%
```

2023-02-02 16:10 UTC, ganpatagarwal commented
# acceptance test run

```
Test session starts (platform: darwin, Python 3.9.11, pytest 6.2.5, pytest-sugar 0.9.5)
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Users/ganpatagarwal/stoke/airbyte/airbyte-integrations/connectors/source-amazon-ads/.hypothesis/examples')
rootdir: /Users/ganpatagarwal/stoke/airbyte, configfile: pytest.ini
plugins: sugar-0.9.5, requests-mock-1.9.3, mock-3.6.1, hypothesis-6.54.4, timeout-1.4.2, cov-3.0.0
collecting ... {"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/ganpatagarwal/stoke/airbyte/airbyte-integrations/connectors/source-amazon-ads/secrets/config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_config_match_spec[inputs0] ✓                                   3% ▍         {"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/ganpatagarwal/stoke/airbyte/airbyte-integrations/connectors/source-amazon-ads/secrets/config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_match_expected[inputs0] ✓                                      5% ▌         {"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/ganpatagarwal/stoke/airbyte/airbyte-integrations/connectors/source-amazon-ads/secrets/config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_docker_env[inputs0] ✓                                          8% ▊         {"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/ganpatagarwal/stoke/airbyte/airbyte-integrations/connectors/source-amazon-ads/secrets/config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_enum_usage[inputs0] ✓                                         11% █▏        {"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/ganpatagarwal/stoke/airbyte/airbyte-integrations/connectors/source-amazon-ads/secrets/config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_oneof_usage[inputs0] ✓                                        13% █▍
 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_required[inputs0] ✓                                           16% █▋
 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_optional[inputs0] ✓                                           18% █▉
 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_has_secret[inputs0] ✓                                         21% ██▏
 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_secret_never_in_the_output[inputs0] ✓                         24% ██▍       {"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/ganpatagarwal/stoke/airbyte/airbyte-integrations/connectors/source-amazon-ads/secrets/config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_secret_is_properly_marked[inputs0] ✓                          26% ██▋
 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_property_type_is_not_array[inputs0] ✓                         29% ██▉
 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_object_not_empty[inputs0] ✓                                   32% ███▎
 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_array_type[inputs0] ✓                                         34% ███▌
 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_forbidden_complex_types[inputs0] ✓                            37% ███▊
 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_date_pattern[inputs0] ✓                                       39% ███▉
 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_date_format[inputs0] ✓                                        42% ████▎     {"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/ganpatagarwal/stoke/airbyte/airbyte-integrations/connectors/source-amazon-ads/secrets/config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_defined_refs_exist_in_json_spec_file[inputs0] ✓               45% ████▌     {"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/ganpatagarwal/stoke/airbyte/airbyte-integrations/connectors/source-amazon-ads/secrets/config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_oauth_flow_parameters[inputs0] ✓                              47% ████▊     {"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/ganpatagarwal/stoke/airbyte/airbyte-integrations/connectors/source-amazon-ads/secrets/config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_backward_compatibility[inputs0] s                             50% █████     {"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/ganpatagarwal/stoke/airbyte/airbyte-integrations/connectors/source-amazon-ads/secrets/config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_additional_properties_is_true[inputs0] ✓                      53% █████▍    {"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/ganpatagarwal/stoke/airbyte/airbyte-integrations/connectors/source-amazon-ads/secrets/config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestConnection.test_check[inputs0] ✓                                        55% █████▌    {"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/ganpatagarwal/stoke/airbyte/airbyte-integrations/connectors/source-amazon-ads/integration_tests/invalid_config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestConnection.test_check[inputs1] ✓                                        58% █████▊    {"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/ganpatagarwal/stoke/airbyte/airbyte-integrations/connectors/source-amazon-ads/secrets/config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestDiscovery.test_discover[inputs0] ✓                                      61% ██████▏   {"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/ganpatagarwal/stoke/airbyte/airbyte-integrations/connectors/source-amazon-ads/secrets/config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestDiscovery.test_defined_curso [...]

2023-04-11 20:44 UTC, marcosmarxm commented
Thanks @ganpatagarwal we're going to review this contribution during the week

2023-04-21 16:32 UTC, marcosmarxm commented
/test connector=connectors/source-amazon-ads

2023-07-06 14:30 UTC, darynaishchenko requested changes

2023-08-15 14:54 UTC, bmcgilli commented
@ganpatagarwal are you still willing to work on this? Please let us know or we will find another contributor, thanks!

2023-09-19 16:33 UTC, marcosmarxm commented
Close due inactivity.

2023-09-19 16:33 UTC, closed without merging