🎉 Amazon Sp Api: adds GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2 incremental report
airbytehq/airbyte pull request #22337
Opened 2023-02-02 18:52 UTC by VenezianoMauro

## What
Adds GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2. 

## How
The new class FlatFileSettlementV2ReportsV2 uses the existing ReportsAmazonSPStream class plus the IncrementalMixin.
To make it incremental, the cursor is set to track the createdSince parameter of the request.  

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

2023-02-02 18:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=22337) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=22337) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=22337) it.</sub>

2023-02-02 20:00 UTC, VenezianoMauro commented
![image](https://user-images.githubusercontent.com/11358106/216436923-d7749182-87ab-416c-8bcc-3527b74f3a4e.png)

2023-02-06 08:52 UTC, marcosmarxm commented
Thanks for the contribution @VenezianoMauro someone will review during the week.

2023-02-15 13:59 UTC, marcosmarxm commented
@sh4sh do you mind reviewing this one?

@VenezianoMauro sorry the delay.

2023-02-15 14:14 UTC, marcosmarxm requested changes
Left some comments.

2023-02-15 14:14 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-amazon-seller-partner/integration_tests/configured_catalog_settlement_reports_v2.json
> +}
Can you add this to `configured_catalog` to run  tests too?

2023-02-15 14:14 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
> +            "pageSize": 100,
```suggestion
            "pageSize": self.page_size,
```
and create the variable

2023-02-15 14:14 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
> +            raise Exception(f"Unknown response for stream `{self.name}`. Response body {report_payload}")
EOF

2023-02-27 20:42 UTC, VenezianoMauro commented on airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
> +            is_fatal = report_payload.get("processingStatus") == "FATAL"
i implemented the class in "constants". Is it okey?

2023-03-02 10:03 UTC, marcosmarxm requested changes
Some comments.

2023-03-02 10:03 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
> +            is_fatal = processing_status == ProcessingStatus.FATAL
Please refactor this to status and not to have one variable to each status.

2023-03-02 10:03 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
> +        if is_done:
```suggestion
        if status == ProcessingStatus.DONE:
```

2023-03-02 10:03 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
> +            raise Exception(f"The report for stream '{self.name}' was aborted due to a fatal error")
What I said here is, if there is a fatal error from the API please log it to the user understand what caused it

2023-03-02 10:03 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
> +        elif is_cancelled:
```suggestion
        elif status == ProcessingStatus.CANCELLED:
```

2023-03-02 10:03 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
> +            is_fatal = processing_status == ProcessingStatus.FATAL
You can use the `processing_status`

2023-05-10 16:24 UTC, sajarin commented
Hey @VenezianoMauro sorry for the delay in review here, it's been a while since we heard from you and there have been some comments left regarding this PR. 

If you have a chance, please create a new PR that rebases the master branch with the requested changes. We'd love to get this report into our connector if possible and we appreciate your contributions here!

2023-05-10 16:24 UTC, closed without merging