Changed docs to differentiate between docker compose standalone and plugin
airbytehq/airbyte pull request #22394
Opened 2023-02-05 22:16 UTC by JulianRommel

## What & How
I changed the local deployment instructions to better differentiate between docker-compose (standalone version) and docker compose (plugin). The docs aren't concise on this currently. I also changed the link to the Docker Engine installation guide, as this includes the Docker Compose plugin.

## 🚨 User Impact 🚨
Should help users who haven't used docker before to find the correct version.

2023-02-05 22:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=22394) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=22394) before we can accept your contribution.<br/><hr/>**Julian Rommel** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=22394) it.</sub>

2023-02-06 14:35 UTC, juweins requested changes
Hey @JulianRommel ! Thank you for your first Contribution! Welcome 🎉

I reviewed your PR and I have got two questions for you:
1. Regarding your proposal: Is there really a need for instructions on docker engine (standalone)? I
I would say no, since this adds complexity to the quick start and may cause some confusion (docker compose vs. -) Furthermore, user of the standalone version will be aware of using the (deprecated) hyphen command.

2. I found a typo on line 54: there is a backslash \ following the WSL_ which causes it to display in the documentation. It would be great if you can include this in you PR.

3. Please make sure to sign the CLA, so your PR can be further processed.

Thoughts?

2023-02-06 18:05 UTC, JulianRommel commented
Hey @juweins and thank you so much for your feedback! You are probably right about the standalone version. I will change it and also include a fix for the typo on line 54.

2023-02-06 18:33 UTC, juweins reviewed
Thanks for removing the odd character in line 54.

**From my side, this LGTM!** The changes are reasonable and provide value. @sh4sh 

BTW:
My previous comment should initiate a little discussion and not terminate your proposals. You can bring in your thoughts, too! 👍🏽

Make sure to sign the CLA from your previous commit. I don't know what happened here.

2023-02-06 18:45 UTC, JulianRommel commented
@juweins that's weird, I have signed the CLA but it seems to be buggy. Any ideas how to fix this? I already removed it and signed it again...

2023-02-07 15:01 UTC, marcosmarxm approved these changes
Thanks @JulianRommel

2023-02-07 15:02 UTC, merged