Docs: Information to setup source GA4 #21670
airbytehq/airbyte pull request #22416
Opened 2023-02-06 15:31 UTC by juweins

## What
There has been an issue regarding the setup process for GA4 source ( #21670 ).

## How
I improved the documentation by adding a caution-box to ensure correct setup. This might be confused by mistake during setup. 

## Recommended reading order
1. `google-analytics-v4.md`

## 🚨 User Impact 🚨
Increased user experience

## Pre-merge Checklist
None applicable.

2023-02-06 15:40 UTC, juweins commented
I just added a hint to the GA4 documentation. In my opinion, that should be enough to guide new users.

Thoughts please @sh4sh

2023-02-07 14:56 UTC, marcosmarxm requested changes

2023-02-07 14:56 UTC, marcosmarxm commented on docs/integrations/sources/google-analytics-v4.md
> +| 0.1.2   | 2023-02-06 | [22416](https://github.com/airbytehq/airbyte/pull/22416) | Improved section on service account                   |
Because it is only a documentation update you don't need to bump the version. Please remove this line.

2023-02-23 10:38 UTC, lazebnyi approved these changes

2023-02-23 22:27 UTC, sh4sh commented
Hey @juweins, this is great thanks for addressing this!

After looking this over, I realized the changes are not on the right page. It's my fault, I added the wrong link to my issue. Would you be able to move your addition to this page instead: https://docs.airbyte.com/integrations/sources/google-analytics-data-api

I'm sorry for the extra work 😞 I'd take care of it but I want you to be credited in the commit history.

2023-03-17 17:51 UTC, marcosmarxm approved these changes

2023-03-17 17:54 UTC, merged