source Aha: new fields - comments, endorsements, categories for ideas
airbytehq/airbyte pull request #22642
Opened 2023-02-09 14:01 UTC by Upgreydd

## What
Adds new fields: endorsements (votes), comments for ideas, and categories for products

## How
CDK

## 🚨 User Impact 🚨
Possible to synchronize comments, endorsements (votes), and categories

2023-02-09 22:49 UTC, marcosmarxm requested changes, later dismissed
some comments.

2023-02-09 22:49 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-aha/source_aha/manifest.yaml
> +      field_pointer: ["idea_comments"]
```suggestion
  selector_products:
    extractor:
      field_pointer: ["{{ options['name'] }}"]
```

2023-02-09 22:49 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-aha/source_aha/manifest.yaml
> +      name: "idea_votes"
Better rename to `idea_endorsements`.

2023-02-10 09:26 UTC, Upgreydd commented
> some comments.

Thank you @marcosmarxm. I did the cleanup of redundant parts.

2023-02-13 21:44 UTC, marcosmarxm commented
/test connector=connectors/source-aha

2023-02-13 22:14 UTC, marcosmarxm commented
@Upgreydd can you check failed tests?

2023-02-14 15:35 UTC, Upgreydd commented
> @Upgreydd can you check failed tests?

@marcosmarxm 
It's related to limited `API key`/`aha plan` to access `features` and `goals` options. Looks like airbyte has a limited key too (so do I). It's not related to my PR at all cause the same test fails in the master. The only option to test it without a good API key is to remove tests for `features` and `goals` I guess?

2023-02-20 10:07 UTC, Upgreydd commented
@marcosmarxm I've removed checks for `goals` and `features` because they are optional and my API key and airbyte API key doesn't cover that part - that's why it fails tests.
Rebased on the new version with `manifest.yaml` changes from master and fixed definitions and structure.

2023-03-03 16:06 UTC, marcosmarxm commented
/test connector=connectors/source-aha

2023-03-17 11:50 UTC, phdmohamedali commented
any updates on this

2023-04-15 06:43 UTC, Upgreydd commented
> any updates on this

My part works as expected, Issue is with base code. No idea why it's not checked while running CI

2023-05-26 16:46 UTC, sh4sh commented
Seeded streams in the integration testing account

2023-05-26 16:46 UTC, sh4sh commented
/test connector=connectors/source-aha

2023-05-30 21:11 UTC, archangelic commented
/test connector=connectors/source-aha

2023-05-30 21:53 UTC, archangelic approved these changes

2023-05-30 22:12 UTC, merged