Changed: Source Confluence delivers body details #22410
airbytehq/airbyte pull request #22663
Opened 2023-02-09 17:46 UTC by juweins

## What
The current alpha version of Source Confluence does not deliver details as requested by an user in issue #22410 .

## How
I added the request details and the connector now delivers the body of a space/blog_post.

There are no updates to present documentation needed.

## Roadmap
- There should be a way to dynamically opt in details, as they produce significant overhead. (Future PR)
- As of now, there are only 2 unittests and no integration tests present. I will probably add some in upcoming PR(s)

## Recommended reading order
1. source.py

## 🚨 User Impact 🚨
The additional delivery of the body details do not break any existing connections. They may produce a larger volume, which should be adressed in future PR / connector development. A majority of the possible details are not covered in the current connector.

## Test Output
### Unit
![unit_test](https://user-images.githubusercontent.com/26652109/217891981-f0739768-a633-42ae-8b74-9a8b9346b2cb.jpg)

### Integration
no tests present

### Acceptance
The failing acceptance tests also occur in unchanged (freshly pulled) airbyte master. (!)
![acceptance test](https://user-images.githubusercontent.com/26652109/217891899-afbc6d36-e19c-4422-b9f7-7f404236ba2e.jpg)

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

2023-03-08 12:27 UTC, shawnxman1423 approved these changes

2023-04-18 16:51 UTC, sajarin commented
/test connector=connectors/source-confluence

2023-04-18 16:52 UTC, sajarin requested changes, later dismissed
Can you do the following: 

1. Bump the dockerfile version 
2. Update the readme of the connector with a note in the change log

2023-04-18 19:04 UTC, sajarin commented
Looks like this has been solved as of #23988

2023-04-18 19:04 UTC, closed without merging