Add Leave Feedback link to streams table header
airbytehq/airbyte pull request #22842
Opened 2023-02-10 20:10 UTC by krishnaglick

## What
Adds a Leave Feedback link to streams table header

2023-02-10 20:25 UTC, krishnaglick commented on airbyte-webapp/src/components/connection/ConnectionForm/SyncCatalogField.tsx
> +        </div>
New button added here

2023-02-10 23:08 UTC, andyjih requested changes
I think "Share" is more welcoming than "Leave"

2023-02-10 23:08 UTC, andyjih commented on airbyte-webapp/src/components/connection/ConnectionForm/SyncCatalogField.tsx
> +                <FormattedMessage id="form.leaveFeedback" />
```suggestion
                <FormattedMessage id="form.shareFeedback" />
```

2023-02-10 23:08 UTC, andyjih commented on airbyte-webapp/src/locales/en.json
> +  "form.leaveFeedback": "Leave Feedback",
```suggestion
  "form.shareFeedback": "Share Feedback",
```

2023-02-13 14:52 UTC, krishnaglick commented
Made that change @andyjih!

2023-02-14 17:47 UTC, andyjih approved these changes
lgtm from a copy perspective, but defer to @edmundito on the code approval

2023-02-14 17:56 UTC, edmundito requested changes

2023-02-14 17:56 UTC, edmundito commented on airbyte-webapp/src/components/connection/ConnectionForm/SyncCatalogField.tsx
> +        <div className={styles.actions}>
Instead of a custom div, this could be a FlexContainer with a lg gap prop

2023-02-14 17:56 UTC, edmundito commented on airbyte-webapp/src/components/connection/ConnectionForm/SyncCatalogField.tsx
> +              <a href="https://forms.gle/5wDQHf6hL5sCvLgK7" target="_blank" rel="noreferrer">
The URL needs to to be part of the `links` file

2023-02-14 19:53 UTC, krishnaglick commented
@edmundito Fixed those two issues!

2023-02-14 20:00 UTC, edmundito approved these changes
Looks good. Tested locally.

One thing to note is that we don't have a consistent color code for links. We just discussed this as a UI team and we're taking point. Since this is temporary I think it's fine to leave it with the default colors.

2023-02-15 04:58 UTC, davinchia commented
/approve-and-merge reason="prep for wednesday deploy"

2023-02-15 04:59 UTC, octavia-approvington commented
It's time <br/> ![fine lets go](https://media1.giphy.com/media/yaR8Dux1s0fAI/giphy.gif?cid=ecf05e47a0zmzctsyu3sqzbajb4aitlkuzrr9vxk70s7lw1r&rid=giphy.gif&ct=g)

2023-02-15 04:59 UTC, octavia-approvington approved these changes

2023-02-15 04:59 UTC, merged