fix: upgrade databend-sqlalchemy
airbytehq/airbyte pull request #22855
Opened 2023-02-11 00:11 UTC by hantmac

## What
*Describe what the change is solving*
Because the 'databend` has some break changes from v0.9.0 and the databend cloud will only use the version > 0.9.0, so we update the databend-py driver to fix compatibility issue with databend-query 0.9 in [this pr](https://github.com/databendcloud/databend-py/pull/2).

## How
*Describe the solution*
If databend version >= v0.9.0 or later, users need to use databend-sqlalchemy version >= v0.1.0 and I set the version of `databend-sqlalchemy` as `0.1.0` in `setup.py`.

2023-02-13 16:00 UTC, marcosmarxm requested changes
Please fix the commits from your pull request and after request my review again.

2023-02-14 01:41 UTC, hantmac commented on airbyte-commons-server/src/main/java/io/airbyte/commons/server/handlers/SchedulerHandler.java
> +        .workspaceId(updatedDestination.getWorkspaceId());
Sorry I made a wrong git rebase 😭

2023-02-14 02:12 UTC, hantmac commented on airbyte-commons-server/src/main/java/io/airbyte/commons/server/handlers/SchedulerHandler.java
> +        .workspaceId(updatedDestination.getWorkspaceId());
Thanks! Fixed.

2023-02-14 22:23 UTC, marcosmarxm commented
/test connector=connectors/destination-databend

2023-02-24 21:36 UTC, natalyjazzviolin commented
@hantmac thanks for the contribution! This is a GA connector so we need to make sure and test all possible use cases to make sure there are no breaking changes.

2023-03-08 14:19 UTC, hantmac commented
/test connector=connectors/destination-databend

2023-03-27 16:14 UTC, natalyjazzviolin commented
Closing this in favor of https://github.com/airbytehq/airbyte/pull/24399/

2023-03-27 16:14 UTC, closed without merging