🎉Source Twilio: New Stream Conversation Messages
airbytehq/airbyte pull request #22875
Opened 2023-02-12 18:09 UTC by btkcodedev

## What
[*Solving the Airbyte Issue #19742*](https://github.com/airbytehq/airbyte/issues/19742)

## Enhancement
New streams: 

- Conversation Messages

## Recommended reading order
1. `source_twilio/source.py`
2. `source_twilio/streams.py`
3.  `source_twilio/schemas/conversation_messages.json`

## 🚨 User Impact 🚨
No breaking changes

## Pre-merge Checklist
<details open><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter [Yes]

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Issue acceptance criteria met
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [x] Documentation which references the generator is updated as needed

</details>

## For the reviewer: 
- Need help with incremental streams, Please someone give comments about how it can be improved. It would greatly help
 - Enhancement passing in local python integration tests (Except incremental). Needs test deployment to cloud build and publish it :)

2023-02-22 23:40 UTC, YowanR commented
@sh4sh Can you take a look at this issue, please?

2023-02-24 16:19 UTC, natalyjazzviolin requested changes
Please make sure to run this to correct formatting errors:

`./gradlew --no-daemon  :airbyte-integrations:connectors:source-twilio:airbytePythonFormat`

Then run `./gradlew :airbyte-integrations:connectors:source-twilio:integrationTest` to see the errors I am referring to.

2023-02-24 19:56 UTC, natalyjazzviolin requested changes

2023-03-01 17:00 UTC, btkcodedev commented on airbyte-integrations/connectors/source-twilio/source_twilio/streams.py
> +        return {"conversation_sid": record["messages"]["conversation_sid"]}
Fixed, Please try build again

2023-03-05 03:18 UTC, btkcodedev commented
/test connector=connectors/source-twilio

2023-03-20 18:44 UTC, marcosmarxm requested changes
<s>Please move this to https://github.com/airbytehq/airbyte/pull/23995 because you're implementing the Parent/Child stream.</s>
This need to wait for https://github.com/airbytehq/airbyte/pull/24114

2023-04-01 12:47 UTC, marcosmarxm commented
/test connector=connectors/source-twilio

2023-04-01 13:09 UTC, marcosmarxm approved these changes
Thanks @btkcodedev I'll publish the change on Monday.

2023-04-03 20:16 UTC, marcosmarxm commented
/test connector=connectors/source-twilio

2023-04-05 21:36 UTC, artem1205 requested changes
Please check schema once more

2023-04-05 21:36 UTC, artem1205 commented on airbyte-integrations/connectors/source-twilio/source_twilio/schemas/conversation_messages.json
> +  "$schema": "http://json-schema.org/draft-04/schema#",
change schema to "https://json-schema.org/draft-07/schema#"

2023-04-05 21:36 UTC, artem1205 commented on airbyte-integrations/connectors/source-twilio/source_twilio/schemas/conversation_messages.json
> +      "type": "integer"
please change to ["null", "integer"] to avoid possible schema problems in future

2023-04-05 21:36 UTC, artem1205 commented on airbyte-integrations/connectors/source-twilio/source_twilio/schemas/conversation_messages.json
> +          "type": "integer"
please change to ["null", "integer"] to avoid possible schema problems in future

2023-04-05 21:36 UTC, artem1205 commented on airbyte-integrations/connectors/source-twilio/source_twilio/schemas/conversation_messages.json
> +      "type": ["null", "string"]
media  should be array, not string

2023-04-07 12:58 UTC, marcosmarxm commented
/test connector=connectors/source-twilio

2023-04-07 13:41 UTC, artem1205 approved these changes

2023-04-10 22:26 UTC, marcosmarxm commented
/test connector=connectors/source-twilio

2023-04-10 23:24 UTC, marcosmarxm commented
/publish connector=connectors/source-twilio

2023-04-11 10:20 UTC, marcosmarxm commented
/publish connector=connectors/source-twilio pre-release=false

2023-04-11 12:16 UTC, pedroslopez commented
/publish connector=connectors/source-twilio

2023-04-11 12:26 UTC, pedroslopez commented
/publish connector=connectors/source-twilio

2023-04-11 15:39 UTC, merged