🎉Source Twilio: New stream Executions
airbytehq/airbyte pull request #22874
Opened 2023-02-12 17:27 UTC by btkcodedev

## What
[*Solving the Airbyte Issue #19748*](https://github.com/airbytehq/airbyte/issues/19748)

## Enhancement
New streams: 

- Executions

## Recommended reading order
1. `source_twilio/source.py`
2. `source_twilio/streams.py`
3.  `source_twilio/schemas/executions.json`

## 🚨 User Impact 🚨
No breaking changes

## Pre-merge Checklist
<details open><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter [Yes]

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Issue acceptance criteria met
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [x] Documentation which references the generator is updated as needed

</details>

## For the reviewer: 
- Need help with incremental streams, Please someone give comments about how it can be improved. It woul greatly help
 - Enhancement passing in local python integration tests (Except incremental). Needs test deployment to cloud build and publish it :)

2023-02-12 17:29 UTC, btkcodedev commented
Really needs help with the incremental behavior, Would love to see review comments from the community for that :)

2023-02-24 17:09 UTC, YowanR commented
@natalyjazzviolin @sh4sh Can you please take a look? 🙏

2023-02-24 20:26 UTC, natalyjazzviolin commented
/test connector=connectors/source-twilio

2023-04-01 12:11 UTC, marcosmarxm commented
/test connector=connectors/source-twilio

2023-04-01 12:20 UTC, marcosmarxm commented
/test connector=connectors/source-twilio

2023-04-01 12:25 UTC, marcosmarxm approved these changes
Thanks @btkcodedev I'm having problems with our CI testing but the code is done. I'll finish this on Monday.

2023-04-01 13:24 UTC, marcosmarxm commented
/test connector=connectors/source-twilio

2023-04-05 21:24 UTC, artem1205 requested changes

2023-04-05 21:24 UTC, artem1205 commented on docs/integrations/sources/twilio.md
> +* [Executions](https://www.twilio.com/docs/phone-numbers/api/incomingphonenumber-resource#read-multiple-incomingphonenumber-resources) \(Incremental\)
Please add Flows stream in docs

2023-04-05 21:24 UTC, artem1205 commented on airbyte-integrations/connectors/source-twilio/source_twilio/schemas/flows.json
> +  "type": "object",
Please add "$schema": "http://json-schema.org/draft-07/schema#"

2023-04-07 12:42 UTC, marcosmarxm commented
/test connector=connectors/source-twilio

2023-04-07 13:39 UTC, artem1205 approved these changes

2023-04-10 20:03 UTC, marcosmarxm commented
/publish connector=connectors/source-twilio

2023-04-10 20:09 UTC, marcosmarxm commented
/publish connector=connectors/source-twilio

2023-04-10 22:19 UTC, merged

2023-04-11 01:33 UTC, btkcodedev commented
Thanks @marcosmarxm for the continuous support shown for this PR. 🙇🙇🙇