Source Hubspot: new stream Email Subscriptions
airbytehq/airbyte pull request #22910
Opened 2023-02-13 13:15 UTC by Alcadeus0

## What
Adding a new stream email subscriptions
Returns all email subscription types that have been created in the given Hub ID.

## How
The connector adds the email subscription API stream

## Recommended reading order
1. `source.py`
2. `streams.py`

## 🚨 User Impact 🚨
No changes to existing code

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

![image](https://user-images.githubusercontent.com/59562284/218467621-bb9bdde2-2b9b-4d37-b75b-650d5fac8cd6.png)

2023-02-13 13:17 UTC, Alcadeus0 commented
![image](https://user-images.githubusercontent.com/59562284/218468011-cc424efc-d8ea-4287-b25b-135d74bea54d.png)
The integration test for incremental read fails. The stream is not an incremental one

2023-02-17 03:47 UTC, Alcadeus0 commented
@YowanR can you take a look at this?

2023-02-17 22:28 UTC, YowanR commented
@Alcadeus0 Is it possible to make this stream incremental? Is there a cursor available?

2023-02-18 03:23 UTC, Alcadeus0 commented
@YowanR Unfortunately this stream doesn't have a cursor field available

2023-02-27 22:11 UTC, YowanR commented
@sh4sh @natalyjazzviolin Can you please take a look at this PR? Thanks 🙏

2023-03-17 17:24 UTC, marcosmarxm commented
/test connector=connectors/source-hubspot

2023-03-18 11:35 UTC, Alcadeus0 commented
![image](https://user-images.githubusercontent.com/59562284/226103154-cbb31958-a9c9-4639-9ea3-ada28199b452.png)

2023-03-21 16:26 UTC, marcosmarxm commented
/test connector=connectors/source-hubspot

2023-03-21 16:36 UTC, Alcadeus0 commented
> /test connector=connectors/source-hubspot
> > :clock2: connectors/source-hubspot https://github.com/airbytehq/airbyte/actions/runs/4481449916

What does that mean?

2023-03-22 16:16 UTC, marcosmarxm requested changes
Left some comments about the stream schema please fix them.

2023-03-22 16:16 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-hubspot/source_hubspot/schemas/email_subscriptions.json
> +    "properties": {
missing the additionalProperties field, please check others stream.

2023-03-31 21:58 UTC, marcosmarxm commented
/test connector=source-hubspot

2023-03-31 23:42 UTC, Alcadeus0 commented
@marcosmarxm Are the tests not successful? It should have merged right?

2023-04-01 01:40 UTC, marcosmarxm commented
> @marcosmarxm Are the tests not successful? It should have merged right?

Yes, Tests are working now. I need the final approval from the connector team and it is ready to merge. There isn't anything in your side right now! Thanks for the contribution @Alcadeus0

2023-04-01 01:42 UTC, marcosmarxm approved these changes
Thanks @Alcadeus0

2023-04-01 04:27 UTC, Alcadeus0 commented
Thanks for your help with the review :)

2023-04-03 14:27 UTC, lazebnyi approved these changes
Nice!

2023-04-03 14:53 UTC, marcosmarxm commented
/publish connector=source-hubspot

2023-04-03 17:31 UTC, merged