Acceptance Test: Fix states for `LEGACY` incremental syncs
airbytehq/airbyte pull request #22943
Opened 2023-02-13 18:05 UTC by sergio-ropero

## What
The tests were failing for `LEGACY` states in the incremental mode.
Tested with Postgres Source.

## How
To fix the error in the acceptance test I had to rework on the `records_with_state` function, responsible of getting the record and state value.

The schema for `LEGACY` states was a bit different and I had to include new logic to fit them. Also, for Incremental states I have faced the error in with the value in the state is string instead of integer, so I had to include a casting function to sort it out. So far I have only included casting to `int`.

These are examples on the state data in the messages:
 ### LEGACY non CDC state data
```
{'cdc': False, 'streams': [{'stream_name': 'id_and_name', 'stream_namespace': 'public', 'cursor_field': ['id'], 'cursor': '3', 'cursor_record_count': 1}]}
```

### LEGACY CDC state data
```
{'cdc': False, 'cdc_state': {'state': {'{"schema":null,"payload":["postgres",{"server":"postgres"}]}': '{"transaction_id":null,"lsn":2101199320,"txId":1055370,"ts_usec":1676304204421970}'}}, 'streams': [{'stream_name': 'id_and_name', 'stream_namespace': 'public', 'cursor_field': ['id']}]}
```
## NOTES
When working in this issue, I realise that CDC state messages are adding `cdc: False` in the state message.
Not investigated if this only impact `LEGACY` state messages or it's happening to new state messages.

2023-02-13 18:13 UTC, rodireich commented
@sergio-ropero : Augustin is adding environment variable support to SAT.
See #22937 
This was for an unrelated failing test in STREAM mode that is currently disabled in master.
I don't know if it has direct impact on this issue or fix. But FYI

2023-02-13 19:07 UTC, bnchrch requested changes
Hey Sergio, thanks for this change.

I left a recommended change in this review.

Though, I will admit I'm a bit shaky on the details of which test was failing and how.

Could you also post the failing test message and a reason why you think it should pass?

2023-02-13 19:07 UTC, bnchrch commented on airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_incremental.py
> +                if "cdc_state" in state.keys():
I'm not sure this is the right place to address the CDC state.

My guiding principle here is: The Airbyte protocol and a result the CAT's should not be aware of how an individual connector consumes state.

As I understand `cdc_state` is specific to postgres's implementation (or database implementations). Which violates the above principle.

As an alternative, `source-postgres` should own this if statement.

I believe `source-sentry` [has implemented a similar method](https://github.com/airbytehq/airbyte/pull/21864/files#diff-350b5fdafcf9ae2b90ed4ab49c4d8d323826a10f16054941f5c812da040f7712R98) to handle legacy issues by overriding cursor value in certain situations.

2023-02-13 19:23 UTC, akashkulk commented
I was looking into the state object and ideally 

> @sergio-ropero : Augustin is adding environment variable support to SAT. See #22937 This was for an unrelated failing test in STREAM mode that is currently disabled in master. I don't know if it has direct impact on this issue or fix. But FYI

+ 1. Maybe worth seeing if this fixes the given issue. Based on a conversation with Subodh - we really shouldn't have the ``LEGACY`` state anywhere and perhaps by overriding the environment variables, we will get an expected non-LEGACY state

2023-02-14 12:15 UTC, sergio-ropero commented
Looks like the issue is going to be resolved with this pr:
https://github.com/airbytehq/airbyte/pull/22937

In case it not, I will reopen it.

2023-02-14 12:15 UTC, closed without merging