Google Analytics #2106 - incremental mode
airbytehq/airbyte pull request #2302
Opened 2021-03-04 11:34 UTC by vitaliizazmic

## What

Setting installing Google Analytics Tap from incremental_mode branch of vitaliizazmic fork for testing new incremental changes.  

## Pre-merge Checklist
- [ ] *Run integration tests*
- [ ] *Publish Docker images*

2021-03-04 11:35 UTC, vitaliizazmic commented
/test connector=source-googleanalytics-singer

2021-03-04 16:46 UTC, sherifnada commented
/test connector=source-googleanalytics-singer

2021-03-05 15:14 UTC, sherifnada commented
/test connector=source-googleanalytics-singer

2021-03-05 15:14 UTC, sherifnada commented
@vitaliizazmic the failure was being caused by a bug in standard tests -- please proceed with publishing the connector

2021-03-08 23:15 UTC, sherifnada commented
/test connector=source-googleanalytics-singer

2021-03-09 20:58 UTC, vitaliizazmic commented
/publish connector=connectors/source-googleanalytics-singer

2021-03-10 16:51 UTC, sherifnada requested changes
I don't think this was tested correctly -- the configured catalogs have not changed, and the catalog output by the connector has not changed I believe? Shouldn't those have changed?

2021-03-10 16:51 UTC, sherifnada commented on airbyte-integrations/connectors/source-googleanalytics-singer/setup.py
> +            "pipelinewise-tap-google-analytics @ https://github.com/vitaliizazmic/pipelinewise-tap-google-analytics/tarball/incremental_mode#egg=pipelinewise-tap-google-analytics-1.3.0-airbyte",
this should be pointing to the Airbyte fork before merging

2021-03-11 17:16 UTC, sherifnada commented
/test connector=source-google-analytics

2021-03-11 17:17 UTC, sherifnada commented
/test connector=source-googleanalytics-singer

2021-03-11 21:00 UTC, vitaliizazmic commented
/publish connector=connectors/source-googleanalytics-singer

2021-03-11 21:21 UTC, vitaliizazmic reviewed
Pointed

2021-03-11 22:01 UTC, sherifnada approved these changes

2021-03-11 22:22 UTC, merged