Source Slack: added timeout for incremental test
airbytehq/airbyte pull request #23249
Opened 2023-02-20 11:12 UTC by darynaishchenko

added timeout 2400 for incremental test

2023-02-20 11:13 UTC, darynaishchenko commented
/test connector=connectors/source-slack

2023-02-21 07:21 UTC, bazarnov approved these changes

2023-02-22 12:13 UTC, lazebnyi requested changes
please can you add allowedHosts.

2023-02-22 21:27 UTC, lazebnyi approved these changes

2023-02-23 09:33 UTC, merged