🎉Source MailChimp: New Stream Automations
airbytehq/airbyte pull request #23290
Opened 2023-02-21 17:03 UTC by btkcodedev

## What
[*Solving the Airbyte Issue #17024*](https://github.com/airbytehq/airbyte/issues/17024)

## Enhancement
New streams: 

- Automations (Incremental)

## Recommended reading order
1. `source_mailchimp/source.py`
2. `source_mailchimp/streams.py`
3.  `source_mailchimp/schemas/automations.json`

## 🚨 User Impact 🚨
No breaking changes

## Pre-merge Checklist
<details open><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter [Yes]

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Issue acceptance criteria met
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [x] Documentation that references the generator is updated as needed

</details>

## For the reviewer: 
- New stream is working in my local system and all acceptance test passing
- Please review & test it on the prod

2023-02-22 06:01 UTC, btkcodedev commented
@YowanR could you please assign anyone for review

2023-02-24 16:45 UTC, natalyjazzviolin commented
@btkcodedev could you please write out what issue this is solving in the future instead of just linking the issue? That would be really helpful, thank you :)

2023-02-24 17:17 UTC, natalyjazzviolin commented
@btkcodedev Please make sure to run `./gradlew --no-daemon  :airbyte-integrations:connectors:source-mailchimp:airbytePythonFormat` to fix formatting errors.

2023-02-24 17:17 UTC, natalyjazzviolin commented
/test connector=connectors/source-mailchimp

2023-02-24 21:21 UTC, natalyjazzviolin commented
/test connector=connectors/source-mailchimp

2023-03-01 16:06 UTC, btkcodedev commented
@natalyjazzviolin Thanks for the comments and build, 
Primary keys, and cursor fields, all are updated and schema fixed.
Acceptance test is passing in local
Please continue the further review.

2023-03-13 15:04 UTC, btkcodedev commented
/test connector=connectors/source-mailchimp

2023-03-15 19:51 UTC, btkcodedev commented
@natalyjazzviolin Bump here

2023-03-16 16:00 UTC, btkcodedev commented
Ready for review :)

2023-03-16 16:18 UTC, btkcodedev commented
@natalyjazzviolin Bump Here :)

2023-04-01 17:59 UTC, btkcodedev commented
@natalyjazzviolin @sh4sh @marcosmarxm @YowanR 
The PR is ready for review, 
Please could anyone run the test command :)

2023-04-01 18:03 UTC, btkcodedev commented
The Docker version is set to 5.0 as the older version 3.5 was a stream update so considering it as a minor update rather than a patch,
Old -> 4.0 and now it's 5.0

2023-04-02 10:17 UTC, marcosmarxm commented
Sorry @btkcodedev for the delay to review the contribution. @airbytehq/community-assistance-dri will review during this week.

2023-04-03 13:59 UTC, marcosmarxm requested changes

2023-04-03 13:59 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-mailchimp/source_mailchimp/spec.json
> +                "airbyte_secret": true
Why are you adding this? The PR is adding a new stream not changing this part of the code. Please rollback the change

2023-04-03 13:59 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-mailchimp/source_mailchimp/streams.py
> +    cursor_field = "create_time"
Add doc link to Mailchimp docs api.

2023-04-04 21:20 UTC, btkcodedev commented on airbyte-integrations/connectors/source-mailchimp/source_mailchimp/streams.py
> +    cursor_field = "create_time"
Added

2023-04-05 19:47 UTC, sajarin commented
Hey thanks for the contribution and apologies for the delay! 

I'll be the DRI responsible for reviewing this and getting it across the finish line. We currently have a backlog of about a dozen PRs, but just wanted to let you know that this PR has been added to the queue and I'll be trying my best to get to this as soon as possible. 

Thanks for the contribution and for being patient :)

2023-04-07 15:18 UTC, btkcodedev commented
Thanks, It is ready for review,
Please forward

2023-04-11 20:05 UTC, marcosmarxm commented
/test connector=connectors/source-mailchimp

2023-04-11 20:13 UTC, marcosmarxm approved these changes
Thanks @btkcodedev I requested to the connector team to made the final review of the contribution. Hope to publish during the week.

2023-04-18 11:05 UTC, btkcodedev commented
Thanks @marcosmarxm for update

2023-04-24 15:54 UTC, arsenlosenko approved these changes

2023-04-24 17:03 UTC, marcosmarxm commented
/publish connector=connectors/source-mailchimp

2023-04-24 18:07 UTC, merged