Connector Acceptance Test: Fix Test Discovery backward_compatibility
airbytehq/airbyte pull request #23681
Opened 2023-03-02 17:44 UTC by artem1205

## What
Fix Test Discovery `backward_compatibility` fixture

## How
move `previous_discovered_catalog` fixtures inside the test

2023-03-02 17:45 UTC, artem1205 commented
/test connector=bases/connector-acceptance-test

2023-03-02 18:38 UTC, lazebnyi approved these changes

2023-03-02 19:01 UTC, davydov-d commented on airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py
> +        def test_catalog_compatibility(
where is this function called?

2023-03-02 20:12 UTC, artem1205 commented
/test connector=bases/connector-acceptance-test

2023-03-02 20:12 UTC, artem1205 commented on airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py
> +        def test_catalog_compatibility(
updated

2023-03-03 07:54 UTC, davydov-d approved these changes

2023-03-03 07:54 UTC, davydov-d commented on airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py
> +    def skip_backward_catalog_fixture(
I'd suggest giving this routine a more meaningful name, otherwise looks good to me. But let's also wait for operations team to review

2023-03-03 16:38 UTC, alafanechere requested changes
@artem1205 I look like you spotted an edge case but I'm not sure what it is exactly and how you code fixes it.
Could you please write a test that reproduce the edge case and assess the correct behavior is now happening? 
You mention spec change in the PR description and made change to discovery/catalog tests, this is why I'm a bit puzzled.

2023-03-03 17:08 UTC, artem1205 commented
@alafanechere, the problem is not in tests itself, but in **fixtures**.

In `test_backward_compatibility` we call `skip_backward_compatibility_tests_fixture`, which, in turn, calls another fixtures:

1. `inputs`
2. `previous_connector_docker_runner`
3. `discovered_catalog`
4. `previous_discovered_catalog`

In my case, call of `discovered_catalog` and `previous_discovered_catalog` with the same config file will raise an error due to schema error. To bypass it, I divided this fixture into 2 to check input version **before** catalogs comparison:

1. Check flag from provided configuration
2. Check and compare catalogs

In this case, we will not face error in second fixture if we have a flag in first one.

2023-03-06 19:09 UTC, alafanechere commented
@artem1205 could you please provide an example of a context that leads to an error?
And it would help if you would add a test (of the tests) to make sure this behavior is not happening after your fix.
I'd like to make sure I understand this change.

2023-03-06 19:55 UTC, artem1205 commented
> @artem1205 could you please provide an example of a context that leads to an error? And it would help if you would add a test (of the tests) to make sure this behavior is not happening after your fix. I'd like to make sure I understand this change.

@alafanechere , as an example, where it fails: https://github.com/airbytehq/airbyte/actions/runs/4347181053/jobs/7594196845#step:11:1882

link to simplified version of test(another branch ):
https://github.com/airbytehq/airbyte/commit/bb512148d44021f4ef45499a16317070f49b3b9d

2023-03-08 18:47 UTC, davydov-d commented
hey @alafanechere did you have a chance to review this PR? does it need some additional work to do? It seems like I'm blocked by this issue as well so looking forward to merge it

2023-03-14 08:56 UTC, alafanechere commented
@artem1205 @davydov-d I merged and published a new CAT version in https://github.com/airbytehq/airbyte/pull/23992 
Please open an issue if your error is still not resolved with links to PR where you're stuck. Thanks!

2023-03-14 08:56 UTC, closed without merging