Destination-snowflake: added host validation by pattern on UI
airbytehq/airbyte pull request #23904
Opened 2023-03-09 11:45 UTC by etsybaev

## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

2023-03-10 18:38 UTC, etsybaev commented
/test connector=connectors/destination-snowflake

2023-03-10 19:37 UTC, etsybaev commented
/test connector=connectors/destination-snowflake

2023-03-11 16:43 UTC, etsybaev commented
/test connector=connectors/destination-snowflake

2023-03-16 22:39 UTC, grishick requested changes
need a stricter regex that matches IP address or hostname, but disallows protocol and query param parts of a URL

2023-03-20 20:44 UTC, ryankfu commented on airbyte-integrations/connectors/destination-snowflake/src/main/resources/spec.json
> +        "pattern": "^([^./?#]+\\.)?([^./?#]+\\.)?([^./?#]+\\.snowflakecomputing\\.com)$",
Would like to add an `example` https://github.com/airbytehq/airbyte/blob/6f98a68e28c7847091229c2231a61a4bc4abe218/airbyte-integrations/connectors/source-amazon-seller-partner/integration_tests/spec.json#L66 so it's clear when someone types in the wrong host they have an idea of what the code is validating against

2023-03-20 20:45 UTC, ryankfu reviewed
Nit: on having an example since when a user inputs an incorrect host they will be presented with a regex which is not the best UX but also doesn't lead the user to self resolve this issue. An example would be a good way to ensure the user is able to understand what the host should look like for Snowflake

2023-03-21 17:05 UTC, ryankfu approved these changes
LGTM and thanks for clarifying examples already exist

2023-03-21 17:23 UTC, ryankfu commented
cc: @airbytehq/frontend this fix adds a regex to validate hostnames for Snowflake, however, the issue we're seeing is that the error message is the `pattern` we're matching against and when an invalid hostname is presented it shows the regex. Is it possible to instead have it default to the `example` instead for a more human-readable format?

2023-03-21 18:34 UTC, lmossman commented
@ryankfu we have actually just merged a feature that allows connector specs to declare a `pattern_descriptor` which serves this exact purpose: you can set a human-readable pattern string that should be displayed in the error as well as above the field. 

This feature is still behind a feature flag which is currently disabled so users won't see the change, but we plan to start doing some A/B testing with it over the next couple of weeks before enabling it for everyone. 

Here are the tentative docs that we will merge once this feature is enabled globally, check out the `Pattern descriptors` section: https://github.com/airbytehq/airbyte/pull/24125/files?short_path=2edd29e#diff-2edd29e95aa820bea04f7d721aa3d847d6a1068f236af0727bc87370a5f608e0

2023-03-21 19:03 UTC, grishick approved these changes

2023-03-22 10:51 UTC, etsybaev commented
/test connector=connectors/destination-snowflake

2023-03-22 11:45 UTC, etsybaev commented
/publish connector=connectors/destination-snowflake

2023-03-22 13:32 UTC, etsybaev commented
/publish connector=connectors/destination-snowflake

2023-03-22 13:50 UTC, etsybaev commented
/publish connector=connectors/destination-snowflake

2023-03-22 14:55 UTC, merged