Added Segmentation Stream
airbytehq/airbyte pull request #23956
Opened 2023-03-11 11:23 UTC by Alcadeus0

## What
Fixes #17547

## How
Added new Stream Segmentation which returns list of segments from target segmentation

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
No

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

<details><summary><strong>Updating a connector</strong></summary>

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [X] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

2023-03-18 12:06 UTC, Alcadeus0 commented
![image](https://user-images.githubusercontent.com/59562284/226104940-6032425e-bf10-4e42-8e14-c263d5e16f55.png)

2023-03-20 14:02 UTC, marcosmarxm requested changes
Some comments.

2023-03-20 17:35 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-marketo/source_marketo/source.py
> +        return f"rest/asset/v1/segmentation/{self.segment_id}/segments.json"
@YowanR this change adds a new spec field where users need to specify the segmentation they want to retrieve. If they need two or all it won't be possible. Marketo has the option to retrieve all segmentations and we could use that to be parent stream and do automatically retrieving all data. Any comments?

2023-03-20 17:37 UTC, Alcadeus0 commented on airbyte-integrations/connectors/source-marketo/source_marketo/source.py
> +        return f"rest/asset/v1/segmentation/{self.segment_id}/segments.json"
I prefer that route as well because it makes it convenient as users would not need to search for the segmentIDs

2023-03-20 17:38 UTC, Alcadeus0 commented on airbyte-integrations/connectors/source-marketo/source_marketo/source.py
> +        return f"rest/asset/v1/segmentation/{self.segment_id}/segments.json"
I'll make the changes to have it return the entire segmentation. Is that alright?

2023-03-20 17:38 UTC, Alcadeus0 commented on airbyte-integrations/connectors/source-marketo/source_marketo/schemas/segmentations.json
> +}
just need to add the "type" to it right?

2023-03-21 22:11 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-marketo/source_marketo/source.py
> +        return f"rest/asset/v1/segmentation/{self.segment_id}/segments.json"
You're correct. you must create the parent stream to retrieve all segmentations and other to read the segments. Take a look in https://docs.airbyte.com/connector-development/cdk-python/http-streams#nested-streams--caching

2023-03-23 18:27 UTC, Alcadeus0 commented on airbyte-integrations/connectors/source-marketo/source_marketo/source.py
> +        return f"rest/asset/v1/segmentation/{self.segment_id}/segments.json"
@marcosmarxm  are there any already implemented nested streams that you know of which I can refer to get a better understanding of it?

2023-04-05 19:47 UTC, sajarin commented
Hey thanks for the contribution and apologies for the delay! 

I'll be the DRI responsible for reviewing this and getting it across the finish line. We currently have a backlog of about a dozen PRs, but just wanted to let you know that this PR has been added to the queue and I'll be trying my best to get to this as soon as possible. 

Thanks for the contribution and for being patient :)

2023-04-05 23:34 UTC, Alcadeus0 commented
Hello and thank you for adding it to the list :D
Of course I understand things at Airbyte can get busy busy, I look forward to  getting this PR finished and merged!

2023-04-18 18:01 UTC, marcosmarxm commented
/test connector=connectors/source-marketo

2023-04-18 18:15 UTC, marcosmarxm commented
/test connector=connectors/source-marketo

2023-04-20 11:17 UTC, marcosmarxm commented
/test connector=connectors/source-marketo

2023-04-25 13:39 UTC, marcosmarxm approved these changes
Thanks for the contribution @Alcadeus0 rigth now Marketo is timing out integration tests. I request the connector team to take a look. There isn't anything pending from your side.

2023-05-04 18:24 UTC, marcosmarxm commented
/test connector=connectors/source-marketo

2023-05-10 11:22 UTC, lazebnyi approved these changes
LGTM! Minor comment for documentation.

2023-05-10 11:22 UTC, lazebnyi commented on docs/integrations/sources/marketo.md
> +| `1.1.0`  | 2023-04-18 | [23956](https://github.com/airbytehq/airbyte/pull/23956) | Add `Segmentations` Stream                                                                     |
We need add stream to the `Supported Streams `section.

2023-05-12 18:14 UTC, marcosmarxm commented
/publish connector=connectors/source-marketo

2023-05-12 20:58 UTC, merged