Duplicate rows for same LSN
airbytehq/airbyte pull request #23964
Opened 2023-03-13 03:41 UTC by sivankumar86

## What
*Describe what the change is solving*
      There is a chance commit LSN same for multiple rows and it is hard to figure out latest rows 

## How
*Describe the solution*
   There is a extra column to find out change sequence but, it was not included in airbyte output 

https://debezium.io/documentation/reference/stable/connectors/sqlserver.html

"
The connector sorts the changes that it reads in ascending order, based on the values of their commit LSN and change LSN. This sorting order ensures that the changes are replayed by Debezium in the same order in which they occurred in the database.
"

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

2023-03-13 03:54 UTC, sivankumar86 commented
@natalyjazzviolin and @akashkulk  Could you take a look when you get time ? it solves critical bug and it made entire team work on sleepless night.

2023-03-17 18:17 UTC, marcosmarxm commented
/test connector=connectors/source-mssql

2023-03-17 18:18 UTC, marcosmarxm requested changes
@sivankumar86 please fix the comment and the conflicts.

2023-03-17 18:18 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-mssql/src/main/java/io/airbyte/integrations/source/mssql/MssqlCdcConnectorMetadataInjector.java
> +}
Please fix the EOF

2023-03-17 19:58 UTC, closed without merging