Source Stripe: add stream accounts
airbytehq/airbyte pull request #23960
Opened 2023-03-11 17:37 UTC by haithem-souala

## What
Closes #9167 

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

2023-03-15 00:50 UTC, YowanR commented
@marcosmarxm @sajarin Can you assist here, please?

2023-03-15 13:48 UTC, marcosmarxm requested changes
Left some comments.

2023-03-15 13:48 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-stripe/source_stripe/schemas/accounts.json
> +      "$ref": "#/components/schemas/account_capabilities"
Please add the correct data for capabilities.

2023-03-15 13:48 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-stripe/source_stripe/schemas/accounts.json
> +      },
Please clean up the schema to follow the standard.

2023-03-15 13:48 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-stripe/source_stripe/schemas/accounts.json
> +      },
Check other Stripe streams.

2023-03-15 13:48 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-stripe/Dockerfile
> +LABEL io.airbyte.version=3.1.0
You only adding a new stream which is a patch update. Correct this to `3.0.1`

2023-03-15 13:48 UTC, marcosmarxm commented on docs/integrations/sources/stripe.md
> +https://github.com/airbytehq/airbyte/pull/23960
Remove this.

2023-03-15 13:48 UTC, marcosmarxm commented on docs/integrations/sources/stripe.md
> +| 3.1.0   | 2023-03-15 | [23960](https://github.com/airbytehq/airbyte/pull/23960) | Add `Accounts` stream
Correct version here too.

2023-03-15 17:26 UTC, haithem-souala commented
@marcosmarxm fixed.

2023-03-15 18:21 UTC, marcosmarxm commented
/test connector=connectors/source-stripe

2023-03-23 21:28 UTC, haithem-souala commented
> /test connector=connectors/source-stripe
> 
> > 🕑 connectors/source-stripe https://github.com/airbytehq/airbyte/actions/runs/4429641780
> > ❌ connectors/source-stripe https://github.com/airbytehq/airbyte/actions/runs/4429641780
> > 🐛 https://gradle.com/s/vdpzlorqzjhsu
> 
> ### Build Failed
> Test summary info:
> 
> ```
> 	 =========================== short test summary info ============================
> 	 FAILED unit_tests/test_source.py::test_source_streams - assert 25 == 24
> 	 �[31m================== �[31m�[1m1 failed�[0m, �[32m45 passed�[0m, �[33m140 warnings�[0m�[31m in 0.82s�[0m�[31m ==================�[0m
> ```

Fixed!

2023-03-24 12:23 UTC, marcosmarxm commented
/test connector=connectors/source-stripe

2023-03-24 12:34 UTC, marcosmarxm commented
/test connector=connectors/source-stripe

2023-04-05 19:45 UTC, sajarin commented
Hey thanks for the contribution and apologies for the delay! 

I'll be the DRI responsible for reviewing and getting across the finish line. We currently have a backlog of about a dozen PRs, but just wanted to let you know that this PR has been added to the queue and I'll be trying my best to get to this as soon as possible. 

Thanks for the contribution and for being patient :)

2023-04-17 17:09 UTC, marcosmarxm commented
Published at https://github.com/airbytehq/airbyte/pull/25136

2023-04-17 17:09 UTC, closed without merging