🎉 New Source: Pendo [Configuration Based Source]
airbytehq/airbyte pull request #24081
Opened 2023-03-15 05:46 UTC by YiyangLi

## What
- add a new source pendo, generated by the low-code platform

## How
- add 4 full import streams to bootstrap the new source connector
- add documentation
- add svg
- generate uuid and add a record in source_definitions.yaml
- issue: https://github.com/airbytehq/airbyte/issues/2977

## Recommended reading order
1. airbyte-integrations/connectors/source-pendo/source_pendo/manifest.yaml
2. airbyte-config/init/src/main/resources/icons/pendo.svg

## 🚨 User Impact 🚨
no, it's a new source connector

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

2023-03-15 05:47 UTC, YiyangLi commented
```
> python -m pytest integration_tests -p integration_tests.acceptance
Test session starts (platform: darwin, Python 3.9.13, pytest 6.2.5, pytest-sugar 0.9.6)
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Users/bartdev/Playground/airbyte/airbyte-integrations/connectors/source-pendo/.hypothesis/examples')
rootdir: /Users/bartdev/Playground/airbyte, configfile: pytest.ini
plugins: hypothesis-6.54.6, requests-mock-1.9.3, mock-3.6.1, sugar-0.9.6, timeout-1.4.2, cov-3.0.0
collecting ... {"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/bartdev/Playground/airbyte/airbyte-integrations/connectors/source-pendo/secrets/config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_config_match_spec[inputs0] ✓                                                                                                                     3% ▍         {"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/bartdev/Playground/airbyte/airbyte-integrations/connectors/source-pendo/secrets/config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_match_expected[inputs0] ✓                                                                                                                        6% ▋         {"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/bartdev/Playground/airbyte/airbyte-integrations/connectors/source-pendo/secrets/config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_docker_env[inputs0] ✓                                                                                                                            9% ▉         {"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/bartdev/Playground/airbyte/airbyte-integrations/connectors/source-pendo/secrets/config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_enum_usage[inputs0] ✓                                                                                                                           12% █▎        {"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/bartdev/Playground/airbyte/airbyte-integrations/connectors/source-pendo/secrets/config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_oneof_usage[inputs0] ✓                                                                                                                          15% █▌        
 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_required[inputs0] ✓                                                                                                                             18% █▊        
 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_optional[inputs0] ✓                                                                                                                             21% ██▏       
 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_has_secret[inputs0] ✓                                                                                                                           24% ██▍       
 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_secret_never_in_the_output[inputs0] ✓                                                                                                           26% ██▋       {"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/bartdev/Playground/airbyte/airbyte-integrations/connectors/source-pendo/secrets/config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_secret_is_properly_marked[inputs0] ✓                                                                                                            29% ██▉       
 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_property_type_is_not_array[inputs0] ✓                                                                                                           32% ███▎      
 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_object_not_empty[inputs0] ✓                                                                                                                     35% ███▌      
 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_array_type[inputs0] ✓                                                                                                                           38% ███▉      
 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_forbidden_complex_types[inputs0] ✓                                                                                                              41% ████▎     
 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_date_pattern[inputs0] ✓                                                                                                                         44% ████▌     
 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_date_format[inputs0] ✓                                                                                                                          47% ████▊     {"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/bartdev/Playground/airbyte/airbyte-integrations/connectors/source-pendo/secrets/config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_defined_refs_exist_in_json_spec_file[inputs0] ✓                                                                                                 50% █████     {"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/bartdev/Playground/airbyte/airbyte-integrations/connectors/source-pendo/secrets/config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_oauth_flow_parameters[inputs0] ✓                                                                                                                53% █████▍    Pulling docker image airbyte/source-pendo:latest
{"type": "LOG", "log": {"level": "WARN", "message": "\n We did not find the airbyte/source-pendo:latest image for this connector. This probably means this version has not yet been published to an accessible docker registry like DockerHub."}}
{"type": "LOG", "log": {"level": "WARN", "message": "\n We could not retrieve the previous connector spec as a connector runner for the previous connector version could not be instantiated."}}
{"type": "LOG", "log": {"level": "INFO", "message": "Using /Users/bartdev/Playground/airbyte/airbyte-integrations/connectors/source-pendo/secrets/config.json as configuration. It is the most recent version."}}

 airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py::TestSpec.test_backward_compatibility[inputs0] s                         [...]

2023-03-17 16:02 UTC, sajarin requested changes
Some comments:

2023-03-17 16:02 UTC, sajarin commented on airbyte-integrations/connectors/source-pendo/source_pendo/manifest.yaml
> +                    003k9r8idkmqq:
What do these random string ids refer to?

2023-03-17 16:02 UTC, sajarin commented on airbyte-integrations/connectors/source-pendo/source_pendo/manifest.yaml
> +                              type: string
What do these values refer to? They seem random but they also appear elsewhere here so just trying to get an idea.

2023-03-17 16:02 UTC, sajarin commented
/test connector=connectors/source-pendo

2023-03-18 21:44 UTC, YiyangLi commented
/test connector=connectors/source-pendo

2023-03-21 14:17 UTC, sajarin commented
/test connector=connectors/source-pendo

2023-03-24 20:47 UTC, misteryeo commented
**Issue was linked to Harvestr Discovery:**  [New Source: Pendo](https://app.harvestr.io/components/0/list/hQPNTlqZm)

2023-03-27 21:09 UTC, marcosmarxm approved these changes

2023-03-30 17:32 UTC, sajarin commented
/test connector=connectors/source-pendo

2023-03-30 18:19 UTC, sajarin approved these changes

2023-03-31 19:25 UTC, marcosmarxm commented
Published in https://github.com/airbytehq/airbyte/pull/24714

2023-03-31 19:25 UTC, closed without merging