update pydantic version to 1.10
airbytehq/airbyte pull request #24520
Opened 2023-03-24 18:22 UTC by mattotodd

## What
The airbyte cdk models throws an exception when trying to import in python 3.11

```
    from airbyte_protocol.models.airbyte_protocol import *
  File "/Users/mattotodd/Library/Caches/pypoetry/virtualenvs/proj-zOVad83R-py3.11/lib/python3.11/site-packages/airbyte_protocol/models/__init__.py", line 3, in <module>
    from .airbyte_protocol import *
  File "/Users/mattotodd/Library/Caches/pypoetry/virtualenvs/proj-zOVad83R-py3.11/lib/python3.11/site-packages/airbyte_protocol/models/airbyte_protocol.py", line 374, in <module>
    class AirbyteStateMessage(BaseModel):
  File "/Users/mattotodd/Library/Caches/pypoetry/virtualenvs/proj-zOVad83R-py3.11/lib/python3.11/site-packages/pydantic/main.py", line 292, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattotodd/Library/Caches/pypoetry/virtualenvs/proj-zOVad83R-py3.11/lib/python3.11/site-packages/pydantic/utils.py", line 258, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "/Users/mattotodd/.pyenv/versions/3.11.2/lib/python3.11/inspect.py", line 2722, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'global' is not a valid parameter name
```

## How
Update pydantic dependency to 1.10.  The issue is[ resolved here](https://github.com/pydantic/pydantic/issues/4011)

## 🚨 User Impact 🚨
[Breaking changes described here](https://github.com/pydantic/pydantic/releases/tag/v1.10.0a1): 

- The compiled boolean (whether pydantic is compiled with cython) has been moved from main.py to version.py
- Now that Config.extra is supported, dataclass ignores by default extra arguments (like BaseModel)

2023-03-24 18:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=24520) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=24520) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=24520) it.</sub>

2023-03-27 17:09 UTC, marcosmarxm commented
@mattotodd can you sign the CLA?

2023-03-29 17:38 UTC, sherifnada requested changes
@mattotodd the build is currently failing. FWIW the CDK only supports 3.8 and 3.9, so while I'm happy to make this change in dep versions, it needs to work on those versions of python

2023-05-25 12:29 UTC, marcosmarxm commented
Close due inactivity.

2023-05-25 12:29 UTC, closed without merging