create metadata files for all connectors
airbytehq/airbyte pull request #24964
Opened 2023-04-06 17:35 UTC by alafanechere

## What
Closes https://github.com/airbytehq/airbyte/issues/24848
I ran the `persist_metadata_definition` Dagster asset to generate these files.

2023-04-06 17:53 UTC, evantahler reviewed
It's Happening 🥳

2023-04-06 18:21 UTC, bnchrch commented
@alafanechere Before we merge lets make sure this PR is in
https://github.com/airbytehq/airbyte/pull/24840

2023-04-10 16:43 UTC, bnchrch requested changes
@alafanechere Looking good!

I think we should do the following  adjustments
1. Move any non airbyte connectors under `connectors/third-party/<AUTHOR>/<CONNECTOR>`. That should currently apply to `farosai` and `ghcr.io`
2. Remove the `devmate-cloud` subfolder of `ghcr.io`

2023-04-10 17:03 UTC, bnchrch commented on airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml
> +      dockerRepository: airbyte/source-mongodb-strict-encrypt
@alafanechere Also I think for strict encrypt we need to manually add a metadata.yml file for each.

These metadata files should
1. Have both cloud and oss catalogs disabled
2. Contain enough information to build the correct docker image
3. Have a comment acknowledging that the get deployed by their non strict encrypt sibling

2023-04-11 13:29 UTC, alafanechere commented
@bnchrch I implemented your suggestions:
> Move any non airbyte connectors under connectors/third-party/<AUTHOR>/<CONNECTOR>. That should currently apply to farosai and ghcr.io

✅ 

> Rename the ghcr.io folder to ghcr

✅ 
> Remove the devmate-cloud subfolder of ghcr.io

✅ - The `ghcr` directory is now empty, is this expected @bnchrch?

> I think for strict encrypt we need to manually add a metadata.yml file for each.

I added metadata.yaml files for strict encrypt variants. They are all disabled from cloud and oss.

2023-04-11 23:03 UTC, bnchrch approved these changes
> ✅ - The ghcr directory is now empty, is this expected @bnchrch?

@alafanechere Oh whoops! I couldve been more clear when I said

> Remove the devmate-cloud subfolder of ghcr.io

We had the following file path in the last commit
`connectors/ghcr.io/devmate-cloud/source-something/metadata.yml`

And I was thinking it should have been
`connectors/third-party/ghcr/source-something/metadata.yml`


But thats minor so ill approve now butso when your back online if you could correct that then feel free to merge!

2023-04-12 11:55 UTC, alafanechere commented
@bnchrch I
- I re-added the deleted connector in `ghrc`
- I fixed the metadata not passing validation
- I updated the model to accept `message_queue` `connectorSubType` (do you think this should be done in a separate PR?)
- The workflow to run validation was quite bulky and sometime stuck on this PR. I tweaked it a bit to make it faster and reuse existing components [here](https://github.com/airbytehq/airbyte/pull/25107).

2023-04-12 15:53 UTC, alafanechere commented
> what led you to adding the subtype?

destination-mqtt uses the `message_queue` subtype

> Were we able to do this in the overrides in the dev assets?

I did this manually . I don't think we can do it in the override for all the cases:
* Missing release stages: we can fallback to alpha
* Missing subtype: We could fallback to unknown, but I think it's better to curate these  connector subtype properly now as there was only a few.

2023-04-12 16:42 UTC, bnchrch commented
> > what led you to adding the subtype?
> 
> destination-mqtt uses the `message_queue` subtype
> 
> > Were we able to do this in the overrides in the dev assets?
> 
> I did this manually . I don't think we can do it in the override for all the cases:
> 
> * Missing release stages: we can fallback to alpha
> * Missing subtype: We could fallback to unknown, but I think it's better to curate these  connector subtype properly now as there was only a few.

Hmm no big deal but if I understand correctly you should be able to override releaseStage and subType for any connector by its connectorId [here](https://github.com/airbytehq/airbyte/blob/augustin/metadata-service/upload-metadata-files-to-gcs/airbyte-ci/connectors/metadata_service/orchestrator/orchestrator/assets/dev.py#L136)

2023-04-13 05:44 UTC, alafanechere commented
The Dagger CI infra is currently down. I ran the metadata validation locally with success. Here are the [logs](https://gist.github.com/alafanechere/41c970ed9d5a99c15f5474e7be1ca7dd). Ready to merge.

2023-04-13 05:45 UTC, merged