🐛 Source Marketo : Remove deprecated fields for the Lead sync
airbytehq/airbyte pull request #25066
Opened 2023-04-11 15:58 UTC by CyprienBarbault

## What
Removed deprecated fields from the Marketo API

## How

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Checklist
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Connector version has been incremented
    - [ ] Version has been bumped according to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines
    - [ ] `Dockerfile` has updated version
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` with an entry for the new version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)

- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<img width="571" alt="image" src="https://user-images.githubusercontent.com/105291432/231220486-dc6e13d9-9af6-43c9-a7bb-59a50873a183.png">

2023-04-11 16:20 UTC, marcosmarxm requested changes
Thanks for the contribution @CyprienBarbault made some suggestions.

2023-04-11 16:20 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-marketo/Dockerfile
> +LABEL io.airbyte.version=2.0.3
```suggestion
LABEL io.airbyte.version=2.0.0
```

2023-04-11 20:34 UTC, marcosmarxm commented
/test connector=connectors/source-marketo

2023-04-12 10:18 UTC, CyprienBarbault commented
/test connector=connectors/source-marketo

2023-04-17 08:36 UTC, CyprienBarbault commented
@marcosmarxm What are the next steps here ? When will this be merged ?

2023-04-17 14:32 UTC, marcosmarxm commented
> It is breaking our sync and blocking our stakeholders

You can build locally the new version and use a dev version during the review period.

2023-04-18 17:25 UTC, marcosmarxm commented
Hello @CyprienBarbault these fields aren't deprecated. Check Marketo documentation note:
> * Filter type is unavailable for some subscriptions.  If unavailable for your subscription, you will receive an error when calling the Create Export Lead Job endpoint (“1035, Unsupported filter type for target subscription”).  Customers may contact Marketo Support to have this functionality enabled in their subscription.

https://developers.marketo.com/rest-api/bulk-extract/bulk-lead-extract/

My recommendation is to close the issue and open one to improve the connector to not break when this happens.

2023-04-19 12:54 UTC, CyprienBarbault commented
Hey @marcosmarxm you were right, the failing fields had been hidden via our Marketo team. This was all due to bad communication.

Sorry for the time you spent investigating this MR. 

Note: you're also right on one point, the sync should not fail in this situation, maybe that's something to raise in an other ticket

2023-04-19 12:55 UTC, closed without merging