🎉 New Source: Aircall [Low code CDK]
airbytehq/airbyte pull request #25240
Opened 2023-04-17 14:33 UTC by btkcodedev

## What
*Developing new connector for the source: Aircall*

Resolves:
[Aircall](https://github.com/airbytehq/DeveloperWeek-Connector-Contest/issues/11)

## How
*Developed using (Configuration Based Source) low-code CDK*

## Recommended reading order
1. `spec.yaml`
2. `manifest.yaml`
3. `schemas/*`

## Tests

<details open><summary><strong>Integration & Acceptance</strong></summary>
Full Test Results

![image](https://user-images.githubusercontent.com/47392334/232517996-915f9232-530d-4a0f-8d99-6b1864991b61.png)

</details>

## 🚨 User Impact 🚨
- No breaking changes, Just addition of new source
<details><summary><strong>New Connector: Source Yotpo</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [ ] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

</details>

2023-04-17 14:35 UTC, btkcodedev commented
@RealChrisSean, @marcosmarxm 
PR raised for review
All acceptance tests are passing
Please ping me via slack for secret sharing

2023-04-17 14:36 UTC, btkcodedev commented
@marcosmarxm @RealChrisSean, Unfortunately, I've got only 7-day trial with aircall secrets.
I would greatly appreciate the testing as soon as possible :)
I would do my best for resolving comments

2023-04-17 14:57 UTC, marcosmarxm requested changes
Add some comments.

2023-04-17 14:57 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-aircall/source_aircall/spec.yaml
> +    date_from:
```suggestion
    start_date:
```

2023-04-17 14:57 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-aircall/source_aircall/spec.yaml
> +    api_id:
```suggestion
    app_id:
```

2023-04-17 14:57 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-aircall/source_aircall/manifest.yaml
> +          field_path: ["company"]
Please create a base RecordSelector and use `field_path: ["{{ parameters['name'] }}"]`

2023-04-17 15:06 UTC, btkcodedev commented on airbyte-integrations/connectors/source-aircall/source_aircall/manifest.yaml
> +        type: NoPagination
I have a doubt regarding pagination, 
the `page` and `per_page` is inside {meta: {}}, but the data is extracted from next field, 
Could you suggest a method for pagination

2023-04-17 16:04 UTC, btkcodedev commented on airbyte-integrations/connectors/source-aircall/source_aircall/manifest.yaml
> +        type: NoPagination
@marcosmarxm

2023-04-17 16:37 UTC, btkcodedev commented
Comments resolved and test passed

![image](https://user-images.githubusercontent.com/47392334/232552360-8b91812c-1f92-4797-b47d-125f2f1cd35f.png)

2023-04-18 18:40 UTC, marcosmarxm commented
/publish connector=connectors/source-marketo

2023-04-18 18:40 UTC, marcosmarxm commented
/publish connector=connectors/source-aircall

2023-04-18 18:58 UTC, marcosmarxm approved these changes

2023-04-18 19:19 UTC, merged