feat: new google ads full refresh custom table
airbytehq/airbyte pull request #25314
Opened 2023-04-19 13:06 UTC by jpmmcneill

## What
Add a new table for google ads full refresh custom tables

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Connector version is set to `0.0.1`
    - [ ] `Dockerfile` has version `0.0.1`
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

2023-04-19 13:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=25314) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=25314) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=25314) it.</sub>

2023-04-20 11:13 UTC, marcosmarxm commented
Thanks for the request @jpmmcneill I asked to @grubberr to take a look

2023-05-25 19:59 UTC, sh4sh commented
/test connector=connectors/source-google-ads

2023-05-25 20:25 UTC, marcosmarxm commented
@sh4sh please add one unit test to validate the cahnge.

2023-05-25 21:16 UTC, sh4sh commented
@marcosmarxm could you explain which additional unit tests would add value here? There are already unit tests for custom tables added in https://github.com/airbytehq/airbyte/pull/22703

2023-05-26 17:10 UTC, lazebnyi requested changes, later dismissed

2023-05-26 17:10 UTC, lazebnyi commented on airbyte-integrations/connectors/source-google-ads/source_google_ads/source.py
> +FULL_REFRESH_CUSTOM_TABLE = ["geo_target_constant", "custom_audience", "asset_group_listing_group_filter"]
Need bump version and update change log.

2023-05-30 17:45 UTC, sh4sh approved these changes

2023-05-30 17:48 UTC, merged