Source Amplitude: refactor Events stream
airbytehq/airbyte pull request #25317
Opened 2023-04-19 14:30 UTC by artem1205

## What
bypass OOM errors by using python CDK for Events stream
Revert https://github.com/airbytehq/airbyte/pull/25282

## How
Delete events stream from manifest and add stream python implementation. 

## Pre-merge Checklist
<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Connector version has been incremented
    - [ ] Version has been bumped according to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines
    - [ ] `Dockerfile` has updated version
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` with an entry for the new version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)

- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

2023-04-19 14:33 UTC, artem1205 commented
/test connector=connectors/source-amplitude

2023-04-19 16:50 UTC, clnoll commented
Go for it @artem1205, LGTM

2023-04-19 17:04 UTC, clnoll approved these changes
LGTM!

2023-04-19 17:19 UTC, bnchrch commented
/publish connector=connectors/source-amplitude pre-release=true

2023-04-19 17:29 UTC, lazebnyi approved these changes

2023-04-19 17:32 UTC, artem1205 commented
PR for version pin: 
https://github.com/airbytehq/airbyte-platform-internal/pull/6019

2023-04-20 08:04 UTC, artem1205 commented
/publish connector=connectors/source-amplitude pre-release=true

2023-04-20 14:33 UTC, bnchrch requested changes
Just unapproving this so it doesnt accidentally get merged

2023-04-20 15:59 UTC, bnchrch approved these changes

2023-04-20 17:47 UTC, bnchrch approved these changes

2023-04-20 18:23 UTC, artem1205 commented
/publish connector=connectors/source-amplitude

2023-04-20 19:18 UTC, bnchrch requested changes
@artem1205 I just realized we still need to update the definition file

https://github.com/airbytehq/airbyte/pull/25317/files#diff-35c72339fc14d9725ebaf33a21cd176b2eac5428893a2b2a4301942765b39abaL106

2023-04-20 19:35 UTC, bnchrch approved these changes
Approved! 

Thanks for all of the work here btw, I really do appriciate it.

2023-04-20 20:14 UTC, merged