🎉 New Source: Yotpo [Low code CDK]
airbytehq/airbyte pull request #25532
Opened 2023-04-26 01:49 UTC by btkcodedev

## What
*Developing new connector for the source: Yotpo*

Resolves:
[Yotpo](https://github.com/airbytehq/DeveloperWeek-Connector-Contest/issues/14)

## How
*Developed using (Configuration Based Source) low-code CDK*

## Recommended reading order
1. `spec.yaml`
2. `manifest.yaml`
3. `schemas/*`

## Tests

<details open><summary><strong>Integration & Acceptance</strong></summary>
Full Test Results

![image](https://user-images.githubusercontent.com/47392334/231709935-ac8eaa0f-4b7c-4667-bba7-95b2c32f9cc3.png)

</details>

## 🚨 User Impact 🚨
- No breaking changes, Just addition of new source
<details><summary><strong>New Connector: Source Yotpo</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [ ] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

</details>

2023-04-26 01:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=25532) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=25532) before we can accept your contribution.<br/>**35** out of **36** committers have signed the CLA.<br/><br/>:white_check_mark: girarda<br/>:white_check_mark: btkcodedev<br/>:white_check_mark: bnchrch<br/>:white_check_mark: ryankfu<br/>:white_check_mark: akashkulk<br/>:white_check_mark: richardlam-quotapath<br/>:white_check_mark: sh4sh<br/>:white_check_mark: alafanechere<br/>:white_check_mark: arsenlosenko<br/>:white_check_mark: vladimir-remar<br/>:white_check_mark: flash1293<br/>:white_check_mark: artem1205<br/>:white_check_mark: clnoll<br/>:white_check_mark: henriblancke<br/>:white_check_mark: erohmensing<br/>:white_check_mark: jnr0790<br/>:white_check_mark: colesnodgrass<br/>:white_check_mark: rach-r<br/>:white_check_mark: josephkmh<br/>:white_check_mark: lmossman<br/>:white_check_mark: cpdeethree<br/>:white_check_mark: sergio-ropero<br/>:white_check_mark: marcosmarxm<br/>:white_check_mark: domzae<br/>:white_check_mark: pedroslopez<br/>:white_check_mark: jooststessens<br/>:white_check_mark: anamargaridarl<br/>:white_check_mark: cynthiaxyin<br/>:white_check_mark: cjwooo<br/>:white_check_mark: suhomud<br/>:white_check_mark: edgao<br/>:white_check_mark: rileybrook<br/>:white_check_mark: jhajajaas<br/>:white_check_mark: penberg<br/>:white_check_mark: iberchid<br/>:x: midavadim<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=25532) it.</sub>

2023-04-26 01:51 UTC, btkcodedev commented
Please add hackathon-developer-week label

2023-04-26 01:51 UTC, btkcodedev commented
Conflicts resolved :)
Thanks

2023-04-26 01:56 UTC, btkcodedev commented
@marcosmarxm conflicts resolved from https://github.com/airbytehq/airbyte/pull/25145

2023-04-26 21:04 UTC, marcosmarxm commented
/test connector=connectors/source-yopto

2023-04-26 21:55 UTC, btkcodedev commented
Fixed some expected records as the platform is auto rejecting some of the seeded content for some reason
Recent Test Results - All passed

![image](https://user-images.githubusercontent.com/47392334/234711831-b737f0e9-abcf-421d-9e60-c8137299381b.png)

2023-04-27 11:28 UTC, marcosmarxm commented
/test connector=connectors/source-yopto

2023-04-27 14:25 UTC, marcosmarxm requested changes

2023-04-27 14:25 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-yotpo/source_yotpo/schemas/email_analytics.json
> +      "properties": {}
missing properties.

2023-04-27 14:27 UTC, marcosmarxm commented
/test connector=connectors/source-yopto

2023-04-27 14:35 UTC, marcosmarxm commented
/test connector=connectors/source-yotpo

2023-04-27 15:13 UTC, marcosmarxm commented
/test connector=connectors/source-yotpo

2023-04-27 16:34 UTC, marcosmarxm commented
/test connector=connectors/source-yotpo

2023-04-27 18:04 UTC, btkcodedev commented on airbyte-integrations/connectors/source-yotpo/source_yotpo/schemas/email_analytics.json
> +      "properties": {}
Resolved

2023-05-01 20:39 UTC, marcosmarxm commented
/test connector=connectors/source-yotpo

2023-05-01 21:07 UTC, marcosmarxm commented
/test connector=connectors/source-yotpo

2023-05-01 21:18 UTC, marcosmarxm approved these changes
Thanks for the contribution @btkcodedev

2023-05-01 21:18 UTC, marcosmarxm commented
/publish connector=connectors/source-yotpo

2023-05-01 22:14 UTC, merged