initial code
airbytehq/airbyte pull request #25682
Opened 2023-04-28 18:35 UTC by dhanjimahto

## What
Initial code for vertica database connector

## How
Adding new destination connector

2023-04-28 18:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=25682) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=25682) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=25682) it.</sub>

2023-05-01 22:38 UTC, marcosmarxm commented
Please update your PR following https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention

2023-05-01 23:04 UTC, marcosmarxm commented
@dhanjimahto please update the PR following https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests/#pull-request-title-convention instructions.

2023-05-02 06:13 UTC, dhanjimahto commented
@marcosmarxm i updated PR based on instruction mentioned in 
https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests/#pull-request-title-convention
 Please review it.

2023-05-04 06:52 UTC, dhanjimahto commented
Hi Team,

Issue - While running testcases locally some test cases are failing because it is not able to find files "source_config.json","destination_config.json", "destination_catalog.json" during test case execution.

Below are steps to reproduce it on local system & we are attaching exception logs, screenshot & logs, pdf also.

Steps to run integration test cases.
1. Take this PR code on your local system and build it locally (Connector -> destination-vertica).
2. Pull image of vertica from link  & run it through terminal - https://hub.docker.com/r/vertica/vertica-ce
3. Config file attached here.
4.  To run integration test case run below command from airbyte root directory
                  ./gradlew :airbyte-integrations:connectors:destination-vertica:integrationTest
5. You will get test cases failure along with report. we are attaching screenshot of failed test cases along with exception in file named "[Integration test case logs.txt.txt](https://github.com/airbytehq/airbyte/files/11394374/Integration.test.case.logs.txt.txt)"
![Test cases failed](https://user-images.githubusercontent.com/122617093/236130322-757513df-911c-4d64-a791-d8dcca82c489.jpg)
[Test results - VerticaDestinationAcceptanceTest.pdf](https://github.com/airbytehq/airbyte/files/11394375/Test.results.-.VerticaDestinationAcceptanceTest.pdf)
[config.txt](https://github.com/airbytehq/airbyte/files/11394397/config.txt)

2023-05-05 15:50 UTC, evantahler commented
@marcosmarxm a cursory glance at the code seems OK!  Can you please build this connector and set up a test sandbox for it?  

@dhanjimahto - Can you please add a documentation markdown file for this connector following an example in `docs/destinations` and add an icon please?

2023-05-08 14:15 UTC, dhanjimahto commented
@evantahler 
I have added markdown file as well as icon file.
Please review code & let me know anything else need to be done from my end.

2023-05-11 11:49 UTC, dhanjimahto commented
Hi Team,
Now we have 100 % test case success rate.
Please see screenshot.

![image](https://github.com/airbytehq/airbyte/assets/122617093/023daff4-2bd3-4c6e-bcb0-92a97a5a985a)

2023-05-11 15:22 UTC, evantahler commented
/test connector=connectors/destination-vertica

2023-05-15 09:53 UTC, dhanjimahto commented
> > Hi Team, Now we have 100 % test case success rate. Please see screenshot.
> > ![image](https://user-images.githubusercontent.com/122617093/237677411-023daff4-2bd3-4c6e-bcb0-92a97a5a985a.png)
> 
> Can you push this version to Github?

@marcosmarxm  We got this 100 % passed test case because we manually used hard coded connection to database, which we discussed in our office hour.
Later we discussed in office hour, to have vertica database instance running on cloud & we can connect it using hard coded connection.
We did same thing but now at test case 26 it stuck & not moving further.

We will discuss this in office hour.

2023-05-19 20:16 UTC, marcosmarxm commented
/test connector=connectors/destination-vertica

2023-05-19 20:17 UTC, marcosmarxm commented
> [![CLA assistant check](https://camo.githubusercontent.com/4c970efeed75dd01f6778bf7e33dec85e4171375cb69acb0927bfc9d437d78d9/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f6e6f745f7369676e6564)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=25682) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=25682) before we can accept your contribution.**1** out of **2** committers have signed the CLA.✅ dhanjimahto❌ rakeshsimplify3xaccountYou have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=25682) it.

@rakeshsimplify3xaccount @dhanjimahto both contributors must sign the CLA. Please make sure its solved.

2023-05-24 19:11 UTC, dhanjimahto commented
Hi Airbyte team,

AS per our discussion, now we are pointing to database running on a cluster & getting 100% test case pass.
Please see below screenshot for reference.
Requesting you to please trigger test case for this branch on CI/CD pipe line.

![image](https://github.com/airbytehq/airbyte/assets/122617093/2e499b7d-ab75-4628-b5c8-0d4eef243ae3)

2023-05-25 14:35 UTC, marcosmarxm commented
/test connector=connectors/destination-vertica

2023-05-25 15:21 UTC, dhanjimahto commented
> @dhanjimahto can you add the `metadata.yaml` file check other connectors in the main branch.

Sure, will do & update you

2023-05-29 06:28 UTC, dhanjimahto commented
> > @dhanjimahto can you add the `metadata.yaml` file check other connectors in the main branch.
> 
> Sure, will do & update you

I added metadata.yml. Please check

2023-05-29 06:29 UTC, dhanjimahto commented
> > > @dhanjimahto can you add the `metadata.yaml` file check other connectors in the main branch.
> > 
> > 
> > Sure, will do & update you
> 
> @marcosmarxm  I added metadata.yml. Please check

2023-05-29 06:29 UTC, dhanjimahto commented
> > > > @dhanjimahto can you add the `metadata.yaml` file check other connectors in the main branch.
> > > 
> > > 
> > > Sure, will do & update you
> > 
> > 
> > @marcosmarxm  I added metadata.yml. Please let's us know what next needs to be done.

2023-05-29 06:29 UTC, dhanjimahto commented
> > > > > @dhanjimahto can you add the `metadata.yaml` file check other connectors in the main branch.
> > > > 
> > > > 
> > > > Sure, will do & update you
> > > 
> > > 
> > > @marcosmarxm  I added metadata.yml. Please let us know what next needs to be done.

2023-05-29 12:58 UTC, marcosmarxm commented
/test connector=connectors/destination-vertica

2023-05-29 20:22 UTC, marcosmarxm requested changes

2023-05-29 20:22 UTC, marcosmarxm commented on airbyte-integrations/connectors/destination-vertica/metadata.yml
> +      enabled: true
```suggestion
      enabled: false
```

2023-05-29 20:23 UTC, marcosmarxm requested changes

2023-05-29 20:23 UTC, marcosmarxm commented on docs/integrations/destinations/vertica.md
> +
Add the changelog.

2023-05-29 20:23 UTC, marcosmarxm commented on airbyte-integrations/connectors/destination-vertica/.dockerignore
> +!build
Please move the icon to this folder and rename it to `icon.svg`

2023-05-30 14:38 UTC, marcosmarxm commented
Published https://github.com/airbytehq/airbyte/pull/26718

2023-05-30 14:38 UTC, closed without merging