Source Facebook Marketing: expand time_increment config, add date_preset config
airbytehq/airbyte pull request #25704
Opened 2023-05-01 06:46 UTC by scottleechua

## What

Solves Issue #14391:

"When fetching reach data, we oftentimes want monthly... or even lifetime aggregations over campaigns or ads. With the current [Airbyte] implementation of `time_increment`, this is not possible. The Insights API does [allow for such specifications though](https://developers.facebook.com/docs/marketing-api/insights/parameters/v14.0), using the `date_preset` and `time_increment` parameters.

- To fetch lifetime data we would set `date_preset` = `maximum` and `time_increment` = `all_days`
- To fetch monthly data we would set `date_preset` = `maximum` and `time_increment` = `monthly`

The `time_increment` configuration currently only allows for values [1,89] in days and defaults to 1."

## How

- Expand `time_increment` type from positive integer only, to also include the exact strings `all_days` and `monthly`
- Add attribute `date_preset = maximum` to the `AdsInsights` stream.
- Update date interval handling to allow monthly increments.

## 🚨 User Impact 🚨
No breaking changes. User can optionally use `all_days` and `monthly` as `time_increment`.

## Pre-merge Actions
<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

2023-05-01 16:43 UTC, marcosmarxm requested changes
@scottleechua you must add unit test to validate all these changes. Please let me know if you need any assistance to add them.

2023-05-02 00:37 UTC, scottleechua commented
Hi @marcosmarxm, would greatly appreciate help on the unit tests!

My thought is to add two more test states containing:
1. `"time_increment": "monthly"`
2. `"time_increment": "all_days"`

to `unit_tests/test_base_insight_streams.py`:

```
    @pytest.mark.parametrize(
        "state",
        [
            {
                AdsInsights.cursor_field: "2010-10-03",
                "slices": [
                    "2010-01-01",
                    "2010-01-02",
                ],
                "time_increment": 1,
            },
            {
                AdsInsights.cursor_field: "2010-10-03",
            },
            {
                "slices": [
                    "2010-01-01",
                    "2010-01-02",
                ]
            },
        ],
    )
```

but it's not clear what the current unit tests are doing.

Also would need help testing this as I don't have a Facebook Marketing sandbox API 🙏 

What do you think?

2023-07-07 12:28 UTC, davydov-d requested changes
@scottleechua thanks for you effort. I've left some comments, also I have a feeling that we're trying to mix things up. The `time_increment` option we used to have in the config is not the equivalent of the `time_increment` in FB API. We used the first one to slice date range, but the second one is rather a `group by` period from my perspective. 
Another request is to cover such changes with a new entry in CAT config and unit tests as well; also current state of the PR needs the conflict to be resolved.

2023-07-07 12:28 UTC, davydov-d commented on airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/base_insight_streams.py
> +        date_preset: str = "maximum",
According to the [FB API doc](https://developers.facebook.com/docs/marketing-api/reference/adgroup/insights/) - `This field is ignored if time_range or time_ranges is specified.`, so I guess this wouldn't work as expected

2023-07-07 12:28 UTC, davydov-d commented on airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/base_insight_streams.py
> +            yield from date_range.range("days", self.time_increment)
very likely you will get an error here if `time_increment == "all_days"`

2023-07-07 12:28 UTC, davydov-d commented on airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/base_insight_streams.py
> +            pass
what's the sense of this statement?

2023-07-07 12:28 UTC, davydov-d commented on airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/base_insight_streams.py
> +            pass
did you mean to add `else` afterwards?

2023-08-15 14:55 UTC, bmcgilli commented
Hey @scottleechua! Are you still able to work with @davydov-d on this contribution? Please let us know or we will close it, thanks

2023-08-29 12:58 UTC, closed without merging

2023-08-29 12:58 UTC, scottleechua commented
@bmcgilli @davydov-d Sorry, I'm not able to continue work on this! Please go ahead and close the PR. 🙏