:tada: Source Amplitude:  added missing attrs in events schema, enabled default availability strategy
airbytehq/airbyte pull request #25842
Opened 2023-05-05 13:31 UTC by midavadim

added missing attrs in events schema, 
enabled default avilability strategy

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

2023-05-05 13:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=25842) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=25842) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=25842) it.</sub>

2023-05-05 13:34 UTC, midavadim commented
/test connector=connectors/source-amplitude

2023-05-05 14:16 UTC, artem1205 requested changes
availability strategy was removed, because for this stream API may return 404 (see [docs](https://www.docs.developers.amplitude.com/analytics/apis/export-api/#response) ) during read of first slice.

2023-05-05 15:51 UTC, midavadim commented
> availability strategy was removed, because for this stream API may return 404 (see [docs](https://www.docs.developers.amplitude.com/analytics/apis/export-api/#response) ) during read of first slice.

@artem1205 
404 error is caught at line 163 and stream just returns empty list of records.
So this error does not get to 'availability strategy' handler

2023-05-05 15:56 UTC, artem1205 commented
Yep, but this means that availability strategy is useless here, isn't it?

2023-05-05 15:57 UTC, midavadim commented
> Yep, but this means that availability strategy is useless here, isn't it?

I suppose it can handle another types of errors, what do you think?

2023-05-05 16:00 UTC, artem1205 approved these changes

2023-05-09 14:15 UTC, erohmensing reviewed
Nice work! Could you please also add the missing column declarations to the cohorts stream? Here are all of the missing columns from the past week (they look pretty much teh same last month) 

<img width="1613" alt="image" src="https://github.com/airbytehq/airbyte/assets/22333512/dccf7bc1-e730-4fed-8c54-539113ceb08c">

This comes from the "please check the datadog dashboard" note [here](https://github.com/airbytehq/airbyte/issues/24480#issuecomment-1488885878).  I guess our test doesn't catch it because `cohorts` is declared as an empty stream.

2023-05-09 14:15 UTC, erohmensing commented on airbyte-integrations/connectors/source-amplitude/acceptance-test-config.yml
> -        fail_on_extra_columns: false
Woot 🥳

2023-05-09 14:15 UTC, erohmensing commented on airbyte-integrations/connectors/source-amplitude/source_amplitude/streams.py
> -        return None
Just double checked - I think @midavadim is right. The availability strategy's `get_first_record_for_slice` calls `stream.read_records` so the 404 error handling that returns empty records should work, and the AS should say "connected to stream, but got 0 records". So this should work in that case 👍🏻

2023-05-09 19:07 UTC, maxi297 approved these changes
LGTM given Ella's concern is addressed!

2023-05-09 20:53 UTC, erohmensing commented
@midavadim that's fine with me! If any of the types are wrong, that's on the documentation, not us. And we'll catch them in the schema validation errors. Thank you! ⭐

2023-05-09 20:53 UTC, erohmensing approved these changes

2023-05-09 20:54 UTC, erohmensing commented
Then I think we can safely close #24480 as well :)

2023-05-09 21:32 UTC, midavadim commented
/publish connector=connectors/source-amplitude

2023-05-10 08:45 UTC, merged