🐛Source Amazon Ads: fix `portfolioId` type
airbytehq/airbyte pull request #25874
Opened 2023-05-08 07:19 UTC by roman-yermilov-gl

## What
*Fix `portfolioId` type to integer ([Docs](https://advertising.amazon.com/API/docs/en-us/reporting/v3/metrics#portfolioid))*

2023-05-09 11:01 UTC, roman-yermilov-gl commented
/test connector=connectors/source-amazon-ads

2023-05-10 12:08 UTC, lazebnyi approved these changes

2023-05-11 08:57 UTC, alafanechere requested changes
@roman-yermilov-gl this type change is a breaking change. I'm going to create a breaking change release plan that I will share in this PR. Could you please link the original issue that led you to implement this change? Is there any functional implication in keeping these fields as decimal today? If it prevents you from deserializing the API response I would suggest to use a type transformer. If this is leading to unusable data on the destination side this change is indeed required.

2023-05-11 08:57 UTC, alafanechere commented on airbyte-integrations/connectors/source-amazon-ads/Dockerfile
> +LABEL io.airbyte.version=1.0.5
```suggestion
LABEL io.airbyte.version=2.0.0
```

2023-05-11 08:57 UTC, alafanechere commented on airbyte-integrations/connectors/source-amazon-ads/metadata.yaml
> +  dockerImageTag: 1.0.5
```suggestion
  dockerImageTag: 2.0.0
```

2023-05-11 08:57 UTC, alafanechere commented on docs/integrations/sources/amazon-ads.md
> +| 1.0.5   | 2023-05-08 | [25874](https://github.com/airbytehq/airbyte/pull/25874) | Type `portfolioId` as integer                                                                                   |
```suggestion
| 2.0.0   | 2023-05-08 | [25874](https://github.com/airbytehq/airbyte/pull/25874) | Type `portfolioId` as integer                                                                                   |
```

2023-05-11 09:42 UTC, alafanechere commented
@roman-yermilov-gl here's the [breaking change release plan draft](https://docs.google.com/document/d/1zWtBOmn85IqxecgXpNHY_72T3ZubsGGGUN8skxByH2c/edit#). I'd need more context on why this change is introduced to move forward.

2023-05-11 09:43 UTC, alafanechere requested changes
@roman-yermilov-gl do you confirm the modified streams are present in the configured catalog we use for acceptance tests? Could you please update the expected records file with data corresponding to the modified streams?

2023-05-11 19:56 UTC, alafanechere commented
@roman-yermilov-gl thank you for the details. I updated the breaking change document. I suspect the error mentioned #17623 to only impact BigQuery denormalized. As we have no test data it's hard to assess the breadth of this problem. I suggest to not merge it until we either:
* Have more evidence that this bug is widespread and impacting multiple users
* Having a painless release strategy for breaking change

2023-05-12 13:10 UTC, roman-yermilov-gl commented
> @roman-yermilov-gl thank you for the details. I updated the breaking change document. I suspect the error mentioned #17623 to only impact BigQuery denormalized. As we have no test data it's hard to assess the breadth of this problem. I suggest to not merge it until we either:
> 
> * Have more evidence that this bug is widespread and impacting multiple users
> * Having a painless release strategy for breaking change

I agree but what would be your suggestion for next steps? Should I put the task https://github.com/airbytehq/airbyte/issues/17623 on hold?

2023-05-16 21:03 UTC, alafanechere commented
> I agree but what would be your suggestion for next steps? Should I put the task https://github.com/airbytehq/airbyte/issues/17623 on hold? 

Yes I think so. I'll ask on the issue to try to seed the account with seed data.

2023-05-26 10:59 UTC, roman-yermilov-gl commented
> > I agree but what would be your suggestion for next steps? Should I put the task #17623 on hold?
> 
> Yes I think so. I'll ask on the issue to try to seed the account with seed data.

Hi @alafanechere 
Is there updates on this isssue?

2023-05-26 11:44 UTC, alafanechere commented
@roman-yermilov-gl I got not update from the stakeholders on #17623
Now that [we can feature flag connectors](https://airbytehq-team.slack.com/archives/C02UF50V9HA/p1685026337296189) on cloud I encourage you to take ownership on this [doc](https://docs.google.com/document/d/1zWtBOmn85IqxecgXpNHY_72T3ZubsGGGUN8skxByH2c/edit#heading=h.r2xzw0kclodc) and suggest a rollout plan in coordination with TCS.

2023-05-31 13:45 UTC, roman-yermilov-gl commented
/test connector=connectors/source-amazon-ads

2023-06-12 09:59 UTC, roman-yermilov-gl commented
/test connector=connectors/source-amazon-ads

2023-06-12 10:19 UTC, roman-yermilov-gl commented
/publish connector=connectors/source-amazon-ads pre-release=true run-tests=false

2023-06-15 13:28 UTC, alafanechere commented
Updating the branch to get a fresh CI run.

2023-06-15 13:33 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/fa1f4176a25528d07e473c7299ca6fdaebd762aa/airbyte-integrations/connectors/source-amazon-ads/icon.svg" width="40" height="40"> source-amazon-ads test report (commit [`fa1f4176a2`](https://github.com/airbytehq/airbyte/pull/25874/commits/fa1f4176a25528d07e473c7299ca6fdaebd762aa)) - ❌

⏲️  Total pipeline duration: 197 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check.                                          | ✅        |
| Connector version increment check.                                       | ✅        |
| QA checks                                                                | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5279427071)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

2023-06-20 13:12 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/39f549b39cc0f052861afff637429cba9588c819/airbyte-integrations/connectors/source-amazon-ads/icon.svg" width="40" height="40"> source-amazon-ads test report (commit [`39f549b39c`](https://github.com/airbytehq/airbyte/pull/25874/commits/39f549b39cc0f052861afff637429cba9588c819)) - ❌

⏲️  Total pipeline duration: 195 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check.                                          | ✅        |
| Connector version increment check.                                       | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5322952165)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

2023-06-20 15:37 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/9c41aeb7e6c08ae3dd6a4f8208285849ec3cb4eb/airbyte-integrations/connectors/source-amazon-ads/icon.svg" width="40" height="40"> source-amazon-ads test report (commit [`9c41aeb7e6`](https://github.com/airbytehq/airbyte/pull/25874/commits/9c41aeb7e6c08ae3dd6a4f8208285849ec3cb4eb)) - ✅

⏲️  Total pipeline duration: 194 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check.                                          | ✅        |
| Connector version increment check.                                       | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5324540529)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

2023-06-20 16:17 UTC, alafanechere approved these changes

2023-06-20 16:19 UTC, bnchrch approved these changes

2023-06-20 16:22 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/221cdc4104092baecfa47fcc5a4d784507139021/airbyte-integrations/connectors/source-amazon-ads/icon.svg" width="40" height="40"> source-amazon-ads test report (commit [`221cdc4104`](https://github.com/airbytehq/airbyte/pull/25874/commits/221cdc4104092baecfa47fcc5a4d784507139021)) - ✅

⏲️  Total pipeline duration: 211 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check.                                          | ✅        |
| Connector version increment check.                                       | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5324979540)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

2023-06-20 16:22 UTC, merged