🐛Source MySQL: remove SSL toggle for OSS MySQL
airbytehq/airbyte pull request #26050
Opened 2023-05-13 00:49 UTC by nguyencongphap

## What
[Issue #24883](https://github.com/airbytehq/airbyte/issues/24883)
According to [nguyenaiden](https://github.com/nguyenaiden?scrlybrkr=29e8f549),
"Currently, MySQL has a SSL Connection toggle to enable/disable traffic encryption. This does not match with our Postgres source connector (OSS)."

## Solution
Remove the ssl key from `spec.json` for `source-postgres` and rely on `ssl_mode` key as the source of truth.

2023-05-13 00:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=26050) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=26050) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=26050) it.</sub>

2023-05-13 01:36 UTC, nguyencongphap commented
/test connector=connectors/source-mysql

2023-05-17 21:30 UTC, marcosmarxm requested changes

2023-05-17 21:30 UTC, marcosmarxm commented on airbyte-config-oss/init-oss/src/main/resources/seed/source_specs.yaml
> -          description: "Encrypt data using SSL."
The proposal is to add the disabled option in SSL mode too.

2023-05-18 18:25 UTC, marcosmarxm commented
@nguyencongphap please check my comment and please resolve the conflicts.

2023-05-25 18:12 UTC, rodireich commented on airbyte-config-oss/init-oss/src/main/resources/seed/oss_catalog.json
> +    "dockerImageTag": "2.0.22",
No longer need to do this with publish on merge (I don't think file exists anymore)

2023-05-25 18:12 UTC, rodireich commented on airbyte-integrations/connectors/source-mysql/Dockerfile
> +LABEL io.airbyte.version=2.0.22
mysql incremented since - bump to latest

2023-05-25 18:12 UTC, rodireich commented on docs/integrations/sources/mysql.md
> +| 2.0.22  | 2023-05-12 | [26050](https://github.com/airbytehq/airbyte/pull/26050)   | Removed SSL toggle and rely on SSL mode dropdown to enable/disable SSL
bump version

2023-06-06 15:06 UTC, nguyencongphap commented
> @nguyencongphap are you planning to continue this work?

Hi Marcos. I have been having a hard time figuring out how to add the disabled option in SSL mode, and I am not planning to continue this work. Thank you for your patience.

2023-06-06 17:04 UTC, closed without merging