🎉Source Stripe: New Streams - Prices
airbytehq/airbyte pull request #26127
Opened 2023-05-16 17:06 UTC by btkcodedev

## What
Closes #16967

## Enhancement
New streams: 

- Prices

## Recommended reading order
1. `source_stripe/source.py`
2. `source_stripe/streams.py`
3.  `source_stripe/schemas/*`

## 🚨 User Impact 🚨
No breaking changes

## Pre-merge Checklist
<details open><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter [Yes]

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Issue acceptance criteria met
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [x] Documentation which references the generator is updated as needed

2023-05-16 17:21 UTC, marcosmarxm requested changes, later dismissed
Small change.

2023-05-16 17:21 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-stripe/Dockerfile
> +LABEL io.airbyte.version=3.5.0
Please update the metadata file too.

2023-05-16 17:27 UTC, btkcodedev commented on airbyte-integrations/connectors/source-stripe/Dockerfile
> +LABEL io.airbyte.version=3.5.0
metadata.yaml updated :)

2023-05-22 18:10 UTC, sajarin requested changes
great job implementing this stream! let's rebase on master and i'll get the integration tests rolling

2023-05-22 18:10 UTC, sajarin commented on airbyte-integrations/connectors/source-stripe/source_stripe/schemas/prices.json
> +    },
Looking at other streams, could this be a date-time formatted string instead of a number?

2023-05-22 18:10 UTC, sajarin commented on airbyte-config-oss/init-oss/src/main/resources/seed/source_definitions.yaml
>    sourceType: api
Can you delete this file? We're no longer using this file on master and instead are relying on metadata.yaml moving forward.

2023-05-22 18:10 UTC, sajarin commented on airbyte-config-oss/init-oss/src/main/resources/seed/source_specs.yaml
>      connectionSpecification:
Can you delete this file? We're no longer using this file on master and instead are relying on metadata.yaml moving forward.

2023-05-30 12:33 UTC, marcosmarxm commented
@btkcodedev are you planning to continue this contribution?

2023-06-07 16:12 UTC, sh4sh commented
/test connector=connectors/source-stripe

2023-06-14 19:45 UTC, marcosmarxm commented
@btkcodedev can you fix the conflicts. CI is working again after that we can run and ge tthis merged.

2023-06-17 15:27 UTC, btkcodedev commented
@marcosmarxm Conflicts resolved

2023-07-12 17:29 UTC, btkcodedev commented
@sajarin @marcosmarxm Conflicts resolved, Ready to merge

2023-07-27 18:26 UTC, sajarin approved these changes

2023-07-27 18:27 UTC, sajarin commented
Thanks @btkcodedev for the new stream!

2023-07-27 18:27 UTC, merged