🎉Source Stripe: New Streams - Persons
airbytehq/airbyte pull request #26208
Opened 2023-05-17 19:01 UTC by btkcodedev

## What
Closes #16965

## Enhancement
New streams: 

- Persons

## Recommended reading order
1. `source_stripe/source.py`
2. `source_stripe/streams.py`
3.  `source_stripe/schemas/*`

## 🚨 User Impact 🚨
No breaking changes

## Pre-merge Checklist
<details open><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter [Yes]

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Issue acceptance criteria met
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [x] Documentation which references the generator is updated as needed
+

2023-05-22 20:11 UTC, archangelic commented on airbyte-integrations/connectors/source-stripe/source_stripe/streams.py
> +
Need to declare `cusor_field = "created"` here.

2023-05-22 20:15 UTC, archangelic commented on airbyte-integrations/connectors/source-stripe/source_stripe/schemas/persons.json
> +          "type": ["null", "string"]
These properties are integers per https://stripe.com/docs/api/persons/object#person_object-dob-day

2023-05-22 20:18 UTC, archangelic commented on airbyte-integrations/connectors/source-stripe/source_stripe/schemas/persons.json
> +        "alternatives": {
The properties of this object doesn't align with what stripe says the structure should be. https://stripe.com/docs/api/persons/object#person_object-requirements-alternatives

2023-05-22 20:37 UTC, archangelic requested changes
Thanks for your contribution! I have added some suggested changes. Let me know if there are any questions.

2023-05-22 20:37 UTC, archangelic commented on airbyte-integrations/connectors/source-stripe/source_stripe/schemas/persons.json
> +  "properties": {
It looks like we are missing some properties. If we can add the following just to ensure full compatibility: `phone, email, address_kana, address_kanji, first_name_kana, first_name_kanji, full_name_aliases, gender, id_number_secondary_provided, maiden_name, nationality, political_exposure, registered_address`

2023-05-22 20:37 UTC, archangelic commented on airbyte-integrations/connectors/source-stripe/source_stripe/schemas/persons.json
> +      "type": "number"
```suggestion
      "type": ["null", "integer"]
```

2023-06-08 13:40 UTC, marcosmarxm commented
@archangelic can we get an update in this contribution?

2023-06-09 18:58 UTC, archangelic commented on airbyte-integrations/connectors/source-stripe/source_stripe/schemas/persons.json
> +          "type": ["null", "string"]
`day`, `month`, and `year` need to be set to integers.

2023-06-09 18:59 UTC, archangelic commented on airbyte-integrations/connectors/source-stripe/source_stripe/schemas/persons.json
> +        "alternatives": {
According to the docs, `alternatives` should have 2 properties `alternative_fields_due` and `original_fields_due` that are arrays of strings.

2023-06-09 19:01 UTC, archangelic commented
Looks like there just needs two areas with changes, then we can continue with getting this merged!

2023-07-14 18:17 UTC, midavadim approved these changes

2023-07-14 20:12 UTC, merged

2023-07-14 20:14 UTC, midavadim commented
Related PR with CI tests:
https://github.com/airbytehq/airbyte/pull/28322