🎉Source Zendesk Support: New Stream - Organization Fields
airbytehq/airbyte pull request #26327
Opened 2023-05-20 18:23 UTC by btkcodedev

## What
Closes #16871

## Enhancement
New streams: 

- Organization Fields

## Recommended reading order
1. `source_stripe/source.py`
2. `source_stripe/streams.py`
3.  `source_stripe/schemas/*`

## 🚨 User Impact 🚨
No breaking changes

## Pre-merge Checklist
<details open><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter [Yes]

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Issue acceptance criteria met
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [x] Documentation which references the generator is updated as needed
+

2023-05-20 19:04 UTC, btkcodedev commented
Update: Awaiting creds for adding expected records

2023-05-23 20:55 UTC, archangelic requested changes
Thanks for your contribution. I have listed out some recommended changes.

2023-05-23 20:55 UTC, archangelic commented on airbyte-integrations/connectors/source-zendesk-support/unit_tests/unit_test.py
> +            (OrganizationFields, {}, {"updated_at": "2022-03-17T16:03:07Z"}, {"updated_at": "2022-03-17T16:03:07Z"})
Missing comma
```suggestion
            (OrganizationFields, {}, {"updated_at": "2022-03-17T16:03:07Z"}, {"updated_at": "2022-03-17T16:03:07Z"}),
```

2023-05-23 20:55 UTC, archangelic commented on airbyte-integrations/connectors/source-zendesk-support/source_zendesk_support/schemas/organization_fields.json
> +    "properties": {
Please add the following missing properties: `custom_field_options, relationship_filter, relationship_target_type, system, tag` per [the documentation](https://developer.zendesk.com/api-reference/ticketing/organizations/organization_fields/#json-format).

Also, the indentation needs to be fixed.

2023-05-30 12:33 UTC, marcosmarxm commented
@btkcodedev are you planning to continue this contribution?

2023-06-07 22:56 UTC, archangelic commented
Pushed more fixes. Still have some unit tests that are blocking completion.

2023-07-06 11:51 UTC, darynaishchenko approved these changes

2023-07-06 11:58 UTC, darynaishchenko reviewed
please, merge conflicts and if CI checks are still running you can close and reopen PR to fix it.

2023-07-06 12:09 UTC, darynaishchenko requested changes
could you add expected_records for this stream?

2023-07-09 16:17 UTC, btkcodedev commented
Merge conflicts cleared, 
Tried to generate data to the endpoint via cURL, but has scope issue:
Error ref: `{
    "error": "Forbidden",
    "description": "You are missing the following required scopes: write"
}`

2023-07-10 10:16 UTC, darynaishchenko commented on airbyte-integrations/connectors/source-zendesk-support/unit_tests/unit_test.py
> +        ),
Just for my understanding, why with identical  ticket_forms_response and status_code we receive different number of streams? 20 and 27 for 200 status code, 19 and 24 for 403 status code

2023-07-20 16:15 UTC, btkcodedev commented
@darynaishchenko Unit test fixed, Please continue further review :)

2023-07-25 14:36 UTC, darynaishchenko commented
@btkcodedev Hi, sorry for delay, could you please merge conflicts.

2023-07-25 14:47 UTC, btkcodedev commented
@darynaishchenko Conflicts cleared :)

2023-08-04 22:35 UTC, bmcgilli commented
@darynaishchenko can you please follow up? @lazebnyi

2023-08-08 16:05 UTC, darynaishchenko approved these changes

2023-08-08 16:42 UTC, darynaishchenko commented
@archangelic Hi, could you please review this PR?  it's blocked by your approve.

2023-08-21 18:57 UTC, archangelic approved these changes

2023-08-21 18:57 UTC, archangelic commented
@darynaishchenko Sorry about that. I've approved!

2023-09-04 14:20 UTC, btkcodedev commented
@darynaishchenko Please continue the review as it got two approvals :)

2023-09-05 15:26 UTC, closed without merging