🐛 Source Slack: fix `lookback window` value range limits
airbytehq/airbyte pull request #26497
Opened 2023-05-24 15:29 UTC by bazarnov

## What
Resolving: https://github.com/airbytehq/oncall/issues/2115
The previous fix for `0.1.26` actually didn't work, because of `min`/`max` abbreviations are not supported by JSON Schema, the `minimum`/`maximum` should be used instead.

## How
- edited `spec.json` with `min` > `minimum`, `max` > `maximum`

## ✅ User Impact Level ✅ : Non-breaking change

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

2023-05-24 15:33 UTC, bazarnov commented
/test connector=connectors/source-slack

2023-05-24 15:51 UTC, davydov-d requested changes

2023-05-24 15:51 UTC, davydov-d commented on airbyte-integrations/connectors/source-slack/Dockerfile
> +LABEL io.airbyte.version=0.1.27
looks like a breaking change, shouldn't this be a major version bump?

2023-05-24 15:51 UTC, artem1205 requested changes

2023-05-24 15:51 UTC, artem1205 commented on airbyte-integrations/connectors/source-slack/acceptance-test-config.yml
> +        disable_for_version: "0.1.25"
```suggestion
        disable_for_version: "0.1.26"
```

2023-05-24 15:55 UTC, bazarnov commented on airbyte-integrations/connectors/source-slack/acceptance-test-config.yml
> +        disable_for_version: "0.1.25"
done

2023-05-24 15:57 UTC, bazarnov commented
/test connector=connectors/source-slack

2023-05-24 15:57 UTC, artem1205 approved these changes

2023-05-24 16:00 UTC, sherifnada approved these changes

2023-05-24 16:17 UTC, bnchrch approved these changes

2023-05-25 05:27 UTC, bazarnov commented
/test connector=connectors/source-slack

2023-05-25 05:50 UTC, davydov-d approved these changes

2023-05-25 05:54 UTC, merged