:tada: Source Hubspot - fixed incremental for engagement stream
airbytehq/airbyte pull request #27161
Opened 2023-06-08 16:59 UTC by midavadim

## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

2023-06-08 16:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=27161) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=27161) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=27161) it.</sub>

2023-06-08 17:02 UTC, midavadim commented
/test connector=connectors/source-hubspot

2023-06-08 21:29 UTC, midavadim commented
/test connector=connectors/source-hubspot

2023-06-09 10:48 UTC, midavadim commented
/test connector=connectors/source-hubspot

2023-06-12 12:47 UTC, lazebnyi requested changes
Please fill PR description

2023-06-16 12:30 UTC, lazebnyi approved these changes
LGTM! Small refactoring required.

2023-06-16 12:30 UTC, lazebnyi commented on airbyte-integrations/connectors/source-hubspot/source_hubspot/streams.py
> +                since_date = pendulum.from_timestamp(int(since_date_timestamp) / 1000)
More pythonic way) 

since_date_timestamp = stream_state.get(self.updated_at_field) if stream_state else stream_state
since_date = pendulum.from_timestamp(int(since_date_timestamp) / 1000) if since_date_timestamp else self._start_date

2023-06-19 19:15 UTC, bnchrch commented
@midavadim This is looking good. I noticed we checked
> [Breaking changes are considered](https://docs.airbyte.com/contributing-to-airbyte/#breaking-changes-to-connectors). If a Breaking Change is being introduced, ensure an Airbyte engineer has created a Breaking Change Plan and you've followed all steps in the [Breaking Changes Checklist](https://docs.airbyte.com/contributing-to-airbyte/#checklist-for-contributors)

Do we have a link to the breaking change plan?

2023-06-20 20:09 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/b88292b7293314f1ea1d0f721fae7c73b74e9199/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`b88292b729`](https://github.com/airbytehq/airbyte/pull/27161/commits/b88292b7293314f1ea1d0f721fae7c73b74e9199)) - ❌

⏲️  Total pipeline duration: 13 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ❌        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5326932126)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-06-20 20:09 UTC, midavadim commented
Connector Hubspot Breaking Change Release Playbook
https://docs.google.com/document/d/1_TSS7NbXU6rCtMXOUMeAm_x7C5ZLmKPBuH8bZzl4FzY/edit

2023-06-20 20:31 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/1533d7b5556e90016334b95cc0c0ce882c44636f/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`1533d7b555`](https://github.com/airbytehq/airbyte/pull/27161/commits/1533d7b5556e90016334b95cc0c0ce882c44636f)) - ❌

⏲️  Total pipeline duration: 134 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ❌        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5327101008)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-06-20 21:36 UTC, bnchrch approved these changes

2023-06-21 12:28 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/6ac4ffcc13aeb6773990af8ff9dd4272a5b0b05d/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`6ac4ffcc13`](https://github.com/airbytehq/airbyte/pull/27161/commits/6ac4ffcc13aeb6773990af8ff9dd4272a5b0b05d)) - ❌

⏲️  Total pipeline duration: 599 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5333932864)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-06-21 15:12 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/6ac4ffcc13aeb6773990af8ff9dd4272a5b0b05d/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`6ac4ffcc13`](https://github.com/airbytehq/airbyte/pull/27161/commits/6ac4ffcc13aeb6773990af8ff9dd4272a5b0b05d)) - ❌

⏲️  Total pipeline duration: 135 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5333932864)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-06-22 12:34 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/6ac4ffcc13aeb6773990af8ff9dd4272a5b0b05d/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`6ac4ffcc13`](https://github.com/airbytehq/airbyte/pull/27161/commits/6ac4ffcc13aeb6773990af8ff9dd4272a5b0b05d)) - ❌

⏲️  Total pipeline duration: 584 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5333932864)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-06-22 12:51 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/9c386821d7acba82704015de7c3cbc175ef91649/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`9c386821d7`](https://github.com/airbytehq/airbyte/pull/27161/commits/9c386821d7acba82704015de7c3cbc175ef91649)) - ❌

⏲️  Total pipeline duration: 566 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/midavadim_26365-hubspot-fix-incremental-sync/1687437690/9c386821d7acba82704015de7c3cbc175ef91649/source-hubspot/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-06-22 13:36 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/9c386821d7acba82704015de7c3cbc175ef91649/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`9c386821d7`](https://github.com/airbytehq/airbyte/pull/27161/commits/9c386821d7acba82704015de7c3cbc175ef91649)) - ✅

⏲️  Total pipeline duration: 11 seconds

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/midavadim_26365-hubspot-fix-incremental-sync/1687440952/9c386821d7acba82704015de7c3cbc175ef91649/source-hubspot/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-06-22 13:49 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/b1c3ddf29113c28377173097325e8b77ca5fb2b1/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`b1c3ddf291`](https://github.com/airbytehq/airbyte/pull/27161/commits/b1c3ddf29113c28377173097325e8b77ca5fb2b1)) - ✅

⏲️  Total pipeline duration: 14 seconds

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/midavadim_26365-hubspot-fix-incremental-sync/1687441738/b1c3ddf29113c28377173097325e8b77ca5fb2b1/source-hubspot/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-06-22 14:05 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/b1c3ddf29113c28377173097325e8b77ca5fb2b1/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`b1c3ddf291`](https://github.com/airbytehq/airbyte/pull/27161/commits/b1c3ddf29113c28377173097325e8b77ca5fb2b1)) - ❌

⏲️  Total pipeline duration: 684 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/midavadim_26365-hubspot-fix-incremental-sync/1687442049/b1c3ddf29113c28377173097325e8b77ca5fb2b1/source-hubspot/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-06-22 14:38 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/b1c3ddf29113c28377173097325e8b77ca5fb2b1/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`b1c3ddf291`](https://github.com/airbytehq/airbyte/pull/27161/commits/b1c3ddf29113c28377173097325e8b77ca5fb2b1)) - ✅

⏲️  Total pipeline duration: 648 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/midavadim_26365-hubspot-fix-incremental-sync/1687444069/b1c3ddf29113c28377173097325e8b77ca5fb2b1/source-hubspot/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-06-22 18:03 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/798fed7a2b940d141d722ccd51418670020271f2/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`798fed7a2b`](https://github.com/airbytehq/airbyte/pull/27161/commits/798fed7a2b940d141d722ccd51418670020271f2)) - ✅

⏲️  Total pipeline duration: 687 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/midavadim_26365-hubspot-fix-incremental-sync/1687456274/798fed7a2b940d141d722ccd51418670020271f2/source-hubspot/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-06-22 19:54 UTC, wmikemoon commented
@midavadim This will be scheduled for 06/29/23 at 12:00PM EST. I will send outreach today. Please let me know if anything changes!

2023-06-29 16:03 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/9338c20892d0fd1f5bf438bf7bc2e7073e2702fc/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`9338c20892`](https://github.com/airbytehq/airbyte/pull/27161/commits/9338c20892d0fd1f5bf438bf7bc2e7073e2702fc)) - ❌

⏲️  Total pipeline duration: 11mn31s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ❌        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/midavadim_26365-hubspot-fix-incremental-sync/1688053904/9338c20892d0fd1f5bf438bf7bc2e7073e2702fc/source-hubspot/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-06-29 18:41 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/b887d914d8e3c307fb69de7b3f3de49695fc0ab0/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`b887d914d8`](https://github.com/airbytehq/airbyte/pull/27161/commits/b887d914d8e3c307fb69de7b3f3de49695fc0ab0)) - ❌

⏲️  Total pipeline duration: 11mn46s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ❌        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/midavadim_26365-hubspot-fix-incremental-sync/1688063349/b887d914d8e3c307fb69de7b3f3de49695fc0ab0/source-hubspot/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-06-29 18:55 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/7ab2e20d43a4512525907296413543b6b0bdd564/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`7ab2e20d43`](https://github.com/airbytehq/airbyte/pull/27161/commits/7ab2e20d43a4512525907296413543b6b0bdd564)) - ❌

⏲️  Total pipeline duration: 10mn32s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ❌        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/midavadim_26365-hubspot-fix-incremental-sync/1688064250/7ab2e20d43a4512525907296413543b6b0bdd564/source-hubspot/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-06-29 19:09 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/575e1f510671ba385516ae7b5a039edc215b413c/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`575e1f5106`](https://github.com/airbytehq/airbyte/pull/27161/commits/575e1f510671ba385516ae7b5a039edc215b413c)) - ❌

⏲️  Total pipeline duration: 10mn43s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ❌        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/midavadim_26365-hubspot-fix-incremental-sync/1688065087/575e1f510671ba385516ae7b5a039edc215b413c/source-hubspot/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-06-29 19:27 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/072ada4d4ea9d6da2d0469f0677a0b7321409ab7/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`072ada4d4e`](https://github.com/airbytehq/airbyte/pull/27161/commits/072ada4d4ea9d6da2d0469f0677a0b7321409ab7)) - ✅

⏲️  Total pipeline duration: 10mn46s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/midavadim_26365-hubspot-fix-incremental-sync/1688066204/072ada4d4ea9d6da2d0469f0677a0b7321409ab7/source-hubspot/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-06-29 19:50 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/87f8431072928417e88ae708c131ed7a0ef62210/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`87f8431072`](https://github.com/airbytehq/airbyte/pull/27161/commits/87f8431072928417e88ae708c131ed7a0ef62210)) - ❌

⏲️  Total pipeline duration: 10mn37s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/midavadim_26365-hubspot-fix-incremental-sync/1688067594/87f8431072928417e88ae708c131ed7a0ef62210/source-hubspot/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-06-29 20:27 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/8597d5309ca269c3201ece6aeb672412f9e8f7da/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`8597d5309c`](https://github.com/airbytehq/airbyte/pull/27161/commits/8597d5309ca269c3201ece6aeb672412f9e8f7da)) - ❌

⏲️  Total pipeline duration: 18.07s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/midavadim_26365-hubspot-fix-incremental-sync/1688070393/8597d5309ca269c3201ece6aeb672412f9e8f7da/source-hubspot/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-06-29 20:39 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/8597d5309ca269c3201ece6aeb672412f9e8f7da/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`8597d5309c`](https://github.com/airbytehq/airbyte/pull/27161/commits/8597d5309ca269c3201ece6aeb672412f9e8f7da)) - ❌

⏲️  Total pipeline duration: 17.18s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/midavadim_26365-hubspot-fix-incremental-sync/1688071121/8597d5309ca269c3201ece6aeb672412f9e8f7da/source-hubspot/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-06-29 20:45 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/8597d5309ca269c3201ece6aeb672412f9e8f7da/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`8597d5309c`](https://github.com/airbytehq/airbyte/pull/27161/commits/8597d5309ca269c3201ece6aeb672412f9e8f7da)) - ❌

⏲️  Total pipeline duration: 17.51s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/midavadim_26365-hubspot-fix-incremental-sync/1688071474/8597d5309ca269c3201ece6aeb672412f9e8f7da/source-hubspot/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-06-29 22:12 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/3f21afa99ed1c3735536a354fe67e17249e7e225/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`3f21afa99e`](https://github.com/airbytehq/airbyte/pull/27161/commits/3f21afa99ed1c3735536a354fe67e17249e7e225)) - ✅

⏲️  Total pipeline duration: 10mn43s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/midavadim_26365-hubspot-fix-incremental-sync/1688076078/3f21afa99ed1c3735536a354fe67e17249e7e225/source-hubspot/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-06-29 22:12 UTC, merged