✨Source Stripe: New Stream - ShippingRates
airbytehq/airbyte pull request #27217
Opened 2023-06-09 18:23 UTC by btkcodedev

## What
Closes #26481

## Enhancement
New streams: 

- Shipping Rates

## Recommended reading order
1. `source_stripe/source.py`
2. `source_stripe/streams.py`
3.  `source_stripe/schemas/*`

## 🚨 User Impact 🚨
No breaking changes

## Pre-merge Checklist
<details open><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter [Yes]

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Issue acceptance criteria met
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [x] Documentation which references the generator is updated as needed
+

2023-06-14 17:04 UTC, sajarin commented
Can you resolve the merge conflicts here?

2023-07-07 12:52 UTC, davydov-d requested changes
Left some minor comments, but please also update the connector version in the Dockerfile and metadata.yaml

2023-07-07 12:52 UTC, davydov-d commented on airbyte-integrations/connectors/source-stripe/source_stripe/schemas/shipping_rates.json
> +    "delivery_estimate": {},
I don't think this is a valid typing, please update it

2023-07-07 12:52 UTC, davydov-d commented on docs/integrations/sources/stripe.md
> +| 3.7.0   | 2023-06-09 | [27217](https://github.com/airbytehq/airbyte/pull/27217) | Add `ShippingRates` stream
please bump version here

2023-07-10 07:00 UTC, davydov-d approved these changes

2023-07-10 08:11 UTC, davydov-d commented
@btkcodedev you'll have to also run code formatting and fix unit tests please
`python -m black --config=/pyproject.toml --check .`
`python -m pytest unit_tests`

2023-07-12 18:30 UTC, btkcodedev commented
@davydov-d I've fixed unit tests, but can't help with code formatting as I am facing some issues with the usage of the command.
Could you please check

2023-07-13 07:58 UTC, davydov-d commented
@btkcodedev please run `./gradlew airbyte-integrations:connectors:source-stripe:airbytePythonFormat` from the project root instead

2023-07-20 15:46 UTC, btkcodedev commented
@davydov-d Ran code formatting, Fixed Unit tests, Cleared conflicts

2023-07-25 14:44 UTC, btkcodedev commented
@davydov-d I am using one of the forks of master for the PRs, I could not change the remote inorder to rebase from your branch, Could you cherrypick changes and push to this PR?
Sorry for that :)

2023-07-25 14:49 UTC, davydov-d commented
> @davydov-d I am using one of the forks of master for the PRs, I could not change the remote inorder to rebase from your branch, Could you cherrypick changes and push to this PR? Sorry for that :)

@btkcodedev yep, working on that. A bit messed up, but will figure it out soon

2023-07-25 15:07 UTC, merged