✨Source Airtable: new stream `Collaborators`
airbytehq/airbyte pull request #27230
Opened 2023-06-10 18:25 UTC by gittysachin

## What
Closes #23896 

## Enhancement
New streams:

* Collaborators

## Recommended reading order
1. `streams.py`
2. `source.py`

## 🚨 User Impact 🚨
No breaking changes

## Pre-merge Actions

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

2023-06-15 19:16 UTC, marcosmarxm requested changes
Please let me know if my comment makes sense! Thanks for the contribution.

2023-06-16 03:49 UTC, gittysachin commented on airbyte-integrations/connectors/source-airtable/source_airtable/streams.py
> +            return AirtableStream(stream_path=stream_path, stream_name=stream_name, stream_schema=stream_schema, authenticator=authenticator)
It's not used right now but I thought can be used later.

2023-06-16 03:51 UTC, gittysachin commented on airbyte-integrations/connectors/source-airtable/source_airtable/source.py
> +                )
Got it, will change

2023-06-16 03:53 UTC, gittysachin commented on airbyte-integrations/connectors/source-airtable/source_airtable/streams.py
> +        yield from workspace_collaborators
Sure

2023-06-20 15:17 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-airtable/source_airtable/streams.py
> +            return AirtableStream(stream_path=stream_path, stream_name=stream_name, stream_schema=stream_schema, authenticator=authenticator)
If its not used remove it. When you need add the implementation.

2023-06-20 18:31 UTC, closed without merging

2023-06-20 18:31 UTC, gittysachin commented
Will raise PRs with correct commits