New Source: Rippling connector
airbytehq/airbyte pull request #27242
Opened 2023-06-12 12:49 UTC by anaselmhamdi

## What
This PR proposes a new Rippling connector as we use it at Gorgias. ([see issue](https://github.com/airbytehq/airbyte/issues/4173))
It embeds employee privacy features if needed as you can filter out sensitive fields like compensation, SSN or other personal details.

## How
- The connector is a Python source
- The only configuration needed is a Rippling API token with read scopes on all resources-> You can do this via the Rippling Admin Dashboard now.
- You can also supply filters to hide employees details in the Source config
![image](https://github.com/airbytehq/airbyte/assets/19236824/7aa34309-1d7c-4573-924a-6010719f2c78)

## Acceptance tests

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

2023-06-12 12:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=27242) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=27242) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=27242) it.</sub>

2023-06-12 17:07 UTC, sajarin requested changes
Thanks for the PR! Left some comments:

2023-06-12 17:07 UTC, sajarin commented on airbyte-integrations/connectors/source-rippling/Dockerfile
> +LABEL io.airbyte.version=0.0.1
The version here should match the metadata.yaml file (0.1.0)

2023-06-12 17:07 UTC, sajarin commented on airbyte-integrations/connectors/source-rippling/source_rippling/schemas/company_leave_types.json
> +  "properties": {
Can you set additionalProperties to true for each of the schema files? https://docs.airbyte.com/connector-development/schema-reference/

2023-06-12 17:07 UTC, sajarin commented on airbyte-integrations/connectors/source-rippling/source_rippling/schemas/company_leave_types.json
> +    }
Can you null these types? It will help make this connector more robust with api regressions

2023-06-12 17:07 UTC, sajarin commented on airbyte-integrations/connectors/source-rippling/source_rippling/schemas/leave_balances.json
> +      "items": {
Same comments above regarding additionalProperties and nullable types

2023-06-12 17:07 UTC, sajarin commented on airbyte-integrations/connectors/source-rippling/source_rippling/schemas/leave_requests.json
> +      "type": "string"
Same comments above regarding additionalProperties and nullable types

2023-06-12 17:07 UTC, sajarin commented on airbyte-integrations/connectors/source-rippling/source_rippling/spec.yaml
> +      type: string
Can you add an order field to api_key and employee_filters? https://docs.airbyte.com/connector-development/connector-specification-reference/#ordering-fields-in-the-ui

2023-06-12 17:07 UTC, sajarin commented on airbyte-integrations/connectors/source-rippling/unit_tests/test_source.py
> +    assert len(streams) == expected_streams_number
Can you verify if this is the correct number of streams?

2023-06-12 17:07 UTC, sajarin commented on docs/integrations/sources/rippling.md
> +| 0.0.1   | 2023-06-12 | [27242](https://github.com/airbytehq/airbyte/pull/27242) | New source |
Can you correct the version here in the changelog?

2023-06-13 11:00 UTC, anaselmhamdi commented
@sajarin I should have adressed all the points you touched on, also here's a preview of what the fields look like with the order (i also added a group)
![image](https://github.com/airbytehq/airbyte/assets/19236824/d992c3c2-4d94-4a4a-aae9-b06532ed6532)

2023-06-14 17:55 UTC, sajarin commented
Hey @anaselmhamdi thanks for making the requested changes. Right now we're waiting on obtaining credentials on our side for Rippling so we can test the connector. Thanks for being patient

2023-06-20 15:14 UTC, marcosmarxm commented
Amost done with the sandbox account.

2023-07-24 14:51 UTC, anaselmhamdi commented
> @anaselmhamdi Hi, I'm interested in the Rippling connector, could you tell me please if there is possible to receive the information about payrolls? I found an API route [GET Employees](https://developer.rippling.com/docs/rippling-api/aac33093e278e-get-employees) but there is no info about payrolls, probably it stored in an event from webhooks `payroll_run.paid`

Hi ! Not sure it's possible to GET the payroll as - like you mentioned- it seems to be described as an event by Rippling. 
However, everything you need to know about an employee's salary is stored under the `compensation` field

2023-07-24 15:33 UTC, marcosmarxm commented
Hello @anaselmhamdi and @dromix sorry the delay to come back to this contribution. There are some information in [Rippling ToS](https://app.rippling.com/developer/tos). Airbyte's team will contact Rippling to make sure if the connector doesn't violate their terms. Any update return to you.

2023-07-26 22:54 UTC, marcosmarxm commented
Still waiting the return from our email to Rippling team.

2023-07-27 12:04 UTC, marcosmarxm commented
@anaselmhamdi hope you're doing well! I wanted to give you an update on the PR. Unfortunately, the connector infringes upon Rippling's ToS, so we won't be able to add it to Airbyte's catalog at the moment. But don't worry, our team is committed to trying to negotiate with Rippling and get the necessary permission to enable their users to move their data with Airbyte.

I want to extend a big thank you for all the effort you've put into this work. Your contributions are greatly appreciated, and we value your dedication to making Airbyte even better! If in the future Rippling allow Airbyte's to ingest their data I'll reopen the contribution.

2023-07-27 12:04 UTC, closed without merging

2023-07-27 12:55 UTC, anaselmhamdi commented
> @anaselmhamdi hope you're doing well! I wanted to give you an update on the PR. Unfortunately, the connector infringes upon Rippling's ToS, so we won't be able to add it to Airbyte's catalog at the moment. But don't worry, our team is committed to trying to negotiate with Rippling and get the necessary permission to enable their users to move their data with Airbyte.
> 
> I want to extend a big thank you for all the effort you've put into this work. Your contributions are greatly appreciated, and we value your dedication to making Airbyte even better! If in the future Rippling allow Airbyte's to ingest their data I'll reopen the contribution.

 No worries @marcosmarxm, thanks for the update 🙂

2024-03-06 22:09 UTC, ctoprimer commented
@marcosmarxm Hey I found this thread as I was looking for a Rippling connector in Airbyte and see it violates the ToS.  I'm a Rippling customer so I want to at least let them know that blocking the Airbyte usage is suboptimal.  Can you clarify which term it violates?  I see multiple clauses.  2.2 (Developer Tools) and 2.4 (Integration Restrictions) imply that approval is required, which should be easy enough to get.  3.1.2, 3.1.3, and 3.1.4 imply that "ETLs", "scraping", and use by Airbyte Cloud would be objectionable.  Is there anything else?