🎉 New Source: Medallia connector
airbytehq/airbyte pull request #27245
Opened 2023-06-12 15:37 UTC by JamesGouldSonos

## What
This PR proposes a new Medallia connector, the initial iteration provides the ability to sync Fields and Feedback entities.

## How

- The connector is a Python source using the Airbyte CDS
- The only configuration needed is Medallia OAUTH credentials and API endpoint details for your instance.

## 🚨 User Impact 🚨
None
*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

2023-06-12 15:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=27245) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=27245) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=27245) it.</sub>

2023-06-15 13:23 UTC, marcosmarxm commented
@JamesGouldSonos do you have a test account to share to run tests?

2023-06-15 14:02 UTC, JamesGouldSonos commented
Hi Marcos,

Apologies I do have a Medallia account we have been using this with but
this is not a generic account we can share for testing purposes,

KInd Regards,

James

On Thu, Jun 15, 2023 at 9:23 AM Marcos Marx ***@***.***>
wrote:

> @JamesGouldSonos
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JamesGouldSonos&d=DwMCAg&c=rs51NVPNx2acMvSlALPpNg&r=xZ8ySlPyOpNMdiLuSbPNlCAeNlDk8PC6v2nYn1mrfA0&m=Z4WSzb4bZy_rnT21X3Opa4byVejC821Xe_9XsExEjacxZLW-gH9jYV8l2OrcD2CI&s=x8825YPWRuvUpcbOK__1SlblzOatuDdrrYcye-t08cQ&e=>
> do you have a test account to share to run tests?
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_airbytehq_airbyte_pull_27245-23issuecomment-2D1593051766&d=DwMCAg&c=rs51NVPNx2acMvSlALPpNg&r=xZ8ySlPyOpNMdiLuSbPNlCAeNlDk8PC6v2nYn1mrfA0&m=Z4WSzb4bZy_rnT21X3Opa4byVejC821Xe_9XsExEjacxZLW-gH9jYV8l2OrcD2CI&s=pV-SnyPAM53sZujbKh3vMFHqkJJbe2ki8pqrgJCIE6w&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AU3ZU6VU6LTWSEMABO364MDXLMEGXANCNFSM6AAAAAAZDSCXHA&d=DwMCAg&c=rs51NVPNx2acMvSlALPpNg&r=xZ8ySlPyOpNMdiLuSbPNlCAeNlDk8PC6v2nYn1mrfA0&m=Z4WSzb4bZy_rnT21X3Opa4byVejC821Xe_9XsExEjacxZLW-gH9jYV8l2OrcD2CI&s=xyWIDHBL1D2Jy6oYUcgbCvicF5oTEB1JBFXW6LFEukE&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-05 13:46 UTC, marcosmarxm commented
> Connector

@JamesGouldSonos can you share the output from the integration tests to make sure all tests are working?

2023-07-05 13:53 UTC, marcosmarxm requested changes
Sorry the delay to review the contribution. Some comments and need the output from integration tests. Also it is missing the documentation page with the changelog.

2023-07-05 13:53 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-medallia/integration_tests/configured_catalog.json
> +        "name": "table_name",
This must have the streams you have implemented for the connector.

2023-07-05 13:53 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-medallia/unit_tests/unit_test.py
> +    assert True
Please add unit test for the custom auth and the schema validation.

2023-07-05 13:53 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-medallia/source_medallia/schemas/feedback.json
> +     "id": {
Make sure you follow https://docs.airbyte.com/connector-development/schema-reference

2023-07-05 13:53 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-medallia/source_medallia/source.py
> +        question_columns = list(filter(lambda x: x.startswith('q_'), nodes))
Can you create constant tuple like METADATA_PREFIX_COLUMN and QUESTION_PREFIX_COLUMN?

2023-07-05 13:53 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-medallia/source_medallia/source.py
> +        return {'query': str(op)}
Please create a unit test to validate this complex function.

2023-07-05 13:53 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-medallia/source_medallia/source.py
> +
Only 2 lines.

2023-07-10 16:09 UTC, JamesGouldSonos commented on airbyte-integrations/connectors/source-medallia/source_medallia/source.py
> +            Feedback(**initialization_params)
Yes the stream just had the two connectors, Survey responses (Feedback) and the Fields information (details about the survey questions.)

2023-07-11 17:36 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-sap-odata/source_sap_odata/authenticator.py
> +from urllib import parse
Please remove this

2023-10-05 15:27 UTC, closed without merging