Source Google Analytics (GA4): Add dimensionFilter and metricFilter
airbytehq/airbyte pull request #27264
Opened 2023-06-12 19:08 UTC by mpetrykin

## What
Add dimensionFilter and metricFilter parameters to custom_report_shema.json. This PR relates to issue #27119.

## How
Add dimensionFilter, metricFilter and filters' expressions described in [runReport documentation](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/runReport) and in [FilterExpression documentation](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/FilterExpression) to custom_report_shema.json.

2023-06-14 16:04 UTC, mpetrykin commented
@marcosmarxm hi! Can i ask you to review this?

2023-06-15 17:04 UTC, sajarin requested changes
Thanks for the PR and feature request! 

Could you run the format command: `./gradlew --no-daemon  :airbyte-integrations:connectors:source-google-analytics-data-api:airbytePythonFormat`

And commit the files?

2023-06-15 21:25 UTC, mpetrykin commented
@sajarin done  :heavy_check_mark:

2023-06-16 18:57 UTC, mpetrykin commented
/test connector=connectors/source-google-analytics-data-api

2023-06-21 16:17 UTC, sajarin approved these changes

2023-06-27 09:33 UTC, mpetrykin commented
@grubberr, @bazarnov Hello! Could you help me with accepting the pull request, because this feature helps to save API credits, so that it will be possible to specify, for example, certain events that the API should return, and thereby reduce the amount of data returned.

2023-06-28 14:08 UTC, marcosmarxm requested changes

2023-07-10 12:38 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-google-analytics-data-api/source_google_analytics_data_api/source.py
> +        metric_filter = report.get("metricFilter")
@mpetrykin did you check my latest comment?

2023-07-24 16:56 UTC, closed without merging