Source Salesloft: Add new streams (call data records, call dispositions, call sentiments, custom fields, meetings, searches) #27504
airbytehq/airbyte pull request #27505
Opened 2023-06-20 14:33 UTC by markortleb-dice

## What
This pull request will add the following streams to the Salesloft Source. Here are the new streams:
* Call Data Records
* Call Dispositions
* Call Sentiments
* Custom Fields
* Meetings
* Searches

## How
These new Salesloft Source streams were added in the line with the same pattern that all previous Salesloft Source streams
have. The only stream that was a bit different was Searches, which has a POST request rather than GET (which all other
Salesloft Source streams have).

## 🚨 User Impact 🚨
There are no breaking changes in this 1.2.0 release. In this change, we are only adding net-new Salesloft Source streams.
We made no modifications to existing streams.

## Pre-merge Actions

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

2023-06-20 14:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=27505) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=27505) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=27505) it.</sub>

2023-06-22 15:53 UTC, markortleb-dice commented
> ### Before Merging a Connector Pull Request
> Wow! What a great pull request you have here! 🎉
> 
> To merge this PR, ensure the following has been done/considered for each connector added or updated:
> 
> * [x]  PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention)
> * [x]  [Breaking changes are considered](https://docs.airbyte.com/contributing-to-airbyte/#breaking-changes-to-connectors). If a **Breaking Change** is being introduced, ensure an Airbyte engineer has created a Breaking Change Plan and you've followed all steps in the [Breaking Changes Checklist](https://docs.airbyte.com/contributing-to-airbyte/#checklist-for-contributors)
> * [x]  Connector version has been incremented in the Dockerfile and metadata.yaml according to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines
> * [x]  Secrets in the connector's spec are annotated with `airbyte_secret`
> * [x]  All documentation files are up to date. (README.md, bootstrap.md, docs.md, etc...)
> * [x]  Changelog updated in `docs/integrations/<source or destination>/<name>.md` with an entry for the new version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
> * [x]  The connector tests are passing in CI
> * [x]  You've updated the connector's `metadata.yaml` file (new!)
> * [x]  If set, you've ensured the icon is present in the `platform-internal` repo. ([Docs](https://docs.airbyte.com/connector-development/connector-metadata-file/#the-icon-field))
> 
> If the checklist is complete, but the CI check is failing,
> 
> 1. Check for hidden checklists in your PR description
> 2. Toggle the github label `checklist-action-run` on/off to re-run the checklist CI.

2023-06-27 15:18 UTC, sajarin requested changes
Thanks for the PR! Left some comments:

2023-06-27 15:18 UTC, sajarin commented on airbyte-integrations/connectors/source-salesloft/metadata.yaml
> +  dockerImageTag: 1.1.2
Same comment as above: https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors

2023-06-27 15:18 UTC, sajarin commented on airbyte-integrations/connectors/source-salesloft/source_salesloft/schemas/call_dispositions.json
> +    "id": {
Can you and additionalProperties and set it to true? https://docs.airbyte.com/connector-development/schema-reference/

2023-06-27 15:18 UTC, sajarin commented on airbyte-integrations/connectors/source-salesloft/source_salesloft/schemas/searches.json
> +    "id": {
Can you and additionalProperties and set it to true? https://docs.airbyte.com/connector-development/schema-reference/

2023-06-27 15:18 UTC, sajarin commented on docs/integrations/sources/salesloft.md
> +| 1.1.2   | 2023-06-20 | [27505](https://github.com/airbytehq/airbyte/pull/27505) | Added new streams (Call Data Records, Call Dispositions, ... )    |
Can you bump this to 1.2.0? Based on semantic versioning here: https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors

2023-06-29 15:17 UTC, sajarin submitted a review, later dismissed
A couple of more formatting things: 

Run the ` ./gradlew --no-daemon  :airbyte-integrations:connectors:source-salesloft:airbytePythonFormat` command to format the files and commit them

Bump the number of streams in the test_streams file (expected streams should be 29 now instead of 23)

2023-06-29 19:34 UTC, markortleb-dice commented
> A couple of more formatting things:
> 
> Run the ` ./gradlew --no-daemon :airbyte-integrations:connectors:source-salesloft:airbytePythonFormat` command to format the files and commit them
> 
> Bump the number of streams in the test_streams file (expected streams should be 29 now instead of 23)

Thank you for the feedback @sajarin . As requested, I was able to run that Gradle command which automatically formatted the Salesloft files, and I also changed the expected number of streams from 23 to 29.

2023-06-30 14:40 UTC, marcosmarxm commented
@markortleb-dice you must sign the CLA.

2023-06-30 15:29 UTC, markortleb-dice commented
> @markortleb-dice you must sign the CLA.

CLA is now signed!

2023-07-07 14:20 UTC, marcosmarxm requested changes, later dismissed
There are some fixes need to be made in this contribution @markortleb-dice.

2023-07-07 14:20 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-salesloft/source_salesloft/source.py
> +        return "call_dispositions"
This stream can't be incremental because it doesn't allow to filter records based on `updated_at` parameter.

2023-07-07 14:20 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-salesloft/source_salesloft/source.py
> +        return "call_sentiments"
This stream can't be incremental because it doesn't allow to filter records based on `updated_at` parameter.

2023-07-07 14:20 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-salesloft/source_salesloft/source.py
> +        return "meetings"
This stream the correct field is `created_at`

2023-07-07 14:20 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-salesloft/source_salesloft/source.py
> +        return "custom_fields"
This stream can't be incremental because it doesn't allow to filter records based on `updated_at` parameter.

2023-07-11 18:50 UTC, archangelic approved these changes

2023-07-11 20:49 UTC, merged