:tada: Source Amazon Ads -  add sponsored_display_budget_rules stream
airbytehq/airbyte pull request #27512
Opened 2023-06-20 16:14 UTC by midavadim

## What
Add sponsored_display_budget_rules stream

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
No

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

2023-06-20 16:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=27512) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=27512) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=27512) it.</sub>

2023-06-20 16:19 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/0827b81682677674f55bfdc385c6bca26b853117/airbyte-integrations/connectors/source-amazon-ads/icon.svg" width="40" height="40"> source-amazon-ads test report (commit [`0827b81682`](https://github.com/airbytehq/airbyte/pull/27512/commits/0827b81682677674f55bfdc385c6bca26b853117)) - ✅

⏲️  Total pipeline duration: 201 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check.                                          | ✅        |
| Connector version increment check.                                       | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5324953003)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

2023-06-20 16:24 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/f6372510f380bcce74a03b75b8f8982d87a8f8f7/airbyte-integrations/connectors/source-amazon-ads/icon.svg" width="40" height="40"> source-amazon-ads test report (commit [`f6372510f3`](https://github.com/airbytehq/airbyte/pull/27512/commits/f6372510f380bcce74a03b75b8f8982d87a8f8f7)) - ✅

⏲️  Total pipeline duration: 192 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check.                                          | ✅        |
| Connector version increment check.                                       | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5324974379)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

2023-06-22 15:17 UTC, lazebnyi requested changes
Please update PR description and fix conflicts.

2023-06-23 10:05 UTC, midavadim commented
> Please update PR description and fix conflicts

Let's process with review approval, there are a lot of continuous changes to Amazon Ads connector.

2023-06-23 11:39 UTC, lazebnyi requested changes
Please add link to issue and to provider doc with endpoint description and still need fix conflicts.

2023-06-23 12:15 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/4aad15af82ed6dc565807b27a24b261708acbdcc/airbyte-integrations/connectors/source-amazon-ads/icon.svg" width="40" height="40"> source-amazon-ads test report (commit [`4aad15af82`](https://github.com/airbytehq/airbyte/pull/27512/commits/4aad15af82ed6dc565807b27a24b261708acbdcc)) - ❌

⏲️  Total pipeline duration: 139 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check.                                          | ✅        |
| Connector version increment check.                                       | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/midavadim_26401-source-amazon-sponsored-display-budget-rules/1687522384/4aad15af82ed6dc565807b27a24b261708acbdcc/source-amazon-ads/2.0.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

2023-06-23 12:58 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/4658198dcb5a22a7989d065d9d77e91182d5a6c3/airbyte-integrations/connectors/source-amazon-ads/icon.svg" width="40" height="40"> source-amazon-ads test report (commit [`4658198dcb`](https://github.com/airbytehq/airbyte/pull/27512/commits/4658198dcb5a22a7989d065d9d77e91182d5a6c3)) - ✅

⏲️  Total pipeline duration: 194 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check.                                          | ✅        |
| Connector version increment check.                                       | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/midavadim_26401-source-amazon-sponsored-display-budget-rules/1687524924/4658198dcb5a22a7989d065d9d77e91182d5a6c3/source-amazon-ads/2.0.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

2023-06-23 13:49 UTC, lazebnyi approved these changes

2023-06-23 13:52 UTC, lazebnyi requested changes

2023-06-23 13:52 UTC, lazebnyi commented on airbyte-integrations/connectors/source-amazon-ads/Dockerfile
> +LABEL io.airbyte.version=2.0.1
```suggestion
LABEL io.airbyte.version=2.2.0
```

2023-06-23 13:52 UTC, lazebnyi commented on docs/integrations/sources/amazon-ads.md
> +| 2.0.1   | 2023-06-20 | [25412](https://github.com/airbytehq/airbyte/pull/25412) | Add sponsored_display_budget_rules stream                                                                       |
```suggestion
| 2.2.0   | 2023-06-20 | [25412](https://github.com/airbytehq/airbyte/pull/25412) | Add sponsored_display_budget_rules stream                                                                       |
```

2023-06-23 13:52 UTC, lazebnyi approved these changes
Approved, but need version change.

2023-06-23 13:54 UTC, lazebnyi commented on docs/integrations/sources/amazon-ads.md
> +| 2.0.1   | 2023-06-20 | [25412](https://github.com/airbytehq/airbyte/pull/25412) | Add sponsored_display_budget_rules stream                                                                       |
Need add stream to list in the doc.

2023-06-23 14:32 UTC, closed without merging