Source Google Analytics Data API: Fix formatting
airbytehq/airbyte pull request #27531
Opened 2023-06-20 19:52 UTC by artem1205

## What

Fix Source Google Analytics Data API Connector health report

## How
Fix formatting

## Recommended reading order
1. `expected_records.jsonl`

## 🚨 User Impact 🚨

no breaking changes

## Pre-merge Actions

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

2023-06-20 20:38 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/3b87c9f01aba35393dc879ffb0ee904d512d5a81/airbyte-integrations/connectors/source-google-analytics-data-api/icon.svg" width="40" height="40"> source-google-analytics-data-api test report (commit [`3b87c9f01a`](https://github.com/airbytehq/airbyte/pull/27531/commits/3b87c9f01aba35393dc879ffb0ee904d512d5a81)) - ❌

⏲️  Total pipeline duration: 1782 seconds

| Step                                                                                    | Result   |
|:----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-google-analytics-data-api/metadata.yaml | ✅        |
| Connector version semver check.                                                         | ✅        |
| Connector version increment check.                                                      | ❌        |
| QA checks                                                                               | ❌        |
| Code format checks                                                                      | ✅        |
| Connector package install                                                               | ✅        |
| Build source-google-analytics-data-api docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                              | ✅        |
| Acceptance tests                                                                        | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5326923622)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-analytics-data-api test
```

2023-06-20 22:18 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/4be3ac02fcb477cf5ad42ccb77b38475f90acd8c/airbyte-integrations/connectors/source-google-analytics-data-api/icon.svg" width="40" height="40"> source-google-analytics-data-api test report (commit [`4be3ac02fc`](https://github.com/airbytehq/airbyte/pull/27531/commits/4be3ac02fcb477cf5ad42ccb77b38475f90acd8c)) - ❌

⏲️  Total pipeline duration: 1789 seconds

| Step                                                                                    | Result   |
|:----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-google-analytics-data-api/metadata.yaml | ✅        |
| Connector version semver check.                                                         | ✅        |
| Connector version increment check.                                                      | ❌        |
| QA checks                                                                               | ❌        |
| Code format checks                                                                      | ✅        |
| Connector package install                                                               | ✅        |
| Build source-google-analytics-data-api docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                              | ✅        |
| Acceptance tests                                                                        | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5327702843)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-analytics-data-api test
```

2023-06-21 07:00 UTC, davydov-d requested changes

2023-06-21 07:00 UTC, davydov-d commented on airbyte-integrations/connectors/source-google-analytics-data-api/source_google_analytics_data_api/api_quota.py
> +
code changes require a version bump as well

2023-06-21 10:07 UTC, artem1205 commented on airbyte-integrations/connectors/source-google-analytics-data-api/source_google_analytics_data_api/api_quota.py
> +
updated

2023-06-21 10:14 UTC, davydov-d approved these changes

2023-06-21 10:39 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/414cfb40895e060c574ac1d18432e1fe2438a075/airbyte-integrations/connectors/source-google-analytics-data-api/icon.svg" width="40" height="40"> source-google-analytics-data-api test report (commit [`414cfb4089`](https://github.com/airbytehq/airbyte/pull/27531/commits/414cfb40895e060c574ac1d18432e1fe2438a075)) - ✅

⏲️  Total pipeline duration: 1791 seconds

| Step                                                                                    | Result   |
|:----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-google-analytics-data-api/metadata.yaml | ✅        |
| Connector version semver check.                                                         | ✅        |
| Connector version increment check.                                                      | ✅        |
| QA checks                                                                               | ✅        |
| Code format checks                                                                      | ✅        |
| Connector package install                                                               | ✅        |
| Build source-google-analytics-data-api docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                              | ✅        |
| Acceptance tests                                                                        | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5332781613)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-analytics-data-api test
```

2023-06-21 10:54 UTC, merged