✨Source Zendesk Support: New Stream - User Fields
airbytehq/airbyte pull request #28346
Opened 2023-07-15 11:39 UTC by btkcodedev

## What
Closes #19123

## Enhancement
New streams: 

- User Fields

## Recommended reading order
1. `source_zendesk_support/source.py`
2. `source_zendesk_support/streams.py`
3.  `source_zendesk_support/schemas/*`

## 🚨 User Impact 🚨
No breaking changes

## Pre-merge Checklist
<details open><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter [Yes]

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Issue acceptance criteria met
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [x] Documentation which references the generator is updated as needed

2023-08-04 22:34 UTC, bmcgilli commented
@lazebnyi can you please assign for review?

2023-08-11 10:46 UTC, artem1205 requested changes

2023-08-11 10:46 UTC, artem1205 commented on docs/integrations/sources/zendesk-support.md
> +- [UserFields](https://developer.zendesk.com/api-reference/ticketing/users/user_fields/#list-user-fields) \(Incremental\)
Incremental support is mentioned here, but I can see only **full refresh** support from code. Which statement is correct?

2023-08-14 13:58 UTC, artem1205 commented
@btkcodedev , please check the comment above

2023-08-15 01:40 UTC, btkcodedev commented
@artem1205 Changes done :)

2023-08-17 18:59 UTC, artem1205 commented
@btkcodedev , if the stream is not `incremental`, please remove redundant mentions from `abnormal_state.json` and `incremental_catalog.json`

2023-08-19 18:20 UTC, btkcodedev commented
@artem1205 Removed unwanted :)

2023-08-29 08:51 UTC, artem1205 commented
Merged in https://github.com/airbytehq/airbyte/pull/29891

2023-08-29 08:51 UTC, closed without merging