✨ Source Hubspot: improve error message during connector setup
airbytehq/airbyte pull request #28558
Opened 2023-07-21 11:14 UTC by arsenlosenko

## What
Define more concise error messages during connector setup, accordingly to this issue:
https://github.com/airbytehq/airbyte/issues/28508

## How
I have tried to invoke errors during check with both access token and OAuth configs and see what errors are raised if fields in configs are changed to invalid values. It boils down to two main cases: either 401 if access token is invalid, or 400 if any of OAuth credentials are invalid. Considering that I have added handling to these two cases, if there are other errors that might be raised during connector setup, they will be presented to user as is. 

In terms of unit tests, covered only the part which handles 400 errors, as the other case with `HubspotInvalidAuth` was already covered by other tests.

2023-07-21 11:15 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/e1a102b54e23bdcac72f4d5b5505257f5bb8873e/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`e1a102b54e`](https://github.com/airbytehq/airbyte/pull/28558/commits/e1a102b54e23bdcac72f4d5b5505257f5bb8873e)) - ✅

⏲️  Total pipeline duration: 5.28s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_28508-source-hubspot-improve-setup-error-messages/1689938104/e1a102b54e23bdcac72f4d5b5505257f5bb8873e/source-hubspot/1.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-07-21 11:17 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/abef9407fb3452c2a1a9df6ac623cf629ab1bede/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`abef9407fb`](https://github.com/airbytehq/airbyte/pull/28558/commits/abef9407fb3452c2a1a9df6ac623cf629ab1bede)) - ✅

⏲️  Total pipeline duration: 2.87s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_28508-source-hubspot-improve-setup-error-messages/1689938202/abef9407fb3452c2a1a9df6ac623cf629ab1bede/source-hubspot/1.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-07-21 12:29 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/181d7a625f54a01f14c802aff77523c7ac5ef27b/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`181d7a625f`](https://github.com/airbytehq/airbyte/pull/28558/commits/181d7a625f54a01f14c802aff77523c7ac5ef27b)) - ❌

⏲️  Total pipeline duration: 10mn20s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ❌        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ❌        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_28508-source-hubspot-improve-setup-error-messages/1689941919/181d7a625f54a01f14c802aff77523c7ac5ef27b/source-hubspot/1.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-07-21 12:53 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/b9ad9ce0c4f6ae943d62e818bbe0520071c35341/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`b9ad9ce0c4`](https://github.com/airbytehq/airbyte/pull/28558/commits/b9ad9ce0c4f6ae943d62e818bbe0520071c35341)) - ✅

⏲️  Total pipeline duration: 6.45s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_28508-source-hubspot-improve-setup-error-messages/1689944012/b9ad9ce0c4f6ae943d62e818bbe0520071c35341/source-hubspot/1.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-07-21 12:56 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/56e87e0e5655e83e1e2db5dcc4ab83e048c64bc6/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`56e87e0e56`](https://github.com/airbytehq/airbyte/pull/28558/commits/56e87e0e5655e83e1e2db5dcc4ab83e048c64bc6)) - ✅

⏲️  Total pipeline duration: 18.86s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_28508-source-hubspot-improve-setup-error-messages/1689944152/56e87e0e5655e83e1e2db5dcc4ab83e048c64bc6/source-hubspot/1.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-07-24 09:41 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/9600945894c8dec5b9d786a44348741b717093c2/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`9600945894`](https://github.com/airbytehq/airbyte/pull/28558/commits/9600945894c8dec5b9d786a44348741b717093c2)) - ❌

⏲️  Total pipeline duration: 10mn13s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_28508-source-hubspot-improve-setup-error-messages/1690191071/9600945894c8dec5b9d786a44348741b717093c2/source-hubspot/1.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-07-24 11:40 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/d02b5c1af8b584bdedbb53de772cf63f37ffc5dd/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`d02b5c1af8`](https://github.com/airbytehq/airbyte/pull/28558/commits/d02b5c1af8b584bdedbb53de772cf63f37ffc5dd)) - ✅

⏲️  Total pipeline duration: 10mn13s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_28508-source-hubspot-improve-setup-error-messages/1690198167/d02b5c1af8b584bdedbb53de772cf63f37ffc5dd/source-hubspot/1.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-07-26 11:05 UTC, darynaishchenko requested changes

2023-07-26 11:28 UTC, arsenlosenko commented on airbyte-integrations/connectors/source-hubspot/source_hubspot/source.py
> +            error_msg = "Authentication failed: Please check if provided credentials are valid and try again.)"
thanks, removed this

2023-07-26 11:42 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/7945638418bf84cfc36f914706abd9ff02b166d7/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`7945638418`](https://github.com/airbytehq/airbyte/pull/28558/commits/7945638418bf84cfc36f914706abd9ff02b166d7)) - ✅

⏲️  Total pipeline duration: 13mn13s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_28508-source-hubspot-improve-setup-error-messages/1690370956/7945638418bf84cfc36f914706abd9ff02b166d7/source-hubspot/1.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-07-27 08:42 UTC, darynaishchenko approved these changes

2023-07-27 11:05 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/534b86313e87c33e5f10d2ec0ed2326dea7390cb/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`534b86313e`](https://github.com/airbytehq/airbyte/pull/28558/commits/534b86313e87c33e5f10d2ec0ed2326dea7390cb)) - ✅

⏲️  Total pipeline duration: 12mn38s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_28508-source-hubspot-improve-setup-error-messages/1690455122/534b86313e87c33e5f10d2ec0ed2326dea7390cb/source-hubspot/1.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-07-27 11:18 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/6fcfdf829388af4c05ebe089a0a43c24abd9599c/airbyte-integrations/connectors/source-hubspot/icon.svg" width="40" height="40"> source-hubspot test report (commit [`6fcfdf8293`](https://github.com/airbytehq/airbyte/pull/28558/commits/6fcfdf829388af4c05ebe089a0a43c24abd9599c)) - ✅

⏲️  Total pipeline duration: 11mn37s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_28508-source-hubspot-improve-setup-error-messages/1690456010/6fcfdf829388af4c05ebe089a0a43c24abd9599c/source-hubspot/1.1.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

2023-07-27 11:20 UTC, merged