:bug: Source Posthog: Fix events.event type
airbytehq/airbyte pull request #28593
Opened 2023-07-24 06:23 UTC by dynalz

## What

Posthog Event schema has wrong type on event column, the type should be a string as can be seen at official posthog api:
https://posthog.com/docs/api/events - Both get (for filtering) and response values from event key are string.

Checking Posthog frontend they are also all labeled as string:
![image](https://github.com/airbytehq/airbyte/assets/12519753/845a7ac1-82c5-4bd1-9251-084fdc721069)

The issue this is causing is making the source channel write the event column in json instead of string. Making it difficult to query since it's not really a json either
Example of Posthog to Postgres behavior on image below:
![image](https://github.com/airbytehq/airbyte/assets/12519753/983244d5-53d5-4727-9fba-1ccf3d6363bb)

## How
Change event typing from `["string", "object"]` to `string`

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

2023-07-24 06:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=28593) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=28593) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=28593) it.</sub>

2023-07-27 13:11 UTC, marcosmarxm commented
@dynalz can you sign the CLA?

2023-07-28 22:59 UTC, dynalz commented
> @dynalz can you sign the CLA?

done

2023-08-23 20:26 UTC, marcosmarxm approved these changes
Thanks @dynalz

2023-11-20 20:25 UTC, marcosmarxm commented
Hello @dynalz thanks for the contribution and patience to get it merged. This week the codebase is freeze because of holidays, but I'll proceeded next week to get it merged.

2023-12-04 22:09 UTC, katmarkham requested changes

2023-12-04 22:09 UTC, katmarkham commented on airbyte-integrations/connectors/source-posthog/metadata.yaml
> +          It was previously set as `[object, string]`, but the correct type is only `string`.
The `event` field in the `events` stream has been corrected to the proper data type. To apply this change, refresh the schema for the 'events' stream and reset your data. For more information visit <link to migration guide>

2023-12-04 22:14 UTC, marcosmarxm approved these changes
Thanks @dynalz

2023-12-04 22:14 UTC, katmarkham approved these changes

2023-12-05 01:02 UTC, merged