Destination Teradata: make connector avaialble on Airbyte Cloud
airbytehq/airbyte pull request #28667
Opened 2023-07-25 14:05 UTC by marcosmarxm

## What
Teradata Destination has integration tests running properly and can be available on Airbyte Cloud

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

2023-07-25 16:21 UTC, evantahler requested changes
Can you either remove [these lines](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/qa-engine/qa_engine/constants.py#L19-L31) - teradata in `INAPPROPRIATE_FOR_CLOUD_USE_CONNECTORS`, because the connectors are OK for cloud now, or... I guess we need to talk about insecure URLs

2023-09-29 22:31 UTC, evantahler commented
So one of the rules we have for running a connector on Airbyte cloud is that it is impossible to connect without using SSL/HTTPS/SSH.  We want to prevent any PII from being moved without encryption.  At the very least, when running on Airbyte cloud, we will need to remove "disable" "allow" and "prefer" from the SSL options.  

<img width="845" alt="Screenshot 2023-09-29 at 3 26 43 PM" src="https://github.com/airbytehq/airbyte/assets/303226/f62b67ed-77c6-4405-aade-e7e8d3b8335f">

Is it possible to self-host Teradata, and would your OSS users want to ever connect without SSL?  The easiest thing to do would be to remove those insecure SSL options in all cases... but, if there's really a use case, you'll need to make the connector "Airbyte Cloud Aware".  

To do that, you should inspect the environment variable, `DEPLOYMENT_MODE` and if it is "cloud", change your spec and runtime behavior to strongly validate SSL connections. 

Finally, once that is done in this PR (and the version of the connector bumped and docs updates), also remove teradata from this [file](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/qa-engine/qa_engine/constants.py#L31)

2023-11-28 12:39 UTC, SatishChGit commented
> So one of the rules we have for running a connector on Airbyte cloud is that it is impossible to connect without using SSL/HTTPS/SSH. We want to prevent any PII from being moved without encryption. At the very least, when running on Airbyte cloud, we will need to remove "disable" "allow" and "prefer" from the SSL options.
> 
> <img alt="Screenshot 2023-09-29 at 3 26 43 PM" width="845" src="https://private-user-images.githubusercontent.com/303226/271730921-f62b67ed-77c6-4405-aade-e7e8d3b8335f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzQ4NzEsIm5iZiI6MTcwMTE3NDU3MSwicGF0aCI6Ii8zMDMyMjYvMjcxNzMwOTIxLWY2MmI2N2VkLTc3YzYtNDQwNS1hYWRlLWU3ZThkM2I4MzM1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOFQxMjI5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODA1MjBhZjAyMmQyMzU1YTI4NTdkZGJjOTFlOTliMmJkYzVjNTI3MzJlODM1MjRhYWNlYjA5MjM1YjBjMGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E41M-dV2agJakcJp1aS56-hAIrV7oVI42VLhBBLwTZQ">
> Is it possible to self-host Teradata, and would your OSS users want to ever connect without SSL? The easiest thing to do would be to remove those insecure SSL options in all cases... but, if there's really a use case, you'll need to make the connector "Airbyte Cloud Aware".
> 
> To do that, you should inspect the environment variable, `DEPLOYMENT_MODE` and if it is "cloud", change your spec and runtime behavior to strongly validate SSL connections.
> 
> Finally, once that is done in this PR (and the version of the connector bumped and docs updates), also remove teradata from this [file](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/qa-engine/qa_engine/constants.py#L31)

Thank you [evantahler](https://github.com/evantahler). 
Currently, TLS is our strategy, but we and customers are not ready yet. TLS is still an optional component for Vantage Cloud and Vantage Core. Customers are using Non TLS connections but teradata provides TeraGSS-based encryption, which is more secure way of connection. TeraGSS-based encryption is enabled with JDBC parameter ENCRYPTDATA. When ENCRYPTDATA set to ON, data exchanged between the Teradata JDBC Driver and the database is encrypted. This provides greater security, though performance is impacted. 
https://github.com/airbytehq/airbyte/pull/32866 through this PR, I added ENCRYPTDATA=ON for connections making from airbyte.


also remove teradata from this [file](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/qa-engine/qa_engine/constants.py#L31) - this refers to source-teradata. but this PR is for destination-teradata. Do we still need this change?

2023-12-18 16:36 UTC, evantahler requested changes

2023-12-18 16:36 UTC, evantahler commented on airbyte-integrations/connectors/destination-teradata/Dockerfile
There should be no dockerfile.

2023-12-19 13:57 UTC, SatishChGit commented on airbyte-integrations/connectors/destination-teradata/Dockerfile
@evantahler  removed docker file

2023-12-20 00:46 UTC, evantahler approved these changes
I pushed a fix for the lint errors.  If the tests are green, I'm 👍!

2023-12-22 15:53 UTC, sunilkmallam commented on airbyte-integrations/connectors/destination-teradata/Dockerfile
@marcosmarxm, just following up on this thread. I know it's holiday time, however, could you please keep us posted on the status?

2023-12-22 16:53 UTC, marcosmarxm commented
Merge to master is frozen until 2-Jan second tests aren't working so need to fix them before to get this merged.

2023-12-23 02:58 UTC, SatishChGit commented
> Merge to master is frozen until 2-Jan second tests aren't working so need to fix them before to get this merged.

I tried to run tests on this branch but its getting struck at  Installing pyasn1. Is there anything else we need to do solve this issue. 
![image](https://github.com/airbytehq/airbyte/assets/23031170/843f0514-c945-44c2-a5ef-35214b14c193)

2024-01-02 21:32 UTC, SatishChGit commented
> > Merge to master is frozen until 2-Jan second tests aren't working so need to fix them before to get this merged.
> 
> I tried to run tests on this branch but its getting struck at Installing pyasn1. Is there anything else we need to do solve this issue. ![image](https://private-user-images.githubusercontent.com/23031170/292605740-843f0514-c945-44c2-a5ef-35214b14c193.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMzEzNDQsIm5iZiI6MTcwNDIzMTA0NCwicGF0aCI6Ii8yMzAzMTE3MC8yOTI2MDU3NDAtODQzZjA1MTQtYzk0NS00NGMyLWE1ZWYtMzUyMTRiMTRjMTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDIxMzA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ZjcwYzk4Y2Y1NjViM2RmYjNiOGIxYzJhZjQ4ZDc1ZjJmMTg4MjEwZjg3NjE0M2RmNDJhYmE0ZGVhYzUxYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sXYje2EQTPab67Hm-G0qhgehMm61kUEOiLyUloZp0y8)


Able to resolve this issue along with integration tests failure with error - Cannot create a NOPI table as a SET table. after this fix, in our local environment, two integration tests are failing. 
![image](https://github.com/airbytehq/airbyte/assets/23031170/6df8ae7f-6864-434a-9f71-84c0635390ae)

2024-01-02 21:34 UTC, SatishChGit commented
> > > Merge to master is frozen until 2-Jan second tests aren't working so need to fix them before to get this merged.
> > 
> > 
> > I tried to run tests on this branch but its getting struck at Installing pyasn1. Is there anything else we need to do solve this issue. ![image](https://private-user-images.githubusercontent.com/23031170/292605740-843f0514-c945-44c2-a5ef-35214b14c193.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMzEzNDQsIm5iZiI6MTcwNDIzMTA0NCwicGF0aCI6Ii8yMzAzMTE3MC8yOTI2MDU3NDAtODQzZjA1MTQtYzk0NS00NGMyLWE1ZWYtMzUyMTRiMTRjMTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDIxMzA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ZjcwYzk4Y2Y1NjViM2RmYjNiOGIxYzJhZjQ4ZDc1ZjJmMTg4MjEwZjg3NjE0M2RmNDJhYmE0ZGVhYzUxYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sXYje2EQTPab67Hm-G0qhgehMm61kUEOiLyUloZp0y8)
> 
> Able to resolve this issue along with integration tests failure with error - Cannot create a NOPI table as a SET table. after this fix, in our local environment, two integration tests are failing. ![image](https://private-user-images.githubusercontent.com/23031170/293792736-6df8ae7f-6864-434a-9f71-84c0635390ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMzE0ODAsIm5iZiI6MTcwNDIzMTE4MCwicGF0aCI6Ii8yMzAzMTE3MC8yOTM3OTI3MzYtNmRmOGFlN2YtNjg2NC00MzRhLTlmNzEtODRjMDYzNTM5MGFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDIxMzMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4Y2MzODJiYjBkZTVmZDNmZTAyMTk2YTkzODE5YmZmMjJiZDFiNjQwNjI4YzY5ZjZlMzczM2M5Nzg0NGU2NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7gYZTx9IMOJUaKetDJGOdl8C4ni8UVlJAlY9ARj31Vc)

@marcosmarxm  created other PR https://github.com/airbytehq/airbyte/pull/33872 to resolve Cannot create a NOPI table as a SET Table. Can you please verify the tests with these changes

2024-01-13 04:47 UTC, sunilkmallam commented
Hi @evantahler,
Now that the changes related to NoPI issue are merged, would you mind looking into this PR as well?

2024-01-15 18:56 UTC, evantahler commented
@marcosmarxm this looks ok to me - your call on the final merge

2024-01-17 03:51 UTC, sunilkmallam commented
> @marcosmarxm this looks ok to me - your call on the final merge

Hi @marcosmarxm, have you had chance to look into this yet?

2024-01-23 04:05 UTC, sunilkmallam commented
> > @marcosmarxm this looks ok to me - your call on the final merge
> 
> Hi @marcosmarxm, have you had chance to look into this yet?

Hi @marcosmarxm, just following up on this again. Have you had chance to look into this yet?

2024-01-29 10:58 UTC, sunilkmallam commented
> > > @marcosmarxm this looks ok to me - your call on the final merge
> > 
> > 
> > Hi @marcosmarxm, have you had chance to look into this yet?
> 
> Hi @marcosmarxm, just following up on this again. Have you had chance to look into this yet?

Hi @evantahler, is Marcos out of office? If so, is there anyone else who could review our changes and merge?

2024-01-30 22:43 UTC, merged