✨Source Shortio: Migrate Python CDK to Low-code CDK
airbytehq/airbyte pull request #28950
Opened 2023-08-01 21:22 UTC by btkcodedev

## What
*Migrating Source Shortio to Low-Code CDK*
Closes #28119

## How
*Developed using (Configuration Based Source) low-code CDK*

## Recommended reading order
1. `spec.yaml`
2. `manifest.yaml`
3. `schemas/*`

## Tests

<details open><summary><strong>Integration & Acceptance</strong></summary>
Full Test Results

![image](https://github.com/airbytehq/airbyte/assets/47392334/4e41d0ed-f615-419b-a834-ca3c8d655f9d)

</details>

## 🚨 User Impact 🚨
- No breaking changes, migration to low-code
<details><summary><strong>Migrate Connector: Source Shortio</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [x] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

</details>

2023-08-02 12:09 UTC, marcosmarxm requested changes
Left some comments.

2023-08-02 12:09 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-shortio/source_shortio/spec.yaml
> +documentationUrl: https://developers.short.io/reference
Url to Airbyte connector page not the connector API refeenc.

2023-08-02 12:09 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-shortio/source_shortio/spec.yaml
> +  required:
additionalProperties: true

2023-08-02 12:09 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-shortio/source_shortio/manifest.yaml
> +      path: "links"
This stream is missing pagination.
<img width="589" alt="image" src="https://github.com/airbytehq/airbyte/assets/5154322/73757d3a-0168-4478-99e5-732b3fb526ba">

2023-08-02 12:09 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-shortio/source_shortio/manifest.yaml
> +      path: "links"
Also the `links` allow to use the parameter `afterDate`. The parameter `start_date`is not been used in this connector yet. You can implement the incremental sync method here.

2023-08-02 12:09 UTC, marcosmarxm commented
Also please resolve the conflicts.

2023-08-02 17:46 UTC, btkcodedev commented
All comments resolved
Test - Passed state

![image](https://github.com/airbytehq/airbyte/assets/47392334/a58da765-68e8-4b01-a127-1edb1f211fe0)

2023-08-03 15:14 UTC, marcosmarxm approved these changes
Amazing work @btkcodedev

2023-08-03 16:33 UTC, merged