✨Source Retently: Migrate Python CDK to Low-code CDK
airbytehq/airbyte pull request #29040
Opened 2023-08-03 13:23 UTC by avirajsingh7

## What
Migrating Source retently to Low-Code CDK
Closes https://github.com/airbytehq/airbyte/issues/28118

## How
Developed using (Configuration Based Source) low-code CDK

## Recommended reading order

1. manifest.yaml
2. schemas/*

 ##  Test
<details>
<summary>Acceptance Test</summary>
<img width="969" alt="Screenshot 2023-08-03 at 6 52 13 PM" src="https://github.com/airbytehq/airbyte/assets/100823015/3c62b438-d753-48a3-a2fe-52c365521a43">
</details>

# 🚨 User Impact 🚨
**No breaking changes**, migration to low-code
<details>
<summary>Migrate Connector : Source retently</summary>

- [x] **Community Member? Grant Edit Access to Maintainers [instructions](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests)**
- [x] **Secrets in the Connector's Spec**
- [x] **Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run ./gradlew :airbyte-integrations:connectors:<name>:integrationTest.**
- [x] **Code Reviews Completed**
  - [x] **Documentation Updated**
  - [x] **Connector's README.md**
  - [x] **Connector's bootstrap.md**
  - [x] **docs/integrations/<source or destination>/<name>.md (including changelog. See changelog example)**
  - [x] **docs/integrations/README.md**
  - [x] **airbyte-integrations/builds.md**
- [x] **PR Name follows PR Naming Conventions**
</details>

2023-08-07 15:02 UTC, sajarin commented
Thanks for the contribution! Can you resolve the merge conflict @avirajsingh7?

2023-08-07 15:04 UTC, avirajsingh7 commented
@sajarin sorry of that, resolved now

2023-08-07 15:06 UTC, sajarin commented on airbyte-integrations/connectors/source-retently/acceptance-test-config.yml
> -          disable_for_version: "0.1.5"
Some of the changes you've made to some of the schema files is resulting in backwards incompatibility. Can you disable these tests for the prior version?

2023-08-07 15:07 UTC, sajarin commented on airbyte-integrations/connectors/source-retently/acceptance-test-config.yml
> +        empty_streams: []
templates is an empty stream in our sandbox account

2023-08-07 15:07 UTC, sajarin requested changes
looks good, some minor comments after running tests locally

2023-08-07 15:14 UTC, avirajsingh7 commented
@sajarin can you check now?

2023-08-07 15:40 UTC, sajarin commented on airbyte-integrations/connectors/source-retently/icon.svg
Why was this deleted?

2023-08-07 15:48 UTC, avirajsingh7 commented on airbyte-integrations/connectors/source-retently/icon.svg
my bad, added now

2023-08-08 16:50 UTC, sajarin commented
Thanks for the PR @avirajsingh7! This has been merged and tested in #29164. The reason why I wasn't able to merge this PR was because I needed to push some changes and run them against our CI but couldn't push to your branch since I didn't have branch permissions. Nevertheless, I forked your changes and tested in the PR aforementioned.

I'm closing this PR but this should still count for the hackathon of course. fyi @RealChrisSean

2023-08-08 16:50 UTC, closed without merging

2023-08-08 16:52 UTC, avirajsingh7 commented
thanks @sajarin