Google sheets handle duplicate headerrs
airbytehq/airbyte pull request #2905
Opened 2021-04-15 17:52 UTC by makalaaneesh

## What
This solves https://github.com/airbytehq/airbyte/issues/2153 

## How
- `check` fails if there are duplicate headers with a message.
- `discover` ignores duplicate headers from the AirbyteStream. It logs a warning

## Pre-merge Checklist
- [ ] *Run integration tests*
- [ ] *Publish Docker images*

## Recommended reading order

2021-04-16 19:49 UTC, sherifnada commented
@makalaaneesh thanks for your PR! I will review this very soon, just a little crunched on time yesterday :)

2021-04-18 03:30 UTC, sherifnada requested changes
@makalaaneesh looks great! just a few small tweaks but I think we can merge this very soon.

2021-04-18 03:30 UTC, sherifnada commented on airbyte-integrations/connectors/source-google-sheets/google_sheets_source/google_sheets_source.py
> +                logger.error(str(err))
if there is an error we should also return a fail message

2021-04-18 03:30 UTC, sherifnada commented on airbyte-integrations/connectors/source-google-sheets/google_sheets_source/google_sheets_source.py
> +                _, duplilcate_headers = Helpers.get_vaild_headers_and_duplicates(header_row_data)
typo: `duplilcate` should be `duplicate`

2021-04-18 03:30 UTC, sherifnada commented on airbyte-integrations/connectors/source-google-sheets/google_sheets_source/google_sheets_source.py
> +        # Check for duplicates
```suggestion
        # Check for duplicate headers
```

2021-04-18 03:30 UTC, sherifnada commented on airbyte-integrations/connectors/source-google-sheets/google_sheets_source/helpers.py
> +    def get_vaild_headers_and_duplicates(header_row_values: List[str]) -> (List[str], List[str]):
typo: `get_valid...`

2021-04-18 03:30 UTC, sherifnada commented on airbyte-integrations/connectors/source-google-sheets/unit_tests/test_helpers.py
> +    def test_duplicate_headers_retrived(self):
awesome! 👍🏼

2021-04-20 14:21 UTC, makalaaneesh commented
So many typos, my bad! 
@sherifnada addressed PR comments!

2021-04-20 14:23 UTC, sherifnada commented
I wish all PRs had typos as their main issue , I'll say that 😜

2021-04-20 16:49 UTC, sherifnada approved these changes

2021-04-20 16:50 UTC, merged

2021-04-20 16:50 UTC, sherifnada commented
thanks @makalaaneesh !