Embedded CDK: run a check before starting to load
airbytehq/airbyte pull request #29079
Opened 2023-08-04 11:26 UTC by flash1293

This PR adds a check call to the embedded base integration to profit from the check logic and improved error messages.

Just trying to run the sync would probably fail at some point as well but will most likely give a worse error message and might fail in unexpected ways.

I'm not 100% sure whether we should do this or not as it causes at least one additional request before the user is seeing data which is slowing down the loader.

2023-08-04 15:35 UTC, pedroslopez requested changes

2023-08-04 15:35 UTC, pedroslopez commented on airbyte-cdk/python/airbyte_cdk/sources/embedded/runner.py
> +        return self._source.check(self._logger, config)
So I looked through what check was actually doing, expecting it to validate things like missing required fields and such with the spec. I remembered this happened at the CDK level across the board, but was a bit surprised to find out it happens at the `AirbyteEntrypoint` level, and not in the `Source`:

https://github.com/airbytehq/airbyte/blob/642e7680b47e51d314ac8ba10e1bbf94a11c1210/airbyte-cdk/python/airbyte_cdk/entrypoint.py#L122-L123

I think this piece is the most valuable, specially as we have a raw config json that needs to be constructed by the end user and passed into the loader/connector.

We can do the same here by calling this util function:
https://github.com/airbytehq/airbyte/blob/2e099acc52aeddc172c5ee66ed98426c69449a4a/airbyte-cdk/python/airbyte_cdk/sources/utils/schema_helpers.py#L149

Though we'll need to also load spec, which _also_ seems to be a part of the AirbyteEntrypoint.

I would say just use the AirbyteEntrypoint, but that class configures things like the uncaught exception handler and the logging + works based on file paths which isn't quite what we want here.

2023-08-04 15:35 UTC, pedroslopez commented on airbyte-cdk/python/airbyte_cdk/sources/embedded/runner.py
> +        return self._source.check(self._logger, config)
If you're worried about time added with an extra request, just doing spec validation like is done here might be enough and addresses my main worry with not doing any validation on the config.

imo it's fine to do an extra request though.

2023-08-18 15:27 UTC, flash1293 commented
@pedroslopez Good point, I adjusted the PR to only check spec compatibility which should be fairly quick. Could you take another look?

2023-08-18 18:11 UTC, pedroslopez approved these changes
Nice!

2023-08-21 10:42 UTC, merged