✨Source Appfollow: Migrate Python CDK to Low-code CDK
airbytehq/airbyte pull request #29128
Opened 2023-08-06 17:15 UTC by btkcodedev

## What
*Migrating Source AppFollow to Low-Code CDK*
Closes #29117

## How
*Developed using (Configuration Based Source) low-code CDK*

## Recommended reading order
1. `spec.yaml`
2. `manifest.yaml`
3. `schemas/*`

## 🚨 User Impact 🚨
- No breaking changes, migration to low-code
<details><summary><strong>Migrate Connector: Source Appfollow</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [x] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

</details>

2023-08-07 16:35 UTC, btkcodedev commented
Couldn't get the credentials, but has only one stream,
Reviewers could you please comment if changes are required?

2023-08-10 17:53 UTC, archangelic requested changes
Thanks so much for your contribution! I have listed some changes below.

2023-08-10 17:53 UTC, archangelic commented on airbyte-integrations/connectors/source-appfollow/source_appfollow/manifest.yaml
> +      type: NoPagination
Pagination needs to be configured. For example:

```
base_paginator:
    type: "DefaultPaginator"
    pagination_strategy:
      type: "CursorPagination"
      cursor_value: "{{ last_records['nextPageToken'] }}"
    page_token_option:
      type: "RequestPath"
      field_name: "pageToken"
      inject_into: "request_parameter"
```

See [the docs](https://docs.airbyte.com/connector-development/config-based/understanding-the-yaml-file/pagination) for more information.

2023-08-10 17:53 UTC, archangelic commented on airbyte-integrations/connectors/source-appfollow/metadata.yaml
> +  releaseDate: TODO
A valid date in `YYYY-MM-DD` format needs to be set here. Today's date is fine.

2023-08-21 16:38 UTC, marcosmarxm approved these changes
Congrats @btkcodedev

2023-08-21 16:40 UTC, archangelic approved these changes

2023-08-21 16:45 UTC, merged