✨Source FreshServices : Migrate Python CDK to Low-code CDK
airbytehq/airbyte pull request #29126
Opened 2023-08-06 11:14 UTC by avirajsingh7

## What
Migrating Source Shortio to Low-Code CDK
Closes #28992 

## How
Developed using (Configuration Based Source) low-code CDK

## Recommended reading order

1. spec.yaml
2. manifest.yaml
3. schemas/*

## 🚨 User Impact 🚨

*Are there any breaking changes? What is the end result perceived by the user?*
Yes, there are breaking changes due to Changes to Stream Schema
At many places previous data type were wrong and added some new properties in schema as per response from API

 ##  Test
<details>
<summary>Acceptance Test</summary>
<img width="989" alt="Screenshot 2023-08-06 at 3 59 04 PM" src="https://github.com/airbytehq/airbyte/assets/100823015/2f60cb2d-3863-453e-8aab-42d8614f4286">
</details>

<details>
<summary>Migrate Connector : Source FreshServices</summary>

- [x] **Community Member? Grant Edit Access to Maintainers [instructions](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests)**
- [x] **Secrets in the Connector's Spec**
- [x] **Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run ./gradlew :airbyte-integrations:connectors:<name>:integrationTest.**
- [x] **Code Reviews Completed**
  - [x] **Documentation Updated**
  - [x] **Connector's README.md**
  - [x] **Connector's bootstrap.md**
  - [x] **docs/integrations/<source or destination>/<name>.md (including changelog. See changelog example)**
  - [x] **docs/integrations/README.md**
  - [x] **airbyte-integrations/builds.md**
- [x] **PR Name follows PR Naming Conventions**
</details>

2023-08-10 18:03 UTC, archangelic requested changes
Thanks so much for your contribution! This overall looks great! I have a few small changes for you!

2023-08-10 18:03 UTC, archangelic commented on docs/integrations/sources/freshservice.md
> +| 2.0.0 | 2023-08-06 | [29126](https://github.com/airbytehq/airbyte/pull/29126) | Migrated to Low-Code CDK |
This will be a minor version update to `1.2.0`.

2023-08-10 18:09 UTC, avirajsingh7 commented on airbyte-integrations/connectors/source-freshservice/metadata.yaml
> +  releaseDate: TODO
set to intial release date

2023-08-15 20:28 UTC, archangelic requested changes
I have added some changes to get acceptance tests working!

2023-08-15 20:28 UTC, archangelic commented on airbyte-integrations/connectors/source-freshservice/acceptance-test-config.yml
> +        empty_streams: ["name":"satisfaction_survey_responses","name":"releases"]
```suggestion
        empty_streams:
          - name: satisfaction_survey_responses
            bypass_reason: Test account does not have permissions
          - name: releases
            bypass_reason: Test account does not have permissions
          - name: assets
            bypass_reason: Test account does not have permissions
          - name: problems
            bypass_reason: Test account does not have permissions
          - name: software
            bypass_reason: Test account does not have permissions
          - name: products
            bypass_reason: Test account does not have permissions
          - name: changes
            bypass_reason: Test account does not have permissions
          - name: vendors
            bypass_reason: Test account does not have permissions
          - name: purchase_orders
            bypass_reason: Test account does not have permissions
```
Add empty streams

2023-08-15 20:28 UTC, archangelic commented on airbyte-integrations/connectors/source-freshservice/acceptance-test-config.yml
> +         future_state_path: "integration_tests/abnormal_state.json"
```suggestion
  incremental: 
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
        future_state:
          future_state_path: "integration_tests/abnormal_state.json"
```
Fix indentation

2023-08-15 20:28 UTC, archangelic commented on airbyte-integrations/connectors/source-freshservice/source_freshservice/manifest.yaml
> +      password: ""
```suggestion
      password: ""
    error_handler:
      response_filters:
        - http_codes: [403]
          action: IGNORE
```
add error handling for streams with no permissions.

2023-08-16 04:28 UTC, avirajsingh7 commented
@archangelic anything else

2023-08-16 16:39 UTC, archangelic approved these changes

2023-08-16 18:12 UTC, archangelic commented
Everything looks good! Going to merge this!

2023-08-16 18:12 UTC, merged