Driftlowcode
airbytehq/airbyte pull request #29121
Opened 2023-08-05 07:42 UTC by btkcodedev

## What
*Migrating Source Drift to Low-Code CDK*
Closes #28113

## How
*Developed using (Configuration Based Source) low-code CDK*

## Recommended reading order
1. `spec.yaml`
2. `manifest.yaml`
3. `schemas/*`

## Tests

<details open><summary><strong>Integration & Acceptance</strong></summary>
Full Test Results

![image](https://github.com/airbytehq/airbyte/assets/47392334/4e41d0ed-f615-419b-a834-ca3c8d655f9d)

</details>

## 🚨 User Impact 🚨
- No breaking changes, migration to low-code
<details><summary><strong>Migrate Connector: Source Drift</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [x] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

</details>

2023-08-05 10:03 UTC, btkcodedev commented
Full test results: Passed state
![image](https://github.com/airbytehq/airbyte/assets/47392334/7457e7b8-793b-46b5-bd6a-011e6b1c7784)

2023-08-05 10:04 UTC, btkcodedev commented
Ping via slack for credentials
ID: btkcodedev

2023-08-09 22:11 UTC, archangelic requested changes
Thanks for your contribution! This looks good, but I have listed out some small changes below.

2023-08-09 22:11 UTC, archangelic commented on airbyte-integrations/connectors/source-drift/acceptance-test-config.yml
> +            bypass_reason: "Sandbox account can't seed this stream"
Need to add `accounts` into the empty streams.

2023-08-09 22:11 UTC, archangelic commented on airbyte-integrations/connectors/source-drift/metadata.yaml
> +  releaseDate: TODO
This needs a valid date in `YYYY-MM-DD` format. (today's date is fine.

2023-08-10 17:13 UTC, archangelic requested changes

2023-08-10 17:13 UTC, archangelic commented on airbyte-integrations/connectors/source-drift/source_drift/manifest.yaml
> +      type: NoPagination
This needs to have a paginator. For example:
```
base_paginator:
    type: "DefaultPaginator"
    pagination_strategy:
      type: "CursorPagination"
      cursor_value: "{{ last_records['nextPageToken'] }}"
    page_token_option:
      type: "RequestPath"
      field_name: "pageToken"
      inject_into: "request_parameter"
```

2023-08-10 17:13 UTC, archangelic commented on airbyte-integrations/connectors/source-drift/source_drift/manifest.yaml
> +  - "#/definitions/users_stream"
`contacts` and `messages` streams need to be migrated as well.

2023-08-12 06:05 UTC, btkcodedev commented
@archangelic All comments resolved
Test result- passed state :)
![image](https://github.com/airbytehq/airbyte/assets/47392334/6666aca9-a3f8-405a-ac82-8dc4bea68f9f)

2023-08-15 22:24 UTC, archangelic approved these changes

2023-08-15 22:52 UTC, merged