Migrate to lowcode
airbytehq/airbyte pull request #29122
Opened 2023-08-05 08:07 UTC by btkcodedev

## What
*Migrating Source Mailgun to Low-Code CDK*
Closes #28113

## How
*Developed using (Configuration Based Source) low-code CDK*

## Recommended reading order
1. `spec.yaml`
2. `manifest.yaml`
3. `schemas/*`

## Tests

<details><summary><strong>Integration & Acceptance</strong></summary>
Full Test Results

</details>

## 🚨 User Impact 🚨
- No breaking changes, migration to low-code
<details><summary><strong>Migrate Connector: Source Mailgun</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [x] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

</details>

2023-08-05 09:13 UTC, btkcodedev commented
Test results: Passed state:
![image](https://github.com/airbytehq/airbyte/assets/47392334/1d896e50-e046-47ad-8b45-05f97a6c64f9)

2023-08-05 09:15 UTC, btkcodedev commented
Waiting for #28471 for merging to update start_date

2023-08-08 13:44 UTC, marcosmarxm commented
> Waiting for #28471 for merging to update start_date

Go ahead and fix the start date directly here.

2023-08-08 13:49 UTC, marcosmarxm requested changes

2023-08-08 13:49 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-mailgun/acceptance-test-config.yml
> +      - spec_path: "source_mailgun/spec.yaml"
This is going to bypass the backward test.
```suggestion
      - spec_path: "source_mailgun/spec.yaml"
        backward_compatibility_tests_config:
          disable_for_version: 0.1.1

2023-08-11 14:57 UTC, marcosmarxm requested changes, later dismissed
Left some comments, the connector is missing pagination.

2023-08-11 14:57 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-mailgun/metadata.yaml
> +      enabled: false
Why ar eyou changing this?

2023-08-11 14:57 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-mailgun/metadata.yaml
> +  releaseDate: TODO
Add a date here

2023-08-11 14:57 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-mailgun/source_mailgun/manifest.yaml
> +      type: NoPagination
Please add pagination as it was implemented before https://github.com/airbytehq/airbyte/blob/b78ad4e9d905f2f02631f7897acabf6441375032/airbyte-integrations/connectors/source-mailgun/source_mailgun/source.py#L42-L49

2023-08-11 14:57 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-mailgun/source_mailgun/manifest.yaml
> +
EOF

2023-08-12 18:25 UTC, btkcodedev commented
All comments resolved
Test result passed state

2023-08-12 18:37 UTC, btkcodedev commented
![image](https://github.com/airbytehq/airbyte/assets/47392334/aba8fa90-56f4-4cd2-a0b7-adf544b71979)

2023-08-14 19:10 UTC, sajarin commented
@btkcodedev getting an error with the check command with the events stream: 

`{"type": "LOG", "log": {"level": "ERROR", "message": "Encountered an error trying to connect to stream events. Error: \n Traceback (most recent call last):\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/checks/check_stream.py\", line 42, in check_connection\n    stream_is_available, reason = availability_strategy.check_availability(stream, logger, source)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py\", line 36, in check_availability\n    stream_slice = get_first_stream_slice(stream)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/utils/stream_helper.py\", line 21, in get_first_stream_slice\n    stream.stream_slices(\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py\", line 126, in stream_slices\n    return self.retriever.stream_slices()\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py\", line 348, in stream_slices\n    return self.stream_slicer.stream_slices()\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py\", line 141, in stream_slices\n    start_datetime = self._calculate_earliest_possible_value(self._select_best_end_datetime())\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py\", line 146, in _calculate_earliest_possible_value\n    earliest_possible_start_datetime = min(self.start_datetime.get_datetime(self.config), end_datetime)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/datetime/min_max_datetime.py\", line 58, in get_datetime\n    time = self._parser.parse(str(self.datetime.eval(config, **additional_parameters)), datetime_format)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/datetime/datetime_parser.py\", line 29, in parse\n    parsed_datetime = datetime.datetime.strptime(str(date), format)\n  File \"/usr/local/lib/python3.9/_strptime.py\", line 568, in _strptime_datetime\n    tt, fraction, gmtoff_fraction = _strptime(data_string, format)\n  File \"/usr/local/lib/python3.9/_strptime.py\", line 349, in _strptime\n    raise ValueError(\"time data %r does not match format %r\" %\nValueError: time data '' does not match format '%Y-%m-%dT%H:%M:%SZ'\n"}}`


`{"type": "LOG", "log": {"level": "ERROR", "message": "Check failed"}}`


`{"type": "CONNECTION_STATUS", "connectionStatus": {"status": "FAILED", "message": "\"Unable to connect to stream events - time data '' does not match format '%Y-%m-%dT%H:%M:%SZ'\""}}`

2023-08-15 01:31 UTC, btkcodedev commented
@sajarin 
Please update the secrets config to match the updated format (start_date: %Y-%m-%dT%H:%M:%SZ)
Ping via Slack (btkcodedev) for getting my creds if needed

2023-08-15 20:53 UTC, sajarin commented
@btkcodedev thanks for the update, config validation is now passing but no records are being fetched. I pinged you on slack for credentials so we can get this moving.

2023-08-17 17:52 UTC, sajarin approved these changes

2023-08-17 17:52 UTC, merged

2023-08-17 17:53 UTC, sajarin commented
Thanks for the contribution @btkcodedev!

2023-08-21 04:01 UTC, padala commented
@btkcodedev @sajarin Thanks for the contribution. I'm still facing the issue with sync resulting in 0 records when I tried this today on Airbyte Cloud. Is this already resolved? 

> @btkcodedev thanks for the update, config validation is now passing but no records are being fetched. I pinged you on slack for credentials so we can get this moving.

2023-08-21 14:49 UTC, sajarin commented
@padala can you make a new issue and tag me? Perhaps an issue with the record selector

2023-09-01 17:35 UTC, padala commented
@sajarin  I've created a new issues here - https://github.com/airbytehq/airbyte/issues/30105