Migrate Confluence Source Connector to Low Code
airbytehq/airbyte pull request #29125
Opened 2023-08-06 00:55 UTC by topefolorunso

## What
Migrating Source Confluence to Low-Code CDK resolves #28989

## How
Created the connector using the connector buider UI, then imported the manifest.yaml to the low code cdk.

## Recommended reading order
1. `manifest.yaml`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

2023-08-08 15:30 UTC, sajarin requested changes
Thanks for the PR, left some comments:

2023-08-08 15:30 UTC, sajarin commented on airbyte-integrations/connectors/source-confluence/Dockerfile
> +LABEL io.airbyte.version=0.1.0
Can you update the version of the connector appropriately here? It looks like you're downgrading here.

2023-08-08 15:30 UTC, sajarin commented on airbyte-integrations/connectors/source-confluence/metadata.yaml
> +  dockerImageTag: 0.1.0
Same comment as above regarding the version

2023-08-08 15:30 UTC, sajarin commented on airbyte-integrations/connectors/source-confluence/metadata.yaml
> +  supportLevel: certified
supportLevel should be "community"

2023-08-08 15:30 UTC, sajarin commented on airbyte-integrations/connectors/source-confluence/metadata.yaml
> +  releaseDate: TODO
Can you update the release date with 2021-11-05? (This is when the connector was first published based on our docs)

2023-08-08 15:30 UTC, sajarin commented on airbyte-integrations/connectors/source-confluence/source_confluence/schemas/TODO.md
Can you remove this file?

2023-08-14 17:41 UTC, sajarin requested changes
Can you update the schema files with "additionalProperties" set to true?

2023-08-14 18:06 UTC, topefolorunso commented
> Can you update the schema files with "additionalProperties" set to true?

Fixed @sajarin

2023-08-14 23:38 UTC, topefolorunso commented
> @topefolorunso there are some validation errors in the manifest.yaml. Please correct them and then attach screenshots of passing acceptance tests

Validation error fixed @sajarin 

![image](https://github.com/airbytehq/airbyte/assets/66448986/d413e77f-7d52-4594-bcc5-4a1b808db2f6)

2023-08-15 20:29 UTC, sajarin commented
@topefolorunso some more errors after running the tests: 

<img width="488" alt="image" src="https://github.com/airbytehq/airbyte/assets/15092743/4bdaa781-1197-4ba2-84d5-a8c9c0fc1bce">

<img width="1343" alt="image" src="https://github.com/airbytehq/airbyte/assets/15092743/9b72bbe5-9baa-49f3-949c-38e172a6fce7">

2023-08-16 21:52 UTC, topefolorunso commented
@sajarin Errors should be fixed now.

- The audit stream requires a premium account which I don't have. So I was unable to test the stream. Kindly test again and let me know if anything else is broken.
- The pk used previously was the "author" property which is not unique. Apparently, there is no unique id for each audit log, so I opted for the "creationDate" property which is expected to be unique. (I hope that is okay)
- Finally, for some reason, I have been unable to run integration tests for all my connectors, probably due to some recent changes in the codebase. Please advise.

2023-08-17 18:18 UTC, sajarin commented
Still running into some issue with the primary keys but running the tests in a separate PR as per our usual review process.

2023-08-18 18:52 UTC, sajarin approved these changes

2023-08-18 19:06 UTC, sajarin commented
Thanks for the contribution @topefolorunso!

2023-08-18 19:06 UTC, merged