Migrate Zendesk Sunshine Source Connector to Low Code
airbytehq/airbyte pull request #29310
Opened 2023-08-09 20:44 UTC by topefolorunso

## What
Migrating Source Zendesk Sunshine to Low-Code CDK resolves #28124 

## How
Created the connector using the connector buider UI, then imported the manifest.yaml to the low code cdk.

## Recommended reading order
1. `manifest.yaml`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

2023-08-15 14:25 UTC, marcosmarxm commented
Hello 👋 , right now Airbyte's integration tests are failing for this connector and I'm going to work during the week to fix them. Due a high number of contributions we have a backlog and your contribution will be review next week. We ask to you share the integration test from your side whatever possible and if you don't have credentials to run tests to get in touch with @RealChrisSean as soon as possible. Also some common missing steps contributors does migrating to low code are (and you can double check to make sure you implemented this): 
* adding paginator
* update the documentation changelog + metadata file and dockerfile version
* if the connector has `start_date` parameter you must implement incremental syncs

2023-08-21 22:28 UTC, archangelic requested changes
Thanks for your contribution! In addition to the changes listed below, you will need to add a changelog entry in `docs/integrations/sources/zendesk-sunshine.md`.

2023-08-21 22:28 UTC, archangelic commented on airbyte-integrations/connectors/source-zendesk-sunshine/metadata.yaml
> +  dockerImageTag: 0.2.1
```suggestion
  dockerImageTag: 0.2.0
```

2023-08-21 22:28 UTC, archangelic commented on airbyte-integrations/connectors/source-zendesk-sunshine/Dockerfile
> +LABEL io.airbyte.version=0.2.1
```suggestion
LABEL io.airbyte.version=0.2.0
```

2023-08-21 22:28 UTC, archangelic commented on airbyte-integrations/connectors/source-zendesk-sunshine/metadata.yaml
> +  releaseDate: TODO
Needs to be set to a date with the format of `YYYY-MM-DD`. (today's date is fine)

2023-08-21 22:28 UTC, archangelic commented on airbyte-integrations/connectors/source-zendesk-sunshine/source_zendesk_sunshine/manifest.yaml
> +  documentation_url: https://example.org
```suggestion
  documentation_url: https://docs.airbyte.com/integrations/sources/zendesk_sunshine
```

2023-08-21 22:28 UTC, archangelic commented on airbyte-integrations/connectors/source-zendesk-sunshine/source_zendesk_sunshine/manifest.yaml
> +    properties:
The authentication methods (`OAuth2.0` and `API Token`) from the current version's spec.json are not properly configured here. Those authentication values need to be migrated here. You can check [the docs](https://docs.airbyte.com/connector-development/config-based/understanding-the-yaml-file/reference) for information on how to configure that.

2023-08-22 03:16 UTC, topefolorunso commented
Changes made @archangelic, please review

2023-08-22 16:33 UTC, archangelic commented
I am running tests on this, and will let you know if there are any further changes necessary.

2023-08-24 19:34 UTC, archangelic approved these changes

2023-08-24 20:17 UTC, archangelic commented
This looks good now! Merging!

2023-08-24 20:17 UTC, merged