Only GA destinations should be certified
airbytehq/airbyte pull request #29499
Opened 2023-08-16 22:25 UTC by evantahler

Updates the work done in https://github.com/airbytehq/airbyte/pull/28904 for destinations - only GA destinations should be Certified.  Alpha and Beta destinations are Community.

2023-08-16 22:32 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/789d30e6d0b94d414a73cbc3357a531f429ff8b9/airbyte-integrations/connectors/destination-amazon-sqs/icon.svg" width="40" height="40"> destination-amazon-sqs test report (commit [`789d30e6d0`](https://github.com/airbytehq/airbyte/pull/29499/commits/789d30e6d0b94d414a73cbc3357a531f429ff8b9)) - ✅

⏲️  Total pipeline duration: 01mn19s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-amazon-sqs/metadata.yaml | ✅        |
| Connector version semver check                                                | ✅        |
| QA checks                                                                     | ✅        |
| Code format checks                                                            | ✅        |
| Connector package install                                                     | ✅        |
| Build destination-amazon-sqs docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                    | ✅        |
| Integration tests                                                             | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_community-destination/1692224988/789d30e6d0b94d414a73cbc3357a531f429ff8b9/destination-amazon-sqs/0.1.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:789d30e6d0b94d414a73cbc3357a531f429ff8b9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-amazon-sqs test
```

2023-08-16 22:32 UTC, pedroslopez requested changes
Thanks Evan, did something change in how we define thigns? I think Ben went by a sheet to determine these initially

2023-08-16 22:32 UTC, pedroslopez commented on airbyte-integrations/connectors/destination-clickhouse/metadata.yaml
> -  supportLevel: certified
We need to also update ab_internal.sl accordingly (see https://www.notion.so/Internal-Metadata-Fields-32b02037e7b244b7934214019d0b7cc9?pvs=4#587617c9002243359322eae01ac0f150)

2023-08-16 22:33 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/789d30e6d0b94d414a73cbc3357a531f429ff8b9/airbyte-integrations/connectors/destination-google-sheets/icon.svg" width="40" height="40"> destination-google-sheets test report (commit [`789d30e6d0`](https://github.com/airbytehq/airbyte/pull/29499/commits/789d30e6d0b94d414a73cbc3357a531f429ff8b9)) - ✅

⏲️  Total pipeline duration: 03mn20s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-google-sheets/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build destination-google-sheets docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_community-destination/1692224988/789d30e6d0b94d414a73cbc3357a531f429ff8b9/destination-google-sheets/0.2.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:789d30e6d0b94d414a73cbc3357a531f429ff8b9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-google-sheets test
```

2023-08-16 22:34 UTC, evantahler commented
[Yep](https://airbytehq-team.slack.com/archives/C03C4AVJWG4/p1692209404859309).  tldr; the initial doc was underspecified when it came to destinations.  The original PR matched the source level, which isn't right for most destinations.

2023-08-16 22:39 UTC, pedroslopez approved these changes

2023-08-17 01:02 UTC, merged

2023-08-17 03:34 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/789d30e6d0b94d414a73cbc3357a531f429ff8b9/airbyte-integrations/connectors/destination-clickhouse/icon.svg" width="40" height="40"> destination-clickhouse test report (commit [`789d30e6d0`](https://github.com/airbytehq/airbyte/pull/29499/commits/789d30e6d0b94d414a73cbc3357a531f429ff8b9)) - ❌

⏲️  Total pipeline duration: 304mn32s 

| Step                                                                              | Result   |
|:----------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-clickhouse/metadata.yaml     | ✅        |
| Connector version semver check                                                    | ✅        |
| QA checks                                                                         | ✅        |
| Build connector tar                                                               | ✅        |
| Build destination-clickhouse docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-clickhouse:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-clickhouse:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_community-destination/1692224988/789d30e6d0b94d414a73cbc3357a531f429ff8b9/destination-clickhouse/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:789d30e6d0b94d414a73cbc3357a531f429ff8b9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-clickhouse test
```

2023-08-17 04:17 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/789d30e6d0b94d414a73cbc3357a531f429ff8b9/airbyte-integrations/connectors/destination-mysql/icon.svg" width="40" height="40"> destination-mysql test report (commit [`789d30e6d0`](https://github.com/airbytehq/airbyte/pull/29499/commits/789d30e6d0b94d414a73cbc3357a531f429ff8b9)) - ❌

⏲️  Total pipeline duration: 42mn53s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mysql/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build destination-mysql docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-mysql:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mysql:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_community-destination/1692224988/789d30e6d0b94d414a73cbc3357a531f429ff8b9/destination-mysql/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:789d30e6d0b94d414a73cbc3357a531f429ff8b9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mysql test
```

2023-08-17 04:48 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/789d30e6d0b94d414a73cbc3357a531f429ff8b9/airbyte-integrations/connectors/destination-postgres/icon.svg" width="40" height="40"> destination-postgres test report (commit [`789d30e6d0`](https://github.com/airbytehq/airbyte/pull/29499/commits/789d30e6d0b94d414a73cbc3357a531f429ff8b9)) - ❌

⏲️  Total pipeline duration: 30mn36s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-postgres/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-postgres docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization:dev                                                 | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-postgres:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_community-destination/1692224988/789d30e6d0b94d414a73cbc3357a531f429ff8b9/destination-postgres/0.4.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:789d30e6d0b94d414a73cbc3357a531f429ff8b9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-postgres test
```

2023-08-17 05:05 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/789d30e6d0b94d414a73cbc3357a531f429ff8b9/airbyte-integrations/connectors/destination-dynamodb/icon.svg" width="40" height="40"> destination-dynamodb test report (commit [`789d30e6d0`](https://github.com/airbytehq/airbyte/pull/29499/commits/789d30e6d0b94d414a73cbc3357a531f429ff8b9)) - ✅

⏲️  Total pipeline duration: 16mn26s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-dynamodb/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-dynamodb docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-dynamodb:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_community-destination/1692224988/789d30e6d0b94d414a73cbc3357a531f429ff8b9/destination-dynamodb/0.1.7/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:789d30e6d0b94d414a73cbc3357a531f429ff8b9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-dynamodb test
```

2023-08-17 10:09 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/789d30e6d0b94d414a73cbc3357a531f429ff8b9/airbyte-integrations/connectors/destination-mssql/icon.svg" width="40" height="40"> destination-mssql test report (commit [`789d30e6d0`](https://github.com/airbytehq/airbyte/pull/29499/commits/789d30e6d0b94d414a73cbc3357a531f429ff8b9)) - ❌

⏲️  Total pipeline duration: 304mn24s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mssql/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build destination-mssql docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-mssql:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mssql:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_community-destination/1692224988/789d30e6d0b94d414a73cbc3357a531f429ff8b9/destination-mssql/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:789d30e6d0b94d414a73cbc3357a531f429ff8b9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mssql test
```

2023-08-17 11:23 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/789d30e6d0b94d414a73cbc3357a531f429ff8b9/airbyte-integrations/connectors/destination-bigquery-denormalized/icon.svg" width="40" height="40"> destination-bigquery-denormalized test report (commit [`789d30e6d0`](https://github.com/airbytehq/airbyte/pull/29499/commits/789d30e6d0b94d414a73cbc3357a531f429ff8b9)) - ✅

⏲️  Total pipeline duration: 21mn37s 

| Step                                                                                         | Result   |
|:---------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery-denormalized/metadata.yaml     | ✅        |
| Connector version semver check                                                               | ✅        |
| QA checks                                                                                    | ✅        |
| Build connector tar                                                                          | ✅        |
| Build destination-bigquery-denormalized docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery-denormalized:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_community-destination/1692224988/789d30e6d0b94d414a73cbc3357a531f429ff8b9/destination-bigquery-denormalized/1.5.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:789d30e6d0b94d414a73cbc3357a531f429ff8b9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery-denormalized test
```

2023-08-17 11:35 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/789d30e6d0b94d414a73cbc3357a531f429ff8b9/airbyte-integrations/connectors/destination-gcs/icon.svg" width="40" height="40"> destination-gcs test report (commit [`789d30e6d0`](https://github.com/airbytehq/airbyte/pull/29499/commits/789d30e6d0b94d414a73cbc3357a531f429ff8b9)) - ✅

⏲️  Total pipeline duration: 11mn09s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-gcs/metadata.yaml     | ✅        |
| Connector version semver check                                             | ✅        |
| QA checks                                                                  | ✅        |
| Build connector tar                                                        | ✅        |
| Build destination-gcs docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-gcs:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_community-destination/1692224988/789d30e6d0b94d414a73cbc3357a531f429ff8b9/destination-gcs/0.4.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:789d30e6d0b94d414a73cbc3357a531f429ff8b9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-gcs test
```

2023-08-17 16:39 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/789d30e6d0b94d414a73cbc3357a531f429ff8b9/airbyte-integrations/connectors/destination-oracle/icon.svg" width="40" height="40"> destination-oracle test report (commit [`789d30e6d0`](https://github.com/airbytehq/airbyte/pull/29499/commits/789d30e6d0b94d414a73cbc3357a531f429ff8b9)) - ❌

⏲️  Total pipeline duration: 303mn46s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-oracle/metadata.yaml     | ✅        |
| Connector version semver check                                                | ✅        |
| QA checks                                                                     | ✅        |
| Build connector tar                                                           | ✅        |
| Build destination-oracle docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-oracle:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-oracle:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_community-destination/1692224988/789d30e6d0b94d414a73cbc3357a531f429ff8b9/destination-oracle/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:789d30e6d0b94d414a73cbc3357a531f429ff8b9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-oracle test
```

2023-08-17 16:42 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/airbyte-integrations/connectors/destination-amazon-sqs/icon.svg" width="40" height="40"> destination-amazon-sqs test report (commit [`7b4f5e53c6`](https://github.com/airbytehq/airbyte/pull/29499/commits/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)) - ✅

⏲️  Total pipeline duration: 01mn08s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-amazon-sqs/metadata.yaml | ✅        |
| Connector version semver check                                                | ✅        |
| QA checks                                                                     | ✅        |
| Code format checks                                                            | ✅        |
| Connector package install                                                     | ✅        |
| Build destination-amazon-sqs docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                    | ✅        |
| Integration tests                                                             | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_community-destination/1692290437/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/destination-amazon-sqs/0.1.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-amazon-sqs test
```

2023-08-17 16:42 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/airbyte-integrations/connectors/destination-google-sheets/icon.svg" width="40" height="40"> destination-google-sheets test report (commit [`7b4f5e53c6`](https://github.com/airbytehq/airbyte/pull/29499/commits/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)) - ✅

⏲️  Total pipeline duration: 01mn18s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-google-sheets/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build destination-google-sheets docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_community-destination/1692290437/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/destination-google-sheets/0.2.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-google-sheets test
```

2023-08-17 16:42 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/airbyte-integrations/connectors/source-faker/icon.svg" width="40" height="40"> source-faker test report (commit [`7b4f5e53c6`](https://github.com/airbytehq/airbyte/pull/29499/commits/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)) - ✅

⏲️  Total pipeline duration: 01mn46s 

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-faker/metadata.yaml | ✅        |
| Connector version semver check                                      | ✅        |
| QA checks                                                           | ✅        |
| Code format checks                                                  | ✅        |
| Connector package install                                           | ✅        |
| Build source-faker docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                          | ✅        |
| Acceptance tests                                                    | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_community-destination/1692290437/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/source-faker/5.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-faker test
```

2023-08-17 21:45 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/airbyte-integrations/connectors/destination-oracle/icon.svg" width="40" height="40"> destination-oracle test report (commit [`7b4f5e53c6`](https://github.com/airbytehq/airbyte/pull/29499/commits/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)) - ❌

⏲️  Total pipeline duration: 304mn40s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-oracle/metadata.yaml     | ✅        |
| Connector version semver check                                                | ✅        |
| QA checks                                                                     | ✅        |
| Build connector tar                                                           | ✅        |
| Build destination-oracle docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-oracle:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-oracle:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_community-destination/1692290437/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/destination-oracle/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-oracle test
```

2023-08-17 22:28 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/airbyte-integrations/connectors/destination-mysql/icon.svg" width="40" height="40"> destination-mysql test report (commit [`7b4f5e53c6`](https://github.com/airbytehq/airbyte/pull/29499/commits/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)) - ❌

⏲️  Total pipeline duration: 42mn24s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mysql/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build destination-mysql docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-mysql:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mysql:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_community-destination/1692290437/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/destination-mysql/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mysql test
```

2023-08-18 03:32 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/airbyte-integrations/connectors/destination-mssql/icon.svg" width="40" height="40"> destination-mssql test report (commit [`7b4f5e53c6`](https://github.com/airbytehq/airbyte/pull/29499/commits/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)) - ❌

⏲️  Total pipeline duration: 303mn51s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mssql/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build destination-mssql docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-mssql:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mssql:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_community-destination/1692290437/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/destination-mssql/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mssql test
```

2023-08-18 03:51 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/airbyte-integrations/connectors/destination-bigquery-denormalized/icon.svg" width="40" height="40"> destination-bigquery-denormalized test report (commit [`7b4f5e53c6`](https://github.com/airbytehq/airbyte/pull/29499/commits/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)) - ✅

⏲️  Total pipeline duration: 19mn14s 

| Step                                                                                         | Result   |
|:---------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery-denormalized/metadata.yaml     | ✅        |
| Connector version semver check                                                               | ✅        |
| QA checks                                                                                    | ✅        |
| Build connector tar                                                                          | ✅        |
| Build destination-bigquery-denormalized docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery-denormalized:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_community-destination/1692290437/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/destination-bigquery-denormalized/1.5.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery-denormalized test
```

2023-08-18 08:55 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/airbyte-integrations/connectors/destination-clickhouse/icon.svg" width="40" height="40"> destination-clickhouse test report (commit [`7b4f5e53c6`](https://github.com/airbytehq/airbyte/pull/29499/commits/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)) - ❌

⏲️  Total pipeline duration: 303mn39s 

| Step                                                                              | Result   |
|:----------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-clickhouse/metadata.yaml     | ✅        |
| Connector version semver check                                                    | ✅        |
| QA checks                                                                         | ✅        |
| Build connector tar                                                               | ✅        |
| Build destination-clickhouse docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-clickhouse:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-clickhouse:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_community-destination/1692290437/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/destination-clickhouse/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-clickhouse test
```

2023-08-18 09:45 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/airbyte-integrations/connectors/destination-redshift/icon.svg" width="40" height="40"> destination-redshift test report (commit [`7b4f5e53c6`](https://github.com/airbytehq/airbyte/pull/29499/commits/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)) - ❌

⏲️  Total pipeline duration: 50mn01s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-redshift/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-redshift docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-redshift:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-redshift:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_community-destination/1692290437/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/destination-redshift/0.6.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-redshift test
```

2023-08-18 10:02 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/airbyte-integrations/connectors/destination-dynamodb/icon.svg" width="40" height="40"> destination-dynamodb test report (commit [`7b4f5e53c6`](https://github.com/airbytehq/airbyte/pull/29499/commits/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)) - ✅

⏲️  Total pipeline duration: 16mn35s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-dynamodb/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-dynamodb docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-dynamodb:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_community-destination/1692290437/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/destination-dynamodb/0.1.7/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-dynamodb test
```

2023-08-18 10:14 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/airbyte-integrations/connectors/destination-gcs/icon.svg" width="40" height="40"> destination-gcs test report (commit [`7b4f5e53c6`](https://github.com/airbytehq/airbyte/pull/29499/commits/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)) - ✅

⏲️  Total pipeline duration: 11mn21s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-gcs/metadata.yaml     | ✅        |
| Connector version semver check                                             | ✅        |
| QA checks                                                                  | ✅        |
| Build connector tar                                                        | ✅        |
| Build destination-gcs docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-gcs:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_community-destination/1692290437/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/destination-gcs/0.4.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-gcs test
```

2023-08-18 10:45 UTC, octavia-squidington-iii commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/airbyte-integrations/connectors/destination-postgres/icon.svg" width="40" height="40"> destination-postgres test report (commit [`7b4f5e53c6`](https://github.com/airbytehq/airbyte/pull/29499/commits/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)) - ❌

⏲️  Total pipeline duration: 31mn28s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-postgres/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-postgres docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization:dev                                                 | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-postgres:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_community-destination/1692290437/7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8/destination-postgres/0.4.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7b4f5e53c6b677173fb3ac5dc2a64185c33c04b8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-postgres test
```