Migrate Hellobaton Source Connector to Low Code
airbytehq/airbyte pull request #29490
Opened 2023-08-16 17:21 UTC by topefolorunso

## What
Migrating Source Hellobaton to Low-Code resolves #29139

## How
Created the connector using the connector buider UI, then imported the manifest.yaml to the low code cdk.

## Recommended reading order
1. `manifest.yaml`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

2023-08-21 18:56 UTC, sajarin requested changes
Thanks for the PR, left some comments

2023-08-21 18:56 UTC, sajarin commented on docs/integrations/sources/baton.md
Can you rename this file to match the name of the connector?

2023-08-21 18:56 UTC, sajarin commented on airbyte-integrations/connectors/source-hellobaton/setup.py
> +    "connector-acceptance-test",
don't think connector-acceptance-test is needed here

2023-08-21 18:56 UTC, sajarin commented on airbyte-integrations/connectors/source-hellobaton/source_hellobaton/manifest.yaml
> +  documentation_url: https://docs.airbyte.com/integrations/sources/baton
can you update this doc url?

2023-08-21 18:56 UTC, sajarin commented on airbyte-integrations/connectors/source-hellobaton/source_hellobaton/manifest.yaml
> +    additionalProperties: false
can you set this to true and skip backward incompatibility check in the acceptance-test-config.yml for the spec task?

2023-08-22 00:03 UTC, topefolorunso commented
Changes made @sajarin, please review.

2023-08-23 19:17 UTC, sajarin requested changes
Just a few more things: 

1. Can you update all of the schema files and make each of the properties nullable? 
2. See below

2023-08-23 19:17 UTC, sajarin commented on airbyte-integrations/connectors/source-hellobaton/acceptance-test-config.yml
Can you migrate this file to use the latest formatting for an acceptance-test-config.yml. Other connectors may be a good reference

2023-08-23 22:53 UTC, topefolorunso commented on airbyte-integrations/connectors/source-hellobaton/acceptance-test-config.yml
Done @sajarin

2023-08-23 22:54 UTC, topefolorunso commented
> Just a few more things:
> 
> 1. Can you update all of the schema files and make each of the properties nullable?
> 2. See below

Changes made @sajarin, please review

2023-08-24 18:10 UTC, sajarin approved these changes

2023-08-24 18:22 UTC, merged