✨ Source MongoDB Internal POC: CDC Metadata Injector
airbytehq/airbyte pull request #29730
Opened 2023-08-22 20:31 UTC by jdpgrailsdev

## What
* Inject Airbyte-required metadata for CDC mode in MongoDB source

## How
* Implement the `CdcMetadataInjector` interface for MongoDB
* Refactor the `DebeziumEventUtils` and `CdcMetadataInjector` implementation to push the retrieval of the stream name down into the metadata injector to support the difference between the relational database Debezium connectors and MongoDB.

## Recommended reading order
1. `CdcMetadataInjector.java`
2. `MongoDbCdcConnectorMetadataInjector.java`
3. `DebeziumEventUtils.java`

**N.B.**: This PR is based off of https://github.com/airbytehq/airbyte/pull/29710, as it depends on some of the utility methods for dealing with resume tokens and timestamps.

2023-08-23 19:32 UTC, subodh1810 reviewed
Are we sure about the metadata columns that we want to add to records, Mongo has a concept of LSN?

2023-08-23 19:32 UTC, subodh1810 commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/cdc/MongoDbCdcConnectorMetadataInjector.java
> +    event.put(CDC_LSN, timestamp.getValue());
Mongo has a concept of LSN?

2023-08-24 19:54 UTC, jpefaur approved these changes

2023-08-24 20:04 UTC, jdpgrailsdev commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/cdc/MongoDbCdcConnectorMetadataInjector.java
> +    event.put(CDC_DEFAULT_CURSOR, getCdcDefaultCursor());
This is used by the V2 destination to track the order of records.  The implementation here is copied from the MySql injector to guarantee a globally unique, increasing value.  We could have potentially used the _id value, but there is no guarantee that if you sort the string value that the order matches the natural document order, so you would probably need to decode it, if possible, into a timestamp.  Therefore, we decided to go with this approach that is already in use by the other CDC sources.

2023-08-24 20:05 UTC, jdpgrailsdev commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/cdc/MongoDbCdcConnectorMetadataInjector.java
> +    record.put(CDC_DELETED_AT, (String) null);
I believe that this is to have parity with the incremental sync side of things, which may actual delete records.  This code is in the method called as part of the initial snapshot, so none of those records would ever be deleted.

2023-08-24 20:05 UTC, jdpgrailsdev commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/cdc/MongoDbCdcConnectorMetadataInjector.java
> +    return this.emittedAtConverted + this.recordCounter.getAndIncrement();
It supposedly is generating an unique, always increasing value for use by the V2 to source to order the records.

2023-08-25 10:56 UTC, subodh1810 requested changes
I pushed a commit to make the class singleton like Mysql one. Also a comment around adding the `CDC_UPDATED_AT` again

2023-08-25 10:56 UTC, subodh1810 commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/cdc/MongoDbCdcConnectorMetadataInjector.java
> +    event.put(CDC_UPDATED_AT, timestamp.getValue());
We are already adding `base.put(CDC_UPDATED_AT, transactionTimestamp);` This is redundant right?

2023-08-25 10:59 UTC, subodh1810 commented
Also lets run tests for all the CDC connectors

2023-08-25 12:53 UTC, jdpgrailsdev commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/cdc/MongoDbCdcConnectorMetadataInjector.java
> +    event.put(CDC_UPDATED_AT, timestamp.getValue());
@subodh1810 I didn't realize that the `event` passed to `addMetaData` contains the metadata from the other method.  If that is the case, then it is redundant, though I think we then need to talk about which value is the correct one.

2023-08-25 17:47 UTC, subodh1810 approved these changes
Looks good! Lets make sure the tests for Postgres, mysql and mssql pass before merging as well.

2023-08-28 19:01 UTC, octavia-approvington commented
It's time <br/> ![fine lets go](https://media1.giphy.com/media/yaR8Dux1s0fAI/giphy.gif?cid=ecf05e47a0zmzctsyu3sqzbajb4aitlkuzrr9vxk70s7lw1r&rid=giphy.gif&ct=g)

2023-08-28 19:01 UTC, octavia-approvington approved these changes

2023-08-28 19:01 UTC, merged