✨Source Apify Dataset: Migrate Python CDK to Low-code CDK
airbytehq/airbyte pull request #29859
Opened 2023-08-25 19:25 UTC by btkcodedev

## What
*Migrating Source Apify Dataset to Low-Code CDK*
Closes #29116

## How
*Developed using (Configuration Based Source) low-code CDK*

## Recommended reading order
1. `spec.yaml`
2. `manifest.yaml`
3. `schemas/*`

## 🚨 User Impact 🚨
- No breaking changes, migration to low-code
<details><summary><strong>Migrate Connector: Source Apify Dataset</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [x] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

</details>

2023-08-25 19:26 UTC, btkcodedev commented
Config
{
  "token": "apify_api_8UPAaECr6WGLasifLAicj0tDziE64E4j40dT",
  "start_date": "2023-08-25T00:00:00.244Z"
}

2023-08-25 19:35 UTC, btkcodedev commented
Checks: 
Added Paginator ✅ 
Added Incremental Sync ✅ 
Updated Version in metadata, Dockerfile and docs ✅

2023-08-29 16:21 UTC, marcosmarxm requested changes
Left some comments.

2023-08-29 16:21 UTC, marcosmarxm commented on docs/integrations/sources/apify-dataset.md
> +|   0.3.0   | 2023-08-25  | [TBD](https://github.com/airbytehq/airbyte/pull/TBD)          | Migrate to lowcode                                                          |
Update this.

2023-08-29 16:21 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-apify-dataset/source_apify_dataset/manifest.yaml
> +    step: "P1M"
Can you reference Apify documentation where you can use incremental?

2023-08-29 16:21 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-apify-dataset/source_apify_dataset/manifest.yaml
> +  base_paginator:
Not used anywhere. Please make sure to use the paginator.

2023-08-29 17:11 UTC, btkcodedev commented
Reolved comments, somehow my apifydataset account got disabled. Thus couldn't test the changes :(

2023-08-30 16:03 UTC, marcosmarxm approved these changes
Thanks @btkcodedev

2023-08-30 16:12 UTC, merged