Migrate Typeform Source Connector to Low Code
airbytehq/airbyte pull request #29916
Opened 2023-08-29 00:06 UTC by topefolorunso

## What
Migrating Source Typeform to Low-Code CDK resolves #28121

## How
Created the connector using the connector buider UI, then imported the manifest.yaml to the low code cdk.

## Recommended reading order
1. `manifest.yaml`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

2023-08-31 17:42 UTC, marcosmarxm requested changes
Fix comments. Connector has two type of auth.

2023-08-31 17:42 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-typeform/source_typeform/manifest.yaml
> +          api_token: '{{ config[''api_key''] }}'
Current connector has two type of auth. You need to implement the Oauth too.

2023-08-31 17:42 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-typeform/source_typeform/manifest.yaml
> +          type: BearerAuthenticator
This doesn't correspond to what the connector spec is.

2023-09-02 01:14 UTC, topefolorunso commented
Fixed now @marcosmarxm, please review

2023-09-04 17:00 UTC, marcosmarxm requested changes, later dismissed
Some comments.

2023-09-04 17:00 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-typeform/source_typeform/manifest.yaml
> +      type: SimpleRetriever
The connector is almost working. It is failing for a incremental test. We're going to return with more info during the week @topefolorunso

2023-09-04 17:00 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-typeform/source_typeform/components.py
> +
PLease add some unit test for this function and remove the print statement (I added it :P)

2023-09-07 15:31 UTC, sh4sh commented on airbyte-integrations/connectors/source-quickbooks/source_quickbooks/manifest.yaml
> +      grant_type: refresh_token
```suggestion
      grant_type: refresh_token
```

2023-09-07 17:06 UTC, sh4sh approved these changes

2023-09-07 17:08 UTC, merged

2023-09-07 17:08 UTC, sh4sh commented
Thank you for the contribution!