✨ Source MongoDB Internal POC: Support incremental syncs via Debezium
airbytehq/airbyte pull request #29969
Opened 2023-08-29 19:11 UTC by jdpgrailsdev

## What
* Use the Debezium MongoDB connector for incremental syncs

## How
* Add logic to select initial snapshot and incremental sync iterators depending on state
* Modify initial snapshot iterator to track completeness
* Use new utility in source read method to fetch iterators based on CDC progress

## Recommended reading order
1. `MongoDbCdcInitializer.java`
2. `MongoDbCdcInitialSnapshotUtils.java`
3. `MongoDbDebeziumStateUtil.java`
4. `MongoDbSource.java`
5. `MongoDbStateIterator.java`
6. `MongoDbTargetPosition.java`
7. `MongoDbCustomLoader.java`

2023-09-04 10:37 UTC, subodh1810 requested changes
There are a couple of bugs I could identify 
1. First is around the state manager. We are constructing the state manager before finalising the debezium state to used. We need to initialise the state manager after we know which streams to sync via initial sync and which state to use. 
2. When emitting the record messages during initial sync we are not adding the values for metadata column. 

I wanted to understand the end to end to test flow. I would like to have similar tests like we have in `CdcPostgresSourceTest`. The tests in there cover everything and would have caught the above problems.

2023-09-04 10:37 UTC, subodh1810 commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/cdc/MongoDbCdcStateHandler.java
> +    LOGGER.info("Snapshot of new collections is complete, saving state...");
This should keep throwing `throw new RuntimeException("Debezium is not used to carry out the snapshot of tables.");` cause we are not using Debezium to carry out snpshot of tables

2023-09-04 10:37 UTC, subodh1810 commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/cdc/MongoDbCdcInitializer.java
> +    final JsonNode initialDebeziumState =
How is the `initialDebeziumState` being passed onto the `MongoDbStateManager`? I think there is a bug, during the first sync the  sharedState is going to be null in the state message emitted by `MongoDbStateManager`.

2023-09-04 10:37 UTC, subodh1810 commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/cdc/MongoDbCdcInitializer.java
> +    if (!savedOffsetIsValid) {
In case the offset is not valid we need to reset the `MongoDbStateManager` and remove all the streams from the `pairToStreamState` and  update the `cdcState` to use the new `initialDebeziumState`

2023-09-04 10:37 UTC, subodh1810 commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/cdc/MongoDbCdcInitialSnapshotUtils.java
> +      AirbyteTraceMessageUtility.emitEstimateTrace(PLATFORM_DATA_INCREASE_FACTOR * c.size().intValue(),
Lets use long value just to be safe 
```
AirbyteTraceMessageUtility.emitEstimateTrace((long) PLATFORM_DATA_INCREASE_FACTOR * c.size().longValue(),
 ```

2023-09-04 10:37 UTC, subodh1810 commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/InitialSnapshotHandler.java
> +          final Optional<MongoDbStreamState> existingState =
What happens if the saved offset is no longer valid. Then we can no longer use this state. The state manager needs to be reset

2023-09-04 10:37 UTC, subodh1810 commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/MongoDbSource.java
> +    final MongoClient mongoClient = createMongoClient(config);
Shouldn't the `mongoClient` be closed after intial snapshot is complete? Why do we wait for Debezium to finish as well for to close this. I guess Debezium doesn't use this and constructs its own connection right?

2023-09-04 10:37 UTC, subodh1810 commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/MongoDbStateIterator.java
> +      iterThrewException = true;
Am still not sure why are we swallowing the exception and not failing the sync?

2023-09-04 10:37 UTC, subodh1810 commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/MongoDbStateIterator.java
> +  public MongoDbStateIterator(final MongoCursor<Document> iter,
I dont think this class is adding the metadata to the records like we do for debezium columns. this needs to use the class `MongoDbCdcConnectorMetadataInjector` and add the metadata like the cursor value. The method `addMetaDataToRowsFetchedOutsideDebezium` needs to be used

2023-09-04 10:37 UTC, subodh1810 commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/MongoConstants.java
>    public static final Integer CHECKPOINT_INTERVAL = 1000;
The default checkpoint interval in other databases is 10K records so lets keep it 10K as well

2023-09-05 14:12 UTC, jdpgrailsdev commented on airbyte-integrations/bases/debezium/src/main/java/io/airbyte/integrations/debezium/internals/DebeziumEventUtils.java
> +    return (ObjectNode) (baseNode instanceof TextNode ? Jsons.deserialize(baseNode.asText()) : baseNode);
@subodh1810 We cannot just do this for Mongo without refactoring this class into different implementations.  We don't know what produced the event at this point.  The proper solution would be to turn this into an abstract class and have two different implementations, much like we did for the DebeziumPropertiesManager.

2023-09-05 14:13 UTC, jdpgrailsdev commented on airbyte-integrations/bases/debezium/src/main/java/io/airbyte/integrations/debezium/internals/mongodb/MongoDbDebeziumStateUtil.java
> +    final Map<String, String> sourceInfoMap = new HashMap<>();
Will do

2023-09-05 14:13 UTC, jdpgrailsdev commented on airbyte-integrations/bases/debezium/src/main/java/io/airbyte/integrations/debezium/internals/mongodb/MongoDbDebeziumStateUtil.java
>      final Map<String, Object> value = new HashMap<>();
Will do.

2023-09-05 14:15 UTC, jdpgrailsdev commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/cdc/MongoDbCdcInitializer.java
> +
Will do.

2023-09-05 14:16 UTC, jdpgrailsdev commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/cdc/MongoDbCdcStateHandler.java
> +    LOGGER.info("Snapshot of new collections is complete, saving state...");
Will fix.

2023-09-05 14:17 UTC, jdpgrailsdev commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/MongoConstants.java
>    public static final Integer CHECKPOINT_INTERVAL = 1000;
Will fix.

2023-09-05 14:55 UTC, jdpgrailsdev commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/MongoDbStateIterator.java
> +  public MongoDbStateIterator(final MongoCursor<Document> iter,
@subodh1810 I took a shot at this.  Please take a look and see if I got it correct.

2023-09-05 14:57 UTC, jdpgrailsdev commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/InitialSnapshotHandler.java
> +          final Optional<MongoDbStreamState> existingState =
@subodh1810 I'm not sure that applies here?  This code is retrieving the initial snapshot checkpoint.  That data doesn't have to exist for us to perform the initial snapshot.  This code uses the `_id` value from the documents in the collection, not the information in the oplog.  If, for some reason, the user has deleted the document with the `_id` value that was last saved to the state (and any other documents beyond it), this query will still work.  It simply does a > "last checkpointed _id value".

2023-09-05 15:00 UTC, jdpgrailsdev commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/MongoDbStateIterator.java
> +      iterThrewException = true;
@colesnodgrass Could you please explain our rationale behind this approach?

2023-09-05 17:57 UTC, jdpgrailsdev commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/InitialSnapshotHandler.java
> +          final Optional<MongoDbStreamState> existingState =
@subodh1810 and I discussed this and the code has been updated to reset the state manager if the offset state is invalid.

2023-09-05 17:58 UTC, jdpgrailsdev commented on airbyte-integrations/bases/debezium/src/main/java/io/airbyte/integrations/debezium/internals/DebeziumEventUtils.java
> +    return (ObjectNode) (baseNode instanceof TextNode ? Jsons.deserialize(baseNode.asText()) : baseNode);
@subodh1810 and I discussed this and the approach that we are going to take is to pass the `DebeziumConnectorType` enum value to the `toAirbyteMessage` method to determine which class to use for the cast.

2023-09-07 09:14 UTC, subodh1810 reviewed
We are almost there! My previous comments are addressed. I found a bug in the discover method (we are not adding the metadata columns as part of the catalog in discover). 

I also pushed a minor commit to get rid of schemaHistoryManager parameter cause its not relevant for Mongo.

2023-09-07 13:29 UTC, jdpgrailsdev commented on airbyte-integrations/connectors/source-mongodb-internal-poc/src/main/java/io/airbyte/integrations/source/mongodb/internal/MongoDbSource.java
> +  public MongoDbSource() {
@subodh1810 This should now be fixed.  See the `MongoUtil` and `MongoDbCdcConnectorMetadataInjector` classes for the change.

2023-09-13 18:13 UTC, bnchrch commented on airbyte-integrations/connectors/source-mongodb-internal-poc/metadata.yaml
> -      enabled: true
One minor note here @jdpgrailsdev is that right now to remove this connector from the registry you will need to merge a metadata.yaml file with 
```yaml
  registries:
    cloud:
      enabled: false
    oss:
      enabled: true
```

Afterwards you are free to delete the file.

2023-09-15 10:52 UTC, subodh1810 approved these changes
This looks good! Great work! I pushed a small nit commit.

2023-09-21 14:22 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/7d1ebab5e19b5734eb2d9cbff5971f1f526488f9/airbyte-integrations/connectors/destination-mongodb/icon.svg" width="40" height="40"> destination-mongodb test report (commit [`7d1ebab5e1`](https://github.com/airbytehq/airbyte/pull/29969/commits/7d1ebab5e19b5734eb2d9cbff5971f1f526488f9)) - ❌

⏲️  Total pipeline duration: 15mn26s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Build connector tar                                                        | ✅        |
| Build destination-mongodb docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                  | ✅        |
| Java Connector Integration Tests                                           | ❌        |
| Validate airbyte-integrations/connectors/destination-mongodb/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ❌        |
| QA checks                                                                  | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695305049/7d1ebab5e19b5734eb2d9cbff5971f1f526488f9/destination-mongodb/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7d1ebab5e19b5734eb2d9cbff5971f1f526488f9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb test
```

2023-09-21 14:26 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/7d1ebab5e19b5734eb2d9cbff5971f1f526488f9/airbyte-integrations/connectors/destination-mongodb-strict-encrypt/icon.svg" width="40" height="40"> destination-mongodb-strict-encrypt test report (commit [`7d1ebab5e1`](https://github.com/airbytehq/airbyte/pull/29969/commits/7d1ebab5e19b5734eb2d9cbff5971f1f526488f9)) - ❌

⏲️  Total pipeline duration: 03mn03s 

| Step                                                                                      | Result   |
|:------------------------------------------------------------------------------------------|:---------|
| Build connector tar                                                                       | ✅        |
| Build destination-mongodb-strict-encrypt docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                                 | ✅        |
| Java Connector Integration Tests                                                          | ✅        |
| Validate airbyte-integrations/connectors/destination-mongodb-strict-encrypt/metadata.yaml | ✅        |
| Connector version semver check                                                            | ✅        |
| Connector version increment check                                                         | ❌        |
| QA checks                                                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695305049/7d1ebab5e19b5734eb2d9cbff5971f1f526488f9/destination-mongodb-strict-encrypt/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7d1ebab5e19b5734eb2d9cbff5971f1f526488f9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb-strict-encrypt test
```

2023-09-21 15:17 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/7d1ebab5e19b5734eb2d9cbff5971f1f526488f9/airbyte-integrations/connectors/source-facebook-marketing/icon.svg" width="40" height="40"> source-facebook-marketing test report (commit [`7d1ebab5e1`](https://github.com/airbytehq/airbyte/pull/29969/commits/7d1ebab5e19b5734eb2d9cbff5971f1f526488f9)) - ❌

⏲️  Total pipeline duration: 73mn20s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |
| Acceptance tests                                                                 | ✅        |
| Code format checks                                                               | ✅        |
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ❌        |
| QA checks                                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695305049/7d1ebab5e19b5734eb2d9cbff5971f1f526488f9/source-facebook-marketing/1.1.11/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7d1ebab5e19b5734eb2d9cbff5971f1f526488f9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

2023-09-21 15:25 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/1205929432d319b324f5e5160eb8eab5166297b8/airbyte-integrations/connectors/source-mongodb-v2/icon.svg" width="40" height="40"> source-mongodb-v2 test report (commit [`1205929432`](https://github.com/airbytehq/airbyte/pull/29969/commits/1205929432d319b324f5e5160eb8eab5166297b8)) - ❌

⏲️  Total pipeline duration: 05mn57s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Build connector tar                                                      | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                | ✅        |
| Java Connector Integration Tests                                         | ❌        |
| Acceptance tests                                                         | ❌        |
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ❌        |
| QA checks                                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695309566/1205929432d319b324f5e5160eb8eab5166297b8/source-mongodb-v2/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1205929432d319b324f5e5160eb8eab5166297b8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

2023-09-21 15:40 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/1205929432d319b324f5e5160eb8eab5166297b8/airbyte-integrations/connectors/destination-mongodb-strict-encrypt/icon.svg" width="40" height="40"> destination-mongodb-strict-encrypt test report (commit [`1205929432`](https://github.com/airbytehq/airbyte/pull/29969/commits/1205929432d319b324f5e5160eb8eab5166297b8)) - ❌

⏲️  Total pipeline duration: 01mn26s 

| Step                                                                                      | Result   |
|:------------------------------------------------------------------------------------------|:---------|
| Build connector tar                                                                       | ✅        |
| Build destination-mongodb-strict-encrypt docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                                 | ✅        |
| Java Connector Integration Tests                                                          | ✅        |
| Validate airbyte-integrations/connectors/destination-mongodb-strict-encrypt/metadata.yaml | ✅        |
| Connector version semver check                                                            | ✅        |
| Connector version increment check                                                         | ❌        |
| QA checks                                                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695309566/1205929432d319b324f5e5160eb8eab5166297b8/destination-mongodb-strict-encrypt/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1205929432d319b324f5e5160eb8eab5166297b8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb-strict-encrypt test
```

2023-09-21 16:30 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/1205929432d319b324f5e5160eb8eab5166297b8/airbyte-integrations/connectors/source-facebook-marketing/icon.svg" width="40" height="40"> source-facebook-marketing test report (commit [`1205929432`](https://github.com/airbytehq/airbyte/pull/29969/commits/1205929432d319b324f5e5160eb8eab5166297b8)) - ❌

⏲️  Total pipeline duration: 70mn46s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |
| Acceptance tests                                                                 | ✅        |
| Code format checks                                                               | ✅        |
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ❌        |
| QA checks                                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695309566/1205929432d319b324f5e5160eb8eab5166297b8/source-facebook-marketing/1.1.11/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1205929432d319b324f5e5160eb8eab5166297b8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

2023-09-22 16:52 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/1447b969ff3802e01696554e95394a7adaa11920/airbyte-integrations/connectors/source-mongodb-v2/icon.svg" width="40" height="40"> source-mongodb-v2 test report (commit [`1447b969ff`](https://github.com/airbytehq/airbyte/pull/29969/commits/1447b969ff3802e01696554e95394a7adaa11920)) - ❌

⏲️  Total pipeline duration: 05mn17s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Build connector tar                                                      | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                | ✅        |
| Java Connector Integration Tests                                         | ❌        |
| Acceptance tests                                                         | ❌        |
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ❌        |
| QA checks                                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695401156/1447b969ff3802e01696554e95394a7adaa11920/source-mongodb-v2/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1447b969ff3802e01696554e95394a7adaa11920)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

2023-09-22 17:05 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/1447b969ff3802e01696554e95394a7adaa11920/airbyte-integrations/connectors/destination-mongodb/icon.svg" width="40" height="40"> destination-mongodb test report (commit [`1447b969ff`](https://github.com/airbytehq/airbyte/pull/29969/commits/1447b969ff3802e01696554e95394a7adaa11920)) - ❌

⏲️  Total pipeline duration: 12mn57s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Build connector tar                                                        | ✅        |
| Build destination-mongodb docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                  | ✅        |
| Java Connector Integration Tests                                           | ❌        |
| Validate airbyte-integrations/connectors/destination-mongodb/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ❌        |
| QA checks                                                                  | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695401156/1447b969ff3802e01696554e95394a7adaa11920/destination-mongodb/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1447b969ff3802e01696554e95394a7adaa11920)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb test
```

2023-09-22 17:12 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/1447b969ff3802e01696554e95394a7adaa11920/airbyte-integrations/connectors/destination-bigquery/icon.svg" width="40" height="40"> destination-bigquery test report (commit [`1447b969ff`](https://github.com/airbytehq/airbyte/pull/29969/commits/1447b969ff3802e01696554e95394a7adaa11920)) - ❌

⏲️  Total pipeline duration: 03mn12s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Build connector tar                                                         | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                   | ✅        |
| Java Connector Integration Tests                                            | ✅        |
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| Connector version increment check                                           | ❌        |
| QA checks                                                                   | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695401156/1447b969ff3802e01696554e95394a7adaa11920/destination-bigquery/2.0.15/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1447b969ff3802e01696554e95394a7adaa11920)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

2023-09-22 18:28 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/098624869c158714f3d1de6f30a7697c201fe922/airbyte-integrations/connectors/source-mongodb-v2/icon.svg" width="40" height="40"> source-mongodb-v2 test report (commit [`098624869c`](https://github.com/airbytehq/airbyte/pull/29969/commits/098624869c158714f3d1de6f30a7697c201fe922)) - ❌

⏲️  Total pipeline duration: 04mn20s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Build connector tar                                                      | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                | ✅        |
| Java Connector Integration Tests                                         | ❌        |
| Acceptance tests                                                         | ❌        |
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ❌        |
| QA checks                                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695406990/098624869c158714f3d1de6f30a7697c201fe922/source-mongodb-v2/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:098624869c158714f3d1de6f30a7697c201fe922)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

2023-09-22 18:38 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/495caffe5b5bb5fdc738e60c2fa4f6bb23a6ffca/airbyte-integrations/connectors/source-mongodb-v2/icon.svg" width="40" height="40"> source-mongodb-v2 test report (commit [`495caffe5b`](https://github.com/airbytehq/airbyte/pull/29969/commits/495caffe5b5bb5fdc738e60c2fa4f6bb23a6ffca)) - ❌

⏲️  Total pipeline duration: 03mn57s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Build connector tar                                                      | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                | ✅        |
| Java Connector Integration Tests                                         | ❌        |
| Acceptance tests                                                         | ❌        |
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ❌        |
| QA checks                                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695407608/495caffe5b5bb5fdc738e60c2fa4f6bb23a6ffca/source-mongodb-v2/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:495caffe5b5bb5fdc738e60c2fa4f6bb23a6ffca)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

2023-09-22 18:45 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/f0590c169ed9140598d5cf5b21d72cf1b142f7df/airbyte-integrations/connectors/source-mongodb-v2/icon.svg" width="40" height="40"> source-mongodb-v2 test report (commit [`f0590c169e`](https://github.com/airbytehq/airbyte/pull/29969/commits/f0590c169ed9140598d5cf5b21d72cf1b142f7df)) - ❌

⏲️  Total pipeline duration: 04mn35s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Build connector tar                                                      | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                | ✅        |
| Java Connector Integration Tests                                         | ❌        |
| Acceptance tests                                                         | ❌        |
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ❌        |
| QA checks                                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695408026/f0590c169ed9140598d5cf5b21d72cf1b142f7df/source-mongodb-v2/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:f0590c169ed9140598d5cf5b21d72cf1b142f7df)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

2023-09-22 18:48 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/f0590c169ed9140598d5cf5b21d72cf1b142f7df/airbyte-integrations/connectors/destination-mongodb-strict-encrypt/icon.svg" width="40" height="40"> destination-mongodb-strict-encrypt test report (commit [`f0590c169e`](https://github.com/airbytehq/airbyte/pull/29969/commits/f0590c169ed9140598d5cf5b21d72cf1b142f7df)) - ❌

⏲️  Total pipeline duration: 03mn22s 

| Step                                                                                      | Result   |
|:------------------------------------------------------------------------------------------|:---------|
| Build connector tar                                                                       | ✅        |
| Build destination-mongodb-strict-encrypt docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                                 | ✅        |
| Java Connector Integration Tests                                                          | ✅        |
| Validate airbyte-integrations/connectors/destination-mongodb-strict-encrypt/metadata.yaml | ✅        |
| Connector version semver check                                                            | ✅        |
| Connector version increment check                                                         | ❌        |
| QA checks                                                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695408026/f0590c169ed9140598d5cf5b21d72cf1b142f7df/destination-mongodb-strict-encrypt/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:f0590c169ed9140598d5cf5b21d72cf1b142f7df)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb-strict-encrypt test
```

2023-09-22 19:02 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/f0590c169ed9140598d5cf5b21d72cf1b142f7df/airbyte-integrations/connectors/destination-mongodb/icon.svg" width="40" height="40"> destination-mongodb test report (commit [`f0590c169e`](https://github.com/airbytehq/airbyte/pull/29969/commits/f0590c169ed9140598d5cf5b21d72cf1b142f7df)) - ❌

⏲️  Total pipeline duration: 13mn11s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Build connector tar                                                        | ✅        |
| Build destination-mongodb docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                  | ✅        |
| Java Connector Integration Tests                                           | ❌        |
| Validate airbyte-integrations/connectors/destination-mongodb/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ❌        |
| QA checks                                                                  | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695408026/f0590c169ed9140598d5cf5b21d72cf1b142f7df/destination-mongodb/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:f0590c169ed9140598d5cf5b21d72cf1b142f7df)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb test
```

2023-09-22 19:32 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/996b64af57775246a91185bdb4614fd25215c7eb/airbyte-integrations/connectors/destination-mongodb/icon.svg" width="40" height="40"> destination-mongodb test report (commit [`996b64af57`](https://github.com/airbytehq/airbyte/pull/29969/commits/996b64af57775246a91185bdb4614fd25215c7eb)) - ❌

⏲️  Total pipeline duration: 13mn47s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Build connector tar                                                        | ✅        |
| Build destination-mongodb docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                  | ✅        |
| Java Connector Integration Tests                                           | ❌        |
| Validate airbyte-integrations/connectors/destination-mongodb/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ❌        |
| QA checks                                                                  | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695410324/996b64af57775246a91185bdb4614fd25215c7eb/destination-mongodb/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:996b64af57775246a91185bdb4614fd25215c7eb)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb test
```

2023-09-22 19:35 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/996b64af57775246a91185bdb4614fd25215c7eb/airbyte-integrations/connectors/source-mongodb-v2/icon.svg" width="40" height="40"> source-mongodb-v2 test report (commit [`996b64af57`](https://github.com/airbytehq/airbyte/pull/29969/commits/996b64af57775246a91185bdb4614fd25215c7eb)) - ❌

⏲️  Total pipeline duration: 02mn56s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Build connector tar                                                      | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                | ✅        |
| Java Connector Integration Tests                                         | ❌        |
| Acceptance tests                                                         | ❌        |
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ❌        |
| QA checks                                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695410324/996b64af57775246a91185bdb4614fd25215c7eb/source-mongodb-v2/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:996b64af57775246a91185bdb4614fd25215c7eb)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

2023-09-22 19:39 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/996b64af57775246a91185bdb4614fd25215c7eb/airbyte-integrations/connectors/destination-mongodb-strict-encrypt/icon.svg" width="40" height="40"> destination-mongodb-strict-encrypt test report (commit [`996b64af57`](https://github.com/airbytehq/airbyte/pull/29969/commits/996b64af57775246a91185bdb4614fd25215c7eb)) - ❌

⏲️  Total pipeline duration: 03mn11s 

| Step                                                                                      | Result   |
|:------------------------------------------------------------------------------------------|:---------|
| Build connector tar                                                                       | ✅        |
| Build destination-mongodb-strict-encrypt docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                                 | ✅        |
| Java Connector Integration Tests                                                          | ✅        |
| Validate airbyte-integrations/connectors/destination-mongodb-strict-encrypt/metadata.yaml | ✅        |
| Connector version semver check                                                            | ✅        |
| Connector version increment check                                                         | ❌        |
| QA checks                                                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695410324/996b64af57775246a91185bdb4614fd25215c7eb/destination-mongodb-strict-encrypt/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:996b64af57775246a91185bdb4614fd25215c7eb)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb-strict-encrypt test
```

2023-09-22 20:00 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/349cd11ada16710e1748d9e18ae661ae430f50bc/airbyte-integrations/connectors/destination-mongodb/icon.svg" width="40" height="40"> destination-mongodb test report (commit [`349cd11ada`](https://github.com/airbytehq/airbyte/pull/29969/commits/349cd11ada16710e1748d9e18ae661ae430f50bc)) - ❌

⏲️  Total pipeline duration: 13mn51s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Build connector tar                                                        | ✅        |
| Build destination-mongodb docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                  | ✅        |
| Java Connector Integration Tests                                           | ❌        |
| Validate airbyte-integrations/connectors/destination-mongodb/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ❌        |
| QA checks                                                                  | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695411962/349cd11ada16710e1748d9e18ae661ae430f50bc/destination-mongodb/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:349cd11ada16710e1748d9e18ae661ae430f50bc)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb test
```

2023-09-22 20:04 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/349cd11ada16710e1748d9e18ae661ae430f50bc/airbyte-integrations/connectors/source-mongodb-v2/icon.svg" width="40" height="40"> source-mongodb-v2 test report (commit [`349cd11ada`](https://github.com/airbytehq/airbyte/pull/29969/commits/349cd11ada16710e1748d9e18ae661ae430f50bc)) - ❌

⏲️  Total pipeline duration: 03mn06s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Build connector tar                                                      | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                | ✅        |
| Java Connector Integration Tests                                         | ❌        |
| Acceptance tests                                                         | ❌        |
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ❌        |
| QA checks                                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695411962/349cd11ada16710e1748d9e18ae661ae430f50bc/source-mongodb-v2/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:349cd11ada16710e1748d9e18ae661ae430f50bc)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

2023-09-22 20:07 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/349cd11ada16710e1748d9e18ae661ae430f50bc/airbyte-integrations/connectors/destination-mongodb-strict-encrypt/icon.svg" width="40" height="40"> destination-mongodb-strict-encrypt test report (commit [`349cd11ada`](https://github.com/airbytehq/airbyte/pull/29969/commits/349cd11ada16710e1748d9e18ae661ae430f50bc)) - ❌

⏲️  Total pipeline duration: 02mn30s 

| Step                                                                                      | Result   |
|:------------------------------------------------------------------------------------------|:---------|
| Build connector tar                                                                       | ✅        |
| Build destination-mongodb-strict-encrypt docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                                 | ✅        |
| Java Connector Integration Tests                                                          | ✅        |
| Validate airbyte-integrations/connectors/destination-mongodb-strict-encrypt/metadata.yaml | ✅        |
| Connector version semver check                                                            | ✅        |
| Connector version increment check                                                         | ❌        |
| QA checks                                                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695411962/349cd11ada16710e1748d9e18ae661ae430f50bc/destination-mongodb-strict-encrypt/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:349cd11ada16710e1748d9e18ae661ae430f50bc)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb-strict-encrypt test
```

2023-09-25 13:57 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/09d3cd04f98cd3b20f0ee2624c948026504289d6/airbyte-integrations/connectors/destination-mongodb-strict-encrypt/icon.svg" width="40" height="40"> destination-mongodb-strict-encrypt test report (commit [`09d3cd04f9`](https://github.com/airbytehq/airbyte/pull/29969/commits/09d3cd04f98cd3b20f0ee2624c948026504289d6)) - ❌

⏲️  Total pipeline duration: 04mn17s 

| Step                                                                                      | Result   |
|:------------------------------------------------------------------------------------------|:---------|
| Build connector tar                                                                       | ✅        |
| Build destination-mongodb-strict-encrypt docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                                 | ✅        |
| Java Connector Integration Tests                                                          | ✅        |
| Validate airbyte-integrations/connectors/destination-mongodb-strict-encrypt/metadata.yaml | ✅        |
| Connector version semver check                                                            | ✅        |
| Connector version increment check                                                         | ❌        |
| QA checks                                                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695649945/09d3cd04f98cd3b20f0ee2624c948026504289d6/destination-mongodb-strict-encrypt/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:09d3cd04f98cd3b20f0ee2624c948026504289d6)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb-strict-encrypt test
```

2023-09-25 14:10 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/09d3cd04f98cd3b20f0ee2624c948026504289d6/airbyte-integrations/connectors/destination-mongodb/icon.svg" width="40" height="40"> destination-mongodb test report (commit [`09d3cd04f9`](https://github.com/airbytehq/airbyte/pull/29969/commits/09d3cd04f98cd3b20f0ee2624c948026504289d6)) - ❌

⏲️  Total pipeline duration: 13mn10s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Build connector tar                                                        | ✅        |
| Build destination-mongodb docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                  | ✅        |
| Java Connector Integration Tests                                           | ❌        |
| Validate airbyte-integrations/connectors/destination-mongodb/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ❌        |
| QA checks                                                                  | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695649945/09d3cd04f98cd3b20f0ee2624c948026504289d6/destination-mongodb/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:09d3cd04f98cd3b20f0ee2624c948026504289d6)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb test
```

2023-09-25 14:15 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/09d3cd04f98cd3b20f0ee2624c948026504289d6/airbyte-integrations/connectors/source-mongodb-v2/icon.svg" width="40" height="40"> source-mongodb-v2 test report (commit [`09d3cd04f9`](https://github.com/airbytehq/airbyte/pull/29969/commits/09d3cd04f98cd3b20f0ee2624c948026504289d6)) - ❌

⏲️  Total pipeline duration: 04mn24s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Build connector tar                                                      | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                | ✅        |
| Java Connector Integration Tests                                         | ❌        |
| Acceptance tests                                                         | ❌        |
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ❌        |
| QA checks                                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695649945/09d3cd04f98cd3b20f0ee2624c948026504289d6/source-mongodb-v2/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:09d3cd04f98cd3b20f0ee2624c948026504289d6)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

2023-09-25 20:47 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/8e4f65c67b1cff8d55abe61f42fae4abca24caa7/airbyte-integrations/connectors/destination-mongodb-strict-encrypt/icon.svg" width="40" height="40"> destination-mongodb-strict-encrypt test report (commit [`8e4f65c67b`](https://github.com/airbytehq/airbyte/pull/29969/commits/8e4f65c67b1cff8d55abe61f42fae4abca24caa7)) - ❌

⏲️  Total pipeline duration: 02mn21s 

| Step                                                                                      | Result   |
|:------------------------------------------------------------------------------------------|:---------|
| Build connector tar                                                                       | ✅        |
| Build destination-mongodb-strict-encrypt docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                                 | ✅        |
| Java Connector Integration Tests                                                          | ✅        |
| Validate airbyte-integrations/connectors/destination-mongodb-strict-encrypt/metadata.yaml | ✅        |
| Connector version semver check                                                            | ✅        |
| Connector version increment check                                                         | ❌        |
| QA checks                                                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695674650/8e4f65c67b1cff8d55abe61f42fae4abca24caa7/destination-mongodb-strict-encrypt/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8e4f65c67b1cff8d55abe61f42fae4abca24caa7)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb-strict-encrypt test
```

2023-09-25 20:50 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/8e4f65c67b1cff8d55abe61f42fae4abca24caa7/airbyte-integrations/connectors/source-mongodb-v2/icon.svg" width="40" height="40"> source-mongodb-v2 test report (commit [`8e4f65c67b`](https://github.com/airbytehq/airbyte/pull/29969/commits/8e4f65c67b1cff8d55abe61f42fae4abca24caa7)) - ❌

⏲️  Total pipeline duration: 03mn20s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Build connector tar                                                      | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                | ✅        |
| Java Connector Integration Tests                                         | ❌        |
| Acceptance tests                                                         | ❌        |
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ❌        |
| QA checks                                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695674650/8e4f65c67b1cff8d55abe61f42fae4abca24caa7/source-mongodb-v2/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8e4f65c67b1cff8d55abe61f42fae4abca24caa7)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

2023-09-25 21:04 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/8e4f65c67b1cff8d55abe61f42fae4abca24caa7/airbyte-integrations/connectors/destination-mongodb/icon.svg" width="40" height="40"> destination-mongodb test report (commit [`8e4f65c67b`](https://github.com/airbytehq/airbyte/pull/29969/commits/8e4f65c67b1cff8d55abe61f42fae4abca24caa7)) - ❌

⏲️  Total pipeline duration: 13mn07s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Build connector tar                                                        | ✅        |
| Build destination-mongodb docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                  | ✅        |
| Java Connector Integration Tests                                           | ❌        |
| Validate airbyte-integrations/connectors/destination-mongodb/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ❌        |
| QA checks                                                                  | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695674650/8e4f65c67b1cff8d55abe61f42fae4abca24caa7/destination-mongodb/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8e4f65c67b1cff8d55abe61f42fae4abca24caa7)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb test
```

2023-09-27 13:25 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/c27363e12370f508f9459f151fedfa546ae5d1f3/airbyte-integrations/connectors/source-mongodb-v2/icon.svg" width="40" height="40"> source-mongodb-v2 test report (commit [`c27363e123`](https://github.com/airbytehq/airbyte/pull/29969/commits/c27363e12370f508f9459f151fedfa546ae5d1f3)) - ❌

⏲️  Total pipeline duration: 05mn21s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Build connector tar                                                      | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                | ✅        |
| Java Connector Integration Tests                                         | ❌        |
| Acceptance tests                                                         | ❌        |
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ❌        |
| QA checks                                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695820728/c27363e12370f508f9459f151fedfa546ae5d1f3/source-mongodb-v2/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:c27363e12370f508f9459f151fedfa546ae5d1f3)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

2023-09-27 13:34 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/d50f4bf368eec3f3352000de84ba77c6c5b5788c/airbyte-integrations/connectors/destination-mongodb-strict-encrypt/icon.svg" width="40" height="40"> destination-mongodb-strict-encrypt test report (commit [`d50f4bf368`](https://github.com/airbytehq/airbyte/pull/29969/commits/d50f4bf368eec3f3352000de84ba77c6c5b5788c)) - ❌

⏲️  Total pipeline duration: 04mn05s 

| Step                                                                                      | Result   |
|:------------------------------------------------------------------------------------------|:---------|
| Build connector tar                                                                       | ✅        |
| Build destination-mongodb-strict-encrypt docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                                 | ✅        |
| Java Connector Integration Tests                                                          | ✅        |
| Validate airbyte-integrations/connectors/destination-mongodb-strict-encrypt/metadata.yaml | ✅        |
| Connector version semver check                                                            | ✅        |
| Connector version increment check                                                         | ❌        |
| QA checks                                                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695821366/d50f4bf368eec3f3352000de84ba77c6c5b5788c/destination-mongodb-strict-encrypt/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:d50f4bf368eec3f3352000de84ba77c6c5b5788c)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb-strict-encrypt test
```

2023-09-27 13:39 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/d50f4bf368eec3f3352000de84ba77c6c5b5788c/airbyte-integrations/connectors/source-mongodb-v2/icon.svg" width="40" height="40"> source-mongodb-v2 test report (commit [`d50f4bf368`](https://github.com/airbytehq/airbyte/pull/29969/commits/d50f4bf368eec3f3352000de84ba77c6c5b5788c)) - ❌

⏲️  Total pipeline duration: 04mn23s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Build connector tar                                                      | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                | ✅        |
| Java Connector Integration Tests                                         | ❌        |
| Acceptance tests                                                         | ❌        |
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ❌        |
| QA checks                                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695821366/d50f4bf368eec3f3352000de84ba77c6c5b5788c/source-mongodb-v2/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:d50f4bf368eec3f3352000de84ba77c6c5b5788c)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

2023-09-27 15:14 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/56459bcbf996a8e99698aec704e15a3536878c14/airbyte-integrations/connectors/source-mongodb-v2/icon.svg" width="40" height="40"> source-mongodb-v2 test report (commit [`56459bcbf9`](https://github.com/airbytehq/airbyte/pull/29969/commits/56459bcbf996a8e99698aec704e15a3536878c14)) - ❌

⏲️  Total pipeline duration: 05mn31s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Build connector tar                                                      | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                | ✅        |
| Java Connector Integration Tests                                         | ❌        |
| Acceptance tests                                                         | ❌        |
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ❌        |
| QA checks                                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695826514/56459bcbf996a8e99698aec704e15a3536878c14/source-mongodb-v2/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:56459bcbf996a8e99698aec704e15a3536878c14)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

2023-09-27 15:16 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/56459bcbf996a8e99698aec704e15a3536878c14/airbyte-integrations/connectors/destination-mongodb-strict-encrypt/icon.svg" width="40" height="40"> destination-mongodb-strict-encrypt test report (commit [`56459bcbf9`](https://github.com/airbytehq/airbyte/pull/29969/commits/56459bcbf996a8e99698aec704e15a3536878c14)) - ❌

⏲️  Total pipeline duration: 01mn33s 

| Step                                                                                      | Result   |
|:------------------------------------------------------------------------------------------|:---------|
| Build connector tar                                                                       | ✅        |
| Build destination-mongodb-strict-encrypt docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                                 | ✅        |
| Java Connector Integration Tests                                                          | ✅        |
| Validate airbyte-integrations/connectors/destination-mongodb-strict-encrypt/metadata.yaml | ✅        |
| Connector version semver check                                                            | ✅        |
| Connector version increment check                                                         | ❌        |
| QA checks                                                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695826514/56459bcbf996a8e99698aec704e15a3536878c14/destination-mongodb-strict-encrypt/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:56459bcbf996a8e99698aec704e15a3536878c14)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb-strict-encrypt test
```

2023-09-27 17:41 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/34b6848d353a09876d285112a73a45fcc4102215/airbyte-integrations/connectors/destination-mongodb-strict-encrypt/icon.svg" width="40" height="40"> destination-mongodb-strict-encrypt test report (commit [`34b6848d35`](https://github.com/airbytehq/airbyte/pull/29969/commits/34b6848d353a09876d285112a73a45fcc4102215)) - ❌

⏲️  Total pipeline duration: 02mn11s 

| Step                                                                                      | Result   |
|:------------------------------------------------------------------------------------------|:---------|
| Build connector tar                                                                       | ✅        |
| Build destination-mongodb-strict-encrypt docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                                 | ✅        |
| Java Connector Integration Tests                                                          | ✅        |
| Validate airbyte-integrations/connectors/destination-mongodb-strict-encrypt/metadata.yaml | ✅        |
| Connector version semver check                                                            | ✅        |
| Connector version increment check                                                         | ❌        |
| QA checks                                                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695836271/34b6848d353a09876d285112a73a45fcc4102215/destination-mongodb-strict-encrypt/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:34b6848d353a09876d285112a73a45fcc4102215)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb-strict-encrypt test
```

2023-09-27 17:55 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/7a7fa2f962c6636e8722d21c19ef4e0d0117a89f/airbyte-integrations/connectors/destination-mongodb-strict-encrypt/icon.svg" width="40" height="40"> destination-mongodb-strict-encrypt test report (commit [`7a7fa2f962`](https://github.com/airbytehq/airbyte/pull/29969/commits/7a7fa2f962c6636e8722d21c19ef4e0d0117a89f)) - ❌

⏲️  Total pipeline duration: 01mn46s 

| Step                                                                                      | Result   |
|:------------------------------------------------------------------------------------------|:---------|
| Build connector tar                                                                       | ✅        |
| Build destination-mongodb-strict-encrypt docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                                 | ✅        |
| Java Connector Integration Tests                                                          | ✅        |
| Validate airbyte-integrations/connectors/destination-mongodb-strict-encrypt/metadata.yaml | ✅        |
| Connector version semver check                                                            | ✅        |
| Connector version increment check                                                         | ❌        |
| QA checks                                                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695837219/7a7fa2f962c6636e8722d21c19ef4e0d0117a89f/destination-mongodb-strict-encrypt/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7a7fa2f962c6636e8722d21c19ef4e0d0117a89f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb-strict-encrypt test
```

2023-09-27 18:00 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/7a7fa2f962c6636e8722d21c19ef4e0d0117a89f/airbyte-integrations/connectors/source-mongodb-v2/icon.svg" width="40" height="40"> source-mongodb-v2 test report (commit [`7a7fa2f962`](https://github.com/airbytehq/airbyte/pull/29969/commits/7a7fa2f962c6636e8722d21c19ef4e0d0117a89f)) - ❌

⏲️  Total pipeline duration: 04mn41s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Build connector tar                                                      | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                | ✅        |
| Java Connector Integration Tests                                         | ❌        |
| Acceptance tests                                                         | ❌        |
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ❌        |
| QA checks                                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695837219/7a7fa2f962c6636e8722d21c19ef4e0d0117a89f/source-mongodb-v2/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7a7fa2f962c6636e8722d21c19ef4e0d0117a89f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

2023-09-27 18:14 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/7a7fa2f962c6636e8722d21c19ef4e0d0117a89f/airbyte-integrations/connectors/destination-mongodb/icon.svg" width="40" height="40"> destination-mongodb test report (commit [`7a7fa2f962`](https://github.com/airbytehq/airbyte/pull/29969/commits/7a7fa2f962c6636e8722d21c19ef4e0d0117a89f)) - ❌

⏲️  Total pipeline duration: 13mn23s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Build connector tar                                                        | ✅        |
| Build destination-mongodb docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                  | ✅        |
| Java Connector Integration Tests                                           | ❌        |
| Validate airbyte-integrations/connectors/destination-mongodb/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ❌        |
| QA checks                                                                  | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695837219/7a7fa2f962c6636e8722d21c19ef4e0d0117a89f/destination-mongodb/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7a7fa2f962c6636e8722d21c19ef4e0d0117a89f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb test
```

2023-09-28 19:13 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/a1a45b17900b0da7c5d7fcb5e76d559d9c9e4c08/airbyte-integrations/connectors/destination-mongodb-strict-encrypt/icon.svg" width="40" height="40"> destination-mongodb-strict-encrypt test report (commit [`a1a45b1790`](https://github.com/airbytehq/airbyte/pull/29969/commits/a1a45b17900b0da7c5d7fcb5e76d559d9c9e4c08)) - ❌

⏲️  Total pipeline duration: 03mn42s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Build connector tar                                                             | ✅        |
| Build destination-mongodb-strict-encrypt docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                                       | ✅        |
| Java Connector Integration Tests                                                | ✅        |
| Validate metadata for destination-mongodb-strict-encrypt                        | ✅        |
| Connector version semver check                                                  | ✅        |
| Connector version increment check                                               | ❌        |
| QA checks                                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695928134/a1a45b17900b0da7c5d7fcb5e76d559d9c9e4c08/destination-mongodb-strict-encrypt/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:a1a45b17900b0da7c5d7fcb5e76d559d9c9e4c08)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb-strict-encrypt test
```

2023-09-28 19:25 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/797cda00d661b32f44be2ffa764c40aef2420fb3/airbyte-integrations/connectors/source-mongodb-v2/icon.svg" width="40" height="40"> source-mongodb-v2 test report (commit [`797cda00d6`](https://github.com/airbytehq/airbyte/pull/29969/commits/797cda00d661b32f44be2ffa764c40aef2420fb3)) - ❌

⏲️  Total pipeline duration: 07mn11s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build connector tar                                            | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                      | ✅        |
| Java Connector Integration Tests                               | ❌        |
| Acceptance tests                                               | ❌        |
| Validate metadata for source-mongodb-v2                        | ✅        |
| Connector version semver check                                 | ✅        |
| Connector version increment check                              | ❌        |
| QA checks                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695928648/797cda00d661b32f44be2ffa764c40aef2420fb3/source-mongodb-v2/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:797cda00d661b32f44be2ffa764c40aef2420fb3)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

2023-09-28 19:30 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/797cda00d661b32f44be2ffa764c40aef2420fb3/airbyte-integrations/connectors/destination-mongodb-strict-encrypt/icon.svg" width="40" height="40"> destination-mongodb-strict-encrypt test report (commit [`797cda00d6`](https://github.com/airbytehq/airbyte/pull/29969/commits/797cda00d661b32f44be2ffa764c40aef2420fb3)) - ❌

⏲️  Total pipeline duration: 04mn27s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Build connector tar                                                             | ✅        |
| Build destination-mongodb-strict-encrypt docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                                       | ✅        |
| Java Connector Integration Tests                                                | ✅        |
| Validate metadata for destination-mongodb-strict-encrypt                        | ✅        |
| Connector version semver check                                                  | ✅        |
| Connector version increment check                                               | ❌        |
| QA checks                                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1695928648/797cda00d661b32f44be2ffa764c40aef2420fb3/destination-mongodb-strict-encrypt/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:797cda00d661b32f44be2ffa764c40aef2420fb3)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb-strict-encrypt test
```

2023-09-29 16:11 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/244d9f3733ce88806556ff02751eed9c318ceaf0/airbyte-integrations/connectors/destination-mongodb/icon.svg" width="40" height="40"> destination-mongodb test report (commit [`244d9f3733`](https://github.com/airbytehq/airbyte/pull/29969/commits/244d9f3733ce88806556ff02751eed9c318ceaf0)) - ❌

⏲️  Total pipeline duration: 16mn48s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Build connector tar                                              | ✅        |
| Build destination-mongodb docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                        | ✅        |
| Java Connector Integration Tests                                 | ❌        |
| Validate metadata for destination-mongodb                        | ✅        |
| Connector version semver check                                   | ✅        |
| Connector version increment check                                | ❌        |
| QA checks                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696002849/244d9f3733ce88806556ff02751eed9c318ceaf0/destination-mongodb/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:244d9f3733ce88806556ff02751eed9c318ceaf0)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb test
```

2023-09-29 16:15 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/244d9f3733ce88806556ff02751eed9c318ceaf0/airbyte-integrations/connectors/destination-mongodb-strict-encrypt/icon.svg" width="40" height="40"> destination-mongodb-strict-encrypt test report (commit [`244d9f3733`](https://github.com/airbytehq/airbyte/pull/29969/commits/244d9f3733ce88806556ff02751eed9c318ceaf0)) - ❌

⏲️  Total pipeline duration: 04mn10s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Build connector tar                                                             | ✅        |
| Build destination-mongodb-strict-encrypt docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                                       | ✅        |
| Java Connector Integration Tests                                                | ✅        |
| Validate metadata for destination-mongodb-strict-encrypt                        | ✅        |
| Connector version semver check                                                  | ✅        |
| Connector version increment check                                               | ❌        |
| QA checks                                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696002849/244d9f3733ce88806556ff02751eed9c318ceaf0/destination-mongodb-strict-encrypt/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:244d9f3733ce88806556ff02751eed9c318ceaf0)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb-strict-encrypt test
```

2023-09-29 16:24 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/26b82718b6443f97a4f6e8f839220702b6f3cf3f/airbyte-integrations/connectors/destination-mongodb-strict-encrypt/icon.svg" width="40" height="40"> destination-mongodb-strict-encrypt test report (commit [`26b82718b6`](https://github.com/airbytehq/airbyte/pull/29969/commits/26b82718b6443f97a4f6e8f839220702b6f3cf3f)) - ❌

⏲️  Total pipeline duration: 05mn44s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Build connector tar                                                             | ✅        |
| Build destination-mongodb-strict-encrypt docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                                       | ✅        |
| Java Connector Integration Tests                                                | ✅        |
| Validate metadata for destination-mongodb-strict-encrypt                        | ✅        |
| Connector version semver check                                                  | ✅        |
| Connector version increment check                                               | ❌        |
| QA checks                                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696004246/26b82718b6443f97a4f6e8f839220702b6f3cf3f/destination-mongodb-strict-encrypt/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:26b82718b6443f97a4f6e8f839220702b6f3cf3f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb-strict-encrypt test
```

2023-09-29 16:38 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/26b82718b6443f97a4f6e8f839220702b6f3cf3f/airbyte-integrations/connectors/destination-mongodb/icon.svg" width="40" height="40"> destination-mongodb test report (commit [`26b82718b6`](https://github.com/airbytehq/airbyte/pull/29969/commits/26b82718b6443f97a4f6e8f839220702b6f3cf3f)) - ❌

⏲️  Total pipeline duration: 13mn51s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Build connector tar                                              | ✅        |
| Build destination-mongodb docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                        | ✅        |
| Java Connector Integration Tests                                 | ❌        |
| Validate metadata for destination-mongodb                        | ✅        |
| Connector version semver check                                   | ✅        |
| Connector version increment check                                | ❌        |
| QA checks                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696004246/26b82718b6443f97a4f6e8f839220702b6f3cf3f/destination-mongodb/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:26b82718b6443f97a4f6e8f839220702b6f3cf3f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb test
```

2023-09-29 16:44 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/26b82718b6443f97a4f6e8f839220702b6f3cf3f/airbyte-integrations/connectors/source-mongodb-v2/icon.svg" width="40" height="40"> source-mongodb-v2 test report (commit [`26b82718b6`](https://github.com/airbytehq/airbyte/pull/29969/commits/26b82718b6443f97a4f6e8f839220702b6f3cf3f)) - ❌

⏲️  Total pipeline duration: 06mn12s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build connector tar                                            | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                      | ✅        |
| Java Connector Integration Tests                               | ❌        |
| Acceptance tests                                               | ❌        |
| Validate metadata for source-mongodb-v2                        | ✅        |
| Connector version semver check                                 | ✅        |
| Connector version increment check                              | ❌        |
| QA checks                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696004246/26b82718b6443f97a4f6e8f839220702b6f3cf3f/source-mongodb-v2/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:26b82718b6443f97a4f6e8f839220702b6f3cf3f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

2023-09-29 18:24 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/99a2404ae29f16ae1dff55431a928b6ec8d87444/airbyte-integrations/connectors/source-mongodb-v2/icon.svg" width="40" height="40"> source-mongodb-v2 test report (commit [`99a2404ae2`](https://github.com/airbytehq/airbyte/pull/29969/commits/99a2404ae29f16ae1dff55431a928b6ec8d87444)) - ❌

⏲️  Total pipeline duration: 05mn23s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build connector tar                                            | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                      | ✅        |
| Java Connector Integration Tests                               | ❌        |
| Acceptance tests                                               | ❌        |
| Validate metadata for source-mongodb-v2                        | ✅        |
| Connector version semver check                                 | ✅        |
| Connector version increment check                              | ❌        |
| QA checks                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696011486/99a2404ae29f16ae1dff55431a928b6ec8d87444/source-mongodb-v2/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:99a2404ae29f16ae1dff55431a928b6ec8d87444)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

2023-09-29 18:28 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/99a2404ae29f16ae1dff55431a928b6ec8d87444/airbyte-integrations/connectors/destination-mongodb-strict-encrypt/icon.svg" width="40" height="40"> destination-mongodb-strict-encrypt test report (commit [`99a2404ae2`](https://github.com/airbytehq/airbyte/pull/29969/commits/99a2404ae29f16ae1dff55431a928b6ec8d87444)) - ❌

⏲️  Total pipeline duration: 03mn25s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Build connector tar                                                             | ✅        |
| Build destination-mongodb-strict-encrypt docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                                       | ✅        |
| Java Connector Integration Tests                                                | ✅        |
| Validate metadata for destination-mongodb-strict-encrypt                        | ✅        |
| Connector version semver check                                                  | ✅        |
| Connector version increment check                                               | ❌        |
| QA checks                                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696011486/99a2404ae29f16ae1dff55431a928b6ec8d87444/destination-mongodb-strict-encrypt/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:99a2404ae29f16ae1dff55431a928b6ec8d87444)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb-strict-encrypt test
```

2023-09-29 18:48 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/f4fbb73ff8b361820209209375f62f940c8644c6/airbyte-integrations/connectors/destination-mongodb-strict-encrypt/icon.svg" width="40" height="40"> destination-mongodb-strict-encrypt test report (commit [`f4fbb73ff8`](https://github.com/airbytehq/airbyte/pull/29969/commits/f4fbb73ff8b361820209209375f62f940c8644c6)) - ❌

⏲️  Total pipeline duration: 03mn27s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Build connector tar                                                             | ✅        |
| Build destination-mongodb-strict-encrypt docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                                       | ✅        |
| Java Connector Integration Tests                                                | ✅        |
| Validate metadata for destination-mongodb-strict-encrypt                        | ✅        |
| Connector version semver check                                                  | ✅        |
| Connector version increment check                                               | ❌        |
| QA checks                                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696013012/f4fbb73ff8b361820209209375f62f940c8644c6/destination-mongodb-strict-encrypt/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:f4fbb73ff8b361820209209375f62f940c8644c6)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb-strict-encrypt test
```

2023-09-29 19:02 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/f4fbb73ff8b361820209209375f62f940c8644c6/airbyte-integrations/connectors/destination-mongodb/icon.svg" width="40" height="40"> destination-mongodb test report (commit [`f4fbb73ff8`](https://github.com/airbytehq/airbyte/pull/29969/commits/f4fbb73ff8b361820209209375f62f940c8644c6)) - ❌

⏲️  Total pipeline duration: 14mn26s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Build connector tar                                              | ✅        |
| Build destination-mongodb docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                        | ✅        |
| Java Connector Integration Tests                                 | ❌        |
| Validate metadata for destination-mongodb                        | ✅        |
| Connector version semver check                                   | ✅        |
| Connector version increment check                                | ❌        |
| QA checks                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696013012/f4fbb73ff8b361820209209375f62f940c8644c6/destination-mongodb/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:f4fbb73ff8b361820209209375f62f940c8644c6)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb test
```

2023-09-29 19:09 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/f4fbb73ff8b361820209209375f62f940c8644c6/airbyte-integrations/connectors/source-mongodb-v2/icon.svg" width="40" height="40"> source-mongodb-v2 test report (commit [`f4fbb73ff8`](https://github.com/airbytehq/airbyte/pull/29969/commits/f4fbb73ff8b361820209209375f62f940c8644c6)) - ❌

⏲️  Total pipeline duration: 06mn18s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build connector tar                                            | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                      | ✅        |
| Java Connector Integration Tests                               | ❌        |
| Acceptance tests                                               | ❌        |
| Validate metadata for source-mongodb-v2                        | ✅        |
| Connector version semver check                                 | ✅        |
| Connector version increment check                              | ❌        |
| QA checks                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696013012/f4fbb73ff8b361820209209375f62f940c8644c6/source-mongodb-v2/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:f4fbb73ff8b361820209209375f62f940c8644c6)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

2023-10-02 15:23 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/d4d7dd8e57d2f09dda59bf1b9e04014327cd9e4b/airbyte-integrations/connectors/source-mongodb-v2/icon.svg" width="40" height="40"> source-mongodb-v2 test report (commit [`d4d7dd8e57`](https://github.com/airbytehq/airbyte/pull/29969/commits/d4d7dd8e57d2f09dda59bf1b9e04014327cd9e4b)) - ❌

⏲️  Total pipeline duration: 04mn10s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build connector tar                                            | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                      | ✅        |
| Java Connector Integration Tests                               | ❌        |
| Acceptance tests                                               | ❌        |
| Validate metadata for source-mongodb-v2                        | ✅        |
| Connector version semver check                                 | ✅        |
| Connector version increment check                              | ❌        |
| QA checks                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696259935/d4d7dd8e57d2f09dda59bf1b9e04014327cd9e4b/source-mongodb-v2/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:d4d7dd8e57d2f09dda59bf1b9e04014327cd9e4b)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

2023-10-02 15:43 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/d4d7dd8e57d2f09dda59bf1b9e04014327cd9e4b/airbyte-integrations/connectors/destination-mongodb/icon.svg" width="40" height="40"> destination-mongodb test report (commit [`d4d7dd8e57`](https://github.com/airbytehq/airbyte/pull/29969/commits/d4d7dd8e57d2f09dda59bf1b9e04014327cd9e4b)) - ❌

⏲️  Total pipeline duration: 14mn23s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Build connector tar                                              | ✅        |
| Build destination-mongodb docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                        | ✅        |
| Java Connector Integration Tests                                 | ❌        |
| Validate metadata for destination-mongodb                        | ✅        |
| Connector version semver check                                   | ✅        |
| Connector version increment check                                | ❌        |
| QA checks                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696259935/d4d7dd8e57d2f09dda59bf1b9e04014327cd9e4b/destination-mongodb/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:d4d7dd8e57d2f09dda59bf1b9e04014327cd9e4b)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb test
```

2023-10-02 18:07 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/01824fc7bb7978a8cd354ebbc8bba8befef0ce7d/airbyte-integrations/connectors/destination-mongodb/icon.svg" width="40" height="40"> destination-mongodb test report (commit [`01824fc7bb`](https://github.com/airbytehq/airbyte/pull/29969/commits/01824fc7bb7978a8cd354ebbc8bba8befef0ce7d)) - ❌

⏲️  Total pipeline duration: 15mn20s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Build connector tar                                              | ✅        |
| Build destination-mongodb docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                        | ✅        |
| Java Connector Integration Tests                                 | ❌        |
| Validate metadata for destination-mongodb                        | ✅        |
| Connector version semver check                                   | ✅        |
| Connector version increment check                                | ❌        |
| QA checks                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696269097/01824fc7bb7978a8cd354ebbc8bba8befef0ce7d/destination-mongodb/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:01824fc7bb7978a8cd354ebbc8bba8befef0ce7d)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb test
```

2023-10-02 21:36 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/4f1585ca0e4cf5485a1d864746e5f75f26a76541/airbyte-integrations/connectors/destination-mongodb-strict-encrypt/icon.svg" width="40" height="40"> destination-mongodb-strict-encrypt test report (commit [`4f1585ca0e`](https://github.com/airbytehq/airbyte/pull/29969/commits/4f1585ca0e4cf5485a1d864746e5f75f26a76541)) - ❌

⏲️  Total pipeline duration: 04mn09s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Build connector tar                                                             | ✅        |
| Build destination-mongodb-strict-encrypt docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                                       | ✅        |
| Java Connector Integration Tests                                                | ✅        |
| Validate metadata for destination-mongodb-strict-encrypt                        | ✅        |
| Connector version semver check                                                  | ✅        |
| Connector version increment check                                               | ❌        |
| QA checks                                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696282279/4f1585ca0e4cf5485a1d864746e5f75f26a76541/destination-mongodb-strict-encrypt/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:4f1585ca0e4cf5485a1d864746e5f75f26a76541)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb-strict-encrypt test
```

2023-10-02 21:52 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/4f1585ca0e4cf5485a1d864746e5f75f26a76541/airbyte-integrations/connectors/destination-mongodb/icon.svg" width="40" height="40"> destination-mongodb test report (commit [`4f1585ca0e`](https://github.com/airbytehq/airbyte/pull/29969/commits/4f1585ca0e4cf5485a1d864746e5f75f26a76541)) - ❌

⏲️  Total pipeline duration: 16mn40s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Build connector tar                                              | ✅        |
| Build destination-mongodb docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                        | ✅        |
| Java Connector Integration Tests                                 | ❌        |
| Validate metadata for destination-mongodb                        | ✅        |
| Connector version semver check                                   | ✅        |
| Connector version increment check                                | ❌        |
| QA checks                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696282279/4f1585ca0e4cf5485a1d864746e5f75f26a76541/destination-mongodb/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:4f1585ca0e4cf5485a1d864746e5f75f26a76541)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb test
```

2023-10-02 22:07 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/4f1585ca0e4cf5485a1d864746e5f75f26a76541/airbyte-integrations/connectors/source-mongodb-v2/icon.svg" width="40" height="40"> source-mongodb-v2 test report (commit [`4f1585ca0e`](https://github.com/airbytehq/airbyte/pull/29969/commits/4f1585ca0e4cf5485a1d864746e5f75f26a76541)) - ❌

⏲️  Total pipeline duration: 14mn27s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build connector tar                                            | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                      | ✅        |
| Java Connector Integration Tests                               | ✅        |
| Acceptance tests                                               | ❌        |
| Validate metadata for source-mongodb-v2                        | ✅        |
| Connector version semver check                                 | ✅        |
| Connector version increment check                              | ❌        |
| QA checks                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696282279/4f1585ca0e4cf5485a1d864746e5f75f26a76541/source-mongodb-v2/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:4f1585ca0e4cf5485a1d864746e5f75f26a76541)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

2023-10-02 23:53 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/8e1489b7a54e873d5d557a2ab5cc13583c5ebd91/airbyte-integrations/connectors/source-mongodb-v2/icon.svg" width="40" height="40"> source-mongodb-v2 test report (commit [`8e1489b7a5`](https://github.com/airbytehq/airbyte/pull/29969/commits/8e1489b7a54e873d5d557a2ab5cc13583c5ebd91)) - ❌

⏲️  Total pipeline duration: 11mn06s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build connector tar                                            | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                      | ✅        |
| Java Connector Integration Tests                               | ❌        |
| Acceptance tests                                               | ❌        |
| Validate metadata for source-mongodb-v2                        | ✅        |
| Connector version semver check                                 | ✅        |
| Connector version increment check                              | ❌        |
| QA checks                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696290068/8e1489b7a54e873d5d557a2ab5cc13583c5ebd91/source-mongodb-v2/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8e1489b7a54e873d5d557a2ab5cc13583c5ebd91)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

2023-10-03 00:08 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/8e1489b7a54e873d5d557a2ab5cc13583c5ebd91/airbyte-integrations/connectors/destination-mongodb/icon.svg" width="40" height="40"> destination-mongodb test report (commit [`8e1489b7a5`](https://github.com/airbytehq/airbyte/pull/29969/commits/8e1489b7a54e873d5d557a2ab5cc13583c5ebd91)) - ❌

⏲️  Total pipeline duration: 15mn02s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Build connector tar                                              | ✅        |
| Build destination-mongodb docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                        | ✅        |
| Java Connector Integration Tests                                 | ❌        |
| Validate metadata for destination-mongodb                        | ✅        |
| Connector version semver check                                   | ✅        |
| Connector version increment check                                | ❌        |
| QA checks                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696290068/8e1489b7a54e873d5d557a2ab5cc13583c5ebd91/destination-mongodb/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8e1489b7a54e873d5d557a2ab5cc13583c5ebd91)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb test
```

2023-10-03 00:13 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/8e1489b7a54e873d5d557a2ab5cc13583c5ebd91/airbyte-integrations/connectors/destination-mongodb-strict-encrypt/icon.svg" width="40" height="40"> destination-mongodb-strict-encrypt test report (commit [`8e1489b7a5`](https://github.com/airbytehq/airbyte/pull/29969/commits/8e1489b7a54e873d5d557a2ab5cc13583c5ebd91)) - ❌

⏲️  Total pipeline duration: 04mn25s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Build connector tar                                                             | ✅        |
| Build destination-mongodb-strict-encrypt docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                                       | ✅        |
| Java Connector Integration Tests                                                | ✅        |
| Validate metadata for destination-mongodb-strict-encrypt                        | ✅        |
| Connector version semver check                                                  | ✅        |
| Connector version increment check                                               | ❌        |
| QA checks                                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696290068/8e1489b7a54e873d5d557a2ab5cc13583c5ebd91/destination-mongodb-strict-encrypt/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8e1489b7a54e873d5d557a2ab5cc13583c5ebd91)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb-strict-encrypt test
```

2023-10-03 16:05 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/4662d15db2d7d851a471e0445f87f8f1d5791a10/airbyte-integrations/connectors/source-mongodb-v2/icon.svg" width="40" height="40"> source-mongodb-v2 test report (commit [`4662d15db2`](https://github.com/airbytehq/airbyte/pull/29969/commits/4662d15db2d7d851a471e0445f87f8f1d5791a10)) - ❌

⏲️  Total pipeline duration: 13mn11s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build connector tar                                            | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                      | ❌        |
| Java Connector Integration Tests                               | ✅        |
| Acceptance tests                                               | ✅        |
| Validate metadata for source-mongodb-v2                        | ❌        |
| Connector version semver check                                 | ✅        |
| Connector version increment check                              | ✅        |
| QA checks                                                      | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696347312/4662d15db2d7d851a471e0445f87f8f1d5791a10/source-mongodb-v2/1.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:4662d15db2d7d851a471e0445f87f8f1d5791a10)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

2023-10-03 16:10 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/4662d15db2d7d851a471e0445f87f8f1d5791a10/airbyte-integrations/connectors/destination-mongodb-strict-encrypt/icon.svg" width="40" height="40"> destination-mongodb-strict-encrypt test report (commit [`4662d15db2`](https://github.com/airbytehq/airbyte/pull/29969/commits/4662d15db2d7d851a471e0445f87f8f1d5791a10)) - ❌

⏲️  Total pipeline duration: 04mn25s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Build connector tar                                                             | ✅        |
| Build destination-mongodb-strict-encrypt docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                                       | ✅        |
| Java Connector Integration Tests                                                | ✅        |
| Validate metadata for destination-mongodb-strict-encrypt                        | ✅        |
| Connector version semver check                                                  | ✅        |
| Connector version increment check                                               | ❌        |
| QA checks                                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696347312/4662d15db2d7d851a471e0445f87f8f1d5791a10/destination-mongodb-strict-encrypt/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:4662d15db2d7d851a471e0445f87f8f1d5791a10)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb-strict-encrypt test
```

2023-10-03 16:31 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/6e140193ca7fe6802ad27594bbbf17670143d7bd/airbyte-integrations/connectors/destination-mongodb/icon.svg" width="40" height="40"> destination-mongodb test report (commit [`6e140193ca`](https://github.com/airbytehq/airbyte/pull/29969/commits/6e140193ca7fe6802ad27594bbbf17670143d7bd)) - ❌

⏲️  Total pipeline duration: 15mn00s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Build connector tar                                              | ✅        |
| Build destination-mongodb docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                        | ✅        |
| Java Connector Integration Tests                                 | ❌        |
| Validate metadata for destination-mongodb                        | ✅        |
| Connector version semver check                                   | ✅        |
| Connector version increment check                                | ❌        |
| QA checks                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696349761/6e140193ca7fe6802ad27594bbbf17670143d7bd/destination-mongodb/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6e140193ca7fe6802ad27594bbbf17670143d7bd)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb test
```

2023-10-03 16:49 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/1d92990af5e0ed242ea4d5f13742502b0b6298fb/airbyte-integrations/connectors/destination-mongodb-strict-encrypt/icon.svg" width="40" height="40"> destination-mongodb-strict-encrypt test report (commit [`1d92990af5`](https://github.com/airbytehq/airbyte/pull/29969/commits/1d92990af5e0ed242ea4d5f13742502b0b6298fb)) - ❌

⏲️  Total pipeline duration: 05mn51s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Build connector tar                                                             | ✅        |
| Build destination-mongodb-strict-encrypt docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                                       | ✅        |
| Java Connector Integration Tests                                                | ✅        |
| Validate metadata for destination-mongodb-strict-encrypt                        | ✅        |
| Connector version semver check                                                  | ✅        |
| Connector version increment check                                               | ❌        |
| QA checks                                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696351337/1d92990af5e0ed242ea4d5f13742502b0b6298fb/destination-mongodb-strict-encrypt/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1d92990af5e0ed242ea4d5f13742502b0b6298fb)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb-strict-encrypt test
```

2023-10-03 17:07 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/6fabc7d9787f8420e4dacf868c14409274fd549c/airbyte-integrations/connectors/destination-mongodb-strict-encrypt/icon.svg" width="40" height="40"> destination-mongodb-strict-encrypt test report (commit [`6fabc7d978`](https://github.com/airbytehq/airbyte/pull/29969/commits/6fabc7d9787f8420e4dacf868c14409274fd549c)) - ❌

⏲️  Total pipeline duration: 03mn31s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Build connector tar                                                             | ✅        |
| Build destination-mongodb-strict-encrypt docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                                       | ✅        |
| Java Connector Integration Tests                                                | ✅        |
| Validate metadata for destination-mongodb-strict-encrypt                        | ✅        |
| Connector version semver check                                                  | ✅        |
| Connector version increment check                                               | ❌        |
| QA checks                                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696352549/6fabc7d9787f8420e4dacf868c14409274fd549c/destination-mongodb-strict-encrypt/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6fabc7d9787f8420e4dacf868c14409274fd549c)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb-strict-encrypt test
```

2023-10-03 17:21 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/6fabc7d9787f8420e4dacf868c14409274fd549c/airbyte-integrations/connectors/source-mongodb-v2/icon.svg" width="40" height="40"> source-mongodb-v2 test report (commit [`6fabc7d978`](https://github.com/airbytehq/airbyte/pull/29969/commits/6fabc7d9787f8420e4dacf868c14409274fd549c)) - ✅

⏲️  Total pipeline duration: 13mn55s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build connector tar                                            | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                      | ✅        |
| Java Connector Integration Tests                               | ✅        |
| Acceptance tests                                               | ✅        |
| Validate metadata for source-mongodb-v2                        | ✅        |
| Connector version semver check                                 | ✅        |
| Connector version increment check                              | ✅        |
| QA checks                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696352549/6fabc7d9787f8420e4dacf868c14409274fd549c/source-mongodb-v2/1.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6fabc7d9787f8420e4dacf868c14409274fd549c)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

2023-10-03 17:35 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/6fabc7d9787f8420e4dacf868c14409274fd549c/airbyte-integrations/connectors/destination-mongodb/icon.svg" width="40" height="40"> destination-mongodb test report (commit [`6fabc7d978`](https://github.com/airbytehq/airbyte/pull/29969/commits/6fabc7d9787f8420e4dacf868c14409274fd549c)) - ❌

⏲️  Total pipeline duration: 14mn10s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Build connector tar                                              | ✅        |
| Build destination-mongodb docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                        | ✅        |
| Java Connector Integration Tests                                 | ❌        |
| Validate metadata for destination-mongodb                        | ✅        |
| Connector version semver check                                   | ✅        |
| Connector version increment check                                | ❌        |
| QA checks                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_cdc-integration/1696352549/6fabc7d9787f8420e4dacf868c14409274fd549c/destination-mongodb/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6fabc7d9787f8420e4dacf868c14409274fd549c)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb test
```

2023-10-03 17:36 UTC, jdpgrailsdev commented
/approve-and-merge reason="release mongodb source v2"

2023-10-03 17:37 UTC, octavia-approvington commented
Lets do it! <br/> ![giddddy-up](https://media3.giphy.com/media/aMh59aKR8vjdC/giphy.gif?cid=ecf05e47yfhzd9ee59baopruw1v0bp8pyrvxp13qlxix22ig&rid=giphy.gif&ct=g)

2023-10-03 17:37 UTC, octavia-approvington approved these changes

2023-10-03 17:37 UTC, merged