Valdemar/#2910 1
airbytehq/airbyte pull request #3008
Opened 2021-04-21 12:58 UTC by vovavovavovavova

## What
Supports array of Objects in source_http_request

## Pre-merge Checklist
- [ ] *Run integration tests*
- [ ] *Publish Docker images*

## Recommended reading order
1. `test.java`
1. `component.ts`
1. the rest

2021-04-21 13:13 UTC, keu commented on airbyte-integrations/connectors/source-http-request/source_http_request/source.py
> +        data = r.json()
ok, lets make it DRY
```python
if not isinstance(data, list):
   data = [data]

for record in data:
    yield AirbyteMessage(
                    type=Type.RECORD,
                    record=AirbyteRecordMessage(
                        stream=SourceHttpRequest.STREAM_NAME,
                        data=obj,
                        emitted_at=int(datetime.now().timestamp()) * 1000
                    )
                )
```

2021-04-21 13:13 UTC, keu requested changes
suggestion

2021-04-28 12:57 UTC, vovavovavovavova commented
/test connector=source-http-request

2021-04-28 15:41 UTC, keu approved these changes

2021-04-29 07:14 UTC, sherifnada approved these changes

2021-04-30 22:21 UTC, keu commented
/publish connector=connectors/source-http-request

2021-04-30 22:22 UTC, merged