Source Google Analytics Data API: ability to add multiple property ids
airbytehq/airbyte pull request #30152
Opened 2023-09-05 11:56 UTC by roman-yermilov-gl

…y ids

## What
*https://github.com/airbytehq/airbyte/issues/24739*

## How
**

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

2023-09-08 13:30 UTC, roman-yermilov-gl commented
There is another option that let us not to rollback to old API version. We can add `?include=customer` query param: (https://developer.rechargepayments.com/2021-11/extending_responses), so we will have entier `customer` model included in response in this way:
```
{
    "id": 534919106,
    ...,
    "customer": {
        "id": 64962974,
        "email": "email@example.com",
        "external_customer_id": {
            "ecommerce": "5213433266347"
        },
        "hash": "f99bd4a6877257af"
    },
    "include": {
        "customer": {
            "id": 10000000,
            "analytics_data": {
                "utm_params": []
            },
            "created_at": "2021-05-13T09:46:44+00:00",
            "email": "email@example.com",
            "external_customer_id": {
                "ecommerce": "5213433266347"
            },
            "first_charge_processed_at": "2021-05-13T13:46:39+00:00",
            "first_name": "Banana",
            "has_payment_method_in_dunning": false,
            "has_valid_payment_method": true,
            "hash": "f99bd4a6877257af",
            "last_name": "Green",
            "phone": "+11111111111",
            "subscriptions_active_count": 1,
            "subscriptions_total_count": 1,
            "tax_exempt": false,
            "updated_at": "2023-05-13T04:16:36+00:00"
        }
    }
    ...
}
```
It let us transform a record, so we can put missing fields from `include.customer.<field>` to `customer.<field>`. There are also some disadvatages: record will contain more data and we will have some duplicated fields.
I am not requesting change. This is only an another of how we can fix this problem

2023-09-08 19:23 UTC, lazebnyi requested changes

2023-09-08 19:23 UTC, lazebnyi commented on airbyte-integrations/connectors/source-google-analytics-data-api/unit_tests/test_source.py
> +        "property_ids": ["108176369"],
can we add unit test with old config and try test backward compatibility in that way

2023-09-08 19:23 UTC, lazebnyi commented on airbyte-integrations/connectors/source-google-analytics-data-api/source_google_analytics_data_api/spec.json
> +    "required": ["property_ids", "date_ranges_start_date"],
do you test those changes manually for backward compatibility?

2023-09-08 19:23 UTC, lazebnyi commented on airbyte-integrations/connectors/source-google-analytics-data-api/source_google_analytics_data_api/source.py
> +                if invalid_dimensions:
please add spaces between condition blocks and add comments for them

2023-09-08 19:23 UTC, lazebnyi commented on airbyte-integrations/connectors/source-google-analytics-data-api/source_google_analytics_data_api/source.py
> +                return False, "failed to get metadata, over quota, try later"
Error message better start with upper case letter

2023-09-08 19:23 UTC, lazebnyi commented on airbyte-integrations/connectors/source-google-analytics-data-api/unit_tests/test_streams.py
> +            "property_ids": ["496180525"],
if an old config has not property_ids 

what happens next?

2023-09-12 20:18 UTC, roman-yermilov-gl commented on airbyte-integrations/connectors/source-google-analytics-data-api/source_google_analytics_data_api/source.py
> +                return False, "failed to get metadata, over quota, try later"
Done

2023-09-13 17:11 UTC, lazebnyi requested changes
Please run tests with old format config

2023-09-13 18:17 UTC, roman-yermilov-gl commented
> Please run tests with old format config

The tests were run with old config. If format is new, it means migration was applied during CI run

2023-09-13 18:18 UTC, lazebnyi approved these changes

2023-09-13 18:31 UTC, lazebnyi approved these changes

2023-09-14 11:12 UTC, merged

2024-01-17 17:41 UTC, Talalqaddoumi commented
I recommend consolidating the data into the same stream rather than creating a stream per table per property. The latter approach proves unhelpful and leads to complications when refreshing the source schema, especially after the addition of numerous properties. Currently, I'm facing difficulties generating and refreshing the source schema in a setup with 160 properties.

Here is an illustration of the challenge:
![image](https://github.com/airbytehq/airbyte/assets/22478086/0c8cfdc8-992d-45dd-b499-c8e9bedd7278)

Furthermore, adopting this approach would necessitate additional transformations in the destination to append the data into a single table.