Destination snowflake: Handle namespace/stream name/columns containing `${`
airbytehq/airbyte pull request #30416
Opened 2023-09-13 22:41 UTC by edgao

closes https://github.com/airbytehq/airbyte/issues/30391

The underlying problem is that `EXECUTE IMMEDIATE` throws an error if you have a string or identifier containing the `${` bigram in your script block. Make two changes to support this:
* `${` is now replaced by `__` (double underscore) in table, schema, and column names
  * This is not a breaking change - previously this was crashing the sync; now the sync no longer crashes
* There's a massive hack in the PK validation code to support this

Notably: there's now a distinction between `escapeJsonIdentifier` and `escapeSqlIdentifier`, because we still need to query the raw data as `"_airbyte_data":"${foo}`.

2023-09-13 22:50 UTC, evantahler commented
`bigram` - today I learned!

2023-09-13 22:51 UTC, evantahler commented
> For the original issue, this means we'll end up with a column "__meta_ads}"... do we want to also turn that final } into an underscore?

If it's not difficult, yes I'd say to remove the final `}`, but don't spend too much time on it

2023-09-13 22:52 UTC, evantahler requested changes
There probably should be a test for a column with a `${}` too

2023-09-13 23:49 UTC, edgao commented
@evantahler I added some commits which are individually reviewable, PTAL

2023-09-14 01:11 UTC, evantahler approved these changes
✔️

2023-09-14 15:17 UTC, merged