[Non-Forked] Source Pipedrive : Migrate Python CDK to Low-code CDK
airbytehq/airbyte pull request #30553
Opened 2023-09-18 20:38 UTC by archangelic

## What
Non-forked branch for PR #29293 

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:generateScaffolds` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

2023-09-20 21:36 UTC, marcosmarxm requested changes
Some comments.

2023-09-20 21:36 UTC, marcosmarxm commented on docs/integrations/sources/pipedrive-migrations.md
> +Please update your config. This version has changed the config to only require an API key.
update your config and reset your data (to match the new format)

2023-09-20 21:36 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-pipedrive/source_pipedrive/manifest.yaml
> +      - replication_start_date
`api_token` should be required.

2023-09-20 21:36 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-pipedrive/source_pipedrive/manifest.yaml
> +  products_fields_stream:
This must be `product_fields`  not `products_fields`.

2023-09-20 22:06 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/d97b030851f257554e82599134b10efebec8b571/airbyte-integrations/connectors/source-pipedrive/icon.svg" width="40" height="40"> source-pipedrive test report (commit [`d97b030851`](https://github.com/airbytehq/airbyte/pull/30553/commits/d97b030851f257554e82599134b10efebec8b571)) - ✅

⏲️  Total pipeline duration: 02mn03s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Connector package install                                               | ✅        |
| Build source-pipedrive docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                        | ✅        |
| Code format checks                                                      | ✅        |
| Validate airbyte-integrations/connectors/source-pipedrive/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/mal_pipedrive-pr-29293/1695247435/d97b030851f257554e82599134b10efebec8b571/source-pipedrive/2.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:d97b030851f257554e82599134b10efebec8b571)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-pipedrive test
```

2023-09-20 22:10 UTC, marcosmarxm requested changes

2023-09-20 22:10 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-pipedrive/source_pipedrive/manifest.yaml
>      name: "products_fields"
You need to change here too.
![Uploading image.png…]()

2023-09-20 22:23 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/e405312fe7a597ee21cbe2da1af513543880300e/airbyte-integrations/connectors/source-pipedrive/icon.svg" width="40" height="40"> source-pipedrive test report (commit [`e405312fe7`](https://github.com/airbytehq/airbyte/pull/30553/commits/e405312fe7a597ee21cbe2da1af513543880300e)) - ✅

⏲️  Total pipeline duration: 02mn45s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Connector package install                                               | ✅        |
| Build source-pipedrive docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                        | ✅        |
| Code format checks                                                      | ✅        |
| Validate airbyte-integrations/connectors/source-pipedrive/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/mal_pipedrive-pr-29293/1695248377/e405312fe7a597ee21cbe2da1af513543880300e/source-pipedrive/2.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e405312fe7a597ee21cbe2da1af513543880300e)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-pipedrive test
```

2023-09-21 12:27 UTC, marcosmarxm reviewed
Mal only need to check this [thread](https://airbytehq-team.slack.com/archives/C02U9R3AF37/p1695299055330149) about the field `id` inside the  `product_fields` schema. After solved that LGTM everything is workign great :)

2023-09-21 15:34 UTC, marcosmarxm approved these changes
LGTM

2023-09-21 17:35 UTC, merged