[DO NOT MERGE] Upload all docs script
airbytehq/airbyte pull request #30603
Opened 2023-09-20 01:56 UTC by lmossman

## What
Draft PR to add a command to upload the docs for every connector's current version to GCS.

## How
Add a command to metadata_service's commands.py and call a new function in gcs_upload which performs the uploading using the existing `_doc_upload()` method.

For now, I've commented out the part that uploads _every_ doc and just added code to upload the docs for github only, to avoid accidentally running this on all connectors unintentionally.

But when I actually do run it for real on the prod bucket, I plan to uncomment that last section so that it uploads the docs for all connectors.

Example usage:
```
$ poetry run metadata_service upload-all-docs /Users/lakemossman/code/airbyte/airbyte-integrations/connectors /Users/lakemossman/code/airbyte/docs/integrations dev-airbyte-cloud-connector-metadata-service
connectors_dir:  /Users/lakemossman/code/airbyte/airbyte-integrations/connectors
docs_dir:  /Users/lakemossman/code/airbyte/docs/integrations
bucket_name:  dev-airbyte-cloud-connector-metadata-service
excluded_connectors:  ['source-mongodb', 'source-stock-ticker-api-tutorial', 'destination-kvdb', 'source-db2-strict-encrypt', 'source-jdbc', 'source-python-http-tutorial', 'source-relational-db']
Found docs for 371 connectors
Local /Users/lakemossman/code/airbyte/docs/integrations/sources/github.md md5_hash: oa7KrOF/36I59yBy6198ww==
Remote metadata/airbyte/source-github/1.0.4/doc.md md5_hash: None
Uploading /Users/lakemossman/code/airbyte/docs/integrations/sources/github.md to metadata/airbyte/source-github/1.0.4/doc.md...
Local /Users/lakemossman/code/airbyte/docs/integrations/sources/github.inapp.md md5_hash: kTrdY+L61WbG0BLGqBvBvA==
Remote metadata/airbyte/source-github/1.0.4/doc.inapp.md md5_hash: None
Uploading /Users/lakemossman/code/airbyte/docs/integrations/sources/github.inapp.md to metadata/airbyte/source-github/1.0.4/doc.inapp.md...
Local /Users/lakemossman/code/airbyte/docs/integrations/sources/github.md md5_hash: oa7KrOF/36I59yBy6198ww==
Remote metadata/airbyte/source-github/latest/doc.md md5_hash: None
Uploading /Users/lakemossman/code/airbyte/docs/integrations/sources/github.md to metadata/airbyte/source-github/latest/doc.md...
Local /Users/lakemossman/code/airbyte/docs/integrations/sources/github.inapp.md md5_hash: kTrdY+L61WbG0BLGqBvBvA==
Remote metadata/airbyte/source-github/latest/doc.inapp.md md5_hash: None
Uploading /Users/lakemossman/code/airbyte/docs/integrations/sources/github.inapp.md to metadata/airbyte/source-github/latest/doc.inapp.md...
```

**Note**: I don't think we should actually merge this PR in, since this shouldn't be needed more than once; instead I think we should keep it as a draft and run the command from this branch, and then close the branch. We can always find this PR again in github if we need the script again for any reason.

2023-09-20 01:58 UTC, lmossman commented
@bnchrch could you take a look at the `upload_all_docs` command/script that I've added in this draft PR, and let me know if you have any thoughts? This is what I plan to use to upload all docs for all of the current connector versions after we merge https://github.com/airbytehq/airbyte/pull/30410

2023-09-26 21:33 UTC, bnchrch requested changes
A few comments! But the only thing holding this part is making sure we are very explicit and thorough with our connector directory exclusions

2023-09-26 21:33 UTC, bnchrch commented on airbyte-ci/connectors/metadata_service/lib/metadata_service/commands.py
> +def upload_all_docs(connectors_dir: pathlib.Path, docs_dir: pathlib.Path, bucket_name: str):
❗Lets be clear this is a dev command by prefixing the command with experimental: `experimental_upload_all_docs`

2023-09-26 21:33 UTC, bnchrch commented on airbyte-ci/connectors/metadata_service/lib/metadata_service/gcs_upload.py
> +def upload_all_docs_to_gcs(connectors_dir: Path, docs_dir: Path, bucket_name: str):
📚 Lets write a docstring explaining what it does, why we added it, and if theres any criteria to remove this

2023-09-26 21:33 UTC, bnchrch commented on airbyte-ci/connectors/metadata_service/lib/metadata_service/gcs_upload.py
> +        if connector_dir.is_dir():
💅 would be great to have a single exclusion criteria
💅 would be great not to nest so deep
❗ also I think were missing certain criteria

```py
def is_valid_connector_dir(connector_dir):
  # Check if directory
  # Check starts with source- or destination-
  # Check has metadata.yaml file
  # Do not allow `-scaffold`
  # Do not allow `-secure` or `-strict-encrypt`
  # What about our third party folder?

for connector_dir in connectors_dir.iterdir() if is_valid_connector_dir(connector_dir):
   #...
```

2023-09-26 21:33 UTC, bnchrch commented on airbyte-ci/connectors/metadata_service/lib/metadata_service/gcs_upload.py
> +                    metadata = read_metadata_yaml(metadata_file_path)
💡(Very Optional) if we import ci_connector_ops ([example import](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/pyproject.toml#L23)) we can use `Connector` and [get_all_connectors_in_repo](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/connector_ops/connector_ops/utils.py#L475) to do alot of this. Particularly now that the related airbyte-ci PR adds helper properties for getting the doc and inapp doc paths.

2023-09-26 21:33 UTC, bnchrch commented on airbyte-ci/connectors/metadata_service/lib/metadata_service/gcs_upload.py
> +                    doc_path, inapp_doc_path = get_doc_paths(metadata, connector_name)  # 'source' becomes 'sources', 'destination' becomes 'destinations'
❓Why did we go with this method instead of just calling `commands.upload(metadata_file_path, doc_path, bucket_name` directly?

2023-11-03 19:32 UTC, closed without merging