Update candidates.json
airbytehq/airbyte pull request #30648
Opened 2023-09-20 22:20 UTC by robertoarnetoli

## What
The change solves the issue [**Source Greenhouse: Candidates stream does not contains custom fields #29892**](https://github.com/airbytehq/airbyte/issues/29892)

## How
The `candidates` stream schema did not include the `custom_fields` and the `keyed_custom_fields` properties, which have now been added.

## 🚨 User Impact 🚨
Users can now extract `custom_fields` and `keyed_custom_fields`  from the Greenhouse candidates stream.

2023-09-20 22:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=30648) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=30648) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=30648) it.</sub>

2023-09-21 11:53 UTC, marcosmarxm requested changes
Some comments.

2023-09-21 11:53 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-greenhouse/source_greenhouse/schemas/candidates.json
> +      "type": "object"
```suggestion
      "additionalProperties": true,
      "type": ["null", "object"]
```

2023-09-21 11:53 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-greenhouse/source_greenhouse/schemas/candidates.json
> +      "type": "object"
For both fields.

2023-09-21 13:06 UTC, robertoarnetoli commented on airbyte-integrations/connectors/source-greenhouse/source_greenhouse/schemas/candidates.json
> +      "type": "object"
@marcosmarxm done. thanks

2023-09-22 08:56 UTC, robertoarnetoli commented
> Some comments.

Hi @marcosmarxm I have made the suggested changes. Please review.

2023-09-27 22:00 UTC, sajarin approved these changes
Thanks for the contribution! Appreciate you adding these additional fields to this stream.

2023-09-27 22:02 UTC, merged