:snake: Source Google Ads: fix custom queries
airbytehq/airbyte pull request #30705
Opened 2023-09-22 22:53 UTC by tolik0

## What
Fix creating schemas for custom queries.
[#30253](https://github.com/airbytehq/airbyte/issues/30253)

## How
- Fix array types from custom queries
- Delete protobuf_message from Message type and changed it to string

2023-09-22 23:15 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/f8bea7f05a6b9d6d8475b181412ecd198080222b/airbyte-integrations/connectors/source-google-ads/icon.svg" width="40" height="40"> source-google-ads test report (commit [`f8bea7f05a`](https://github.com/airbytehq/airbyte/pull/30705/commits/f8bea7f05a6b9d6d8475b181412ecd198080222b)) - ✅

⏲️  Total pipeline duration: 07mn19s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Connector package install                                                | ✅        |
| Build source-google-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |
| Code format checks                                                       | ✅        |
| Validate airbyte-integrations/connectors/source-google-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/tolik0_source-google-ads_custom-query-fix/1695424044/f8bea7f05a6b9d6d8475b181412ecd198080222b/source-google-ads/0.11.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:f8bea7f05a6b9d6d8475b181412ecd198080222b)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-ads test
```

2023-09-25 18:40 UTC, davydov-d requested changes
Can you please add more context here? Why are you removing `protobuf_message` from the code? Why is this a breaking change? If it is, we should bump major version and follow a breaking change release process

2023-09-25 20:53 UTC, tolik0 commented
> Can you please add more context here? Why are you removing `protobuf_message` from the code? Why is this a breaking change? If it is, we should bump major version and follow a breaking change release process

@davydov-d I updated description and added migration guide.

2023-09-25 20:55 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/e4eeaa2c6cba19deee5a676fd1cff20cd4b9d5b0/airbyte-integrations/connectors/source-google-ads/icon.svg" width="40" height="40"> source-google-ads test report (commit [`e4eeaa2c6c`](https://github.com/airbytehq/airbyte/pull/30705/commits/e4eeaa2c6cba19deee5a676fd1cff20cd4b9d5b0)) - ❌

⏲️  Total pipeline duration: 01mn22s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Connector package install                                                | ✅        |
| Build source-google-ads docker image for platform linux/x86_64           | ❌        |
| Code format checks                                                       | ✅        |
| Validate airbyte-integrations/connectors/source-google-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/tolik0_source-google-ads_custom-query-fix/1695675216/e4eeaa2c6cba19deee5a676fd1cff20cd4b9d5b0/source-google-ads/0.11.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e4eeaa2c6cba19deee5a676fd1cff20cd4b9d5b0)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-ads test
```

2023-09-25 21:14 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/67f87f15aa7abac5379b528874c2fd4bfc8b2281/airbyte-integrations/connectors/source-google-ads/icon.svg" width="40" height="40"> source-google-ads test report (commit [`67f87f15aa`](https://github.com/airbytehq/airbyte/pull/30705/commits/67f87f15aa7abac5379b528874c2fd4bfc8b2281)) - ❌

⏲️  Total pipeline duration: 06mn36s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Connector package install                                                | ✅        |
| Build source-google-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ❌        |
| Code format checks                                                       | ✅        |
| Validate airbyte-integrations/connectors/source-google-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/tolik0_source-google-ads_custom-query-fix/1695676055/67f87f15aa7abac5379b528874c2fd4bfc8b2281/source-google-ads/1.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:67f87f15aa7abac5379b528874c2fd4bfc8b2281)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-ads test
```

2023-09-26 13:11 UTC, davydov-d approved these changes

2023-09-28 08:49 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/d5e7f6b60efc7d31acf2556bff730735509073d1/airbyte-integrations/connectors/source-google-ads/icon.svg" width="40" height="40"> source-google-ads test report (commit [`d5e7f6b60e`](https://github.com/airbytehq/airbyte/pull/30705/commits/d5e7f6b60efc7d31acf2556bff730735509073d1)) - ✅

⏲️  Total pipeline duration: 08mn01s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Connector package install                                      | ✅        |
| Build source-google-ads docker image for platform linux/x86_64 | ✅        |
| Unit tests                                                     | ✅        |
| Acceptance tests                                               | ✅        |
| Code format checks                                             | ✅        |
| Validate metadata for source-google-ads                        | ✅        |
| Connector version semver check                                 | ✅        |
| Connector version increment check                              | ✅        |
| QA checks                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/tolik0_source-google-ads_custom-query-fix/1695890472/d5e7f6b60efc7d31acf2556bff730735509073d1/source-google-ads/1.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:d5e7f6b60efc7d31acf2556bff730735509073d1)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-ads test
```

2023-09-28 12:25 UTC, clnoll approved these changes
LGTM once the breaking changes doc is approved!

2023-09-29 21:01 UTC, pedroslopez commented
/approve-and-merge reason="release + skip stuck gradle check"

2023-09-29 21:01 UTC, octavia-approvington commented
Enough! Let's do this <br/> ![goooooo!](https://media4.giphy.com/media/3oz8xHY5TPG9CAW0xi/giphy.gif?cid=ecf05e47z0yx82769b47apuo7ktdy80smghysn94klxp2k9v&rid=giphy.gif&ct=g)

2023-09-29 21:01 UTC, octavia-approvington approved these changes

2023-09-29 21:01 UTC, merged