🎉 New Source: Audience Project
airbytehq/airbyte pull request #30840
Opened 2023-09-28 17:01 UTC by Zawar92

## What
*Building a new connector [Audience Project](https://www.audienceproject.com/resources/api-documentation/). As related to the current https://github.com/airbytehq/airbyte/issues/26424*
*Relates to closed [MR](https://github.com/airbytehq/airbyte/pull/27394) converted it to low-code*

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:generateScaffolds` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

2023-10-10 16:59 UTC, marcosmarxm commented
Thanks for the contribution @Zawar92 and sorry the missing update here.
Right now the team is dedicated to October Hackathon and it will be only possible to review after the event finish.
Hope you understand and return to you as soon as possible.

2023-11-20 13:14 UTC, marcosmarxm requested changes
Hello @Zawar92 thanks for the contribution and sorry the delay to review your contribution. I made some comments please take a look. It is missing the connector documentation page please add it too. Can you show the connector integration tests output?

2023-11-20 13:14 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-audience-project/source_audience_project/schemas/TODO.md
> +## Static schemas
Remove this file.

2023-11-20 13:14 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-audience-project/source_audience_project/schemas/campaigns.json
> +      "type":"string"
Make sure all schemas follow the reference https://docs.airbyte.com/connector-development/schema-reference

2023-11-20 13:14 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-audience-project/setup.py
> +    "connector-acceptance-test",
Remove this because is not used anymore.

2023-11-20 13:14 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-audience-project/setup.py
> +    "airbyte-cdk~=0.1",
Remove version constrain.

2023-11-20 13:14 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-audience-project/source_audience_project/streams.py
> +import pendulum
Rename this file to components.

2023-11-23 12:51 UTC, Zawar92 commented
Hi @marcosmarxm,
All changes are met but now there is an error in the integration test, Can you give me some suggestions?
<img width="1371" alt="audienceproject_integration_test" src="https://github.com/airbytehq/airbyte/assets/26454033/63094a85-9769-4eb2-aaee-d0e2513e27ad">

2024-02-06 08:47 UTC, Zawar92 commented
Any update on this?

2024-03-08 17:47 UTC, marcosmarxm commented
@Zawar92, unfortunately, the Airbyte team couldn't set up a sandbox account for testing. Therefore, we regret to inform you that we have to decline the contribution since running integration tests and providing maintenance for the connector won't be possible in the future.

2024-03-08 17:47 UTC, closed without merging