✨ Source Apple Ads Search : add timezone from spec to request parameters
airbytehq/airbyte pull request #30959
Opened 2023-09-30 16:55 UTC by Abuton

I'm adding timezone to spec to allow for proper data aggregation as stated [here](https://developer.apple.com/documentation/apple_search_ads/reportingrequest)
![image](https://github.com/airbytehq/airbyte/assets/40719064/9b4cedc1-a3da-44fa-8e6c-8130b5ade769)

## How
I have added `timezone` as one of the optional configuration a user needs to fill when setting up a connection with apple ads search source connector. I have also preserved the default that was included when this source connector was initially developed `UTC`.

## Recommended reading order
1. `airbyte/airbyte_integrations/connectors/source-apple-search-ads/source_apple_search_ads/spec.yaml`
2. `airbyte/airbyte_integrations/connectors/source-apple-search-ads/source_apple_search_ads/manifest.yaml`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

There are no breaking changes in this Pull Request.

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

2023-10-10 17:33 UTC, marcosmarxm requested changes
@Abuton do you have a link to Apple Ads documentation showing what timezones are supported?

2023-10-10 17:52 UTC, Abuton commented
> @Abuton do you have a link to Apple Ads documentation showing what timezones are supported?

Yes, here it is: https://developer.apple.com/documentation/apple_search_ads/reportingrequest

2023-10-11 18:37 UTC, marcosmarxm requested changes

2023-10-11 18:37 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-apple-search-ads/source_apple_search_ads/manifest.yaml
> +          timeZone: "{{ config.time_zone }}"
```suggestion
          timeZone: "{{ config.get('time_zone', "UTC") }}"
```
Using this method it won't introduce a breaking change to existing connector.

2023-10-11 18:37 UTC, marcosmarxm commented on docs/integrations/sources/apple-search-ads.md
> +8. You can also set the timezone to determine how the report data is aggregated
Add a note saying default is UTC.

2023-10-11 18:46 UTC, Abuton commented on docs/integrations/sources/apple-search-ads.md
> +8. You can also set the timezone to determine how the report data is aggregated
Done

2024-06-12 14:31 UTC, closed without merging