:sparkles: Source Github: marked start date as optional field
airbytehq/airbyte pull request #30971
Opened 2023-10-02 12:16 UTC by darynaishchenko

## What
Start date was a required, which is not suitable for certification. 

## How
Start date is optional, if start date is not set, date 2 years ago from today will be used.

2023-10-02 12:22 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/9508ca1a64583bb8a38863a7dd9b7871854c3d4e/airbyte-integrations/connectors/source-github/icon.svg" width="40" height="40"> source-github test report (commit [`9508ca1a64`](https://github.com/airbytehq/airbyte/pull/30971/commits/9508ca1a64583bb8a38863a7dd9b7871854c3d4e)) - ❌

⏲️  Total pipeline duration: 01mn00s 

| Step                                                       | Result   |
|:-----------------------------------------------------------|:---------|
| Connector package install                                  | ✅        |
| Build source-github docker image for platform linux/x86_64 | ✅        |
| Unit tests                                                 | ❌        |
| Code format checks                                         | ✅        |
| Validate metadata for source-github                        | ✅        |
| Connector version semver check                             | ✅        |
| Connector version increment check                          | ✅        |
| QA checks                                                  | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-github_spec-improvment/1696249278/9508ca1a64583bb8a38863a7dd9b7871854c3d4e/source-github/1.4.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:9508ca1a64583bb8a38863a7dd9b7871854c3d4e)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-github test
```

2023-10-02 12:45 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/ddd3ccd10383275727f21a4f367e1e0d35f35655/airbyte-integrations/connectors/source-github/icon.svg" width="40" height="40"> source-github test report (commit [`ddd3ccd103`](https://github.com/airbytehq/airbyte/pull/30971/commits/ddd3ccd10383275727f21a4f367e1e0d35f35655)) - ❌

⏲️  Total pipeline duration: 01mn18s 

| Step                                                       | Result   |
|:-----------------------------------------------------------|:---------|
| Connector package install                                  | ✅        |
| Build source-github docker image for platform linux/x86_64 | ✅        |
| Unit tests                                                 | ❌        |
| Code format checks                                         | ✅        |
| Validate metadata for source-github                        | ✅        |
| Connector version semver check                             | ✅        |
| Connector version increment check                          | ✅        |
| QA checks                                                  | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-github_spec-improvment/1696250609/ddd3ccd10383275727f21a4f367e1e0d35f35655/source-github/1.4.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:ddd3ccd10383275727f21a4f367e1e0d35f35655)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-github test
```

2023-10-02 15:42 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/9e2b1db192ea3a0869fb8ca35f828347d48551b3/airbyte-integrations/connectors/source-github/icon.svg" width="40" height="40"> source-github test report (commit [`9e2b1db192`](https://github.com/airbytehq/airbyte/pull/30971/commits/9e2b1db192ea3a0869fb8ca35f828347d48551b3)) - ✅

⏲️  Total pipeline duration: 07mn02s 

| Step                                                       | Result   |
|:-----------------------------------------------------------|:---------|
| Connector package install                                  | ✅        |
| Build source-github docker image for platform linux/x86_64 | ✅        |
| Unit tests                                                 | ✅        |
| Acceptance tests                                           | ✅        |
| Code format checks                                         | ✅        |
| Validate metadata for source-github                        | ✅        |
| Connector version semver check                             | ✅        |
| Connector version increment check                          | ✅        |
| QA checks                                                  | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-github_spec-improvment/1696260866/9e2b1db192ea3a0869fb8ca35f828347d48551b3/source-github/1.4.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:9e2b1db192ea3a0869fb8ca35f828347d48551b3)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-github test
```

2023-10-02 16:17 UTC, darynaishchenko commented on airbyte-integrations/connectors/source-github/unit_tests/test_source.py
> +os.environ["REQUEST_CACHE_PATH"] = "REQUEST_CACHE_PATH"
test report above failed because this env variable was not set. it's related to this changes https://github.com/airbytehq/airbyte/pull/30925

2023-10-02 17:45 UTC, artem1205 requested changes
According to cert requirements, we should sync all available data if start_date is not provided and is not required.
it seems like we can ignore initial start date comparison (if we have no start_date) in semi-incremental streams: https://github.com/airbytehq/airbyte/blob/9e2b1db192ea3a0869fb8ca35f828347d48551b3/airbyte-integrations/connectors/source-github/source_github/streams.py#L296C28-L296C28

2023-10-03 13:30 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/f6bc0a5dc5b72aa76568f547730f847f419dbc7f/airbyte-integrations/connectors/source-github/icon.svg" width="40" height="40"> source-github test report (commit [`f6bc0a5dc5`](https://github.com/airbytehq/airbyte/pull/30971/commits/f6bc0a5dc5b72aa76568f547730f847f419dbc7f)) - ✅

⏲️  Total pipeline duration: 05mn56s 

| Step                                                       | Result   |
|:-----------------------------------------------------------|:---------|
| Connector package install                                  | ✅        |
| Build source-github docker image for platform linux/x86_64 | ✅        |
| Unit tests                                                 | ✅        |
| Acceptance tests                                           | ✅        |
| Code format checks                                         | ✅        |
| Validate metadata for source-github                        | ✅        |
| Connector version semver check                             | ✅        |
| Connector version increment check                          | ✅        |
| QA checks                                                  | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-github_spec-improvment/1696339452/f6bc0a5dc5b72aa76568f547730f847f419dbc7f/source-github/1.4.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:f6bc0a5dc5b72aa76568f547730f847f419dbc7f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-github test
```

2023-10-03 14:17 UTC, artem1205 approved these changes

2023-10-03 14:38 UTC, roman-yermilov-gl approved these changes

2023-10-03 15:05 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/ae8898b50270f4b3486ad4176b304a5d4bdb457d/airbyte-integrations/connectors/source-github/icon.svg" width="40" height="40"> source-github test report (commit [`ae8898b502`](https://github.com/airbytehq/airbyte/pull/30971/commits/ae8898b50270f4b3486ad4176b304a5d4bdb457d)) - ✅

⏲️  Total pipeline duration: 07mn35s 

| Step                                                       | Result   |
|:-----------------------------------------------------------|:---------|
| Connector package install                                  | ✅        |
| Build source-github docker image for platform linux/x86_64 | ✅        |
| Unit tests                                                 | ✅        |
| Acceptance tests                                           | ✅        |
| Code format checks                                         | ✅        |
| Validate metadata for source-github                        | ✅        |
| Connector version semver check                             | ✅        |
| Connector version increment check                          | ✅        |
| QA checks                                                  | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-github_spec-improvment/1696345048/ae8898b50270f4b3486ad4176b304a5d4bdb457d/source-github/1.4.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:ae8898b50270f4b3486ad4176b304a5d4bdb457d)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-github test
```

2023-10-03 15:14 UTC, merged