✨ Added new stream in Source Square
airbytehq/airbyte pull request #31045
Opened 2023-10-04 11:32 UTC by avirajsingh7

Closes #16856 

Added [Bank Account](https://developer.squareup.com/reference/square/objects/BankAccount) stream in Source Square

2023-10-04 20:44 UTC, marcosmarxm commented
Thanks for the contribution 🚀 . I added it to the team backlog and we're planning to start next week the review process.

2023-10-12 17:02 UTC, archangelic requested changes
Thank you so much for your contribution. I have submitted some changes below. Additionally, can you update `Dockerfile` and `metadata.yaml` to version `1.2.0`?

2023-10-12 17:02 UTC, archangelic commented on airbyte-integrations/connectors/source-square/source_square/manifest.yaml
> +      path: "/bank-accounts"
```suggestion
  bank_accounts_stream:
    $ref: "#/definitions/base_stream"
    $parameters:
      name: "bank_accounts"
      primary_key: "id"
      path: "/bank-accounts"
```

2023-10-12 17:02 UTC, archangelic commented on airbyte-integrations/connectors/source-square/source_square/manifest.yaml
> +  - "#/definitions/banks_accounts_stream"
```suggestion
  - "#/definitions/bank_accounts_stream"
```

2023-10-16 18:05 UTC, archangelic commented
@avirajsingh7 Are you able to make the suggested changes? I can't seem to push changes to your branch myself.

2023-10-16 19:07 UTC, avirajsingh7 commented
@archangelic done changes

2023-10-16 23:17 UTC, archangelic approved these changes

2023-10-17 00:15 UTC, closed without merging

2023-10-17 00:15 UTC, archangelic commented
Congrats! I merged it in another PR to fix some things!