✨Source Wrike: Migrate Python CDK to Low-code CDK
airbytehq/airbyte pull request #31058
Opened 2023-10-04 15:41 UTC by btkcodedev

## What
*Migrating Source Wrike to Low-Code CDK*
Closes #30885

## How
*Developed using (Configuration Based Source) low-code CDK*

## Recommended reading order
1. `spec.yaml`
2. `manifest.yaml`
3. `schemas/*`

## Tests

<details open><summary><strong>Integration & Acceptance</strong></summary>
Full Test Results

</details>

## 🚨 User Impact 🚨
- No breaking changes, migration to low-code
<details><summary><strong>Migrate Connector: Source Wrike</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [x] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

</details>

2023-10-04 17:55 UTC, btkcodedev commented
Test results: Full pass state
![image](https://github.com/airbytehq/airbyte/assets/47392334/8d9bb46d-c392-49f3-9a43-1c6f44e61446)

2023-10-04 17:55 UTC, btkcodedev commented
Ping via slack for credentials: Slack ID: btkcodedev

2023-10-04 20:49 UTC, marcosmarxm commented
Thanks for the contribution 🚀 . I added it to the team backlog and we're planning to start next week the review process.

2023-10-23 13:59 UTC, marcosmarxm requested changes
I made a quick review asking to update a few files this will help us during the code review. Sorry the long delay to get into your contribution. Probably this week or next one the team will start the process. Are you able to run the tests in your local setup? It can speed up a lot the process if you share the integration tests results

2023-10-23 13:59 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-wrike/build.gradle
> +}
Remove this isn't used anymore.

2023-10-23 13:59 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-wrike/integration_tests/abnormal_state.json
> +}
Fix this file.

2023-10-23 13:59 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-wrike/requirements.txt
> +-e ../../bases/connector-acceptance-test
Remove this not used anymore.

2023-10-23 13:59 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-wrike/setup.py
> +    "connector-acceptance-test",
Remove this not used anymore.

2023-10-24 13:16 UTC, marcosmarxm approved these changes
Thanks @btkcodedev

2023-10-24 13:31 UTC, merged