✨ Source Freshcaller : Migrate Python CDK to Low-code CDK
airbytehq/airbyte pull request #31102
Opened 2023-10-05 15:04 UTC by aazam-gh

## What
Fix #30893
Migrate Source Zendesk Sell from Python CDK to Low-code CDK

## How
Using Low Code/No Code Connector Development Kit

## Recommended reading order
1. `manifest.yaml`
2. `schemas`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/resources/pull-requests-handbook)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:generateScaffolds` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

2023-10-18 21:14 UTC, archangelic commented
@aazam-gh it looks like this branch also has changes for source-zendesk-sell. Are you able to clean this PR so that the changes are limited to source-freshcaller?

2023-10-18 21:15 UTC, aazam-gh commented
@archangelic sure I'll take a look at it and remove the Zendesk changes

2023-10-23 14:08 UTC, marcosmarxm requested changes
Missing update doc changelog. Remove changes to Zendesk Sell.

2023-10-23 14:08 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-freshcaller/build.gradle
> +}
Remove this file.

2023-10-23 14:08 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-freshcaller/setup.py
> +    "connector-acceptance-test",
Remove this import, not used anymore.

2023-11-07 21:57 UTC, marcosmarxm approved these changes

2023-11-07 22:32 UTC, merged