:bug:Source Posthog: Fix Connector Date Formatting Error
airbytehq/airbyte pull request #31265
Opened 2023-10-11 01:01 UTC by topefolorunso

## What
Fix events stream cursor format resolves #30166

## How

## Recommended reading order
1. `manifest.yaml`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

2023-10-26 10:30 UTC, lazebnyi requested changes, later dismissed
need bump version and change log 

and follow with braking change flow or update to backward compatibility

2023-10-26 10:30 UTC, lazebnyi commented on airbyte-integrations/connectors/source-posthog/source_posthog/manifest.yaml
> +          datetime_format: "%Y-%m-%dT%H:%M:%S+00:00"
look like braking change

2023-10-28 21:01 UTC, topefolorunso commented on airbyte-integrations/connectors/source-posthog/source_posthog/manifest.yaml
> +          datetime_format: "%Y-%m-%dT%H:%M:%S+00:00"
No @lazebnyi , not a breaking change

2023-11-03 20:19 UTC, marcosmarxm approved these changes
I sent an update to correct the fix.

2023-11-03 20:31 UTC, merged