:rotating_light: :rotating_light: Source Bing Ads: remove PKs from geographic performance reports
airbytehq/airbyte pull request #31277
Opened 2023-10-11 12:36 UTC by davydov-d

## What
https://github.com/airbytehq/oncall/issues/3068

## How
Remove PKs from the geographic performance report streams as they are the cause of losing the data in the incremental append+dedup mode.

## 🚨 User Impact 🚨
This is a breaking change as four streams will lose their primary keys. Users will have to reset data + refresh their stream schemas. Also, users will have more data in their destinations.

2023-10-11 13:15 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/ca7ff11d6269eb7853e5b44f6b18ba1839793813/airbyte-integrations/connectors/source-bing-ads/icon.svg" width="40" height="40"> source-bing-ads test report (commit [`ca7ff11d62`](https://github.com/airbytehq/airbyte/pull/31277/commits/ca7ff11d6269eb7853e5b44f6b18ba1839793813)) - ✅

⏲️  Total pipeline duration: 23mn35s 

| Step                                                            | Result   |
|:----------------------------------------------------------------|:---------|
| Build source-bing-ads docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                      | ✅        |
| Acceptance tests                                                | ✅        |
| Code format checks                                              | ✅        |
| Validate metadata for source-bing-ads                           | ✅        |
| Connector version semver check                                  | ✅        |
| Connector version increment check                               | ✅        |
| QA checks                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_3068-source-bing-ads-remove-pk/1697028686/ca7ff11d6269eb7853e5b44f6b18ba1839793813/source-bing-ads/1.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:ca7ff11d6269eb7853e5b44f6b18ba1839793813)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-bing-ads test
```

2023-10-11 13:18 UTC, roman-yermilov-gl approved these changes

2023-10-11 13:38 UTC, bazarnov approved these changes

2023-10-11 18:31 UTC, bnchrch approved these changes
LGTM! Just tagging @katmarkham as a reviewer for the breaking changes copy. Once she gives this the green light I think were good to merge

2023-10-11 19:59 UTC, katmarkham requested changes

2023-10-11 20:05 UTC, davydov-d commented on airbyte-integrations/connectors/source-bing-ads/metadata.yaml
> +        message: "Version 1.0.0 removes the primary keys from the geographic performance report streams. This will prevent the connector from loosing the data in the incremental append+dedup sync mod
Thanks!

2023-10-11 20:31 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/3b016eee33359e91b1fd2cb6f263686dc01a7576/airbyte-integrations/connectors/source-bing-ads/icon.svg" width="40" height="40"> source-bing-ads test report (commit [`3b016eee33`](https://github.com/airbytehq/airbyte/pull/31277/commits/3b016eee33359e91b1fd2cb6f263686dc01a7576)) - ✅

⏲️  Total pipeline duration: 24mn08s 

| Step                                                            | Result   |
|:----------------------------------------------------------------|:---------|
| Build source-bing-ads docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                      | ✅        |
| Acceptance tests                                                | ✅        |
| Code format checks                                              | ✅        |
| Validate metadata for source-bing-ads                           | ✅        |
| Connector version semver check                                  | ✅        |
| Connector version increment check                               | ✅        |
| QA checks                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_3068-source-bing-ads-remove-pk/1697054835/3b016eee33359e91b1fd2cb6f263686dc01a7576/source-bing-ads/1.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:3b016eee33359e91b1fd2cb6f263686dc01a7576)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-bing-ads test
```

2023-10-12 13:36 UTC, katmarkham approved these changes

2023-10-12 13:38 UTC, merged