Source S3: Add reading files inside zip archive
airbytehq/airbyte pull request #31340
Opened 2023-10-12 12:18 UTC by tolik0

## What
Add new compression type - zip. Connector now can read files from inside of zip.
Closes:
[#17021
](https://github.com/airbytehq/airbyte/issues/17021)

## How
*Describe the solution*

2023-10-12 12:26 UTC, davydov-d requested changes
Please add tests, preferably CAT with the new archive type

2023-10-13 12:22 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/e56c48c8b51f8b0e4de2e929f22fe251706e94da/airbyte-integrations/connectors/source-s3/icon.svg" width="40" height="40"> source-s3 test report (commit [`e56c48c8b5`](https://github.com/airbytehq/airbyte/pull/31340/commits/e56c48c8b51f8b0e4de2e929f22fe251706e94da)) - ✅

⏲️  Total pipeline duration: 14mn55s 

| Step                                                      | Result   |
|:----------------------------------------------------------|:---------|
| Build source-s3 docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                | ✅        |
| Acceptance tests                                          | ✅        |
| Code format checks                                        | ✅        |
| Validate metadata for source-s3                           | ✅        |
| Connector version semver check                            | ✅        |
| Connector version increment check                         | ✅        |
| QA checks                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/tolik0_source-s3_add-reading-inside-zip/1697198826/e56c48c8b51f8b0e4de2e929f22fe251706e94da/source-s3/4.1.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e56c48c8b51f8b0e4de2e929f22fe251706e94da)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

2023-10-13 12:50 UTC, davydov-d approved these changes
:clap:

2023-10-17 10:17 UTC, bazarnov approved these changes

2023-10-17 10:17 UTC, bazarnov commented on airbyte-integrations/connectors/source-s3/source_s3/v4/zip_reader.py
> +        return file_start + 30 + name_len + extra_len
Could you please give more info about these hardcoded ints: `26` and `30` ?

2023-10-17 23:51 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/721796980873373d92356e1101b2255a26bc54db/airbyte-integrations/connectors/source-s3/icon.svg" width="40" height="40"> source-s3 test report (commit [`7217969808`](https://github.com/airbytehq/airbyte/pull/31340/commits/721796980873373d92356e1101b2255a26bc54db)) - ❌

⏲️  Total pipeline duration: 20mn20s 

| Step                                                      | Result   |
|:----------------------------------------------------------|:---------|
| Build source-s3 docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                | ✅       |
| Acceptance tests                                          | ❌       |
| Code format checks                                        | ✅       |
| Validate metadata for source-s3                           | ✅       |
| Connector version semver check                            | ✅       |
| Connector version increment check                         | ✅       |
| QA checks                                                 | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/tolik0_source-s3_add-reading-inside-zip/1697585444/721796980873373d92356e1101b2255a26bc54db/source-s3/4.1.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:721796980873373d92356e1101b2255a26bc54db)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

2023-10-18 08:31 UTC, airbyte-oss-build-runner commented
## <img src="https://raw.githubusercontent.com/airbytehq/airbyte/5f74715bbe569ce9886c9d967c0739e65a91fcd8/airbyte-integrations/connectors/source-s3/icon.svg" width="40" height="40"> source-s3 test report (commit [`5f74715bbe`](https://github.com/airbytehq/airbyte/pull/31340/commits/5f74715bbe569ce9886c9d967c0739e65a91fcd8)) - ✅

⏲️  Total pipeline duration: 21mn00s 

| Step                                                      | Result   |
|:----------------------------------------------------------|:---------|
| Build source-s3 docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                | ✅       |
| Acceptance tests                                          | ✅       |
| Code format checks                                        | ✅       |
| Validate metadata for source-s3                           | ✅       |
| Connector version semver check                            | ✅       |
| Connector version increment check                         | ✅       |
| QA checks                                                 | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/tolik0_source-s3_add-reading-inside-zip/1697616590/5f74715bbe569ce9886c9d967c0739e65a91fcd8/source-s3/4.1.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:5f74715bbe569ce9886c9d967c0739e65a91fcd8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

2023-10-18 08:53 UTC, merged