Vitalii/2257 google search console implementation
airbytehq/airbyte pull request #3137
Opened 2021-04-29 19:00 UTC by vitaliizazmic

## What
Implementing new Google Search Console Source based on Singer Tap fork. Fork was made for using service account credentials instead authentication token. And making requests to API via Google Client Library instead directly calling.

## Pre-merge Checklist
- [ ] *Run integration tests*
- [ ] *Publish Docker images*

2021-04-29 19:15 UTC, vitaliizazmic commented
/test connector=source-google-search-console-singer

2021-04-29 19:41 UTC, vitaliizazmic commented
/test connector=source-google-search-console-singer

2021-04-29 20:20 UTC, sherifnada approved these changes
nice! some files should be cleaned up. anything that isn't used should be removed. Also standard tests aren't passing, you might need to sync with @eugene-kulak

2021-04-29 20:20 UTC, sherifnada commented on airbyte-integrations/connectors/source-google-search-console-singer/integration_tests/catalog.json
> +{
delete this file since it is unused

2021-04-29 20:20 UTC, sherifnada commented on airbyte-integrations/connectors/source-google-search-console-singer/integration_tests/sample_state.json
> +{
remove if unused

2021-04-29 20:20 UTC, sherifnada commented on airbyte-integrations/connectors/source-google-search-console-singer/integration_tests/invalid_config.json
> +{
remove if unused

2021-04-29 20:20 UTC, sherifnada commented on airbyte-integrations/connectors/source-google-search-console-singer/integration_tests/configured_catalog.json
> +{
update to the actual configured catalog or remove if unused

2021-04-29 21:36 UTC, keu commented on airbyte-integrations/connectors/source-google-search-console-singer/acceptance-test-config.yml
> +connector_image: airbyte/google-search-console
this is a bug in template, you should be `airbyte/google-search-console-singer`

2021-04-29 21:37 UTC, keu requested changes
acceptance tests

2021-04-30 03:34 UTC, sherifnada commented on airbyte-integrations/connectors/source-google-search-console-singer/setup.py
> +    "tap-google-search-console @ https://github.com/vitaliizazmic/tap-google-search-console/tarball/service_account_creds",
don't forget to change this to the Airbyte fork once it's merged

2021-05-06 07:44 UTC, vitaliizazmic commented
/test connector=source-google-search-console-singer

2021-05-06 13:07 UTC, vitaliizazmic commented
/test connector=source-google-search-console-singer

2021-05-06 13:54 UTC, vitaliizazmic commented
@sherifnada Source passes test successful. But there are several issues.

- This source based on base_singer.BaseSingerSource. BaseSingerSource check method always finish with exit code 0 even with wrong credentials. It cause error.  I temporally disabled this check, but we should fix BaseSingerSource. I created separate issue #3266 
- tap-google-search-console state has different from other sources structure. It causes error while checking incremental test. I disable it temporarily.

Example of state

`{
  "currently_syncing": "sitemaps",
  "bookmarks": {
    "performance_report_device": {
      "sc-domain:example.com": {
        "web": "2020-04-18T00:00:00.000000Z",
        "image": "2020-04-18T00:00:00.000000Z",
        "video": "2020-04-08T00:00:00.000000Z"
      },
      "https://example.com": {
        "web": "2020-04-18T00:00:00.000000Z",
        "image": "2020-04-18T00:00:00.000000Z",
        "video": "2020-04-08T00:00:00.000000Z"
      },
      "http://example.com": {
        "web": "2020-04-16T00:00:00.000000Z"
      }
    },
  }
}`

Another issue - quota exceeded error. Search Analytics resource, which is used for performance report streams, has [load quota](https://developers.google.com/webmaster-tools/search-console-api-original/v3/limits). When Short-term load quota is exceeded, it requires 15 minutes backoff. It increase syncing time. I disabled performance_report_date stream to decrease loading on Search Analytics resource. Analytics by date repeats in other performance streams.

2021-05-06 14:22 UTC, sherifnada commented
Thanks for the update @vitaliizazmic. Agreed with all the steps you took.

2021-05-06 17:10 UTC, vitaliizazmic commented
/test connector=source-google-search-console-singer

2021-05-07 13:41 UTC, vitaliizazmic commented
/test connector=source-google-search-console-singer

2021-05-07 18:52 UTC, keu approved these changes
lgtm

2021-05-10 06:59 UTC, merged