Source Mailgun: test connection fail after upgrading to 0.2.0
airbytehq/airbyte pull request #31405
Opened 2023-10-13 21:26 UTC by ariesgun

## What
Fixed test connection fail when the start date field is empty
Fixed #29985

## How
*Describe the solution*

## Recommended reading order
1. manifest.yaml

## 🚨 User Impact 🚨
None

## Pre-merge Actions

<summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

2023-10-16 12:37 UTC, marcosmarxm requested changes

2023-10-16 12:37 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-mailgun/source_mailgun/manifest.yaml
> +      datetime: "{{ config['start_date'] if config['start_date'] else day_delta(-3, format='%Y-%m-%dT%H:%M:%SZ') }}"
I think it's better to define a longer default start date, like 90 days.
You can improve the expression to:
`"{{ config.get('start_date', day_delta(-3, format='%Y-%m-%dT%H:%M:%SZ')) }}"`

Please bum the connector version (dockerfile, metadata and doc changelog).
Also add a comment in the documentation explaining the default date.

2023-10-20 16:42 UTC, marcosmarxm commented
Thanks @ariesgun I added the PR to the backlog. Soon someone from the team will start the review.

2023-10-26 10:20 UTC, lazebnyi approved these changes
LGTM!

2023-10-31 17:40 UTC, marcosmarxm approved these changes

2023-10-31 18:19 UTC, merged