Add single node GCP Terraform deploy option
airbytehq/airbyte pull request #3145
Opened 2021-04-29 23:31 UTC by jrhizor

Adds the ability to deploy a single node to GCP with minimal effort with Terraform.

Remaining todos:
- [ ] Grant the ability for an external IAM to be an `instanceAdmin` and access to Stackdriver metrics for that instance. 
- [ ] Put docs in actual docs, not `README.md`
- [ ] Add deletion protection? (open to comment on if this is useful/desired)

2021-04-30 00:45 UTC, michel-tricot commented on terraform/gcp/single-node/main.tf
> +resource "google_compute_network" "airbyte-network" {
I think we should only focus on creating the resources that are related to the instance, not network nor subnetworks, nor NAT. These should be specified as variables so you can hook your environement

2021-04-30 00:47 UTC, michel-tricot requested changes

2021-04-30 00:47 UTC, michel-tricot commented on terraform/gcp/single-node/main.tf
> +}
I woudn't put that here.

2021-04-30 00:47 UTC, michel-tricot commented on terraform/gcp/single-node/main.tf
> +}
I wouldn't put that here

2021-06-01 23:16 UTC, sherifnada commented
@jrhizor is this blocked on review?

2021-06-22 22:18 UTC, closed without merging