Update bigquery.md with output schemas of V2 destination
airbytehq/airbyte pull request #31548
Opened 2023-10-18 11:02 UTC by ignaciovi

## What
Due to changes in the BigQuery destination (version 2.0.0+) some parts of the BigQuery documentation are outdated

## How
I've changed the `bigquery.md` file to reflect new airbyte fields populated on the table's output schema

2023-10-18 11:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=31548) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=31548) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=31548) it.</sub>

2023-10-18 19:55 UTC, marcosmarxm requested changes
@evantahler can you assignee someone from destination team to validate this doc change?Not sure if we want to reference raw tables in docs instead of the final ones. Or maybe remove how data looks like and only create a link to the destination v2 doc.

2023-10-18 19:58 UTC, evantahler requested changes

2023-10-18 19:58 UTC, evantahler commented on docs/integrations/destinations/bigquery.md
```suggestion
... and a column of the proper data type for each of the top-level properties from your source's schema.  Arrays and Objects will remain as JSON columns in BigQuery. 

```

2023-10-18 19:59 UTC, evantahler commented on docs/integrations/destinations/bigquery.md
> +... and a column of the proper data type for each of the top-level properties from your source's schema.  Arrays and Objects will remain as JSON columns in BigQuery.
```suggestion
... and a column of the proper data type for each of the top-level properties from your source's schema.  Arrays and Objects will remain as JSON columns in BigQuery. Learn more about Typing and Deduping [here](/understanding-airbyte/typing-deduping)
```

2023-10-18 20:00 UTC, evantahler approved these changes
Added some changes, and 👍

2023-10-19 13:28 UTC, marcosmarxm commented
/approve-and-merge reason="only doc changes"

2023-10-19 13:29 UTC, octavia-approvington commented
Jerry would be proud <br/> ![Spongebob](https://media0.giphy.com/media/26u4lOMA8JKSnL9Uk/giphy.gif?cid=ecf05e47acx2v2fgjubem3x5944r4enp4vekwmbboaoug95u&rid=giphy.gif&ct=g)

2023-10-19 13:29 UTC, octavia-approvington approved these changes

2023-10-19 13:29 UTC, merged