Adding subscription version to the Orb Airbyte connector
airbytehq/airbyte pull request #31635
Opened 2023-10-20 00:34 UTC by sskhandek

## What
*Describe what the change is solving*
In Orb, subscriptions can change over time and have different plans associated with them in different time frames. This PR exposes the concept of a `SubscriptionVersion`, which includes the `subscription_id`, `plan_id`, `start_date` and `end_date`.

## How
*Describe the solution*
We call the `subscription_versions` endpoint in the Orb API, which we can paginate through.

## Recommended reading order
1. `airbyte-integrations/connectors/source-orb/source_orb/schemas/subscription_version.json`
2. `airbyte-integrations/connectors/source-orb/source_orb/source.py`
3. `airbyte-integrations/connectors/source-orb/unit_tests/test_incremental_streams.py`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*
None since this is adding a new object.
 
*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

2023-10-20 11:07 UTC, va3093 approved these changes
LGTM

2023-10-20 13:33 UTC, marcosmarxm commented
Thanks for the contribution. Do you have an issue open requesting this feature?

2023-10-20 17:33 UTC, sskhandek commented
Hi @marcosmarxm , I don't. I'm part of the Orb team and we wanted to add this resource to the connector for the benefit of one of our clients.

2023-10-23 09:12 UTC, va3093 commented
Hey guys. Can we merge this please 🙏

2023-10-24 00:04 UTC, sskhandek commented
Hi @marcosmarxm , can you let me know if anything's needed from our end to merge this?

2023-10-24 00:09 UTC, marcosmarxm commented
@sskhandek at the moment the team is dedicated to review Hackathon contributions. After the event ends we're going to return to the community backlog. This doesn't block you to build the connector locally and use to your project for now.

2023-10-24 22:28 UTC, sskhandek commented
> @sskhandek at the moment the team is dedicated to review Hackathon contributions. After the event ends we're going to return to the community backlog. This doesn't block you to build the connector locally and use to your project for now.

FYI on the timeline to merge here! @va3093

2023-10-30 23:16 UTC, sskhandek commented
@marcosmarxm when does the event end? Just want to give a timeline to folks

2023-11-06 17:44 UTC, sskhandek commented
@marcosmarxm  are there any updates here?

2023-11-13 11:02 UTC, va3093 commented
@marcosmarxm Any update here?

2023-11-22 18:09 UTC, marcosmarxm requested changes
Missing doc entry changelog besides that LGTM

2024-03-08 20:00 UTC, marcosmarxm commented
@sskhandek do you have a link to Orb API for this endpoint?

2024-04-24 00:32 UTC, marcosmarxm commented
Closing due inactivity. @sskhandek let me know if you want to continue the contribution to reopen it.

2024-04-24 00:32 UTC, closed without merging