🎉 New Source: Pushnews
airbytehq/airbyte pull request #31886
Opened 2023-10-26 17:31 UTC by Ruy-Araujo

## What

Add new source for Pushnews

#31881 

## How
Using the low code source generator

Get data from:

- Sites
- Sites Configurations
- Notifications
- Push on Site
- Push on Site Events

## Recommended reading order
1. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user?
No

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

</details>

2023-10-26 17:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=31886) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=31886) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=31886) it.</sub>

2023-11-22 18:04 UTC, marcosmarxm requested changes
Left some comments, sorry the delay to start the review!

2023-11-22 18:04 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-pushnews/requirements.txt
> +-e .
Rename icon file to `icon.svg`

2023-11-22 18:04 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-pushnews/source_pushnews/schemas/notifications.json
> +        },
You don't need to have sxchema files if you're using inline schema in manifest.yaml

2023-11-22 18:04 UTC, marcosmarxm commented on docs/integrations/sources/pushnews.md
> +Pushnews [API reference](https://docs.pushnews.com.br/) has v2 at present and v1 as depricated. The connector as default uses v2.
Missing changelog.

2023-11-22 18:04 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-pushnews/setup.py
> +    "connector-acceptance-test",
Remove this because is not used anymore.
```suggestion
```

2023-11-22 18:04 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-pushnews/source_pushnews/manifest.yaml
> +      - api_key
start date isn't required but it is expected in incremental syncs.

2023-12-04 18:10 UTC, marcosmarxm commented
@Ruy-Araujo did you have time to take a look in my latest review?

2023-12-04 20:44 UTC, Ruy-Araujo commented
Hi @marcosmarxm, sorry for the delay. 

I've already made changes to everything except for the schema, I'm still working on them. I'll release the corrections as soon as possible.

2023-12-05 00:49 UTC, Ruy-Araujo commented
All changes have been made, if any further modifications are needed, please let me know. 😀

2024-01-20 00:41 UTC, marcosmarxm commented
@Ruy-Araujo sorry the missing review to your contribution. I'm trying to setup a sandbox account but Pushnews need quite more engineering work to make the initial installation.

2024-01-20 21:30 UTC, Ruy-Araujo commented
Hey @marcosmarxm no problem, if there's something I can help with, let me know.

2024-06-14 13:23 UTC, marcosmarxm commented
Hi @Ruy-Araujo, apologies for the delay in updating and reviewing your contribution. Regrettably, we had to decline it for now because the team was unable to set up a sandbox and conduct integration tests. We understand this can be disappointing and we want to assure you that we recognize this issue. We dedicated a significant amount of effort in the previous quarter, and will continue to do so in the next to improve the process for contributions like new connectors. The team will include a new process for contributing and publishing sources in future doesn't depend on Airbyte needs to have a proper sandbox to accept contributions and ensure all tests are valid. Please get in touch if you want to learn more about it and resubmit the amazing source :) Thanks a lot for all effort you put into this contribution and feel free to contact me on Slack

2024-06-14 13:23 UTC, closed without merging