[source-mongodb-v2] : Add UUID codecs to custom registry while trying…
airbytehq/airbyte pull request #32119
Opened 2023-11-02 21:48 UTC by akashkulk

… to parse DBZ events

## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/resources/pull-requests-handbook)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:generateScaffolds` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

<details><summary><strong>Updating the Python CDK</strong></summary>

### Airbyter

Before merging:
- Pull Request description explains what problem it is solving
- Code change is unit tested
- Build and my-py check pass
- Smoke test the change on at least one affected connector
   - On Github: Run [this workflow](https://github.com/airbytehq/airbyte/actions/workflows/connectors_tests.yml), passing `--use-local-cdk --name=source-<connector>` as options
   - Locally: `airbyte-ci connectors --use-local-cdk --name=source-<connector> test`
- PR is reviewed and approved
      
After merging:
- [Publish the CDK](https://github.com/airbytehq/airbyte/actions/workflows/publish-cdk-command-manually.yml)
   - The CDK does not follow proper semantic versioning. Choose minor if this the change has significant user impact or is a breaking change. Choose patch otherwise.
   - Write a thoughtful changelog message so we know what was updated.
- Merge the platform PR that was auto-created for updating the Connector Builder's CDK version
   - This step is optional if the change does not affect the connector builder or declarative connectors.

</details>

2023-11-03 17:41 UTC, akashkulk commented
/publish-java-cdk dry-run=true

2023-11-03 18:25 UTC, rodireich commented
This looks good.
Is there no way to do cascading attempt, if not standard try legacy etc.
How will packed mode help? we still need to serialize a uuid out

2023-11-03 18:26 UTC, rodireich approved these changes

2023-11-03 19:59 UTC, rodireich commented
Thinking about this issue:
* This issue is limited to incremental sync only if I understand correctly. How are other UUID subtypes getting handled during initial?
* Are there other types or subtypes we're unable to convert? either during initial or incremental

2023-11-04 01:05 UTC, stephane-airbyte requested changes
bump version to 0.4.2. Marius just pushed 0.4.1 to solve a merge conflict

2023-11-06 17:00 UTC, akashkulk commented
> bump version to 0.4.2. Marius just pushed 0.4.1 to solve a merge conflict

Can you link me to the PR?

2023-11-06 17:09 UTC, stephane-airbyte commented
> > bump version to 0.4.2. Marius just pushed 0.4.1 to solve a merge conflict
> 
> Can you link me to the PR?

https://github.com/airbytehq/airbyte/pull/32192

2023-11-06 17:11 UTC, stephane-airbyte commented
@akashkulk I understand your request for a PR. Looks like 0.4.0's changelog should have been "fix compiler warnings", while 0.4.1s should have been "add 's3-destination' module to CDK"

2023-11-06 17:28 UTC, stephane-airbyte commented on airbyte-cdk/java/airbyte-cdk/README.md
> +| 0.4.0   | 2023-11-02 | [\#32192](https://github.com/airbytehq/airbyte/pull/32192) | Add 's3-destinations' CDK module.
0.4.1?

2023-11-06 17:29 UTC, stephane-airbyte commented on airbyte-cdk/java/airbyte-cdk/README.md
> +| 0.4.0   | 2023-11-02 | [\#32050](https://github.com/airbytehq/airbyte/pull/32050) | Fix compiler warnings.
thank you for adding this

2023-11-06 17:30 UTC, stephane-airbyte approved these changes

2023-11-06 18:30 UTC, akashkulk commented
/publish-java-cdk dry-run=true

2023-11-06 19:29 UTC, akashkulk commented
/publish-java-cdk dry-run=true

2023-11-07 05:46 UTC, akashkulk commented
/publish-java-cdk

2023-11-07 05:55 UTC, akashkulk commented
/publish-java-cdk

2023-11-07 06:28 UTC, merged