re-update all connectors for new CDK version and more stringent javac checks
airbytehq/airbyte pull request #32125
Opened 2023-11-02 23:30 UTC by stephane-airbyte

This is a no-op in term of features or bugs. This is part 2 of a series of PRs. This builds upon #32118 

I'm only trying to use as many compiler warnings as possible. They're cheap and can help with a lot of bugs.
Unfortunately, our CDK is currently packaged in a way that causes warnings in any package that uses it. I fixed that by making swagger an api-level dependency (which means it'll be exported to projects that depend on airbyte-cdk), but all projects that depend on it will have a warning, which means we can't turn those into errors.

Since we released a new CDK (0.4.0) that exports everything properly, we now need to use it and fix the connectors that are certified

For the projects that don't depend on CDK, I'm disabling the errors that are present, rather than making a sweeping change across all projects. I'll try to fix as many of those as possible, and remove the special cases.

2023-11-02 23:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=32125) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=32125) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=32125) it.</sub>

2023-11-02 23:42 UTC, stephane-airbyte commented on airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresQueryUtils.java
> -                                                                                                          final StateManager<AirbyteStateMessage, AirbyteStreamState> stateManager,
StateManager was modified in CDK 0.4.0 to not have any generics. Fixing that here.

2023-11-02 23:42 UTC, stephane-airbyte commented on airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/initialsync/MySqlInitialLoadRecordIterator.java
> +@SuppressWarnings("try")
close() throws Exception, which triggers a java warning.

2023-11-02 23:42 UTC, stephane-airbyte commented on airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/initialsync/MySqlInitialLoadRecordIterator.java
> +  private final JdbcCompatibleSourceOperations<MysqlType> sourceOperations;
this was a raw type before

2023-11-02 23:43 UTC, stephane-airbyte commented on airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/initialsync/MySqlInitialLoadHandler.java
> +  private final MySqlSourceOperations sourceOperations;
MySqlSourceOperation is used everywhere in this class, and is not parameterized

2023-11-02 23:43 UTC, stephane-airbyte commented on airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlQueryUtils.java
> +      return Collections.emptySet();
collections.EMPTY_SET is a SET, while Collections.emptySet() returns a Set<>

2023-11-02 23:43 UTC, stephane-airbyte commented on airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlQueryUtils.java
> +                                                    """;
fixing whatespaces that would have been removed by the compiler (and that triggered a warning)

2023-11-02 23:44 UTC, stephane-airbyte commented on airbyte-integrations/connectors/source-mongodb-v2/src/main/java/io/airbyte/integrations/source/mongodb/MongoUtil.java
> +        @SuppressWarnings("unchecked")
the get() returns an Object, so there's an unchecked cast here

2023-11-02 23:44 UTC, stephane-airbyte commented on airbyte-integrations/connectors/source-mongodb-v2/src/main/java/io/airbyte/integrations/source/mongodb/MongoUtil.java
> +          @SuppressWarnings("unchecked")
get() returns an Object, so there's an unchecked cast here

2023-11-02 23:45 UTC, stephane-airbyte commented on airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/typing_deduping/SnowflakeV1V2Migrator.java
> +    String tableName = this.namingConventionTransformer.getRawTableName(streamConfig.id().originalName());
getRawTableName is deprecated. I had to move the call to its own line for the SuppressWarnings to be accepted

2023-11-02 23:45 UTC, stephane-airbyte commented on airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/typing_deduping/SnowflakeSqlGenerator.java
> +    @SuppressWarnings("deprecation")
isNullable is deprecated

2023-11-02 23:46 UTC, stephane-airbyte commented on airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/typing_deduping/SnowflakeColumnDefinition.java
> +public record SnowflakeColumnDefinition(String type, boolean isNullable) {
Deprecated on a constuctor was triggering a warning, while the call to isNullable was also triggering a warning on the calling site for deprecation. We're keeping the deprecation, but removing the warning in this class

2023-11-02 23:46 UTC, stephane-airbyte commented on airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/uploader/BigQueryUploaderFactory.java
> +                                                 """;
fixing whitespace that would be removed by the compiler but triggered a warning

2023-11-02 23:46 UTC, stephane-airbyte commented on airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryRecordStandardConsumer.java
>  public class BigQueryRecordStandardConsumer extends AsyncStreamConsumer {
close throws Exception, hence the suppresswarnings

2023-11-02 23:46 UTC, stephane-airbyte commented on airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryRecordConsumer.java
> +class BigQueryRecordConsumer extends FailureTrackingAirbyteMessageConsumer implements AirbyteMessageConsumer {
close() throws Exception, hence the SuppressWarnings

2023-11-02 23:47 UTC, stephane-airbyte commented on airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryGcsOperations.java
>    public void cleanUpStage(final String datasetId, final String stream, final List<String> stagedFiles) {
the overloaded cleanUpStage is deprecated,so this one needs to be annotated too

2023-11-03 03:38 UTC, rodireich approved these changes
0 warnings!
Looks good to me. 

Maybe just consult with @airbytehq/destinations since a bunch of their connectors are upgraded as well.

2023-11-03 18:09 UTC, postamar requested changes
Can you wait until https://github.com/airbytehq/airbyte/pull/32050 merges please? I expect it to pass CI in an hour or so, since it touches quite a few of the same connectors. It bumps them to 0.4.0 as well.

Blocking the merge is the only reason why I'm "requesting changes"

2023-11-03 18:09 UTC, postamar commented on docs/integrations/destinations/snowflake.md
> +| 3.4.6           | 2023-11-03 | [32125](https://github.com/airbytehq/airbyte/pull/32125)   | Fix compilation warnings 7
typo

2023-11-03 18:09 UTC, postamar commented on docs/integrations/destinations/bigquery.md
> +| 2.3.6   | 2023-11-03 | [32125](https://github.com/airbytehq/airbyte/pull/32125)   | fix compilation warnings
nit: here and in the other changelogs, I think the significant change is rather that we're adopting version 0.4.0 of the CDK.

I'm assuming that these changelogs are read when the connector's misbehaving after an upgrade; knowing about the CDK change is probably going to be more relevant in that use case.

2023-11-03 20:50 UTC, postamar approved these changes
I've removed myself as a blocker spinning off the connector changes in https://github.com/airbytehq/airbyte/pull/32050 into separate PRs:
https://github.com/airbytehq/airbyte/pull/32173
https://github.com/airbytehq/airbyte/pull/32174
https://github.com/airbytehq/airbyte/pull/32175
https://github.com/airbytehq/airbyte/pull/32176
https://github.com/airbytehq/airbyte/pull/32177
https://github.com/airbytehq/airbyte/pull/32178
https://github.com/airbytehq/airbyte/pull/32179
https://github.com/airbytehq/airbyte/pull/32180

Not all have release notes, because the CDK bump is often a functional no-op.

2023-11-06 20:34 UTC, postamar approved these changes

2023-11-08 22:21 UTC, merged