Greenhouse Source: Updated QL to 200
airbytehq/airbyte pull request #32397
Opened 2023-11-09 21:08 UTC by pnilan

## What
Updates the QL to 200 for the Greenhouse source connector.

2023-11-10 08:53 UTC, lazebnyi approved these changes

2023-11-22 17:29 UTC, katmarkham approved these changes

2023-11-30 01:51 UTC, bnchrch requested changes
I think a rebase went wrong here 😬

2023-11-30 15:55 UTC, ChristoGrab commented
@bnchrch My bad! I pushed some changes at EOD and forgot to update the branch before walking away 🙀 Everything's back in order now

2023-11-30 17:51 UTC, bnchrch approved these changes
LGTM!

2023-11-30 18:58 UTC, merged