🐛 Source Sftp-Bulk: fix empty password field exception
airbytehq/airbyte pull request #32719
Opened 2023-11-22 08:47 UTC by SoerenStahlmann

## What
When creating a SFTP-Bulk connection you can choose to authenticate via password or a ssh-key. If you choosing to authenticate with a ssh-key an exception is thrown when the password field is empty, since the dictionary value 'password' does not exist in that case. 

This case was already handled for the other authentication method by providing a default 'None' value when getting the dictionary key for an empty ssh-key.

## How
I provided a default value in case the password field was not set

```python
password=config.get("password", None),
```

## Pre-merge Actions

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

2023-11-22 08:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=32719) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=32719) before we can accept your contribution.<br/><hr/>**Soeren Stahlmann** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=32719) it.</sub>

2023-11-22 16:37 UTC, marcosmarxm requested changes
Small change.

2023-11-22 16:37 UTC, marcosmarxm commented on docs/integrations/sources/sftp-bulk.md
> +| 0.1.3   | 2023-11-22 |  | Password field no longer throws exception when empty |
Please update here.

2023-11-30 13:58 UTC, marcosmarxm reviewed
At the moment integration tests are failing and will take some time to fix them. Thanks for your patience.

2024-02-15 08:59 UTC, SoerenStahlmann commented
Are there any news concerning the issue @marcosmarxm? We are currently running a forked version of the connector and would rather switch to the official connector as soon as the issue is merged.

2024-06-12 18:01 UTC, closed without merging

2024-06-12 18:01 UTC, marcosmarxm commented
@SoerenStahlmann sorry the lack of updates here. The latest version of this connector already fix this issue. Please upgrade to the latest version.