✨ source-stripe: use concurrent source to read multiple streams concurrently
airbytehq/airbyte pull request #32908
Opened 2023-11-28 23:54 UTC by girarda

## What
* Update the stripe connector to read multiple streams concurrently

## How
* Extend ConcurrentSourceAdapter instead of AbstractSource

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/resources/pull-requests-handbook)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:generateScaffolds` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

<details><summary><strong>Updating the Python CDK</strong></summary>

### Airbyter

Before merging:
- Pull Request description explains what problem it is solving
- Code change is unit tested
- Build and my-py check pass
- Smoke test the change on at least one affected connector
   - On Github: Run [this workflow](https://github.com/airbytehq/airbyte/actions/workflows/connectors_tests.yml), passing `--use-local-cdk --name=source-<connector>` as options
   - Locally: `airbyte-ci connectors --use-local-cdk --name=source-<connector> test`
- PR is reviewed and approved
      
After merging:
- [Publish the CDK](https://github.com/airbytehq/airbyte/actions/workflows/publish-cdk-command-manually.yml)
   - The CDK does not follow proper semantic versioning. Choose minor if this the change has significant user impact or is a breaking change. Choose patch otherwise.
   - Write a thoughtful changelog message so we know what was updated.
- Merge the platform PR that was auto-created for updating the Connector Builder's CDK version
   - This step is optional if the change does not affect the connector builder or declarative connectors.

</details>

2023-12-04 14:08 UTC, maxi297 requested changes
see https://github.com/airbytehq/airbyte/pull/32908#issuecomment-1836202144

2023-12-05 16:17 UTC, clnoll reviewed
On the face of it the change looks fine but would like to take another look once the CAT failure is addressed.

2023-12-07 22:57 UTC, clnoll commented on airbyte-integrations/connectors/source-stripe/source_stripe/source.py
> -        config["start_date"] = start_date
So is it the case that we never really needed to mutate the config?

2023-12-07 22:57 UTC, clnoll approved these changes
LGTM!

2023-12-11 13:43 UTC, maxi297 approved these changes
LGTM! Have we checked if we have the expected benefits? My memory is telling me that we expect CPU to always reach the limit instead of being low while processing streams without data which would lead to shorter syncs. Have confirmed this assumption using https://app.datadoghq.com/dashboard/b2x-7y7-izf/concurrent-cdk---stripe-resource-usage?

2023-12-12 00:53 UTC, girarda commented
Good question @maxi297. The CPU is not 100% pegged because there's no real guarantee that there will always be records ready to be processed, but the CPU is able to peek:
<img width="1184" alt="Screenshot 2023-12-11 at 4 51 26 PM" src="https://github.com/airbytehq/airbyte/assets/1451943/5d93403c-2219-4d42-8396-d34afb64fedd">

Compared with CPU usage on 5.0.2 where the CPU usage only have short spikes above the 50% mark:
<img width="1304" alt="Screenshot 2023-12-11 at 4 52 07 PM" src="https://github.com/airbytehq/airbyte/assets/1451943/495e4750-b2e0-4995-8194-a45387257c88">

2023-12-12 03:19 UTC, girarda commented on airbyte-integrations/connectors/source-stripe/integration_tests/expected_records.jsonl
> +{"stream": "checkout_sessions", "data": {"id": "cs_test_a1uSLwxkrTLjGhRXgzJweMwh09uvSZcWIkGLcIqDXzYADowSPwkAmJUrAN", "object": "checkout.session", "after_expiration": null, "allow_promotion_codes": n
the record's "custom_text" has a new field `"after_submit": null`

2023-12-12 03:38 UTC, merged