source-intercom adding an additional contact_segment substream
airbytehq/airbyte pull request #33244
Opened 2023-12-08 13:12 UTC by nisargpatel-m

## What
adding a substream fetching the segments object individually from the contacts streams, adding an additional contact id field to the substream

feat(source-intercom): add contact_segments stream with Dockerfile setup

This commit introduces the 'contact_segments' stream to the source-intercom connector, extending its functionality. The update includes a new manifest section, JSON schema file, and the necessary Dockerfile configuration for proper environment setup.

- The Dockerfile has been created to set up a lightweight Python environment using Alpine Linux as a base image.

- A new manifest entry for the 'contact_segments' substream outlines incremental sync capabilities along with requisite transformations.

- The corresponding JSON schema for 'contact_segments' specifies its data structure and types.

This enhancement allows users to retrieve segment information associated with contacts directly from Intercom through Airbyte's integration system, improving the completeness of available data for synchronization tasks.

## How
Creating a new substream i.e. contact_segment based of the parent stream i.e. contact. This substream waits till the parent stream has been completed running and than retrieves the segment information for each of the contact. 

## Recommended reading order
1. `manifest.yaml`
2. `schema/contact_segments.json`
3. `Dockerfile`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

This pr introduces **_no_** breaking changes.

2023-12-11 12:47 UTC, marcosmarxm requested changes
Left some comments.

2023-12-11 19:06 UTC, nisargpatel-m commented on airbyte-integrations/connectors/source-intercom/Dockerfile
> +FROM base as builder
Good to know, In that case Ill take away the docker file from the PR

2023-12-20 14:17 UTC, marcosmarxm commented
@nisargpatel-m please make sure to sign the CLA or use the same user to commit the changes.

2024-01-20 00:38 UTC, marcosmarxm commented
Closed due inactivity @nisargpatel-m let me know if you want to return this contribution

2024-01-20 00:38 UTC, closed without merging