🐛 Source Serpstat: fixed bug related to full data export
airbytehq/airbyte pull request #33360
Opened 2023-12-12 17:44 UTC by alex-danilin

## What
*Fixed the issue with an error related to full data export*

## How
*Added stop condition in Pagination settings*

## 🚨 User Impact 🚨
*No braking changes. Bug is fixed*

## Pre-merge Actions
<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

2023-12-19 17:12 UTC, marcosmarxm requested changes

2023-12-19 17:12 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-serpstat/source_serpstat/manifest.yaml
> +          stop_condition: "{{response.error.code==32017 or response.result.summary_info.page > config['pages_to_fetch'] - 1}}"
Tests aren't working:
```
[35m51:[0m [7.59s] {"type": "LOG", "log": {"level": "INFO", "message": "Backing off _send(...) for 0.0s (airbyte_cdk.sources.streams.http.exceptions.UserDefinedBackoffException: Request URL: https://api.serpstat.com/v4/, Response Code: 200, Response Text: {\"id\":\"2023-12-19 16:30:24.590822+00:00\",\"error\":{\"code\":32000,\"message\":\"Too Many Requests\",\"data\":null}})"}}
```

2024-01-12 13:25 UTC, alex-danilin commented
@marcosmarxm I can't replicate the issue with tests. I run tests on a GCP instance, and they pass. Can you add more details on the credentials you are using for tests? It might be that you have some restrictions on your credentials.

2024-06-12 14:39 UTC, marcosmarxm commented
@alex-danilin I'm closin as tests weren't passing or fixing the current integration. Please let me know if you want to return the work here.

2024-06-12 14:39 UTC, closed without merging