added get_header_row_offset helper google-sheets source
airbytehq/airbyte pull request #33743
Opened 2023-12-22 10:22 UTC by theissn

## What
Add an option for row offset to the google sheets connector (Header row offset)

<img width="877" alt="Screenshot 2023-12-22 at 10 19 22" src="https://github.com/airbytehq/airbyte/assets/5305773/60b0d77b-3db5-412f-8c1a-f30d45624075">

## How
Simply added an additional (optional) config setting for skipping x amount of rows before the headers

## 🚨 User Impact 🚨
No breaking changes or anything to do for existing users. Will default to 0 unless specified otherwise

2023-12-22 10:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=33743) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=33743) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=33743) it.</sub>

2023-12-29 14:03 UTC, marcosmarxm requested changes
Some comments.

2023-12-29 14:03 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-google-sheets/source_google_sheets/helpers.py
> +        return 0
```suggestion
    @staticmethod
    def get_header_row_offset(config) -> int:
        return config.get("header_row_offset", 1)
```

2023-12-29 14:03 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-google-sheets/source_google_sheets/spec.yaml
> +      default: 0
Maybe add the minimum to 1 and default as 1.

2024-01-15 20:53 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-google-sheets/source_google_sheets/spec.yaml
> +      default: 0
@theissn did you check my comment here?

2024-02-06 14:53 UTC, lazebnyi requested changes

2024-02-06 14:53 UTC, lazebnyi commented on airbyte-integrations/connectors/source-google-sheets/source_google_sheets/source.py
> +        header_row_offset = Helpers.get_header_row_offset(config)
Need add some default value, to avoid braking changes for old users which haven't this field in config.

2024-06-13 14:01 UTC, lazebnyi approved these changes
lgtm

2024-06-13 14:04 UTC, marcosmarxm approved these changes

2024-08-21 09:00 UTC, closed without merging