Requirements updated to CDK.
airbytehq/airbyte pull request #3378
Opened 2021-05-12 17:09 UTC by htrueman

## What
Requirements updated to CDK.
airbyte-protocol and base-python requirements removed.

## Pre-merge Checklist
- [ ] *Run integration tests*
- [ ] *Publish Docker images*

## Recommended reading order
1. `setup.py`
1. the rest

2021-05-12 17:59 UTC, sherifnada approved these changes
LGTM! please make sure to run `/test` and `/publish` (with bumping the version) before merging

2021-05-12 17:59 UTC, sherifnada commented on airbyte-integrations/connectors/source-iterable/setup.py
> +    "airbyte-cdk==0.1.0rc5",
```suggestion
    "airbyte-cdk==0.1.2",
```

2021-05-12 17:59 UTC, sherifnada commented on airbyte-integrations/connectors/source-iterable/setup.py
> +    "airbyte-cdk==0.1.0rc5",
0.1.2 is the latest version

2021-05-12 18:33 UTC, keu commented on airbyte-integrations/connectors/source-slack-singer/sample_files/configured_catalog.json
> +    },
I'm not sure what these changes for?

2021-05-12 18:34 UTC, keu commented
It is not clear from PR's title what these change for, i.e. no name of connector and changes has two different connectors (slack and iterable)

2021-05-12 18:37 UTC, keu requested changes
see my comments

2021-05-13 08:33 UTC, keu requested changes

2021-05-13 08:33 UTC, keu commented on airbyte-integrations/connectors/source-iterable/main_dev.py
> +from airbyte_cdk.entrypoint import launch
I think `main_dev.py` should also be renamed to `main.py`, don't forget to update README

2021-05-13 08:38 UTC, po3na4skld approved these changes

2021-05-13 09:24 UTC, keu approved these changes

2021-05-13 10:31 UTC, htrueman commented
/test connector=source-iterable

2021-05-13 16:28 UTC, htrueman commented
/test connector=source-iterable

2021-05-13 16:29 UTC, keu requested changes

2021-05-13 16:29 UTC, keu commented on airbyte-integrations/connectors/source-iterable/Dockerfile
> +LABEL io.airbyte.name=airbyte/source-iterable
new line

2021-05-13 20:13 UTC, keu commented
> /test connector=source-iterable
> 
> > 🕑 source-iterable https://github.com/airbytehq/airbyte/actions/runs/839504209
> > ❌ source-iterable https://github.com/airbytehq/airbyte/actions/runs/839504209

you need to check .dockerignore for files that included in container

2021-05-13 23:42 UTC, sherifnada submitted a review, later dismissed
@htrueman sorry missed this in my first review: `read_stream` doesn't exist anymore. This was written on an old version of the CDK. Could you change it to use `read_records` and take the appropriate parameters?

2021-05-14 13:19 UTC, htrueman commented
/test connector=source-iterable

2021-05-14 14:34 UTC, po3na4skld approved these changes

2021-05-16 18:21 UTC, htrueman commented
/test connector=source-iterable

2021-05-17 13:38 UTC, htrueman commented
/test connector=source-iterable

2021-05-18 11:22 UTC, keu approved these changes
lgtm

2021-05-18 14:56 UTC, htrueman commented
/test connector=source-iterable

2021-05-18 15:10 UTC, htrueman commented
/publish connector=connectors/source-iterable

2021-05-18 15:26 UTC, merged