Add S3 IAM roles + ALB ingress definition
airbytehq/airbyte pull request #33944
Opened 2024-01-04 16:19 UTC by Hesperide

Adds:
* New step on S3 IAM roles.
* New section including a skeleton for ALB ingress definition
* Clarifying that default external Airbyte DB security config doesn't require more than user/password
* Clarifying that you need to change `ingress` field in `airbyte.yml`

2024-01-09 15:16 UTC, perangel requested changes

2024-01-09 15:18 UTC, perangel commented
We should probably add some documentation about creating the appropriate IAM policy necessary to attach to the ServiceAccount so that it can manage the ALB:
https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy.json

2024-01-09 16:58 UTC, Hesperide commented on docs/enterprise-setup/implementation-guide.md
> +    # [Optional] Custom SSL policy for security settings and protocols. If not provided, a default will be used.
These are optional, but I assume most customers will want to specify them - so really, it's 'Recommended'.

What would you suggest removing for simplicity?

2024-01-12 16:51 UTC, perangel approved these changes

2024-01-12 17:00 UTC, merged