🚨🚨 Source Microsoft Teams: Update Schemas
airbytehq/airbyte pull request #33959
Opened 2024-01-04 21:59 UTC by ChristoGrab

## What

Resolves

2024-01-05 17:58 UTC, ChristoGrab commented on airbyte-integrations/connectors/source-microsoft-teams/source_microsoft_teams/schemas/team_device_usage_report.json
>        "type": ["null", "string"]
Did not add a "date" format to this field as it defaults to an empty string when empty rather than a null value, which will throw a validation error.

2024-01-05 19:40 UTC, katmarkham approved these changes

2024-01-08 22:58 UTC, evantahler commented
@alafanechere - what do you think about this CAT test failure?  Should we allow this case?

2024-01-09 08:27 UTC, alafanechere requested changes
> @alafanechere - what do you think about this CAT test failure? Should we allow this case?

I indeed think that the `additionalProperties` field should be removed from the `credentials` object in the spec, it will default to `true`.
If we're not allowing additionalProperties it means we'd have to perform a config migration on the next iteration on this `credentials` field if we remove a field and a rollback to the previous config state needs to be supported in case of a version downgrade.
So we enforce `additionalProperties: true` on spec field to keep flexibility and maximize backward compatiblity.

Looking at this PR, this is a test that was likely previously failing. And  to make it pass we should just remove `additionalProperties: false` and the `credentials` oneOf (not the `advancedAuth` section.

[For example, on `source-google-sheets`, we have a similar `credentials` field on which `additionalProperties` is not set.
](https://github.com/airbytehq/airbyte/blob/main/airbyte-integrations/connectors/source-google-sheets/source_google_sheets/spec.yaml#L29)

2024-01-09 22:19 UTC, ChristoGrab commented
@alafanechere Thanks for taking a look at this! Apologies for the slow turnaround, I was stuck for a while trying to figure out how to resolve the CAT failure caused by removing the `false` flag.

It turns out the root cause was very simple; the credentials in GSM were missing the "auth_type" key, which was preventing the connector from validating the correct auth method being used when additional properties were allowed. I've updated the creds and marked "auth_type" as a required key within the `credentials` object, and we are now fully green with additionalProps allowed 👍

2024-01-10 17:07 UTC, alafanechere approved these changes
🟢 CI = LGTM 😄

2024-01-10 19:03 UTC, merged