🐛 Source Linkedin Ads: fix changing next_page_token stopping criteria
airbytehq/airbyte pull request #34166
Opened 2024-01-11 15:22 UTC by FVidalCarneiro

## What
This pull request aims in changing the criteria used by the airbyte Linkedin Ads source connector for when to stop requesting the Linkedin API for more pages. Currently, the criteria is the following - stop requesting a new page when page size is smaller than maximum allowed records per page. We propose to change this criteria to - stop requesting a new page when page size is equal to zero. 

## How
This is done by modifying the `next_page_token` method in both the `LinkedinAdsStream` class and the `LinkedInAdsAnalyticsStream`.

## Recommended reading order
1. `streams.py`

## 🚨 User Impact 🚨
The source connector will behave as previously expected, no breaking changes. Given that an extra API call is made per account, this might slightly impact source connector performance, but this difference is negligible. The version change should therefore only be of type patch, rendering the connector version therefore equal to 0.6.5.

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

2024-01-11 15:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=34166) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=34166) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=34166) it.</sub>

2024-01-11 15:49 UTC, FVidalCarneiro commented
This PR solves related issue https://github.com/airbytehq/airbyte/issues/34164

2024-01-18 20:40 UTC, marcosmarxm reviewed
Thanks @FVidalCarneiro the issue you opened made more clear about the proposition you're suggesting. The change will impact in the connector behavior to probably always retrieve the N+1 page (the page doesn't exist) in most cases. What is the API response to that case? Can you confirm it won't return a 404 error?

Meanwhile I requested to the connector team take a look into your change

2024-01-19 14:43 UTC, FVidalCarneiro commented
Thank you @marcosmarxm for your review. 

Indeed, with the suggested implementation, we will always obtain the N+1 page, where N is the last page of the object. As you can see in the screenshot below, the API responds with an empty page and status code 200:

![last-page-ok](https://github.com/airbytehq/airbyte/assets/147708078/40e1f838-dddd-4b4a-b41d-a592eebf07bd)

If we wanted to avoid this "useless" call (but required when there is a broken creative, please read initial description of this PR), there is another solution which would be to add the condition `parsed_response.get("paging")["start"] + self.records_limit > parsed_response.get("paging")["total"]` to the end pagination criteria making the full condition equal to:
`if len(parsed_response.get("elements")) < self.records_limit and (parsed_response.get("paging")["start"] + self.records_limit > parsed_response.get("paging")["total"]):`. In this case we would maintain the original condition, but refine it by adding a condition which confirms that N is indeed the last page as the next page would request more elements than there is total. 

Even though the current suggested implementation would work, this last suggestion would also protect the connector against a potential future Linkedin API update, where a non existing page responds with 404 instead of 200 HTTP code.

If you (and/or the connector team) give me your approval, I can add this last suggested implementation (bearing in mind that the downside is that it requires more parsing of the response elements). Do you have a preference on one of these two solutions ?

2024-02-06 12:58 UTC, lazebnyi requested changes
Hey @FVidalCarneiro 
Thanks for your PR. Let's leave `len(parsed_response.get("elements")) < self.records_limit and (parsed_response.get("paging")["start"] + self.records_limit > parsed_response.get("paging")["total"])` as condition for last page. And add comment with link to issue why we need additional check

2024-02-06 13:30 UTC, FVidalCarneiro commented
Following the feedback of the engineering team available [here](https://github.com/airbytehq/airbyte/pull/34166#pullrequestreview-1830520237), I have decided to complement the pagination ending condition with a condition that ensures, based on the total record count field, that there are no other pages to request. This will both:

1. Allow to manage broken creatives that are missing from paginated responses (page responding with 99 records instead of 100).
2. Avoid sending a request to an empty page (the last request will be to the last page).

Ready for review @lazebnyi , many thanks !

2024-02-09 00:04 UTC, lazebnyi commented
hey @FVidalCarneiro 
can you grant edit access to maintainers - https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

2024-02-09 09:26 UTC, FVidalCarneiro commented
Hi @lazebnyi , I tried to follow the provided documentation to grant edit access to maintainers but I do not think this is possible given that my PR is coming from an organization GitHub project. I have found this [issue](https://github.com/orgs/community/discussions/5634) describes this problem. 

What is the recommended course of action ? Thanks !

2024-02-09 12:48 UTC, lazebnyi commented
Can you pull changes from https://github.com/airbytehq/airbyte/pull/35046 to your branch?

2024-02-09 14:51 UTC, FVidalCarneiro commented
I merged your changes to this branch @lazebnyi , thank you. Let me know if it is ok on your end ?

2024-02-14 15:52 UTC, FVidalCarneiro commented
Hi @lazebnyi , noticed recently there was a little merge conflict to be solved on `docs/integrations/sources/linkedin-ads.md`, should be good now. Let me know if there are any more actions on my side. Thank you for the support !

2024-02-27 10:55 UTC, FVidalCarneiro commented
Hi @lazebnyi , with the help of @agiloucap, we have rebased and solved the merge conflicts as the Linkedin Ads plugin had once again diverged from our fix. Could you let us know if all is ok on your end so we can merge the fix ?

2024-03-03 22:06 UTC, natikgadzhi commented
@marcosmarxm, can you please keep an eye on this? @lazebnyi has quite a few things on his plate, I want to make sure this PR doesn't fall through the cracks.

2024-03-15 11:03 UTC, FVidalCarneiro commented
Thank you @marcosmarxm , let us know please if there are any other changes required, thank you !

2024-04-10 15:18 UTC, FVidalCarneiro commented
@natikgadzhi , could you please help us assign someone to this PR ? We have updated with regards to the master branch already three times and responded to all feedback

2024-04-19 00:25 UTC, natikgadzhi commented
Pushing up a test PR to see if tests will pass, if it works, I'll merge this up.

2024-04-30 14:43 UTC, closed without merging

2024-04-30 14:43 UTC, marcosmarxm commented
It was merged in https://github.com/airbytehq/airbyte/pull/37421