🚨🚨✨ Source Slack: adding edit information and message lookback window config
airbytehq/airbyte pull request #34163
Opened 2024-01-11 13:15 UTC by krishan08

## What
Fix for https://github.com/airbytehq/airbyte/issues/34096

When a message is edited in slack the api response contains information regarding who edited the message and the timestamp it was edited. This is currently missing from the schema define in the slack source connector and therefore is omitted from the data outputted.

## How
- Added the edited fields to the message and threads schema definition.

This then creates a new issue when extracting message data incrementally for edits that happen after the original message was extracted. To solve this I implemented the same logic that is used for extracting threads incrementally.
- Added `messages_lookback_window` to `spec.json` file
- Moved the initialisation of the lookback window and the start date calculation to the parent IncrementalMessagesStream class

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
This change requires users to also specify a `messages_lookback_window` in the source settings.

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

## Pre-merge Actions
### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

2024-01-11 13:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=34163) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=34163) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=34163) it.</sub>

2024-01-18 20:55 UTC, marcosmarxm requested changes
Small comments, I requested to the connector team take a look in your proposition.

2024-01-18 20:55 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-slack/source_slack/schemas/channel_messages.json
> +      "type": ["null", "object"]
Please add `additionalProperties: true` this makes the field backward compatible with new or removed fields in the future.

2024-01-18 20:55 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-slack/source_slack/schemas/threads.json
> +      "type": ["null", "object"]
Same here.

2024-01-23 16:02 UTC, krishan08 commented
> Small comments, I requested to the connector team take a look in your proposition.

thanks @marcosmarxm, I've added the `additional properties` in for both

2024-02-06 14:40 UTC, lazebnyi requested changes

2024-02-06 14:40 UTC, lazebnyi commented on airbyte-integrations/connectors/source-slack/source_slack/source.py
> +        threads_lookback_window = pendulum.Duration(days=config["threads_lookback_window"])
We need to avoid braking changes and add migration config script. Please check google ads as a reference.

2024-02-06 14:40 UTC, lazebnyi commented on airbyte-integrations/connectors/source-slack/source_slack/source.py
> +        threads_lookback_window = pendulum.Duration(days=config["threads_lookback_window"])
May be migrate `lookback_window` to `threads_lookback_window` and set `messages_lookback_window` to 0 as default value.

2024-04-30 20:10 UTC, marcosmarxm commented
Source Slack was migrated to low-code and this contribution was not updated since last review.

2024-04-30 20:10 UTC, closed without merging