🐛 Source Zoom: update cloud registry metadata
airbytehq/airbyte pull request #34530
Opened 2024-01-25 16:54 UTC by ChristoGrab

## What

A small fix to Source Zoom's metadata. This connector is not currently available in Cloud, and will remain so until we are able to [set up a valid test environment to ensure its stability](https://github.com/airbytehq/airbyte/issues/26777). The metadata does not reflect this fact, so our docs currently incorrectly list it as available in Cloud.

![Zoom Cloud Status](https://github.com/airbytehq/airbyte/assets/108154848/350e720d-cd7d-4d03-a653-bf7c130a53d4)

2024-02-08 18:08 UTC, lazebnyi requested changes

2024-02-08 18:08 UTC, lazebnyi commented on airbyte-integrations/connectors/source-zoom/metadata.yaml
> +      enabled: false
I believe we need to update our documentation, but we shouldn't release it without conducting thorough testing.

2024-02-14 10:40 UTC, DanyloGL commented
It was decided to create new Zoom test account. Account was created and added to LastPass. For now it's free and could be used for testing only 2 out of 19 streams. Waiting for decision regarding what paid plan should be chosen.

2024-02-20 16:15 UTC, DanyloGL commented
New Zoom test account credentials were added to GSM. All streams except those that require Webinars were seeded (8 out of 19).

2024-02-21 15:44 UTC, ChristoGrab commented
Closing this as work on the connector has moved to #35369

2024-02-21 15:44 UTC, closed without merging