AirbyteLib: add null cache and null writer
airbytehq/airbyte pull request #34587
Opened 2024-01-28 03:13 UTC by aaronsteers

This is born out of a desire to get a better understanding of performance bottlenecks. This PR add a "NullCache" which does nothing at all with incoming records. 

The goal with this is to be able to get performance benchmarks on a source connector, with little or no slowdown from AirbyteLib, the file write, and/or the SQL cache.

2024-01-28 16:58 UTC, aaronsteers commented on airbyte-lib/airbyte_lib/_file_writers/null.py
> +"""A Parquet cache implementation."""
```suggestion
"""A No-Op (Null) cache implementation.

This is designed to test the raw throughput of a source, without any slowdown from writing files.
"""
```

2024-01-28 16:59 UTC, aaronsteers commented on airbyte-lib/airbyte_lib/_file_writers/null.py
> +    """A Parquet cache implementation."""
```suggestion
class NullWriterConfig(FileWriterConfigBase):
    """Configuration for the Null (no-op) file writer."""

    # Inherits `cache_dir` from base class


class NullWriter(FileWriterBase):
    """A Null (no-op) file writer implementation."""
```

2024-01-29 14:15 UTC, alafanechere requested changes

2024-01-29 14:15 UTC, alafanechere commented on airbyte-lib/airbyte_lib/caches/null.py
> +    so we insert as values instead.
I think this docstring is not up to date

2024-01-29 14:15 UTC, alafanechere commented on airbyte-lib/airbyte_lib/caches/null.py
> +        # Do nothing
I'd appreciate an explicit "return None"

2024-01-29 14:15 UTC, alafanechere commented on airbyte-lib/airbyte_lib/caches/null.py
> +    def _write_files_to_new_table(self, files: list[Path], stream_name: str, batch_id: str) -> str:
please change the type hint if none is returned here

2024-01-29 14:18 UTC, flash1293 commented
Based on the stated goal of this PR - the best you should be able to do is to just use `list(source.get_records())`. It's basically 

> with little or no slowdown from AirbyteLib, the file writer, and/or the SQL cache.

2024-04-20 23:04 UTC, natikgadzhi commented
I'm closing because I assume you already made this change in pyairbyte repo. If not, apologies! Seems like a huge lift to rebase and rename anyway.

2024-04-20 23:04 UTC, closed without merging