Source File: add fixed width file format support #34585
airbytehq/airbyte pull request #34678
Opened 2024-01-30 19:00 UTC by mjgatz

## What
*Resolving [#34585](https://github.com/airbytehq/airbyte/discussions/34585)*
*Adding support for fixed width files*

## How
*Adding pandas.read_fwf to the read_dataframe reader mapping*

## Pre-merge Actions
<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

2024-01-30 19:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=34678) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=34678) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: mjgatz<br/>:x: michael-greene-gravie<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=34678) it.</sub>

2024-02-06 11:43 UTC, lazebnyi requested changes
@marcosmarxm Need fix unit tests, integration and CAT tests. Also need fix QA check.

2024-02-06 14:42 UTC, mjgatz commented
@lazebnyi @marcosmarxm Anything I can do to help this process?

2024-02-10 01:36 UTC, lazebnyi approved these changes

2024-02-13 18:58 UTC, merged