Remove connector ops team
airbytehq/airbyte pull request #34867
Opened 2024-02-05 19:15 UTC by evantahler

```[tasklist]
### Tasks
- [x] `airbyte` Repo: Codeowners, Airbyte CI automations (https://github.com/airbytehq/airbyte/pull/34867)
- [x] `airbyte-Platform-Internal` Repo: Codeowners, etc (https://github.com/airbytehq/airbyte-platform-internal/pull/11081)
- [x] `workflow-actions` Repo: https://github.com/airbytehq/workflow-actions/pull/86
- [x] Remove/Archive Slack Team
- [x] Remove Github Team
- [ ] Remove Slack Group
```

2024-02-05 19:22 UTC, alafanechere requested changes

2024-02-05 19:22 UTC, alafanechere commented on .github/workflows/publish-command.yml
> +            Please reach out to the @dev-extensibility team if you need support in publishing a connector.
```suggestion
            Please reach out to the @airbytehq/connector-extensibility team if you need support in publishing a connector.
```

2024-02-05 19:22 UTC, alafanechere commented on airbyte-ci/connectors/pipelines/pipelines/airbyte_ci/connectors/publish/context.py
> +            message += "\ncc. <!subteam^dev-connector-extensibility>"
Does this work? I thought we had to figure the group id.

2024-02-05 19:22 UTC, alafanechere commented on airbyte-ci/connectors/pipelines/pipelines/airbyte_ci/connectors/publish/context.py
Please bump airbyte-ci version in `pyproject.toml` (+ changelog update in `README.md`) if you want this change to take affect following the merge of this PR

2024-02-05 19:22 UTC, alafanechere commented on .github/workflows/publish-command.yml
I think we can remove / disable this workflow as /publish is gone

2024-02-06 01:13 UTC, evantahler commented
FYI @natikgadzhi this PR tracks all the code changes I'm doing to wind down the connector ops team, if you ever want to change something.

2024-02-06 19:10 UTC, alafanechere approved these changes
Thank you for the changes 🙏

2024-02-06 19:10 UTC, alafanechere commented on airbyte-ci/connectors/pipelines/README.md
Are you using a specific markdown formatter locally?

2024-02-06 20:11 UTC, evantahler commented on airbyte-ci/connectors/pipelines/README.md
Just vscode 🤷

2024-02-06 20:42 UTC, merged