Vitalii/3453 Jira Source HTTP CDK
airbytehq/airbyte pull request #3488
Opened 2021-05-19 13:56 UTC by vitaliizazmic

## What
Migrate Jira Source to HTTP CDK

Closes #3453

2021-05-19 19:17 UTC, keu requested changes

2021-05-19 19:17 UTC, keu commented on airbyte-integrations/connectors/source-jira/source_jira/api.py
> +        yield from records
just `yield records` ?

2021-05-19 22:10 UTC, keu commented on airbyte-integrations/connectors/source-jira/setup.py
> +MAIN_REQUIREMENTS = ["airbyte-cdk", "requests", "pendulum"]
pin cdk~=0.1

2021-05-19 22:12 UTC, keu approved these changes
just small comment

2021-05-19 22:24 UTC, sherifnada requested changes
mostly LGTM with a few questions

2021-05-19 22:24 UTC, sherifnada commented on airbyte-integrations/connectors/source-jira/source_jira/source.py
> +            alive, error_msg = False, str(error)
```suggestion
            alive, error_msg = False, repr(error)
```

2021-05-19 22:24 UTC, sherifnada commented on airbyte-integrations/connectors/source-jira/source_jira/streams.py
> +    parse_response_root = ""
is this better than empty stirng? 

```suggestion
    parse_response_root = None
```

2021-05-19 22:24 UTC, sherifnada commented on airbyte-integrations/connectors/source-jira/source_jira/streams.py
> +            yield from super().read_records(stream_slice={"screen_id": screen["id"]}, **kwargs)
should this just call `read_tab_records`?

2021-05-19 22:24 UTC, sherifnada commented on airbyte-integrations/connectors/source-jira/source_jira/streams.py
> +        response_json = response.json()
we can just `yield response.json()` here right?

2021-05-19 22:24 UTC, sherifnada commented on airbyte-integrations/connectors/source-jira/source_jira/streams.py
> +        records = response_json if not self.parse_response_root else response_json.get(self.parse_response_root, [])
is `response_json` guaranteed to be a list?

2021-05-19 22:24 UTC, sherifnada commented on airbyte-integrations/connectors/source-jira/source_jira/streams.py
> +    def get_updated_state(self, current_stream_state: MutableMapping[str, Any], latest_record: Mapping[str, Any]) -> Mapping[str, Any]:
should this method instead be in the superclass?

2021-05-19 22:24 UTC, sherifnada commented on airbyte-integrations/connectors/source-jira/source_jira/streams.py
> +class IssueWorklogs(JiraStream):
should this be incremental?

2021-05-20 17:37 UTC, vitaliizazmic commented
/test connector=source-jira

2021-05-20 18:00 UTC, vitaliizazmic commented
/test connector=source-jira

2021-05-20 18:37 UTC, vitaliizazmic commented
/test connector=source-jira

2021-05-20 21:15 UTC, sherifnada approved these changes
One suggestion but otherwise LGTM

2021-05-20 21:15 UTC, sherifnada commented on airbyte-integrations/connectors/source-jira/source_jira/streams.py
> +    def get_updated_state(self, current_stream_state: MutableMapping[str, Any], latest_record: Mapping[str, Any]) -> Mapping[str, Any]:
```suggestion
    @abstractmethod
    def get_updated_state(self, current_stream_state: MutableMapping[str, Any], latest_record: Mapping[str, Any]) -> Mapping[str, Any]:
```

2021-05-20 21:15 UTC, sherifnada commented on airbyte-integrations/bases/standard-source-test/src/main/java/io/airbyte/integrations/standardtest/source/StandardSourceTest.java
> +      "airbyte/source-jira");
if we are using new test script then we don't need this or the build block in gradle

2021-05-21 12:07 UTC, merged