bug: set cdc flag in state
airbytehq/airbyte pull request #3497
Opened 2021-05-19 18:18 UTC by cgardens

## What
* @subodh1810 pointed out that we never actually set the `cdc` flag in the jdbc state. While this omission hasn't caused an actual bug (yet), it is super confusing. This PR adds a change to make sure that this flag gets set. It's definitely a stopgap until we consolidate our CDC code a little bit more intelligently into the rest of our jdbc abstraction.

2021-05-19 22:24 UTC, sherifnada reviewed
what is the function of the CDC flag?

2021-05-19 22:42 UTC, sherifnada approved these changes
nvm, looked at code. lgtm

2021-05-20 08:45 UTC, subodh1810 requested changes

2021-05-20 08:45 UTC, subodh1810 commented on airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSource.java
> +      stateManager.setIsCdc(true);
This is going to break syncs. In `airbyte-integrations/connectors/source-jdbc/src/main/java/io/airbyte/integrations/source/jdbc/JdbcStateManager.java` in the constructor we do 
```
 public JdbcStateManager(JdbcState serialized, ConfiguredAirbyteCatalog catalog) {
    this.cdcStateManager = new JdbcCdcStateManager(serialized.getCdcState());
    this.isCdc = serialized.getCdc();
    if (serialized.getCdc() == null) {
      this.isCdc = false;
    }

    pairToCursorInfo =
        new ImmutableMap.Builder<AirbyteStreamNameNamespacePair, CursorInfo>().putAll(createCursorInfoMap(serialized, catalog)).build();
  }
```

Which means `cdc` is already set to false when its null. Now in the `setIsCdc` method we have a check
 
```
  public void setIsCdc(boolean isCdc) {
    if (this.isCdc == null) {
      this.isCdc = isCdc;
    } else {
      Preconditions.checkState(this.isCdc == isCdc, "attempt to set cdc to {}, but is already set to {}.", isCdc, this.isCdc);
    }
  }
```
which would throw the error `java.lang.IllegalStateException: attempt to set cdc to {}, but is already set to {}. [true, false]`

2021-05-20 08:58 UTC, subodh1810 commented
Am curious how did the build pass? When I run `CdcPostgresSourceTest` with this change, 7 tests failed. Are these tests not run as part of CI?
<img width="1792" alt="Screenshot 2021-05-20 at 2 27 45 PM" src="https://user-images.githubusercontent.com/28527634/118950243-a414b780-b977-11eb-9eaa-1d270413f1fd.png">

2021-07-12 20:55 UTC, cgardens commented
@subodh1810 is there any follow up we should do here? i agree what i had in this PR isn't right. mostly looking to close this PR, but want to figure out if there's any outstanding issue I should create or if this was addressed in your CDC abstraction.

2021-07-12 20:55 UTC, closed without merging