[destination-bigquery] Update documentation to include mention of per table iam access rights
airbytehq/airbyte pull request #34988
Opened 2024-02-08 00:19 UTC by julienfouilhe

## What

This PR edits the documentation to clarify how BigQuery handles resets and how access rights should be set. 

## How

Adds a sentence in the troubleshooting section.

## 🚨 User Impact 🚨

None

2024-02-10 02:51 UTC, evantahler requested changes

2024-02-10 02:51 UTC, evantahler commented on docs/integrations/destinations/bigquery.md
> +- If you're using per-table permissions, it's important to note that the connector briefly deletes the final tables after a reset. This deletion is sufficient for IAM permissions granted on a single
```suggestion
- If you're using per-table permissions, it's important to note that the connector deletes the final tables after a reset. This deletion removes IAM permissions granted on a single table to be removed along with the table. You can set your permissions at the dataset level or use [authorized datasets/views](https://cloud.google.com/bigquery/docs/authorized-datasets) to access your Airbyte tables.  [Learn more here](/using-airbyte/core-concepts/typing-deduping)
```

2024-02-10 02:51 UTC, evantahler commented on docs/integrations/destinations/bigquery.md
> +- If you're using per-table permissions, it's important to note that the connector briefly deletes the final tables after a reset. This deletion is sufficient for IAM permissions granted on a single
It's not the 'temporary' that's the issue - it's that we actually delete the old table and then make a new one ;) 

I've added more docs about this here that we can link to - https://github.com/airbytehq/airbyte/pull/35124

2024-03-07 14:29 UTC, closed without merging

2024-03-07 14:29 UTC, marcosmarxm commented
Stale and partially resolved by https://github.com/airbytehq/airbyte/pull/34988#