destination-async-framework: move the state emission logic into GlobalAsyncStateManager
airbytehq/airbyte pull request #35240
Opened 2024-02-13 20:07 UTC by subodh1810

There is no issue for this. See slack [thread](https://airbytehq-team.slack.com/archives/C0624HL9UTU/p1707843108366429?thread_ts=1707513683.088909&cid=C0624HL9UTU)

2024-02-14 06:04 UTC, davinchia commented on airbyte-cdk/java/airbyte-cdk/core/src/main/java/io/airbyte/cdk/integrations/destination_async/buffers/MemoryAwareMessageBatch.java
>     * @return list of states that can be flushed
nit: change java doc.

2024-02-14 06:07 UTC, davinchia commented on airbyte-cdk/java/airbyte-cdk/core/src/main/java/io/airbyte/cdk/integrations/destination_async/buffers/MemoryAwareMessageBatch.java
> +    stateManager.flushStates();
Curious, does the locking break if we return the ids to flush and flush them in the FlushWorkers instead?

That way, all the actual action happens in the flush workers, and not in objects scattered around. Mainly a cleanliness suggestion.

2024-02-14 06:08 UTC, davinchia commented on airbyte-cdk/java/airbyte-cdk/core/src/main/java/io/airbyte/cdk/integrations/destination_async/state/GlobalAsyncStateManager.java
> +  public void flushStates() {
suggestion: what if `flushStates` took in an output record collector? This helps us prevent passing the record collector everywhere. Should help comprehension.

2024-02-14 06:10 UTC, davinchia commented on airbyte-cdk/java/airbyte-cdk/core/src/main/java/io/airbyte/cdk/integrations/destination_async/state/GlobalAsyncStateManager.java
>     * @return list of state messages with no more inflight records.
nit: update javadoc.

2024-02-14 06:14 UTC, davinchia approved these changes
Conditionally approval.

If I understand correctly, what we do here is centralise flushing into one class. Flushing itself is locked, so though many threads can call it, we prevent a race condition, which is good!

Most of my feedback is for readability. In the previous iteration, you'll see that all action happens in the FlushWorkers. This is intentional, since someone can read this class and understand most of what is going on. Signalling to another class is a fine pattern - my main suggestion is to keep the output record collector in one spot so it's clearer where writing mostly happens. This is just a suggestion.

What is a must-have, though non-blocking is to update the javadocs. Keeping them in sync will really have readability!

2024-02-14 20:49 UTC, gisripa requested changes

2024-02-14 20:49 UTC, gisripa commented on airbyte-cdk/java/airbyte-cdk/core/src/main/java/io/airbyte/cdk/integrations/destination_async/state/GlobalAsyncStateManager.java
> +  private static final Object LOCK = new Object();
static seems unnecessary ?

2024-02-14 20:49 UTC, gisripa commented on airbyte-cdk/java/airbyte-cdk/core/src/main/java/io/airbyte/cdk/integrations/destination_async/state/GlobalAsyncStateManager.java
> +    this.outputRecordCollector = outputRecordCollector;
Can we avoid holding a copy of outputRecordCollector at instance level and use only in flushStates ? This reduces the possibility of future abuse of this instance variable.

2024-02-15 16:59 UTC, gisripa approved these changes

2024-02-15 18:10 UTC, subodh1810 commented
/publish-java-cdk

2024-02-15 19:06 UTC, merged