Archive unpopular / unsupported destinations
airbytehq/airbyte pull request #35359
Opened 2024-02-16 17:47 UTC by evantahler

More information in the [doc](https://docs.google.com/document/d/1OL6vVaje5S1ajhXeSaGW3WKnvLik6g0ZDXnaNVDtAJs/edit)

2024-02-23 18:08 UTC, erohmensing requested changes
Blocking until we are sure that `archived` will not break the platform ([comment](https://airbytehq-team.slack.com/archives/C02TL38U5L7/p1708711028486249?thread_ts=1708624845.955359&cid=C02TL38U5L7)) if an archived connector makes its way into a registry for any reason.

2024-02-23 18:15 UTC, evantahler commented on airbyte-integrations/connectors/destination-cassandra/metadata.yaml
> +      enabled: true
... great catch! it should not have been. 712df7e824094f4b9719ba54ce29950044638dc4

2024-02-23 18:22 UTC, erohmensing commented on airbyte-integrations/connectors/destination-cassandra/metadata.yaml
> +      enabled: true
Thanks! Easy mistake to make - that's why I'm being so pushy on making sure that `archived` in the registry doesn't break platform, even though it hypothetically should not be a problem if we never publish an archived connector to a registry.

2024-02-26 17:41 UTC, evantahler commented
https://github.com/airbytehq/airbyte-platform-internal/pull/11405 is merged, so this should be ready to go!

2024-02-27 18:48 UTC, erohmensing commented on airbyte-integrations/connectors/destination-cassandra/metadata.yaml
>        enabled: false # hide Cassandra Destination https://github.com/airbytehq/airbyte-cloud/issues/2606
```suggestion
      enabled: false
```

2024-02-27 18:52 UTC, erohmensing approved these changes
Approving as PRs resolving the potential breaking of the platform are merged. 

Thanks for creating a PR to handle hiding the archived connectors from the UI if they make it into a catalog. Please go ahead and remove them from the LaunchDarkly flag after that is merged! 

There is some stuff we could do if we _really_ want to do this right, in that we probably would want to make cloud and oss both aware that all these connectors are archived, so that if a user is using a connector that is now archived, they can see that in their UI. That would however involve releasing all the connectors (potentially new versions since they last hit cloud), cutting an OSS release so that OSS users have that info too. That's probably not ideal, and what we talked about re: one large catalog with all the info about which registries a connector is available in and if a connector is archived, would probably better solve this problem. I don't expect you to do this, but wanted to raise it in case we are wondering why we don't see these connectors as archived in the UI.

2024-02-28 01:08 UTC, evantahler commented
/approve-and-merge reason="archiving destinations"

2024-02-28 01:09 UTC, octavia-approvington commented
Approve this <br/> ![imagine the commander saying yes](https://media2.giphy.com/media/McPX868ZmoAF7zNJa6/giphy.gif?cid=ecf05e47l4gpmzmv9wpg48fgu21m99n41ra1tq5inzrsobff&rid=giphy.gif&ct=g)

2024-02-28 01:09 UTC, octavia-approvington approved these changes

2024-02-28 01:09 UTC, merged