initial commit
airbytehq/airbyte pull request #35603
Opened 2024-02-24 00:58 UTC by bindipankhudi

## What
Resolves: https://github.com/airbytehq/PyAirbyte/issues/36 & part of https://github.com/airbytehq/PyAirbyte/issues/55

## How
Made following changes to the PyAirbyte docs 
- Replaced instances of AirbyteLib with PyAirbyte and update usage code 
- Updated architecture image 
- Added a PyAirbyte logo 
- Added Quickstarts section
- Removed reference.mdx

2024-02-24 00:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=35603) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=35603) before we can accept your contribution.<br/><hr/>**bindipankhudi** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=35603) it.</sub>

2024-02-25 17:05 UTC, aaronsteers requested changes
Small nits. Will apply those and then approve.

2024-02-25 17:05 UTC, aaronsteers commented on docs/using-airbyte/airbyte-lib/getting-started.mdx
> +* [PostGres (cache)](https://github.com/airbytehq/quickstarts/blob/main/airbyte_lib_notebooks/PyAirbyte_Postgres_Custom_Cache_Demo.ipynb)
```suggestion
* [Postgres (cache)](https://github.com/airbytehq/quickstarts/blob/main/airbyte_lib_notebooks/PyAirbyte_Postgres_Custom_Cache_Demo.ipynb)  
```

2024-02-25 17:05 UTC, aaronsteers commented on docs/using-airbyte/airbyte-lib/getting-started.mdx
> +* [Github](https://github.com/airbytehq/quickstarts/blob/main/airbyte_lib_notebooks/AirbyteLib_Github_Incremental_Demo.ipynb)
```suggestion
* [GitHub](https://github.com/airbytehq/quickstarts/blob/main/airbyte_lib_notebooks/AirbyteLib_Github_Incremental_Demo.ipynb) 
```

2024-02-25 17:07 UTC, aaronsteers approved these changes
Looks great - thanks, @bindipankhudi ! 


Approving, and expecting this will auto-merge after CI turns green again.

2024-02-25 17:10 UTC, merged

2024-02-25 17:54 UTC, bindipankhudi commented
Thanks for merging! Didn’t mean for u to make the changes :)

On Sun, Feb 25, 2024 at 9:07 AM aaronsteers ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Looks great - thanks, @bindipankhudi <https://github.com/bindipankhudi> !
>
> Approving, and expecting this will auto-merge after CI turns green again.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/airbytehq/airbyte/pull/35603#pullrequestreview-1899716779>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BF2EJSX66TCEUDAWTJISFEDYVNVUPAVCNFSM6AAAAABDXSCR46VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQOJZG4YTMNZXHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>