Source: Okta
airbytehq/airbyte pull request #3563
Opened 2021-05-24 08:18 UTC by grebessi

## What
Added new source to Okta.
This PR closes #2414

## How
Added support for the following schemas:
- Users
- Groups
- System Log

## Pre-merge Checklist
- [ ] *Run integration tests*
- [ ] *Publish Docker images*

2021-05-24 18:59 UTC, keu commented on airbyte-integrations/connectors/source-okta/build.gradle
> +    implementation files(project(':airbyte-integrations:bases:base-python').airbyteDocker.outputs)
should not be necessary anymore

2021-05-24 19:00 UTC, keu commented on airbyte-integrations/connectors/source-okta/integration_tests/catalog.json
> +}
newline

2021-05-24 19:00 UTC, keu commented on airbyte-integrations/connectors/source-okta/sample_files/catalog.json
> +}
nl

2021-05-24 19:01 UTC, keu commented on airbyte-integrations/connectors/source-okta/setup.py
> +    "airbyte-cdk",
bind version ~=0.1

2021-05-24 19:03 UTC, keu commented on airbyte-integrations/connectors/source-okta/source_okta/source.py
> +            'limit': 200,
lets move to class attribute

2021-05-24 19:04 UTC, keu commented on airbyte-integrations/connectors/source-okta/source_okta/source.py
> +            yield row
```suggestion
        yield from response.json()
```

2021-05-24 19:09 UTC, keu requested changes
minor changes

2021-05-25 07:23 UTC, keu approved these changes

2021-05-26 07:47 UTC, sherifnada approved these changes
Very small comments. Please bump and publish once you've addressed them. 

Also, please change the PR name to `🎉 New Source: Okta`

2021-05-26 07:47 UTC, sherifnada commented on airbyte-integrations/connectors/source-okta/sample_files/configure_catalog.json
> +{
this seems not to belong to this connector

2021-05-26 07:47 UTC, sherifnada commented on airbyte-integrations/connectors/source-okta/source_okta/source.py
> +    def page_size(self) -> int:
why is this not a hardcoded property e.g: `page_size = 200`?

2021-05-26 07:47 UTC, sherifnada commented on airbyte-integrations/connectors/source-okta/sample_files/catalog.json
> +      "sync_mode": "incremental",
this catalog used for testing should contain the cursor field and primary key for each stream

2021-05-26 07:55 UTC, sherifnada requested changes
Actually just realized a few things:
1. Which API token are you using? I thought Okta was an Oauth based source
2. Could you add the config to Github secrets, `ci_credentials.sh`, `test-command` and `publish-command.yml`? 
3. we need to add docs for this connector in the `docs/` directory. Could you pattern match off the existing connectors to do this? Also, we need to update `SUMMARY.md` to point to these docs.

2021-05-26 11:23 UTC, grebessi commented
> Actually just realized a few things:
> 
> 1. Which API token are you using? I thought Okta was an Oauth based source
> 2. Could you add the config to Github secrets, `ci_credentials.sh`, `test-command` and `publish-command.yml`?
> 3. we need to add docs for this connector in the `docs/` directory. Could you pattern match off the existing connectors to do this? Also, we need to update `SUMMARY.md` to point to these docs.

1. According to [the docs](https://developer.okta.com/docs/reference/api/authn/#primary-authentication), we can authenticate in 5 ways:
- Public Application
- [Trusted Application](https://developer.okta.com/docs/reference/api/authn/#primary-authentication-with-trusted-application)
- Activation Token
- Device Fingerprinting
- Password Expiration Warning
In this case, I did use `Trusted Application`. I used the token provided by `LastPass` [(Create the token docs)](https://developer.okta.com/docs/guides/create-an-api-token/create-the-token/)

2 and 3, I will start working on adding it.

2021-05-26 12:12 UTC, po3na4skld approved these changes

2021-06-01 16:04 UTC, sherifnada approved these changes
LGTM -- please publish and merge

2021-06-01 16:04 UTC, sherifnada commented on docs/integrations/README.md
> +|[Okta](./sources/oracle.md)| Beta |
```suggestion
|[Okta](./sources/okta.md)| Beta |
```

2021-06-01 18:58 UTC, grebessi commented
/publish connector=connectors/source-okta

2021-06-01 19:31 UTC, grebessi commented
/publish connector=connectors/source-okta

2021-06-01 19:54 UTC, grebessi commented
/publish connector=connectors/source-okta

2021-06-02 15:24 UTC, grebessi commented
/publish connector=connectors/source-okta

2021-06-02 16:52 UTC, grebessi commented
/publish connector=connectors/source-okta

2021-06-02 17:03 UTC, merged