Fix tags in metadata files for migrated community connectors
airbytehq/airbyte pull request #35725
Opened 2024-02-29 15:40 UTC by DanyloGL

Some of migrated to low-code community connectors had no updated language tags in metadata file.
List of connectors:

- source-braintree
- source-everhour
- source-klaus-api
- source-plaid
- source-unleash

## What
Language tags of connectors were fixed
## How
Was added language tag `low-code` in metadata files of listed above connectors.

## 🚨 User Impact 🚨
No breaking changes

2024-02-29 17:20 UTC, lazebnyi requested changes

2024-02-29 17:20 UTC, lazebnyi commented on airbyte-integrations/connectors/source-braintree/metadata.yaml
> +    - language:low-code
we need leave only one tag 

language:low-code or language:python should be presented in metadata file

2024-03-05 17:17 UTC, lazebnyi approved these changes
lgtm

2024-03-06 12:52 UTC, DanyloGL commented
/approve-and-merge reason="fixing language tags for community connectors, no testing required"

2024-03-06 12:52 UTC, octavia-approvington commented
It's time <br/> ![fine lets go](https://media1.giphy.com/media/yaR8Dux1s0fAI/giphy.gif?cid=ecf05e47a0zmzctsyu3sqzbajb4aitlkuzrr9vxk70s7lw1r&rid=giphy.gif&ct=g)

2024-03-06 12:52 UTC, octavia-approvington approved these changes

2024-03-06 12:52 UTC, merged