✨ Source Gainsight PX: add new stream `Engagement`
airbytehq/airbyte pull request #35797
Opened 2024-03-04 18:34 UTC by honggyu420

## What
Adds new stream [`engagement`](https://gainsightpx.docs.apiary.io/#reference/engagement/get-engagements)

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
None, adds new stream to existing connector

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/resources/pull-requests-handbook)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:generateScaffolds` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

<details><summary><strong>Updating the Python CDK</strong></summary>

### Airbyter

Before merging:
- Pull Request description explains what problem it is solving
- Code change is unit tested
- Build and my-py check pass
- Smoke test the change on at least one affected connector
   - On Github: Run [this workflow](https://github.com/airbytehq/airbyte/actions/workflows/connectors_tests.yml), passing `--use-local-cdk --name=source-<connector>` as options
   - Locally: `airbyte-ci connectors --use-local-cdk --name=source-<connector> test`
- PR is reviewed and approved
      
After merging:
- [Publish the CDK](https://github.com/airbytehq/airbyte/actions/workflows/publish-cdk-command-manually.yml)
   - The CDK does not follow proper semantic versioning. Choose minor if this the change has significant user impact or is a breaking change. Choose patch otherwise.
   - Write a thoughtful changelog message so we know what was updated.
- Merge the platform PR that was auto-created for updating the Connector Builder's CDK version
   - This step is optional if the change does not affect the connector builder or declarative connectors.

</details>

2024-03-04 18:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=35797) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=35797) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=35797) it.</sub>

2024-03-04 21:10 UTC, honggyu420 commented on airbyte-integrations/connectors/source-gainsight-px/source_gainsight_px/manifest.yaml
> +      extractorPath: "featureMatchEvents"
this is not a typo. Actually stated in the docs like this
https://gainsightpx.docs.apiary.io/#reference/segmentmatchevent/v1eventssegmentmatch/get-segment-match-events

2024-03-07 04:03 UTC, natikgadzhi commented
Hey @honggyu420, thank you for the contribution!

This connector needs a little bit of maintenance:
1. Let's switch away from custom Docker image. 
2. Let's switch from setup.py to Poetry
3. Upgrade to latest `airbyte_cdk`

It seems that `source-gainsight-px` only uses declarative syntax without any custom Python components, so we could also pass the connector through the Connector Builder UI, that would inline the schemas and reduce the amount of files out here, but it would kill the ref blocks (and duplicate their contents). 

I will try and get through the 1-3 points and record a little demo of how to do it for this and other connectors.

2024-03-17 05:55 UTC, natikgadzhi commented
@honggyu420 @honggyu-rr I've rebased the PR and added the commit to move to base image in https://github.com/airbytehq/airbyte/pull/36221 — you can cherry-pick my last commit into this PR and rebase as well. 

If we don't have a sandbox account for gainsight-px (not sure), we might need them to get this merged.

2024-03-17 20:23 UTC, natikgadzhi commented
I've also commmitted the Poetry bump — I think it might be easier for me to merge my PR — you will still get the contribution score since I cherry-picked your commits. Good with you, @honggyu-rr?

2024-03-19 15:49 UTC, marcosmarxm requested changes
Please run the `airbyte-ci format all fix` to fix all files.

2024-03-19 15:49 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-gainsight-px/metadata.yaml
> +  dockerImageTag: 0.1.1
New stream is a minor update. Please update to 0.2.0

2024-03-19 15:49 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-gainsight-px/integration_tests/configured_catalog.json
> +}
EOF

2024-06-12 16:42 UTC, marcosmarxm commented
Closed as inactive.

2024-06-12 16:42 UTC, closed without merging