fmt
airbytehq/airbyte pull request #36050
Opened 2024-03-14 05:35 UTC by jbfbell

2024-03-14 05:35 UTC, jbfbell commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/36050?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#36050** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/36050?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#36047** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/36047?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#36048](https://github.com/airbytehq/airbyte/pull/36048) <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/36048?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @jbfbell and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-12 11:44 UTC, katmarkham requested changes

2024-04-12 11:44 UTC, katmarkham commented on docs/integrations/destinations/mssql-migrations.md
> +This version removes the option to use "normalization" with MS SQL Server. It also changes
MS SQL Server> either Microsoft SQL Server or MSSQL Server

2024-04-12 11:44 UTC, katmarkham commented on docs/integrations/destinations/mssql-migrations.md
> +Airbyte will only produce the ‘raw’ v2 tables, which store all content in JSON. These changes remove
change it to "raw"

2024-04-12 11:44 UTC, katmarkham commented on docs/integrations/destinations/mssql-migrations.md
> +of Destinations V2 (including final tables), click [[https://github.com/airbytehq/airbyte/discussions/37010]]
line 10/11: these should also be changed to either MSSQL Server or Microsoft SQL Server

2024-04-12 11:44 UTC, katmarkham commented on docs/integrations/destinations/mssql-migrations.md
> +For each stream, you could perform the following query to migrate the data from the old raw table
s/could/should

2024-04-12 11:44 UTC, katmarkham commented on docs/integrations/destinations/mssql-migrations.md
> +`Raw Table Schema Name`.
45/49 these should also be changed to either MSSQL Server or Microsoft SQL Server

2024-04-12 11:44 UTC, katmarkham commented on docs/integrations/destinations/mssql-migrations.md
> +where as:
Where as

2024-04-12 11:44 UTC, katmarkham commented on docs/integrations/destinations/mssql-migrations.md
> +Writes to: `raw_data.default_raw__stream_my_stream`
take out :

2024-04-22 18:13 UTC, katmarkham approved these changes

2024-04-22 20:23 UTC, merged

2024-04-24 13:23 UTC, cohenj20 commented
Am I wrong or does the MSSQL destination now only create raw airbyte tables with an `_airbyte_data` column containing a JSON blob of all source data? Is there really no way anymore to have airbyte deliver tabular source data to MSSQL?

2024-04-24 15:05 UTC, cohenj20 commented
I understand. Do you have a rough estimate on when users could expect this enhancement to be shipped? And does Airbyte have a plan to certify this destination?

2024-04-24 15:21 UTC, evantahler commented
We do not have plans to certify the destination-mssql at this time.  That said, as this is a community connector, if you are interested in adding those features, let us know

2024-05-18 04:06 UTC, brywhi commented
This is one of my most heavily used destinations. Normalization is also important for me- I'll have to camp out on an old version for a while it seems.