✨ [source-google-drive] add `id` to the `URI`
airbytehq/airbyte pull request #36266
Opened 2024-03-19 12:01 UTC by Marcus0086

### This update will add id to the uri with a delimeter `::name::` for splitting id and name.

* To avoid making changes in the airbyte_cdk, I added id to the uri only without breaking `glob` patterns by keeping file name as the suffix

2024-03-19 15:35 UTC, marcosmarxm commented
Thanks for the contribution @Marcus0086 I added it to the connector team backlog to prioritize in future sprints. I don't have much context for source google drive to give you more inputs if the change is valid or not. We need to wait for them to make this review.

2024-03-20 19:10 UTC, Marcus0086 commented
> Thanks for the contribution @Marcus0086 I added it to the connector team backlog to prioritize in future sprints. I don't have much context for source google drive to give you more inputs if the change is valid or not. We need to wait for them to make this review.

No issues @marcosmarxm. 
Actually I am running a self hosted airbyte container and wanted to make changes to the google drive source to add id to it. I added it and built the source with dev version and used that only for one of my requirement that needs file id.

2024-03-27 18:32 UTC, marcosmarxm requested changes
@Marcus0086 I need you to also bump the connector version in the metadata file, pyproject.toml run poetry lock and update the changelog entry.

2024-05-01 12:19 UTC, marcosmarxm commented
Closed as inactive @Marcus0086 let me know if you want to continue the change.

2024-05-01 12:19 UTC, closed without merging