Skip review-requirements check on forks (no org team check perms)
airbytehq/airbyte pull request #36370
Opened 2024-03-21 21:27 UTC by aaronsteers

This was cherry-picked from the PR:

- https://github.com/airbytehq/airbyte/pull/36367

This skips membership checks when on a fork, where don't have permissions to do so.

2024-03-22 08:56 UTC, alafanechere requested changes
I think it'd be cleaner to discard the use of `${{ secrets.OCTAVIA_4_ROOT_ACCESS}}` and replace it with `${{ GITHUB_TOKEN}}`
[We shall give the token the right set of read permissions](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/).
`GITHUB_TOKEN` for runs on `fork`[ do have read permissions](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/), so they likely be able to `read:org`.

2024-04-19 03:47 UTC, aaronsteers commented
> I think it'd be cleaner to discard the use of `${{ secrets.OCTAVIA_4_ROOT_ACCESS}}` and replace it with `${{ GITHUB_TOKEN}}` [We shall give the token the right set of read permissions](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/). `GITHUB_TOKEN` for runs on `fork`[ do have read permissions](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/), so they likely be able to `read:org`.

Circling back after a while...

@alafanechere - docs seems to suggest that GITHUB_TOKEN won't be enough.

https://github.com/tspascoal/get-user-teams-membership?tab=readme-ov-file#requirements

> In order to use this action you need to use a [personal access token] with read:org [scope](https://docs.github.com/en/developers/apps/scopes-for-oauth-apps#available-scopes) (so the builtin in [GITHUB_TOKEN](https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token) is not enough)

Can we accept this PR as a step in the right direction, and continue to iterate from here? My understanding is that my proposed update is actually in line with the intended logic of the condition that is being replace.

2024-04-20 23:22 UTC, natikgadzhi approved these changes
LGTM to me

2024-04-22 19:03 UTC, aaronsteers commented
@alafanechere - This is currently blocked on your review. Wdyt of continuing with this increment and then we can continue to tune in future iterations?

2024-04-23 17:42 UTC, merged