Fix the `fields` data type to include the `id` and `value`
airbytehq/airbyte pull request #36388
Opened 2024-03-22 14:19 UTC by mohamagdy

2024-03-22 18:20 UTC, marcosmarxm commented
@mohamagdy please update the pull request description. Can you link the Zendesk documentation showing the field is valid? Did you run tests confirming the API actually return these values?

2024-03-25 08:44 UTC, mohamagdy commented
@marcosmarxm thanks for taking a look into this PR. Unfortunately, I can't find the `fields` field in Zendesk documentation here https://developer.zendesk.com/api-reference/ticketing/tickets/tickets/#json-format. And yes, I can see the `fields` field returned from the API. What I noticed is that the values of the `custom_fields` and `fields` are the same (maybe this was for my case only). Maybe the `fields` and `custom_fields` are aliases, not sure 😕

2024-03-25 15:31 UTC, marcosmarxm commented
@mohamagdy any chance to contact Zendesk to make clear this distinction? Would be quite helpful if you could this :)

2024-04-02 09:40 UTC, mohamagdy commented
@marcosmarxm I asked Zendesk Customer Service and they pointed me to this page https://support.zendesk.com/hc/en-us/articles/4408886739098-About-ticket-fields saying that the `fields` field should contain the Standard Fields but the `custom_fields` should contain the Custom Fields.

2024-04-10 16:41 UTC, marcosmarxm requested changes
Small change than ready to go.

2024-04-10 16:41 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-zendesk-support/source_zendesk_support/schemas/shared/tickets.json
> +        "type": ["null", "object"]
```suggestion
        "type": ["null", "object"],
        "additionalProperties": true
```

2024-04-22 16:11 UTC, mohamagdy commented on airbyte-integrations/connectors/source-zendesk-support/source_zendesk_support/schemas/shared/tickets.json
> +        "type": ["null", "object"]
Changed

2024-04-25 10:10 UTC, lazebnyi approved these changes
lgtm

After @marcosmarxm approve can be merged

2024-04-25 11:27 UTC, marcosmarxm approved these changes

2024-04-25 21:03 UTC, merged