🐛 Source Quickbooks: Update missing stream props and add token refresh udpater
airbytehq/airbyte pull request #36389
Opened 2024-03-22 14:20 UTC by henriblancke

## Changed
* Added some missing properties to to `bills`, `deposits` and `journal_entries` streams
* Updated `manifest.json` to include the `refresh_token_updater` so new refresh tokens get picked up and stored in config

2024-03-29 18:48 UTC, marcosmarxm requested changes
Some small details. I need to run tests but the change looks good.

2024-03-29 18:48 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-quickbooks/source_quickbooks/schemas/bills.json
> +                "type": ["null", "object"]
Please add `additionalProperties: true` for both cases.

2024-03-29 18:48 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-quickbooks/source_quickbooks/schemas/journal_entries.json
> +                "type": ["null", "object"]
Same here.

2024-04-11 12:20 UTC, marcosmarxm commented
Having a hard time running tests to release this change. Hope to get something today/tmw

2024-04-11 13:02 UTC, marcosmarxm approved these changes

2024-04-11 14:22 UTC, merged

2024-06-21 06:49 UTC, niteshsharoff commented
@henriblancke I have a quickbooks/invoices stream running daily. My initial pull is successful but the day after it fails. I'm on v3.0.3 running airbyte cloud and my error log is as shown below.

Any ideas why this would happen? It almost feels like the refresh token isn't stored or used when the stream loads. I set the token expiry to be 1h from sync (UTC) so the next time it runs (tomorrow) theoretically it should renew the token and sync + store the new refresh token - not too sure what I'm doing wrong.

<img width="400" alt="image" src="https://github.com/airbytehq/airbyte/assets/2419888/9c56b029-705a-43ae-96c1-d2131c745af9">



    yield from self.retriever.read_records(self.get_json_schema(), stream_slice)
    File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 323, in read_records
      for stream_data in self._read_pages(record_generator, self.state, stream_slice):
    File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 287, in _read_pages
      response = self._fetch_next_page(stream_state, stream_slice, next_page_token)
    File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 262, in _fetch_next_page
      return self.requester.send_request(
    File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 454, in send_request
      headers=self._request_headers(stream_state, stream_slice, next_page_token, request_headers),
    File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 308, in _request_headers
      headers = self._get_request_options(
    File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 292, in _get_request_options
      auth_options_method(),
    File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 56, in get_auth_header
      return {"Authorization": f"Bearer {self.get_access_token()}"}
    File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/oauth.py", line 233, in get_access_token
      new_access_token, access_token_expires_in, new_refresh_token = self.refresh_access_token()
    File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/oauth.py", line 248, in refresh_access_token
      response_json = self._get_refresh_access_token_response()
    File "/usr/local/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
      ret = target(*args, **kwargs)
    File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 132, in _get_refresh_access_token_response
      response.raise_for_status()
    File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
      raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer
    2024-06-21 04:24:27 ERROR i.a.w.i.VersionedAirbyteStreamFactory(internalLog):304 - Check failed

2025-01-17 16:52 UTC, JCatalystIQ commented
I am still running into this issue. Can we confirm this is fixed? I am seeing the same exact activity as the above question/problem?