Destination snowflake: Depend on published cdk artifact
airbytehq/airbyte pull request #36461
Opened 2024-03-25 20:00 UTC by edgao

code changes in https://github.com/airbytehq/airbyte/pull/36396; forgot to publish cdk >.>

2024-03-25 21:13 UTC, jbfbell requested changes

2024-03-25 21:13 UTC, jbfbell commented on airbyte-integrations/connectors/destination-snowflake/build.gradle
> +    cdkVersionRequired = '0.26.2'
`0.27.2` ?

2024-03-25 21:26 UTC, jbfbell approved these changes

2024-03-25 21:30 UTC, edgao commented
/publish-java-cdk

2024-03-26 10:50 UTC, alafanechere commented
@edgao [I ran the test on a pre-release version of airbyte-ci ](https://github.com/airbytehq/airbyte/actions/runs/8434576668/job/23098087586) which is likely fixing the problem you had in using the latest CDK . The airbyte-ci PR is here: https://github.com/airbytehq/airbyte/pull/36480

2024-03-26 15:16 UTC, edgao commented
/publish-java-cdk

2024-03-26 16:35 UTC, merged