source-paypal-transaction: schema descriptions
airbytehq/airbyte pull request #36654
Opened 2024-03-29 00:10 UTC by bleonard

2024-03-29 04:56 UTC, natikgadzhi approved these changes
LGTM. Connector version increment check freaks out, but this is fine. Good to merge in the morning.

2024-04-21 05:02 UTC, bleonard commented
Seems likely there were other updates on the master branch. Have to mess around with the version probably.

2024-04-22 10:02 UTC, bazarnov approved these changes

2024-04-22 10:02 UTC, bazarnov commented
@bleonard I was able to bump the CDK version last week for the `source-paypal`, re-base and merge with master, should resolve the conflicts.

2024-04-25 04:54 UTC, bleonard commented
rebased!

2024-04-25 09:43 UTC, bazarnov requested changes

2024-04-25 09:43 UTC, bazarnov commented on airbyte-integrations/connectors/source-paypal-transaction/pyproject.toml
> +airbyte-cdk = "0.82.0"
Why would we pin the versions again?

2024-05-07 11:15 UTC, lazebnyi approved these changes

2024-05-07 13:28 UTC, bazarnov approved these changes

2024-05-07 13:32 UTC, merged