add guidance on writing a good spec
airbytehq/airbyte pull request #3669
Opened 2021-05-27 17:45 UTC by cgardens

## What
* Was trying to close out some old issues. Noticed this one: https://github.com/airbytehq/airbyte/issues/454. Realized we should in general give some guidance on what a "good" spec looks like.

2021-05-27 18:04 UTC, sherifnada requested changes

2021-05-27 18:04 UTC, sherifnada commented on docs/contributing-to-airbyte/building-new-connector/best-practices.md
> +5. Specify the order of the fields so that the user has to input data in a sequence that is intuitive.
can you add an example for each of these points using a code block? Also add something about secrets?

2021-06-03 00:35 UTC, jrhizor commented on docs/contributing-to-airbyte/building-new-connector/best-practices.md
> +### Spec.json
```suggestion
### Spec
```

2021-09-27 17:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=3669) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=3669) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=3669) it.</sub>

2022-03-13 21:54 UTC, closed without merging