[source-bing-ads] add reports_end_date field to Bing Ads connector
airbytehq/airbyte pull request #36784
Opened 2024-04-03 11:00 UTC by vytautasnord

Issue raised: https://github.com/airbytehq/airbyte/issues/33351

In this pull request, the option for an end date in reports has been implemented. Now, it's possible to resynchronize data for a specific period without the need to load all data until the current date.

The implemented reports_end_date field is optional, and the main change is as follows:
**Previously:**
`report_time.CustomDateRangeEnd = self.get_request_date(reporting_service, datetime.utcnow())`
**Now:**
`report_time.CustomDateRangeEnd = self.get_request_date(reporting_service, end_date)`, where end_date is the date specified in the specifications, or datetime.utcnow() if not defined.

2024-04-08 17:25 UTC, marcosmarxm commented
Do you have a link to Bing documentation showing the option of end date for the reports endpoints?
Is available to all reports and custom ones?

2024-04-09 14:54 UTC, vytautasnord commented
@marcosmarxm Documentation link with End Date: https://learn.microsoft.com/en-us/advertising/reporting-service/reporttime?view=bingads-13.

The end field is currently implemented in the current Bing Ads connector. However, its value is set to datetime.utcnow(). Therefore, I have made a change to retrieve this value from the source configuration.

2024-04-23 12:27 UTC, vytautasnord commented
@marcosmarxm any update about this one?

2024-04-30 13:07 UTC, artem1205 requested changes

2024-05-06 17:03 UTC, marcosmarxm commented
@vytautasnord, could you please check the last review comment?

2024-05-28 12:32 UTC, vytautasnord commented on airbyte-integrations/connectors/source-bing-ads/source_bing_ads/report_streams.py
> +                return pendulum.from_timestamp(stream_state[account_id][self.cursor_field])
Hi @artem1205 ,
Sorry for the late response. This `get_end_date` function isn't really necessary here. It's sufficient to set the end_date from `client.reports_end_date` to run the report for a specific date range.

2024-06-12 14:01 UTC, vytautasnord commented on airbyte-integrations/connectors/source-bing-ads/source_bing_ads/report_streams.py
> +                return pendulum.from_timestamp(stream_state[account_id][self.cursor_field])
@artem1205 @marcosmarxm Could you please review this PR again?

2024-08-19 11:20 UTC, vytautasnord commented
Hi @marcosmarxm  @artem1205 

I hope you're doing well. Could you please take a look at this MR again when you have a moment? Recently, I encountered an issue where I needed to extract BingAds data for a specific period, and the reports_end_date functionality would have been really helpful.

Thank you in advance for your time and assistance!

2024-10-28 09:01 UTC, closed without merging

2025-03-04 08:10 UTC, tautvydas-v commented
@marcosmarxm Can this be reviewed once again? I see that the MR should work, at least in our use case, so not sure what's the progress here