✨Source Primetric: Migrate Python CDK to Low-code CDK
airbytehq/airbyte pull request #36957
Opened 2024-04-10 07:29 UTC by btkcodedev

## What
*Migrating Source Primetric to Low-Code CDK*
Closes airbytehq/airbyte-internal-issues#7029

## How
*Developed using (Configuration Based Source) low-code CDK*

## Recommended reading order
1. `spec.yaml`
2. `manifest.yaml`
3. `schemas/*`

## Tests

<details open><summary><strong>Integration & Acceptance</strong></summary>

 - Build Successfull
 
![image](https://github.com/airbytehq/airbyte/assets/47392334/f7d621d3-ee01-4e8f-b832-b96de94f10e0)

</details>

## 🚨 User Impact 🚨
- Spec Breaking changes, migration to low-code

2024-04-25 09:38 UTC, askarpets requested changes
Good job! Please also add unit tests back where possible

2024-04-25 09:38 UTC, askarpets commented on airbyte-integrations/connectors/source-primetric/acceptance-test-config.yml
> +            bypass_reason: Stream cannot be seeded with sandbox credentails
```suggestion
            bypass_reason: Stream cannot be seeded with sandbox credentials
```

2024-04-25 09:38 UTC, askarpets commented on airbyte-integrations/connectors/source-primetric/acceptance-test-config.yml
> +            bypass_reason: Stream cannot be seeded with sandbox credentails
Same for the next two

2024-04-25 15:35 UTC, btkcodedev commented
@askarpets All changes done, Updated docs, CI green

2024-04-25 18:27 UTC, askarpets commented on airbyte-integrations/connectors/source-primetric/source_primetric/manifest.yaml
> +              type:
This should be
```
type:
    - "null"
    - integer
```

2024-04-25 18:28 UTC, askarpets requested changes
@btkcodedev thanks for the updates, left one comment and please add unit tests back

2024-04-29 18:34 UTC, btkcodedev commented on airbyte-integrations/connectors/source-primetric/source_primetric/manifest.yaml
> +              type:
Done

2024-04-29 18:34 UTC, btkcodedev commented
Tests fixed and CI green
Please continue merging process :bow:

2024-04-29 18:51 UTC, btkcodedev commented
@askarpets, the credential trail period is almost over. Please review and merge it as soon as possible 🙏.

2024-04-30 10:18 UTC, askarpets approved these changes
@btkcodedev thanks for all updates you've made!

2024-05-03 21:03 UTC, girarda approved these changes

2024-05-03 21:03 UTC, merged