Add new columns for AB tests on lemlist activities.json
airbytehq/airbyte pull request #37100
Opened 2024-04-12 15:52 UTC by tlfbrito

Add new columns (`stepTested` and `sequenceTested`)

2024-04-12 15:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=37100) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=37100) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=37100) it.</sub>

2024-04-15 16:55 UTC, marcosmarxm requested changes
Can you bump the metadata version and the changelog entry in docs?

2024-04-15 21:33 UTC, tlfbrito commented
> Can you bump the metadata version and the changelog entry in docs?

Thanks for the review @marcosmarxm

2024-04-26 16:47 UTC, marcosmarxm commented
Running tests 🚀 ⌛

2024-04-30 18:06 UTC, marcosmarxm approved these changes

2024-04-30 18:27 UTC, merged