🎉 New Source: SingleStore
airbytehq/airbyte pull request #37337
Opened 2024-04-16 12:12 UTC by oyeliseiev-ua

Developing new connector for the source: SingleStore
Resolves: #35871

2024-04-16 12:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=37337) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=37337) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=37337) it.</sub>

2024-04-24 12:38 UTC, marcosmarxm commented
Hi @oyeliseiev-ua, 
Thank you for creating the Singlestore connector. Currently, we're not accepting new Java source-based connectors for the project. However, you can still build and run them locally, or publish them on Dockerhub for your clients to use as custom connectors. 
Another option is to contact Teo Gonzalez in Airbyte Slack to discuss releasing this connector as a partner-supported one. 
Let me know your thoughts.

2024-04-25 13:49 UTC, oyeliseiev-ua commented
Hi, @marcosmarxm,
Thank you. We contacted Teo Gonzalez, he is aware of this connector development.

2024-06-04 19:21 UTC, marcosmarxm requested changes
Connector looks good @oyeliseiev-ua there is an internal validation it is not passing I need to investigate further.

2024-06-06 12:35 UTC, marcosmarxm approved these changes
Thanks @oyeliseiev-ua

2024-06-06 12:35 UTC, merged

2024-06-06 14:51 UTC, oyeliseiev-ua commented
Thank you! @marcosmarxm Will be you able to check destination connector as well? https://github.com/airbytehq/airbyte/pull/38600