:tada: New Source: Awtomic
airbytehq/airbyte pull request #37342
Opened 2024-04-16 13:59 UTC by saadatqadri

2024-04-16 14:13 UTC, natikgadzhi requested changes
Hey @saadatqadri, thank you for the new connector! 👏🏼 

There are a few new requirements (I'm working on writing them down) that we need to get through to be able merge this:
1. Use the latest `baseImage` in `metadata.yaml`. Current is 1.2.0 I believe. 
2. Remove `setup.py` and `requirements`, use Poetry instead. There are several new examples of this, you can use `source-slack` as one.
3. Schemas need to be inlined into the manifest. The easiest way to do this is to open this connector in connector builder and run test reads, this will regenerate schemas in the yaml file itself. Export it and commit it back.
  - This should also update the CDK version to bump from 0.57 to 0.87.6+

Ideally, we would love to have a sandbox account for the source to be able to run connector acceptance tests with records. Do you think you could provide one? If so, let's figure out how you could send it over in a secure way.

2024-04-16 14:13 UTC, natikgadzhi commented on airbyte-integrations/connectors/source-awtomic/integration_tests/sample_config.json
> +  "fix-me": "TODO"
You might want to remove this

2024-04-16 14:13 UTC, natikgadzhi commented on airbyte-integrations/connectors/source-awtomic/integration_tests/sample_state.json
> +{
If you're not using the file, remove it. Are all streams full refresh only? If some are incremenental, pleae add test states.

2024-04-16 14:13 UTC, natikgadzhi commented on airbyte-integrations/connectors/source-awtomic/main.py
> +if __name__ == "__main__":
`main.py` should invoke `run.py` as in `source-slack`. That's required for the connector to be published to pypi as a package and be available in `pyairbyte`.

2024-04-16 14:13 UTC, natikgadzhi commented on airbyte-integrations/connectors/source-awtomic/metadata.yaml
> +      - localhost # Please change to the hostname of the source.
Not cool, please set the correct hosts.

2024-04-16 14:13 UTC, natikgadzhi commented on airbyte-integrations/connectors/source-awtomic/metadata.yaml
> +  releaseDate: TODO
Please set a release date.

2024-04-16 14:13 UTC, natikgadzhi commented on airbyte-integrations/connectors/source-awtomic/setup.py
> +    "airbyte-cdk~=0.1",
CDK should be unpinned in `pyproject.toml`, to `^0`.

2024-04-16 14:48 UTC, saadatqadri commented
@natikgadzhi i'll close this and re-create the PR with the recommendations.

2024-04-24 12:08 UTC, marcosmarxm commented
@saadatqadri why not make new commits?

2024-04-24 12:09 UTC, marcosmarxm commented
@saadatqadri any return about 
> Ideally, we would love to have a sandbox account for the source to be able to run connector acceptance tests with records. Do you think you could provide one? If so, let's figure out how you could send it over in a secure way.

2024-04-24 12:44 UTC, saadatqadri commented
@marcosmarxm working on refactoring. Slack ok to send over test API keys

2024-06-05 13:34 UTC, marcosmarxm commented
@saadatqadri do you still want to continue this work?

2024-06-06 01:21 UTC, saadatqadri commented
@marcosmarxm had some success using the Airbyte builder for this source. closing PR for now.

2024-06-06 01:21 UTC, closed without merging