[destination-astra] Explicit projection when reading from Astra DB
airbytehq/airbyte pull request #38181
Opened 2024-05-14 09:06 UTC by hemidactylus

## What

In view of upcoming changes in the Astra DB Data API, this PR explicitly sets a projection every time a `find` command is executed, in order to ensure all necessary fields of the document are returned by the API.

## How
The `find_query["projection"]` field is always set during the `find_documents` method body.

## Review guide

`astra_client.py` : added and else clause to ensure the projection is always set.

## User Impact

When a future version of the Data API will start excluding the `$vector` field by default, with this PR the users will not be impacted by any missing field.

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌

2024-05-14 16:28 UTC, marcosmarxm requested changes
Hello @hemidactylus can you run `poetry lock` to update dependencies, update version in the metadata.yaml file and in the doc changelog entry (docs/integrations/destinations/astra.md).

2024-05-16 08:29 UTC, hemidactylus commented
@marcosmarxm Done. Thank you!

2024-06-05 12:33 UTC, marcosmarxm approved these changes

2024-06-05 12:51 UTC, merged

2024-06-05 17:58 UTC, marcosmarxm commented
Hello 👋 , your feedback matters a lot to us. Can you spare just 3 minutes to complete a [survey](https://form.typeform.com/to/DOBqejte)? We're dedicated to making the contributor experience even better, and your input is key to achieving excellence. Thank you for helping us improve!