increase default timeout
airbytehq/airbyte pull request #38355
Opened 2024-05-20 18:09 UTC by hackathon12344

## What
Original github source code had issue with elastic search connector timeout after 30k milliseconds. 

## How
This PR increases this default timeout at clientBuilder to 30k*100k millisecs.

## Review guide
the clientbuilder in the Elastic search connection builder sets this default value and this pr increases this timeout. 

## User Impact
Longer timeout for elastic search scrolls in the default client.

## Can this PR be safely reverted and rolled back?
- [x ] YES 💚
- [ ] NO ❌

2024-05-20 18:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=38355) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=38355) before we can accept your contribution.<br/><hr/>**Shailesh** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=38355) it.</sub>

2024-05-20 18:15 UTC, evantahler commented
That's a really long timeout... like 34 days.  That's probably too long.

2024-05-20 19:11 UTC, evantahler reviewed
This change also only applies to the connection when a custom SSL certificate is in use.  I would imagine the change should be applied to the `clientBuilder` in all cases?

2024-05-20 19:13 UTC, evantahler requested changes
Suggestions for improvement:
* apply the `clientBuilder.setSocketTimeout` changes such that they apply regardless of if a custom SSL certificate is in use
* rather than choose a single large value for the timeout, use the connector's SPEC options to make this configurable, and start with a much smaller default (perhaps 30min, which is the default Elasticsearch chose).
* Update the connector's version, metadata, and docs, so that a new version can be published

2024-05-20 19:57 UTC, hackathon12344 commented
> That's a really long timeout... like 34 days. That's probably too long.

The timeout for SSL was specific to my local environment hence I put there. But I see your point and have moved it outside this block. I have reduced it to 1 hour. The default 30 seconds was not enough for elastic search scroll records to scroll through large results of data. I am not sure if this 1 hour will work either. Hence, I put a random large number of 1 day and 34 days before it. I think we can test it and see. 

Spec options - That makes sense to pass this as a configurable value. Let me check the spec file on how to achieve this.

2024-05-20 20:02 UTC, hackathon12344 commented
>     * Update the connector's version, metadata, and docs, so that a new version can be published

Thanks for the feedback.
In metadata yaml:
metadataSpecVersion: "1.0" has to be changed to "1.1" ?
or   dockerImageTag: 0.1.6 ? to 0.1.7 ?

Where is the connector version specified ?

I see the resources/spec.json. But I could not see an example where this resource gets used in the main src class files.

2024-05-22 15:19 UTC, evantahler commented
Versions: Both the metadata.yaml and docker image tags should match.
Here's an example PR (https://github.com/airbytehq/airbyte/pull/35304/files) of how the java code loads an option set in the spec.  This PR added a new option to the spec invalid_cdc_cursor_position_behavior and then references it later via `sourceConfig.get("replication_method")`

2024-06-07 16:06 UTC, marcosmarxm requested changes

2024-06-07 16:06 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-elasticsearch/src/main/java/io/airbyte/integrations/source/elasticsearch/ElasticsearchConnection.java
> +            .setFailureListener((new FailureListener()));
Can you check this line pelase?

2024-08-26 09:01 UTC, closed without merging