Source Intercom: Add tickets stream
airbytehq/airbyte pull request #39117
Opened 2024-06-05 11:33 UTC by krishan711

## What

## How

## Review guide

## User Impact

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

2024-06-05 12:28 UTC, marcosmarxm requested changes

2024-06-05 12:28 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-intercom/metadata.yaml
> +  dockerImageTag: 0.6.7
@krishan711 new streams are a minor update can you change to 0.7.0 and also bump the version in project.toml and run poetry lock? Thanks

2024-06-05 12:28 UTC, marcosmarxm commented
If possible update the description of the contribution and link an existing issue or discussion.

2024-06-05 13:40 UTC, krishan711 commented
> If possible update the description of the contribution and link an existing issue or discussion.

Thanks, updated the description. please let me know what i should add more detail about if anything.

2024-06-06 15:55 UTC, marcosmarxm commented
Running CI Tests

2024-06-07 15:46 UTC, marcosmarxm requested changes
One small detail

2024-06-07 15:46 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-intercom/source_intercom/manifest.yaml
> +    type: object
It misses `additionalProperties: true` to all object fields.

2024-06-14 13:58 UTC, marcosmarxm commented
@krishan711 running CI, let's wait for the results.

2024-06-17 08:25 UTC, krishan711 commented
@marcosmarxm i cant tell what i need to do to make these checks pass. could i get some guidance here by any chance pls?

2024-09-01 09:00 UTC, closed without merging