Update manifest.yaml
airbytehq/airbyte pull request #39344
Opened 2024-06-07 15:01 UTC by NimbleSebastian

## What

## How

## Review guide

## User Impact

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

2024-06-07 15:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=39344) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=39344) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=39344) it.</sub>

2024-06-07 15:34 UTC, marcosmarxm requested changes
Please update the title of your contribution to match the guidelines and add information in the description and link to an existing issue. Also sign the CLA.

2024-06-10 03:22 UTC, natikgadzhi reviewed
Hey @NimbleSebastian, thank you for the patch! A few things to get this over the finish line:

- [ ] Sign the CLA
- [ ] Update the PR title. Something like "update schemas for source-waiteraid.
- [ ] Update the connector version in `pyproject.toml` file, and `metadata.yaml` file in `dockerImageTag`.
- [ ] Add a changelog entry in `docs/integrations/source_waiteraid`

2024-06-24 23:28 UTC, marcosmarxm commented
Closed due to lack of response.

2024-06-24 23:28 UTC, closed without merging