Source Hubspot: add associations to custom objects again
airbytehq/airbyte pull request #39376
Opened 2024-06-10 16:13 UTC by azorej

## What
I used [PR](https://github.com/airbytehq/airbyte/issues/31509) as the base

The question about Custom object associations:
https://github.com/airbytehq/airbyte/discussions/38650

## How
There are two types of associations with custom objects:
1. Associations **from** custom objects
2. Associations **to** custom objects

**from** are resolved in moment of creation of custom object stream
**to** are more complicated. I added field `associated_custom_objects` to `CRMSearchStream`  and store new associations there.

## Review guide
1. `airbyte-integrations/connectors/source-hubspot/source_hubspot/streams.py`
2. `airbyte-integrations/connectors/source-hubspot/source_hubspot/source.py`

## User Impact

We use the connector but I didn't have excessive testing. 

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

2024-06-10 16:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=39376) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=39376) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=39376) it.</sub>

2024-06-10 16:18 UTC, bazarnov commented
@ChristoGrab, Could you please take a look at this PR once you have a chance? Thank you.

2024-06-11 19:25 UTC, marcosmarxm requested changes

2024-06-11 19:25 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-hubspot/pyproject.toml
> +version = "4.2.3dev1"
Please bump the version correctly to `4.3.0`, also bump the metadata file and doc entry changelog.

2024-06-11 19:25 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-hubspot/pyproject.toml
> +version = "4.2.3dev1"
After run `poetry lock` in the connector folder to regenerate the dependencies.

2024-06-11 19:26 UTC, marcosmarxm commented
Probably this do the same as https://github.com/airbytehq/airbyte/pull/38217 @ChristoGrab can you take a look?

2024-06-11 22:07 UTC, ChristoGrab commented
@azorej Thanks for your contribution! I had a chance to run things locally and everything seems to work well, although there are a few unit and integration tests that are failing at the moment. I was able to resolve a couple of them, is it ok by you if I push some changes to your branch?

2024-06-11 22:27 UTC, ChristoGrab commented on airbyte-integrations/connectors/source-hubspot/source_hubspot/streams.py
> +            final.pop("properties", None)  # HACK: Disable field in Airbyte does not work for a moment :(
Could you clarify the comment here? I see the sense in removing this field given that we are already unnesting the data, but I ran some tests on the production connector and the built-in field disabling does seem to work properly.

2024-07-23 22:15 UTC, jayqi commented
Hi @marcosmarxm, @ChristoGrab, @azorej, 

I'm ingesting custom HubSpot models using Airbyte Cloud, and the functionality in this PR would be very helpful. Are there any plans for pushing this over the finish line? Would additional contributors to the PR be helpful? If so, what are the gaps that still need to be addressed?

2024-09-30 09:01 UTC, closed without merging