🐛 Source Shopify: remove `supportedActions` field from api calls, causing `INTERNAL_SERVER_ERROR`
airbytehq/airbyte pull request #39436
Opened 2024-06-12 17:40 UTC by bazarnov

## What
Resolving:
- https://github.com/airbytehq/oncall/issues/5539

## How
- commented out the `supportedActions` field from requesting and using with `API calls` due to the fact it causes the `INTERNAL_SERVER_ERROR` for the `fulfillment_orders` stream.

The actual reason is unknown so far, but we should not let the customer wait for the fix forever.

## User Impact
This is not a breaking change, because the schema remains the same, we only exclude the field from use within the API calls, thus no data for this field will be available after this change, there will be `Null` instead for the field.

We should release the `pre-release` version and test on this wks: https://cloud.airbyte.com/workspaces/fd2d27ae-f104-4b8b-bda9-23e01c7865a7/connections/139ae5db-fd38-42f4-9019-da3ea191cdcc/job-history

If the issue is gone, we can leave this Customer using the `pre-release` version or merge this PR to update all of the customers. 

## Can this PR be safely reverted and rolled back?
- [X] YES 💚
- [ ] NO ❌

2024-06-12 17:41 UTC, bazarnov commented
@maxi297 Could you please block this PR from merging, intentionally, so there is no opportunity to merge it before we agree on the action items of what todo with this.

2024-06-12 17:48 UTC, maxi297 requested changes
Blindly blocking this PR as asked [here](https://github.com/airbytehq/airbyte/pull/39436#issuecomment-2163585930)

2024-06-12 17:57 UTC, bazarnov commented
The `pre-release` version contains the fix that has been published with the tag: `2.2.4-dev.0047effb35` 

This version excludes the `supportedActions` from being part of the query for the `fulfillment orders` stream.

2025-07-30 12:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=39436) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=39436) before we can accept your contribution.<br/><hr/>**Oleksandr Bazarnov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=39436) it.</sub>

2025-08-14 17:25 UTC, cgardens commented
We are closing this PR due to inactivity. We regularly close PRs that were created more than 6 months ago. If you'd like to keep working on it, please feel free reopen it. We'd be happy to keep working with you.

2025-08-14 17:25 UTC, closed without merging