postgres source/destination - bump postgres driver version
airbytehq/airbyte pull request #39460
Opened 2024-06-13 15:52 UTC by evantahler

Closes https://github.com/airbytehq/airbyte-internal-issues/issues/8249

2024-06-13 16:39 UTC, stephane-airbyte requested changes
you also should bump the version in deps.toml

2024-06-13 16:51 UTC, stephane-airbyte approved these changes

2024-06-13 18:58 UTC, evantahler commented
Looks like `PostgresDestinationHandler` needs to implement `createNamespaces` - I need help with that

2024-06-13 20:45 UTC, evantahler commented
New plan - the postgres destination(s) can't use the latest CDK until the Airbyte 1.0 work is complete (`ERROR: column "_airbyte_generation_id" of relation "users_final" does not exist`).  So, in this PR I'll bump the CDK dependencies, and when we update the postgres destination in general later this month, it will gain the new JDBC driver.

2024-06-13 20:58 UTC, evantahler commented
@xiaohansong - any tips about what I should be doing here to get source-postgres to build with the latest CDK?

```
Error: [Task :airbyte-integrations:connectors:source-postgres:compileJava] constructor RelationalDbDebeziumPropertiesManager in class RelationalDbDebeziumPropertiesManager cannot be applied to given types;
    final var propertiesManager = new RelationalDbDebeziumPropertiesManager(
```

2024-06-14 06:55 UTC, theyueli commented
> @xiaohansong - any tips about what I should be doing here to get source-postgres to build with the latest CDK?
> 
> ```
> Error: [Task :airbyte-integrations:connectors:source-postgres:compileJava] constructor RelationalDbDebeziumPropertiesManager in class RelationalDbDebeziumPropertiesManager cannot be applied to given types;
>     final var propertiesManager = new RelationalDbDebeziumPropertiesManager(
> ```

Is this actually related to @akashkulk 's change? The constructor now requires a new parameter:

https://github.com/airbytehq/airbyte/pull/39405/files#diff-3af961ccd56f952a3f466eb2f94fb6786785e37aa298fc1134e1aec2d2f81869R22

2024-06-14 17:10 UTC, xiaohansong commented
@akashkulk has a fix in https://github.com/airbytehq/airbyte/pull/39474

2024-06-14 19:08 UTC, evantahler commented
After rebasing the latest from @akashkulk, this PR is green!
Can I please get a review from @airbytehq/dbsources

2024-06-14 19:14 UTC, xiaohansong approved these changes

2024-06-14 19:14 UTC, xiaohansong commented on airbyte-integrations/connectors/source-postgres/build.gradle
> +    useLocalCdk = true
remember to change this back!

2024-06-14 19:15 UTC, evantahler commented
/publish-java-cdk

2024-06-14 19:35 UTC, merged