Make credentials optional in BigQuery connector (issue #3657)
airbytehq/airbyte pull request #3947
Opened 2021-06-08 13:03 UTC by sabifranjo

## What
Issue #3657 
![image](https://user-images.githubusercontent.com/29524300/121188935-dffdb700-c869-11eb-98a4-45f817614ab5.png)
![image](https://user-images.githubusercontent.com/29524300/121188955-e55b0180-c869-11eb-891e-9868afba295c.png)

## How
Solved by adding a dropdown to select authentication method and making the existing credentials field part of the second option.

## Additional comment
Since the configuration structure was changed, **airbyte/normalization:0.1.32** (also included in this PR) needs to be published before running tests for the connector.

## Pre-merge Checklist
Expand the checklist which is relevant for this PR. 

<details><summary> <strong> Connector checklist </strong> </summary>
<p>

- [x] Issue acceptance criteria met
- [x] Unit & integration tests added as appropriate (and are passing)
![image](https://user-images.githubusercontent.com/29524300/121189234-310dab00-c86a-11eb-8d02-ab7539598fe7.png)

- [ ] `/test` command documented [here]() is passing. 
    * Community members can skip this, Airbyters will run this for you. 
- [ ] Code reviews completed
- [ ] Credentials added to Github CI if needed and not already present. [instructions for injecting secrets into CI](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#using-credentials-in-ci). 
- [x] Documentation updated 
    - [ ] README
    - [x] CHANGELOG.md
    - [ ] Reference docs in the `docs/integrations/` directory.
- [x] Build is successful
- [x] Connector version bumped like described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] No major blockers
- [ ] PR merged into master branch
- [ ] Follow up tickets have been created
- [ ] Associated tickets have been closed & stakeholders notified
</p>
</details>

2021-06-08 17:26 UTC, sherifnada requested changes
@sabifranjo I am concerned that this is a breaking change/backwards incompatible. While I agree that this is the right way to solve this issue, we don't have a way to automatically gracefully upgrade connectors when a breaking change has been made to the config. Can we instead leave the schema the same and just remove `credentials_json` as a required field? We should also update its description to clarify that not including it would use the "default" authentication. 

In the future once we have a graceful migration process for breaking changes on connectors this should be solved more elegantly.

2021-06-09 10:36 UTC, sabifranjo commented
> @sabifranjo I am concerned that this is a breaking change/backwards incompatible. While I agree that this is the right way to solve this issue, we don't have a way to automatically gracefully upgrade connectors when a breaking change has been made to the config. Can we instead leave the schema the same and just remove `credentials_json` as a required field? We should also update its description to clarify that not including it would use the "default" authentication.
> 
> In the future once we have a graceful migration process for breaking changes on connectors this should be solved more elegantly.

@sherifnada I did the changes and updated the description accordingly. So now only the destination-bigquery:0.3.5 image needs to be published.

2021-06-17 21:42 UTC, marcosmarxm commented
@sabifranjo sorry took so long! I'm going to review this max later today! thanks for the contribution

2021-06-17 23:58 UTC, marcosmarxm approved these changes

2021-06-17 23:59 UTC, merged