Valdemar/#3712 create schemas from catalog
airbytehq/airbyte pull request #3948
Opened 2021-06-08 13:18 UTC by vovavovavovavova

## What
Closes #3712 
## How

`python main.py read --config secrets/config.json --catalog sample_files/configured_catalog.json | python schema_generator.py
`
Command will generate Json schemas and will place them in `_schemas` folder.

2021-06-11 14:02 UTC, keu commented on tools/integrations/schema_generator.py
> +data = sys.stdin.readlines()
lets add the main function and call it

2021-06-11 14:05 UTC, keu commented on tools/integrations/schema_generator.py
> +default_folder = os.path.join(os.getcwd(), "_schemas")
lets just call it `schemas` folder

2021-06-11 14:06 UTC, keu commented on tools/integrations/schema_generator.py
> +        json.dump(schema, outfile, indent=2)
lets sort keys as well

2021-06-11 14:06 UTC, keu commented on tools/integrations/schema_generator.py
> +for record in record_messages:
it is matter of taste, but about to iterate over stdin and do processing at the same time?

2021-06-11 14:14 UTC, keu commented on tools/integrations/schema_generator.py
> +Object.to_schema = to_schema
no need for hacks, genson is really flexible and quality package, check `EXTRA_STRATEGIES` docs

2021-06-11 14:14 UTC, keu requested changes
see my comments

2021-06-16 09:18 UTC, keu commented on tools/integrations/schema_generator.py
> +class NoRequiredObj(Object):
please add class docstring explaining why do we need this

2021-06-16 09:19 UTC, keu commented on tools/integrations/schema_generator.py
> +    for line in data:
```suggestion
    for line in sys.stdin:
```

2021-06-16 09:20 UTC, keu approved these changes
few comments

2021-06-16 11:16 UTC, merged

2021-06-28 14:18 UTC, bazarnov commented
`python main.py read --config secrets/config.json --catalog sample_files/configured_catalog.json | python schema_generator.py`

I have a question, regards this command: 
If I understood this correctly the output would be the same schemas but in separated files that configured_catalog.json is using in order to produce the RECORDS output? 

If so, shouldn't that be something like this? 
`python main.py read --config secrets/config.json | python schema_generator.py >> {output folder with configured_catalog.json + schemas}`