fix(source-racharge): fix primary key for `shop` stream
airbytehq/airbyte pull request #39491
Opened 2024-06-14 12:11 UTC by tolik0

## What
CAT failed due to a forbidden type of primary key - `object` for the `Shop` stream.

## How
Updated the primary key from the composite `[shop, store]` to a valid type - `integer` for id.

## User Impact
Users will need to refresh the schema and clear the stream data.

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

2024-06-14 17:19 UTC, bazarnov approved these changes

2024-06-17 16:31 UTC, lazebnyi approved these changes

2024-06-18 14:59 UTC, katmarkham requested changes

2024-06-18 14:59 UTC, katmarkham commented on airbyte-integrations/connectors/source-recharge/metadata.yaml
> +        message: "Primary key for Shop stream has been changed from [`shop`, `store`] to [`id`]. This change of pk makes the stream compatible with more types of destinations."
```suggestion
        message: "Primary key for Shop stream has been changed from [`shop`, `store`] to [`id`]. This change of primary key makes the stream compatible with more types of destinations."
```

2024-06-18 14:59 UTC, katmarkham commented on docs/integrations/sources/recharge.md
> +| 2.0.0   | 2024-06-14 | [39491](https://github.com/airbytehq/airbyte/pull/39491) | Update pk for Shop stream from shop, store(object, object) to id(integer)
```suggestion
| 2.0.0   | 2024-06-14 | [39491](https://github.com/airbytehq/airbyte/pull/39491) | Update primary key for Shop stream from shop, store(object, object) to id(integer)                                                      |
```

2024-06-18 14:59 UTC, katmarkham commented on docs/integrations/sources/recharge-migrations.md
> +This version introduces changing of pk from `[shop, store]`(type: object, object) to pk `id`(type: integer), as it makes stream compatible with destinations that do not support complex primary keys(e
```suggestion
This version introduces changing of primary key from `[shop, store]`(type: object, object) to primary key `id`(type: integer), as it makes stream compatible with destinations that do not support complex primary keys(e.g. BigQuery).
```

2024-06-18 14:59 UTC, katmarkham commented on docs/integrations/sources/recharge-migrations.md
> +This is a breaking change for **Shop** stream, which used `[shop, store]` fields as pk.
```suggestion
This is a breaking change for **Shop** stream, which used `[shop, store]` fields as a primary key.
```

2024-06-18 18:48 UTC, katmarkham approved these changes

2024-06-19 09:40 UTC, merged