Experimental class made to use expicit category which is filtered in …
airbytehq/airbyte pull request #40240
Opened 2024-06-24 17:29 UTC by inossidabile

## What
There are several clasess in Python CDK streams that are marked experimental. It's done with `@deprecated`. There's an option to specifcy category of deprecation and it's more semantically correct to explicitly mark those as experimental. All of that allows to remove about 1.5k warnings from unit tests.

## How
```python
@deprecated("This class is experimental. Use at your own risk.", category=ExperimentalClassWarning)
```

## Review guide
Run unit tests and see no `This class is experimental` warnings.

## User Impact
None

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌

2024-06-24 17:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=40240) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=40240) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=40240) it.</sub>

2024-06-24 18:53 UTC, girarda approved these changes
Nice! This is a good improvement!

2024-06-24 21:30 UTC, marcosmarxm commented
@inossidabile can you sign the CLA? Thanks!

2024-06-24 21:31 UTC, marcosmarxm requested changes

2024-06-24 21:31 UTC, marcosmarxm commented on airbyte-cdk/python/pytest.ini
> +    ignore::airbyte_cdk.sources.source.ExperimentalClassWarning
nit, EOF

2024-06-25 19:07 UTC, inossidabile commented
@marcosmarxm CLA done, EOF adjusted.

2024-06-26 00:39 UTC, marcosmarxm approved these changes

2024-06-27 01:15 UTC, merged