AWS S3 and Alternative S3 destination connector feature
airbytehq/airbyte pull request #4038
Opened 2021-06-10 18:49 UTC by panhavad

## What
Allow S3 Destination Connector have the option to connect to both standard AWS S3 and Minio S3(Alternative S3).
This PR answering to this issue #3900 
![image](https://user-images.githubusercontent.com/7156904/121580530-0a609780-ca57-11eb-80a7-0ea0b998b3d4.png)

Integration test result:
![image](https://user-images.githubusercontent.com/7156904/121580351-d7b69f00-ca56-11eb-86e0-1a0ed3097eff.png)

## How
Because Minio S3 also supports AWS SDK, just use `AwsClientBuilder.EndpointConfiguration` to enable the custom endpoint.
Also check the condition, if the user enters 'aws' in the endpoint field. It will use the default AWS endpoint, else it connects to entered custom endpoint URL

## Recommended reading order
1. `spec.json`
2. `S3Consumer.java`
3. `S3StreamCopier.java`
4. `S3Config.java`
5. `s3.md`

## Pre-merge Checklist
Expand the checklist which is relevant for this PR. 

<details><summary> <strong> Connector checklist </strong> </summary>
<p>

- [X] Issue acceptance criteria met
- [X] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Secrets are annotated with `airbyte_secret` in output spec
- [ ] Unit & integration tests added as appropriate (and are passing)
    * Community members: please provide proof of this succeeding locally e.g: screenshot or copy-paste acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] `/test connector=connectors/<name>` command as documented [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-an-existing-connector) is passing. 
    * Community members can skip this, Airbyters will run this for you. 
- [ ] Code reviews completed
- [ ] Credentials added to Github CI if needed and not already present. [instructions for injecting secrets into CI](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#using-credentials-in-ci). 
- [x] Documentation updated 
    - [x] README
    - [ ] CHANGELOG.md
    - [x] Reference docs in the `docs/integrations/` directory.
- [x] Build is successful
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] No major blockers
- [ ] PR merged into master branch
- [ ] Follow up tickets have been created
- [ ] Associated tickets have been closed & stakeholders notified
</p>
</details>

<details><summary> <strong> Connector Generator checklist </strong> </summary>
<p>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

2021-06-10 18:49 UTC, panhavad commented
@davinchia This is the new one, hope it fine. Feel free to suggest any change.

2021-06-11 02:24 UTC, tuliren requested changes
Looks great! Thank you for the PR.

One suggestion is that `s3_endpoint` can just be an optional. What about defaulting to AWS when this field is empty? The rationales are: 1) asking people to type "aws" seems unnecessary, and 2) in this way, existing users of this connector does not need to migrate their config.

2021-06-11 02:24 UTC, tuliren commented on airbyte-integrations/connectors/destination-s3/src/main/resources/spec.json
> +      "s3_endpoint",
This field should be optinoal. When empty, it can default to "aws". Otherwise, existing users will have to run a migration, which is unnecessary.

2021-06-11 07:03 UTC, panhavad commented
Change has been made:
-Leave blank if using AWS
-By default blank
-s3_endpoint is not required
-PASSED integration test (Both AWS & Minio)
-PASSED build
-Tested on UI and API

2021-06-13 06:16 UTC, tuliren commented
/test connector=connectors/destination-s3

2021-06-13 07:15 UTC, tuliren reviewed
Thank you.

There is one NPE issue when `s3_endpoint ` does not exist in the config (for existing S3 users). Look good and ready to merge otherwise.

2021-06-13 07:33 UTC, panhavad commented on airbyte-integrations/connectors/destination-jdbc/src/main/java/io/airbyte/integrations/destination/jdbc/copy/s3/S3Config.java
> +        config.get("s3_endpoint") == null ? "" : config.get("s3_endpoint").asText()
@tuliren did you forget ","

2021-06-13 07:40 UTC, panhavad commented on airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/S3DestinationConfig.java
> +        config.get("s3_endpoint") == null ? "" : config.get("s3_endpoint").asText()
i think the same here, "," missing

2021-06-13 07:52 UTC, tuliren commented on airbyte-integrations/connectors/destination-jdbc/src/main/java/io/airbyte/integrations/destination/jdbc/copy/s3/S3Config.java
> +        config.get("s3_endpoint") == null ? "" : config.get("s3_endpoint").asText()
Yes, you are right.

2021-06-13 07:53 UTC, tuliren approved these changes

2021-06-13 07:57 UTC, merged