✨ source-clazar: fixed streams schema declarations
airbytehq/airbyte pull request #41657
Opened 2024-07-12 01:50 UTC by prashant-mittal9

## What

## How

## Review guide

## User Impact

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

2024-07-12 15:45 UTC, marcosmarxm reviewed
@prashant-mittal9 let us know when this is ready to review.

2024-07-14 20:20 UTC, prashant-mittal9 commented
> @prashant-mittal9 let us know when this is ready to review.

@marcosmarxm can you please review this, if fine please merge it as well

2024-07-17 17:56 UTC, marcosmarxm requested changes
It is missing the update the connector version in the pyproject and metadata file.

2024-07-17 18:12 UTC, marcosmarxm commented
@natikgadzhi we need to /approve this. Can you double check it? The file is a valid connector in Builder.

2024-07-18 14:15 UTC, marcosmarxm approved these changes
LGTM

2024-07-18 14:15 UTC, merged

2024-07-18 14:16 UTC, marcosmarxm commented
Hello your feedback matters a lot to us. Can you spare just 2 minutes to complete a [survey](https://form.typeform.com/to/DOBqejte)? We’re dedicated to making the contributor experience even better, and your input is key to achieving excellence. Thank you for helping us improve!