Implement Workspace and Source* API endpoints
airbytehq/airbyte pull request #42
Opened 2020-08-11 22:44 UTC by cgardens

Takes a first pass at implementing endpoints for the Workspace, Source, SourceSpecification, SourceImplementation resources. This informed a lot of the other more infrastructure-y PRs I just put up.

Of note...
* Since the API interface class is pretty huge, I split up each resource into its own handler primarily for code readability reasons. The idea is that the handler can essentially just be treated like "controller" in express or rails. In other words it is appropriate for there to be API interface specific logic in there. All the other layers of code, should not be concerned about this.

2020-08-12 18:52 UTC, michel-tricot approved these changes

2020-08-12 20:44 UTC, merged

2026-03-02 21:32 UTC, wanguardd requested changes
System of Review completed analysis of 'Implement Workspace and Source* API endpoints'. Found **10 findings** across 6 files.

## 📋 Review Summary

| Category | Count |
|----------|-------|
| 🐛 CORRECTNESS | 3 |
| 🛡️ SECURITY | 3 |
| 📐 DESIGN | 2 |
| 🔍 QUALITY | 1 |
| ✅ TESTING | 1 |

---

## 🐛 CORRECTNESS

### `toSourceImplementationRead` always returns an empty object

The method creates a `SourceImplementationRead` result but all three setter calls target the **input parameter** `sourceConnectionImplementation`, not the result. The returned object has all null fields on every call.

**Evidence:**
```java
// SourceImplementationsHandler.java
private SourceImplementationRead toSourceImplementationRead(
    SourceConnectionImplementation sourceConnectionImplementation) {
  final SourceImplementationRead sourceImplementationRead = new SourceImplementationRead();
  sourceConnectionImplementation.setSourceImplementationId(  // ← BUG: wrong object
      sourceConnectionImplementation.getSourceImplementationId());
  sourceConnectionImplementation.setSourceSpecificationId(   // ← BUG: wrong object
      sourceConnectionImplementation.getSourceSpecificationId());
  sourceConnectionImplementation.setConfiguration(           // ← BUG: wrong object
      sourceConnectionImplementation.getConfiguration());
  return sourceImplementationRead;  // always empty
}
```

**Action:**
- [ ] Change all three `set*` calls to target `sourceImplementationRead`: `sourceImplementationRead.setSourceImplementationId(sourceConnectionImplementation.getSourceImplementationId());` etc.

---

### `updateWorkspace` silently discards all updates — missing `writeConfig` call

The method mutates an in-memory `StandardWorkspace` object but never calls `configPersistence.writeConfig()`. All five field mutations are lost when the request completes. The method then re-reads from persistence via `getWorkspaceFromId`, returning the original unchanged values.

**Evidence:**
```java
// WorkspacesHandler.java — updateWorkspace
persistedWorkspace.setEmail(workspaceUpdate.getEmail());
persistedWorkspace.setInitialSetupComplete(workspaceUpdate.getInitialSetupComplete());
persistedWorkspace.setAnonymousDataCollection(workspaceUpdate.getAnonymousDataCollection());
persistedWorkspace.setNews(workspaceUpdate.getNews());
persistedWorkspace.setSecurityUpdates(workspaceUpdate.getSecurityUpdates());
// ← Missing: configPersistence.writeConfig(...)
return getWorkspaceFromId(workspaceUpdate.getWorkspaceId());  // re-reads old values
```
Compare: `createSourceImplementation` in `SourceImplementationsHandler.java` correctly calls `configPersistence.writeConfig()` after setting fields.

**Action:**
- [ ] Add `configPersistence.writeConfig(PersistenceConfigType.STANDARD_WORKSPACE, workspaceId, persistedWorkspace);` immediately after all field mutations and before the return statement

---

### `getWorkspaceBySlug` ignores the slug parameter — returns the hardcoded default workspace for every request

The `slugRequestBody` parameter is marked `@SuppressWarnings("unused")` and is never referenced. The method unconditionally returns `WorkspaceConstants.DEFAULT_WORKSPACE_ID` regardless of the slug provided.

**Evidence:**
```java
// WorkspacesHandler.java
@SuppressWarnings("unused")
public WorkspaceRead getWorkspaceBySlug(SlugRequestBody slugRequestBody) {
  // for now we assume there is one workspace and it has a default uuid.
  return getWorkspaceFromId(WorkspaceConstants.DEFAULT_WORKSPACE_ID);
}
```

**Action:**
- [ ] Either implement actual slug-based lookup, or if the single-workspace assumption is intentional, document it in the OpenAPI spec and return `404` for any slug other than `"default"`

---

## 🛡️ SECURITY

### Hardcoded workspace UUID committed to the repository

UUID `5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6` is committed as both the filename and JSON content in a static config file, and is used as `WorkspaceConstants.DEFAULT_WORKSPACE_ID` throughout `WorkspacesHandler`.

**Evidence:**
```
data/config/STANDARD_WORKSPACE_CONFIGURATION/5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6.json
{
  "workspaceId": "5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6",
  "name": "default",
  "slug": "default",
  "initialSetupComplete": false
}
```

**Action:**
- [ ] Generate the default workspace UUID at server startup if none exists
- [ ] Remove this committed config file and remove the UUID from git history (BFG Repo Cleaner or `git filter-branch`)

---

### 14 stub methods return `null` — NPE exposes server stack traces to callers

14 unimplemented API methods in `ConfigurationApi` return `null`. When JAX-RS attempts to serialize a null response, it throws `NullPointerException`, returning a stack trace containing internal class names, package paths, and line numbers to the API caller.

**Evidence:**
```java
// ConfigurationApi.java — 14 occurrences
public SourceImplementationDiscoverSchemaRead discoverSchemaForSourceImplementation(...) {
  return null;  // → NPE on serialization
}
public ConnectionRead createConnection(@Valid ConnectionCreate connectionCreate) {
  return null;
}
// ... 12 more: getSourceImplementation, getSourceImplementationsForWorkspace,
// testConnectionToSourceImplementation, updateSourceImplementation, createConnection,
// createDestinationImplementation, getConnection, getDestination,
// getDestinationImplementation, getDestinationSpecification, listDestinations,
// syncConnection, updateConnection, updateDestinationImplementation
```

**Action:**
- [ ] Replace all `return null;` in stub methods with `throw new KnownException(501, "Not implemented");` to return a proper HTTP 501 status

---

### No authentication or authorization on any new endpoint

None of the new handler classes, nor `ConfigurationApi`, implement any form of authentication or authorization. Any network-reachable caller can read all workspace and source data, create source implementations, and modify workspace configuration.

**Evidence:**
```
Reviewed: ConfigurationApi.java, WorkspacesHandler.java, SourcesHandler.java,
          SourceSpecificationsHandler.java, SourceImplementationsHandler.java,
          IntegrationSchemaValidation.java

No occurrences of: @Secured, @RolesAllowed, Principal, authentication filter,
token validation, session check, or credential verification in any of the above.
```

**Action:**
- [ ] Add authentication filter/interceptor to all `/v1/*` routes; return `401 Unauthorized` before any handler code runs

---

## 📐 DESIGN

### `ConfigurationApi` no-arg constructor bypasses dependency injection

The no-arg constructor instantiates `ConfigPersistenceImpl` directly with `new`, creating a hidden coupling between the API layer and a specific persistence implementation. This makes unit testing the class impossible without a live filesystem.

**Evidence:**
```java
// ConfigurationApi.java
public ConfigurationApi() {
  ConfigPersistence configPersistence = new ConfigPersistenceImpl();  // ← DI bypass
  workspacesHandler = new WorkspacesHandler(configPersistence);
  // ...
}
```

**Action:**
- [ ] Remove the no-arg constructor; bind `ConfigPersistenceImpl` to `ConfigPersistence` in the DI container configuration; the DI framework will inject the correct instance

---

### `SourceSpecificationsHandler.getSourceSpecification` performs full table scan to find one record

The method loads all source connection specifications from disk and filters in memory to find one by `sourceId`. Author has acknowledged this with a `// todo` comment.

**Evidence:**
```java
// SourceSpecificationsHandler.java
// todo (cgardens) - this is a shortcoming of rolling our own disk storage.
// since we are not querying on a the primary key, we have to list all
// of the specification objects and then filter.
sourceConnection = configPersistence
    .getConfigs(PersistenceConfigType.SOURCE_CONNECTION_SPECIFICATION,
                SourceConnectionSpecification.class)
    .stream()
    .filter(spec -> spec.getSourceId().equals(sourceIdRequestBody.getS [...]

2026-03-08 10:05 UTC, wanguardd reviewed
System of Review completed analysis of 'Implement Workspace and Source* API endpoints'. Found **13 findings** across 6 files.

## 📋 Review Summary

| Category | Count |
|----------|-------|
| 🐛 CORRECTNESS | 3 |
| 🛡️ SECURITY | 4 |
| 📐 DESIGN | 3 |
| ✅ TESTING | 1 |
| 🔍 QUALITY | 2 |

---

## 🐛 CORRECTNESS

**`toSourceImplementationRead` always returns a null-filled object — setters target the input parameter instead of the return value**

Every call to `createSourceImplementation` returns `{"sourceImplementationId": null, "sourceSpecificationId": null, "connectionConfiguration": null}`. The method creates a new `SourceImplementationRead` but then calls all three setters on `sourceConnectionImplementation` (the input), never on the new object.

**Evidence:**
```java
// SourceImplementationsHandler.java lines 64-72
final SourceImplementationRead sourceImplementationRead = new SourceImplementationRead();
sourceConnectionImplementation.setSourceImplementationId(   // ← wrong target
    sourceConnectionImplementation.getSourceImplementationId());
sourceConnectionImplementation.setSourceSpecificationId(   // ← wrong target
    sourceConnectionImplementation.getSourceSpecificationId());
sourceConnectionImplementation.setConfiguration(           // ← wrong target
    sourceConnectionImplementation.getConfiguration());
return sourceImplementationRead;  // always all-null
```

**Action:**
- [ ] Change all three setter call sites from `sourceConnectionImplementation.setX(...)` to `sourceImplementationRead.setX(...)`

---

**`updateWorkspace` silently discards all changes — no `configPersistence.writeConfig(...)` call**

The method reads the workspace config, mutates 5 fields in memory (`initialSetupComplete`, `anonymousDataCollection`, `news`, `securityUpdates`, `email`), then returns by calling `getWorkspaceFromId()` which re-reads the original unchanged data from disk. HTTP 200 is returned with the unmodified workspace. Notably, `anonymousDataCollection` opt-outs are silently ignored — the consent preference is confirmed to the caller but never saved.

**Evidence:**
```java
// WorkspacesHandler.java lines 52-75 — no writeConfig call present
persistedWorkspace.setInitialSetupComplete(workspaceUpdate.getInitialSetupComplete());
persistedWorkspace.setAnonymousDataCollection(workspaceUpdate.getAnonymousDataCollection());
persistedWorkspace.setNews(workspaceUpdate.getNews());
persistedWorkspace.setSecurityUpdates(workspaceUpdate.getSecurityUpdates());

return getWorkspaceFromId(workspaceUpdate.getWorkspaceId()); // re-reads original disk state
```

**Action:**
- [ ] Insert before the return: `configPersistence.writeConfig(PersistenceConfigType.STANDARD_WORKSPACE, workspaceId, persistedWorkspace);`

---

**17 endpoints return `null` — callers receive 204 No Content or opaque framework errors instead of HTTP 501**

The four source-implementation endpoints central to setting up a data pipeline (`getSourceImplementation`, `getSourceImplementationsForWorkspace`, `testConnectionToSourceImplementation`, `updateSourceImplementation`) all return `null`. A client trying to use the full source-implementation lifecycle gets silent failures with no indication of what to do.

**Evidence:**
```java
// ConfigurationApi.java — confirmed null returns (17 total)
public SourceImplementationRead getSourceImplementation(...) { return null; }
public SourceImplementationReadList getSourceImplementationsForWorkspace(...) { return null; }
public SourceImplementationTestConnectionRead testConnectionToSourceImplementation(...) { return null; }
public SourceImplementationRead updateSourceImplementation(...) { return null; }
// ... 13 more across connection, destination, and sync endpoints
```

**Action:**
- [ ] Replace all `return null` stubs with `throw new KnownException(501, "Not implemented")` so callers receive a consistent, debuggable HTTP 501 response

---

## 🛡️ SECURITY

**Full connector credentials logged at INFO level on every request via `LoggingFeature(Verbosity.PAYLOAD_ANY)`**

`ServerApp.java` registers Jersey's `LoggingFeature` with `Verbosity.PAYLOAD_ANY` at `Level.INFO`, logging up to 10 KB of each request and response body. POST `/v1/source_implementations/create` carries `connectionConfiguration` containing database passwords, API keys, and OAuth secrets in plaintext. This is the first PR that connects a real handler to this endpoint, making the logging live for credential-carrying requests.

**Evidence:**
```java
// ServerApp.java — ResourceConfig registration
.register(new LoggingFeature(
    Logger.getLogger(LoggingFeature.DEFAULT_LOGGER_NAME),
    Level.INFO,
    LoggingFeature.Verbosity.PAYLOAD_ANY,   // logs full req + resp bodies
    10000));                                 // up to 10 KB per message
```

**Action:**
- [ ] Change `Verbosity.PAYLOAD_ANY` to `Verbosity.HEADERS_ONLY`. If body logging is required for debugging, implement a custom filter that redacts credential fields before writing to the log.

---

**Validation errors echo the full submitted credential payload in the HTTP 422 response body**

When JSON schema validation fails (e.g., a required connector field is missing), `JsonSchemaValidation.validateThrow()` constructs an exception message that includes `configJson.toPrettyString()` — the complete submitted configuration object. This message propagates through `SourceImplementationsHandler` and `KnownExceptionMapper` directly into the HTTP 422 body. Any proxy, load balancer, or logging infrastructure that records 4xx responses captures the credentials.

**Evidence:**
```java
// JsonSchemaValidation.validateThrow()
throw new JsonValidationException(
    String.format(
        "json schema validation failed. \nerrors: %s \nschema: \n%s \nobject: \n%s",
        validationMessages...,
        schemaJson.toPrettyString(),
        configJson.toPrettyString()));  // ← full submitted config echoed
```

**Action:**
- [ ] Remove `configJson.toPrettyString()` (and `schemaJson.toPrettyString()`) from the format string. Report only the validation error messages: `"json schema validation failed. errors: %s"`

---

**No authentication enforced despite `config.yaml` declaring global `bearerAuth` JWT requirement**

`config.yaml` declares `security: [bearerAuth: []]` globally, but `ServerApp.java` registers no `ContainerRequestFilter`, no `@RolesAllowed` resolver, and no JWT validator. All endpoints — workspace configuration, source enumeration, and source implementation creation (which persists raw credentials) — are accessible to any network-reachable caller without identity verification.

**Evidence:**
```yaml
# config.yaml — global security declaration
security:
- bearerAuth: []
```
```java
// ServerApp.java — no auth component registered
config.register(ConfigurationApi.class)
     .register(InvalidJsonExceptionMapper.class)
     .register(InvalidInputExceptionMapper.class)
     .register(KnownExceptionMapper.class)
     .register(CatchAllExceptionMapper.class)
     .register(new JacksonJaxbJsonProvider(...))
     .register(new LoggingFeature(...));
// ← no ContainerRequestFilter, no auth interceptor
```

**Action:**
- [ ] Implement a `ContainerRequestFilter` that validates Bearer JWTs. Register it in `ServerApp.java` before this service accepts real connector credentials.

---

**`ConfigNotFoundException` messages expose internal storage type names in HTTP error responses**

`ConfigPersistenceImpl.getFileOrThrow()` constructs error messages like `"config type: STANDARD_WORKSPACE id: <uuid> not found"` containing the internal `PersistenceConfigType` enum name. `WorkspacesHandler` and `SourcesHandler` pass `e.getMessage()` directly to `KnownException(404, ...)`, which `KnownExceptionMapper` serializes into the HTTP response body. Callers can learn that the system uses a flat-file config store keyed by type-enum names.

**Evidence:**
```java
// ConfigPersistenceImpl.getFileOrThrow()
throw new ConfigNotFoundException(
    String.format("config type: %s id: %s not [...]

2026-05-17 00:00 UTC, wanguardd requested changes
System of Review completed analysis of 'Implement Workspace and Source* API endpoints'. Found **12 findings** across 5 files.

## 📊 Progress Summary

**Review #3** (following two prior reviews: 10 findings and 13 findings)

The two critical data bugs (empty mapper result, missing persist call) and the zero-test finding have been flagged in both prior reviews and remain unresolved in the merged code. This review adds coverage of findings not raised previously: missing workspace ownership binding, plaintext credential storage, error message enumeration oracle, CORS absence, HTTP status code misuse, and per-request object instantiation.

---

## 📋 Review Summary

| Category | 🔴 Blocking | 🟡🟠 Non-Blocking | Total |
|----------|------------|------------------|-------|
| 🐛 CORRECTNESS | 3 | 1 | 4 |
| 🛡️ SECURITY | 1 | 2 | 3 |
| 📐 DESIGN | 0 | 2 | 2 |
| 🔍 QUALITY | 0 | 2 | 2 |
| ✅ TESTING | 1 | 0 | 1 |
| **Total** | **5** | **7** | **12** |

**Note**: 3 findings carry the 🔄 RE-REQUEST modifier (unaddressed from prior reviews).

---

## 🐛 CORRECTNESS

### 🔄 `toSourceImplementationRead` targets the input object — all fields always null

Every setter in the mapper is called on `sourceConnectionImplementation` (the input parameter), not on `sourceImplementationRead` (the return value). The return object is never written to. `createSourceImplementation` silently returns `{ sourceImplementationId: null, sourceSpecificationId: null, connectionConfiguration: null }` on every call.

**Evidence:**
```java
// SourceImplementationsHandler.java
private SourceImplementationRead toSourceImplementationRead(
    SourceConnectionImplementation sourceConnectionImplementation) {
  final SourceImplementationRead sourceImplementationRead = new SourceImplementationRead();
  sourceConnectionImplementation.setSourceImplementationId(   // ← wrong object (input)
      sourceConnectionImplementation.getSourceImplementationId());
  sourceConnectionImplementation.setSourceSpecificationId(    // ← wrong object (input)
      sourceConnectionImplementation.getSourceSpecificationId());
  sourceConnectionImplementation.setConfiguration(            // ← wrong object (input)
      sourceConnectionImplementation.getConfiguration());
  return sourceImplementationRead;  // never written to — all fields null
}
```

**Action:**
- [ ] Change all three call sites from `sourceConnectionImplementation.setX(...)` to `sourceImplementationRead.setX(...)`. Also check the field name: the response type likely uses `setConnectionConfiguration()` not `setConfiguration()`.

---

### 🔄 `updateWorkspace` discards all changes — missing `configPersistence.writeConfig()` call

Five fields are mutated in memory (`initialSetupComplete`, `anonymousDataCollection`, `news`, `securityUpdates`, `email`) but `configPersistence.writeConfig()` is never called. The method ends by re-reading from disk via `getWorkspaceFromId`, returning the original unmodified data. HTTP 200 is returned with unchanged values. The `anonymousDataCollection` opt-out is silently ignored — the user's consent preference is confirmed but never saved.

**Evidence:**
```java
// WorkspacesHandler.java — updateWorkspace (lines 52–75, no writeConfig present)
persistedWorkspace.setInitialSetupComplete(workspaceUpdate.getInitialSetupComplete());
persistedWorkspace.setAnonymousDataCollection(workspaceUpdate.getAnonymousDataCollection());
persistedWorkspace.setNews(workspaceUpdate.getNews());
persistedWorkspace.setSecurityUpdates(workspaceUpdate.getSecurityUpdates());
// ← no configPersistence.writeConfig() call

return getWorkspaceFromId(workspaceUpdate.getWorkspaceId()); // re-reads original disk state
```

Compare: `SourceImplementationsHandler.createSourceImplementation()` correctly calls `configPersistence.writeConfig()` after building the entity.

**Action:**
- [ ] Insert before the return: `configPersistence.writeConfig(PersistenceConfigType.STANDARD_WORKSPACE, workspaceId, persistedWorkspace)` (wrapped in `try/catch JsonValidationException → KnownException(422)`)

---

### `createSourceImplementation` does not store `workspaceId` — workspace ownership permanently lost

The persisted `SourceConnectionImplementation` has `sourceSpecificationId`, `sourceImplementationId`, and `configuration` set — but `workspaceId` is never transferred from the incoming `SourceImplementationCreate`. Each created source implementation exists without an ownership record. `getSourceImplementationsForWorkspace` (a `null`-returning stub) cannot be implemented correctly without this field. Any records written before this is fixed will require a data migration.

**Evidence:**
```java
// SourceImplementationsHandler.java — createSourceImplementation
final SourceConnectionImplementation newSourceConnectionImplementation =
    new SourceConnectionImplementation();
newSourceConnectionImplementation.setSourceSpecificationId(
    sourceImplementationCreate.getSourceSpecificationId());
newSourceConnectionImplementation.setSourceImplementationId(sourceImplementationId);
newSourceConnectionImplementation.setConfiguration(
    sourceImplementationCreate.getConnectionConfiguration());
// ← no setWorkspaceId() call — sourceImplementationCreate.getWorkspaceId() never read
configPersistence.writeConfig(..., newSourceConnectionImplementation);
```

**Action:**
- [ ] Add `newSourceConnectionImplementation.setWorkspaceId(sourceImplementationCreate.getWorkspaceId())` before `configPersistence.writeConfig(...)`. If `SourceConnectionImplementation` does not have a `workspaceId` field, add it and regenerate the model.

---

### Empty-string email silently discarded — no way to clear a previously set email

`updateWorkspace` guards email updates with `!workspaceUpdate.getEmail().equals("")`. A client sending `"email": ""` to clear a previously set address receives HTTP 200 but the old email is retained. There is no error, no indication of what happened, and no way to unset the field. Additionally, no email format validation is applied despite `format: email` in the OpenAPI schema — any non-null, non-empty string (including `"not-an-email"`) is accepted and persisted.

**Evidence:**
```java
// WorkspacesHandler.java line 59
if (workspaceUpdate.getEmail() != null && !workspaceUpdate.getEmail().equals("")) {
  persistedWorkspace.setEmail(workspaceUpdate.getEmail());
}
// OpenAPI config.yaml: email field has `format: email` — advisory only, not enforced server-side
```

**Action:**
- [ ] Define explicit clearing semantics: treat `null` as "no change", `""` as "clear email" (or reject `""` with 422 and a specific message). Add `@Email @Size(max = 254)` to the email DTO field.

---

## 🛡️ SECURITY

### Connector credentials stored in plaintext — no encryption, no field masking

`connectionConfiguration` (containing database passwords, API keys, and OAuth tokens) is written directly to `configPersistence` with no encryption and no masking. Any read endpoint that returns the full source implementation will expose raw credentials. Combined with zero authentication on all endpoints (flagged in prior reviews), any network-reachable caller can both write and enumerate plaintext credentials.

**Evidence:**
```java
// SourceImplementationsHandler.java
newSourceConnectionImplementation.setConfiguration(
    sourceImplementationCreate.getConnectionConfiguration());  // raw credentials

configPersistence.writeConfig(
    PersistenceConfigType.SOURCE_CONNECTION_IMPLEMENTATION,
    sourceImplementationId.toString(),
    newSourceConnectionImplementation);  // written as-is, no encryption wrapper
```

No encryption call, no secrets-manager interaction, no sensitive-field identification present anywhere in the diff.

**Action:**
- [ ] Before writing, identify sensitive fields via the connector schema's `airbyte_secret: true` annotation and encrypt their values with an application-managed key stored in a secrets manager (never in source or committed config). Return masked values (e.g. `"***"`) in all API responses that  [...]