🎉 New Source: Leadfeeder
airbytehq/airbyte pull request #42051
Opened 2024-07-17 15:15 UTC by KimPlv

## Discussion : https://github.com/airbytehq/airbyte/discussions/42050

## What
Add a new source with [Leadfeeder API](https://docs.leadfeeder.com/api)

## How
Extract Leadfeeder streams through the API

## Why 
Identify the businesses of website visitors, so it’s really useful information to integrate with a B2B sales pipeline.

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- Connector version is set to `0.1.0`
    - `Dockerfile` has version `0.1.0`
- Documentation updated
    - `docs/integrations/source/pingdom.md` including changelog with an entry for the initial version. 
    - `docs/integrations/README.md`

</details>

2024-07-18 13:37 UTC, marcosmarxm requested changes

2024-07-18 13:37 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-leadfeeder/source_leadfeeder/manifest.yaml
> +      file_path: "./source_leadfeeder/schemas/accounts.json"
Would be possible to integrate the schema inline or have it completly made by the builder?

2024-08-09 05:40 UTC, natikgadzhi reviewed
Sorry about the delay! Left a few comments, let's power through them and merge this.

2024-08-09 05:40 UTC, natikgadzhi commented on airbyte-integrations/connectors/source-leadfeeder/acceptance-test-config.yml
> +      - spec_path: "source_leadfeeder/spec.yaml"
```suggestion
      - spec_path: "source_leadfeeder/manifest.yaml"
```

2024-08-09 05:40 UTC, natikgadzhi commented on airbyte-integrations/connectors/source-leadfeeder/pyproject.toml
> +airbyte-cdk = "^0"
```suggestion
airbyte-cdk = "^4.3.0"
```

2024-08-09 05:40 UTC, natikgadzhi commented on airbyte-integrations/connectors/source-leadfeeder/pyproject.toml
> +airbyte-cdk = "^0"
This would also require a `poetry lock` run locally.

2024-08-09 05:40 UTC, natikgadzhi commented on airbyte-integrations/connectors/source-leadfeeder/metadata.yaml
> +    baseImage: docker.io/airbyte/python-connector-base:1.2.0@sha256:c22a9d97464b69d6ef01898edf3f8612dc11614f05a84984451dde195f337db9
Can you please update this to the new `2.0.0` and it's sha hash please?

2024-08-09 05:40 UTC, natikgadzhi commented on airbyte-integrations/connectors/source-leadfeeder/main.py
> +from airbyte_cdk.entrypoint import launch
It's better to import `run` and just run it. But I understand this is templated, alright to keep.

2024-08-09 05:40 UTC, natikgadzhi commented on airbyte-integrations/connectors/source-leadfeeder/integration_tests/acceptance.py
> +# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
If this is just boilerplate, I would advise to delete the whole integration_tests directory and adjust acceptance-test-config.

2024-08-09 05:40 UTC, natikgadzhi commented on airbyte-integrations/connectors/source-leadfeeder/metadata.yaml
> +      enabled: false
```suggestion
      enabled: true
```

2024-08-09 05:40 UTC, natikgadzhi commented on airbyte-integrations/connectors/source-leadfeeder/metadata.yaml
> +      enabled: false
Why not ;)

2024-08-09 05:40 UTC, natikgadzhi commented on airbyte-integrations/connectors/source-leadfeeder/metadata.yaml
> +      - TODO # Please change to the hostname of the source.
```suggestion
      - "api.leadfeeder.com"
```

2024-09-20 09:16 UTC, closed without merging