source-plausible new config setting for self hosted plausible instance.
airbytehq/airbyte pull request #43048
Opened 2024-08-03 07:15 UTC by maxmckenzie

## What
New config added to manifest.yaml for api_url as Plausible can be self hosted.

## How
Updated the manifest.yaml

## User Impact
* What is the end result perceived by the user?: _they will be given a new config option for API URL_

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

2024-08-03 07:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=43048) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=43048) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=43048) it.</sub>

2024-08-05 12:25 UTC, marcosmarxm requested changes
Can you bump the connector version in the metadata and pyprojet files (in the connector folder). Also, add the changelog entry in the connector docs and update the setup as it now has a new parameter possible to configure.

2024-08-06 05:21 UTC, maxmckenzie commented
> Can you bump the connector version in the metadata and pyprojet files (in the connector folder). Also, add the changelog entry in the connector docs and update the setup as it now has a new parameter possible to configure.

Sorted, there where no set up steps so i've added them 💃

2024-08-06 18:35 UTC, marcosmarxm approved these changes
Thanks @maxmckenzie

2024-08-06 18:35 UTC, merged