live tests: redirect stderr & stdout to separate files
airbytehq/airbyte pull request #43453
Opened 2024-08-09 19:29 UTC by clnoll

## What

## How

## Review guide

## User Impact

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

2024-08-12 10:18 UTC, alafanechere requested changes

2024-08-12 10:18 UTC, alafanechere commented on airbyte-ci/connectors/live-tests/src/live_tests/commons/connector_runner.py
> +                raise errors.ExportError(f"Failed to export {self.IN_CONTAINER_STDOUT_PATH}")
Shall we also export the `IN_CONTAINER_STDERR_PATH`, might be helpful for debugging.
I'm not 💯 sure but I think `stderr` might also contain airbyte messages, so this change might mean our tests will not consume them.

2024-08-12 10:18 UTC, alafanechere commented on airbyte-ci/connectors/live-tests/src/live_tests/commons/connector_runner.py
> +                    + f"| {self.IN_CONTAINER_OBFUSCATOR_PATH} 2>{self.IN_CONTAINER_STDERR_PATH} 2>&1 | tee -a {self.IN_CONTAINER_STDOUT_PATH}",
We're redirectiong the obsfuscator and not the connector output right?
I think that in any case the use of `|` after the connector command means that the obsfuscator only gets `stdout`. 
I think we should do something like this instead:
```
command > >(obfuscator consumes stdout) 2> >(obfuscator consumes stderr)
```

2025-08-14 17:23 UTC, cgardens commented
We are closing this PR due to inactivity. We regularly close PRs that were created more than 6 months ago. If you'd like to keep working on it, please feel free reopen it. We'd be happy to keep working with you.

2025-08-14 17:23 UTC, closed without merging