Source Snapchat Marketing: Add filter for organization and ad account
airbytehq/airbyte pull request #44170
Opened 2024-08-16 01:14 UTC by topefolorunso

## What

Adds filter for organization and ad account closes #44117

## How

Added the `organization_ids` and `ad_account_ids` inputs to config and made them optional. Then conditionally set the paths for `organizations` and `adaccounts` streams if the list of ids are provided in config

## Review guide
1. `manifest.yaml`

## User Impact
Users of the Snapchat source can sync a subset of their total data by `organization_ids` and by `ad_account_ids`.

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌

2024-09-06 23:19 UTC, lazebnyi requested changes
Looks good overall! Just need to add a unit test before I can approve.

2024-09-09 13:28 UTC, topefolorunso commented
> Looks good overall! Just need to add a unit test with non empty lists in the config before I can approve.

Unit tests added now @lazebnyi

2024-09-23 22:38 UTC, lazebnyi reviewed
lgtm 
after passing tests can be approved

2025-02-02 19:43 UTC, lazebnyi approved these changes

2025-02-05 18:01 UTC, merged