Source Stripe: Add tax_rates stream
airbytehq/airbyte pull request #44184
Opened 2024-08-16 15:26 UTC by btkcodedev

## What
Closes https://github.com/airbytehq/airbyte/issues/44183

## How
Add tax rates stream

2024-08-25 18:21 UTC, girarda requested changes
can you add a test suite for the new stream?[ here's an example for the transactions stream](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-stripe/unit_tests/integration/test_transactions.py)

2024-08-25 18:21 UTC, girarda commented on airbyte-integrations/connectors/source-stripe/pyproject.toml
> +version = "5.5.2"
nit: this should be a minor upgrade because we're adding a stream

2024-08-26 04:27 UTC, btkcodedev commented
Yes sure, will do

2025-03-04 03:49 UTC, natikgadzhi commented
While there might be a bunch of conflicts, I'd be hpapy to merge this if you get this over the finish line ;)

2025-03-04 03:49 UTC, natikgadzhi commented
/cc @btkcodedev

2025-03-13 20:34 UTC, maxi297 commented
@btkcodedev, @lazebnyi is currently migrating the whole source to low-code. This mean that this implementation will not work by the end of the week. Can we wait a bit until @lazebnyi release the changes so that we can implement this as low-code? 

CC @natikgadzhi

2025-03-13 20:36 UTC, btkcodedev commented
Thats cool! 
Yes sure, i'll wait

2025-03-16 13:11 UTC, lazebnyi reviewed
you can check migration details here - https://github.com/airbytehq/airbyte/pull/53687

2025-08-14 17:23 UTC, cgardens commented
We are closing this PR due to inactivity. We regularly close PRs that were created more than 6 months ago. If you'd like to keep working on it, please feel free reopen it. We'd be happy to keep working with you.

2025-08-14 17:23 UTC, closed without merging