Add Iterable EU functionality
airbytehq/airbyte pull request #44508
Opened 2024-08-21 15:43 UTC by JaydanPB

## What

## How

## Review guide

## User Impact

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

2024-08-21 15:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=44508) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=44508) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=44508) it.</sub>

2024-08-21 16:04 UTC, marcosmarxm requested changes
Left some comments.

2024-08-21 16:04 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-iterable/source_iterable/source.py
> +        region = config["region"]
```suggestion
        region = config["region"] or "US"
```

This way it won't break existing connections.

2024-08-21 16:04 UTC, marcosmarxm commented
Please sign the CLA.

2024-08-22 17:00 UTC, marcosmarxm requested changes
LGTM @JaydanPB can you bump the connector version inside the metadata.yaml and pyproject.toml file. Also add the entry for the changelog in documentation

2024-09-05 13:58 UTC, JaydanPB commented
This has now been tested - it successfully synced data from Iterable EU as expected.  

I do not have access to a Iterable US API key so I cannot fully test whether we have introduced any breaking changes, but I have attempted to add the region parameter in the least intrusive way possible and a rollback should be straightforward.

2024-12-12 09:01 UTC, closed without merging

2026-03-06 08:53 UTC, gregor-weber-knowunity commented
Hey @marcosmarxm this is not available yet in the iterable [connector](https://docs.airbyte.com/integrations/sources/iterable). Are there any plans to add the EU region support?

2026-03-10 10:51 UTC, JaydanPB commented
Hey guys, I've refreshed the EU implementation here and opened a PR: https://github.com/airbytehq/airbyte/pull/74702