source-reddit contribution from btkcodedev
airbytehq/airbyte pull request #44579
Opened 2024-08-23 05:58 UTC by btkcodedev

Auto-generated PR by the Connector Builder for source-reddit

2024-08-23 16:54 UTC, btkcodedev commented
/format-fix

2024-08-23 16:55 UTC, erohmensing requested changes
We need to size the icons according to our style guide. 

@nora-airbyte is there a straightforward way for someone not in Figma to do this?

2024-08-23 16:57 UTC, btkcodedev commented
@erohmensing  We've got svg height and width in icon.svg
Does that help?

2024-08-23 17:19 UTC, erohmensing commented
@btkcodedev it needs to have the correct padding to match the other icons, i.e. it needs to not extend to the edges

2024-08-24 05:22 UTC, btkcodedev commented
/format-fix

2024-08-25 05:28 UTC, btkcodedev commented
@erohmensing, Please comment if the logo fixes are applied/how to do for completing this PR :bow: 
CC: @natikgadzhi

2024-08-26 16:01 UTC, nora-airbyte commented
![reddit](https://github.com/user-attachments/assets/fe987b42-e3da-439f-869e-a683f718c2f1)
Resized icon slightly

2024-08-26 17:07 UTC, btkcodedev commented
Given resize done Thanks @nora-airbyte @erohmensing 
CC: @natikgadzhi :bow:

2024-08-26 17:55 UTC, erohmensing approved these changes
Thank you for the contribution! I took a look over the docs - please be on the lookout for typos, etc. when you're writing them

2024-08-26 17:55 UTC, erohmensing commented on airbyte-integrations/connectors/source-reddit/metadata.yaml
> +      - www.reddit.com
```suggestion
      - oauth.reddit.com
      - reddit.com
```

2024-08-26 17:55 UTC, erohmensing commented on docs/integrations/sources/reddit.md
> +_Incremental_ syn means only changed resources are copied from Recurly. For the first run, it will be a Full Refresh sync.
```suggestion
_Incremental_ sync means only changed resources are copied from Reddit. For the first run, it will be a Full Refresh sync.
```

2024-08-26 17:55 UTC, erohmensing commented on docs/integrations/sources/reddit.md
> +Hit send to receive api_key as response under `access_token`
```suggestion
3. Visit Postman via web or app and make a new request with following guidelines:
 - Request - POST `https://www.reddit.com/api/v1/access_token`
 - Authorization - Basic Auth -`username: <YOUR_USERNAME>`, `password: <YOUR_PASSWORD>`
 - Body - x-www-form-urlencoded - `grant_type: password, username: YOUR_REDDIT_USERNAME, password: YOUR_REDDIT_PASSWORD`

Hit send to receive `api_key` in the response under `access_token`
```

2024-08-26 17:55 UTC, erohmensing commented on docs/integrations/sources/reddit.md
> +Hit send to receive api_key as response under `access_token`
Does the url-encoded body use the spaces between args?

2024-08-26 17:55 UTC, erohmensing commented on docs/integrations/sources/reddit.md
> +- The reddit api has a hard limit of fetch 1000 records for a single stream call with subsequent pagination.
```suggestion
- The Reddit API has [rate limiting of 100 queries per minute (QPM) per OAuth client ID](https://support.reddithelp.com/hc/en-us/articles/16160319875092-Reddit-Data-API-Wiki). It is handled with an exponential backoff strategy, with maximum 3 retries.
- If the `api_key` expires, a new access token will need to be generated through Postman.
- The Reddit API has a hard limit of fetching 1000 records per single stream call with subsequent pagination.
```

2024-08-26 17:55 UTC, erohmensing commented on docs/integrations/sources/reddit.md
> +| 0.0.1 | 2024-08-23 | Initial release by btkcodedev via Connector Builder|
Link your GitHub profile, if you like :)

2024-08-26 18:08 UTC, btkcodedev commented on airbyte-integrations/connectors/source-reddit/acceptance-test-config.yml
Yes, Sent over reddit, Already tested through the builder

2024-08-27 00:09 UTC, natikgadzhi approved these changes

2024-08-27 00:09 UTC, merged