🎉 New Source: PrestaShop
airbytehq/airbyte pull request #4465
Opened 2021-07-01 16:06 UTC by vitaliizazmic

## What
Implementing new source for PrestaShop

Closes #2980 

## Pre-merge Checklist
Expand the checklist which is relevant for this PR. 

<details><summary> <strong> Connector checklist </strong> </summary>
<p>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Secrets are annotated with `airbyte_secret` in the connector's spec
- [ ] Credentials added to Github CI if needed and not already present. [instructions for injecting secrets into CI](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#using-credentials-in-ci). 
- [ ] Unit & integration tests added as appropriate (and are passing)
    * Community members: please provide proof of this succeeding locally e.g: screenshot or copy-paste acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] `/test connector=connectors/<name>` command as documented [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-an-existing-connector) is passing. 
    * Community members can skip this, Airbyters will run this for you. 
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] `README.md`
    - [ ] `docs/SUMMARY.md` if it's a new connector
    - [ ] Created or updated reference docs in `docs/integrations/<source or destination>/<name>`.
    - [ ] Changelog in the appropriate page in `docs/integrations/...`. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md` contains a reference to the new connector
    - [ ] Build status added to [build page](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/builds.md)
- [ ] Build is successful
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] No major blockers
- [ ] PR merged into master branch
- [ ] Follow up tickets have been created
- [ ] Associated tickets have been closed & stakeholders notified
</p>
</details>

2021-07-03 06:39 UTC, keu commented on airbyte-integrations/connectors/source-presta-shop/build.gradle
> +    implementation files(project(':airbyte-integrations:bases:base-python').airbyteDocker.outputs)
```suggestion
```

2021-07-03 06:51 UTC, keu commented on airbyte-integrations/connectors/source-presta-shop/integration_tests/catalog.json
> +          "properties": {
format?
also, we don't need to specify, jscon_schema in catalogs

2021-07-03 06:53 UTC, keu commented on airbyte-integrations/connectors/source-presta-shop/setup.py
> +    "airbyte-cdk",
```suggestion
    "airbyte-cdk~=0.1",
```

2021-07-03 07:03 UTC, keu commented on airbyte-integrations/connectors/source-presta-shop/acceptance-test-config.yml
> +        tax_rule_groups: ["date_upd"]
as long as the path in the state file matches the last piece of the path in record you can commit cursor_paths and fallback to default logic.
```suggestion
```

2021-07-04 19:53 UTC, keu commented on airbyte-integrations/connectors/source-presta-shop/source_presta_shop/streams.py
> +        data_key = self.data_key if self.data_key else self.name
lets move this logic to `data_key` property
if child class will redefine it like `data_key="somthing"` it will work natural

2021-07-04 19:58 UTC, keu commented on airbyte-integrations/connectors/source-presta-shop/source_presta_shop/streams.py
> +        return self._has_next_page
I don't get it, why we introduce state variable like `_has_next_page` and `_offset`?
why we don't return 
```python
{
  "limit":  f"{self._offset},{self.limit}"
}
```
here?

2021-07-04 20:04 UTC, keu requested changes
I'm not sure how to review this without being able to test it.
1. please add creds to lastpass
2. please add docker container creation to acceptance tests (can be hooked in build.gradle as pre-hook/post-hook to integrationTest task or as acceptance test fixture in acceptance.py file)

2021-07-04 20:41 UTC, keu commented on airbyte-integrations/connectors/source-presta-shop/source_presta_shop/streams.py
> +        return self._has_next_page
also it is hard to say how response looks like, without running test container

2021-07-04 20:43 UTC, keu commented on airbyte-integrations/connectors/source-presta-shop/source_presta_shop/streams.py
> +            records = response_json.get(data_key, [])
this logic should go to next_token method

2021-07-04 20:46 UTC, keu commented on airbyte-integrations/connectors/source-presta-shop/source_presta_shop/streams.py
> +        params["date"] = 1
what does this param means? I can't find it in the docs

2021-07-04 20:47 UTC, keu commented on airbyte-integrations/connectors/source-presta-shop/source_presta_shop/streams.py
> +    def path(self, **kwargs) -> str:
is it safe to say that here in many other places `self.path == self.name` ? maybe lets have default path implementation that return self.name?

2021-07-04 20:48 UTC, keu requested changes
looks good in general, just few comments and testing is not clear

2021-07-26 15:42 UTC, keu commented
/test connectors=source-prestashop

2021-07-26 21:23 UTC, keu commented on airbyte-integrations/connectors/source-prestashop/integration_tests/docker-compose.yaml
> +    image: eugenekulak/airbyte-prestashop:0.1.0
someone needs to copy and publish this under airbyte account

2021-07-26 21:23 UTC, keu commented on airbyte-integrations/connectors/source-prestashop/integration_tests/test_dummy.py
> +def test_dummy():
apparently we need this also to make acceptance setup/teardown fixture to work, see `acceptance.py`

2021-07-26 21:47 UTC, sherifnada approved these changes

2021-07-26 23:47 UTC, keu commented
/test connector=source-prestashop

2021-07-27 00:14 UTC, keu commented
/publish connector=bases/source-acceptance-test

2021-07-27 00:32 UTC, keu commented
/publish connector=source-prestashop

2021-07-27 00:39 UTC, keu commented
/publish connector=connectors/source-prestashop

2021-07-27 01:33 UTC, keu commented
/publish connector=source-prestashop

2021-07-27 01:39 UTC, keu commented
/publish connector=connectors/source-prestashop

2021-07-27 01:55 UTC, merged