Create on on-oci-vm.md
airbytehq/airbyte pull request #4468
Opened 2021-07-01 17:27 UTC by shadabshaukat

Deployment guide for Airbyte on Oracle Cloud Infrastructure (OCI) VM

## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## Pre-merge Checklist
Expand the checklist which is relevant for this PR. 

<details><summary> <strong> Connector checklist </strong> </summary>
<p>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Secrets are annotated with `airbyte_secret` in the connector's spec
- [ ] Credentials added to Github CI if needed and not already present. [instructions for injecting secrets into CI](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#using-credentials-in-ci). 
- [ ] Unit & integration tests added as appropriate (and are passing)
    * Community members: please provide proof of this succeeding locally e.g: screenshot or copy-paste acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] `/test connector=connectors/<name>` command as documented [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-an-existing-connector) is passing. 
    * Community members can skip this, Airbyters will run this for you. 
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] `README.md`
    - [ ] `docs/SUMMARY.md` if it's a new connector
    - [ ] Created or updated reference docs in `docs/integrations/<source or destination>/<name>`.
    - [ ] Changelog in the appropriate page in `docs/integrations/...`. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md` contains a reference to the new connector
    - [ ] Build status added to [build page](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/builds.md)
- [ ] Build is successful
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] No major blockers
- [ ] PR merged into master branch
- [ ] Follow up tickets have been created
- [ ] Associated tickets have been closed & stakeholders notified
</p>
</details>

<details><summary> <strong> Connector Generator checklist </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

2021-07-03 11:49 UTC, shadabshaukat commented
Hello. Is anyone able to review this documentation?

2021-07-06 13:29 UTC, marcosmarxm requested changes
@shadabshaukat Thanks for your contribution and sorry for the delay. LGTM, but could you add the images inside the folder https://github.com/airbytehq/airbyte/tree/master/docs/.gitbook/assets?

2021-07-06 17:51 UTC, shadabshaukat commented
@marcosmarxm Thanks Marcos but when i try to upload the image files to "https://github.com/airbytehq/airbyte/tree/master/docs/.gitbook/assets" it tells me "Uploads are disabled, file uploads require push access to this repository"

2021-07-06 18:13 UTC, avaidyanatha reviewed
Just some updates to the headers, but the rest looks great! And yeah, make sure to add those images to the `/assets` folder in the PR.

2021-07-06 18:13 UTC, avaidyanatha commented on docs/deploying-airbyte/on-oci-vm.md
> +-------------------------------------------------------
```suggestion
# Install Airbyte on Oracle Cloud Infrastructure (OCI) VM
```

2021-07-06 18:13 UTC, avaidyanatha commented on docs/deploying-airbyte/on-oci-vm.md
> +-------------------
```suggestion
## Create OCI Instance 
```

2021-07-06 18:13 UTC, avaidyanatha commented on docs/deploying-airbyte/on-oci-vm.md
> +----------------------------------------------------------------------
```suggestion
## Whitelist Port 8000 for a CIDR range in Security List of OCI VM Subnet
```

2021-07-06 18:13 UTC, avaidyanatha commented on docs/deploying-airbyte/on-oci-vm.md
> +--------------------------------------------------------
```suggestion
## Login to the Instance/VM with the SSH key and 'opc' user
```

2021-07-06 18:13 UTC, avaidyanatha commented on docs/deploying-airbyte/on-oci-vm.md
> +--------------
```suggestion
### Install Docker
```

2021-07-06 18:13 UTC, avaidyanatha commented on docs/deploying-airbyte/on-oci-vm.md
> +----------------------
```suggestion
### Install Docker Compose
```

2021-07-06 18:13 UTC, avaidyanatha commented on docs/deploying-airbyte/on-oci-vm.md
> +----------------
```suggestion
### Install Airbyte
```

2021-07-06 18:13 UTC, avaidyanatha commented on docs/deploying-airbyte/on-oci-vm.md
> +
```suggestion
## Install Prerequisites

```

2021-07-06 18:13 UTC, avaidyanatha commented on docs/deploying-airbyte/on-oci-vm.md
> +------------------------------------------
```suggestion
## Create SSH Tunnel to Login to the Instance

```

2021-07-06 18:13 UTC, avaidyanatha commented on docs/deploying-airbyte/on-oci-vm.md
> +--------------
```suggestion
## Access Airbyte
```

2021-07-06 18:23 UTC, shadabshaukat commented
Thanks for the update on the headers @avaidyanatha  I tried to upload the screen capture images to /assest folder but it gave me message "Uploads are disabled, file uploads require push access to this repository" Could you please help here, thanks

2021-07-07 10:57 UTC, marcosmarxm commented
@shadabshaukat you need to add the images in your fork https://github.com/shadabshaukat/airbyte/tree/patch-1/docs/.gitbook/assets probably using the link you should be able to add images, after that you need to change the link in docs

2021-07-07 11:09 UTC, marcosmarxm commented
@shadabshaukat one last step is `![](../.gitbook/assets/imageName.png)`

2021-07-07 11:11 UTC, shadabshaukat commented
@marcosmarxm Thanks, I have uploaded the images and change the references. Are we good to go ?

2021-07-07 11:19 UTC, shadabshaukat commented
@marcosmarxm All done, changed the References to ![](../.gitbook/assets/OCIScreen1.png)

2021-07-08 00:55 UTC, marcosmarxm approved these changes

2021-07-08 00:55 UTC, merged

2021-07-08 05:40 UTC, sherifnada commented
Wow, amazing. Thanks @shadabshaukat !!

2021-07-08 05:53 UTC, shadabshaukat commented
Thanks @sherifnada :)  When does the new OCI deployment guide get added to https://docs.airbyte.io/deploying-airbyte

2021-07-08 05:57 UTC, sherifnada commented
@shadabshaukat added it here https://github.com/airbytehq/airbyte/pull/4619 -- docs added to the index in `SUMMARY.md` appear on the docs page

2021-07-08 05:59 UTC, shadabshaukat commented
Thanks @sherifnada I can see it now in the Airbyte deployment guide. Much appreciated