Source Apify Dataset: add option to specify dataset by its name
airbytehq/airbyte pull request #44857
Opened 2024-08-28 13:15 UTC by vdusek

## What

- Introduce a new feature to specify an Apify dataset by its name.
- Closes: #43321

## How

- Added two new properties: `username` and `dataset_name`. These are necessary to identify the dataset by its name.
- Implemented logic to handle dataset resolution based on the provided inputs. If `dataset_id` is provided, the dataset will be resolved using it. If `username` and `dataset_name` are provided, the dataset will be resolved using those instead. Fail otherwise.
  - This logic is a work in progress - any guidance or feedback would be appreciated (see `## Todo`). 
  - Tagging @flash1293 directly, as he helped me in the last updates of the connector (#30428, #31333, #31397), thanks.

## Todo

- This PR is still under development, and I'm seeking assistance with the following challenge:

### Logic for dataset resolution in `DeclarativeStreams`

- There should be two distinct branches for resolving the dataset path:

1. Using `dataset_id`:

```
path: "datasets/{{ config['dataset_id'] }}"
```

2. Using `username` and `dataset_name`:

```
path: "datasets/{{ config['username'] }}~{{ config['dataset_name'] }}"
```

If neither or both of these options are provided, the process should fail.

- **Question**: How can this conditional logic be defined in the manifest? Is there a way to enforce this directly?

## User Impact

- This update introduces an alternative way to reference a dataset, but the existing method (using `dataset_id`) remains fully functional.

## Can this PR be safely reverted and rolled back?

- [x] YES 💚

2024-09-09 18:26 UTC, marcosmarxm requested changes
@vdusek, are you planning to continue working on this contribution? Today, you made a change in the spec, but it hasn't been applied to any part of the connector code.

2024-09-10 07:15 UTC, vdusek commented
@marcosmarxm Hi, I'd love to. Have you read the "Logic for dataset resolution in DeclarativeStreams" section? I have a question there regarding the conditional evaluation in the manifest.

2024-10-16 18:15 UTC, omcknightkittl commented
Hey, any update on this fix? Would be greatly appreciated :)

2024-10-21 10:47 UTC, vdusek commented
Well, I haven't found anything about the conditional logic in the manifests in docs.

Another approach would be to remove the `dataset_id` parameter and replace it with `dataset_name`. This change would be breaking, so it would require releasing a new major version. However, this solution wouldn't work for users who want to use a dataset ID instead of a name.

2025-01-02 08:57 UTC, vdusek commented
Hi @octavia-squidington-iii, why did you close this?

2025-02-11 01:08 UTC, marcosmarxm commented
Hello 👋, I apologize if your contribution hasn't been reviewed or updated yet. I'm working to address the community contribution backlog. I created this [GitHub project](https://github.com/orgs/airbytehq/projects/108/views/4) to help you understand when to expect a review. This week, my goal is to complete all contributions related to Marketplace and Manifest-only connectors. Next week, I will focus on API Certified Connectors, followed by DB Java Connector contributions. If you have any questions about your contribution, please feel free to send me a direct message in the Airbyte Community Slack (and include the link to your pull request).

2025-03-25 16:32 UTC, closed without merging

2025-03-25 16:32 UTC, marcosmarxm commented
Currently, the contribution is not providing the correct solution.