feat: include components in manifest-only build
airbytehq/airbyte pull request #44879
Opened 2024-08-29 00:16 UTC by ChristoGrab

## What

## How

## Review guide

## User Impact

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

2024-08-29 00:17 UTC, ChristoGrab commented
* **#44879** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/44879?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ChristoGrab and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-29 20:44 UTC, bnchrch requested changes
Just needs 1 test :)

2024-08-29 20:44 UTC, bnchrch commented on airbyte-ci/connectors/pipelines/pipelines/airbyte_ci/connectors/build_image/steps/manifest_only_connectors.py
> +        components_file = self.context.connector.code_directory / COMPONENTS_FILE_PATH
💎 This seems great to me.

2024-08-29 20:44 UTC, bnchrch commented on airbyte-ci/connectors/pipelines/pipelines/airbyte_ci/connectors/build_image/steps/manifest_only_connectors.py
> +        if components_file.exists():
🧪 Now, can we add a test to assert this works?

You should be able to modify this test
https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/tests/test_build_image/test_manifest_only_connectors.py#L51

And
1. mock it so `components_file.exists()` always returns true
2. We assert base_container.with_file was called with the expected params! (you'll notice we do that with_exec and with_label)

Let me know if you want a hand!

2024-09-03 21:50 UTC, ChristoGrab commented on airbyte-ci/connectors/pipelines/tests/test_helpers/test_utils.py
> +    assert await utils.check_path_in_workdir(container, "manifest.yaml")
Updated this test as this connector is now manifest-only and does not have poetry files

2024-09-03 21:52 UTC, bnchrch approved these changes
Pre-approving! But! Please look at the couple comments I made. 

Theres a chance we have some changes that dont belong?

2024-09-03 21:52 UTC, ChristoGrab commented on airbyte-ci/connectors/connector_ops/tests/test_required_reviewer_checks.py
> +    return "airbyte-integrations/connectors/source-zoho-crm/metadata.yaml"
Updated as source Pokeapi is now manifest-only, which breaks a couple test cases for expected reviewers. Zoho CRM is written in Python, which makes it unlikely to be migrated to manifest-only anytime soon.

2024-09-03 21:53 UTC, ChristoGrab commented on airbyte-ci/connectors/connector_ops/tests/test_required_reviewer_checks.py
> +        metadata_file.write("\nnot_tracked: true\n")
This was throwing a YAML SafeLoader error, needed to be formatted as a `k:v` pair

2024-09-03 21:58 UTC, ChristoGrab commented on airbyte-ci/connectors/connector_ops/tests/test_required_reviewer_checks.py
> +    return "airbyte-integrations/connectors/source-zoho-crm/metadata.yaml"
Haha sorry, was typing the explanation at the same time, here 'tis:

Updated as source Pokeapi is now manifest-only, which breaks a couple test cases for expected reviewers. Zoho CRM is written in Python, which makes it unlikely to be migrated to manifest-only anytime soon.

2024-09-03 22:00 UTC, ChristoGrab commented on airbyte-ci/connectors/connector_ops/tests/test_required_reviewer_checks.py
> +        metadata_file.write("\nnot_tracked: true\n")
This was me as well! This line was throwing a YAML SafeLoader error because it wasn't formatted as a `k:v` pair

2024-09-03 22:08 UTC, merged