Deploy a sweeper pod to clear completed pod histories
airbytehq/airbyte pull request #4500
Opened 2021-07-02 10:31 UTC by ChristopheDuong

## What
Closes https://github.com/airbytehq/airbyte/issues/3634

## How
Deploy a separate pod sweeper using shell command

2021-07-02 10:36 UTC, davinchia approved these changes

2021-07-02 14:18 UTC, jrhizor commented on kube/resources/pod-sweeper.yaml
> +            - while :; do kubectl get pod | grep Completed | awk '{print $1}' | xargs --no-run-if-empty kubectl delete pod | xargs --no-run-if-empty echo `date "+%Y-%m-%d %H:%M:%S"`; sleep 300; done
This doesn't handle namespaced airbyte deployments. It also doesn't limit itself to just pods that were created as part of Airbyte.

Probably the easiest way to do this is to add a label to all connector pods / command fetcher pods that makes it easy to `kubectl get` them by this label. Then you can also insert the namespace used in a similar way that we pulled it in as an env variable before, and use that to scope the search for pods.

2021-07-02 14:19 UTC, jrhizor requested changes
Needs to address some more edge cases but I like the simple bash pod approach.

2021-07-02 17:28 UTC, jrhizor approved these changes
Looks good. 

We should only clear pods that are not `Running` and that are older than maybe 1 day. Right now I think this will kill things that are currently running.

It would be nice to also log the name and status for deleted pod on the sweeper.

2021-07-02 19:07 UTC, ChristopheDuong commented
> We should only clear pods that are not Running and that are older than maybe 1 day.

There is a grep on Completed, is it possible for them to be completed and running at the same time?

2021-07-02 21:56 UTC, jrhizor commented
Pods might be stuck in an `Error` or `Pending` state, so I think the "not running" condition might be better than "completed". And if we're going to sweep those states we probably want a time window for debugging the pods.

2021-07-06 17:58 UTC, jrhizor approved these changes
nice!

2021-07-07 08:32 UTC, merged