🎉 New destination: GlassFlow
airbytehq/airbyte pull request #45082
Opened 2024-09-02 09:20 UTC by PabloPardoGarcia

## What
- New destination: [GlassFlow](https://www.glassflow.dev/)

## How

- Sends data to GlassFlow pipeline
- pipeline_id and pipeline_access_token supported for connecting to GlassFlow pipeline
- `check` creates a connection to GlassFlow, then the pipeline is consumed and succeeds is there is not exception. If fails otherwise.
- Add  stream name, namespace and emmited_at as top level fields in the GlassFlow pipeline message. This can be used by consumers to filter by them.
- GlassFlow message data is serialized as JSON.

## Review guide

1. destination.py
2. unit_test.py
3. integration_test.py

## User Impact

- A new connector destination available

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌

2024-09-02 12:15 UTC, PabloPardoGarcia commented
I tested the connector locally and worked as expected
<img width="1276" alt="Screenshot 2024-09-02 at 14 13 44" src="https://github.com/user-attachments/assets/c0b2bdef-ac3c-489e-88c9-903510d3721a">
<img width="889" alt="Screenshot 2024-09-02 at 14 15 13" src="https://github.com/user-attachments/assets/3a2d4b64-2669-45b9-8a23-b1fc3f4d2157">

2024-09-08 17:21 UTC, marcosmarxm requested changes
Sorry for the delay in reviewing your contribution, @PabloPardoGarcia. I have added it to my to-do list and hope to complete the first review by next week.

2024-11-01 08:40 UTC, PabloPardoGarcia commented
Hi @marcosmarxm, do you have any updates on this PR?

2024-11-04 16:19 UTC, marcosmarxm commented
Hello @PabloPardoGarcia at the moment I'm responsible to review all hackathon contributions and it wil take around 2-3 weeks to finish them.

2025-02-06 14:24 UTC, marcosmarxm commented
@PabloPardoGarcia im trying to catch up with contribution backlog. new destinations aren't the priority right now but hope to get them in 2 weeks.

2025-02-11 01:08 UTC, marcosmarxm commented
Hello 👋, I apologize if your contribution hasn't been reviewed or updated yet. I'm working to address the community contribution backlog. I created this [GitHub project](https://github.com/orgs/airbytehq/projects/108/views/4) to help you understand when to expect a review. This week, my goal is to complete all contributions related to Marketplace and Manifest-only connectors. Next week, I will focus on API Certified Connectors, followed by DB Java Connector contributions. If you have any questions about your contribution, please feel free to send me a direct message in the Airbyte Community Slack (and include the link to your pull request).

2025-03-14 18:48 UTC, marcosmarxm approved these changes

2025-03-25 16:31 UTC, marcosmarxm commented
Merged at https://github.com/airbytehq/airbyte/pull/56389

2025-03-25 16:31 UTC, closed without merging