Snowflake: Handling large records
airbytehq/airbyte pull request #45139
Opened 2024-09-04 19:52 UTC by Vee7574

## What
Implementing the handling of large records in the snowflake destination connector to fix the issue mentioned in this ticket:
https://github.com/airbytehq/oncall/issues/6245

## How
Removing large values from the record using these steps:

- Snowflake has a max size (16 MB) for the content we can fit into a VARIANT column, which we use to load all the record’s into the raw tables
- If we exceed this size, we need to remove (null out) properties until the record fits.  There’s an algorithm in destination-redshift for this we can port over.
- We should never null out the PK, CDC delete columns, or cursors

## Review guide
Please review the code to confirm the removal of null values is being done as per the requirements mentioned above.

## User Impact
Large values from records will be removed so users may see null values for some fields in the destination records.

## Can this PR be safely reverted and rolled back?

- [ X] YES 💚
- [ ] NO ❌

2024-09-05 21:18 UTC, stephane-airbyte commented on airbyte-integrations/connectors/destination-snowflake/src/main/kotlin/io/airbyte/integrations/destination/snowflake/typing_deduping/SnowflakeSuperLimitationTransformer.kt
> +    private data class ScalarNodeModification(
this seems extremely complex for what is essentially a column-nullifier

2024-09-05 21:25 UTC, gisripa requested changes

2024-09-05 21:25 UTC, gisripa commented on airbyte-integrations/connectors/destination-snowflake/src/main/kotlin/io/airbyte/integrations/destination/snowflake/SnowflakeDestination.kt
> +        // composition.
I'm not sure what this comment here means.

2024-09-05 21:25 UTC, gisripa commented on airbyte-integrations/connectors/destination-snowflake/src/main/kotlin/io/airbyte/integrations/destination/snowflake/typing_deduping/SnowflakeSuperLimitationTransformer.kt
> +        //println("Traversing the record to NULL fields for snowflake size limitations")
Remove all commented out TODOs and println statements.

2024-09-05 21:25 UTC, gisripa commented on airbyte-integrations/connectors/destination-snowflake/src/main/kotlin/io/airbyte/integrations/destination/snowflake/typing_deduping/SnowflakeSuperLimitationTransformer.kt
> +        val DEFAULT_PREDICATE_VARCHAR_GREATER_THAN_64K: Predicate<String> =
Rename it appropriately to the predicate it is testing for.

2025-08-14 17:22 UTC, cgardens commented
We are closing this PR due to inactivity. We regularly close PRs that were created more than 6 months ago. If you'd like to keep working on it, please feel free reopen it. We'd be happy to keep working with you.

2025-08-14 17:22 UTC, closed without merging