SAT: Validate config according to specification
airbytehq/airbyte pull request #4565
Opened 2021-07-06 12:33 UTC by yevhenii-ldv

## What
*closes #4299.*

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## Pre-merge Checklist
Expand the checklist which is relevant for this PR. 

<details><summary> <strong> Connector checklist </strong> </summary>
<p>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Secrets are annotated with `airbyte_secret` in the connector's spec
- [ ] Credentials added to Github CI if needed and not already present. [instructions for injecting secrets into CI](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#using-credentials-in-ci). 
- [ ] Unit & integration tests added as appropriate (and are passing)
    * Community members: please provide proof of this succeeding locally e.g: screenshot or copy-paste acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] `/test connector=connectors/<name>` command as documented [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-an-existing-connector) is passing. 
    * Community members can skip this, Airbyters will run this for you. 
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] `README.md`
    - [ ] `docs/SUMMARY.md` if it's a new connector
    - [ ] Created or updated reference docs in `docs/integrations/<source or destination>/<name>`.
    - [ ] Changelog in the appropriate page in `docs/integrations/...`. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md` contains a reference to the new connector
    - [ ] Build status added to [build page](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/builds.md)
- [ ] Build is successful
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] No major blockers
- [ ] PR merged into master branch
- [ ] Follow up tickets have been created
- [ ] Associated tickets have been closed & stakeholders notified
</p>
</details>

<details><summary> <strong> Connector Generator checklist </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

2021-07-06 12:43 UTC, htrueman approved these changes
LGTM. One small update suggested.

2021-07-06 12:43 UTC, htrueman commented on airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py
> +    def test_spec(self, connector_spec: ConnectorSpecification, connector_config, docker_runner: ConnectorRunner):
Consider adding type annotation?

2021-07-06 12:44 UTC, Zirochkaa commented on airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py
> +    def test_spec(self, connector_spec: ConnectorSpecification, connector_config, docker_runner: ConnectorRunner):
What type is `connector_config` have?

2021-07-06 12:44 UTC, Zirochkaa commented on airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/config.py
> +    config_path: str = config_path
Why do we need this?

2021-07-06 15:54 UTC, keu requested changes
don't forget to update changelog and version

2021-07-07 03:02 UTC, Zirochkaa approved these changes

2021-07-07 06:50 UTC, keu approved these changes

2021-07-07 13:25 UTC, yevhenii-ldv commented
/publish connector=bases/source-acceptance-test

2021-07-07 13:53 UTC, yevhenii-ldv commented
/publish connector=bases/source-acceptance-test

2021-07-07 13:59 UTC, merged