intial files
airbytehq/airbyte pull request #45876
Opened 2024-09-24 14:02 UTC by teetangh

## What

## How

## Review guide

## User Impact

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

2024-09-24 14:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=45876) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=45876) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=45876) it.</sub>

2025-01-14 13:39 UTC, deniswsrosa commented
Any updates on this one?

2025-02-11 01:08 UTC, marcosmarxm commented
Hello 👋, I apologize if your contribution hasn't been reviewed or updated yet. I'm working to address the community contribution backlog. I created this [GitHub project](https://github.com/orgs/airbytehq/projects/108/views/4) to help you understand when to expect a review. This week, my goal is to complete all contributions related to Marketplace and Manifest-only connectors. Next week, I will focus on API Certified Connectors, followed by DB Java Connector contributions. If you have any questions about your contribution, please feel free to send me a direct message in the Airbyte Community Slack (and include the link to your pull request).

@teetangh make sure to sign the CLA until there.

2025-03-06 19:12 UTC, marcosmarxm reviewed
@teetangh the implementation looks good. I'll create a Couchbase cloud account to run integration tests. I hope to get this done next week.

2025-03-06 19:49 UTC, marcosmarxm requested changes

2025-03-06 19:49 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-couchbase/metadata.yaml
> +            alias: airbyte-connector-testing-secret-store
@teetangh please comment these lines for now.

2025-03-06 20:03 UTC, teetangh commented on airbyte-integrations/connectors/source-couchbase/metadata.yaml
> +            alias: airbyte-connector-testing-secret-store
have commented these lines for now

2025-03-07 16:10 UTC, marcosmarxm approved these changes

2025-03-07 16:35 UTC, merged