feat: Glide destination
airbytehq/airbyte pull request #45915
Opened 2024-09-25 23:01 UTC by activescott

## What
This is an Airbyte Destination for Glide.

## How
Implemented as Python destination using the Airbyte's prescribed guidance and generation script. Supports overwrite mode only.

## Review guide

See `airbyte-integrations/connectors/destination-glide/**/*`

## User Impact

Once this is cleaned up and published customers will be able synchronize data via Airbyte to Glide applications.

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

2024-09-25 23:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=45915) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=45915) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: activescott<br/>:x: chkn<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=45915) it.</sub>

2024-09-25 23:02 UTC, activescott commented
Opening a fresh one per Teo @ Airbyte. Looking forward to feedback we can take into account to get this merged.

2024-09-26 22:45 UTC, marcosmarxm requested changes
@activescott thanks! need both contributors sign the CLA.

2024-10-07 22:56 UTC, marcosmarxm commented
@activescott I'll take some time to review your contribution sorry the delay

2024-10-28 17:14 UTC, marcosmarxm commented
@activescott at the moment Airbyte is running the annual October Hackathon and all team efforts are to review/merge those contributions. I'm going to be able to return to yours only next week, srry the delay.

2025-01-04 09:01 UTC, closed without merging