fix issue #22359 - connect to named instance
airbytehq/airbyte pull request #45920
Opened 2024-09-26 09:46 UTC by jbrissier

"For optimal connection performance, you should set the portNumber when you connect to a named instance. This will avoid a round trip to the server to determine the port number. If both a portNumber and instanceName are used, the portNumber will take precedence and the instanceName will be ignored."

https://learn.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-ver16

## What
I changed the default setting of the port, and don't apply it to the connection string

## How
new connection string 

## Review guide

## User Impact
No default port needed for mssql server 

## Can this PR be safely reverted and rolled back?

- [ x ] YES 💚
- [ ] NO ❌

2024-09-26 09:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=45920) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=45920) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=45920) it.</sub>

2024-09-26 09:47 UTC, jbrissier commented
Try to fix the issue for #22359,

2024-09-26 22:38 UTC, marcosmarxm requested changes
@theyueli can someone from db team can take a look into this change?

@jbrissier can you bump the connector version in the ` metadata.yaml` file and include an entry in the changelog section in the connector doc?

2024-09-27 06:45 UTC, jbrissier commented
@marcosmarxm bumped the version to 4.1.15.

But i don't finde any section to add the description / changelog. I only found the section with breaking changes ?!

2024-09-30 09:02 UTC, theyueli commented
Thanks for the contribution! 

If such a round trip happens only once initially, the performance improvement of this PR would be negligible. Is this correct?

2024-09-30 09:39 UTC, jbrissier commented
@theyuel iI think so. I'm not 100% sure, but it is still possible to connect with the port to ensure optimal performance.

2024-12-10 09:01 UTC, closed without merging