source-google-calendar contribution from bala-ceg
airbytehq/airbyte pull request #46306
Opened 2024-10-02 10:25 UTC by bala-ceg

## What

This PR adds a new connector for source Google Calendar (source-google-calendar).

Contributor-provided connector description:

Solves https://github.com/airbytehq/airbyte/issues/45995
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `client_id` | `string` | Client ID.  |  |
| `client_secret` | `string` | Client secret.  |  |
| `client_refresh_token_2` | `string` | Refresh token.  |  |
| `calendarid` | `string` | Calendar Id.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| colors |  | No pagination | ✅ |  ❌  |
| settings | id | DefaultPaginator | ✅ |  ❌  |
| calendarlist | id | DefaultPaginator | ✅ |  ❌  |
| calendars | id | DefaultPaginator | ✅ |  ❌  |
| events |  | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

2024-10-03 18:05 UTC, marcosmarxm requested changes
Left some comments.

2024-10-06 18:47 UTC, bala-ceg commented on docs/integrations/sources/google-calendar.md
> +Solves https://github.com/airbytehq/airbyte/issues/45995
Updated the Readmed.md

2024-10-06 18:48 UTC, bala-ceg commented on docs/integrations/sources/google-calendar.md
> +| events |  | DefaultPaginator | ✅ |  ❌  |
Thanks @marcosmarxm. I updated the stream.

2024-10-07 17:14 UTC, marcosmarxm approved these changes
LGTM Awesome contribution!

2024-10-07 17:26 UTC, merged