source-incident contribution from aazam-gh
airbytehq/airbyte pull request #46333
Opened 2024-10-03 11:01 UTC by aazam-gh

## What

This PR adds a new connector for source Incident (source-incident).

Contributor-provided connector description:

Source connector for Incident which is an on all, incident response and status pages tool. 
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key` | `string` | API Key. API key to use. Find it at https://app.incident.io/settings/api-keys |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| actions | id | No pagination | ✅ |  ❌  |
| catalog_types | id | No pagination | ✅ |  ❌  |
| custom_fields | id | No pagination | ✅ |  ❌  |
| follow-ups | id | No pagination | ✅ |  ❌  |
| incident_roles | id | No pagination | ✅ |  ❌  |
| incident_timestamps | id | No pagination | ✅ |  ❌  |
| incident_updates | id | DefaultPaginator | ✅ |  ❌  |
| incident_statuses | id | No pagination | ✅ |  ❌  |
| workflows | id | No pagination | ✅ |  ❌  |
| users | id | DefaultPaginator | ✅ |  ❌  |
| severities | id | No pagination | ✅ |  ❌  |
| schedules | id | DefaultPaginator | ✅ |  ❌  |
| incidents | id | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

2024-10-03 13:36 UTC, natikgadzhi commented
I think we already have incident.io source, cc @marcosmarxm

2024-10-03 14:15 UTC, marcosmarxm commented
> I think we already have incident.io source, cc @marcosmarxm

We don't have yet

2024-10-03 17:58 UTC, marcosmarxm requested changes
Some comments.

2024-10-03 17:58 UTC, marcosmarxm commented on docs/integrations/sources/incident.md
> +Source connector for Incident which is an on all, incident response and status pages tool.
Please improve the description. Include url to api docs and service website.

2024-10-03 17:58 UTC, marcosmarxm commented on docs/integrations/sources/incident.md
> +| incidents | id | DefaultPaginator | ✅ |  ❌  |
Some endpoints have support to use incremental, do you mind implement them?

2024-10-05 03:00 UTC, natikgadzhi commented
Huh! Alright, let's name it `source-incident-io` then, they're very recognizable with that name specifically. /cc @marcosmarxm

2024-10-07 17:20 UTC, marcosmarxm requested changes
Contribution looks great @aazam-gh can you just rename to `incident-io` to make clear what service the connector is about? Thanks

2024-10-07 19:44 UTC, natikgadzhi commented on docs/integrations/sources/incident-io.md
> +You can create an account here https://incident.io/
Linking to the vendor home page without clarifying how to navigate to the page where I can make a token is not good enough.

2024-10-07 19:44 UTC, natikgadzhi commented on docs/integrations/sources/incident-io.md
> +This is the setup guide for the Incident.io source connector which ingests data from the incident API.
This sentence is not clear enough. What are the two most useful streams? 

Calling this a guide is not necessary. It's pretty obvious it's a guide from where we render this page.

2024-10-08 16:28 UTC, marcosmarxm approved these changes
Thanks @aazam-gh !

2024-10-08 16:59 UTC, merged