source-rootly contribution from gemsteam
airbytehq/airbyte pull request #46351
Opened 2024-10-03 16:55 UTC by gemsteam

## What
Closes https://github.com/airbytehq/airbyte/issues/46042
This PR adds a new connector for source Rootly (source-rootly).

Contributor-provided connector description:

Documentation: https://rootly.com/api#/
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key` | `string` | API Key.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| dashboards | id | DefaultPaginator | ✅ |  ❌  |
| incidents | id | DefaultPaginator | ✅ |  ❌  |
| authorizations | id | DefaultPaginator | ✅ |  ❌  |
| dashboards_panels | id | DefaultPaginator | ✅ |  ❌  |
| users | id | DefaultPaginator | ✅ |  ❌  |
| incident_types | id | DefaultPaginator | ✅ |  ❌  |
| ip_ranges | id | DefaultPaginator | ✅ |  ❌  |
| users_notification_rules | id | DefaultPaginator | ✅ |  ❌  |
| teams | id | DefaultPaginator | ✅ |  ❌  |
| sub_statuses | id | DefaultPaginator | ✅ |  ❌  |
| incidents_sub_statuses | id | DefaultPaginator | ✅ |  ❌  |
| incident_roles | id | DefaultPaginator | ✅ |  ❌  |
| post_mortems | id | DefaultPaginator | ✅ |  ❌  |
| status-pages | id | DefaultPaginator | ✅ |  ❌  |
| severities | id | DefaultPaginator | ✅ |  ❌  |
| services | id | DefaultPaginator | ✅ |  ❌  |
| incident_permission_sets | id | DefaultPaginator | ✅ |  ❌  |
| incident_permission_sets_resources | id | DefaultPaginator | ✅ |  ❌  |
| incident_permission_sets_booleans | id | DefaultPaginator | ✅ |  ❌  |
| roles | id | DefaultPaginator | ✅ |  ❌  |
| incidents_events | id | DefaultPaginator | ✅ |  ❌  |
| workflows | id | DefaultPaginator | ✅ |  ❌  |
| workflow_groups | id | DefaultPaginator | ✅ |  ❌  |
| workflows_tasks | id | DefaultPaginator | ✅ |  ❌  |
| form_sets | id | DefaultPaginator | ✅ |  ❌  |
| form_fields | id | DefaultPaginator | ✅ |  ❌  |
| playbooks | id | DefaultPaginator | ✅ |  ❌  |
| incidents_action_items | id | DefaultPaginator | ✅ |  ❌  |
| retrospective_configurations | id | DefaultPaginator | ✅ |  ❌  |
| retrospective_processes | id | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [x] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

2024-10-03 16:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=46351) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=46351) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=46351) it.</sub>

2024-10-03 17:19 UTC, natikgadzhi reviewed
Wow, this is very promising. Good work!

2024-10-03 17:19 UTC, natikgadzhi commented on docs/integrations/sources/rootly.md
> +| dashboards | id | DefaultPaginator | ✅ |  ❌  |
Wow, nice list of streams! 👏🏼

2024-10-03 17:19 UTC, natikgadzhi commented on docs/integrations/sources/rootly.md
> +Documentation: https://rootly.com/api#/
```suggestion
Documentation: [https://rootly.com/api#/](https://rootly.com/api#/)
```

2024-10-03 18:28 UTC, marcosmarxm requested changes

2024-10-04 14:37 UTC, marcosmarxm commented
@gemsteam can you sign the CLA please?

2024-10-07 17:38 UTC, marcosmarxm commented on docs/integrations/sources/rootly.md
> +| incidents | id | DefaultPaginator | ✅ |  ❌  |
What about adding a transformation to move `updated_at` to higher level?
<img width="628" alt="image" src="https://github.com/user-attachments/assets/618c1455-1488-49c1-bd1c-5a44afb36c49">

2024-10-08 17:00 UTC, marcosmarxm requested changes
Please check my latest comment about how implement incremental.

2024-10-09 09:42 UTC, closed without merging