✨ Source Freshcaller : Migrate to Manifest-only
airbytehq/airbyte pull request #46472
Opened 2024-10-05 13:57 UTC by topefolorunso

2024-10-05 14:00 UTC, topefolorunso commented
/format-fix

2024-10-06 04:16 UTC, natikgadzhi requested changes
The CI says that incremental reads are broken and always return the same records. Probably filtering by updated at is broken.

2024-10-07 03:06 UTC, natikgadzhi commented
```
16 new failing acceptance tests detected:
-test_core.py::TestDiscovery::test_defined_refs_exist_in_schema[inputs0]
-test_core.py::TestDiscovery::test_defined_keyword_exist_in_schema[inputs0-not]
-test_core.py::TestDiscovery::test_streams_has_sync_modes[inputs0]
-test_full_refresh.py::TestFullRefresh::test_sequential_reads[inputs0]
-test_core.py::TestDiscovery::test_backward_compatibility[inputs0]
-test_core.py::TestBasicRead::test_read[inputs0]
-test_incremental.py::TestIncremental::test_state_with_abnormally_large_values[inputs0]
-test_core.py::TestDiscovery::test_primary_keys_exist_in_schema[inputs0]
-test_incremental.py::TestIncremental::test_two_sequential_reads[inputs0]
-test_core.py::TestDiscovery::test_defined_keyword_exist_in_schema[inputs0-allOf]
-test_core.py::TestDiscovery::test_primary_keys_data_type[inputs0]
-test_incremental.py::TestIncremental::test_read_sequential_slices[inputs0]
-test_core.py::TestDiscovery::test_defined_cursors_exist_in_schema[inputs0]
-test_core.py::TestDiscovery::test_streams_have_valid_json_schemas[inputs0]
-test_core.py::TestConnection::test_check[inputs1]
-test_core.py::TestDiscovery::test_additional_properties_is_true[inputs0]
-test_core.py::TestConnection::test_check[inputs0]
-test_core.py::TestDiscovery::test_discover[inputs0]
Please fix the new failing tests before merging this PR.
```

@topefolorunso nope, that backfired.

2024-10-17 20:48 UTC, topefolorunso commented
> The CI says that incremental reads are broken and always return the same records. Probably filtering by updated at is broken.

@natikgadzhi see your comment here https://github.com/airbytehq/airbyte/pull/40618#discussion_r1664905398. Could something similar be happening here?

2024-10-19 00:20 UTC, ChristoGrab commented
Took a look at the failing test. I think it's possible the failure is caused by the stream only containing a single record. So 1st read, we don't have state and set it to the value of the sole record. 2nd read, we set state to the value of the record's cursor field, which is equal to itself and therefore read again.

Unfortunately the only connection I could find for progressive rollouts is a forbidden fancy-tier workspace. Regression tests are saying they can't find a connector at the latest version, but that seems sus since I can see the syncs in Metabase. Gonna try and run the tests in GHA manually.

2025-02-24 03:11 UTC, natikgadzhi commented
cleanup the conflicts, let's merge this

2025-02-27 08:05 UTC, topefolorunso commented
Cleaned up here @natikgadzhi

2025-03-01 06:08 UTC, natikgadzhi commented
One failing CAT test in incremental tests: "AssertionError: Records should change between reads but did not."

2025-03-02 14:49 UTC, topefolorunso commented
> One failing CAT test in incremental tests: "AssertionError: Records should change between reads but did not."

Could this have anything to do with @ChristoGrab's earlier comment [here](https://github.com/airbytehq/airbyte/pull/46472#issuecomment-2423399771)

2025-03-02 19:14 UTC, topefolorunso commented
/format-fix

2025-03-02 20:04 UTC, topefolorunso commented
@natikgadzhi Update:  Time Travel in Incremental Sync

The failing incremental test is due to time zone correction of the datetime parameter. 

The record pulled in the first sequential read has `created_time` (`cursor_field`) in `-0700` but the `cursor_value` is stored in `+0000`. Hence, during the second sequential read, the datetime parameter is set to 7 hours into the past i.e using the `cursor_value` stored in `+0000` which makes the api return the same record naively.

Temporary fix: Maintained the time zone received from the api when storing the state and cursor_value. Same time zone is used when making subsequent requests with the state. What happens if there are different records returned with different time zones?

More permanent fix would be to find a way to correct all incoming datetime from records to +0000 before storing them as state values

2025-03-02 20:10 UTC, topefolorunso commented
Also worthy of note in this PR - I removed the incremental sync for calls stream because the endpoint is not configured properly for time filtering with same parameters as `calls_metrics`.

2025-03-02 20:19 UTC, natikgadzhi commented
It's really inspiring to see such a deep dive into failure reasons. Thank you @topefolorunso!

2025-03-12 18:44 UTC, natikgadzhi commented
Alright, so — everything related to calls should stay incremental if it was incremental before. The reason for this is the quality of the experience for our users — you'd assume they have a LOT of calls, and you don't want to increase sync time linearly with data volume growth. 

@brianjlai can you take a look and advice @topefolorunso on how to go about the cursor? If you have time for a loom, that would prob help us level up Tope so he can figure out situations like this in the future.

2025-03-12 21:19 UTC, topefolorunso commented
/format-fix

2025-03-12 23:07 UTC, natikgadzhi commented
Ideally cursor datetime timezone conversions should be automatic too =/

2025-03-14 12:03 UTC, topefolorunso commented
/format-fix

2025-08-14 17:22 UTC, cgardens commented
We are closing this PR due to inactivity. We regularly close PRs that were created more than 6 months ago. If you'd like to keep working on it, please feel free reopen it. We'd be happy to keep working with you.

2026-04-30 16:51 UTC, closed without merging