source-smartwaiver contribution from avirajsingh7
airbytehq/airbyte pull request #46665
Opened 2024-10-09 08:10 UTC by avirajsingh7

## What

This PR adds a new connector for source Smartwaiver (source-smartwaiver).

Contributor-provided connector description:

The Smartwaiver connector for Airbyte enables seamless integration with the Smartwaiver API, allowing users to automate the extraction of waiver-related data. Smartwaiver is a platform that digitizes waivers, converting them into customizable, legally-binding documents with signatures.
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key` | `string` | API Key. You can retrieve your token by visiting your dashboard then click on My Account then click on API keys. |  |
| `start_date` | `string` | Start Date.  | 2017-01-24 13:12:29 |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| templates | templateId | No pagination | ✅ |  ❌  |
| signed_waivers | waiverId | DefaultPaginator | ✅ |  ❌  |
| detailed_signed_waiver | waiverId | No pagination | ✅ |  ❌  |
| checkins | waiverId | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

2024-10-16 20:11 UTC, marcosmarxm requested changes
Let's follow this strategy:
1. you can retrieve all templates from `templates` stream
2. use `/search` with template as parent to retrieve all waivers associated with a template
3. for `checkins` you can use offset as pagination, correct?

Let me know what are you thoughts about this path

2024-10-17 13:43 UTC, avirajsingh7 commented
@marcosmarxm 
For Checkins :
offset  integer optional  
Offset to be combined with limit to page results. Default value: 0 Allowed values 0-1000
offset can have max value of 1000 but with current implementation we can get all records

For Search as substream :
Note: This request is not included in the normal 100 request per minute limit, but is instead limited to 5 requests per minute by itself.
This API rate is very low and still it is limited to 30k signed waiver but with current implementation we can get all records

2024-10-21 19:55 UTC, marcosmarxm commented
Hello 👋 Due to the numerous contributions happening, I decided to create this [view](https://github.com/orgs/airbytehq/projects/104/views/3) to help you know when I plan to review your contribution. If your connector has some limited-time credential feel free to reach me out.

2024-10-21 20:14 UTC, marcosmarxm approved these changes

2024-10-21 21:32 UTC, merged