source-squarespace contribution from avirajsingh7
airbytehq/airbyte pull request #46705
Opened 2024-10-10 13:30 UTC by avirajsingh7

## What

This PR adds a new connector for source Squarespace (source-squarespace).

Contributor-provided connector description:

The Squarespace connector enables seamless integration with your Squarespace store, allowing you to sync data from various key endpoints
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key` | `string` | API Key. API key to use. Find it at https://developers.squarespace.com/commerce-apis/authentication-and-permissions |  |
| `start_date` | `string` | Start date. Any data before this date will not be replicated. |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| inventory | variantId | DefaultPaginator | ✅ |  ❌  |
| store_pages | id | DefaultPaginator | ✅ |  ❌  |
| products | id | DefaultPaginator | ✅ |  ✅  |
| profiles | id | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

2024-10-12 11:11 UTC, marcosmarxm requested changes

2024-10-12 11:11 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-squarespace/manifest.yaml
> +    orders:
This isn't described in the docs please check that.

2024-10-12 11:11 UTC, marcosmarxm commented on docs/integrations/sources/squarespace.md
> +| profiles | id | DefaultPaginator | ✅ |  ❌  |
Missing some streams.

2024-10-16 20:52 UTC, marcosmarxm commented
@avirajsingh7 did you have time to take a look in my comments?

2024-10-17 13:26 UTC, avirajsingh7 commented on docs/integrations/sources/squarespace.md
> +| profiles | id | DefaultPaginator | ✅ |  ❌  |
@marcosmarxm  done added

2024-10-17 13:27 UTC, avirajsingh7 commented
@marcosmarxm sorry for delay, I have updated a docs

2024-10-22 19:48 UTC, marcosmarxm approved these changes
Great contribution @avirajsingh7

2024-10-22 19:57 UTC, merged