source-uppromote contribution from avirajsingh7
airbytehq/airbyte pull request #46715
Opened 2024-10-10 15:48 UTC by avirajsingh7

## What

This PR adds a new connector for source UpPromote (source-uppromote).

Contributor-provided connector description:

The Uppromote Connector for Airbyte enables seamless data integration between Uppromote, an affiliate and influencer marketing platform, and your data warehouses or analytics tools.
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key` | `string` | API Key. For developing your own custom integration with UpPromote, you can create an API key. This is available from Professional plan.  Simply go to Settings &gt; Integration &gt; API &gt; Create API Key.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| affiliates | id | DefaultPaginator | ✅ |  ❌  |
| coupons | id | DefaultPaginator | ✅ |  ❌  |
| referrals | id | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

2024-10-12 11:32 UTC, marcosmarxm requested changes

2024-10-12 11:32 UTC, marcosmarxm commented on docs/integrations/sources/uppromote.md
> +| referrals | id | DefaultPaginator | ✅ |  ❌  |
Referrals you can implement incremental https://aff-api.secomapp.com/docs/index.html#get-list-referrals can you check it? Thanks.

2024-10-17 13:34 UTC, avirajsingh7 commented
@marcosmarxm Referrals is incremental now

2024-10-17 18:01 UTC, marcosmarxm approved these changes
Nice contribution @avirajsingh7

2024-10-17 20:08 UTC, merged