source-katana contribution from aazam-gh
airbytehq/airbyte pull request #46762
Opened 2024-10-12 12:12 UTC by aazam-gh

## What

This PR adds a new connector for source Katana (source-katana).

Contributor-provided connector description:

This is the Katana source connector that ingests data from the katana API.

Katana is a real-time cloud inventory platform to manage sales channels, products, and materials to always be ready to meet demands.  You can find more about it here https://katanamrp.com/

This source uses OAuth Bearer Token for authentication. In order to obtain your API token, you must first create an account on Katana and be on their Professional Plan. 

To generate a live API key: log in to your Katana account.  Go to Settings &gt; API. Select Add new API key. You can find more about the API here https://developer.katanamrp.com/reference/api-introduction
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key` | `string` | API Key. API key to use. Find it at https://katanamrp.com/login/ |  |
| `start_date` | `string` | Start date.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| customers | id | DefaultPaginator | ✅ |  ✅  |
| shipping_fee |  | DefaultPaginator | ✅ |  ❌  |
| costs | id | DefaultPaginator | ✅ |  ✅  |
| customer_addresses | id | DefaultPaginator | ✅ |  ✅  |
| variants | id | DefaultPaginator | ✅ |  ✅  |
| tax_rates | id | DefaultPaginator | ✅ |  ✅  |
| suppliers | id | DefaultPaginator | ✅ |  ✅  |
| stocktakes | id | DefaultPaginator | ✅ |  ✅  |
| stock_adjustments | id | DefaultPaginator | ✅ |  ✅  |
| sales_orders | id | DefaultPaginator | ✅ |  ✅  |
| sales_order_fulfillments | id | DefaultPaginator | ✅ |  ❌  |
| sales_order_addresses | id | DefaultPaginator | ✅ |  ✅  |
| recipes | ingredient_variant_id.product_variant_id | DefaultPaginator | ✅ |  ✅  |
| purchase_orders | id | DefaultPaginator | ✅ |  ✅  |
| products | id | DefaultPaginator | ✅ |  ✅  |
| price_lists | id | DefaultPaginator | ✅ |  ❌  |
| inventory | variant_id | DefaultPaginator | ✅ |  ❌  |
| locations | id | DefaultPaginator | ✅ |  ✅  |
| manufacturing_orders | id | DefaultPaginator | ✅ |  ✅  |
| materials | id | DefaultPaginator | ✅ |  ✅  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

2024-10-14 13:37 UTC, marcosmarxm requested changes

2024-10-14 13:37 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-katana/manifest.yaml
> +        requester:
Missing `limit` parameter to inject into HTTPs requests for pagination. Please check to all streams.

<img width="643" alt="image" src="https://github.com/user-attachments/assets/1a6ef0f0-50dc-4d5d-80b7-f45c1c9b7ee5">

2024-10-21 19:56 UTC, marcosmarxm commented
Hello 👋 Due to the numerous contributions happening, I decided to create this [view](https://github.com/orgs/airbytehq/projects/104/views/3) to help you know when I plan to review your contribution. If your connector has some limited-time credential feel free to reach me out.

2024-10-23 03:28 UTC, aazam-gh commented
Trial ending in 2 days

2024-10-23 17:47 UTC, marcosmarxm approved these changes

2024-10-23 18:18 UTC, merged