✨ Source-Stripe: Add incremental stream support to accounts stream
airbytehq/airbyte pull request #46864
Opened 2024-10-12 17:08 UTC by williamkaper

## What

## How

## Review guide

## User Impact

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

2024-10-12 17:19 UTC, williamkaper commented on docs/integrations/sources/stripe.md
> -- [Usage Records](https://stripe.com/docs/api/usage_records/subscription_item_summary_list)
This was causing the tests to fail - not sure how this got here...

2024-10-12 22:11 UTC, natikgadzhi commented
/format-fix

2024-10-18 23:20 UTC, natikgadzhi commented
Just calling out that I was slow this week, but someone on @airbytehq/dev-python will take a look in the next week, if we have a chance.

2024-11-04 11:07 UTC, alafanechere commented
/format-fix

2024-11-04 11:08 UTC, alafanechere commented
/format-fix

2024-11-04 14:54 UTC, alafanechere requested changes
Hey @williamkaper, thank you for this awesome contribution!
I'm requesting changes because I noticed a regression while running our internal test suite: when set in `full_refresh` mode the `customer_balance_transaction` stream is not producing any record. I can't identify the root cause of it, I'm quite new to this connector. 
I tried switching the class to `UpdatedCursorIncrementalStripeSubStream` instead of `UpdatedCursorIncrementalStripeLazySubStream` and the missing records get produced.
So it has something to do with the "lazyness".
Let me know if you can reproduce this problem.

@maxi297 is it legit to not use a lazy substream in this situation?

2024-11-04 14:56 UTC, alafanechere commented on docs/integrations/sources/stripe.md
> +| 5.6.3 | 2024-10-12 | [46864](https://github.com/airbytehq/airbyte/pull/46864) | Add incremental stream support to `accounts` stream |
```suggestion
| 5.7.0 | 2024-10-12 | [46864](https://github.com/airbytehq/airbyte/pull/46864) | Add incremental stream support to `accounts` and `customer_balance_transactions` streams |
```

2024-11-04 17:19 UTC, williamkaper commented
> Hey @williamkaper, thank you for this awesome contribution! I'm requesting changes because I noticed a regression while running our internal test suite: when set in `full_refresh` mode the `customer_balance_transaction` stream is not producing any record. I can't identify the root cause of it, I'm quite new to this connector. I tried switching the class to `UpdatedCursorIncrementalStripeSubStream` instead of `UpdatedCursorIncrementalStripeLazySubStream` and the missing records get produced. So it has something to do with the "lazyness". Let me know if you can reproduce this problem.
> 
> @maxi297 is it legit to not use a lazy substream in this situation?

How can I see the test failure easily? When I run airbyte-ci connectors --name source-stripe test I seem to get different transient results, but the actual test failure isn't cleanly surfaced

2024-11-04 17:39 UTC, alafanechere commented
> @alafanechere How can I see the test failure easily?

@williamkaper unfortunately you can't ATM. We run a regression test suite on our sandbox accounts. The reports are private because they might expose sensitive information.
Did you try running `customer_balance_transactions` in `full_refresh` in production?

2024-11-05 22:07 UTC, williamkaper commented
> > @alafanechere How can I see the test failure easily?
> 
> @williamkaper unfortunately you can't ATM. We run a regression test suite on our sandbox accounts. The reports are private because they might expose sensitive information. Did you try running `customer_balance_transactions` in `full_refresh` in production?

It doesn't appear full_refresh works. Do you want to change the stream type or want me to change the stream type?

2024-11-06 15:29 UTC, williamkaper commented
> > > @alafanechere How can I see the test failure easily?
> > 
> > 
> > @williamkaper unfortunately you can't ATM. We run a regression test suite on our sandbox accounts. The reports are private because they might expose sensitive information. Did you try running `customer_balance_transactions` in `full_refresh` in production?
> 
> It doesn't appear full_refresh works. Do you want to change the stream type or want me to change the stream type?

I just pushed it up

2024-11-12 19:57 UTC, williamkaper commented
@alafanechere where are we at on this? Is there anything you are waiting for me to do or is this now on your team's conveyor belt?

2024-11-29 10:19 UTC, alafanechere approved these changes
I made some fixes to get CI 🟢 .
Thanks @williamkaper for your contribution and patience!

2024-11-29 10:19 UTC, merged