source-concord contribution from aazam-gh
airbytehq/airbyte pull request #46899
Opened 2024-10-14 19:09 UTC by aazam-gh

## What

This PR adds a new connector for source Concord (source-concord).

Contributor-provided connector description:

This is the setup for the Concord source which ingests data from the concord API.

Concord turns contract data into financial insights. Sign, store and search unlimited contracts https://www.concord.app/

In order to use this source, you must first create a concord account and log in. Then navigate to Automations -&gt; Integrations -&gt; Concord API -&gt; Generate New Key to obtain your API key.

The API is accessible from two environments, sandbox and production. You can learn more about the API here https://api.doc.concordnow.com/
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key` | `string` | API Key.  |  |
| `enviornment` | `string` | enviornment. The environment from where you want to access the API. |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| agreements | uid | DefaultPaginator | ✅ |  ❌  |
| user_organizations | id | No pagination | ✅ |  ❌  |
| organization | id | No pagination | ✅ |  ❌  |
| folders | id | No pagination | ✅ |  ❌  |
| reports | id | DefaultPaginator | ✅ |  ❌  |
| tags | id | No pagination | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

2024-10-18 17:07 UTC, marcosmarxm requested changes
Can you also implement organizations membership and groups?

2024-10-18 17:07 UTC, marcosmarxm commented on docs/integrations/sources/concord.md
> +| `enviornment` | `string` | enviornment. The environment from where you want to access the API. |  |
```suggestion
| `environment` | `string` | environment. The environment from where you want to access the API. |  |
```

Fix typo. Can you link to Concord docs where to find the info?

2024-10-18 17:07 UTC, marcosmarxm commented on docs/integrations/sources/concord.md
> +In order to use this source, you must first create a concord account and log in. Then navigate to Automations -&gt; Integrations -&gt; Concord API -&gt; Generate New Key to obtain your API key.
```suggestion
In order to use this source, you must first create a concord account and log in. Then navigate to Automations -> Integrations -> Concord API -> Generate New Key to obtain your API key.
```

2024-10-21 19:57 UTC, marcosmarxm commented
Hello 👋 Due to the numerous contributions happening, I decided to create this [view](https://github.com/orgs/airbytehq/projects/104/views/3) to help you know when I plan to review your contribution. If your connector has some limited-time credential feel free to reach me out.

2024-10-24 07:27 UTC, aazam-gh commented
@marcosmarxm Ready for review again

2024-10-24 07:28 UTC, aazam-gh commented
> Can you also implement organizations membership and groups?

membership is added, groups would require team account, out of scope at the moment

2024-10-25 18:08 UTC, marcosmarxm approved these changes

2024-10-25 18:22 UTC, merged