source-spree-commerce contribution from Harmaton
airbytehq/airbyte pull request #46997
Opened 2024-10-18 15:23 UTC by Harmaton

## What

This PR adds a new connector for source Spree Commerce (source-spree-commerce).

Contributor-provided connector description:

A coonecor for spree commerce Platform API
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `base_url` | `string` | Base_URL.  |  |
| `client_id` | `string` | Client ID.  |  |
| `client_secret` | `string` | Client secret.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| List Users |  | DefaultPaginator | ✅ |  ❌  |
| Variants |  | DefaultPaginator | ✅ |  ❌  |
| List Products |  | DefaultPaginator | ✅ |  ❌  |
| Payments |  | DefaultPaginator | ✅ |  ❌  |
| Payment Methods |  | DefaultPaginator | ✅ |  ❌  |
| List Orders |  | DefaultPaginator | ✅ |  ❌  |
| Menus |  | DefaultPaginator | ✅ |  ❌  |
| Addresses |  | DefaultPaginator | ✅ |  ❌  |
| Classifications |  | DefaultPaginator | ✅ |  ❌  |
| Adjustments |  | DefaultPaginator | ✅ |  ❌  |
| CMS Pages |  | DefaultPaginator | ✅ |  ❌  |
| CMS Sections |  | DefaultPaginator | ✅ |  ❌  |
| Shipments |  | DefaultPaginator | ✅ |  ❌  |
| Shipping Categories |  | DefaultPaginator | ✅ |  ❌  |
| States |  | DefaultPaginator | ✅ |  ❌  |
| Stock Items |  | DefaultPaginator | ✅ |  ❌  |
| Stock Locations |  | DefaultPaginator | ✅ |  ❌  |
| Stock Credit Categories |  | DefaultPaginator | ✅ |  ❌  |
| Store Credit Types |  | DefaultPaginator | ✅ |  ❌  |
| Store Credits |  | DefaultPaginator | ✅ |  ❌  |
| Tax Categories |  | DefaultPaginator | ✅ |  ❌  |
| Tax Rates |  | DefaultPaginator | ✅ |  ❌  |
| Wished Items |  | DefaultPaginator | ✅ |  ❌  |
| Wishlists |  | DefaultPaginator | ✅ |  ❌  |
| Zones |  | DefaultPaginator | ✅ |  ❌  |
| Webhook Subscribers |  | DefaultPaginator | ✅ |  ❌  |
| Taxonomies |  | DefaultPaginator | ✅ |  ❌  |
| Taxons |  | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

2024-10-18 15:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=46997) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=46997) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=46997) it.</sub>

2024-10-18 16:47 UTC, natikgadzhi commented
Huh, somehow the documentation md file wasn't generated ;( You could look at things like `docs/integrations/sources/basecamp.md` as an example and make one.

2024-10-19 05:48 UTC, Harmaton commented
Is there a way to do this in the UI builder ?

2024-10-21 19:59 UTC, marcosmarxm commented
Hello 👋 Due to the numerous contributions happening, I decided to create this [view](https://github.com/orgs/airbytehq/projects/104/views/3) to help you know when I plan to review your contribution. If your connector has some limited-time credential feel free to reach me out.

2024-10-28 21:23 UTC, marcosmarxm requested changes
At the moment the connector wasn't tested and submited properly using the Connector Builder. Please check your submission, the review I made and create a new pull request. I'm closing this one.

2024-10-28 21:23 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-spree-commerce/manifest.yaml
> +description: A coonecor for spree commerce Platform API
Please provide a better description and check typos.

2024-10-28 21:23 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-spree-commerce/manifest.yaml
> +      streamHash: 81c15fe0f62280c1681ea8b538bacef3f52b115c
All streams weren't tested. I strongly suggest to build the connector using Airbyte Cloud.

2024-10-28 21:23 UTC, closed without merging

2024-10-28 21:24 UTC, marcosmarxm commented
If you're using Airbyte Open Source, please use latest version of the platform but I strongly recomend to use Airbyte Cloud to make contributions for the Hackathon.