✨ Source MongoDB-v2: Collect SSL parameter from user
airbytehq/airbyte pull request #47184
Opened 2024-10-21 16:02 UTC by cAtaman

## What
When creating connections with MongoDB-v2 connector, SSL is enforced in the connection to MongoDB. However, some internal, self-hosted MongoDB clusters may have been created without SSL by design. Currently, this connector cannot be used for such connections.

This PR is to enable users control whether the connection to the MongoDB cluster is made with or without SSL.

## How
- Update the Spec file to include a boolean field for enabling SSL
- Use the value from this field in setting up the MongoDB connection

## Review guide

## User Impact

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌

2024-10-21 16:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=47184) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=47184) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=47184) it.</sub>

2024-10-23 09:20 UTC, nifex007 commented on airbyte-integrations/connectors/source-mongodb-v2/src/main/java/io/airbyte/integrations/source/mongodb/cdc/MongoDbDebeziumPropertiesManager.java
> +    //properties.setProperty(MONGODB_SSL_ENABLED_KEY, MONGODB_SSL_ENABLED_VALUE);
remove  commented code.

2024-10-24 09:16 UTC, cAtaman commented on airbyte-integrations/connectors/source-mongodb-v2/src/main/java/io/airbyte/integrations/source/mongodb/cdc/MongoDbDebeziumPropertiesManager.java
> +    //properties.setProperty(MONGODB_SSL_ENABLED_KEY, MONGODB_SSL_ENABLED_VALUE);
```suggestion
```

2024-10-24 21:44 UTC, xiaohansong requested changes
Thanks for your contribution! Please see comments below. Looking good overall.

Please use airbyte-ci to run format fix.

2024-10-24 21:44 UTC, xiaohansong commented on airbyte-integrations/connectors/source-mongodb-v2/src/main/java/io/airbyte/integrations/source/mongodb/MongoDbSourceConfig.java
> +    return getDatabaseConfig().has(ENABLE_SSL_CONFIGURATION_KEY) ? getDatabaseConfig().get(ENABLE_SSL_CONFIGURATION_KEY).asBoolean() : true;
can we default this to false so it won't cause disruptions to existing users?

2024-10-24 21:44 UTC, xiaohansong commented on airbyte-integrations/connectors/source-mongodb-v2/src/main/resources/spec.json
I think you also need to update https://github.com/airbytehq/airbyte/blob/8f42de9c3757a09cf84db6d5b594a4d59132e9e7/airbyte-integrations/connectors/source-mongodb-v2/integration_tests/expected_spec.json

2025-02-11 01:07 UTC, marcosmarxm commented
Hello 👋, I apologize if your contribution hasn't been reviewed or updated yet. I'm working to address the community contribution backlog. I created this [GitHub project](https://github.com/orgs/airbytehq/projects/108/views/4) to help you understand when to expect a review. This week, my goal is to complete all contributions related to Marketplace and Manifest-only connectors. Next week, I will focus on API Certified Connectors, followed by DB Java Connector contributions. If you have any questions about your contribution, please feel free to send me a direct message in the Airbyte Community Slack (and include the link to your pull request).

2025-05-28 17:55 UTC, closed without merging