source-quora-ads contribution from bala-ceg
airbytehq/airbyte pull request #47238
Opened 2024-10-22 16:33 UTC by bala-ceg

## What

This PR adds a new connector for source Quora Ads (source-quora-ads).

Contributor-provided connector description:

Quora Ads API Connector allows you to sync advertising data between Quora Ads and external platforms, such as analytics tools, CRMs, or marketing dashboards. Quora Ads is a platform that enables businesses to reach relevant audiences through targeted advertising on Quora, helping drive brand awareness, engagement, and conversions. This connector streamlines the process of retrieving key ad performance data, making it easier to monitor campaigns and optimize marketing strategies.
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key` | `string` | API Key.  |  |
| `campaign_id` | `string` | Campaign Id.  |  |
| `ad_sets` | `string` | adsets.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| current_user |  | DefaultPaginator | ✅ |  ❌  |
| accounts | accountId | DefaultPaginator | ✅ |  ❌  |
| leadgenforms |  | DefaultPaginator | ✅ |  ❌  |
| campagins |  | DefaultPaginator | ✅ |  ❌  |
| adsets |  | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

2024-10-22 22:35 UTC, natikgadzhi requested changes
@marcosmarxm any ad platform connectors without actual converstion data and spend data are not really useful. With the high volume of data, those are usually especially sensitive to incremental reads.

Very often, performance reporting data would be in, well, a report.

2024-10-22 22:35 UTC, natikgadzhi commented on docs/integrations/sources/quora-ads.md
> +| `api_key` | `string` | API Key.  |  |
Link to how to obtain the api key pretty pelase.

2024-10-23 21:59 UTC, marcosmarxm commented
Hello 👋 Due to the numerous contributions happening, I decided to create this [view](https://github.com/orgs/airbytehq/projects/104/views/3) to help you know when I plan to review your contribution. If your connector has some limited-time credential feel free to reach me out.

2024-11-07 13:11 UTC, marcosmarxm commented
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

Make sure you have pagination properly working, the API doesn't have pagination please left a comment making my review easier.
Make sure have a square svg icon
Make sure credentials are valid.

2024-11-07 13:59 UTC, marcosmarxm commented
Not possible to test the connector yet, moving next review to Monday Nov 11. If that time I can't run proper tests I'm going to decline the contribution.

2024-11-07 14:22 UTC, bala-ceg commented
Hi @marcosmarxm , it is in my anonther airbyte account with user email as balaji281295@gmail.com

2024-11-07 22:29 UTC, marcosmarxm commented
The connector in your workspace isn't working. Please fix that by Monday.

2024-11-09 15:44 UTC, bala-ceg commented
@marcosmarxm this connector is ready for review (updated the icon and make sure all streams are working) and it is my in airbyte connector of email address - balaji281295@gmail.com

2024-11-11 17:01 UTC, marcosmarxm commented
Thanks @bala-ceg but Quora Ads doens't look a good candidate to build using UI Builder. It is very similar to Google Ads, Bing Ads, Facebook Ads. Which demand a lot of complex API calls / parameters and transformation to the data to make sense to end user. Also the account used doesn't much data which can't provide much to use analyze. Thanks for the contribution but for that reason I'm declining it.

2024-11-11 17:01 UTC, closed without merging