source-cal-com contribution from bishalbera
airbytehq/airbyte pull request #47293
Opened 2024-10-23 13:35 UTC by bishalbera

## What

This PR adds a new connector for source Cal.com (source-cal-com).

Contributor-provided connector description:

The Cal.com connector enables seamless data synchronization between Cal.com’s scheduling platform and various destinations. It helps extract events, attendees, and booking details from Cal.com, making it easy to analyze scheduling data or integrate it into downstream systems like data warehouses or CRMs. This connector streamlines automated reporting and insights for time management and booking analytics
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `orgId` | `string` | orgId.  |  |
| `api_key` | `string` | API Key. API key to use. Find it at https://cal.com/account |  |
| `start_time` | `string` | Start Time.  |  |
| `end_time` | `string` | End Time.  |  |
| `event_type_id` | `number` | Event Type Id.  |  |
| `event_type_slug` | `string` | Event Type Slug.  |  |
| `user_name_list` | `array` | User Name List.  |  |
| `duration` | `number` | Duration.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| event_types | id | No pagination | ✅ |  ❌  |
| my_profile | id | No pagination | ✅ |  ❌  |
| schedules | id | No pagination | ✅ |  ❌  |
| slots |  | No pagination | ✅ |  ❌  |
| calendars | externalId | No pagination | ✅ |  ❌  |
| bookings | id | No pagination | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

2024-10-23 16:48 UTC, natikgadzhi requested changes, later dismissed

2024-10-23 16:48 UTC, natikgadzhi commented on airbyte-integrations/connectors/source-cal-com/icon.svg
This is very not square. 🙃

2024-10-23 21:59 UTC, marcosmarxm commented
Hello 👋 Due to the numerous contributions happening, I decided to create this [view](https://github.com/orgs/airbytehq/projects/104/views/3) to help you know when I plan to review your contribution. If your connector has some limited-time credential feel free to reach me out.

2024-10-23 22:34 UTC, bishalbera commented on airbyte-integrations/connectors/source-cal-com/icon.svg
pardon me :( ...I've to edit the image

2024-11-07 13:11 UTC, marcosmarxm commented
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

Make sure you have pagination properly working, the API doesn't have pagination please left a comment making my review easier.
Make sure have a square svg icon
Make sure credentials are valid.

2024-11-07 14:19 UTC, marcosmarxm requested changes
Missing offset pagination and limit.
Missing some important endpoints (teams, membership, users, conferencing)
You can remove slots and make the input more clear.

2024-11-08 04:15 UTC, bishalbera commented
> Missing offset pagination and limit. Missing some important endpoints (teams, membership, users, conferencing) You can remove slots and make the input more clear.

these endpoints are under org feature which costs $37 @marcosmarxm thats why I wasnt able to implement them in the first place.

2024-11-11 17:22 UTC, marcosmarxm approved these changes

2024-11-11 17:48 UTC, merged