source-ebay contribution from bishalbera
airbytehq/airbyte pull request #47367
Opened 2024-10-25 11:15 UTC by bishalbera

## What

This PR adds a new connector for source Ebay (source-ebay).

Contributor-provided connector description:

The eBay connector  enables seamless data synchronization between eBay&#39;s platform and various data destinations, helping users extract eBay listings, orders, inventory, and marketing data in real time. It supports various eBay APIs, including the Inventory and Marketing APIs, allowing businesses to streamline operations, monitor sales, and analyze product performance efficiently.
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `authorization_credentials` | `string` | Authorization credentials.  |  |
| `marketplace_id` | `string` | Marketplace Id.  |  |
| `refresh_token` | `string` | Refresh Token.  |  |
| `customer_service_metric_type` | `string` | Customer Service Metric Type.  |  |
| `evaluation_type` | `string` | evaluation_type.  |  |
| `evaluation_marketplace_id` | `string` | evaluation_marketplace_id.  |  |
| `serch` | `string` | Serch.  |  |
| `environment` | `string` | environment.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| inventory_items | sku | DefaultPaginator | ✅ |  ❌  |
| offers |  | DefaultPaginator | ✅ |  ❌  |
| violation_summary |  | DefaultPaginator | ✅ |  ❌  |
| customer_service_metric |  | No pagination | ✅ |  ❌  |
| order_tasks | taskId | DefaultPaginator | ✅ |  ❌  |
| inventory_tasks | taskId | DefaultPaginator | ✅ |  ❌  |
| charity_orgs |  | DefaultPaginator | ✅ |  ❌  |
| get_campaigns | campaignId | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

2024-10-25 11:29 UTC, bishalbera commented
This was a complex one. I wouldn’t have been able to complete it without help from Justin on Slack. Some endpoints couldn't be implemented because they require different authentication logic. Additionally, I had to use the sandbox environment since gathering data wouldn’t have been possible otherwise, so I set an environment enum to toggle between environments. @marcosmarxm

2024-11-05 14:26 UTC, marcosmarxm approved these changes

2024-11-05 14:32 UTC, marcosmarxm requested changes
After some consideration and deeper analysis it doesn't look you're extracting the main endpoints required to get insights from Ebay, like orders, payments, shipping... Unfortunately this is a hard API requires access to a real account to create the connector. Thanks for trying.

2024-11-05 14:33 UTC, closed without merging

2024-11-06 00:52 UTC, bishalbera commented
> After some consideration and deeper analysis it doesn't look you're extracting the main endpoints required to get insights from Ebay, like orders, payments, shipping... Unfortunately this is a hard API requires access to a real account to create the connector. Thanks for trying.

yess an actual account would helped a lot here but other endpoints require different authorization methods thats why I couldn't apply some other endpoints. @marcosmarxm