:tada: New source: Yuki
airbytehq/airbyte pull request #47375
Opened 2024-10-25 15:54 UTC by Tom-DK

## What

Yuki is a Belgian/Dutch accounting software. This new source syncs the general ledger transactions.

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

2024-10-25 15:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=47375) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=47375) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=47375) it.</sub>

2024-10-28 08:32 UTC, Tom-DK commented
Can anyone help me here what went wrong during the CI/CD. Error codes are not very clear to me?

2024-10-28 17:30 UTC, marcosmarxm requested changes
Thanks for your first contribution @Tom-DK!
Unfortunately only including a single endpoint with a custom SOAP authentication I'm not sure how easy it will to keep this connector in the catalog.
Is there public documentation to read more about it?

2024-11-14 17:13 UTC, marcosmarxm commented
Closing as unresponsive

2024-11-14 17:13 UTC, closed without merging