[source-mysql] Adding CAT tests for source-mysql
airbytehq/airbyte pull request #47392
Opened 2024-10-26 05:00 UTC by theyueli

## What

This patch implements CAT tests for source-mysql. 

The implementation will be reused for testing source-mysql-v2. 

This patch contributes to https://github.com/airbytehq/airbyte-internal-issues/issues/10002

## How

## Review guide

This reuses the CAT test facilities our tooling team built when we were adding CAT tests to source-postgres.

## Can this PR be safely reverted and rolled back?

- [X ] YES 💚
- [ ] NO ❌

2024-10-28 13:44 UTC, clnoll requested changes
Nice @theyueli! Great to see more DB sources using CATs.

I focused my review on hook.py and have some requests related to using context managers for resource management.

2024-10-31 21:41 UTC, theyueli commented on airbyte-integrations/connectors/source-mysql/integration_tests/seed/requirement.txt
> +mysql-connector-python
fixed.

2024-10-31 21:41 UTC, theyueli commented on airbyte-integrations/connectors/source-mysql/integration_tests/seed/hook.py
> +        cursor.close()
Thanks for the suggestion, fixed!

2024-10-31 21:41 UTC, theyueli commented on airbyte-integrations/connectors/source-mysql/integration_tests/seed/hook.py
> +def create_schema(conn, schema_name: str) -> None:
fixed.

2024-10-31 21:41 UTC, theyueli commented on airbyte-integrations/connectors/source-mysql/integration_tests/seed/hook.py
> +def create_table(conn, schema_name: str, table_name: str) -> None:
fixed.

2024-10-31 21:41 UTC, theyueli commented on airbyte-integrations/connectors/source-mysql/integration_tests/seed/hook.py
> +        connection.close()
fixed.

2024-10-31 21:41 UTC, theyueli commented on airbyte-integrations/connectors/source-mysql/integration_tests/seed/hook.py
> +    try:
fixed.

2024-10-31 21:41 UTC, theyueli commented on airbyte-integrations/connectors/source-mysql/integration_tests/seed/hook.py
> +        sys.exit(1)
fixed, thanks!

2024-10-31 21:46 UTC, theyueli commented on airbyte-integrations/connectors/source-mysql/integration_tests/Dockerfile
> +RUN pip install --no-cache-dir -r ./requirement.txt
just to confirm, you meant the following?

```
COPY seed/requirement.txt .
RUN pip install --no-cache-dir -r ./requirement.txt
COPY seed/hook.py .
```

2024-10-31 21:51 UTC, clnoll approved these changes
Looks great @theyueli!

2024-10-31 22:28 UTC, theyueli commented on airbyte-integrations/connectors/source-mysql/integration_tests/Dockerfile
> +RUN pip install --no-cache-dir -r ./requirement.txt
great, fixed!

2024-10-31 22:45 UTC, merged