source-sendowl contribution from ombhardwajj
airbytehq/airbyte pull request #48047
Opened 2024-10-31 12:17 UTC by ombhardwajj

## What

This PR adds a new connector for source Sendowl (source-sendowl).

Contributor-provided connector description:

Sendowl is an All-in-One Digital Commerce Platform.
Using this connector we can extract data from products , packages , orders , discounts and subscriptions streams.
Docs : https://dashboard.sendowl.com/developers/api/introduction
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `username` | `string` | Username.  |  |
| `password` | `string` | Password.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| products |  | No pagination | ✅ |  ❌  |
| packages | id | No pagination | ✅ |  ❌  |
| orders | id | No pagination | ✅ |  ❌  |
| discounts | id | No pagination | ✅ |  ❌  |
| subscriptions |  | No pagination | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

2024-11-07 19:55 UTC, marcosmarxm requested changes
Connector has wrong record selector and it isn't implementing pagination.
Please fix that and ping me.

Order support incremental please implement that.

Moving next check to Monday nov 11

2024-11-08 14:00 UTC, ombhardwajj commented
@marcosmarxm I've added pagination to every stream and incremental support to Orders.
There is some problem with discounts stream (with and without pagination) from the sendowl server.
Can I proceed ahead and remove discounts stream for the time being and publish the changes?
I can add that stream once that error is resolved...?
You can try testing it infrom my account

2024-11-09 06:41 UTC, ombhardwajj commented
I am commiting the changes without discounts stream.
We always have the option of adding it back once it starts working !
(There is some issue with server)
@marcosmarxm

2024-11-11 19:49 UTC, marcosmarxm approved these changes

2024-11-11 19:56 UTC, merged