source-capsule-crm contribution from bishalbera
airbytehq/airbyte pull request #48043
Opened 2024-10-31 10:49 UTC by bishalbera

## What

This PR adds a new connector for source Capsule CRM (source-capsule-crm).

Contributor-provided connector description:

Capsule CRM connector  enables seamless data syncing from Capsule CRM to various data warehouses, helping businesses centralize and analyze customer data efficiently. It supports real-time data extraction of contacts, opportunities, and custom fields, making it ideal for comprehensive CRM analytics and reporting.
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `bearer_token` | `string` | Bearer Token. Bearer token to authenticate API requests. Generate it from the &#39;My Preferences&#39; &gt; &#39;API Authentication Tokens&#39; page in your Capsule account. |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| users | id | DefaultPaginator | ✅ |  ❌  |
| parties | id | DefaultPaginator | ✅ |  ❌  |
| tasks | id | DefaultPaginator | ✅ |  ❌  |
| employees | id | DefaultPaginator | ✅ |  ❌  |
| projects | id | DefaultPaginator | ✅ |  ❌  |
| opportunities | id | DefaultPaginator | ✅ |  ❌  |
| pipelines | id | DefaultPaginator | ✅ |  ❌  |
| milestones | id | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

2024-11-07 13:06 UTC, marcosmarxm commented
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

2024-11-08 16:54 UTC, marcosmarxm requested changes
* Pagination is wrong please fix that and use limit.
* Opportunities endpoint allows incremental using `since`
* You're only implementing the Core endpoints it misses all the Settings, please implement them. If not possible I don't think it will be able to accept the contribution.

2024-11-09 05:37 UTC, bishalbera commented
> * Pagination is wrong please fix that and use limit.
> * Opportunities endpoint allows incremental using `since`
> * You're only implementing the Core endpoints it misses all the Settings, please implement them. If not possible I don't think it will be able to accept the contribution.

Done please check now @marcosmarxm

2024-11-11 20:24 UTC, marcosmarxm approved these changes

2024-11-11 20:29 UTC, merged