source-pipeliner contribution from ombhardwajj
airbytehq/airbyte pull request #48059
Opened 2024-10-31 17:36 UTC by ombhardwajj

## What

This PR adds a new connector for source Pipeliner (source-pipeliner).

Contributor-provided connector description:

Pipeliner is a CRM tool.
Using this connector we fetch data from various streams such as contacts , data , leads and quotes.
Docs : https://pipeliner.stoplight.io/docs/api-docs
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `username` | `string` | Username.  |  |
| `password` | `string` | Password.  |  |
| `service` | `string` | Service.  |  |
| `spaceid` | `string` | SpaceID.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| accounts | id | No pagination | ✅ |  ❌  |
| activities | id | No pagination | ✅ |  ❌  |
| clients | id | No pagination | ✅ |  ❌  |
| contacts | id | No pagination | ✅ |  ❌  |
| entities | id | No pagination | ✅ |  ❌  |
| data | id | No pagination | ✅ |  ❌  |
| cloud_objects | id | No pagination | ✅ |  ❌  |
| fields | id | No pagination | ✅ |  ❌  |
| forecasts | id | No pagination | ✅ |  ❌  |
| form_views | id | No pagination | ✅ |  ❌  |
| entity_scorings | id | No pagination | ✅ |  ❌  |
| leads | id | No pagination | ✅ |  ❌  |
| lead_oppties | id | No pagination | ✅ |  ❌  |
| memos | id | No pagination | ✅ |  ❌  |
| notes | id | No pagination | ✅ |  ❌  |
| entity_fitnesses | id | No pagination | ✅ |  ❌  |
| pipelines | id | No pagination | ✅ |  ❌  |
| products | id | No pagination | ✅ |  ❌  |
| oppty_product_relations | id | No pagination | ✅ |  ❌  |
| profiles | id | No pagination | ✅ |  ❌  |
| quotes | id | No pagination | ✅ |  ❌  |
| reports | id | No pagination | ✅ |  ❌  |
| steps | id | No pagination | ✅ |  ❌  |
| tags | id | No pagination | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

2024-11-07 13:05 UTC, marcosmarxm commented
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

2024-11-07 19:35 UTC, marcosmarxm requested changes
Missing pagination from some streams, see example but not limited to this one: https://pipeliner.stoplight.io/docs/api-docs/e1dvdz2t2kub9-pipelines-list

Please fix that and ping me when its done.
Moving next check to Nov 11 Monday

2024-11-09 18:01 UTC, ombhardwajj commented
Hey @marcosmarxm Pagination has been added !! 😄

2024-11-11 19:46 UTC, marcosmarxm approved these changes

2024-11-11 19:51 UTC, merged