source-onepagecrm contribution from ombhardwajj
airbytehq/airbyte pull request #48068
Opened 2024-10-31 20:07 UTC by ombhardwajj

## What

This PR adds a new connector for source Onepagecrm (source-onepagecrm).

Contributor-provided connector description:

Onepagecrm is a CRM solution for small busineeses.
Using this stream we can extarct data from various streams such as contacts , deals , pipelines and meetings
Docs : https://developer.onepagecrm.com/api/
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `username` | `string` | Username. Enter the user ID of your API app |  |
| `password` | `string` | Password. Enter your API Key of your API app |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| contacts |  | DefaultPaginator | ✅ |  ❌  |
| users |  | DefaultPaginator | ✅ |  ❌  |
| bootstrap |  | DefaultPaginator | ✅ |  ❌  |
| companies |  | DefaultPaginator | ✅ |  ❌  |
| actions |  | DefaultPaginator | ✅ |  ❌  |
| action_stream |  | DefaultPaginator | ✅ |  ❌  |
| team_stream |  | DefaultPaginator | ✅ |  ❌  |
| deals |  | DefaultPaginator | ✅ |  ❌  |
| notes |  | DefaultPaginator | ✅ |  ❌  |
| relationship_types |  | DefaultPaginator | ✅ |  ❌  |
| pipelines |  | DefaultPaginator | ✅ |  ❌  |
| statuses |  | DefaultPaginator | ✅ |  ❌  |
| lead_sources | id | DefaultPaginator | ✅ |  ❌  |
| filters |  | DefaultPaginator | ✅ |  ❌  |
| predefined_actions |  | DefaultPaginator | ✅ |  ❌  |
| predefined_items | id | DefaultPaginator | ✅ |  ❌  |
| custom_fields |  | DefaultPaginator | ✅ |  ❌  |
| calls |  | DefaultPaginator | ✅ |  ❌  |
| meetings |  | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

2024-11-07 13:05 UTC, marcosmarxm commented
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

2024-11-08 17:59 UTC, marcosmarxm requested changes
Record selector is not correct please fix them.
It should be something `data * company`
Pagination and limits are OK
Endpoints looks good.

2024-11-09 05:00 UTC, ombhardwajj commented
I've fixed the record selector and also added primary key ! 🙇 
@marcosmarxm

2024-11-11 20:10 UTC, marcosmarxm approved these changes

2024-11-11 20:16 UTC, merged