fix for date range too narrow exception
airbytehq/airbyte pull request #4807
Opened 2021-07-18 07:37 UTC by blotouta2

## What
Date Range Exception 

## How
Add support for start and end date calculation for accessing google ads report  

## Recommended reading order
1. `x.java`
2. `y.python`

## Pre-merge Checklist
Expand the checklist which is relevant for this PR. 

<details><summary> <strong> Connector checklist </strong> </summary>
<p>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Secrets are annotated with `airbyte_secret` in the connector's spec
- [ ] Credentials added to Github CI if needed and not already present. [instructions for injecting secrets into CI](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#using-credentials-in-ci). 
- [ ] Unit & integration tests added as appropriate (and are passing)
    * Community members: please provide proof of this succeeding locally e.g: screenshot or copy-paste acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] `/test connector=connectors/<name>` command as documented [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-an-existing-connector) is passing. 
    * Community members can skip this, Airbyters will run this for you. 
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] `README.md`
    - [ ] `docs/SUMMARY.md` if it's a new connector
    - [ ] Created or updated reference docs in `docs/integrations/<source or destination>/<name>`.
    - [ ] Changelog in the appropriate page in `docs/integrations/...`. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md` contains a reference to the new connector
    - [ ] Build status added to [build page](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/builds.md)
- [ ] Build is successful
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] No major blockers
- [ ] PR merged into master branch
- [ ] Follow up tickets have been created
- [ ] Associated tickets have been closed & stakeholders notified
</p>
</details>

<details><summary> <strong> Connector Generator checklist </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

2021-07-20 12:30 UTC, yevhenii-ldv commented on airbyte-integrations/connectors/source-google-ads/source_google_ads/source.py
> +        end_date = max(end_date, pendulum.parse(stream_slice.get(cursor_field)).add(months=1))
If we accept your changes, then we will get a lot of unnecessary duplicates.
The code now works in such a way that we read data in one month.
For example, start_date is 2021-03-18, then we will have several requests:

| start_date   |      end_date      | 
|----------|:-------------:|
| 2021-03-18 |  2021-04-18 |
| 2021-04-19 |  2021-05-18 |
| 2021-05-19 |  2021-06-18 |
| 2021-06-19 |  2021-07-18 |
| 2021-07-19 |  2021-07-18 | 

**This is where the code breaks down**

If we well use your changes, then the following situation will be:
| start_date   |      end_date      | 
|----------|:-------------:|
| 2021-03-18 |  2021-07-18 |
| 2021-04-19 |  2021-07-18 |
| 2021-05-19 |  2021-07-18 |
| 2021-06-19 |  2021-07-18 |
| 2021-07-19 |  2021-08-18 | 

The problem exists, but change `min` to `max` is not the correct solution.

2021-07-20 12:31 UTC, yevhenii-ldv requested changes
Please looks comment.

2021-07-20 13:51 UTC, yevhenii-ldv commented
Hi @blotouta2 
I have already added fix to #4788

2021-07-30 06:31 UTC, sherifnada commented
@blotouta2 I think we should be good to go according to @yevhenii-ldv comments

2021-07-30 06:31 UTC, closed without merging