source-apptivo contribution from bishalbera
airbytehq/airbyte pull request #48081
Opened 2024-10-31 23:18 UTC by bishalbera

## What

This PR adds a new connector for source Apptivo (source-apptivo).

Contributor-provided connector description:

Apptivo connector  seamless data integration between Apptivo and various data warehouses or databases, automating data transfer for analytics, reporting, and insights. This connector allows businesses to synchronize Apptivo CRM data, such as contacts, deals, and activities, with other systems to streamline workflows and improve data accessibility across platforms.
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key` | `string` | API Key. API key to use. Find it in your Apptivo account under Business Settings -&gt; API Access. |  |
| `access_key` | `string` | Access Key.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| customers | customerId | DefaultPaginator | ✅ |  ❌  |
| contacts | contactId | DefaultPaginator | ✅ |  ❌  |
| cases |  | No pagination | ✅ |  ❌  |
| leads | id | DefaultPaginator | ✅ |  ❌  |
| opportunities | opportunityId | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

2024-11-07 13:04 UTC, marcosmarxm commented
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

2024-11-08 16:49 UTC, marcosmarxm requested changes
Sandbox has only a single record each stream this means we can test pagination.

This API support offset pagination:
```
https://api.apptivo.com/app/dao/v6/customers?a=getAll&iDisplayLength=50&iDisplayStart=0
```

Please add more records and check for pagination and iDisplayLength limit.

Moving next check to Nov Tue 12

2024-11-09 03:35 UTC, bishalbera commented
fixed @marcosmarxm

2024-11-11 20:19 UTC, marcosmarxm approved these changes

2024-11-11 20:25 UTC, merged