feat(destination-yellowbrick): improve performance by using JSONB type and functions
airbytehq/airbyte pull request #48475
Opened 2024-11-13 11:38 UTC by markcusack

## What
Improve insert performance by using JSONB types and functions behind the scenes.

## How
Internal changes to the connector to process JSON versus VARCHAR.

## User Impact
No impact to users.

## Can this PR be safely reverted and rolled back?
- [x] YES 💚
- [ ] NO ❌

2024-11-13 18:59 UTC, marcosmarxm commented
/format-fix

2024-12-23 18:50 UTC, marcosmarxm commented
Running tests

2025-03-06 19:23 UTC, marcosmarxm requested changes
I tried to run integration tests and most of them are failing. Unfortunately I wont be able to help fixing them.

> YellowbrickInsertDestinationAcceptanceTest > testEntrypointEnvVar() STANDARD_OUT
    2025-03-06T19:18:04,287`ForkJoinPool-1-worker-1`32`[32mINFO[m`i.a.c.e.LoggingInvocationInterceptor$LoggingInvocationInterceptorHandler$TimeoutInteruptor(cancel):177 - cancelling timer task on ForkJoinPool-1-worker-1
    2025-03-06T19:18:04,300`ForkJoinPool-1-worker-1`32`[1;31mERROR[m`i.a.c.e.LoggingInvocationInterceptor$LoggingInvocationInterceptorHandler(invoke):152 - Junit exception throw during execution of @BeforeEach method YellowbrickInsertDestinationAcceptanceTest.setUpInternal(DestinationAcceptanceTest) after 1 second:
    java.lang.RuntimeException: org.postgresql.util.PSQLException: FATAL: database "airbyte_test" does not exist
        	at io.airbyte.cdk.db.factory.ConnectionFactory.create(ConnectionFactory.kt:41)
        	at io.airbyte.integrations.destination.yellowbrick.YellowbrickDestinationAcceptanceTest.createDatabase(YellowbrickDestinationAcceptanceTest.java:194)
        	at io.airbyte.integrations.destination.yellowbrick.YellowbrickDestinationAcceptanceTest.setup(YellowbrickDestinationAcceptanceTest.java:144)
        	at io.airbyte.cdk.integrations.standardtest.destination.DestinationAcceptanceTest.setUpInternal(DestinationAcceptanceTest.kt:362)
        	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
        	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        Caused by: org.postgresql.util.PSQLException: FATAL: database "airbyte_test" does not exist
        	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
        	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2825)
        	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:175)
        	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:313)
        	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
        	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
        	at org.postgresql.Driver.makeConnection(Driver.java:443)
        	at org.postgresql.Driver.connect(Driver.java:297)
        	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
        	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:191)
        	at io.airbyte.cdk.db.factory.ConnectionFactory.create(ConnectionFactory.kt:39)
        	... 70 more

2025-03-07 11:55 UTC, markcusack commented
@marcosmarxm Will take a look and fix.

2025-03-07 14:57 UTC, marcosmarxm commented
/format-fix

2025-03-07 16:04 UTC, marcosmarxm approved these changes

2025-03-07 16:04 UTC, merged