Bendavis/doc enterprise
airbytehq/airbyte pull request #48619
Opened 2024-11-22 18:41 UTC by bengineerdavis

## What
This is updating our docs with a better version of the role-mapping script example we provide for enterprise customers. It was originally created by @malikdiarra for this OnCall issue: https://github.com/airbytehq/oncall/issues/6581

## How
- Adds conditional logic to address the edge case when permissions already exist and avoid the script failing without error handling

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌

2024-11-26 18:00 UTC, malikdiarra requested changes

2024-11-26 18:00 UTC, malikdiarra commented on docs/access-management/role-mapping.md
> +0. - Enter your own credentials to use Airbyte API.
This needs to be commented out

2024-11-26 21:30 UTC, malikdiarra approved these changes

2025-08-14 17:21 UTC, cgardens commented
We are closing this PR due to inactivity. We regularly close PRs that were created more than 6 months ago. If you'd like to keep working on it, please feel free reopen it. We'd be happy to keep working with you.

2025-08-14 17:21 UTC, closed without merging