source-greythr contribution from bhushan-dhwaniris
airbytehq/airbyte pull request #48699
Opened 2024-11-26 04:48 UTC by bhushan-dhwaniris

## What

This PR adds a new connector for source GreytHr (source-greythr).

Contributor-provided connector description:

The GreytHR Connector for Airbyte allows seamless integration with the GreytHR platform, enabling users to automate the extraction and synchronization of employee management and payroll data into their preferred destinations for reporting, analytics, or further processing.
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `gthost` | `string` | Host URL. Your GreytHR Host URL |  |
| `password` | `string` | Password.  |  |
| `username` | `string` | Username.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| Employees | employeeId | DefaultPaginator | ✅ |  ❌  |
| Employees Categories | employeeId | DefaultPaginator | ✅ |  ❌  |
| Employees Profile | employeeId | DefaultPaginator | ✅ |  ❌  |
| Employees Personal Details | employeeId | DefaultPaginator | ✅ |  ❌  |
| Employees Work Details | employeeId | DefaultPaginator | ✅ |  ❌  |
| Employee Separation Details | employeeId | DefaultPaginator | ✅ |  ❌  |
| Employee Statutory Details | employeeId | DefaultPaginator | ✅ |  ❌  |
| Employee Bank Details | employeeId | DefaultPaginator | ✅ |  ❌  |
| Employee PF &amp; ESI details | employeeId | DefaultPaginator | ✅ |  ❌  |
| Employee Qualifications Details |  | DefaultPaginator | ✅ |  ❌  |
| Users List |  | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

2024-11-26 16:22 UTC, marcosmarxm requested changes
Can you upload an square svg icon for GreytH?

2024-11-26 16:23 UTC, marcosmarxm requested changes

2024-11-26 16:23 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-greythr/manifest.yaml
> +      gthost:
```suggestion
      domain:
```

2024-11-26 16:23 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-greythr/metadata.yaml
> +      - "api.greythr.com"
```suggestion
      - "*"
```

2024-11-27 14:01 UTC, marcosmarxm requested changes
@bhushan-dhwaniris can you upload the square icon? and request my review again thanks

2024-11-27 14:34 UTC, bhushan-dhwaniris commented
> Can you upload an square svg icon for GreytH?

@marcosmarxm done.

2024-11-29 06:45 UTC, closed without merging