source-brevo contribution from lideke
airbytehq/airbyte pull request #48737
Opened 2024-11-28 11:11 UTC by lideke

## What

This PR updates source Brevo (source-brevo).

The contributor provided the following description of the change:

Update pagination on all streams to make be follow on the documentations

## Reviewer checklist
- [ ] Resolve any merge conflicts and validate file diffs (make sure the PR only includes changes intended by the contributor)
- [ ] After reviewing the changes, run the [`bump-version` Airbyte-CI command](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md#connectors-bump-version-command) locally to update the version of the connector according to the [versioning guidelines](https://docs.airbyte.io/contributor-guide/versioning-guidelines). Add `breakingChanges` to metadata if necessary.
- [ ] Ensure connector docs are up to date with any changes
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

2024-11-28 13:17 UTC, marcosmarxm commented
@lideke can you make sure you allow maintainers to edit your branch/fork? Some pipelines are broken and I want to fix to merge your contribution.

2024-11-28 13:39 UTC, lideke commented
> @lideke can you make sure you allow maintainers to edit your branch/fork? Some pipelines are broken and I want to fix to merge your contribution.

Hi @marcosmarxm, 
this PR has been generated by airbyte builder
I've invited you to the repo
but how to find maintainers from airbyte ?

2024-12-06 19:49 UTC, marcosmarxm requested changes
Our pipeline has a hard rule to not allow `http://` urls and today this captures everything. @lideke can you confirm the new schema is correct with all these links as fields?
Because of Brevo connector usage the CI tests are requesting me to turn-on acceptance test to run them all.

@natikgadzhi fyi, can this something Marketplace team can help?

2025-01-29 11:18 UTC, lideke commented
@natikgadzhi @marcosmarxm any update for this PR ?

2025-02-10 17:02 UTC, marcosmarxm approved these changes

2025-02-10 17:07 UTC, marcosmarxm commented
@lideke I'm working with connector team to get this merge this week. There is a blocker in CI I'm trying to fix.

2025-02-11 01:07 UTC, marcosmarxm commented
Hello 👋, I apologize if your contribution hasn't been reviewed or updated yet. I'm working to address the community contribution backlog. I created this [GitHub project](https://github.com/orgs/airbytehq/projects/108/views/4) to help you understand when to expect a review. This week, my goal is to complete all contributions related to Marketplace and Manifest-only connectors. Next week, I will focus on API Certified Connectors, followed by DB Java Connector contributions. If you have any questions about your contribution, please feel free to send me a direct message in the Airbyte Community Slack (and include the link to your pull request).

2025-02-12 14:19 UTC, merged