Update Hubspot Forms to Include all Form Types
airbytehq/airbyte pull request #49141
Opened 2024-12-12 08:13 UTC by Rhiyo

## What
The forms API defaults to only retrieving "hubspot" type forms. However, there is captured, flow and blog_comment type forms that can also be taken, these need to be explicitely added as formTypes to be collected. This is necessary for form submissions as well, as form submissions can come from all these types.

Can see what type of forms there are here: https://developers.hubspot.com/beta-docs/reference/api/marketing/forms

Can see what type of forms can have form submissions here: https://developers.hubspot.com/beta-docs/reference/api/marketing/forms/v1

## How
Override the request params in the form stream and explicitely include the formTypes with all available forms.

## User Impact
Previously uncaptured data will start being rolled in. However, if incremental, data from the past will not start coming in.

## Can this PR be safely reverted and rolled back?
Unsure

2024-12-12 08:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=49141) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=49141) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=49141) it.</sub>

2024-12-13 13:28 UTC, marcosmarxm requested changes
The change looks good, @Rhiyo. Could you update the connector version in the `metadata.yaml` and `pyproject.toml` files? Also, please include an entry in the connector changelog documentation page.

2024-12-13 15:21 UTC, Rhiyo commented
> The change looks good, @Rhiyo. Could you update the connector version in the `metadata.yaml` and `pyproject.toml` files? Also, please include an entry in the connector changelog documentation page.

Done @marcosmarxm

2025-02-11 01:10 UTC, marcosmarxm commented
Hello 👋, I apologize if your contribution hasn't been reviewed or updated yet. I'm working to address the community contribution backlog. I created this [GitHub project](https://github.com/orgs/airbytehq/projects/108/views/4) to help you understand when to expect a review. This week, my goal is to complete all contributions related to Marketplace and Manifest-only connectors. Next week, I will focus on API Certified Connectors, followed by DB Java Connector contributions. If you have any questions about your contribution, please feel free to send me a direct message in the Airbyte Community Slack (and include the link to your pull request).

2025-02-18 23:27 UTC, marcosmarxm commented
@Rhiyo, I apologize for the delay in merging your contribution. The change looks good, but there is an issue with the CI related to the `deals_archived` stream. I will work on fixing this and merge your contribution later this week.

2025-03-25 13:55 UTC, marcosmarxm approved these changes
Thanks @Rhiyo

2025-03-25 13:55 UTC, merged