feat: Upgrading linkedin ads api version for creatives stream
airbytehq/airbyte pull request #49458
Opened 2024-12-13 09:15 UTC by FVidalCarneiro

## What

This PR aims to solve the issue (https://github.com/airbytehq/airbyte/discussions/49457). It does this quite simply by upgrading the linkedin ads version of the creatives stream to 202410. This is an important step of the Linkedin ads API with its long term objective to deprecate the endpoints [InMailContents API](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/ads/advertising-targeting/version/message-ads-integrations?view=li-lms-2024-11#create-inmail-content) or the [AdDirectSponsoredContents API](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/ads/advertising-targeting/create-and-manage-video-legacy?view=li-lms-2024-11#sample-request-1).
## How
Upgrading the manifest.yaml file of the source connector.

## Review guide

1. manifest.yaml

## User Impact

User impacts only the creatives stream is only the addition of the name column. This can be confirmed [here](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/recent-changes?view=li-lms-2024-11#october-2024---version-202410).

## Can this PR be safely reverted and rolled back?

- [x] YES 💚 - however, the name field will no longer appear and will be removed from stream.
- [ ] NO ❌

2024-12-13 13:19 UTC, marcosmarxm requested changes
@FVidalCarneiro thanks for update the connector. Update the connector version in the `metadata.yaml` and `pyproject.toml` files, also add an entry in the connector documentation for this change.

Would be possible to provide access to maintainers edit your branch? This is necessary to run tests, future format fixes and merging the contribution.

2024-12-16 07:43 UTC, FVidalCarneiro commented
> @FVidalCarneiro thanks for update the connector. Update the connector version in the `metadata.yaml` and `pyproject.toml` files, also add an entry in the connector documentation for this change.
> 
> Would be possible to provide access to maintainers edit your branch? This is necessary to run tests, future format fixes and merging the contribution.

Hello @marcosmarxm , I have applied the requested changes, thanks. 

Unfortunately we cannot make you editors of this branch due to the limitation described [here](https://github.com/orgs/community/discussions/5634). This was already the case for our PR (https://github.com/airbytehq/airbyte/pull/34166#issuecomment-1935872385) where @lazebnyi requested me the same thing.

Please let me know what other changes you would like me to do.

Thanks

2024-12-17 13:55 UTC, maxi297 commented
If the goal of this API upgrade is to have access to a new field in the creatives, should the creatives schema be updated?

2024-12-18 02:20 UTC, natikgadzhi commented on airbyte-integrations/connectors/source-linkedin-ads/source_linkedin_ads/manifest.yaml
> +            Linkedin-Version: "202410"
Should there also be a schema change?

2024-12-19 15:15 UTC, kev-datams commented
hello @maxi297, @natikgadzhi, just added the `name` new field in schema 🙏

2025-01-13 19:53 UTC, lazebnyi reviewed
I think we can move forward with this PR after @agarctfi finishes with the progressive rollout

2025-01-14 14:57 UTC, kev-datams commented
@lazebnyi thanks, do you know when the 5.1.0 will be officially available to be able to merge this one ?

2025-01-14 17:15 UTC, FVidalCarneiro commented
> I think we can move forward with this PR after @agarctfi finishes with the progressive rollout of #48863

Hi @lazebnyi , I have just solved merge conflicts. Ready to merge now. Thank you, this small change is important for us 🙏

2025-01-15 18:25 UTC, natikgadzhi commented
Time for another rebase?

2025-01-15 20:14 UTC, kev-datams commented
> Time for another rebase?

hello @natikgadzhi @lazebnyi , all done
please could you merge it 🙏
thanks a lot !

FYI @FVidalCarneiro

2025-01-21 09:29 UTC, kev-datams commented
This is quite frustrating not to have a validation for a such small PR

2025-01-22 01:08 UTC, natikgadzhi reviewed
Code changes are fine, but let's make this a progressive rollout just in case. 

@marcosmarxm can you please work with @agarctfi to change the version tags here, and then merge and start a progressive rollout?

I'm happy to force-merge / approve when the version are set to RC correctly.

2025-01-22 18:20 UTC, kev-datams commented
> Code changes are fine, but let's make this a progressive rollout just in case. 
> 
> 
> 
> @marcosmarxm can you please work with @agarctfi to change the version tags here, and then merge and start a progressive rollout?
> 
> 
> 
> I'm happy to force-merge / approve when the version are set to RC correctly. 
> 
> 

@natikgadzhi do you confirm we can not help you on this point ?

2025-01-27 08:02 UTC, kev-datams commented
hello, new conflict (again), how can we efficiently progress on this topic ? 🙏

2025-01-28 14:00 UTC, FVidalCarneiro commented
Hello @natikgadzhi , @marcosmarxm , @agarctfi , another merge conflict that we had to solve. Please try to merge this asap to avoid once again updating our branch. This is a very small change that has a business impact for us and that is taking the creatives endpoint to the direction required (as described in the PR description). We opened this small PR more than a month ago and are a bit frustrated to see it not advancing. 

FYI, we believe the [AdDirectSponsoredContents API](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/ads/advertising-targeting/create-and-manage-video-legacy?view=li-lms-2024-11#sample-request-1) has been silently already sunset by Linkedin. On our side, we are currently unable to collect creative names.

2025-01-29 19:53 UTC, PaulGrolleau commented
Hello Everyone,

Thank you so much, @FVidalCarneiro and @kev-datams, for the adjustment! I was working on this earlier today and just came across your PR—great timing.

To the Airbyte team, is there any update on when this might be merged? It’s a valuable feature for my team, and I’m exploring options in the meantime.

Appreciate your efforts—thanks in advance!

2025-01-29 20:10 UTC, natikgadzhi commented
@agarctfi is fixing up another bug in linkedin ads, and then he'll get this merged — I expect it's this or next week.

2025-02-03 09:02 UTC, FVidalCarneiro commented
@natikgadzhi , I saw that the fix has been merged. Solved merge conflicts and ready to merge again

2025-02-03 23:06 UTC, agarctfi commented
These changes should be live with `LinkedIn Ads v5.1.6` merged [here](https://github.com/airbytehq/airbyte/pull/52599)

2025-02-03 23:06 UTC, closed without merging