feat(source-airtable): migrate to low-code
airbytehq/airbyte pull request #49813
Opened 2024-12-16 15:56 UTC by darynaishchenko

## What

## How

## Review guide

## User Impact

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

2025-01-13 22:05 UTC, lazebnyi requested changes
I have some concerns with custom components and am a little worried about the failed CAT tests (have you run any regression tests?) , but everything else looks okay to me. Nice job!

2025-01-14 12:19 UTC, darynaishchenko commented on airbyte-integrations/connectors/source-airtable/source_airtable/auth.py
> +    connector_config: dict
the reason why I left oauth as custom component as we need to add headers to request in `_get_refresh_access_token_response`, using low-code we can't menage headers for this request only request body.

2025-01-14 12:24 UTC, darynaishchenko commented on airbyte-integrations/connectors/source-airtable/source_airtable/source.py
> +        if len(self.streams(config)) > 0:
you are right, it's enough to check only `tables` stream. but there is a problem in the configuration as we need to define a stream for `CheckStream` that is in the list of streams in manifest. `tables` stream is not available for users now. I'm not sure that we need to add it only for check connection, I don't think this stream is valuable for users.

2025-01-14 12:24 UTC, darynaishchenko commented on airbyte-integrations/connectors/source-airtable/source_airtable/manifest.yaml
> +  airtable_stream:
nope, removed

2025-01-14 12:26 UTC, darynaishchenko commented on airbyte-integrations/connectors/source-airtable/source_airtable/manifest.yaml
> +            - ["id"]
it's just how I added it, updated to align one way of definition

2025-01-14 13:31 UTC, lazebnyi commented on airbyte-integrations/connectors/source-airtable/source_airtable/auth.py
> +    connector_config: dict
do you think we can override the `get_auth_header` method in the `DeclarativeOauth2Authenticator` class and eval the field as we do for `token_expiry_date` and `refresh_request_body`? If value not presented we will use default behavior. 

To encode the `client_id` and `client_secret`, we can pass the `base64.b64encode `object directly during the `eval` method call.

2025-01-14 13:35 UTC, lazebnyi commented on airbyte-integrations/connectors/source-airtable/source_airtable/source.py
> +        if len(self.streams(config)) > 0:
Hmm, interesting. We definitely need CheckDynamicStream to handle situations where we have only dynamic streams.

In the current situation, I think we can make such a sacrifice and show the internal stream in the catalog for the user.
@darynaishchenko @maxi297 wdyt?

2025-01-14 13:53 UTC, lazebnyi commented on airbyte-integrations/connectors/source-airtable/source_airtable/source.py
> +        if len(self.streams(config)) > 0:
But config migration isn't a block that airtable can builder compatible, unlike custom components or custom behavior for check connection

2025-01-14 15:45 UTC, maxi297 commented on airbyte-integrations/connectors/source-airtable/source_airtable/source.py
> +        if len(self.streams(config)) > 0:
There are a couple acceptance criteria for this project (which might have not all been explicit so sorry about that):
1. Have source-airtable use streams defined in a manifest file. Goal: ease maintenance
2. Allow for dynamic sources like source-airtable to be created in the builder. Goal: extensibility of the engine and having more people create sources

The current solution that was provided is good for number 1 which is great. However, devs would need to re-implement the check for any source that only has dynamic streams which makes this builder incompatible. There are still two weeks to the cycle. I'm good with increasing the scope of this project to address the second part. This only means we will spend less time on source-stripe which I'm fine with.

2025-01-14 15:54 UTC, maxi297 commented on airbyte-integrations/connectors/source-airtable/source_airtable/auth.py
> +            token_provider = InterpolatedStringTokenProvider(api_token=config["api_key"], config=config, parameters={})
Out of 1196 sources configured, 190 still have the old configuration. I haven't checked if they all synced recently but I would assume some of there do

```
prod-configapi=> select count(*) from actor where actor_definition_id = '14c6e7ea-97ed-4f5e-a7b5-25e9a80b8212' and (configuration->'api_key') is not null and tombstone = 'f';
 count
-------
   190
(1 row)

prod-configapi=> select count(*) from actor where actor_definition_id = '14c6e7ea-97ed-4f5e-a7b5-25e9a80b8212' and tombstone = 'f';
 count
-------
  1196
(1 row)
```

2025-01-14 16:00 UTC, darynaishchenko commented on airbyte-integrations/connectors/source-airtable/source_airtable/auth.py
> +            token_provider = InterpolatedStringTokenProvider(api_token=config["api_key"], config=config, parameters={})
@maxi297 @lazebnyi I'm currently working on updating `DeclarativeOauth2Authenticator` to accept `refresh_request_headers` to not use custom component, once it's in review I'll add config migration

2025-01-14 16:14 UTC, lazebnyi commented on airbyte-integrations/connectors/source-airtable/source_airtable/source.py
> +        if len(self.streams(config)) > 0:
Ok, I'll take care about `CheckDynamicStream`.

2025-01-16 18:14 UTC, darynaishchenko commented on airbyte-integrations/connectors/source-airtable/source_airtable/auth.py
> +            token_provider = InterpolatedStringTokenProvider(api_token=config["api_key"], config=config, parameters={})
removed custom components for authentication and updated manifest

2025-01-16 18:15 UTC, darynaishchenko commented on airbyte-integrations/connectors/source-airtable/source_airtable/source.py
> +        if len(self.streams(config)) > 0:
updated with new `CheckDynamicStream` and removed custom check

2025-01-20 13:36 UTC, darynaishchenko commented
### Regression tests
[Job 1](https://github.com/airbytehq/airbyte/actions/runs/12827918916/job/35770896342)

_Catalogs are not the same: failed._

Diff in catalogs:
1. fields with `array` type now don’t have `items` object. `DynamicSchemaLoader` doesn’t handle this case. We should be good with this change.
2. `is_resumable` is `false` now, instead of `null` in previous version.
3. `supported_destination_sync_modes` were removed from the catalog. `AirbyteStream` doesn’t have it in latest cdk version.
4. `date` fields with type `string` don’t have `format` in it. `DynamicSchemaLoader` doesn’t handle this case.

_Records count_
Stream N has 1 more records in the target version (1440 vs. 1439).
Reason: missing record filter (added in the PR)

_Records schema match:_

Records were flattened, so object inside `fields` object was transformed to wrong format. Added `DpathFlattenFields` to only flatten fields inside fields `object` and not update fields inside it.
### After changes:
[Job1](https://github.com/airbytehq/airbyte/actions/runs/12867207709)
[Job2](https://github.com/airbytehq/airbyte/actions/runs/12867688883)

_Records schema match:_ passed
_Record count:_ passed
_Catalogs are not the same_: failed with the issues mentioned above.

Job3: https://github.com/airbytehq/airbyte/actions/runs/12868016299 , https://github.com/airbytehq/airbyte/actions/runs/12868607641 
_Failed on records schema:_ fixed order of transformations. The issue was due to `RemoveFields` transformation were applied for field “id” after `DpathFlattenFields`, which removed fields id from `record.fields.id`, but we need to keep it and rename and delete only `record.id`.

2025-01-20 14:48 UTC, lazebnyi reviewed
> 2. is_resumable is false now, instead of null in previous version.

What is the reason for this? Is it related to low-code migration or the migration to the latest version of the CDK?

> 4. date fields with type string don’t have format in it. DynamicSchemaLoader doesn’t handle this case.

`DynamicSchemaLoader` handles date fields and implements data types as described in the official Airbyte documentation, where the date field has a specified format - https://github.com/airbytehq/airbyte-python-cdk/blob/34a978ddf6704eb07ab81414c7f953f12f464cac/airbyte_cdk/sources/declarative/schema/dynamic_schema_loader.py#L24

2025-01-20 14:48 UTC, lazebnyi commented on airbyte-integrations/connectors/source-airtable/pyproject.toml
> +airbyte-cdk = "6.21.1.dev0"
Need move to last available version

2025-01-20 15:38 UTC, darynaishchenko commented on airbyte-integrations/connectors/source-airtable/pyproject.toml
> +airbyte-cdk = "6.21.1.dev0"
updated

2025-01-20 15:47 UTC, darynaishchenko commented
@lazebnyi 
> What is the reason for this? Is it related to low-code migration or the migration to the latest version of the CDK?

migration to low code. if[ stream doesn't have cursor](https://github.com/airbytehq/airbyte-python-cdk/blob/main/airbyte_cdk/sources/declarative/declarative_stream.py#L129), it's not resumable.

> `DynamicSchemaLoader` handles date fields and implements data types as described in the official Airbyte documentation, where the date field has a specified format

Yes, fixed types_mapping [here](https://github.com/airbytehq/airbyte/pull/49813/commits/4ff9cec47fba1f218f6f066750d8c955d6e596fa)

2025-01-20 18:57 UTC, lazebnyi commented
Looks good to me. However, I suggest rolling out a pre-release version with a feature flag for select users. This will allow us to test the builder and ensure backward compatibility of the version

@maxi297 wdyt?

2025-01-20 23:53 UTC, natikgadzhi commented
We have progressive rollouts exactly for this purpose.


> —
> Reply to this email directly, view it on GitHub
> <https://github.com/airbytehq/airbyte/pull/49813#issuecomment-2603080072>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAKU4P4ATRBSRQE4EZ4CHD2LVBMLAVCNFSM6AAAAABTWOTSE6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMMBTGA4DAMBXGI>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2025-01-21 08:30 UTC, lazebnyi commented
> We have progressive rollouts exactly for this purpose.

@natikgadzhi Yes, it can be used for that. But we still need to check backward compatibility with the builder manually, don't we?

2025-01-21 17:08 UTC, darynaishchenko commented
@lazebnyi 
I re-ran regression tests with the new changes
[job1](https://github.com/airbytehq/airbyte/actions/runs/12887620435/job/35930705466), [job2](https://github.com/airbytehq/airbyte/actions/runs/12887345934/job/35929838652)

Only catalogs diff mentioned above failed. Issue with date/datime and format was fixed. 
For some jobs 
`TestDataIntegrity.test_all_records_are_the_same_without_state ` failed due to file not found issue, asked in slack. But locally records are identical. Will re-run tests after feedback from tolling team.

> Catalogs are not the same: failed.
> 
> Diff in catalogs:
> 
> fields with array type now don’t have items object. DynamicSchemaLoader doesn’t handle this case. We should be good with this change.
> is_resumable is false now, instead of null in previous version.
> supported_destination_sync_modes were removed from the catalog. AirbyteStream doesn’t have it in latest cdk version.

2025-01-23 11:18 UTC, darynaishchenko commented
### Regression tests after fix in the live tests:
https://github.com/airbytehq/airbyte/actions/runs/12913423626/job/36010634765
https://github.com/airbytehq/airbyte/actions/runs/12913053477/job/36009346601 
https://github.com/airbytehq/airbyte/actions/runs/12926871501/job/36050820127 

### Regarding `TestDataIntegrity.test_all_records_are_the_same_without_state` failure:

It's related to array fields. In the new low code schema doesn't have items definition for array type fields. Data inside fields with type array wasn't transformed to follow items type as it was in previous version. So all fields have initial format.

_I found two types of this difference:_
1. when items are integer: before `{field: [1.0, 2.0]}`, now `{field: [1, 2]}`
2. when items are strings: before `{field: [["val1"], ["val2"]]}`, now `{field: ["val1", "val2"]}`.

I don't think this is critical change and root's type array is not changed, data is up-to-date with original type from response. So we should be fine with this change. 
@lazebnyi what do you think?

2025-01-24 05:45 UTC, lazebnyi commented
/format-fix

2025-01-24 06:17 UTC, lazebnyi commented
### **Regression test results:** 

https://github.com/airbytehq/airbyte/actions/runs/12944153362/job/36104597286
https://github.com/airbytehq/airbyte/actions/runs/12944159949/job/36104616341

Only `test_catalog_are_the_same` has failed as `supported_destination_sync_modes` was removed with last CDK version. 

#### **ETA:** Release connector with progressive rollout flow at Monday (27.01)

2025-01-24 06:28 UTC, lazebnyi approved these changes

2025-01-27 14:15 UTC, tolik0 approved these changes

2025-01-27 14:25 UTC, merged

2025-01-27 21:57 UTC, Audace commented
I'm now getting errors on all of my Airtable ETLs. 
```
    launch(source, _args)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py", line 341, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py", line 163, in run
    yield from map(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py", line 230, in discover
    catalog = self.source.discover(self.logger, config)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/concurrent_declarative_source.py", line 158, in discover
    concurrent_streams, synchronous_streams = self._group_streams(config=config)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/concurrent_declarative_source.py", line 272, in _group_streams
    declarative_stream.get_json_schema(),
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 161, in get_json_schema
    return self._schema_loader.get_json_schema()
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/schema/dynamic_schema_loader.py", line 148, in get_json_schema
    value = self._get_type(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/schema/dynamic_schema_loader.py", line 216, in _get_type
    return self._resolve_complex_type(mapped_field_type)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/schema/dynamic_schema_loader.py", line 229, in _resolve_complex_type
    self._get_airbyte_type(complex_type.items)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/schema/dynamic_schema_loader.py", line 262, in _get_airbyte_type
    raise ValueError(f"Invalid Airbyte data type: {field_type}")
ValueError: Invalid Airbyte data type: datetime
```