[DRAFT_PR] Destination: BigQuery: Introduced chunk size config
airbytehq/airbyte pull request #5029
Opened 2021-07-27 16:20 UTC by etsybaev

## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*

## How
*Describe the solution*

## Pre-merge Checklist
Expand the checklist which is relevant for this PR. 

<details><summary> <strong> Connector checklist </strong> </summary>
<p>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Secrets are annotated with `airbyte_secret` in the connector's spec
- [ ] Credentials added to Github CI if needed and not already present. [instructions for injecting secrets into CI](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#using-credentials-in-ci). 
- [ ] Unit & integration tests added as appropriate (and are passing)
    * Community members: please provide proof of this succeeding locally e.g: screenshot or copy-paste acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] `/test connector=connectors/<name>` command as documented [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-an-existing-connector) is passing. 
    * Community members can skip this, Airbyters will run this for you. 
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] `README.md`
    - [ ] `docs/SUMMARY.md` if it's a new connector
    - [ ] Created or updated reference docs in `docs/integrations/<source or destination>/<name>`.
    - [ ] Changelog in the appropriate page in `docs/integrations/...`. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md` contains a reference to the new connector
    - [ ] Build status added to [build page](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/builds.md)
- [ ] Build is successful
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] No major blockers
- [ ] PR merged into master branch
- [ ] Follow up tickets have been created
- [ ] Associated tickets have been closed & stakeholders notified
</p>
</details>

<details><summary> <strong> Connector Generator checklist </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

2021-07-28 14:50 UTC, etsybaev commented
/test connector=connectors/destination-bigquery

2021-07-29 11:58 UTC, yaroslav-hrytsaienko approved these changes

2021-07-30 08:12 UTC, etsybaev commented
/test connector=connectors/destination-bigquery

2021-07-30 08:40 UTC, etsybaev commented
Hi @sherifnada @subodh1810 @tuliren.
This PR introduces a chunk\buffer size config for big query SDK client. I would propose to add it at least for a while and ask those who have an issue with migration to decrease the buffer size and increase the allocated RAM memory. Just to see it helps. If yes - then we would definitely know the reason. If now - we may think about rolling back this PR

2021-07-30 10:14 UTC, subodh1810 requested changes
This will break existing connectors cause none of them would have chunk size selected. Also what about handling 404 and adding more logs and specifying the job location and project like we discussed in the meeting.

2021-07-30 10:33 UTC, etsybaev commented
> This will break existing connectors cause none of them would have chunk size selected. Also what about handling 404 and adding more logs and specifying the job location and project like we discussed in the meeting.

Hi @subodh1810.

I've added more logs as part of this PR and here described the point about 404 https://github.com/airbytehq/airbyte/pull/5049#discussion_r678585179


As an option to keep the backward compatibility I may update this PR making this new arg as an optional. If not set - then will use the default BigQuery SDK client's value. What do you think?

2021-07-30 10:45 UTC, subodh1810 commented
Ahan! alright! I think its important to keep this as backward compatible and make a default choice if the value is not present

2021-07-30 13:25 UTC, etsybaev commented
/test connector=connectors/destination-bigquery

2021-07-30 13:52 UTC, etsybaev commented
Hi @subodh1810. I've updated the PR -> removed new arg from the mandatory list. Will use default SDK BigQuery client's values if other is not set explicitly in config

2021-08-02 19:13 UTC, subodh1810 approved these changes
Just 1 comment, rest looks fine

2021-08-02 19:13 UTC, subodh1810 commented on airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryDestination.java
> +  final int MiB = 1024 * 1024;
`private static final int MIB = 1024 * 1024;`

2021-08-02 19:39 UTC, etsybaev commented on airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryDestination.java
> +  final int MiB = 1024 * 1024;
Updated, thanks

2021-08-03 06:09 UTC, etsybaev commented
/test connector=connectors/destination-bigquery

2021-08-03 07:50 UTC, etsybaev commented
/publish connector=connectors/destination-bigquery

2021-08-03 09:37 UTC, etsybaev commented
/test connector=connectors/destination-bigquery

2021-08-03 10:02 UTC, etsybaev commented
/publish connector=connectors/destination-bigquery

2021-08-03 10:20 UTC, merged