Feat/az blob client cred
airbytehq/airbyte pull request #50398
Opened 2024-12-23 09:48 UTC by vpipkt

## What

In connector `source-azure-blob-storage`, allow authentication to Azure using `client_credentials` type of grant. This is a common pattern for accessing Azure resources using a Service Principal's app registration. 

## How

Add a third option to the authentication for using only tenant id, client id and client secret; Add a new Authenticator inheriting the Oauth2Authenticator that sets options specific to Azure's requirements found [here](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-client-creds-grant-flow).

## Review guide

1. `stream_reader.py` add another Authenticator class and wire it up to spec
2. `unit_tests` 
   0. `test_config_migration`: use a temp file so test execution doesn't overwrite files in git
   4. add a simple test for new Authenticator 

## User Impact

Adds a new option to authenticate using Service Principals. Should not impact existing authentication patterns

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

2024-12-23 13:53 UTC, marcosmarxm requested changes

2024-12-23 13:53 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-azure-blob-storage/metadata.yaml
> +  dockerImageTag: 0.5.4
```suggestion
  dockerImageTag: 0.5.0
```

Please bump to `0.5.0` version.

2025-01-02 09:04 UTC, vpipkt commented on airbyte-integrations/connectors/source-azure-blob-storage/metadata.yaml
> +  dockerImageTag: 0.5.4
🤦 ofc

2025-01-02 12:35 UTC, marcosmarxm commented
running tests again.

2025-01-03 08:59 UTC, vpipkt commented
I really don't see how to move forward past test failures. Locally I am missing a bunch of environment variables and also the source-azure-blob-storage/secrets directory referenced in the acceptance test config. I also cannot see the output from CI runs here.

2025-01-06 19:30 UTC, marcosmarxm approved these changes

2025-01-06 20:28 UTC, merged

2025-01-08 10:20 UTC, vpipkt commented
thank you so very very much @marcosmarxm 🙇