✨ Source Facebook Marketing: Add learning_stage_info field to AdSets stream
airbytehq/airbyte pull request #50418
Opened 2024-12-24 19:10 UTC by h0rban

## What

Adds the learning_stage_info to the adsets pull in source-facebook-marketing when it's available.

Issues:
- [#50417](https://github.com/airbytehq/airbyte/discussions/50417)

## How

AdSets schema is updated to include additional field.

## Review guide

1. `airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/schemas/ad_sets.json`

## User Impact

additional available data

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

2024-12-24 19:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=50418) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=50418) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=50418) it.</sub>

2024-12-27 10:23 UTC, marcosmarxm commented
@airbytehq/dev-python can someone take a look in this contribution?

2025-02-11 01:10 UTC, marcosmarxm commented
Hello 👋, I apologize if your contribution hasn't been reviewed or updated yet. I'm working to address the community contribution backlog. I created this [GitHub project](https://github.com/orgs/airbytehq/projects/108/views/4) to help you understand when to expect a review. This week, my goal is to complete all contributions related to Marketplace and Manifest-only connectors. Next week, I will focus on API Certified Connectors, followed by DB Java Connector contributions. If you have any questions about your contribution, please feel free to send me a direct message in the Airbyte Community Slack (and include the link to your pull request).

2025-03-06 19:27 UTC, marcosmarxm approved these changes
The change looks good to me. I'm running tests.  @h0rban let's wait for them, after they're green need final approval from connector team.

2025-03-07 11:53 UTC, artem1205 requested changes
small comment, please take a look,
otherwise LGTM!

2025-03-07 11:53 UTC, artem1205 commented on airbyte-integrations/connectors/source-facebook-marketing/unit_tests/test_async_job.py
> +        mocker.patch(
why do we need to remove context manager here?

2025-03-10 17:28 UTC, h0rban commented on airbyte-integrations/connectors/source-facebook-marketing/unit_tests/test_async_job.py
> +        mocker.patch(
@artem1205, i am seeing the following warning when running unit tests with the previous version.

```
airbyte-integrations/connectors/source-facebook-marketing/unit_tests/test_async_job.py::TestInsightAsyncJob::test_get_result_retried
  xxx/airbyte-contributions/airbyte/airbyte-integrations/connectors/source-facebook-marketing/unit_tests/test_async_job.py:337: PytestMockWarning: Mocks returned by pytest-mock do not need to be used as context managers. The mocker fixture automatically undoes mocking at the end of a test. This warning can be ignored if it was triggered by mocking a context manager. https://pytest-mock.readthedocs.io/en/latest/remarks.html#usage-as-context-manager
    with mocker.patch(
```

2025-03-10 17:30 UTC, artem1205 commented on airbyte-integrations/connectors/source-facebook-marketing/unit_tests/test_async_job.py
> +        mocker.patch(
TIL, thanks for the explanation @h0rban !

2025-03-10 17:31 UTC, artem1205 approved these changes
LGTM!

2025-03-11 14:25 UTC, merged