delete unused singer modules
airbytehq/airbyte pull request #5241
Opened 2021-08-06 05:41 UTC by sherifnada

2021-08-07 10:41 UTC, bazarnov reviewed
Before we remove anything of those, we need to make sure the customers don't have any of listed connectors in use, kind of check of usage or something, also announce that such a change takes place, so everyone is aware of it and migrate their flow to the new native connectors.

2021-08-07 10:44 UTC, bazarnov commented on airbyte-integrations/connectors/source-github/source_github/schemas/shared/user.json
> -      }
So, regards this change of source-github > schemas > shared > user.json - the file was just formated, right?

2021-08-07 11:01 UTC, bazarnov requested changes
LGTM, with small correction)

This leftover should be also removed.

 SEED:
- `airbyte-config/init/src/main/resources/seed/source_definitions.yaml` - Mixpanel-singer block should be removed

 STANDARD_SOURCE_DEFINITION:
- `airbyte-config/init/src/main/resources/config/STANDARD_SOURCE_DEFINITION/859e501d-2b67-471f-91bb-1c801414d28f.json` - Mixpanel-singer seed file.

2021-08-10 05:14 UTC, sherifnada commented
@bazarnov thanks for the comments! made the changes you pointed out. Good catch!

2021-08-10 05:19 UTC, merged