🎉  Source S3: support of Parquet format
airbytehq/airbyte pull request #5305
Opened 2021-08-10 15:14 UTC by antixar

## How
Using same lib 'pyarrow' as for csv parsing

## Recommended reading order
1. `formats/parquet_spec.py`
2. `formats/parquet_parserpy`

## Pre-merge Checklist

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

2021-08-12 22:24 UTC, antixar commented
/test connector=connectors/source-s3

2021-08-13 07:52 UTC, antixar commented
/test connector=connectors/source-s3

2021-08-13 09:02 UTC, antixar commented
/test connector=connectors/source-s3

2021-08-13 09:18 UTC, antixar commented
/test connector=connectors/source-s3

2021-08-23 10:11 UTC, bazarnov requested changes
Please fix branch conflicts + fix the `airbyte-integrations/connectors/source-hubspot/source_hubspot/api.py` file conflict on this branch.

2021-08-23 10:39 UTC, antixar commented
/test connector=connectors/source-s3

2021-08-23 10:40 UTC, antixar commented on airbyte-integrations/connectors/source-hubspot/source_hubspot/api.py
>              # do not cast numeric IDs into float, use integer instead
You are right. Fixed.

2021-08-23 11:09 UTC, antixar commented
/test connector=connectors/source-s3

2021-08-23 12:45 UTC, antixar commented
/test connector=connectors/source-s3

2021-08-23 12:52 UTC, antixar commented
/test connector=connectors/source-s3

2021-08-23 13:53 UTC, bazarnov approved these changes

2021-08-27 16:03 UTC, Phlair reviewed
This is looking awesome! The data generation in the parquet unit tests is great, would be worth putting that into abstract (at least the parts that make sense) so new formats can re-use it too 👍 

Most of my points in comments are around which parameters we expose to user and how we describe them for nice UX.

2021-08-30 12:22 UTC, antixar commented
> One additional check: have you tested the spec functions as expected in the UI?

@Phlair , yes, I have. We made a demo for Sherif last Thursday.

2021-08-30 12:26 UTC, antixar commented on docs/integrations/sources/s3.md
> +You can find details on [here](https://arrow.apache.org/docs/python/generated/pyarrow.csv.ConvertOptions.html#pyarrow.csv.ConvertOptions) and [here](https://arrow.apache.org/docs/python/generated/pya
Fixed

2021-08-30 13:32 UTC, antixar commented on airbyte-integrations/connectors/source-s3/source_s3/source_files_abstract/formats/parquet_spec.py
> +        description="perform read buffering when deserializing individual  column chunks. Otherwise IO calls are unbuffered.",
Added

2021-08-30 13:42 UTC, antixar commented on airbyte-integrations/connectors/source-s3/source_s3/source_files_abstract/formats/parquet_spec.py
> +        parquet = "parquet"
Added

2021-08-30 13:51 UTC, antixar commented on airbyte-integrations/connectors/source-s3/source_s3/source_files_abstract/formats/parquet_spec.py
> +        description="If the source is a file path, use a memory map to read file, which can improve performance in some environments.",
Initially I copied all options as is. I don't see any  downsides for this enabling option and I removed it from the spec.

2021-08-30 13:53 UTC, antixar commented on airbyte-integrations/connectors/source-s3/source_s3/source_files_abstract/formats/parquet_spec.py
> +        description="Maximum number of records per batch. Batches may be smaller if there aren’t enough rows in the file.",
Added a comment

2021-08-30 13:57 UTC, antixar commented on airbyte-integrations/connectors/source-s3/source_s3/source_files_abstract/formats/parquet_spec.py
> +    )
You are right. For sync tasks this option is not relevant because all data is loaded consistency. Removed

2021-08-30 14:23 UTC, antixar commented on airbyte-integrations/connectors/source-s3/source_s3/source_files_abstract/formats/parquet_spec.py
> +        description="Perform multi-threaded column reads.",
it is default setting only. I'm not sure that users will be changed in the future. Removed

2021-08-30 14:25 UTC, antixar commented on airbyte-integrations/connectors/source-s3/source_s3/source_files_abstract/formats/parquet_spec.py
> +    )
I don't see cases when those options will be changed by someone.

2021-08-30 14:31 UTC, antixar commented on airbyte-integrations/connectors/source-s3/source_s3/source_files_abstract/formats/parquet_parser.py
> +            raise OSError("empty Parquet file")
A schema of Parquet files is fixed after adding of a first row. Thus a file without rows also doesn't have a schema. I added a test for this case.

2021-08-30 14:32 UTC, antixar commented on airbyte-integrations/connectors/source-s3/source_s3/source_files_abstract/formats/parquet_parser.py
> +        for num_row_group in num_row_groups:
Fixed

2021-08-30 14:33 UTC, antixar commented on airbyte-integrations/connectors/source-s3/source_s3/source_files_abstract/stream.py
> +        """Override this mapping where every key is equal  'filetype' and values are  corresponding  parser classes."""
Agree. Fixed

2021-08-30 14:36 UTC, antixar commented on airbyte-integrations/connectors/source-s3/unit_tests/test_fileformatparser.py
Renamed

2021-08-30 14:42 UTC, antixar commented on airbyte-integrations/connectors/source-s3/unit_tests/test_fileformatparser.py
> -class AbstractTestFileFormatParser(ABC):
Sure, this class `AbstractTestParser` (was renamed) is allocated into the separate file "unit_tests/abstract_test_parser.py" now

2021-08-30 14:43 UTC, antixar commented on docs/integrations/sources/s3.md
> +- `use_threads` : Perform multi-threaded column reads.
fixed

2021-08-31 12:45 UTC, Phlair approved these changes
Great, lgtm! One small note on `buffer_size` to make that more clear.

Due to the way we're iterating through individual files at the abstract-level, I anticipate issues with partitioned parquet datasets. I think we should make clear in the documentation that partitioned parquet datasets are unsupported for now. 
For more context, it should _work_ however the performance could be very bad + the columns used for partition would be missing from output (I think).

2021-08-31 13:45 UTC, antixar commented on airbyte-integrations/connectors/source-s3/source_s3/source_files_abstract/formats/parquet_spec.py
> +        description="Perform read buffering when deserializing individual column chunks. By default a file will be loaded fully to memory. This option can help to optimize a work with memory if your
added

2021-08-31 13:52 UTC, antixar commented
/test connector=connectors/source-s3

2021-08-31 14:14 UTC, antixar commented
/publish connector=connectors/source-cart

2021-08-31 14:15 UTC, antixar commented
/publish connector=connectors/source-s3

2021-09-03 11:10 UTC, antixar commented
/test connector=connectors/source-s3

2021-09-04 22:57 UTC, antixar commented
/test connector=connectors/source-s3

2021-09-04 23:16 UTC, antixar commented
/publish connector=connectors/source-s3

2021-09-04 23:40 UTC, merged