WIP: loopack_window_days parameter for incremental update
airbytehq/airbyte pull request #6017
Opened 2021-09-13 11:42 UTC by eliziario

## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

2021-09-14 15:12 UTC, keu commented on airbyte-cdk/python/CHANGELOG.md
> +Add field loopback_window_days to Stream
I think it is `lookback_window`

2021-09-14 15:16 UTC, keu requested changes
I'm not sure that this solves the problem in all sources because developers still need to update all sources and do this logic manually basically every time, is there maybe more common logic that we can re-use in CDK?

2021-09-27 17:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=6017) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=6017) before we can accept your contribution.<br/><hr/>**Marcos** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=6017) it.</sub>

2021-09-29 23:32 UTC, keu commented on airbyte-integrations/connectors/source-stripe/source_stripe/source.py
> +        incremental_args = {**args, "loopback_window_days": config.get("loopback_window_days"), "start_date": config["start_date"]}
```suggestion
        incremental_args = {**args, "lookback_window_days": config.get("loopback_window_days"), "start_date": config["start_date"]}
```

2021-09-29 23:32 UTC, keu commented on airbyte-integrations/connectors/source-stripe/source_stripe/spec.json
> +      "loopback_window_days": {
```suggestion
      "lookback_window_days": {
```

2021-09-29 23:33 UTC, keu commented on airbyte-integrations/connectors/source-stripe/source_stripe/streams.py
> +    def __init__(self, start_date: str, loopback_window_days: int, **kwargs):
```suggestion
    def __init__(self, start_date: str, lookback_window_days: int, **kwargs):
```

2021-09-29 23:34 UTC, keu requested changes
it is `looKback_window`

2021-09-30 07:27 UTC, keu approved these changes

2021-09-30 07:38 UTC, avida commented
/test connector=connectors/source-stripe

2021-10-01 23:36 UTC, sherifnada approved these changes

2021-10-01 23:36 UTC, sherifnada commented on airbyte-integrations/connectors/source-stripe/source_stripe/streams.py
> +    def __init__(self, start_date: str, lookback_window_days: int, **kwargs):
did mypy succeed on this? currently we are passing an optional in source.py

2021-10-01 23:36 UTC, sherifnada commented on airbyte-integrations/connectors/source-stripe/source_stripe/spec.json
> +        "description": "Lookback window in days for incremental streams"
this should have a minimum allowed value of 0 in the spec

2021-10-01 23:36 UTC, sherifnada commented on airbyte-integrations/connectors/source-stripe/source_stripe/spec.json
> +        "type": "integer",
```suggestion
        "title": "Lookback Window (in days)",
        "default": 0,
        "type": "integer",
```

2021-10-01 23:36 UTC, sherifnada commented on airbyte-integrations/connectors/source-stripe/source_stripe/spec.json
> +        "description": "Lookback window in days for incremental streams"
```suggestion
        "description": "When set, the connector will always reload data from the past N days, where N is the value set here. This is useful if your data is updated after creation."
```

2021-10-01 23:36 UTC, sherifnada commented
also @avida please remember to update the title according to the guidelines

2021-10-05 09:41 UTC, avida commented
/test connector=connectors/source-stripe

2021-10-05 09:43 UTC, avida commented
/publish connector=connectors/source-stripe

2021-10-05 09:53 UTC, merged