Upd connection check: verify all the site urls
airbytehq/airbyte pull request #6315
Opened 2021-09-20 12:42 UTC by gaart

## What
Fix #5691

## How
Verify connection for all the site urls

## Recommended reading order
1. `airbyte-integrations/connectors/source-google-search-console/source_google_search_console/source.py`

## Pre-merge Checklist
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

2021-09-20 12:43 UTC, gaart commented
/test connector=connectors/source-google-search-console

2021-09-20 14:26 UTC, gaart commented
/test connector=connectors/source-google-search-console

2021-09-21 10:41 UTC, gaart commented
/test connector=connectors/source-google-search-console

2021-09-21 10:56 UTC, gaart commented
/test connector=connectors/source-google-search-console

2021-09-21 11:31 UTC, gaart commented
/test connector=connectors/source-google-search-console

2021-09-21 11:42 UTC, gaart commented
/test connector=connectors/source-google-search-console

2021-09-21 12:48 UTC, keu approved these changes

2021-09-21 16:36 UTC, Phlair approved these changes

2021-09-21 16:50 UTC, sherifnada requested changes
@gaart just flagging request changes for visibility: can you update the PR title so it is clear what it's actually doing? "upd connection check" doesn't tell me what the actual change was. This is important for writing release logs -- we use commit messages to understand what's changing. 

A better title might be e.g: `Source Google Search Console: Verify access to all sites when performing connection check`

2021-09-21 16:50 UTC, sherifnada approved these changes
LGTM but please update the title according to the guidelines

2021-09-22 16:24 UTC, gaart commented
/publish connector=connectors/source-google-search-console

2021-09-23 03:58 UTC, merged