Yaroslav dudar/5937 spec linter
airbytehq/airbyte pull request #6366
Opened 2021-09-22 07:04 UTC by yaroslav-dudar

## What
Implemented linter script which parse spec file #5937 

## How to execute
1. `pip install pre-commit`
2. `pre-commit run spec-linter -a`

## How
1. read spec file and serialize it as python dict object
2. get properties field from spec object
3. check if all fields from `FIELDS_TO_CHECK` exist in each property
4. if field has oneOf attribute - fetch all subobjects and for each of them goto step (2)

## Recommended reading order
1. `.pre-commit-config.yaml`
2. `tools/bin/spec_linter.py`

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

2021-09-22 15:14 UTC, midavadim reviewed
According to the issue comment, we should check(and update) existing spec files. Has it been done already?

2021-09-22 15:40 UTC, yaroslav-dudar commented
> According to the issue comment, we should check(and update) existing spec files. Has it been done already?

at this moment script performs check only. I can't find requirement about update

2021-09-23 07:39 UTC, annalvova05 approved these changes

2021-09-24 09:52 UTC, antixar requested changes
Please add unit test set for local running

2021-09-24 09:52 UTC, antixar commented on tools/bin/spec_linter.py
> +            logging.error(f"\033[1m{spec_path}\033[0m: Couldn't find properties in connector spec.json")
Move this log printing to a separated function. It has same format.

2021-09-24 09:52 UTC, antixar commented on tools/bin/spec_linter.py
> +
I propose to use an aggregative approach: this logic has to validates all spec files and will print summary errors list if needed. For this every checking function should return an error or None. Using of the global value is not unclear

2021-09-24 09:52 UTC, antixar commented on tools/bin/spec_linter.py
> +            logging.error(f"\033[1m{spec_path}\033[0m: Couldn't find properties in connector spec.json")
Add a JSON exception too. A source JSON file can be broken

2021-09-24 09:52 UTC, antixar commented on tools/bin/spec_linter.py
> +    return []
I think all items of every "oneOf" have to be objects.  Can we return some error about unsupported types?

2021-09-27 15:51 UTC, antixar approved these changes
Great!

2021-09-27 17:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=6366) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=6366) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=6366) it.</sub>

2021-09-29 16:25 UTC, Phlair approved these changes
This is great!

Would be useful to have some brief docstrings on the non-trivial functions.

I don't think we have any nested `oneOf`s at the moment but if we wanted to handle that might want to look at making validate_schema recursive. Non-blocking though.

2021-09-29 16:25 UTC, Phlair commented on tools/git_hooks/spec_linter.py
> +    Validates single field objects and return errors if thay are exist
```suggestion
    Validates single field objects and return errors if they exist
```

2021-09-30 06:59 UTC, yaroslav-dudar commented
> This is great!
> 
> Would be useful to have some brief docstrings on the non-trivial functions.
> 
> I don't think we have any nested `oneOf`s at the moment but if we wanted to handle that might want to look at making validate_schema recursive. Non-blocking though.

If I understand you properly current implementation should handle nested oneofs. I added this test case https://github.com/airbytehq/airbyte/blob/yaroslav-dudar/5937-spec-linter/tools/git_hooks/tests/test_spec_linter.py#L141

2021-09-30 09:45 UTC, Phlair commented
Awesome, lgtm! Thanks

2021-09-30 09:46 UTC, Phlair approved these changes
Awesome, lgtm! Thanks

2021-09-30 10:01 UTC, merged