🐛 Source Facebook Marketing: estimate cost_per_estimated_ad_recallers
airbytehq/airbyte pull request #6463
Opened 2021-09-27 15:51 UTC by vitaliizazmic

## What
Sometimes records of AdsInsights streams don't contain cost_per_estimated_ad_recallers. It causes test failing.

## How
Metric cost_per_estimated_ad_recallers can be calculated based on spend and estimated_ad_recallers. Estimate metric if not presented in records.

## Pre-merge Checklist
 
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

2021-09-27 15:52 UTC, vitaliizazmic commented
/test connector=source-facebook-marketing

2021-09-27 17:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=6463) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=6463) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=6463) it.</sub>

2021-10-05 06:51 UTC, vitaliizazmic commented
/test connector=source-facebook-marketing

2021-10-05 08:29 UTC, eliziario approved these changes

2021-10-05 10:01 UTC, avida commented on airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/conftest.py
> +@pytest.fixture(name="ignored_fields")
Why do you need fixture for this? Fixture galore makes code vary hard to read, just use input .

2021-10-05 10:04 UTC, avida requested changes
Please bump SAT version, add docs  and change input format to more generic one, like here https://github.com/airbytehq/airbyte/issues/6433

2021-10-05 10:04 UTC, avida commented on airbyte-integrations/connectors/source-facebook-marketing/acceptance-test-config.yml
> +        "ads_insights_age_and_gender": [ "cost_per_estimated_ad_recallers", ]
This config is specific to your case, please make it more general, like described in this issue https://github.com/airbytehq/airbyte/issues/6433

2021-10-05 15:24 UTC, keu commented on airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/utils/common.py
> +def remove_ignored_fields(output: List[AirbyteMessage], ignored_fields: Mapping[str, List[str]]) -> List[Mapping[str, Any]]:
this function does too much and doesn't reflect its name.
how about have additional argument in `serialize` function:
```python
def serialize(value, exclude_fields=None):
...
```
then your code will be:
```python
serializer = partial(serialize, exclude_fields= ignored_fields)
output_diff = set(map(serializer, records_1)) - set(map(serializer, records_2))

```

2021-10-05 15:25 UTC, keu requested changes
see comments

2021-10-20 13:06 UTC, keu approved these changes

2021-10-20 13:37 UTC, avida requested changes
Please add some unittests to unit_tests/test_utils.py file.

2021-10-22 11:41 UTC, avida approved these changes
Nice, please bump version and publish SAT image

2021-11-01 14:35 UTC, vitaliizazmic commented
/test connector=bases/source-acceptance-test

2021-11-01 14:44 UTC, vitaliizazmic commented
/publish connector=bases/source-acceptance-test

2021-11-01 15:45 UTC, merged