🐛 Source S3 - memory & performance optimisations
airbytehq/airbyte pull request #6615
Opened 2021-10-01 15:10 UTC by Phlair

closes https://github.com/airbytehq/airbyte/issues/6606

I'm fairly confident I've been able to make some small but impactful improvements here:
- significantly reduced the memory footprint of the connector, meaning we shouldn't see that memory issue in the linked issue until the bucket is far more populated with files.
- made incremental reads only parse schemas of _new_ files rather than _all_ files, which should massively improve runtimes when number of files in bucket is anything non-trivial.

2021-10-01 15:23 UTC, Phlair commented
/test connector=connectors/source-s3

2021-10-03 22:23 UTC, antixar requested changes
I guess the main reason of performance issues is loading of file objects for filtering/sorting( by last_modified). 
```
    def last_modified(self) -> datetime:
        """
        Using decorator set up boto3 session & s3 resource.
        Note: slight nuance for grabbing this when we have no credentials.

        :return: last_modified property of the blob/file
        """
        bucket = self._provider.get("bucket")
        try:
            obj = self._boto_s3_resource.Object(bucket, self.url)
            return obj.last_modified
```
And thus your code tries to download all files (including not relevant for incremental mode). 
I propose to move this filtering/sorting logic to the bucket listing function:
```
   def _list_bucket(self, accept_key=lambda k: True) -> Iterator[str]:
       ....
                content = response["Contents"]
                # =======
                # content["LastModified"]
                # =======
                raise Exception(content)
            except KeyError:
                pass
       ....
```
This function should return relevant sorted filepath values only.

2021-10-16 08:44 UTC, tuliren reviewed
I'm afraid that this python code is too fancy for me to provide any useful review comments.

2021-10-19 09:56 UTC, ChristopheDuong approved these changes

2021-10-19 11:34 UTC, Phlair commented
/publish connector=connectors/source-s3

2021-10-19 13:33 UTC, Phlair commented
/test connector=connectors/source-s3

2021-10-19 15:50 UTC, merged