feat: sign out button for email verification page
airbytehq/airbyte pull request #6891
Opened 2021-10-08 11:00 UTC by isalikov

- `Sign out` button added to Email Verification page
![image](https://user-images.githubusercontent.com/36078770/136821807-ce52d52a-a7a9-4656-bd0f-487bc1ea44b6.png)

2021-10-08 16:40 UTC, jrhizor requested changes
Can we have another line like the "Didn't receive the email? Send it again" instead that says "Entered the wrong email address? Start over" which has the same logout behavior behind the scenes?

We don't want to encourage people to click this; it's a rare edge case and should be given a visual weight to match.

Also, to make the behavior more clear, we can change "Please click on the link to log in to your new Airbyte account." to "Please click on the link to access your new Airbyte account."

2021-10-11 16:04 UTC, jamakase approved these changes

2021-10-11 16:28 UTC, jrhizor approved these changes

2021-10-11 16:28 UTC, jrhizor commented
great!

2021-10-11 16:58 UTC, merged