Create a secure-only MongoDb destination
airbytehq/airbyte pull request #6945
Opened 2021-10-11 12:07 UTC by irynakruk

## What
We want to create secure-only versions of connectors that can be used in the Airbyte cloud. The idea is that these connectors inherently prevent certain insecure connections such as connecting to a database over the public internet without encryption.

## How
Created a new connector destination-mongodb-strict-encrypt based on the current connector, modified the connector's spec to hide any options which allow the user to disable TLS change the connector to enable TLS by default if the TLS option is not specified.

## Recommended reading order
1. `MongodbDestinationStrictEncrypt.java`
2. `tests `

## Pre-merge Checklist

<summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [ ] Documentation updated 
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] `docs/SUMMARY.md`
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [x] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>

2021-10-12 15:28 UTC, alexandr-shegeda approved these changes
LGTM

2021-10-13 16:37 UTC, tuliren requested changes

2021-10-18 16:33 UTC, tuliren approved these changes
@irynakruk, thank you for the updates.

Please make sure to follow and check off the `Pre-merge Checklist` to make sure the connector is properly published.

2021-10-19 12:21 UTC, irynakruk commented
> @irynakruk, thank you for the updates.
> 
> Please make sure to follow and check off the `Pre-merge Checklist` to make sure the connector is properly published.

@tuliren thanks, I've pushed nitpick commit and small fixes for tests and dependencies. Also, I've bumped version for `destination-mongodb`, as there was some changes as well. I've updated `Pre-merge Checklist`, last step is to publish two connectors.

2021-10-20 13:04 UTC, merged