🐛 Source Hubspot: Fix issue with getting 414 HTTP error for streams
airbytehq/airbyte pull request #6954
Opened 2021-10-11 15:52 UTC by yevhenii-ldv

## What
*resolves #3977 and #5835.*

## Pre-merge Checklist

#### Community member or Airbyter
   
- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

2021-10-12 06:27 UTC, htrueman approved these changes

2021-10-12 16:47 UTC, Zirochkaa approved these changes

2021-10-12 23:59 UTC, sherifnada requested changes
1. I think we should go with a character-length-based check to prevent this issue from happening again (what is the max length we can use?)
2. we should have very thorough unit tests around this functionality to ensure data integrity and correct pagination/merging records/making the correct requests/etc....

2021-10-21 11:20 UTC, yevhenii-ldv commented
/test connector=connectors/source-hubspot

2021-10-22 00:37 UTC, sherifnada reviewed
Looks great! 

I have one question about why we are changing schemas and the impact users should expect, but otherwise we should be ready to ship

2021-10-25 17:45 UTC, sherifnada approved these changes

2021-10-26 12:37 UTC, merged