🎉 New Source: Azure Table Storage
airbytehq/airbyte pull request #7095
Opened 2021-10-16 18:34 UTC by geekwhocodes

## What
- Add new source - Azure Table Storage
- Participating in hacktoberfest-2021 https://github.com/airbytehq/hacktoberfest-2021/issues/70

## How
This connector uses generic configured schema to support any table. Currently, it supports `full sync` only.

## Recommended reading order
1. readme.md
2. spec.json
3. source.py
4. reader.py
5. constants.py

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] `docs/SUMMARY.md`
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [x] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [x] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

2021-10-23 16:32 UTC, harshithmullapudi requested changes

2021-10-27 16:31 UTC, harshithmullapudi requested changes
Small comments otherwise LGTM. Once you are done with those I can publish this connector

2021-10-31 17:17 UTC, geekwhocodes commented
@harshithmullapudi I have made requested changes.

2021-11-01 17:54 UTC, harshithmullapudi approved these changes
LGTM

2021-11-01 17:54 UTC, harshithmullapudi commented on airbyte-integrations/connectors/source-azure-table/source_azure_table/reader.py
> +
Can you add more comments on this so that the functionality becomes more clear

2021-11-02 14:59 UTC, geekwhocodes commented
@harshithmullapudi I have made requested changes.

2021-11-10 12:56 UTC, geekwhocodes commented
@harshithmullapudi did you get a chance to look at this?

2021-11-14 19:33 UTC, harshithmullapudi commented
Hey @geekwhocodes thanks for the contribution. I have created a new branch out of this #7953 since there were some rebasing issues and thus closing this

2021-11-14 19:33 UTC, closed without merging

2021-11-15 08:08 UTC, geekwhocodes commented
Thank you @harshithmullapudi :)