🎉 Source Shopify: Add `FulfillmentOrders` and `Fulfillments` streams
airbytehq/airbyte pull request #7107
Opened 2021-10-18 05:11 UTC by yuhuishi-convect

## What
*Describe what the change is solving*
I am adding two new resources `FulfillmentOrders` and `Fulfillments` as new streams to Shopify connector.
These two streams are critical if downstream apps rely on the demands at the warehousing location level (compared to the normal definition of order).

Closes #7026 

Will land after #7063 

*It helps to add screenshots if it affects the frontend.*

## How
*Describe the solution*
* `FulfillmentOrders` stream is implemented as child stream of `Orders` - https://shopify.dev/api/admin-rest/2021-07/resources/fulfillmentorder#[get]/admin/api/2021-10/orders/{order_id}/fulfillment_orders.json
* `Fulfillments` stream is implemented as child stream of `Orders` - https://shopify.dev/api/admin-rest/2021-07/resources/fulfillment#[get]/admin/api/2021-10/orders/{order_id}/fulfillments.json

## Recommended reading order
1. `source.py`
2. `schema/fulfillment_orders.py`
3. `schema/fulfillments.py`

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

2021-10-18 23:14 UTC, yuhuishi-convect commented
<details>
<summary> Unittests </summary>

```
> Task :airbyte-integrations:connectors:source-shopify:unitTest
[python] .venv/bin/python -m pytest -s unit_tests --cov=./ --cov-config=/data/oss/airbyte/tools/python/.coveragerc --cov-report html --cov-report term
         ============================= test session starts ==============================
         platform linux -- Python 3.8.5, pytest-6.1.2, py-1.10.0, pluggy-0.13.1 -- /data/oss/airbyte/airbyte-integrations/connectors/source-shopify/.venv/bin/python
         cachedir: .pytest_cache
         rootdir: /data/oss/airbyte, configfile: pytest.ini
         plugins: timeout-1.4.2, sugar-0.9.4, requests-mock-1.9.3, cov-2.12.1
         collecting ... collected 18 items
         
         unit_tests/test_cached_stream_state.py::test_full_refresh[Sync Started] PASSED
         unit_tests/test_cached_stream_state.py::test_incremental_sync[Sync Started] PASSED
         unit_tests/test_cached_stream_state.py::test_incremental_sync[Sync in progress] PASSED
         unit_tests/test_control_rate_limit.py::test_with_unknown_load PASSED
         unit_tests/test_control_rate_limit.py::test_with_low_load PASSED
         unit_tests/test_control_rate_limit.py::test_with_mid_load PASSED
         unit_tests/test_control_rate_limit.py::test_with_high_load PASSED
         unit_tests/test_transform.py::test_enforcer_correct_type[transform_object0-schema0-checks0] PASSED
         unit_tests/test_transform.py::test_enforcer_correct_type[transform_object1-schema1-checks1] PASSED
         unit_tests/test_transform.py::test_enforcer_correct_type[transform_object2-schema2-checks2] PASSED
         unit_tests/test_transform.py::test_enforcer_correct_type[transform_object3-schema3-checks3] PASSED
         unit_tests/test_transform.py::test_enforcer_string_to_number[transform_object0-schema0-checks0] PASSED
         unit_tests/test_transform.py::test_enforcer_string_to_number[transform_object1-schema1-checks1] PASSED
         unit_tests/test_transform.py::test_enforcer_nested_object[transform_object0-schema0-checks0] PASSED
         unit_tests/test_transform.py::test_enforcer_nested_array[transform_object0-schema0-checks0] PASSED
         unit_tests/test_transform.py::test_enforcer_nested_array[transform_object1-schema1-checks1] PASSED
         unit_tests/test_transform.py::test_enforcer_string_to_number_in_array[transform_object0-schema0-checks0] PASSED
         unit_tests/unit_test.py::test_get_next_page_token PASSED
```

</details>

<details>
<summary> Integration tests </summary>

```
> Task :airbyte-integrations:connectors:source-shopify:sourceAcceptanceTest
============================= test session starts ==============================
platform linux -- Python 3.7.11, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /test_input
plugins: timeout-1.4.2, sugar-0.9.4
collected 18 items

test_core.py ..............F                                             [ 83%]
test_full_refresh.py .                                                   [ 88%]
test_incremental.py ..                                                   [100%]

=================================== FAILURES ===================================
_______________________ TestBasicRead.test_read[inputs0] _______________________

self = <source_acceptance_test.tests.test_core.TestBasicRead object at 0x7fd8f9be9e90>
connector_config = SecretDict(******)
configured_catalog = ConfiguredAirbyteCatalog(streams=[ConfiguredAirbyteStream(stream=AirbyteStream(name='customers', json_schema={'type': ...ental'>, cursor_field=['updated_at'], destination_sync_mode=<DestinationSyncMode.append: 'append'>, primary_key=None)])
inputs = BasicReadTestConfig(config_path='secrets/config.json', configured_catalog_path='integration_tests/configured_catalog.json', empty_streams=set(), expect_records=None, validate_schema=True, timeout_seconds=1200)
expected_records = []
docker_runner = <source_acceptance_test.utils.connector_runner.ConnectorRunner object at 0x7fd8f9be9210>
detailed_logger = <Logger detailed_logger /test_input/acceptance_tests_logs/test_core.py__TestBasicRead__test_read[inputs0].txt (DEBUG)>

    def test_read(
        self,
        connector_config,
        configured_catalog,
        inputs: BasicReadTestConfig,
        expected_records: List[AirbyteMessage],
        docker_runner: ConnectorRunner,
        detailed_logger,
    ):
        output = docker_runner.call_read(connector_config, configured_catalog)
        records = [message.record for message in filter_output(output, Type.RECORD)]
    
        assert records, "At least one record should be read using provided catalog"
    
        if inputs.validate_schema:
            self._validate_schema(records=records, configured_catalog=configured_catalog)
    
>       self._validate_empty_streams(records=records, configured_catalog=configured_catalog, allowed_empty_streams=inputs.empty_streams)

/usr/local/lib/python3.7/site-packages/source_acceptance_test/tests/test_core.py:264: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <source_acceptance_test.tests.test_core.TestBasicRead object at 0x7fd8f9be9e90>
records = [AirbyteRecordMessage(stream='customers', data={'id': 5239165812944, 'email': None, 'accepts_marketing': False, 'creat...': [], 'admin_graphql_api_id': 'gid://shopify/Customer/5239165976784'}, emitted_at=1634598381000, namespace=None), ...]
configured_catalog = ConfiguredAirbyteCatalog(streams=[ConfiguredAirbyteStream(stream=AirbyteStream(name='customers', json_schema={'type': ...ental'>, cursor_field=['updated_at'], destination_sync_mode=<DestinationSyncMode.append: 'append'>, primary_key=None)])
allowed_empty_streams = set()

    def _validate_empty_streams(self, records, configured_catalog, allowed_empty_streams):
        """
        Only certain streams allowed to be empty
        """
        counter = Counter(record.stream for record in records)
    
        all_streams = set(stream.stream.name for stream in configured_catalog.streams)
        streams_with_records = set(counter.keys())
        streams_without_records = all_streams - streams_with_records
    
        streams_without_records = streams_without_records - allowed_empty_streams
>       assert not streams_without_records, f"All streams should return some records, streams without records: {streams_without_records}"
E       AssertionError: All streams should return some records, streams without records: {'abandoned_checkouts', 'price_rules', 'metafields', 'discount_codes', 'orders_risks', 'orders_refunds'}
E       assert not {'abandoned_checkouts', 'discount_codes', 'metafields', 'orders_refunds', 'orders_risks', 'price_rules'}

/usr/local/lib/python3.7/site-packages/source_acceptance_test/tests/test_core.py:220: AssertionError
=========================== short test summary info ============================
FAILED test_core.py::TestBasicRead::test_read[inputs0] - AssertionError: All ...
=================== 1 failed, 17 passed in 159.19s (0:02:39) ===================
```
</details>

There is 1 error in integration tests that complain about not some streams are empty. I think that is because the development store I used is not fully populated with data.

2021-10-19 01:23 UTC, marcosmarxm requested changes
small changes! Overall LGTM!

2021-10-28 13:33 UTC, bazarnov requested changes
LGTM with small corrections. Please check the comments.

2021-11-01 16:46 UTC, harshithmullapudi commented
Hey can you update source-acceptance image `docker pull airbyte/source-acceptance-test:latest` and then try running integration tests

2021-11-01 18:02 UTC, yuhuishi-convect commented
> Hey can you update source-acceptance image `docker pull airbyte/source-acceptance-test:latest` and then try running integration tests

Hi @harshithmullapudi , the integration tests all passed using the latest image

<details>
<summary>log</summary>

```
gitpod /workspace/airbyte $ docker pull airbyte/source-acceptance-test:latest
latest: Pulling from airbyte/source-acceptance-test
Digest: sha256:da6127397903c921b6b08ca2a23ccdc862b1b972a7859ed5e4997b42f503343c
Status: Image is up to date for airbyte/source-acceptance-test:latest
docker.io/airbyte/source-acceptance-test:latest
gitpod /workspace/airbyte $ ./gradlew :airbyte-integrations:connectors:source-shopify:integrationTest
Picked up JAVA_TOOL_OPTIONS: -Xmx2576m
Building all of Airbyte.
/workspace/airbyte/airbyte-integrations/connectors

> Task :airbyte-integrations:bases:base-normalization:checkPython
Using python 3.8.12 from /workspace/airbyte/airbyte-integrations/bases/base-normalization/.venv (.venv/bin/python)
Using pip 21.1.3 from /workspace/airbyte/airbyte-integrations/bases/base-normalization/.venv/lib/python3.8/site-packages/pip (python 3.8)

> Task :airbyte-integrations:bases:airbyte-protocol:checkPython
Using python 3.8.12 from /workspace/airbyte/airbyte-integrations/bases/airbyte-protocol/.venv (.venv/bin/python)
Using pip 21.1.3 from /workspace/airbyte/airbyte-integrations/bases/airbyte-protocol/.venv/lib/python3.8/site-packages/pip (python 3.8)

> Task :airbyte-integrations:bases:base-python-test:checkPython
Using python 3.8.12 from /workspace/airbyte/airbyte-integrations/bases/base-python-test/.venv (.venv/bin/python)
Using pip 21.1.3 from /workspace/airbyte/airbyte-integrations/bases/base-python-test/.venv/lib/python3.8/site-packages/pip (python 3.8)

> Task :airbyte-integrations:connectors:source-shopify:checkPython
Using python 3.8.12 from /workspace/airbyte/airbyte-integrations/connectors/source-shopify/.venv (.venv/bin/python)
Using pip 21.1.3 from /workspace/airbyte/airbyte-integrations/connectors/source-shopify/.venv/lib/python3.8/site-packages/pip (python 3.8)

> Task :airbyte-integrations:bases:base-python:checkPython
Using python 3.8.12 from /workspace/airbyte/airbyte-integrations/bases/base-python/.venv (.venv/bin/python)
Using pip 21.1.3 from /workspace/airbyte/airbyte-integrations/bases/base-python/.venv/lib/python3.8/site-packages/pip (python 3.8)

> Task :airbyte-integrations:bases:base-singer:checkPython
Using python 3.8.12 from /workspace/airbyte/airbyte-integrations/bases/base-singer/.venv (.venv/bin/python)
Using pip 21.1.3 from /workspace/airbyte/airbyte-integrations/bases/base-singer/.venv/lib/python3.8/site-packages/pip (python 3.8)

> Task :airbyte-integrations:bases:source-acceptance-test:checkPython
Using python 3.8.12 from /workspace/airbyte/airbyte-integrations/bases/source-acceptance-test/.venv (.venv/bin/python)
Using pip 21.1.3 from /workspace/airbyte/airbyte-integrations/bases/source-acceptance-test/.venv/lib/python3.8/site-packages/pip (python 3.8)

> Task :airbyte-integrations:bases:base-normalization:pipInstall
[python] .venv/bin/python -m pip install pip==21.1.3
         Requirement already satisfied: pip==21.1.3 in ./.venv/lib/python3.8/site-packages (21.1.3)
         WARNING: You are using pip version 21.1.3; however, version 21.3.1 is available.
         You should consider upgrading via the '/workspace/airbyte/airbyte-integrations/bases/base-normalization/.venv/bin/python -m pip install --upgrade pip' command.
[python] .venv/bin/python -m pip list --format=columns
         Package           Version    Location
         ----------------- ---------- --------------------------------------------------------------
         airbyte-protocol  0.0.0      /workspace/airbyte/airbyte-integrations/bases/airbyte-protocol
         appdirs           1.4.4
         attrs             21.2.0
         black             20.8b1
         click             8.0.3
         coverage          6.0.2
         flake8            3.8.4
         iniconfig         1.1.1
         isort             5.6.4
         Jinja2            3.0.2
         MarkupSafe        2.0.1
         mccabe            0.6.1
         mypy              0.812
         mypy-extensions   0.4.3
         normalization     0.0.0
         packaging         21.0
         pathspec          0.9.0
         pip               21.1.3
         pluggy            0.13.1
         py                1.10.0
         pycodestyle       2.6.0
         pydantic          1.6.2
         pyflakes          2.2.0
         pyparsing         3.0.3
         pytest            6.1.2
         pytest-cov        2.12.1
         PyYAML            5.4
         regex             2021.10.23
         setuptools        57.4.0
         toml              0.10.2
         typed-ast         1.4.3
         typing-extensions 3.10.0.2
         wheel             0.37.0
         WARNING: You are using pip version 21.1.3; however, version 21.3.1 is available.
         You should consider upgrading via the '/workspace/airbyte/airbyte-integrations/bases/base-normalization/.venv/bin/python -m pip install --upgrade pip' command.

> Task :airbyte-integrations:bases:base-python-test:pipInstall
[python] .venv/bin/python -m pip install pip==21.1.3
         Requirement already satisfied: pip==21.1.3 in ./.venv/lib/python3.8/site-packages (21.1.3)
         WARNING: You are using pip version 21.1.3; however, version 21.3.1 is available.
         You should consider upgrading via the '/workspace/airbyte/airbyte-integrations/bases/base-python-test/.venv/bin/python -m pip install --upgrade pip' command.
[python] .venv/bin/python -m pip list --format=columns
         Package             Version    Location
         ------------------- ---------- --------------------------------------------------------------
         airbyte-protocol    0.0.0      /workspace/airbyte/airbyte-integrations/bases/airbyte-protocol
         airbyte-python-test 0.0.0
         appdirs             1.4.4
         attrs               21.2.0
         black               20.8b1
         click               8.0.3
         coverage            6.0.2
         flake8              3.8.4
         iniconfig           1.1.1
         isort               5.6.4
         mccabe              0.6.1
         mypy                0.812
         mypy-extensions     0.4.3
         packaging           21.0
         pathspec            0.9.0
         pip                 21.1.3
         pluggy              0.13.1
         py                  1.10.0
         pycodestyle         2.6.0
         pydantic            1.6.2
         pyflakes            2.2.0
         pyparsing           3.0.3
         pytest              6.1.2
         pytest-cov          2.12.1
         PyYAML              5.4
         regex               2021.10.23
         setuptools          57.4.0
         toml                0.10.2
         typed-ast           1.4.3
         typing-extensions   3.10.0.2
         wheel               0.37.0
         WARNING: You are using pip version 21.1.3; however, version 21.3.1 is available.
         You should consider upgrading via the '/workspace/airbyte/airbyte-integrations/bases/base-python-test/.venv/bin/python -m pip install --upgrade pip' command.

> Task :airbyte-integrations:bases:base-singer:pipInstall
[python] .venv/bin/python -m pip install pip==21.1.3
         Requirement already satisfied: pip==21.1.3 in ./.venv/lib/python3.8/site-packages (21.1.3)
         WARNING: You are using pip version 21.1.3; however, version 21.3.1 is available.
         You should consider upgrading via the '/workspace/airbyte/airbyte-integrations/bases/base-singer/.venv/bin/python -m pip install --upgrade pip' command.
[python] .venv/bin/python -m pip list --format=columns

Updating license header in: airbyte-integrations/bases/airbyte-protocol/airbyte_protocol/models/airbyte_protocol.py

> Task :airbyte-integrations:bases:base-python-test:isortFormat
[python] .venv/bin/python -m isort . --settings-file /workspace/airbyte/tools/pyt [...]

2021-11-01 18:28 UTC, bazarnov commented
LGTM, nicely done.

2021-11-04 17:27 UTC, yuhuishi-convect commented
> LGTM, nicely done.

Is there anything I can do to resolve the CI failure? I see one of the checks failed.

2021-11-05 23:53 UTC, marcosmarxm approved these changes
thanks @yuhuishi-convect sorry the delay in merging your contribution

2021-11-05 23:53 UTC, merged

2024-02-03 03:11 UTC, meyerovb commented
So this is why my backfill's gonna take an extra 43 hours...