4280/connectors guides
airbytehq/airbyte pull request #7312
Opened 2021-10-24 14:14 UTC by isalikov

- Documentation can be shown when user create source/destination if docs markdown are available
![image](https://user-images.githubusercontent.com/36078770/138598182-2f077f60-b8dc-40b4-997e-30f2bf0f6f32.png)

2021-10-26 00:05 UTC, jamakase requested changes

2021-11-01 19:08 UTC, Jamakase approved these changes

2021-11-02 22:49 UTC, jrhizor requested changes
This looks great when configuring the source and destination directly. 

There are two issues:
1. It's easy to get stuck. Would it be easy to make clicking outside of the doc pane (for example if someone clicked to go to settings) to close out the docs pane?
2. Accessing the guide during onboarding breaks the styling:
![Screen Shot 2021-11-02 at 3 46 46 PM](https://user-images.githubusercontent.com/120362/139962385-93a60f0f-8f83-42b3-b4b7-8a1a0c54609b.png)
It's also very easy to feel stuck in this situation because you have to horizontally scroll to see the `x`.

2021-11-04 23:50 UTC, Jamakase commented
> It's easy to get stuck. Would it be easy to make clicking outside of the doc pane 
@isalikov 
 this problem is still there. We need to add outside-click listener
 
 Also 1 more point - we need to display cross absolutely positioned, so if user scroll down - it is still visible.

2021-11-05 10:36 UTC, isalikov commented
- Click ouside docs panel close SideView
- Styles updated
![image](https://user-images.githubusercontent.com/36078770/140497853-1ef85cf5-3aae-4479-ab41-c556dc14e0d6.png)

2021-11-05 17:42 UTC, jrhizor requested changes
The panel looks and feels perfect now!

However, I think it's breaking the design in other places:
![Screen Shot 2021-11-05 at 10 41 00 AM](https://user-images.githubusercontent.com/120362/140554999-fdb439d0-9025-47d2-9ad2-dc825aacadb0.png)
![Screen Shot 2021-11-05 at 10 38 33 AM](https://user-images.githubusercontent.com/120362/140555008-3161e32b-92aa-48da-8b7a-3cc96f6b5ec0.png)

See random box in both of them and the misaligned buttons in the second.

2021-11-06 19:59 UTC, Jamakase requested changes

2021-11-06 19:59 UTC, Jamakase commented on airbyte-webapp/src/components/Markdown/Markdown.tsx
> +  * {
@isalikov aren't you changing here styles for all elements instead of Markdown specific ones?

2021-11-06 19:59 UTC, Jamakase commented on airbyte-webapp/src/components/Markdown/Markdown.tsx
> +  a {
react-markdown has `components` prop, I think we should reuse it and pass current stylings.

2021-11-06 21:13 UTC, Jamakase commented
> The panel looks and feels perfect now (both for onboarding and normal configuration)!
> 
> However, I think it's breaking the design in other places: ![Screen Shot 2021-11-05 at 10 41 00 AM](https://user-images.githubusercontent.com/120362/140554999-fdb439d0-9025-47d2-9ad2-dc825aacadb0.png) ![Screen Shot 2021-11-05 at 10 38 33 AM](https://user-images.githubusercontent.com/120362/140555008-3161e32b-92aa-48da-8b7a-3cc96f6b5ec0.png)
> 
> See random box in both of them and the misaligned buttons in the second.

Indeed. Applied qfix so we can merge it

2021-11-07 00:17 UTC, Jamakase approved these changes

2021-11-08 17:47 UTC, jrhizor approved these changes

2021-11-08 21:15 UTC, merged