🎉 New Source: Zenloop
airbytehq/airbyte pull request #7380
Opened 2021-10-26 07:16 UTC by AlexanderBatoulis

## What
* Added new source Zenloop
* Participating in hacktoberfest-2021 https://github.com/airbytehq/hacktoberfest-2021/issues/82

## How
Added four streams for this source
1. Surveys
2. Answers
3. Survey Groups
4. Answers Survey Groups

## Recommended reading order
1. bootstrap.md
2. spec.json
3. Schemas under schemas/*.json
4. source.py

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

## Test Runs
unit test
<img width="1431" alt="zenloop_unit_test" src="https://user-images.githubusercontent.com/85283328/138827149-012e3e53-9612-4132-8d36-f2efb5d820b2.png">

integration test
<img width="1431" alt="zenloop_acceptance_test" src="https://user-images.githubusercontent.com/85283328/138827050-037d908c-5d73-4613-a6db-a553e2d812d3.png">

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] `docs/SUMMARY.md`
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

2021-11-04 16:18 UTC, alafanechere commented
Hey @AlexanderBatoulis , could you please fill the checklist at the bottom of the PR's description so that we can check if it's ready for review? Thanks! 🙏

2021-11-04 17:41 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-zenloop/acceptance-test-config.yml
> +#        extra_records: yes
can you remove this?

2021-11-04 17:54 UTC, marcosmarxm requested changes
Thanks @AlexanderBatoulis small comment also can you run `./gradlew format`?

2021-11-08 16:22 UTC, AlexanderBatoulis commented
> Thanks @AlexanderBatoulis small comment also can you run `./gradlew format`?

done

2021-11-08 16:22 UTC, AlexanderBatoulis commented
> Hey @AlexanderBatoulis , could you please fill the checklist at the bottom of the PR's description so that we can check if it's ready for review? Thanks! 🙏

done

2021-11-15 16:21 UTC, marcosmarxm commented
Hello @AlexanderBatoulis ! Sorry to not finished your contribution before the date stipulated in the contest. All contributions made before 15-November are eligible to receive the award. We're trying to review your contribution as soon as possible.

2021-11-16 09:17 UTC, alafanechere requested changes
Thank you very much @AlexanderBatoulis for this contribution, I have some minor questions and suggestions that you'll find in my review comments.
In addition, we configured a sandbox account for Zenloop and I'm afraid that the integration tests are not passing when we fill the `public_hash_id` field. The `https://app.zenloop.com/settings/api` provides list of hash ids for surveys, but this value is reused to build requests to `survey_groups` endpoint in the `AnswersSurveyGroup` stream (`survey_groups/{self.public_hash_id}/answers`). It looks like the API expects survey group id that are different from the public hash id provided in the config and it leads to 404 error.
**TLDR: integration tests did not pass when setting `public_hash_id` to a valid value in our config.**

Could you also fix conflicts with master please? 🙏

2021-11-18 19:30 UTC, AlexanderBatoulis commented on airbyte-integrations/connectors/source-zenloop/source_zenloop/source.py
> +class ChildStreamMixin:
Set up of class to be consistent with [trello](https://github.com/airbytehq/airbyte/blob/f6d81ff8813b8bd1a5cd9923093d5472a8407d76/airbyte-integrations/connectors/source-trello/source_trello/source.py) and [onesignal](https://github.com/airbytehq/airbyte/blob/760f429959075605dbe25adeb8d29d9efff0cc7a/airbyte-integrations/connectors/source-onesignal/source_onesignal/streams.py) connectors.

2021-11-18 19:30 UTC, AlexanderBatoulis commented on airbyte-integrations/connectors/source-zenloop/source_zenloop/source.py
> +class Surveys(ZenloopStream):
Thanks for the suggestion, I added it to it

2021-11-18 19:33 UTC, AlexanderBatoulis commented
> Thank you very much @AlexanderBatoulis for this contribution, I have some minor questions and suggestions that you'll find in my review comments. In addition, we configured a sandbox account for Zenloop and I'm afraid that the integration tests are not passing when we fill the `public_hash_id` field. The `https://app.zenloop.com/settings/api` page provides list of hash ids for surveys, but this value is reused to build requests to `survey_groups` endpoint in the `AnswersSurveyGroup` stream (`survey_groups/{self.public_hash_id}/answers`). It looks like the API expects a survey group id that is different from the public hash id provided in the config (which is expected to be a _survey id_ and not a _survey group id_) and it leads to 404 error. **TLDR: integration tests did not pass when setting `public_hash_id` to a valid value in our config.**
> 
> Could you also fix conflicts with master please? 🙏

Hi @alafanechere,
Thank you very much for your thorough review! I resolved the not passing integration tests by adding another request parameter for survey_group_id. 
Would be great if you could take another look and let me know if there is anything outstanding.

Kind regards,
Alex

2021-11-19 08:20 UTC, alafanechere commented
HI @AlexanderBatoulis , thanks for your modifications, I'll go for another review.

2021-11-19 16:17 UTC, alafanechere requested changes
Hi @AlexanderBatoulis , I tried to run the acceptance tests but they are failing. Could you please make sure  the command runs flawlessly?
` ./gradlew :airbyte-integrations:connectors:source-zenloop:integrationTest

2021-11-21 11:27 UTC, AlexanderBatoulis commented
Hi @alafanechere, this should run fine now - missed to update setup.py

2021-11-22 13:58 UTC, alafanechere approved these changes
LGTM, I'm happy with the change you've made and successfully ran the acceptance tests!
Ready to merge 👏

2021-11-22 16:14 UTC, merged