🐛 Source Google Search Console: set default end_date param value
airbytehq/airbyte pull request #7431
Opened 2021-10-27 19:24 UTC by gaart

## What
Fixes #6697 
The API endpoint requires two mandatory parameters: a start date and an end date. The end date is not a required field on our side, and if not specified, the end point will return an error. So, we use some date in the future

## How
Add default value for the `end_date` param

## Pre-merge Checklist
   
- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated 
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

2021-10-28 12:52 UTC, eliziario submitted a review, later dismissed
Could you just give a quick explanation why adding a default end date fixes the issue?

2021-10-31 10:14 UTC, gaart commented
/test connector=connectors/source-google-search-console

2021-11-02 15:22 UTC, gaart commented on airbyte-integrations/connectors/source-google-search-console/source_google_search_console/source.py
> +            "end_date": config.get("end_date") or pendulum.now().add(years=2).to_date_string(),
Yes, we can move this logic somewhere inside.
As for the end date - we can use `today` as the end date if we bypass the testing issue

2021-11-15 05:17 UTC, Zirochkaa commented
/test connector=connectors/source-google-search-console

2021-11-15 05:26 UTC, Zirochkaa commented
/test connector=connectors/source-google-search-console

2021-11-15 06:27 UTC, Zirochkaa commented
/test connector=connectors/source-google-search-console

2021-11-16 17:21 UTC, Zirochkaa commented
/test connector=connectors/source-google-search-console

2021-11-16 20:46 UTC, Zirochkaa commented
Tests are failing because of memory issues on CI instance. I run tests locally few times and they were green.
![image](https://user-images.githubusercontent.com/19872253/142063029-ca58fa80-13be-41c2-b6ee-b555962b03e2.png)

2021-11-17 10:31 UTC, avida requested changes
Why you concluded it has memory issues? Couldnt find any clues in logs. If it failiing on CI/CD there is very high probablity it would fail on EC2 instance/ k8s pod where it being run. We have to investigate reason of fail. Reliability is top priority for us.

2021-11-17 10:52 UTC, Zirochkaa commented
> Why you concluded it has memory issues? Couldnt find any clues in logs. If it failiing on CI/CD there is very high probablity it would fail on EC2 instance/ k8s pod where it being run. We have to investigate reason of fail. Reliability is top priority for us.

Please, read the description of (#8038) ticket. I run tests locally like 5 times and each time they were green. I can't reproduce an error which may or may not occur on EC2 instance/ k8s pod. If it will occur we will fix it, but for now tests are green. I talket to the @sherifnada and he said that if tests are green locally then this PR can be merged. I created a separate issue (#8038) for deeper investigation of why tests on github are failing with `Process 'command 'docker'' finished with non-zero exit value 137` error but locally they are green.

2021-11-17 11:11 UTC, avida requested changes
Could you at least investigate if those fails was caused by this change or not? You trying to commit PR that never passed SAT without knowing root cause of that. Please follow that rule of [5 whys](https://en.wikipedia.org/wiki/Five_whys)

2021-11-17 11:58 UTC, Zirochkaa commented
> You trying to commit PR that never passed SAT

Wrong. In the message above I wrote that I run SAT locally for 6 times already and each time tests were green. I saved the result of each test run if you need any proof. So this PR passed SAT for a few times.


> Could you at least investigate if those fails was caused by this change or not?
Yes, I can revert changes made in this PR and run SAT again.

2021-11-17 12:13 UTC, keu commented
@Zirochkaa @avida if the current version has the same issue with tests I don't think it is related to changes in this PR, so we can give it a green light

2021-11-17 14:32 UTC, Zirochkaa commented
@keu @avida I run tests on master branch and 2 tests are failing because of Timeout:


`basic_read` with timuout for 300 seconds:
![image](https://user-images.githubusercontent.com/19872253/142219441-798c6500-bf0c-4ce1-bf8c-0c024c9375d9.png)


`full_refresh` with timeout for 1200 secinds:
![image](https://user-images.githubusercontent.com/19872253/142219562-0d7e028c-758e-45a4-86b1-961daa4b84da.png)



That's why I added `timeout_seconds: 3600` to `basic_read`, `full_refresh` and `incremental` tests.

Other tests were green.
![image](https://user-images.githubusercontent.com/19872253/142219865-c0a7ef4c-f392-4a40-82e2-0185bca8ff2a.png)

2021-11-17 15:17 UTC, keu commented
as explained in DMs between me, @avida and @Zirochkaa SAT reads all output from connector, if the output is too big, there might be a timeout, and if we increase the timeout, the whole dataset might not fit the memory limits. I proposed to use `_limit` parameter to read only a subset of the data from the stream

2021-11-17 15:29 UTC, Zirochkaa commented
/test connector=connectors/source-google-search-console

2021-11-17 16:18 UTC, Zirochkaa commented
/test connector=connectors/source-google-search-console

2021-11-25 07:36 UTC, Zirochkaa commented
/test connector=connectors/source-google-search-console

2021-11-25 07:56 UTC, Zirochkaa commented
/test connector=connectors/source-google-search-console

2021-11-26 16:20 UTC, Zirochkaa commented
/test connector=connectors/source-google-search-console

2021-11-26 16:31 UTC, avida approved these changes

2021-11-26 16:59 UTC, Zirochkaa commented
/publish connector=connectors/source-google-search-console

2021-11-26 17:25 UTC, merged