🎉 New Source: Outreach
airbytehq/airbyte pull request #7507
Opened 2021-11-01 02:25 UTC by lgomezm

## What
* Adding `Outreach` as new source. Fixes https://github.com/airbytehq/airbyte/issues/3627
* Includes a few streams to start with.

## How
* Implements OAuth authentication.
* Supports both full refresh and incremental syncs.
* Supported streams: `prospects`, `sequences`, `sequence_states`.
* New streams can be added easily.

## Recommended reading order
1. `spec.json`.
2. Schemas in `schemas/*.json`.
3. `source.py`

## Tests Run
### Integration tests
<img width="1197" alt="Screen Shot 2021-10-31 at 9 20 12 PM" src="https://user-images.githubusercontent.com/781929/139613002-ebed0a3a-3a0c-4001-9237-bc2595140fb0.png">
### Unit tests
<img width="1199" alt="Screen Shot 2021-10-31 at 9 23 01 PM" src="https://user-images.githubusercontent.com/781929/139613021-8745b8f0-4fca-4668-a5c6-09afb4e4c954.png">

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

2021-11-02 12:52 UTC, harshithmullapudi commented
Hey @lgomezm thanks for the contribution 🔥. Can you run `./gradlew format`

2021-11-02 12:58 UTC, harshithmullapudi requested changes
Small changes otherwise LGTM

2021-11-02 12:58 UTC, harshithmullapudi commented on airbyte-integrations/connectors/source-outreach/source_outreach/source.py
> +    cursor_field = "attributes/properties/updatedAt"
I think this is not needed as it is already declared in parent class

2021-11-02 12:58 UTC, harshithmullapudi commented on airbyte-integrations/connectors/source-outreach/source_outreach/source.py
> +    def next_page_token(self, response: requests.Response) -> Optional[Mapping[str, Any]]:
can you add documentation URL here

2021-11-02 12:58 UTC, harshithmullapudi commented on airbyte-integrations/connectors/source-outreach/source_outreach/source.py
> +class Sequences(IncrementalOutreachStream):
can you add documentation URL here for this stream

2021-11-02 12:58 UTC, harshithmullapudi commented on airbyte-integrations/connectors/source-outreach/source_outreach/source.py
> +class SequenceStates(IncrementalOutreachStream):
can you add documentation URL here for this stream

2021-11-02 12:58 UTC, harshithmullapudi commented on airbyte-integrations/connectors/source-outreach/source_outreach/source.py
> +            token_refresh_endpoint="https://api.outreach.io/oauth/token",
if this is constant can you declare a variable on the top and use it here

2021-11-02 17:40 UTC, lgomezm commented
Hi @harshithmullapudi. I've just addressed your comments. Please take a look again when you get a chance. Thanks for reviewing!

2021-11-09 11:52 UTC, harshithmullapudi approved these changes

2021-11-14 18:51 UTC, harshithmullapudi commented
Hey @lgomezm due to some restriction on Outreach end our credentials are returning 429 in later tests. Do you have some take on this ?

2021-11-14 21:57 UTC, lgomezm commented
> Hey @lgomezm due to some restriction on Outreach end our credentials are returning 429 in later tests. Do you have some take on this ?
Hi @harshithmullapudi. Yes, unfortunately it fails intermittently beacuse of `HTTP 429: Too many requests`. One work around I use to check failed scenarios is run separately those cases that failed because of that error, with something like `$ python -m pytest integration_tests -p integration_tests.acceptance -k 'test_two_sequential_reads'`.  That command  runs the test case called `test_two_sequential_reads`.

2021-11-15 16:22 UTC, marcosmarxm commented
Hello @lgomezm ! Sorry to not finished your contribution before the date stipulated in the contest. All contributions made before 15-November are eligible to receive the award. We're trying to review your contribution as soon as possible.

2021-11-23 05:03 UTC, merged