Add Gsheets setup guide
airbytehq/airbyte pull request #764
Opened 2020-10-30 21:50 UTC by sherifnada

2020-10-30 23:05 UTC, michel-tricot requested changes
I am super concerned about the complexity of enabling GG spreadsheet.

GG spreadsheet will most likely be synced by the least technical people and yet it seems to be the most complex one to configure.

Is this the only way? How are other services doing it?

2020-10-30 23:39 UTC, michel-tricot approved these changes
Looks good. but if we know a way to make the configuration actually user-friendly we should have a follow up on this work.

2020-10-30 23:55 UTC, sherifnada commented
Created an issue capturing the work needed to improve the auth flow https://github.com/airbytehq/airbyte/issues/766

2020-10-31 00:10 UTC, sherifnada commented on docs/SUMMARY.md
> +    * [Google Sheets](integrations/sources/google-sheets.md)
done

2020-10-31 00:11 UTC, merged