Custom auto-setup temporal docker image
airbytehq/airbyte pull request #7681
Opened 2021-11-05 18:24 UTC by benmoriceau

## What
Make the update of temporal possible.

## How
This is a custom auto-setup script for the temporal environment. Unfortunately there is no other way properly update the DB without copy pasting parts of the temporal auto-setup script. Ideally temporal would provide a dedicated container for it DB but it is not the case right now.

2021-11-05 18:27 UTC, benmoriceau commented
Moving it to draft, because I need to merge the removal of the docker-compose.

2021-11-06 00:41 UTC, cgardens reviewed
cool! we had talked about just dropping the db for now. i take it from this PR you think we should just go straight for the upgrade solution instead?

2021-11-08 21:56 UTC, benmoriceau commented
> t just dropping the db for now. i take it from this PR you think we should just go straight for the upgrade solution instead?

I don't think that dropping the DB will be needed here the upgrade will create the DB if needed. However the PR is affected by the revert of the removal of the docker-compose.

2021-11-08 23:52 UTC, benmoriceau commented
Manual test run:

2021-11-09 22:00 UTC, jrhizor requested changes
Added some comments.

My main worry is around upgrading to a new Temporal version after this. Do we need to update the update script itself to be able to do that? Is there a way to detect incompatibilities via automated testing?

2021-11-10 00:56 UTC, benmoriceau commented
I didn't want t o push. I put it back in draft.

2021-11-10 05:10 UTC, cgardens commented
Nice. Agreed with @jrhizor 's comments. As long as this is something we think is going to reasonable to maintain in future temporal versions, this seeems like a good approach.

2021-11-10 18:14 UTC, benmoriceau commented on airbyte-temporal/build.gradle
> +task copyScripts(type: Copy) {
The docker build task will copy the dockerfile to the `build/docker` folder so I need to copy the script in this folder too.

2021-11-10 18:18 UTC, benmoriceau commented on airbyte-temporal/scripts/update-and-start-temporal.sh
> +initEntryPoint() {
Done

2021-11-10 18:18 UTC, benmoriceau commented on docker-compose.yaml
> -      - 7233:7233
Done

2021-11-10 18:18 UTC, benmoriceau commented on docker-compose.yaml
> +    command: ./update-and-start-temporal.sh
Thanks, I have set it as an entry point.

2021-11-10 19:07 UTC, benmoriceau commented
> Added some comments.
> 
> My main worry is around upgrading to a new Temporal version after this. Do we need to update the update script itself to be able to do that? Is there a way to detect incompatibilities via automated testing?

I added a test, It is hacky and based on the fact that the docker compose up takes less than 1 minute.

2021-11-10 20:17 UTC, jrhizor approved these changes

2021-11-10 22:32 UTC, merged