:tada: New Source: Parcel Perform
airbytehq/airbyte pull request #7926
Opened 2021-11-12 19:50 UTC by apostoltego

## What
Source for Parcel Perform 
Related to this [issue](https://github.com/airbytehq/hacktoberfest-2021/issues/61) 
## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

2021-11-12 19:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=7926) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=7926) before we can accept your contribution.<br/><hr/>**Apostol** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=7926) it.</sub>

2021-11-12 20:00 UTC, apostoltego commented
Hey @avaidyanatha , @marcosmarxm there's some concerns with getting this connector live:

- I believe for the hackathon you needed sandbox account etc. I’ve spoken to parcelperform and they’ve generated one under our main account however this has an expiration date. Secondary to this is that you need real parcels (shipments) to track through this tool so even with a secondary account this becomes a bit of a problem in both generating data and somehow have a public set of creds (the shipments would be holding some recipients address etc)
- Tried getting the caching mechanism to work but could never actually figure out why when  use_cache = True the parent object gets called. In this case it was creating without state passed through which in turn triggers a sync from config’s start date.

2021-11-12 20:01 UTC, apostoltego commented
![Screenshot 2021-11-12 at 19 46 11](https://user-images.githubusercontent.com/16501677/141527654-c55694fa-0541-4805-829b-5c0d14ec673f.png)
Integration tests

2021-11-15 16:22 UTC, marcosmarxm commented
Hello @apostoltego ! Sorry to not finished your contribution before the date stipulated in the contest. All contributions made before 15-November are eligible to receive the award. We're trying to review your contribution as soon as possible.

2021-11-16 09:02 UTC, apostoltego commented
@marcosmarxm  Don't worry about it - still keen to get this one through. Especially with some guidance on the concerns raised in the first comment.

2021-11-18 15:40 UTC, harshithmullapudi commented
Hey @apostoltego can you move this PR out of Draft state when you are done with this work.

2021-11-18 17:29 UTC, apostoltego commented
hey @harshithmullapudi I've left in draft due to the concerns raised above but on my end there's no immediate next steps. Any chance you can review and suggest whether you'd like to implement caching or just proceed as is?

2021-11-19 19:36 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-parcel-perform/source_parcel_perform/source.py
> +    url_base = "https://api.parcelperform.com"
Add the url_base in ParcelSource

2021-11-19 19:40 UTC, marcosmarxm requested changes
See comments @apostoltego thanks for the contribution. I requested our team to get one sandbox account to test your contribution.

2021-11-19 19:40 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-parcel-perform/source_parcel_perform/source.py
> +        elif response.status_code == 404 and response.json()["api_response"] == "4041":
the code 4041 is correct? can you add a documentation explaining this?

2021-11-19 19:40 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-parcel-perform/source_parcel_perform/source.py
> +            return True, None
See other connectors `check_connection` function example. Most cases you need a try/except

2021-11-21 17:25 UTC, marcosmarxm commented
@apostoltego please sign the CLA

2021-11-23 11:51 UTC, apostoltego commented
@marcosmarxm  Thanks for the feedback. Your comments should be addressed. Regarding the CLA not sure why it says pending - when I click through it shows that I've signed it.

2021-11-25 10:47 UTC, alafanechere commented
Hi @apostoltego, could you set your PR as ready for review if you think you've made the requested changes. Moreover the CLA signature seems to remain pending. It looks like CLA assistant cannot match your username with a github user, could you please troubleshoot this with this [documentation](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user)?

2021-11-26 11:12 UTC, apostoltego commented
Done, thanks for the help @alafanechere

2021-11-26 12:17 UTC, karinakuz commented
Free Trial account is created (expiration date 2021-12-12), OAuth token is received, credentials are added to the LastPass with the name "Parcel Perform". APIs are tested for two streams: 
- Shipments List https://api.parcelperform.com/v5/shipment/list/?created_date_from=2021-11-01T10:30:00&created_date_to=2021-11-30T10:30:00&carrier_reference=usps
- Shipment Details https://api.parcelperform.com/v5/shipment/details/?shipment_id=shipment001&shipment_uuid=a0fe1b96-3932-4d91-b9b4-a7073c72236b

2021-11-29 06:12 UTC, harshithmullapudi requested changes

2021-11-29 06:12 UTC, harshithmullapudi commented on airbyte-integrations/connectors/source-parcel-perform/source_parcel_perform/schemas/shipments_details.json
> +}
can you add a new line ?

2021-11-29 06:12 UTC, harshithmullapudi commented on airbyte-integrations/connectors/source-parcel-perform/source_parcel_perform/source.py
> +
can you add link(in comments) to the api documentation for this stream ?

2021-11-29 06:12 UTC, harshithmullapudi commented on airbyte-integrations/connectors/source-parcel-perform/source_parcel_perform/source.py
> +class ParcelPerformStream(HttpStream, ABC):
can you add link(in comments) to the api documentation for this stream ?

2021-11-29 06:14 UTC, harshithmullapudi commented
Hey @apostoltego  can you run `./gradlew format` in the root airbyte folder. We have also got credentials so we are good to go. Thanks for your patience.

2021-12-01 10:12 UTC, alafanechere requested changes
Hi @apostoltego I want to give you a first review but I'd like the acceptance test to pass before: 
`./gradlew :airbyte-integrations:connectors:source-parcel-perform:integrationTest` must run without failures.

Here are the failures I encountered:
* Flake checks: You've some unused import
* Unit tests: the test declared in `airbyte-integrations/connectors/source-parcel-perform/unit_tests` are not passing, please make them pass or update them according to your connector logic
* Integration tests: 
  * connection test with `status == "failed"` should run with a valid config in term of schema but with wrong credentials in `integration_tests/invalid_config.json` the date is not valid according to you spec.
  * the `basic_read` is failing with multiple errors of this kind: 
 ```
Failed validating 'type' in schema['properties']['return_address']:
    {'type': ['null', 'string']}

On instance['return_address']:
    {'address_name': 'org-001',
     'city': 'Chiyoda-ku, Tokyo',
     'company': 'Warehouse Manufacturing Company',
     'country': 'Japan',
     'country_code': 'JP',
     'email': 'email@warehouse.com',
     'entity_reference': 's001-org-001',
     'first_name': '',
     'full': '7-30, Marunouchi 2-chome, #01-55, 100-6432, Chiyoda-ku, '
             'Tokyo, Kanto, Japan',
     'last_name': '',
     'line1': '7-30',
     'line2': 'Marunouchi 2-chome',
     'line3': '#01-55',
     'location_type': 'warehouse',
     'phone': '+81959820269',
     'postal_code': '100-6432',
     'region': 'Kanto',
     'salutation': '',
     'state_or_province': '',
     'tax_id': 'TXA51-31'}
```
Please update your configured catalog to handle these nested object type.

2022-01-27 22:36 UTC, marcosmarxm commented
@apostoltego  I'll close this due to inactivity. If you want to return this work you can reopen the PR.

2022-01-27 22:36 UTC, closed without merging