Plaid source update
airbytehq/airbyte pull request #7977
Opened 2021-11-15 13:32 UTC by firmbase-tal

## What
Reformatted plaid to be written in Python instead of Javascript: #3998
Added transaction functionality to the source.

## How

The new Python connector works with the Plaid API package to draw data, then extracts the relevant data to stream, and dumps it as messages.
Balance stream maintains data structure from previous connector version.

## Recommended reading order
Chef's choice. 😄 

## Pre-merge Checklist

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

2021-11-15 13:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=7977) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=7977) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=7977) it.</sub>

2021-11-18 09:35 UTC, alafanechere commented
Hi @firmbase-tal , thanks for this contribution! Could you please share evidence that acceptance tests are passing on your side?
Command to run from top level airbyte directory:
```sh
./gradlew :airbyte-integrations:connectors:source-plaid:integrationTest`
```
Please also run: 
```sh
./gradlew bash
```

2021-11-18 10:03 UTC, alafanechere requested changes
I made a first quick review of the core and my main concern is that I feel like the abstractions you defined thanks to `configs/PlaidStream/PlaidRequester` are a bit far-fetched. I'm not 100% sure of the interest of storing some streams configurations in an external json file. 
I think that you can make your connector more readable by having the following classes:

* `PlaidStream(Stream)`
* `BalanceStream(PlaidStream)`
* `IncrementalTransactionStream(PlaidStream)`

And IMO the `PlaidRequesters` method could be brought back to the child classes above.

Let me know what you think about this!

2021-11-23 15:05 UTC, alafanechere commented
Hi @firmbase-tal, are you still interested in moving this PR forward according to my review?

2021-12-01 10:15 UTC, alafanechere commented
I add the label blocked until the user reply the review.

2021-12-13 09:29 UTC, firmbase-tal commented
Yes, apologies for the delay, will handle the changes soon.

2021-12-23 21:31 UTC, hbd commented
Thanks for your work here @firmbase-tal. Let me know if I can help get this over the line.

2021-12-27 13:01 UTC, firmbase-tal commented on airbyte-integrations/connectors/source-plaid/acceptance-test-config.yml
> +  # TODO uncomment this block to specify that the tests should assert the connector outputs the records provided in the input file a file
> Hi @firmbase-tal , thanks for this contribution! Could you please share evidence that acceptance tests are passing on your side? Command to run from top level airbyte directory:
> 
> ```shell
> ./gradlew :airbyte-integrations:connectors:source-plaid:integrationTest
> ```
> 
> Please also run:
> 
> ```shell
> ./gradlew bash
> ```

```shell
./gradlew bash
```
This fails with error: `Task 'bash' not found in root project 'airbyte'.`
I'm unsure as to what went wrong there.

Also, where should I upload the files from the acceptance tests?

2021-12-27 13:02 UTC, firmbase-tal commented
I think I fixed everything for now, please let me know if further changes are necessary.

2021-12-27 18:23 UTC, alafanechere commented
Hi @firmbase-tal, thanks for the changes; I'll go for another review this week then! @hbd feel free to review too if you're familiar with Plaid 😄

2021-12-30 18:22 UTC, alafanechere commented on airbyte-integrations/connectors/source-plaid/acceptance-test-config.yml
> +  # TODO uncomment this block to specify that the tests should assert the connector outputs the records provided in the input file a file
Sorry it was a typo for my side I meant `./gradlew format`

2022-01-04 18:29 UTC, alafanechere commented
@firmbase-tal could you double-check that `docs/integrations/sources/plaid.md` is up to date? Especially the part about access token creation. I tried to renew the one we have but following the instructions led to an error and it seems not to correspond with the [online Plaid documentation](https://plaid.com/docs/api/tokens/)

2022-01-05 18:27 UTC, alafanechere commented
@firmbase-tal I allowed myself to make some changes to simplify the code.
Mainly:
* Schemas are usually declared in external json files.
* The `PlaidRequester` class and some abstraction logic looked redundant to me.

Let me know what you think about these.

2022-01-05 21:12 UTC, hbd reviewed
LGTM. I was able to build the image locally and, although I am not very familiar with the Plaid API, the spec looks good

2022-01-05 21:12 UTC, hbd commented on airbyte-integrations/connectors/source-plaid/source_plaid/source.py
> +from .plaid_requester import PlaidRequester
@jrhizor I think this needs to be removed as well if the `PlaidRequester` is going to be removed

2022-01-06 18:05 UTC, alafanechere approved these changes
I confirm acceptance tests are passing. I'm publishing this now.

2022-01-10 03:50 UTC, hbd commented
Just confirming that I ran latest locally and successfully synced Plaid Sandbox data.

2022-01-10 11:15 UTC, merged

2022-01-10 11:16 UTC, alafanechere commented
Thank you @hbd for testing and @firmbase-tal for your original contribution!