DBT project for Airbyte normalization
airbytehq/airbyte pull request #802
Opened 2020-11-03 15:53 UTC by ChristopheDuong

## What
To solve #782, let's make a prototype of conversion from json schemas to DBT models
(running first on BigQuery)

2020-11-04 16:45 UTC, cgardens commented on airbyte-integrations/bases/base-normalization/normalization/transform_catalog/transform.py
> +    return property_type == "integer" or "integer" in property_type
i think you'll need to add "number" to this as well. jsonschema can come as either integer or number

2020-11-04 16:45 UTC, cgardens commented on airbyte-integrations/bases/base-normalization/normalization/transform_catalog/transform.py
> +  --json json_blob \
my inclination would be to call this `--json-column`. that might be java speaking if you think it's more idiomatic in python to stick with one word that is less specific, than feel free to leave it as is.

2020-11-04 16:45 UTC, cgardens commented on airbyte-integrations/bases/base-normalization/normalization/transform_catalog/transform.py
> +        if "name" in obj:
in the airbyte catalog the `name` field is required. `stream` key isn't a thing. i think these may be artifacts of the jsonschema catalog?

2020-11-04 16:45 UTC, cgardens commented on airbyte-integrations/bases/base-normalization/normalization/transform_catalog/transform.py
> +        elif "schema" in obj:
same. airbyte catalog is json_schema not schema.

2020-11-06 00:27 UTC, jrhizor requested changes

2020-11-06 00:27 UTC, jrhizor commented on .gitignore
> +profiles.yml
do we expect `profiles.yml` to be in the `airbyte` git repo at all?

2020-11-06 00:27 UTC, jrhizor commented on .gitignore
> +airbyte-integrations/bases/base-normalization/dbt-project-template/logs/
Should these be in `airbyte-integrations/bases/base-normalization/dbt-project-template/.gitignore`?

Or maybe we could exclude everything like https://github.com/fishtown-analytics/dbt-utils/blob/master/.gitignore:
```
logs
models/generated
dbt_modules
```

2020-11-06 00:27 UTC, jrhizor commented on airbyte-integrations/bases/base-normalization/setup.py
> +    install_requires=["airbyte-protocol", "dbt>=0.18.1", "pyyaml"],
What's the benefit of allowing > versions of dbt? Shouldn't we bump the version to upgrade?

2020-11-06 00:27 UTC, jrhizor commented on airbyte-integrations/connectors/destination-bigquery/src/main/resources/spec.json
> +        "examples": ["false"]
This should either be removed or use the booleans as the examples instead of strings.

```
        "examples": [true, false]
```

2020-11-06 00:27 UTC, jrhizor commented on airbyte-integrations/bases/base-normalization/entrypoint.sh
>    dry-run)
What's the difference between dry run and run?

2020-11-06 00:27 UTC, jrhizor commented on airbyte-integrations/bases/base-normalization/integration_tests/one_recipe.json
> +  "url": "https://www.bbcgoodfood.com/recipes/2793/christmas-pie",
We should use non-copyrighted content for test cases.

2020-11-06 00:27 UTC, jrhizor commented on airbyte-integrations/bases/base-normalization/dbt-project-template/packages.yml
> +    revision: 0.6.2
nit: missing newline at end of file

2020-11-06 03:12 UTC, michel-tricot commented on airbyte-integrations/bases/base-normalization/Dockerfile
> +COPY dbt-project-template/macros ./dbt-template/macros
can you do 
```
COPY dbt-project-template/ ./dbt-template/
```
Instead?

2020-11-06 03:12 UTC, michel-tricot commented on build.gradle
> +        targetExclude "**/build/**/*", "**/.gradle/**/*", "**/.venv/**", "airbyte-integrations/bases/base-normalization/dbt-project-template/**/*"
If you merge master in your branch, I will be able to update this code to be working with the faster spotless

2020-11-06 15:23 UTC, ChristopheDuong commented
> What's the difference between dry run and run?

dry run is calling `dbt compile` vs run calling `dbt run`

Compiling is translating DBT SQL Models into the warehouse's SQL but doesn't actually run it against the warehouse so it does not perform any changes on the destination.

We can use that for syntax errors

2020-11-06 19:04 UTC, michel-tricot approved these changes

2020-11-06 19:04 UTC, michel-tricot commented on airbyte-integrations/connectors/destination-postgres/build.gradle
> +buildImage.dependsOn(':airbyte-integrations:bases:base-normalization:buildImage')
why do we need that?

2020-11-06 19:04 UTC, michel-tricot commented on airbyte-integrations/connectors/destination-bigquery/build.gradle
> +buildImage.dependsOn(':airbyte-integrations:bases:base-normalization:buildImage')
why do we need that?

2020-11-06 19:04 UTC, michel-tricot commented on airbyte-integrations/connectors/destination-snowflake/build.gradle
> +buildImage.dependsOn(':airbyte-integrations:bases:base-normalization:buildImage')
why do we need that?

2020-11-06 19:04 UTC, michel-tricot commented on airbyte-workers/src/main/java/io/airbyte/workers/normalization/DefaultNormalizationRunner.java
> +  public static final String NORMALIZATION_IMAGE_NAME = "airbyte/normalization:dev";
can you create an issue with the proper milestone so we fix that before releasing?

2020-11-06 19:04 UTC, michel-tricot commented on build.gradle
> +        'dbt-project-template/macros',
do you need the three? can't you just do `dbt-project-template/` ?

2020-11-06 21:01 UTC, jrhizor approved these changes

2020-11-06 22:02 UTC, merged