Source hubspot: add Feedback Submissions stream and update Ticket Pipelines stream
airbytehq/airbyte pull request #9081
Opened 2021-12-23 11:13 UTC by vladimir-remar

## What
Add Feedback Submissions as new stream and update/use the Ticket Pipelines stream.

## How
In Feedback Submissions  just add an entry into `client.py` in the Ticket Pipelines since it was not use at all, I updated the class and add an entry into `client.py`.

## 🚨 User Impact 🚨
Not really, because `ticket_pipelines` as I said i wasn't use.

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

2021-12-23 17:02 UTC, marcosmarxm commented
Looks good @vladimir-remar! thanks for your contribution, please bump the connector version in config files, docker and docs? See instructions [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

2021-12-23 21:28 UTC, marcosmarxm commented
Our integration account is returning 404 from the new endpoint. @vladimir-remar do you know how to give permission to v3?

2021-12-24 09:41 UTC, vladimir-remar commented
> Our integration account is returning 404 from the new endpoint. @vladimir-remar do you know how to give permission to v3?

Hello @marcosmarxm, certainly not, I get the api-key by an external agent, let me ask.

2022-01-17 10:23 UTC, vladimir-remar commented
Hello @marcosmarxm can you take at look on this?

2022-01-19 00:24 UTC, marcosmarxm commented
@vladimir-remar is it possible to you share the output from `./gradlew airbyte-integrations:connectors:source-hubspot:integrationTest`?

2022-01-19 02:03 UTC, marcosmarxm commented on airbyte-integrations/connectors/source-hubspot/integration_tests/abnormal_state.json
> +    "timestamp": "2221-10-12T13:37:56.412000+00:00"
```suggestion
    "updatedAt": "2221-10-12T13:37:56.412000+00:00"
```

2022-01-19 02:03 UTC, marcosmarxm requested changes
small comments after is ready to merge! please share the output from integration tests

2022-01-19 11:33 UTC, vladimir-remar commented
> @vladimir-remar is it possible to you share the output from `./gradlew airbyte-integrations:connectors:source-hubspot:integrationTest`?

Hi @marcosmarxm , I'm having problems with the tests, let me explain, I have 2 API-Keys, one for production and one without data, the problem is that if I use the prod API key the tests don't end because they reach the limit and end up giving a timeout, even with a recent `start_date`, on the other hand if I use the other API key they fail because there is certainly no data.
Attached files with errors.
[hubspot_tests_test_api_key.log](https://github.com/airbytehq/airbyte/files/7896669/hubspot_tests_test_api_key.log)
[huspot_tests_prod_api_key.log](https://github.com/airbytehq/airbyte/files/7896670/huspot_tests_prod_api_key.log)

2022-01-25 02:06 UTC, marcosmarxm approved these changes
thanks @vladimir-remar

2022-01-25 02:06 UTC, merged