fix for Source Amazon Seller Partner: only 100 orders are read
airbytehq/airbyte pull request #9115
Opened 2021-12-26 11:09 UTC by prudhvi85

## What
Amazon seller partner reads only 100 records and terminates.

## How
Next token is not in the root level of steam_data, it is nested in payload. Marketplace ids should be always part of the request. 

## 🚨 User Impact 🚨
No breaking changes

2021-12-26 11:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=9115) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=9115) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=9115) it.</sub>

2021-12-27 06:58 UTC, harshithmullapudi commented
Hey @prudhvi85 can you sign SLA?

2021-12-27 07:00 UTC, harshithmullapudi requested changes
https://docs.airbyte.io/connector-development#4.-publish-the-connector can you check these steps here

2021-12-27 07:00 UTC, harshithmullapudi commented on airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
> +        #if not next_page_token:
can we remove this line?

2021-12-27 07:56 UTC, prudhvi85 commented
> Hey @prudhvi85 can you sign Agreement?

Hey @harshithmullapudi   I did sign it. and rechecked it more than 10 times.  When I try to redo it again here is what it looks like

![image](https://user-images.githubusercontent.com/5214499/147449034-34a27d48-c747-43df-bd6f-087c70953607.png)

2021-12-27 08:08 UTC, prudhvi85 commented on airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
> +        #if not next_page_token:
Remove the commented if condition

2021-12-27 10:47 UTC, avida approved these changes

2021-12-27 18:05 UTC, alafanechere commented
Hi @prudhvi85, to make the CLA signature work, please make sure the commits you made are with the same email as the one you're using for GitHub. You committed with your address `agility.com,` and the screenshot you attached shows a Gmail address, so maybe your GitHub account is also registered with your Gmail address; this makes the CLA signature fails. 
If you're not eventually succeeding, I can still create a PR myself from your branch and merge, but it will be a pity because you won't be recorded as the contributor for this fix 😢  .  

We also need you to bump the connector version in the following file:
*  `airbyte-integrations/connectors/source-amazon-seller-partner/Dockerfile` 
* `airbyte-config/init/src/main/resources/seed/source_definitions.yaml`
* `airbyte-config/init/src/main/resources/config/STANDARD_SOURCE_DEFINITION/e55879a8-0ef8-4557-abcf-ab34c53ec460.json`
* +Update Changelog : `docs/integrations/sources/amazon-seller-partner.md`

2021-12-27 19:11 UTC, prudhvi85 commented
> 

Thank you for the suggeston. Signed the CLA successfully

2022-01-03 10:07 UTC, prudhvi85 commented
@harshithmullapudi  can you please check the changes and approve the pull request

2022-01-03 10:43 UTC, harshithmullapudi commented
Hey @prudhvi85 it looks good but I can see that there is something messed in the md file can you fix it?
https://github.com/prudhvi85/airbyte/blob/sp_api_fix/docs/integrations/sources/amazon-seller-partner.md

2022-01-03 10:44 UTC, harshithmullapudi commented
Can you also share screenshot for unit tests and integration tests ?

2022-01-03 11:03 UTC, prudhvi85 commented
> @harshithmullapudi can you please check the changes and approve the pull request

sure, I think it is due to my editor.

2022-01-03 14:19 UTC, prudhvi85 commented
> 
Hi @harshithmullapudi  

Last code on master is not functional.  I have tested the changed in the previous version it works fine. 

Error : 'Orders' object has no attribute 'marketplace_ids'"

my change is not related to marketplace_ids.

2022-01-03 18:16 UTC, alafanechere commented
@prudhvi85 and @harshithmullapudi I merged another contributor PR https://github.com/airbytehq/airbyte/pull/9212  with version `0.2.9`, please merge master and bump the version again 🙏 .

2022-01-03 19:18 UTC, prudhvi85 commented
> 
@alafanechere  the connector is not in working after I pulled the current version on master.  
In the previous versions python main.py read --config config.py --catalog catalog.json  used to work fine.  After this pull it failed with following error: 
'Orders' object has no attribute 'marketplace_ids'"
Even the integrations tests are failed.

2022-01-04 05:55 UTC, prudhvi85 commented
> 

Bumped version to 0.2.10.

2022-01-04 06:08 UTC, prudhvi85 commented
> Can you also share screenshot for unit tests and integration tests ?

@harshithmullapudi 
![image](https://user-images.githubusercontent.com/5214499/148016073-d758688d-8fef-4837-af93-a5c48aafd627.png)

2022-01-04 06:14 UTC, prudhvi85 commented
> Can you also share screenshot for unit tests and integration tests ?

![image](https://user-images.githubusercontent.com/5214499/148017072-f1409542-85df-4b44-bfdf-d5786dc550e5.png)

![image](https://user-images.githubusercontent.com/5214499/148017115-382b6748-b197-4214-8eeb-66d3495fe135.png)

2022-01-04 10:19 UTC, harshithmullapudi commented
LGTM @prudhvi85 I will publish it sometime in the evening today.

2022-01-04 10:33 UTC, harshithmullapudi commented
Hey, @prudhvi85 also need some help to understand when you say `The connector is not working`.

2022-01-04 11:39 UTC, prudhvi85 commented
> today
@harshithmullapudi  my bad there was a merge issue in my code. I fixed it. it's working fine now

2022-01-04 21:07 UTC, harshithmullapudi commented
Hey @prudhvi85 I have pulled your commits into #9294 as there was one more PR which got merged. I did this to avoid more back and forth and merge this quick. Closing this.

2022-01-04 21:07 UTC, closed without merging