🎉 Source Zendesk: sync rate improvement
airbytehq/airbyte pull request #9456
Opened 2022-01-12 22:28 UTC by htrueman

## What
Updated Source Zendesk request execution with future requests.

## How
Used requests-future library using FuturesSession, then processing them in batch.

## Recommended reading order
1. `streams.py`
2. `setup.py`

## 🚨 User Impact 🚨
It shouldn't change the UX.

## Pre-merge Checklist
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>

2022-01-14 15:17 UTC, sherifnada commented on airbyte-integrations/connectors/source-zendesk-support/source_zendesk_support/streams.py
> +    def read_records(
this is repeating the whole CDK method, can you add some context on why? ideally this should not be the case

2022-02-15 08:34 UTC, sergei-solonitcyn requested changes

2022-02-23 07:42 UTC, sergei-solonitcyn approved these changes

2022-02-28 19:39 UTC, htrueman commented
/test connector=connectors/source-zendesk-support

2022-02-28 22:18 UTC, htrueman commented
/test connector=connectors/source-zendesk-support

2022-02-28 22:41 UTC, merged

2022-02-28 22:43 UTC, htrueman commented
/publish connector=connectors/source-zendesk-support