🔧  Pinterest Schema updated
airbytehq/airbyte pull request #9537
Opened 2022-01-16 20:24 UTC by rfortmann-ewolff

## What
`Ad_id` and `Account_id` are non-existent in the destination (BigQuery). The schema has a typo for `ad_id` and `account_id`.

## How
The schemas have been updated.

2022-01-16 20:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=9537) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=9537) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=9537) it.</sub>

2022-01-18 03:25 UTC, marcosmarxm commented
@harshithmullapudi please review this PR.

2022-01-18 08:17 UTC, harshithmullapudi requested changes

2022-01-18 08:17 UTC, harshithmullapudi commented on airbyte-integrations/connectors/source-pinterest/source_pinterest/schemas/ad_account_analytics.json
> +}
can you add new line here

2022-01-18 08:17 UTC, harshithmullapudi commented on airbyte-integrations/connectors/source-pinterest/source_pinterest/schemas/ad_analytics.json
> +}
same ^ newline

2022-01-18 08:17 UTC, harshithmullapudi commented on airbyte-integrations/connectors/source-pinterest/source_pinterest/schemas/ad_group_analytics.json
> +}
same ^ newline

2022-01-18 08:17 UTC, harshithmullapudi commented on airbyte-integrations/connectors/source-pinterest/source_pinterest/schemas/campaign_analytics.json
> +}
same ^ newline

2022-01-18 08:19 UTC, harshithmullapudi commented
Hey @rfortmann-ewolff  https://docs.airbyte.com/connector-development#updating-an-existing-connector can you check this

2022-01-18 12:58 UTC, rfortmann-ewolff commented
> Hey @rfortmann-ewolff https://docs.airbyte.com/connector-development#updating-an-existing-connector can you check this

all tests pass:
- no new tests required
- no documentation update required

2022-01-20 05:29 UTC, harshithmullapudi commented
Hey, @rfortmann-ewolff can you bump the version as mentioned here https://docs.airbyte.com/connector-development#publishing-a-connector. Also can you share integration tests and unit tests screenshot

2022-01-28 13:03 UTC, harshithmullapudi commented
Hey @rfortmann-ewolff I tried running the sourceAcceptance tests and looks like they are failing 
<img width="1134" alt="Screenshot 2022-01-28 at 6 31 31 PM" src="https://user-images.githubusercontent.com/17528887/151551488-31e38fa2-118d-4b0e-a35b-2e95c871be7e.png">

1. docker pull airbyte/source-acceptance-test
2. ./gradlew :airbyte-integrations:connectors:source-pinterest:sourceAcceptanceTest

2022-01-31 15:04 UTC, rfortmann-ewolff commented
> Hey @rfortmann-ewolff I tried running the sourceAcceptance tests and looks like they are failing <img alt="Screenshot 2022-01-28 at 6 31 31 PM" width="1134" src="https://user-images.githubusercontent.com/17528887/151551488-31e38fa2-118d-4b0e-a35b-2e95c871be7e.png">
> 
> 1. docker pull airbyte/source-acceptance-test
> 2. ./gradlew :airbyte-integrations:connectors:source-pinterest:sourceAcceptanceTest

I cannot reproduce the failing test - it's failing because of this:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':airbyte-integrations:bases:airbyte-protocol:generateProtocolClassFiles'.
> Process 'command 'bin/generate-protocol-files.sh'' finished with non-zero exit value 1
```

So I guess, I'll just change the `AD_ACCOUNT_ID` type (and other similar changes in the schemas) to the origin.

2022-01-31 15:24 UTC, harshithmullapudi commented
You can rebase it with latest master first then

2022-02-01 09:31 UTC, rfortmann-ewolff commented
> You can rebase it with latest master first then

Even after the rebase, I still get the same error.

2022-02-01 10:28 UTC, rfortmann-ewolff commented
I only rebased on my fork and not on the origin master - my bad.

2022-02-01 16:07 UTC, rfortmann-ewolff commented
> You can rebase it with latest master first then
```
configured_catalog = ConfiguredAirbyteCatalog(streams=[ConfiguredAirbyteStream(stream=AirbyteStream(name='boards', json_schema={'$schema': ...l: 'incremental'>, cursor_field=None, destination_sync_mode=<DestinationSyncMode.append: 'append'>, primary_key=None)])
allowed_empty_streams = set()

    def _validate_empty_streams(self, records, configured_catalog, allowed_empty_streams):
        """
        Only certain streams allowed to be empty
        """
        counter = Counter(record.stream for record in records)

        all_streams = set(stream.stream.name for stream in configured_catalog.streams)
        streams_with_records = set(counter.keys())
        streams_without_records = all_streams - streams_with_records

        streams_without_records = streams_without_records - allowed_empty_streams
>       assert not streams_without_records, f"All streams should return some records, streams without records: {streams_without_records}"
E       AssertionError: All streams should return some records, streams without records: {'ad_group_analytics', 'board_section_pins', 'boards', 'board_pins', 'ad_account_analytics', 'campaign_analytics', 'board_sections'}
E       assert not {'ad_account_analytics', 'ad_group_analytics', 'board_pins', 'board_section_pins', 'board_sections', 'boards', ...}

/usr/local/lib/python3.7/site-packages/source_acceptance_test/tests/test_core.py:289: AssertionError
```
I don't understand the error that is meant here

2022-02-01 16:53 UTC, closed without merging

2022-02-01 16:56 UTC, rfortmann-ewolff commented
Even though the schema change seemed easy and should not have produced much errors, I had to close my PR as tests were impossible to reproduce.

2022-02-01 17:02 UTC, rfortmann-ewolff commented
If anyone wants to try to solve that schema change, here is where the typos take place:
https://github.com/airbytehq/airbyte/blob/98b5aabd187a7338e01114c373a397d3aae3590e/airbyte-integrations/connectors/source-pinterest/source_pinterest/schemas/ad_account_analytics.json#L9

https://github.com/airbytehq/airbyte/blob/98b5aabd187a7338e01114c373a397d3aae3590e/airbyte-integrations/connectors/source-pinterest/source_pinterest/schemas/ad_analytics.json#L9

https://github.com/airbytehq/airbyte/blob/98b5aabd187a7338e01114c373a397d3aae3590e/airbyte-integrations/connectors/source-pinterest/source_pinterest/schemas/ad_group_analytics.json#L9

https://github.com/airbytehq/airbyte/blob/98b5aabd187a7338e01114c373a397d3aae3590e/airbyte-integrations/connectors/source-pinterest/source_pinterest/schemas/campaign_analytics.json#L9