S3, GCS Destinations : Fix interface duplication
airbytehq/airbyte pull request #9577
Opened 2022-01-18 15:22 UTC by DoNotPanicUA

## What
#8894
Remove logical duplication from the writer interfaces.
Is blocked by #6063

## How
Create new generic interfaces at the bottom (S3 destination is the lowest level right now for writers). Remove duplication interfaces from the GCS destination.

## Recommended reading order
1. `x.java`
2. `y.python`

2022-01-21 12:02 UTC, alexandr-shegeda commented on airbyte-integrations/connectors/destination-snowflake/src/test/java/io/airbyte/integrations/destination/snowflake/SnowflakeDestinationTest.java
> +  //@Test
are you going to uncomment this test?

2022-01-21 13:18 UTC, mkhokh-33 requested changes

2022-01-21 13:18 UTC, mkhokh-33 commented on airbyte-integrations/connectors/destination-snowflake/src/test/java/io/airbyte/integrations/destination/snowflake/SnowflakeDestinationTest.java
> +  //@Test
please check do we need this test?

2022-01-21 13:20 UTC, mkhokh-33 requested changes

2022-01-21 13:20 UTC, mkhokh-33 commented on airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/writer/BaseS3Writer.java
>    public static final String DEFAULT_SUFFIX = "_0";
I guess we could change it to private as constant is used only inside this class :)

2022-01-24 11:18 UTC, alexandertsukanov approved these changes
No critical remarks from my side.

2022-01-24 13:22 UTC, DoNotPanicUA commented
/test connector=connectors/destination-s3

2022-01-24 13:22 UTC, DoNotPanicUA commented
/test connector=connectors/destination-gcs

2022-01-24 13:23 UTC, DoNotPanicUA commented
/test connector=connectors/destination-snowflake

2022-01-24 13:23 UTC, DoNotPanicUA commented
/test connector=connectors/destination-bigquery

2022-01-24 13:23 UTC, DoNotPanicUA commented
/test connector=connectors/destination-bigquery-denormalized

2022-01-24 14:01 UTC, DoNotPanicUA commented
/test connector=connectors/destination-s3

2022-01-24 14:01 UTC, DoNotPanicUA commented
/test connector=connectors/destination-gcs

2022-01-24 14:01 UTC, DoNotPanicUA commented
/test connector=connectors/destination-bigquery

2022-01-24 14:01 UTC, DoNotPanicUA commented
/test connector=connectors/destination-bigquery-denormalized

2022-01-24 14:01 UTC, DoNotPanicUA commented
/test connector=connectors/destination-snowflake

2022-01-24 20:16 UTC, mkhokh-33 approved these changes

2022-01-25 11:01 UTC, alexandr-shegeda approved these changes

2022-01-25 11:22 UTC, merged