Include DO one-click deployment option
airbytehq/airbyte pull request #9803
Opened 2022-01-26 00:09 UTC by rbalsick

Offer users the ability to one click deploy much more quickly on DO

## What
Updated description

## How
Offer users the ability to one-click deploy to DO

2022-01-26 00:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airbytehq/airbyte?pullRequest=9803) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=9803) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=9803) it.</sub>

2022-01-26 00:18 UTC, marcosmarxm requested changes
small suggestion, added @avaidyanatha and @harshithmullapudi to also review. thanks @rbalsick

2022-01-26 00:18 UTC, marcosmarxm commented on docs/deploying-airbyte/on-digitalocean-droplet.md
> +##### Alternatively, you can one-click deply Airbyte to DigitalOcean using their marketplace: https://cloud.digitalocean.com/droplets/new?onboarding_origin=marketplace&appId=95451155&image=airbyte&ut
```suggestion

Alternatively, you can [click here](https://cloud.digitalocean.com/droplets/new?onboarding_origin=marketplace&appId=95451155&image=airbyte&utm_source=deploying-airbyte_on-digitalocean-droplet) to one-click deploy Airbyte in DigitalOcean using their marketplace clicking here 
```

2022-01-27 22:43 UTC, marcosmarxm commented on docs/deploying-airbyte/on-digitalocean-droplet.md
> +##### Alternatively, you can one-click deply Airbyte to DigitalOcean using their marketplace: https://cloud.digitalocean.com/droplets/new?onboarding_origin=marketplace&appId=95451155&image=airbyte&ut
@rbalsick did you see my comment?

2022-01-27 23:47 UTC, rbalsick commented on docs/deploying-airbyte/on-digitalocean-droplet.md
> +##### Alternatively, you can one-click deply Airbyte to DigitalOcean using their marketplace: https://cloud.digitalocean.com/droplets/new?onboarding_origin=marketplace&appId=95451155&image=airbyte&ut
looks good

2022-01-28 05:59 UTC, harshithmullapudi approved these changes

2022-01-31 10:28 UTC, merged