🐛 CDK: fixing type errors
airbytehq/airbyte pull request #9926
Opened 2022-01-31 15:00 UTC by vitaliizazmic

## What
Running mypy airbyte_cdk returns 46 typing errors. Fixing the issues.
Closes #9500 

## How
Fixing part of the issues. Fixing part of the issues, e.g, module "json" is not valid as a type.

2022-02-01 07:22 UTC, sergei-solonitcyn approved these changes

2022-02-08 21:48 UTC, keu commented on airbyte-cdk/python/airbyte_cdk/sources/utils/schema_helpers.py
>                      pathes.add(path)
```suggestion
                    path_str = "/".join([p for p in path[:-1] if p not in ["properties", "oneOf"]])  # type: ignore
                    pathes.add(path_str)
```

2022-02-08 21:49 UTC, keu commented on airbyte-cdk/python/airbyte_cdk/sources/utils/schema_helpers.py
> +        return pathes  # type: ignore
```suggestion
        return pathes
```

2022-02-08 21:50 UTC, keu requested changes
see my comments

2022-02-10 08:00 UTC, sherifnada approved these changes

2022-02-12 02:30 UTC, keu requested changes
please remove all unnecessary mypy silencing directives

2022-02-14 06:39 UTC, vitaliizazmic commented
/publish-cdk dry-run=false

2022-02-14 07:24 UTC, merged